### ISSUE TITLE
Improve or revert two-step import process

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8596]
There have been quite a few discussions on the darktable IRC channel in the recent days about the new two-step import process, and the general opinion (with which I concur) seems to be that it is a worse solution than the "import files" and "import folder" buttons from previous versions. It has caused confusion and, especially when importing single files and entire folders, it is felt to be one click too many.

It has been improved recently, in that you can just press enter to Ok through the second dialog when importing a whole folder, but I don't think that helps much. I personally find it hard to do that without at least reviewing the contents of the second dialog, which slows my workflow.

I'm willing to be persuaded that the new way is better, or that it can be improved, but I thought it worth raising an issue so that the discussion can continue in the open.

**Comment by AxelG-DE** [comment]
I fully second @elstoc's opinion here.

pressing "enter" btw. eventually means moving your hand from mouse to keyboard, which is not ideal.

I'm also willing to be persuaded for the new way and also say, the former way worked well for me to import folders (which I generate with RapidPhotoDownloader) where the new dialogue first confuses me and ask me to click unnecessarily more than before, hence I'd rather opt for getting back what it was.

Many ppl know already, I will not be a very active discussion partner until moving home is completed, which I assume will be around autumn this year (quite some intensive renovations and afterwards relaxation is needed)

**Comment by elstoc** [comment]
I've raised #8517 and #8541 to try to improve the experience with the first dialog (to make it clear that you have to select a folder first) but I'm not sure either of them help much.

**Comment by jade-nl** [comment]
I second this request.

As it stands now I would like to see it reverted. I do realize that hard work went into it, but this one is a step back compared to the original situation.

Things that could be improved when this new one is going to stay:

**The first window**

*  Its there to select a directory/folder. Do not show files, greyed out or otherwise,
* Don't mix single click and double click to enter a directory folder,
* Make it obvious that the *open* button is already primed and just pressing enter is enough,

**The second window**

* Make it (more) obvious what is/isn't selected. It turns out that all files are selected by default, but that is not obvious at all.

**In general**

* Should there really be 2 separate windows for this process?

I'm not a coder, but I find it very hard to believe that this cannot be done in one. Be it a window that has 2 subwindows (have a look at the top part of the old version).

**Comment by AlicVB** [comment]
For me, the new way is *really* better, as it offers more fine tuning possibilities : 
- for the copy & import : there was no alternative before, except by abusing gphoto...
- For the import in place : I've always found very surprising and not intuitive at all that the "recursive" "jpeg only" and "lua filters" need to be set in the module before the import by expanding some hidden part of it. Althought I think it's ok for metadata which doesn't change in time, that's not the case for this options.

If users are really upset by this change (I understand the "1 more click") maybe we can add 2 "direct" buttons : "direct import file" and "direct import directory" that will do what was done before (with the lack of any finetuning)

Now, has @elstoc and @jade-nl have said, there's still rooms for improvement in current implementation, but that's more cosmetic than anything and doesn't mean we should drop @phweyland great work !

> I'm not a coder, but I find it very hard to believe that this cannot be done in one. Be it a window that has 2 subwindows (have a look at the top part of the old version).

This has already been discussed. The main problem is that gtk will remove that possibility soon (add custom widget inside their built-in dialogs). So we can't follow this way... and, of course, developing our own file selector will be a nightmare to maintain, esp. considering that we target 3 different OS...

**Comment by elstoc** [comment]
> for the copy & import : there was no alternative before, except by abusing gphoto...

Agreed, I think here we're mostly concerned with the "import in-place" functionality

> I've always found very surprising and not intuitive at all that the "recursive" "jpeg only" and "lua filters" need to be set in the module before the import by expanding some hidden part of it.

Well all that is a very recent change and I'm still not entirely convinced by that either. But that was also originally implemented via a two-step process.

> gtk will remove that possibility soon

I've had a look in the gtk repos and I can't imagine they're gonna bother deprecating much more stuff in Gtk3 now since Gtk4 has hit the mainstream (though obviously we can't be certain). So that's a larger discussion and at the moment Gtk4 upgrade is optional (plenty of apps are still on Gtk2).

Certainly adding the old behaviour back _as well_ is an option we could consider but I'd rather have one mechanism that works for everyone.

**Comment by jade-nl** [comment]
> If users are really upset by this change (I understand the "1 more click") maybe we can add 2 "direct" buttons : "direct import file" and "direct import directory" that will do what was done before

This might be the best solution yet; The "best" of both worlds if you like.

**Comment by phweyland** [comment]
There is a constraint in the current process which doesn't help to merge the 2 steps.
In the first step, one has to chose the starting (root) folder.
In the second step he looks at the images and selects them. Note that images in the child folders may be shown as well.
These are two different functions which may not be easy to merge. The hard point being to display child folders images and keep folder navigation together.

Currently filechooser is not flexible about the interaction one can have with the files (in the previous version only one thumbnail could be be shown at a time for example; one cannot preview any information about a selected file other that the ones provided natively by filechooser). Trying to be compatible with other OS will only turn things worse.

Creating an ad hoc filechooser to combine the 2 functions may be an option; still we would have to solve the difficulty above.

**Comment by elstoc** [comment]
I've also been trying to come up with alternative button descriptions to distinguish the types of import. Generally for most users I think the word import _implies_ copy so a different word for the non-copying one might be a good idea. The best I can come up with is "load". So, with the above proposal we might have (tooltips in brackets):

- load images (load existing image(s) into the database)
- load folder (load the contents of a folder into the database)
- advanced load (load images or folders into the database with extra dialogs to refine selection)
- import and load (copy images to a pre-defined location and provide dialogs to refine selection)

**Comment by TurboGit** [comment]
It is also really better the new way to me.

Of course it is one more click (or just enter) but it has many more features as outlined already. So the subject "improve or revert" should certainly be only improve but we don't want to revert the very good work. Also remember that in Gtk4 we won't be able to have specific options on dialog, that's partly why we have this intermediate dialog.

**Comment by AlicVB** [comment]
@elstoc : I can only trust you on the english part ;) That said, I would have put "copy and load" on the last item...
I would also put the 2 last items in first to emphasis that they are the "classic" way to import, and the 2 other "just" simplified actions.

The delicate point : what default settings for "load folder" ? I would say "non-recursive", "with jpeg", and "without lua filter"... but I bet that this specific point will be controversial, as everyone as it's own workflow...

**Comment by jenshannoschwalm** [comment]
Maybe there can be improvements but for me the new dialog is a big improvement in usability and for new users will be easier to understand. Just remember the bunch of sd-card issues ...

What's the problem with one click while importing will certainly take much longer :-)

**Comment by elstoc** [comment]
> what default settings for "load folder" ? I would say "non-recursive", "with jpeg", and "without lua filter"

I thought the first two used to be in the "parameters" section didn't they?

**Comment by bdemaistre** [comment]
I am using only "import in place" after having the file copied by RapidPhoto downloader, like AxelG-DE. I was also surprised with the 2nd window but after a few import sessions the experience is very positive :
- When I have something special to import i can set parameters accordingly before starting (for example a change in the default rating or specific keywords) and then I can select the files which are to be imported with these specifics in the 2nd window.
- When I have to import whole folders (usual case), I use a default preset for parameters and the list of files is already selected for me in the 2nd window with the number of files displayed next to the import-in-place button, it is a very good quick check before starting the import.
For me this added step is quite useful for example if I forgot to click on recursive when it is needed I see it right away and can correct in the same window !

Please keep the new dialog, it is really really good ! and I am not sure that added buttons will improve anything (each added button also add some visual and cognitive clutter).
Maybe it will be better to have a visual clue that the import in-place button is the default action in the 2nd window ? Or maybe just adding  a tooltip ('click or press ENTER') when hoovering on the button ?

**Comment by AlicVB** [comment]
> I thought the first two used to be in the "parameters" section didn't they?

I've just checked, and you're right for the first one : jpeg only is still params section... @phweyland : I'm not sure this is intentional, but that's strange to have the same settings in 2 places... are they synchronized ? I would have say that this settings should have moved inside the dialog...

**Comment by phweyland** [comment]
> I'm not sure this is intentional,

You are right. This is redundant. As included in the 3 dialogs (in-place, copy and import and import from camera), it should be removed from import module params. 
I'll do it.

**Comment by quovadit** [comment]
I really love the new import process by @phweyland, it's a massive improvement!
The fact that even Bruce Williams suggests to use rapid photo downloader shows, that dt was not able to cover the import-process.
Now it's possible to copy and import within darktable for all usecases (not only from camera), which is awesome.

And I think the new buttons 'import in place' and 'copy and import' make it very clear that import does not copy files.
So please don't change the buttons again!


But I agree, that it would be even better to have all the functionality in one dialog.

If it's not possible to add custom widgets in gtk dialogs, we have to include a folder-selection to the second dialog.

I don't think this would be a nightmare to maintain, because we "only" need folder-selection which should be similar to the folder-tree in 'collect images'.

If we would add a list of mounted devices and remember the last x used folders in a drop down, we would have something like this:

![image](https://user-images.githubusercontent.com/5677563/113515772-ce9ce380-9576-11eb-98fc-a7edce7719a1.png)
(file browser from rawtherapee combined with current darktable-dialog)

**Comment by elstoc** [comment]
> But I agree, that it would be even better to have all the functionality in one dialog

If you can find a reasonable cross-platform way to do this I'm all for it

**Comment by AlicVB** [comment]
> I don't think this would be a nightmare to maintain, because we "only" need folder-selection which should be similar to the folder-tree in 'collect images'.

Sadly, collect is a completely different thing, as it doesn't have to deal with folder list at OS level, but just read the folders in the database as string and do some magics to recreate the tree.
But, as @elstoc , if there's a reasonable way to do it  for all the OS, that would be great !

**Comment by elstoc** [comment]
Well if rawtherapee does it we probably could steal some code from there - that's supposed to be cross-platform too isn't it?

**Comment by quovadit** [comment]
> I have idiosyncratic folder/file naming conventions

then maybe we should try to support those instead of duplicating functions with a 'simple import'


> rawtherapee ... is supposed to be cross-platform too isn't it?

yes, it is cross-platform, but it's c++
(https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/filepanel.cc)

**Comment by elstoc** [comment]
> then maybe we should try to support those instead of duplicating functions with a 'simple import'

No. I prefer to sort out my images before importing them.

**Comment by todd-prior** [comment]
While I understand it now, briefly when I started to use DT I was confused. Far too many software programs use import to mean a physical action on a file so you have import and copy which for some could be confused with move and copy. I think the term index or catalogue or term that defines that the import action is merely creating a database entry vs and action that performs a physical location change or copy would be the most clear way to do it. For me I would use load to simulate the memory option for the library...so basically using DT to open images for editing with no interaction with the database and then maybe load with index and finally copy with index or something along those lines.....having said that I can use the current version as is without any issues for me.....

**Comment by aurelienpierre** [comment]
Just now, I wanted to import one single image from my `Downloads` directory. I couldn't. @elstoc just told me I had to select the folder first, then narrow it down to the desired image at step 2. Let's face it : I would never have dared importing a full download directory of shit and nothing tells me in there that I have to wait for stage 2 to be able to excerpt a file from the folder.

I have nothing against inventing stuff and redesigning shit, but folder/file selection is really not the place to be clever in 2021. At very least, we should have a quick way to select a file.

**Comment by elstoc** [comment]
It's not the extra click for me so much as the cognitive load of realising that it's a two step process, trusting that the second step will allow you to do more (you will have the chance to review this order before you complete your purchase) and then I still feel the need to review the second screen even though I know I can just click enter to ignore it. It just feels like an interruption to the mental flow, but, except for reintroducing the old options in addition, I don't know of an easy alternative.

**Comment by phweyland** [comment]
> a full download directory of shit
> redesigning shit

the unsurpassable horizon of shit... 


>  It just feels like an interruption to the mental flow, but, except for reintroducing the old options in addition, I don't know of an easy alternative.

It is possible to reintroduce the old code, but the above arguments may not be worth the corresponding 500+ lines of code.
I think the following should be possible and not too heavy:
In the first level filechooser dialog (of [import in-place]) we could let select one or several images or a folder. We would have 4 buttons:
 - open (selected folder): continue the navigation under filechooser.
 - import (selected images or folder): import (with no other control) the selected images or the selected folder (but taking in account recursive and ignore jpeg flags)
 - import dialog (or whatever better naming): open the current 2nd stage on the selected folder. 
 - cancel
 
Today it is still possible to move the module parameters expander to a second stage dialog tab. But with any of the above changes we would have to keep the parameters where they are (and duplicate ignore jpeg and recursive flags, which is not an issue).

**Comment by quovadit** [comment]
Having 4 buttons in the first dialog would make it even worse for me, because I have no idea what to choose.

Why not just allow selecting files or folders in the first dialog and keep the process as is for now?

(still I think we should try to create the one-step-process including the folder-selection illustrated [above](https://github.com/darktable-org/darktable/issues/8596#issuecomment-813065519))

**Comment by TurboGit** [comment]
So, what about another design.
1. Use the new dialog first.
2. As for the export module or Lut3D one, have a top entry to select the directory. This fire up the Gtk+ selection dialog.
3. Keep under a button the last 20 selected directories for quick access.
4. Use the new dialog as it is today to select single images, see thumb... 
5. When all ok click import.

**Comment by elstoc** [comment]
I think we might be able to build a single-window solution with some combination of what @TurboGit and @quovadit have suggested. I suspect that the main issue with building a cross-platform file browser is the top level (drives/devices on Windows vs mounted folders on Linux - not sure about Mac). Once you've selected a "top level" directory, building a navigable folder tree from that root should be fairly easy. 

So we add a second (left-hand) pane to the new dialog with a button at the top to choose the "base" folder and a selectable folder tree beneath it (something like @quovadit's screenshot). The last selected base folder and the last selected folder in the tree are stored and used for default values the next time the user enters the screen.

I have almost all of my photos as single subdirectories in my "home/photos" directory (with maybe some others in home/downloads). If, for example, I selected my home directory as the "base" folder I would probably never need to change it again and it would always be a two click operation for me. Most of the time the file tree would always be expanded to show all of my photo subdirectories, then I would just need to select another subdirectory and click "import".

**Comment by quovadit** [comment]
great solution @elstoc

**Comment by phweyland** [comment]
> great solution @elstoc

Agreed. A bit more work but sounds great indeed.

**Comment by elstoc** [comment]
Note the "we" though :)

I'm pretty sure conceptually that it should be possible. Not sure I know how right now though.

**Comment by AlicVB** [comment]
@elstoc : I quite like your proposal too. The only difficult point I think is how to "explain" that notion of "base folder" visually for beginners (we have to keep in mind that this step is the first one)
I think we can follow @quovadit screenshots with a 2 lists folder selection. The first one for "places", with "root", "home", ... and a button to add special places (linked to the classic gtkfilechooser). and the second one for the tree of subdirs of the selected "place"

For the implementation, as @elstoc has said, the crucial point is this "places". For the subdir tree, I think we can be good with "already cross-platform" gtk libs (or maybe glib) Maybe we can do the linux version first with all the code in one place, so it's easy to add other OS versions with ifdef and ask for the devs on those OS to help us...

**Comment by elstoc** [comment]
> The only difficult point I think is how to "explain" that notion of "base folder" visually for beginners (we have to keep in mind that this step is the first one)

Presumably we can start with a default of the user's home or pictures directory - iirc we have stuff like that around anyway.

> For the implementation, as @elstoc has said, the crucial point is this "places"

I think we want to use as much of the built-in Gtk stuff as possible here to ease the cross-platform issues. Ideally all of our functionality starts off with a "directory" that has been selected using a Gtk file chooser. Then, as you say, the tree should be easy.

**Comment by RawConvert** [comment]
My 2p worth... I've built dt master this morning, saw the new import options and thought "Oh no, what's happening here..."
Then I searched and found this issue.  Please bear in mind the less sophisticated users like me!  Skimming the above makes me think it's all too complicated!  FOSS should not = "Frequently Overcomplicates Ordinary Scenarios" !
Here's a suggestion:  Have an "Import method" setting in prefs where you choose between "simple" and "expert/advanced".
The simple journey then let's you choose between a) importing one or more files, which of course you have to choose, or b) importing a folder (with or without jpegs).  You are protected from all stuff about copy/load/programmatically rename/move images to some other place etc.
Expert mode gives you the full flexibility to do all the clever operations for users who are happy to invest time understanding what's on offer and how best to use it.
Perhaps ask the pixls.us forum what they think?

**Comment by RawConvert** [comment]
A further point, previously I've been in the habit of loading an individual raw like this: Ctrl-C copy the raw in the desktop file manager (which I always have open anyway); then click "image..." under "import" of course; Ctrl-V, Enter, raw now opened in darktable.
This is useful, perhaps lots of people do this, however you can't as things stand, it wants a folder.

**Comment by quovadit** [comment]
what about just drag&drop from file manager to darktable?
or rightclick in file manager - open with - darktable

**Comment by RawConvert** [comment]
I'm using Ubuntu.  Drag & drop onto lighttable doesn't work.  (Older dt, not today's)
Right click ("open with") doesn't give me dt as an option.
Do those work on windows?

**Comment by phweyland** [comment]
> > great solution @elstoc
> 
> Agreed. A bit more work but sounds great indeed.

On the way.
![image](https://user-images.githubusercontent.com/23012047/115264254-83eda080-a10c-11eb-9e3d-479b70309b88.png)
