### ISSUE TITLE
darktable wont quit if .jpg|.xmp  are unopenable ( no premission rwx=0000 )

### ISSUE THREAD

**Issue by UsefGeorge** [darktable-org/darktable#8598]
place some pics in a directory
chmod 0000 *
run darktable (3.4.1)
import the directory
get errors about not being able to open files for reading ( no permissions )
close darktable
( now just wait, and wait, and wait, and ...... ) 

___________________________________________________________________
fedora linux 33
darktable build with src rpm.

Other things go wrong before you try/give up to close up.
like 
[New LWP 555353]

(darktable:555157): GLib-GObject-WARNING **: 17:24:11.713: invalid unclassed pointer in cast to 'GtkDarktableExpander'

** (darktable:555157): CRITICAL **: 17:24:11.713: dtgtk_expander_get_expanded: assertion 'DTGTK_IS_EXPANDER(expander)' failed
[LWP 555353 exited]

**Comment by jade-nl** [comment]
Confirmed: darktable does have issues when it encounters permission problems and this isn't limited to the above *chmod 000* example.

Files with different user/group are shown as skull(s), but dt hangs after encountering them.

I.e:

Do the following in a directory/folder that normally works:
`sudo chown other:user somefile.x.nef`

Import that directory: dt hangs

**Comment by UsefGeorge** [comment]
there seems to be other issues. 
darktable will import just the **names** of the files it cant open
darktable wont be able to display the (protected) file, and issues that BLOCK picture.
Whats also interesting is that the file info is also created, but those value are mostly 0/null.
BUT if you give darktable READ PERMISSION, darktable will read in the file(s). It just **wont _update_ the missing file info** alt all.
so i get funny values

aperture f/0.0
exposure 1/inf
iso 0
focal length 0mm

Probably also funny values for picture dimensions. does not darktable need accurate dimensions to work properly?

**Comment by jade-nl** [comment]
This is still an issue.

darktable encountering permission problems hangs it. This is true for the main program  and also darktable-generate-cache. Have not tried any of the other ones.

Please fix this.
