### ISSUE TITLE
How to select the default bayer demosaicer

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#8600]
**The problem**
For bayer raw files the default demosaicer is PPG for performance and historical reasons. We have RCD in dt 3.6 which is comparably fast both on cpu and cl code paths and gives much better output for almost all images.

**Possible Solutions**
1. We expect the user to define camera specific demosaicer presets - a generic preset would require the demosaicer module to check for bayer vs fuji files which it does not atm.
2. We define RCD as the default demosaicer for bayer raws.
3. We define RCD as the default demosaicer for bayer raws only in non "performance over quality" settings as at least on machines with clang compilers and no cl available RCD is slower.

Before i am going in any pr i would like to hear your opinion about this.

**Comment by TurboGit** [comment]
I would vote for 2 or 3. But for proper decision I suppose some timing will be good to have.

- how slower it is with GPU
- how slower it is with CPU only

Also are we really confident that it gives always better output ?

**Comment by jenshannoschwalm** [comment]
Timings on my system after switching to constant cpu/gpu clock rate
```
[hanno@fedora-w580 ~]$ darktable -d demosaic --disable-opencl
 [demosaic] process CPU `AMaZE' did 44.80mpix, 0.4968 secs (6.4805 CPU), 90.18 pix/us
 [demosaic] process CPU `VNG4' did 44.80mpix, 0.1058 secs (1.2391 CPU), 423.57 pix/us
 [demosaic] process CPU `RCD' did 44.80mpix, 0.1603 secs (2.2086 CPU), 279.53 pix/us
 [demosaic] process CPU `PPG' did 44.80mpix, 0.2988 secs (3.2840 CPU), 149.92 pix/us
 [demosaic] process CPU `AMaZE' did 44.80mpix, 0.4777 secs (6.5639 CPU), 93.79 pix/us
 [demosaic] process CPU `VNG4' did 44.80mpix, 0.1099 secs (1.2294 CPU), 407.61 pix/us
 [demosaic] process CPU `RCD' did 44.80mpix, 0.1378 secs (1.7907 CPU), 325.05 pix/us
 [demosaic] process CPU `PPG' did 44.80mpix, 0.2874 secs (3.0826 CPU), 155.87 pix/us
 [demosaic] process CPU `AMaZE' did 44.80mpix, 0.4714 secs (6.0297 CPU), 95.04 pix/us
 [demosaic] process CPU `VNG4' did 44.80mpix, 0.1134 secs (1.2687 CPU), 394.92 pix/us
 [demosaic] process CPU `RCD' did 44.80mpix, 0.1368 secs (1.8464 CPU), 327.60 pix/us
[hanno@fedora-w580 ~]$ darktable -d demosaic
 [demosaic] process GPU `RCD' did 44.80mpix, 0.0740 secs (0.0527 CPU), 605.07 pix/us
 [demosaic] process GPU `PPG' did 44.80mpix, 0.0402 secs (0.0362 CPU), 1114.30 pix/us
 [demosaic] process CPU `AMaZE' did 44.80mpix, 0.4615 secs (6.3123 CPU), 97.09 pix/us
 [demosaic] process GPU `VNG4' did 44.80mpix, 0.1341 secs (0.1342 CPU), 334.08 pix/us
 [demosaic] process GPU `RCD' did 44.80mpix, 0.0708 secs (0.0555 CPU), 633.21 pix/us
 [demosaic] process GPU `PPG' did 44.80mpix, 0.0393 secs (0.0353 CPU), 1139.52 pix/us
 [demosaic] process CPU `AMaZE' did 44.80mpix, 0.4760 secs (6.5360 CPU), 94.13 pix/us
 [demosaic] process GPU `VNG4' did 44.80mpix, 0.1354 secs (0.1340 CPU), 330.95 pix/us
 [demosaic] process GPU `RCD' did 44.80mpix, 0.0695 secs (0.0575 CPU), 644.33 pix/us
[hanno@fedora-w580 ~]$ 
```
About the quality; definitely yes. En par with AMaZE as also reported for other apps.

**Comment by jenshannoschwalm** [comment]
There has already been some docs added about selection and performance of the demosaicers.

**Comment by TurboGit** [comment]
So basically on CPU RCD is 2x faster and on GPU 2x slower. Yet the GPU version is 2nd faster amongst all demosaic algo and seems fast enough. So, with better quality I would opt for option 2.

Let's see if other agree with that. Thanks for the detailed info.

**Comment by ralfbrown** [comment]
Just did a quick CPU-only test with one Nikon D7200 .nef on a 32-core Threadripper (no OpenCL here).  Average over 4 runs is ~195pix/us for PPG, ~275 for AMAZE, ~320 for RCD, and >550 for VNG4.  Among these algorithms, PPG gets the least parallelism out of the available cores....

**Comment by jenshannoschwalm** [comment]
gcc or clang?

**Comment by jenshannoschwalm** [comment]
At least for rcd and amaze the performance depends a lot on the tile size depending on cache architecture and ramspeed.

Unfortunately selecting that at runtime gives a very bad penalty.

**Comment by ralfbrown** [comment]
> gcc or clang?

GCC 8.4

**Comment by jenshannoschwalm** [comment]
Ping @elstoc 

I think just this needs to be changed in the manual.

1. PPG used to be darktables default demosaicer, it has been replaced by RCD as it often faster and always gives better results.

ok?

**Comment by elstoc** [comment]
Yep. I added a documentation-pending tag to the PR - I think that's all that needs to be changed, unless you also want to change the default demosaicer for the darkroom preview as well (which we should maybe consider doing).

**Comment by jenshannoschwalm** [comment]
> default demosaicer for the darkroom preview

In fact that was also in the merged pr :-)

**Comment by elstoc** [comment]
> In fact that was also in the merged pr :-)

Are you sure? I've just rebuilt master and it still shows PPG as default:

![Screenshot_2021-04-06_15-30-14](https://user-images.githubusercontent.com/9555491/113727407-0332ab80-96ed-11eb-89cf-574392e42cea.png)

**Comment by jenshannoschwalm** [comment]
Arrgh, i missed that in the preferences. Will do, also in the configure section.
