### ISSUE TITLE
Duplicate creation after re-opening collection starts numbering over at 01

### ISSUE THREAD

**Issue by billmartz** [darktable-org/darktable#8604]
**Describe the bug/issue**
When I work on a Play Raw, I download the raw into a directory and all the posters' sidecars. I then create duplicates to load all the sidecars into, plus some extra duplicates to play with. After loading all the sidecars and doing my own editing of a duplicate, I might go to another collection. Later, if I return to the first collection and try to create an additional duplicate, dt will create a duplicate starting with 01, and put that into the directory the original 01 file was in. If I immediately remove the new 01 from dt, the original sidecar will reappear in the directory. Trying a different approach, I might try to duplicate the highest numbered duplicate, say, 08. Instead of making an 09, dt will make an 02, if, for instance, I've already removed an 01.

To get around this problem, because I have been experiencing it for quite awhile, including with 3.4, I have been making copies of an unaltered duplicate in the directory, say, 08, and renaming it 09. I would make as many copies as desired this way and re-import the folder. 

Starting with darktable-3.5.0+1567, and using import in-place, dt no longer imports the new duplicates. It doesn't seem to see them.

What I expect to happen, and used to happen, is new duplicates would be created with a version number one higher than the existing highest one.

This should be reproducible by anyone by following the above steps, since it has been a frequent and now default experience for me. Edit: Just imported from a different old directory and created duplicates without problem. This is the first time after several failed attempts with other directories.

**Platform**

* darktable version : darktable-3.5.0+1567~g4e6781e2d-win64
* OS                : Windows 10 Pro
* Memory            :  32 GB RAM
* Graphics card     :  NVIDIA GeForce GTX 1070 Driver version: 457.30
* OpenCL : Installed and activated

**Comment by elstoc** [comment]
@phweyland this might be related to the new import-in-place functionality. Please can you take a look.

**Comment by billmartz** [comment]
Is there an explanation somewhere of what that is? What I would do to check it? Also, what copy in-place is?

**Comment by billmartz** [comment]
I just tried copying and renumbering the copy and importing, and dt imported the new copy. So, it does work, but not on every old directory. I will try going back to the directories I have had trouble with, removing all duplicates, and importing the directory again.

**Comment by phweyland** [comment]
> this might be related to the new import-in-place functionality. Please can you take a look.

I don't see how this can be related ... the core functions, _image_import_internal() and _image_read_duplicates(), have not changed.
The problem seems to occur when creating a new duplicate if I'm not mistaken.
