### ISSUE TITLE
development - mask manager: grp functionality crashes darktable -> clang issue (bisected)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#8606]
**Describe the bug**

When trying to access the options window in the *grp <module_name>* section of the mask manager, darktable crashes.

**To Reproduce**

0. Build darktable using clang,
1. Open image in darkroom,
2. activate any mask capable module,
3. select *drawn mask*,
4. add a circle (and/or ellipse and/or path). Any size, any place,
5. go to the *mask manager* module,
6. expand the *grp <module_name>* section so that *circle #1* shows up,
7. right click on *circle #1*,
8. darktable just crashed

**Expected behaviour**

Being able to use the options that are part of that section / darktable not to crash.

The above does not happen when darktable is build using gcc.

**Screenshot/Video**

https://user-images.githubusercontent.com/56407344/113505688-fddc3200-952f-11eb-9ac8-7034fd9faf1a.mp4

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.9)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : **!! clang 10.0.1 !!!**
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 0.27.3
* Sqlite        : 3.27.2
* Optimization  : None

**Hardware**

* CPU              : AMD Ryzen 5 3600 6-Core Processor
* GPU              : GeForce RTX 2060 SUPER 7979 MiB
* Memory           : 32 Gb + 15 Gb Swap

**Additional context**

* Reproducible when building with gcc : **!! NO !!**
* Reproducible with other version(s)       : **No** tried 3.4.0 and 3.4.1 those are gcc build version though
* Reproducible with clean config directory : **Yes**
* Reproducible after removing xmp file     : **Yes**
* Reproducible after removing luarc  : **Yes**

Crash dump file:  [darktable_bt_P1O900.txt](https://github.com/darktable-org/darktable/files/6254346/darktable_bt_P1O900.txt)

_EDIT: Realized that my 3.4.0 and 3.4.1 version are gcc builds, not clang build. Changed text to reflect that._

**Comment by jade-nl** [comment]
This issue might be rather old.

I do not use this functionality too often (understatement) and have no idea when the last good commit was done.

Tried to backtrack and am now at a point that my current database cannot be loaded by the older dt version (tried this 95258fb40). This is where I stop, so no bisect.

**Comment by jade-nl** [comment]
Although I'm using the latest stable Debian version, I just upgraded clang (et al) to the latest version via a backported repo.

End result is the same: darktable crashes.

**Comment by jade-nl** [comment]
I just build the following darktable version using clang and the official stable _darktable-x.y.z.tar.xz_ packages . Here are the results:

* dt 3.2.1 - *OK* This version works as expected. No crashes using the grp <module_name> section,
* dt 3.4.0 - *OK* Also works as expected.
* dt 3.4.1 - *OK* No crashes.

Just to make sure it was actually build using clang:

```
$ strings /home/jade/.local/dt.341/bin/darktable | egrep -i "gcc|clang"
Debian clang version 10.0.1-++20210313014605+ef32c611aa21-1~exp1~20210313125208.190
Debian clang version 10.0.1-++20210313014605+ef32c611aa21-1~exp1~20210313125208.190
```

This points to a problem in the development version.

**Comment by jade-nl** [comment]
Set up a separate environment to bisect this one:

```
$ git bisect bad
6727436a851b39f33cec42b1c5ef87d21bb9945c is the first bad commit
commit 6727436a851b39f33cec42b1c5ef87d21bb9945c
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Mon Mar 1 20:00:13 2021 -0500

    fix additional leaks of gtk_tree_selection_get_selected_rows return value

:040000 040000 fc735586dcd0e798a2850487b6678a60f098868a bfc924d1fea09fa4456c15e5544d08a9aa76470a M  src
```

ping @ralfbrown

**Comment by ralfbrown** [comment]
I'll take a look, but can't promise to get to it before the weekend.

**Comment by jade-nl** [comment]
No need to hurry: Not many users use clang to build to my knowledge and I do not use this specific mask module very often. I can always build a gcc version if I really, really need it :-)

**Comment by jade-nl** [comment]
@ralfbrown : Fixed, thanks!
