### ISSUE TITLE
Editing style with multiple instances of module loses instance

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#8610]
**Describe the bug/issue**
lighttable -> _styles_ -> _edit_ -> _update_ corrupts style if multiple instances are selected for update

**To Reproduce**
1. Open an image
2. Apply 2 instances of a module (I used contrast EQ / atrous with the built-in _clarity_ and _deblur: large blur, strength 3_ presets). Name the instances (I used the names 'clarity' and 'deblur).
3. From the history stack, create a style with the 2 module instances.
4. In lighttable, export the preset to a dtstyle file.
5. With the same image selected as the one from which the style was created, click _edit_ in the lighttable's _styles_ menu.
6. Select the module instances to _update_ the style.
![image](https://user-images.githubusercontent.com/3177739/113522130-7bd72200-959e-11eb-89c7-433706ae2e88.png)
7. Export the updated style.
8. Edit the style again. It'll show the same module instance twice:
![image](https://user-images.githubusercontent.com/3177739/113522184-d2dcf700-959e-11eb-9579-fccf0b4a8e78.png)
9. Apply the updated style to an image.

**Expected behavior**
1. Exported files are identical (2 instances of the module with the same sets of settings)
2. After-update version of the style is the same as the one original one.

My exported dtstyles before/after the update are at https://tech.kovacs-telekes.org/files/2021-04-04-style-with-multiple-instances-of-module/clarity-plus-deblur.zip

Might be related to #7581? Though, for me, creating the style works; it's the update that's broken.

**Which commit introduced the error**
Went back to 3.4.1, the problem is present.  Then to 3.0.2, still present. Maybe this never worked?

**Platform**
* darktable version : 3.5.0+1560~g1eb0866d0
* OS                : Linux, kernel 5.8.0-48-generic
* Linux - Distro    : e.g. Ubuntu 20.10
* Memory            : 64 GB
* Graphics card     : NVidia 1060/6GB
* Graphics driver   : 450.102.04-0ubuntu0.20.10.1
* OpenCL installed  : nvidia-opencl-dev: 11.0.3-1ubuntu1, ocl-icd-libopencl1: 2.2.12-4
* OpenCL activated  : yes
* Xorg              : 1:7.7+19ubuntu15    
* Desktop           : KDE   5.74.0
* GTK+              :  3.24.23
* gcc               : 10.2.0-1ubuntu1
* cflags            : ?
* CMAKE_BUILD_TYPE  : ?

I just use the supplied build.sh without any magic.

**Additional context**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by TurboGit** [comment]
Point 6 is where the bug is as in 7 the dtstyle contains the same instance name.

**Comment by TurboGit** [comment]
Thanks for the report, should be fixed on master.

**Comment by kofa73** [comment]
Confirmed: it is fixed, indeed. Thanks for the quick reaction.

**Comment by TurboGit** [comment]
Thanks for confirming !
