### ISSUE TITLE
Contrast-Equalizer doesn't run on GPU when high-quality resampling is turned on

### ISSUE THREAD

**Issue by HNieme** [darktable-org/darktable#8611]
**Background:** I have tried exporting >1.3k images with high-quality resampling on. This is extremely slow, although I have a somewhat decent GPU + OpenCL activated, taking ~46sec per image.

The problem seems to be that the Kontrast-Equalizer is not processed at the GPU but at the CPU

---

**System:** Debian 10 with Darktable installed vom Backports, version 3.2.1-3~bpo10+1.
Graphics Card Nvidia GTX970 ([versions see attached file](https://github.com/darktable-org/darktable/files/6256998/installed-nvidia-packages.txt)
4GB RAM

---

I ran Darktable with `darktable -d opencl -d perf`. I have tried `opencl_async_pixelpipe` set to true as well as set to false, as explained [here](https://www.darktable.org/usermanual/en/special-topics/opencl/performance/), this did not change the results.

The relevant part of the output is:

```
[...]
251,282437 [dev_pixelpipe] took 0,104 secs (0,043 CPU) processed `Schatten und Spitzlichter' on GPU, blended on GPU [export]
251,419454 [default_process_tiling_cl_ptp] use tiling on module 'atrous' for image with full size 6029 x 4011
251,419495 [default_process_tiling_cl_ptp] (2 x 1) tiles with max dimensions 5408 x 4011 and overlap 512
251,419500 [default_process_tiling_cl_ptp] tile (0, 0) with 5408 x 4011 at origin [0, 0]
251,796507 [opencl_atrous] couldn't enqueue kernel! -4
251,805171 [default_process_tiling_opencl_ptp] couldn't run process_cl() for module 'atrous' in tiling mode: 0
251,805191 [opencl_pixelpipe] could not run module 'atrous' on gpu. falling back to cpu path
291,894020 [dev_pixelpipe] took 40,612 secs (146,141 CPU) processed `Kontrast-Equalizer' on CPU with tiling, blended on CPU [export]
292,045471 [dev_pixelpipe] took 0,151 secs (0,116 CPU) processed `Kontrast Helligkeit Sättigung' on GPU, blended on GPU [export]
[...]
```
[whole output pertaining to image](https://github.com/darktable-org/darktable/files/6257024/relevant.output.txt)

At startup of darktable it said that atrous loaded/compiled? successfully.

I hope this information is useful

**Comment by ralfbrown** [comment]
Contrast equalizer on GPU needs 176 bytes per pixel....  So a 24 megapixel image needs 4.25 GB of **available** GPU memory.   Your card doesn't that  much memory, and the attempt at tiling on the GPU is probably failing due to improper configuration (dt thinks it can allocate enough to process a 21 megapixel section,  but then fails).  You might try adjusting the memory headroom parameter in `darktablerc` (see the OpenCL portion of the  manual).

**Comment by jenshannoschwalm** [comment]
@johnny-bit please close :-)
