### ISSUE TITLE
<FUJIFILM FinePix F550EXR>

### ISSUE THREAD

**Issue by enzolin-Fuji-Nikon** [darktable-org/darktable#8619]
Hi there I'm having troubles on the RAF files of my old camera.

They can be regularly imported and their thumbnails are correctly displaied in the lighttable but any of then can be opened in the darkroom module 

There was already a sample of these files in https://raw.pixls.us/ but I wanted to add some more (even if I don't see them online yet).

Thanks, Enzo.

**Comment by jrobinsonAG** [comment]
Hi, 

Just checking if this has been added to pipeline of changes?

**Comment by kmilos** [comment]
You can just copy the F600EXR section in cameras.xml as shown in the linked PR until it gets merged and shipped.

**Comment by enzolin-Fuji-Nikon** [comment]
Many thanks, i'll try and make you know! Cheers!

**Comment by enzolin-Fuji-Nikon** [comment]
Hi, I duped the section of the F600 and renamed anything to F550 the single photos now are correcly opened in the darkroom module but I get an alert message that says " 'Fujifilm Finepix F550EXR' color matrix not found! .

**Comment by enzolin-Fuji-Nikon** [comment]
To obtain a realistic result I've to boos the saturation very up (about +1).

**Comment by enzolin-Fuji-Nikon** [comment]
Anyway many thanks again, working on the raw some acceptable result already come out with little adjusts! ;)

**Comment by kmilos** [comment]
I think this one can be closed since dt 4.4 release. @LebedevRI
