### ISSUE TITLE
Collect images does not handle non-integer focal lengths properly

### ISSUE THREAD

**Issue by SWSRN** [darktable-org/darktable#8630]
My OLYMPUS IMAGING CORP. TG-3 has non-integer focal lengths in the metadata. When I try to collect images with this camera and narrow the search down using focal length, there are multiple options for some of the focal lengths, which are all shown as integer. For example, I get three options for a focal length of 5 (rounded down?) for focal lengths between 5.0 and 5.9 (?). When I select a focal length, regardless of whether there are one or duplicate "integer" focal lengths, I get an integer focal length in the box and get the error that "There are no images in this collection." See the screen shot.

As a counter-example, my Canon EOS 700D has integer focal length in the metadata and the collect images module works just fine when narrowing down by focal length. Also, narrowing down by aperature works for both cameras and that is stored as a non-integer in the metadata.

* darktable version :3.4.0
* OS                : Mac OS 11.2.3 Big Sur

![20210405_Screen Shot 2021-04-05 at 3 51 47 PM](https://user-images.githubusercontent.com/9578196/113893862-6b3ccc80-9795-11eb-85b2-11224d6de899.jpg)

**Comment by elstoc** [comment]
Yes I've been noticing this too on 3.4.1

**Comment by SWSRN** [comment]
Is commit comment backwards?
"@elstoc
collect: use integer focal lengths 256c33e when grouping images in the collect module or doing equality
comparisons, convert the focal length to an integer first"

Don't want to use integer. Use floating point +- delta.
Using Aperature in Collect Images does not convert to integer. Don't you want to do Focial Length and Aperature the same way?

**Comment by elstoc** [comment]
I'm not bothered either way really. I can either just deal with them all as integers or take them as-is. It looked like the intent of whoever did the collect module originally was to display integers so I just made that work. 

In general apertures are more likely to be non-integer than focal lengths. In my entire collection the only images I have with non-integer focal lengths are those taken on point-and-shoot or small format cameras. All my DSLR stuff is rounded to the nearest mm.

Let's see what others think.
