### ISSUE TITLE
Sony Alpha 7s III (ILCE-7SM3)

### ISSUE THREAD

**Issue by borrascador** [darktable-org/darktable#8632]
I'd love to be able to use darktable with my new Sony camera however my ARW files show up in lighttable but not in darkroom. I was about to try contributing to raw.pixls.us with samples but noticed there is already a sample there for this camera. Is the current upload sufficient to get support for all of the a7s3's format, or should I upload additional pictures?

**Comment by kmilos** [comment]
I guess the (new) uncompressed sample is missing on RPU to complete this as well?

**Comment by borrascador** [comment]
Hi @kmilos and thanks for making progress on this! I'm new to this process and unfamiliar with the sample requirements, but I am able to fill in any gaps on RPU with my camera if you can explain what's missing.

**Comment by kmilos** [comment]
Just follow the instructions on https://raw.pixls.us/ and please submit a full new set (all the different combos of bit depth and compression) of the same, well exposed scene. It should replace the single sample that is there now.

**Comment by borrascador** [comment]
OK, that answers my original question as well. I'll try to do it in the next week and will update this thread once I do.
