### ISSUE TITLE
GoPro Hero9 Black

### ISSUE THREAD

**Issue by convolutionbbs** [darktable-org/darktable#8635]
I uploaded 3 new raw files from a new GoPro Hero9 Black to pixls.us.  One outdoor with significant distortion, one outdoor with wide panorama, and one indoor for noise capture.  I can take more as needed.  The Hero4 gets fairly close, but it would be good to get the Hero9.  With raw, you can't shoot linear and it's difficult to adjust the distortion on every image.

Thanks!

**Comment by LebedevRI** [comment]
Thank you for the sample.
Unfortunately, lens correction is an upstream lesnfun issue.
https://lensfun.github.io/
