### ISSUE TITLE
Segfault in libdemosaic under Windows (bisected)

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#8636]
DT segfaults in lighttable or when opening and image in darkroom

current git master, Windows 10, OpenCL activated.

[darktable_bt_WHF800.txt](https://github.com/darktable-org/darktable/files/6283717/darktable_bt_WHF800.txt)

Error occurred on Friday, April 9, 2021 at 08:47:19.

```
darktable.exe caused an Access Violation at location 00007FFFF8410415 in module libdemosaic.dll Reading from location FFFFFFFFFFFFFFFF.

AddrPC           Params
00007FFFF8410415 0000000000000000 00007FF81EB52EF8 0000000000000000  libdemosaic.dll!rcd_demosaic._omp_fn.0  [C:/msys64/home/marco/develop/darktable/src/iop/rcd_demosaic.c @ 307]
   305:           for(int col = 4, indx = row * RCD_TILESIZE + col; col < tileCols - 4; col++, indx++ )
   306:           {
>  307:             bufferV[row - 3][col - 4] = sqf((cfa[indx - w3] - cfa[indx - w1] - cfa[indx + w1] + cfa[indx + w3]) - 3.0f * (cfa[indx - w2] + cfa[indx + w2]) + 6.0f * cfa[indx]);
   308:           }
   309:         }
```

Git bisect gives:

```
6727a3ab99a3684b7137c8483cecc763fe77d20f is the first bad commit
commit 6727a3ab99a3684b7137c8483cecc763fe77d20f
Author: hanno@schwalm-bremen.de <hanno@schwalm-bremen.de>
Date:   Tue Apr 6 22:03:24 2021 +0200

    RCD demosaicer maintenance updates.

    While working on the new 'contrast mask' (should be understood as a 'detail mask' btw) i found

    - some functions/variables are named in a misleading way
    - i didn't want to duplicate code
    - some minor code improvements
    - the detail mask was not visible in default darkroom demosaicer setting

    So, some files touched for 3.6 code cleanup needed anyway

 data/kernels/demosaic_rcd.cl |  98 +++++++++++---------
 src/develop/masks.h          |   6 ++
 src/develop/masks/detail.c   | 167 ++++++++++++++++++++++++++++++++++
 src/develop/masks/masks.c    |   3 +
 src/iop/demosaic.c           |  31 ++++---
 src/iop/dual_demosaic.c      | 211 +++++++++++--------------------------------
 src/iop/rcd_demosaic.c       |  15 +--
 7 files changed, 307 insertions(+), 224 deletions(-)
 create mode 100644 src/develop/masks/detail.c
```
@jenshannoschwalm can you have a look ?

**Comment by jenshannoschwalm** [comment]
Hmm, just to make sure
1. does this also happen if you use --disable-opencl while starting darktable?
2. there have been changes to the OpenCl kernels, did you clear your cl kernel cache before re-install?

**Comment by jenshannoschwalm** [comment]
From first sight there is only one thing changed in rcd code which i assumed to be safe sqrf --> sqf, don't know how that could interfere but ...

**Comment by TurboGit** [comment]
@jenshannoschwalm : Yes, I've seen that it is the only change on those lines. The sqf() is SIMD whereas the previous sqrt() was not. Could this be the problem?

**Comment by jenshannoschwalm** [comment]
Yes might be because of assuming aligned access? Didn't think of this and would revert that code part if Marco can confirm.

**Comment by TurboGit** [comment]
Or better makes bufferV aligned (line 301) as we might gain some precious CPU cycles.

**Comment by jenshannoschwalm** [comment]
Yes that might be good indeed.

Although we have a reading problem here, here we do something like `sqf(cfa[idx + something] ...` something is aligned, idx is not. So the write buffer is fine, reading not i guess.

**Comment by TurboGit** [comment]
@jenshannoschwalm : Of course you are right ! The cfa table is indexed with idx and w3 / w4 and there is no way to ensure that the values will be aligned in this part of the code. So we probably only can disable the SIMD inst (at least for now).

**Comment by jenshannoschwalm** [comment]
Anyway, thanks for the discussion pascal and thanks to you marco for giving me the hint! I was so busy the last weeks getting detail mask (or contrast mask in rt) ready for 3.6 i got somewhat blind here. I had a few peculiar things with that and now i likely know the reason.

Will do a fixing pr tonight ...

**Comment by Mark-64** [comment]
I have been quite busy today, but don't hesitate to give me changes to test
