### ISSUE TITLE
Image is shown as square crop during tethered shoot

### ISSUE THREAD

**Issue by 0ge** [darktable-org/darktable#8637]
**Describe the bug/issue**
In tethered mode the images shown are shown as a square crop instead of the full image.
It would also be beneficial if there was zoom controls - primarily 100% and fit. (To check focus and composition)

**To Reproduce**
1. Start new tethered session
2. Capture image

**Expected behavior**
Entire image is shown.

**Screenshots**
![Screenshot 2021-04-09 at 11 27 12](https://user-images.githubusercontent.com/7213234/114160501-46785e80-9927-11eb-86b3-f6574a1b0e96.png)

**Which commit introduced the error**
Don't known

**Platform**
* darktable version : 3.4.1
* OS                : macOS 11.2.3 (Big Sur)
* Memory            : 8 GB 1867 MHz DDR3
* Graphics card     : Intel Iris Graphics 6100 1536 MB
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Additional info**
If I resize the darktable window's height it scales the image, but maintains the aspect ratio. Resizing the width has no apparent effect.

**Comment by dtorop** [comment]
@0ge: This may be a hidpi bug in tether view, which is causing the image to be drawn too large (hence appearing square cropped in this case with camera in portrait orientation). This may be fixed by #9031.
