### ISSUE TITLE
color calibration blacks out screen

### ISSUE THREAD

**Issue by billmartz** [darktable-org/darktable#8645]
**Describe the bug/issue**

A certain combination of settings in color calibration results is screen black-out when red channel is increased.

![image](https://user-images.githubusercontent.com/46618108/114272082-949e6800-99e2-11eb-9e0e-86f694f67443.png)

Using raw DSCF1110.RAF from https://discuss.pixls.us/t/out-of-the-box-raw-rendering-not-up-to-jpegs/6669.

Sidecar:
[DSCF1110_14.RAF.txt](https://github.com/darktable-org/darktable/files/6290050/DSCF1110_14.RAF.txt)

Required conditions:
clip negative RGB from gamut is unchecked in both color calibration modules.
color calibration 1 is using drawn and parametric masks. 
red channel: increase input red above 1.015 in color calibration 1.

Problem occurs with both builds:
darktable-3.5.0+1600/~g6727a3ab9-win64.exe
darktable-3.5.0+1616/~ge9302dbf7-win64.exe

**Platform**

* darktable version : See above
* OS                : Windows 10 Pro, version 20H2
* Memory            : 32 GB
* Graphics card     : NVIDIA GeForce GTX 1070 Driver version: 457.30
* OpenCL installed  : unknown
* OpenCL activated  : activated
* CMAKE_BUILD_TYPE  : unknown

**Comment by paolodepetrillo** [comment]
I can reproduce this, running the latest 3.5.0+1822~gd746b5630 on Arch Linux, with a GTX 1080.
The problem only occurs with OpenCL enabled. It looks like it's happening within Filmic RGB, somewhere in the highlight reconstruction step. If I comment out the highlight reconstruction stuff in filmicrgb.c process_cl() the problem goes away.

**Comment by paolodepetrillo** [comment]
After some more experimentation I don't think this depends on OpenCL being enabled, it does happen with OpenCL off.
It looks like for some small number of pixels in the image, the first color calibration module is outputting extremely large positive or negative values, on the order of +/- 10000 to 1000000, when they should be close to the range 0-1. Depending on the settings of the second instance of color calibration these affected pixels may come out with reasonable values and there is no problem. But if a mask is enabled (uniform mask works) and the RGB sliders have been adjusted, the module can output a pixel with the value NaN for one of the affected input pixels. If a single NaN value gets into filmicrgb's highlight reconstruction, it will turn a large region of the image black, exactly as seen here.

**Comment by aurelienpierre** [comment]
>  clip negative RGB from gamut is unchecked in both color calibration modules.

So I am going to say it's not a bug then. Negative RGB are illegitimate.

**Comment by billmartz** [comment]
So, something about this particular image is causing a negative value? Not expected to commonly occur?
