### ISSUE TITLE
color balance rgb: increase sliders soft range

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#8646]
I am testing the new color balance rgb module for a while, and often I find myself going out of soft ranges for luminance and chroma sliders in "4 ways" tab.
Here is my proposal of soft ranges:

**offset**
luminance: no change
chroma: 0 - 1% (instead of 0 - 0.5%)

**lift**
luminance: -100% - 100% (instead of -50% - 50%)
chroma: 0 - 50% (instead of 0 - 10%)

**gain**
luminance: no change
chroma: 0 - 20% (instead of 0 - 5%)

**power**
luminance: no change
chroma: 0 - 10% (instead of 0 - 2%)

**Comment by aurelienpierre** [comment]
Go for it !
