### ISSUE TITLE
UI focus is lost during import making light table unusable

### ISSUE THREAD

**Issue by 0ge** [darktable-org/darktable#8653]
**Describe the bug/issue**
When importing images the UI focus changes, which makes it impossible to do anything.
I've observed two places:
 1. In collect images, the edit fields lose focus so it is not possible to enter an expression.
 2. The light table constantly moves to the top, so even if you're fast enough to collect images, it is not possible to scroll through it.

**To Reproduce**
1. Start import of multiple photos.
2. Go to "collect images"
3. Attempt to enter an expression. E.g. try to set "tag" to `darktable|changed`
4. With collected images, scroll in light table

**Expected behavior**
It is possible to collect images in the usual manner.
Collected images are updated if an imported image is to be included
Light table does not move around during import, even if an imported image matches the collection criteria.

**Platform**

* darktable version : 3.4.1
* OS                : macOS 11.2.3 (Big Sur)
* Memory            : 8 GB 1867 MHz DDR3
* Graphics card     : Intel Iris Graphics 6100 1536 MB
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Additional context**
The import has to take sufficiently long time in order for this to be an issue. In my case I was importing some ~1000 images from a network drive.

**Comment by Nilvus** [comment]
I would add that this is a thing to improve. Another example related to this issue:

- import a large set of images (I do it this day with about 380 images)
- try to begin sort images with filmstrip or culling mode
- go to next image
- see that in about 2 or 3 seconds max, the view is reset to first image of current collection

It's hard to began working on images (reject, rate them or simply move between images) during an import session. As soon as the import is done, we can work on that.

Should it be possible to avoid that reset to first image during an import and allow us to begin working on images without waiting for the end of import (what I test here is an import from copy and import button, especially from an SD card of my camera).

@phweyland and @AlicVB: it's a really annoying behavior. As you work respectively in import and lighttable parts, what's your view on that?

**Comment by Nilvus** [comment]
It would be good, if possible of course, to see that improved in 3.6.
