### ISSUE TITLE
Clarify delete button

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#8656]
**problem**

It's very difficult to see, which button really deletes the image file from disk:
- the remove_button has a tooltip including "(Delete)"
- the delete_button on the other hand does not include "delete" at all

The reason for this strange behavior with default-settings is:
  - the key 'del' is mapped to the remove_button
  - dt tries to move files to trash "on system that supports it"

**solution**
- extend the tooltip to "(key: 'Delete')
- always use the label 'delete' for the delete-action

Deleting image files including sidecars is a very severe action, dt can't undo the deletion, so it should not pretend to have a trash.

**Alternatives**
- remove delete_button
- create a trash in dt to undo the deletion of files

**Comment by elstoc** [comment]
I've pushed a PR to clarify the tooltip. The "delete" button changes to "trash" automatically if you select the appropriate option in the security tab of the preferences dialog. You should restore files using your filesystem trash if required and, as always, take care when physically deleting things.

**Comment by quovadit** [comment]
Yes, I know that delete changes to trash depending on the setting. But as quoted, it uses trash "on system that supports it".
So there is no guarantee, that files are not deleted.
Having a button in dt called 'trash' claims there is a undo functionality within dt.
So from a user-perspective it's always a deletion.
And there are operating systems which automatically delete trash, so you can't be sure if you even have a chance to restore.

**Comment by elstoc** [comment]
> Having a button in dt called 'trash' claims there is a undo functionality within dt

I'm not sure it does. I think most people know that trash is a filesystem thing. I'm not sure we can easily detect whether the OS supports trash, or whether there'll be much interest in dt implementing its own undo, given that you'd have to undo changes to the database as well as file system stuff.

> So from a user-perspective it's always a deletion

If the OS doesn't support trash, yes it is. I don't know what we can realistically do about the cases you've mentioned though.

**Comment by parafin** [comment]
I don't agree that usage of term "trash" means that undo functionality has to be inside darktable. We just use system trash, and it's reasonable to assume that user knows how trash works in his OS. As from "system that supports it" - I think when trash doesn't work darktable displays some warning dialog, but I might be wrong. This is something to check and maybe clarify.

**Comment by parafin** [comment]
For "undo" inside darktable just use "reject" rating feature instead.

**Comment by elstoc** [comment]
> For "undo" inside darktable just use "reject" rating feature instead.

Or use "remove" instead of "trash/delete".

**Comment by elstoc** [comment]
Actually it looks like darktable is attempting to trash and then deleting if that fails, so we could potentially add an error message or prompt stating that trash is unsupported (`g_file_trash`returns `G_IO_ERROR_NOT_SUPPORTED` if trash isn't supported by the FS). I'm not sure how easy this is though. Might be better as a separate issue.

**Comment by quovadit** [comment]
Thanks for the PR @elstoc , but this only solves 1/2 of the problem.

I know, that there are alternatives to the trash-button (reject, remove). But anyhow deleting image files including sidecars is a very severe action.

I did not know, that dt uses the operating-system trash until I inspected the source-code before creating this issue.
So if I empty the operating-system trash, I don't necessarily know that hereby I permanently delete all my trashed dt-images.
And I have a setting 'Automatically Delete Trash Content' in manjaro.

**Comment by elstoc** [comment]
I've reopened but it might be worth adjusting the title to reflect the actual remaining issue here.

**Comment by quovadit** [comment]
It's not a matter of "understanding how the OS works".

It is not obvious, that the 'trash' button in dt references the trash of the OS.
There is no way to undo the deletion in dt.
It is not guaranteed, that there even is a working trash (which does not automatically gets deleted as a cleanup).

That's why I think the delete-button should always be called 'delete' (see my PR)

**Comment by curiousercreative** [comment]
Coming from Apple Aperture, the application had an application specific "trash" that you had to empty manually. As @quovadit states, such a consequential action should be clarified and require a user confirmation.
