### ISSUE TITLE
'Image is currently unavailable'

### ISSUE THREAD

**Issue by sladcolour** [darktable-org/darktable#8664]
**Which new feature or section need to be documented/updated**

Hello, can anyone help? I have been processing images on Darktable for several months with no problems. But recently lots of my photographs are 'currently unavailable' and the drive is plugged in.

Please do share thoughts

**Comment by ralfbrown** [comment]
You'll need to provide more details.  What darktable version?  Operating system?  Are you using darktable's "local copy" feature?  Can the "unavailable" files be read by other programs? (there's a chance your external drive is failing)

**Comment by sladcolour** [comment]
Hello, Darktable version 3.4.0 on a MacOS Catolina Version 10.15.7. Have tried with a different drive and same issue, different photos. Can access all photos fine through other software so I don't think it is the drive. Thanks for your help

**Comment by AlicVB** [comment]
can you check the full file path in the image information panel when you are in lighttable, and then check with a file explorer or whatever if the file you want has still the same path. Esp. pay attention to the start of the path...
I've no idea how MacOS works, but in other OS, external drives may sometimes be mapped to a different location...

**Comment by MStraeten** [comment]
you might check the name of your external drive via terminal  - it's mounted as /Volumes/name-of-the-drive. if you already have mounted an equally named share or drive the name can get an appendix -1 (but thats not shown on the desktop)

**Comment by johnny-bit** [comment]
@sladcolour - please get check the responses and see if solutions work for you, since it might be some macos peculiarities and totally outside of the scope of darktable.

**Comment by johnny-bit** [comment]
Closing as no other info available
