### ISSUE TITLE
Spots and retouch stamps misaligned if distortion changes

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#8675]
**Describe the bug/issue**

darktable draws masks in RAW coordinates by belief masks should be anchored to pixels and move with them if they are to be distorted at a later time but lower in the pipe. Spots and Retouch stamps show a gross misalignment when the image is deformed. Liquify is ok though.

**To Reproduce**

Use
![grid](https://user-images.githubusercontent.com/2779157/114700106-6346d480-9d21-11eb-82b2-b1480f779269.jpg)

Put clone stamps at corners with lens correction, crop and rotate and perspective correction modules off.
![Screenshot_20210414_125241](https://user-images.githubusercontent.com/2779157/114700196-81143980-9d21-11eb-81be-de53a4d0e04b.png)

Enable perspective module with arbitrary deformation: mismatch
![Screenshot_20210414_125305](https://user-images.githubusercontent.com/2779157/114700253-94270980-9d21-11eb-82c0-5bdc80dfc879.png)

Enable crop and rotate with arbitrary keystone deformation : mismatch
![Screenshot_20210414_125350](https://user-images.githubusercontent.com/2779157/114700290-a43ee900-9d21-11eb-9519-48843576cec5.png)

Test with liquify, no distortion on:
![Screenshot_20210414_125552](https://user-images.githubusercontent.com/2779157/114700385-c0428a80-9d21-11eb-9e3c-b09a3ca14e28.png)

Apply distortions : match with both perspective module and crop and rotate keystone
![Screenshot_20210414_125726](https://user-images.githubusercontent.com/2779157/114700471-d2bcc400-9d21-11eb-9477-7878b8a24bfc.png)

![Screenshot_20210414_125740](https://user-images.githubusercontent.com/2779157/114700483-d6e8e180-9d21-11eb-8262-4f6c46474974.png)

**Expected behavior**

Same as liquify.

**Comment by aurelienpierre** [comment]
On further investigation, it appears that both spots and retouch take the geometry they get at their input, and even though they correct the coordinates of the masks for distortions, they don't actually correct use pixel geometry.

Contrarily to what @ralfbrown said in #8634, spots and retouch actually take the pixel geometry at the place where the are in the pipeline, when they are placed after the perspective module, which would indicate they always have to go after geometric corrections in the pipeline to be able to sample properly oriented edges, and current pipeline order makes sense.

**Comment by AlicVB** [comment]
there's something I don't understand here... maybe I overlook some usage for this tools, but if we take spot (as it's the most simple) : 
What you want is replacing some "problematic" pixels in your image by pixels from another area. So for this 2 operations, you want your masks to be "anchored" to specific pixels, whatever the distortions you apply. I mean, if you want to remove the electric line, you want to mask the electric line pixels. Whatever if you have applied heavy liquify and you line make waves ;)

So I really don't get why it can't happen before geometric corrections... I may certainly have forgot something...

**Comment by AlicVB** [comment]
ok, I see the problem. @aurelienpierre describe it correctly, we "just" differ on conclusion ;)

steps : 
- open "fresh" image with current master, pipe order "3.0"
- apply some keystoning with crop&rotate
- try to clone some area with spots removal and circle form (same apply for retouch, I've just used this one as it's more simple)
- I'm just focusing here on the fact that the cloning source should be the right one.

=> with default (3.0) pipe order where spot is *after* crop&rotate : 
![Capture_après](https://user-images.githubusercontent.com/1818223/114735623-aadf5780-9d45-11eb-9466-dfd46cd1a688.png)
=> if you move spot *before* crop&rotate : 
![capture_avant](https://user-images.githubusercontent.com/1818223/114735711-be8abe00-9d45-11eb-902e-ccd1dab12308.png)

If you look at the code (here, all happen in the input "space" of the spot removal module)
1. we get the form as a raster mask in the module input reference, distorted by all the previous modules in the pipe
2. we get the shift between the form center and it's source
3. for each pixels in the form mask, we replace it by the pixel located at position - shift.

That mean : 
- if we have some distortion *before* spot, the shift may not be accurate anymore (completely off, like in the example above) => this one is easily solvable by recomputing the shift in regards to the distortion applied *before*
- if we have some distortions *before*, the source may not have the same "form" than the destination. => this one is really more difficult to solve, as it would means reapplying all the distortions to each pixels... not impossible but very costly in term of computations...

=> So... is there any reason why not putting spot and retouch *before* any geometric distortions ?

**Comment by aurelienpierre** [comment]
The usual use case for perspective distortion is to **correct**. Here, you **distort**. Whatever you do, spots and retouch need to work in an orthogonal space, where lines that appear straight and vertical in real life are straight vertical lines at the pipeline step where you put the retouch/spots module.

When you **correct* for lens and perspective, the place where the space is orthogonal is **after** distortions because they are meant for that.

**Comment by AlicVB** [comment]
So the erroneous shift is clearly a bug in the code. I've started to fix it in #8676 (scale not applied at the right stage)...
With that, you at least have the right source source center for the cloning :)

@aurelienpierre : I'm not sure we use the retouch/spot for the same purpose... I've focused my mind on the fact that this tools where here to *remove* things, like dusts, mole, electric lines, ... but you seems to use it to duplicate objects (you want the object to be distorted *before* you clone to ensure that it has the same distortion). If I'm right, that would explain some misunderstanding...

**Comment by elstoc** [comment]
Even when you want to remove things, sometimes the background has features that you want to retain. For example if you wanted to clone out a feature on a picket fence by cloning from another part of the fence. Lens distortions can mean that the features don't match up even if lens correction fixed the original distortion.

**Comment by aurelienpierre** [comment]
@AlicVB the fundamentals of removing objects in retouch are to clone (and possibly blend, for the healing tool) a clean region having the same texture onto the object to remove, and choosing a source region that matches (same edges direction if any + same texture) the destination. 

So we are using the tool in the same way, it's just that I put high priority on having edges and textures properly scaled and distorted before the cloning (aka content matching), while you seem more focused on the locality of the destination/source patches. I mean, both are important, but the locality of the patches is easily fixed by coordinates mapping, while the content matching needs to sample the pixels at the right place in the pipe (I should make a stamp for that "Right place in the pipe®").

**Comment by AlicVB** [comment]
@aurelienpierre : thanks for the explanations... I was forgetting the structures rotation and compression (certainly because most of the time, I'm cloning on sky, with very small distance between source and target)
in French we say something like "I understand quickly but I need a long explanation" :)
