### ISSUE TITLE
[FR] display distorted sample form before applying them

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#8677]
steps : 
- take a "fresh" image
- apply an "heavy" deformation, like keystone in the example
- go to whatever module with masks (here curvesRGB to darken the image)
- enable drawn masks on this module and select "circle" tool

when you move the mouse on the image before clicking to add a new circle, the "sample" under the mouse is true round, not distorted :
![capture_avant](https://user-images.githubusercontent.com/1818223/114756024-99547a80-9d5a-11eb-9e10-b31f523215e3.png)
but when you add the circle, you see that in "real" it's distorted :
![Capture_après](https://user-images.githubusercontent.com/1818223/114756123-b6894900-9d5a-11eb-8c3d-8c74c170f8e8.png)

The goal here is to make the sample "distortion aware" so what you get isn't unpredictable.

Note : it's different from the actual controversial discussion about what reference to take for masks. This is just to enhance the current behavior (which will stay in any case)

I'll try to take care of implementing that. I've just open this FR so other devs are aware of my projects ;)

**Comment by TurboGit** [comment]
I love it ! Was thinking about this since long time and never got the time to work on this.
