### ISSUE TITLE
restrict histogram to selection is lost on edits

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#8680]
The checkbox "restrict histogram to selection" allows to restrict the histogram to a selection made with global picker.
This restriction is lost if there're changes in the pixel pipe (new module applied or change of settings of active modules)

**To Reproduce**
1. Go to 'global color picker'
2. select an area
3. check 'restrict histogram to selection'
--> histogram is restricted
4. activate a further module or change an existing
--> histogram restriction is lost

**Expected behavior**
histogram restriction is kept until the checkbox is unchecked

**Which commit introduced the error**
maybe that's works as designed - it's present since a long time ago

**Platform**
darktable version : /opt/darktable/bin/darktable --version
this is darktable 3.5.0+1719~g2db3961cc
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

equal behaviour on OSX and Win10

**Comment by todd-prior** [comment]
I hadn't seen 8680 thanks for letting me know......

**Comment by dtorop** [comment]
I've been puzzling over this & related cases as well -- the current behavior may be intended, but it isn't intuitive. I think the work on this lies more with pixelpipe than scope code, but I'm happy to look at this as time allows.

**Comment by johnny-bit** [comment]
Actually this and #5689 are duplicates :)

@Mstraeten - I'll close this in favour of that one if you don't mind.
