### ISSUE TITLE
Drawn masks have jagged edges

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#8685]
**Describe the bug/issue**
Drawn selections (tried with different modules, raw and non-raw files) display jagged edges; exported files are also affected.

**To Reproduce**
1. Get the files from https://tech.kovacs-telekes.org/files/dt-jagged-drawn-mask-edges/
2. Check the masks - they are jagged

**Expected behavior**
Smooth masks

**Which commit introduced the error**
I may have time to bisect during the weekend

**Platform**
* darktable version : 3.5.0+1665~ge6a12721e
* OS                : Linux, kernel 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Linux - Distro    : Ubuntu 20.10
* Memory            : 64 GB
* Graphics card     : NVidia 1060/6GB
* Graphics driver   : 450.102.04-0ubuntu0.20.10.2
* OpenCL installed  : yes
* OpenCL activated  : yes, no (problem occurs regardless of OpenCL enabled)
* Xorg              : 1:7.7+19ubuntu15
* Desktop           : KDE Plasma 5.19.5-0ubuntu1  
* GTK+              : 3.24.23-1ubuntu1, 2.24.32-4ubuntu4 
* gcc               : 10.2.0-13ubuntu1 
* cflags            : 
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes

**Comment by TurboGit** [comment]
I'm wondering if this is not just a matter of adding some feathering (0.2) to the mask?

**Comment by kofa73** [comment]
It's the same as 3.4.1 on Windows, so it's not a regression. Somehow, I never noticed that before.
