### ISSUE TITLE
Darktable 3.5 slows then crashes when using Color Balance RGB on Windows 10

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/darktable#8686]
Darktable slows when activating the Color Balance RGB module and then eventually crashes.
---------------------------------------------------------------

Activating the module begins slowing darktable response time.  The sliders begin to lag behind the mouse commands and the computer hardware seems to be caught up in some sort of processing loop.  At some point darktable will fail due to an unhandled exception:

"darktable.exe caused an Access Violation at location 00007FF9A3859602 in module libcolorbalancergb.dll Writing to location 0000000000000400"

**To Reproduce**
1. Activate the Color Balance RGB module
2. Module use will begin to slow response time
3. Mask use appears to accelerate the issue
4. System will seem to bog down and then crash

I've had three occurrences to date.  Backtraces are attached.

**Platform**

* darktable version : 3.5.0+1620~g47fbd509a
* OS                : Windows 10
* Memory            :  8 GB
* Graphics card     : AMD A8-7410 APU with AMD Radeon R5 Graphics, 2.20 Ghz
* Graphics driver   : Unk
* OpenCL installed  : Yes
* OpenCL activated  : No (Open CL always causes my system to lock up - different issue)
* Xorg              : Unk
* Desktop           : HP Pavalion
* GTK+              : Unk
* gcc               :  Unk
* cflags            : Unk
* CMAKE_BUILD_TYPE  : Unk

This module is awesome and I hope this helps. I will be happy to provide any additional information.  

[darktable_bt_CXJR10.txt](https://github.com/darktable-org/darktable/files/6324780/darktable_bt_CXJR10.txt)
[darktable_bt_5PWZ10.txt](https://github.com/darktable-org/darktable/files/6324781/darktable_bt_5PWZ10.txt)
[darktable_bt_ENZY10.txt](https://github.com/darktable-org/darktable/files/6324783/darktable_bt_ENZY10.txt)

**Comment by Dave22152** [comment]
I've been investigating further and found that darktable 3.5.0+1620~g47fbd509a crashes when attempting export after the Color Balance RGB (CBRGB) mask tab is activated.  Procedure to replicate:

1.  Opened a file and exported multiple times, first with default scene-referred settings (OPENCL not activated), then with CBRGB with no issue
2. Activated CBRGB and exported multiple times, first with no changes, then with changes limited to Master tab, with no issue
3. Activated the Mask tab with NO changes.  Export failed on first attempt and DT crashed, generating the attached backtraces.  This failure is highly repeatable.

I went through the identical steps with 3.5.0 _1426 and had no issues, even with the mask tab activated and after making changes to roll-off settings.  This leads me to believe there is something happening with the masking GUI implemented in the latter version, at least in Windows.


[darktable_bt_MZA310.txt](https://github.com/darktable-org/darktable/files/6336705/darktable_bt_MZA310.txt)
[darktable_bt_9PDT10.txt](https://github.com/darktable-org/darktable/files/6336706/darktable_bt_9PDT10.txt)
[aria-debug-10152.log](https://github.com/darktable-org/darktable/files/6336707/aria-debug-10152.log)

**Comment by Mark-64** [comment]
I can't reproduce in Windows 10 with the above procedure and unfortunately the backtrace file provided do not say much.
@Dave22152 maybe you could try to build DT in "RelWithDebInfo" or "Debug" mode and see if the backtrace have more info

**Comment by Dave22152** [comment]
@Mark-64 , I'll be happy to do that.  Forgive my ignorance, but how do I enter debug mode?  I currently start darktable from a shortcut, invoking the following in the target line: "C:\Program Files\darktable Dev 3.5+1620\bin\darktable.exe" --configdir "C:\Users\dave_\AppData\Local\Darktable 3.5+1620"

Adding the -d at the end doesn't work, so clearly I don't understand how to apply the command and syntax.

Much obliged.

**Comment by aurelienpierre** [comment]
There is nothing really useful in those backtraces to help find the cause, so I picked the smell of the reproducing sequence and tried 2d7eadc6637ef85f3bd446aebcf7864b6b43e9fc. Can you see if it fixes it ?

**Comment by Dave22152** [comment]
@aurelienpierre, I'll be glad to.  I'm afraid I'm going to expose my ignorance and ask for some guidance.  I see your code, and I know where the colorbalancergb.dll file is located, but could you tell me how I implement your potential fix?  Sorry if this is a nuisance, I'm hoping this is helping.

**Comment by aurelienpierre** [comment]
Just pull the master branch as usual, from git, the commit is already in there.

**Comment by Dave22152** [comment]
Thanks.  I'll let you know what I find.

**Comment by Dave22152** [comment]
I spent about 4 hours putting the CBRGB module through its paces and haven't had a single crash, so it looks like the code change did the trick.  I'll continue working with it, but the results look promising.

**Comment by Dave22152** [comment]
I've completed three editing sessions using the module and haven't had any further crashes, so I think you can considered the issue successfully closed.  Thanks for your attention!

**Comment by johnny-bit** [comment]
> considered the issue successfully closed

OK :)
