### ISSUE TITLE
Export module : keep last piwigo album used

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#8687]
**Describe the bug/issue**
I'm not sure if this is a bug but if not, it's so a feature request.
I'm using since few days Piwigo and so set my piwigo account in darktable export module and it's great.

The only annoying thing is that my settings are never saved.

2 things:

- I saved a preset but each time I launch darktable, I need to set back server link, id and password. They are not saved. At worst, I could understand to set each time password, even if it will be great to save all things and avoid seeing them reset on each darktable restart.
- When doing import, I would like to see last album selected kept. Actually, after each export, album is reset back to first one

@TurboGit: maybe this one is for you as you worked on that part? Or maybe @phweyland or someone else ;-) !

**Expected behavior**
Having last settings kept and not reset by default, for all things, so export module, saved preset and last album selected for piwigo part.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : last master (compiled on 15th april)
* OS                :  Linux Ubuntu 20.10

**Comment by TurboGit** [comment]
>     * I saved a preset but each time I launch darktable, I need to set back server link, id and password. They are not saved. At worst, I could understand to set each time password, even if it will be great to save all things and avoid seeing them reset on each darktable restart.

This is working on my part. I'm also using Piwigo and my preset do save the server & username even the password is restorre when selecting the preset.

>     * When doing import, I would like to see last album selected kept. Actually, after each export, album is reset back to first one

Export you mean ? But indeed we have never restored the last album.

**Comment by wpferguson** [comment]
> but each time I launch darktable, I need to set back server link, id and password

Do you the password storage back end preference set?

**Comment by johnny-bit** [comment]
Piwigo credentials are not in export module at all (and shouldn't be) but instead are in password storage.

**Comment by Nilvus** [comment]
> Do you the password storage back end preference set?

Good catch @wpferguson, I forgot to check that and setting it in preferences, make it works.

> Export you mean ? But indeed we have never restored the last album.

Yes, of course! So, remains that second point. It would be good to have by default last album used kept. It would be good to see that for 3.6?
