### ISSUE TITLE
Cannot reload edited watermark 

### ISSUE THREAD

**Issue by pedjas** [darktable-org/darktable#8690]
**Describe the bug/issue**

When watermark svg is loaded it seems darktable keeps it in memory. If SVG is changed darktable does not reflect change. There is no option to reload/refresh watermark file.

This is nuisance when one creates watermark and tries to make it fit. SVG should be edited in external program like Inkscape and frequently reloaded until desired look is achieved. Having no option to easily reload/refresh SVG watermark file in darktable makes it hard to work.

**To Reproduce**

1. Create watermark SVG in Inkscape and save it in watermark directory
2. Load that watermark into darktable
3. Change watermark SVG in Inkscape and save it in watermark directory
4. darktable does not see change.
5. Changing to other watermark and then loading back new one does not reload file, it still shows old version of file.

**Expected behavior**
Expected is to have some way to force reload of watermark file, either by specific button, or clicking already existing refresh button, or by switching to other watermark and then switching back to one that is changed to initiate reload.

**Which commit introduced the error**
darktable version 3.4.1.1 for Windows, downloaded and installed on April 16th, 2021.

**Platform**

* darktable version : 3.4.1.1 downloaded and installed on April 16th, 2021.
* OS                : Win10

**Comment by wpferguson** [comment]
> This is nuisance when one creates watermark and tries to make it fit.

Use the scaling and positioning in the watermark module to make it fit

**Comment by pedjas** [comment]
> 
> 
> > This is nuisance when one creates watermark and tries to make it fit.
> 
> Use the scaling and positioning in the watermark module to make it fit

I did not mean to physically fit but to fit wanted looking of the watermark. That means editing graphical elements in SVG.
