### ISSUE TITLE
Retouch module: How do you (re)activate a drawn mask that is inside another one?

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#8697]
Description:

For example, I have two masks on same scale in the retouch module. one larger (path mask) for blur and one inside this mask (circle, heal tool mask):

![Retouch_mask](https://user-images.githubusercontent.com/38165484/115106346-8dd49f80-9f64-11eb-9645-bc788d3fc50d.jpg)

After I created heal tool mask, I have no possibility to reactivate it again, because it is inside another mask. In the mask manager of darktable the masks of retouch module are not listed and accordingly I cannot access individual masks there.

Is there a possibility to access this mask later? For example with the help of a keyboard combination?
I could not find any entry about this in the documentation.

Thanks in advance

**Platform**

* darktable version : 3.5.0~git1703.030138222-1
* Linux - Distro    :  Kubuntu 20.04
* Memory            : 32 GiB
* Graphics card     : GeForce GTX 1070
* Graphics driver   : Nvidia 460.56
* OpenCL installed  : yes
* OpenCL activated  : yes
* Desktop           : KDE Plasma 5.18.5

**Comment by elstoc** [comment]
I think the only way at the moment would be to move the larger mask out of the way. Making the masks available in the mask manager might be hard, since these aren't "normal" shapes (because they are source-target pairs). Perhaps where the module says "shape selected: path #1" we could change this to a combobox to choose & highlight shapes?

**Comment by s7habo** [comment]
> Perhaps where the module says `shape selected: path #1` we could change this to a combobox to choose & highlight shapes?

That would be a nice solution. Even better, if in combobox would be listed only the masks that are currently in active scala.

An easier way would be to have a keyboard shortcut to activate the mask inside another one. In Inkscape for example if an object is inside another object you can activate it with Alt+ right mouse button

**Comment by TurboGit** [comment]
Yes, I have this problem from time to time.

**Comment by TurboGit** [comment]
I've been thinking about this and using a combo for this won't be very handy. In retouch we may have lot of shapes and having to select one just by the number would be immediate.

I would certainly prefer having a way with the mouse (ctrl-shift-scroll or whatever) to cycle through all shapes under the cursor.

**Comment by s7habo** [comment]
This is how it works in Inkscape:

Note that the path object is hierarchically _above_ ("covers") the circles and ellipse. That is, the circles and ellipses are not accessible with a normal right-click - the path object is always selected. If you keep ALT key pressed, at first the path object is selected and then, with the next right-click the circle or ellipse under it is selected if you stay with mouse cursor on it:


https://user-images.githubusercontent.com/38165484/115155974-7a1f5b00-a082-11eb-907e-f44b513bd634.mp4



This is easiest, because you can select the object _directly with the cursor,_ which you want to adjust again. You don't need to scroll through the list to find the object first.

**Comment by elstoc** [comment]
If we had a workflow whereby you had to select a shape first (by clicking on its path) before working on it that would solve a number of pain points and allow us in the future to show additional on-screen controls as suggested in #3740. Perhaps this could work in combination with the current methods (like "hover to select" in lighttable thumbnails doesn't preclude "click-to-select" or "multi-select").

**Comment by s7habo** [comment]
> Perhaps this could work in combination with the current methods (like "hover to select" in lighttable thumbnails doesn't preclude "click-to-select" or "multi-select").

That would be a super elegant solution! 
From the behavior in the lighttable you can even take over the grayscale differences between already selected object and the object that is highlighted when hovering over it.

**Comment by s7habo** [comment]
To demonstrate what I mean in my last post, I will demonstrate again how Inkscape handles objects.

As for selecting paths, darktable behaves similarly to Inkscape when the objects in Inkscape _have a fill_. 

Here we have a path with the fill in Inkscape. This is what the cursor looks like outside of object, that is before hovering over the object:

![Cursor1](https://user-images.githubusercontent.com/38165484/115192852-a6bb8d00-a0eb-11eb-9265-08fb882323ec.jpg)

When hovering _over the path_ (cursor turns white and gets a cross arrow on the right as an indicator that it can now be selected with the right-click): 

![Cursor2](https://user-images.githubusercontent.com/38165484/115193151-12055f00-a0ec-11eb-9a4b-e7e30d871458.jpg)

Now, if the path has no fill, you can select it only over its _contour_, that is, indication for the selection appears only when _hovering over the_ _contour_ of the path.

Outside the path:

![Cursor3](https://user-images.githubusercontent.com/38165484/115194397-b8059900-a0ed-11eb-850d-814790b0ef83.jpg)

Hovering over contour. Note how the selection indicator appears _already short before_ hovering over the contour. This ensures that you can still select the path even if you zoom out a lot. Now the path can be selected:

![Cursor4](https://user-images.githubusercontent.com/38165484/115194446-c489f180-a0ed-11eb-8eef-460f6d250a84.jpg)

Inside the path. Now we have the normal cursor again. Path is no longer indicated for selection:

![Cursor5](https://user-images.githubusercontent.com/38165484/115195564-3282e880-a0ef-11eb-93e0-349e023e79bc.jpg)

Now we can select another object that is inside the path when hovering over its contour:

![Cursor6](https://user-images.githubusercontent.com/38165484/115195853-8c83ae00-a0ef-11eb-9501-d54b800d2ed3.jpg)
