### ISSUE TITLE
When loading - darktable.exe caused a Breakpoint at location 00007FFF33DF9052 in module KERNELBASE.dll.

### ISSUE THREAD

**Issue by Myron-S** [darktable-org/darktable#8700]
Simply, the application will not start,  A console window is shown for a fraction of a second and after about 30 seconds darktable fails to load and produces the error report shown here.

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                :  Microsoft Windows 10 Pro 10.0.19042 N/A Build 19042
* Memory            :  32,651 MB
* Graphics card     :  Intel(R) HD Graphics 630 and  NVIDIA GeForce GTX 1060
* Graphics driver   :  Intel:27.20.100.9316 and  NVIDIA:27.21.14.6231

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? yes with version 3.4.0
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes

[darktable_bt_GA0N10.txt](https://github.com/darktable-org/darktable/files/6329893/darktable_bt_GA0N10.txt)
[darktable_bt_ZAD210.txt](https://github.com/darktable-org/darktable/files/6329894/darktable_bt_ZAD210.txt)

**Comment by johnny-bit** [comment]
Analyzing log in `darktable_bt_GA0N10.txt` clearly points the issue to `OpenCLOn12.dll` which is a microsoft project https://github.com/microsoft/OpenCLOn12 that tries to map opencl via directx12 and it clearly fails. You can try either disabling it and relying on proper OpenCL drivers (nvidia ones on windows should be fine, I have GTX 1060 and no problems with it) or you can try to file an issue with https://github.com/microsoft/OpenCLOn12

on a side note: darktable 3.5.0+250 is older commit, so you'd be advised to try and run newest build if you build yourself. Or try 3.4.1.1 (that's the one recommended currently for windows).

Ultimately - this is not a darktable bug.

**Comment by Myron-S** [comment]
Just now found https://github.com/darktable-org/darktable/issues/8567#issue-842523190

Disabling OpenCL worked.  

How do I configure darktable to only use the nvidia's opencl?   I have the latest studio drivers installed.

**Comment by jenatali** [comment]
You can disable OpenCLOn12 by uninstalling the OpenCL and OpenGL Compatibility Pack. I have a fix for this crash that's out for review now (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10303). Once it's reviewed and merged I can update the package to prevent this issue.
