### ISSUE TITLE
Corrupted output and darkroom view on amdgpu with opencl

### ISSUE THREAD

**Issue by edio** [darktable-org/darktable#8703]
**Describe the bug/issue**

Similar to #8000, however I was unable to make any connection between enabled modules and output.
Rather after some some trigger event _darktable_ enters an invalid state in which OpenCL starts producing corrupted outputs consistently. While in this state, modifications to the pipeline corrupts the darkroom view as well. 

Turning off OpenCL fixes both the darkroom view (on first edit) and the export feature. However re-enabling OpenCL makes the issue reappear on first export or first edit.

Restart of the _darktable_ fixes the issue allowing OpenCL again, however the issue comes back after a trigger event happens.

So far I observed following trigger events for this issue:
* exporting multiple images at once (not all images come out corrupted, but this is not consistent. Reexporting corrupted image does NOT fix it, reexporting a valid image may result in a corrupted output)
* exporting an image multiple times

**To Reproduce**
1. Import provided raw and xmp into darktable
2. Turn on opencl processing
3. Export the image at least twice
4. (!) Observe second and following renderings corrupted
5. Try editing an image
6. (!) Observe darkroom view corrupted

**Expected behavior**
OpenCL should produce the same results as CPU-based rendering

**Platform**

* darktable version : 3.5.0+1548~gd751803e8
* OS                : Linux 5.11.10-1-MANJARO
* Linux - Distro    : Manjaro
* Memory            : 32 GiB
* Graphics card     : Integrated AMD Radeon™ Graphics (AMD Ryzen™ 7 Pro 4750U)
* Graphics driver   : amdgpu
* OpenCL installed  : opencl-amd 20.30.1109583-1
* OpenCL activated  : yes
* Xorg              : 1.20.11
* Desktop           : KDE
* GTK+              : 3.24.28
* gcc               : 10.2.0
* cflags: unknown. I have a PKGBUILD used to build the binary and I see following `cmake` invocation there
```
     cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DCMAKE_INSTALL_LIBEXECDIR=/usr/lib \
        -DCMAKE_BUILD_TYPE=Release \
        -DBINARY_PACKAGE_BUILD=1 \
        -DBUILD_USERMANUAL=False \
        -DUSE_LIBSECRET=ON \
        -DUSE_LUA=ON \
        -DUSE_COLORD=ON \
        -DBUILD_CURVE_TOOLS=ON \
        -DBUILD_NOISE_TOOLS=ON \
        -DRAWSPEED_ENABLE_LTO=ON \
```

Corrupted outputs examples (all from the same source, produced in different darktable sessions. Shows that the result is somewhat random):
![DSCF5976_01](https://user-images.githubusercontent.com/787439/115142888-ccde2000-a04c-11eb-9560-ae1730f23db2.jpg)
![DSCF5976_02](https://user-images.githubusercontent.com/787439/115142891-d071a700-a04c-11eb-803a-b318ebb592fa.jpg)
![DSCF5976_03](https://user-images.githubusercontent.com/787439/115142896-d1a2d400-a04c-11eb-8da1-cd274bef8fc1.jpg)

Raw file and xmp to reproduce:
https://drive.google.com/drive/folders/1zLGheGRwiJiyIdc-gUEhU-xrr7_Mp1Ye?usp=sharing

**Comment by johnny-bit** [comment]
Based on your description I can conclude that the issue is caused by opencl drivers/hardware rather than darktable.

In order to make sure  try with stable version (eg 3.4.1) of darktable. If it exhibits same/similar issues during normal re-export or multi-image-export then we'll be certain it's drivers/hw issue. If that's the case your best way to deal with issue is to file a report with amd drivers team and ultimately amd itself.

Sidenote: OpenCL on cpu is usually not beneficial at all performance-wise and integrated GPUs might not have necessary capabilities/power to be worthwhile for OpenCL processing.

**Comment by edio** [comment]
@johnny-bit 
Thanks, I'll check if it's the same on 3.4.1 and will let you know

> Sidenote: OpenCL on cpu is usually not beneficial at all performance-wise and integrated GPUs might not have necessary capabilities/power to be worthwhile for OpenCL processing.

There is noticeable performance in my experience: darkroom view becomes more interactive, pipeline lag is roughly halfed comparing to cpu-only processing.

**Comment by edio** [comment]
After you mentioned opencl implementation, I realized, that my opencl-amd package was very old (not in the official repos, hence missed during normal updates). I updated it to the most recent version (20.50) and I can no longer reproduce the issue.

Closing this as invalid. Thanks for your help!
