### ISSUE TITLE
Custom targets support for color calibration module

### ISSUE THREAD

**Issue by XAndrey** [darktable-org/darktable#8705]
**Is your feature request related to a problem? Please describe.**

I need an ability to use not only 6 color targets in color calibration module but other custom tables.

**Describe the solution you'd like**

Please add a feature for adjust each color of color table. If i have not "xrite"© color checker table. For example, by entering RGB codes for each cell.

**Alternatives**

**Additional context**

![IMG_20210418_162955](https://user-images.githubusercontent.com/20306883/115147432-9bbd1a00-a063-11eb-9e31-3cf4896b5120.jpg)
![IMG_20210418_163007](https://user-images.githubusercontent.com/20306883/115147435-9eb80a80-a063-11eb-8561-0d2933c8c21c.jpg)

**Comment by XAndrey** [comment]
Main information with color description for each cell in source file darktable\src\common\colorchecker.h

**Comment by XAndrey** [comment]
These are values for that china target, converted from RGB to LAB:
`                                    .values = {
                                              { "A1", { 38.037, 11.929,  13.073 }, { 0.087, 0.125}},
                                              { "A2", { 69.647, 13.036,  16.477 }, { 0.250, 0.125}},
                                              { "A3", { 55.145,  0.464, -27.339 }, { 0.417, 0.125}},
                                              { "A4", { 43.356,-16.464,  24.370 }, { 0.584, 0.125}},
                                              { "A5", { 59.387, 14.224, -29.083 }, { 0.751, 0.125}},
                                              { "A6", { 84.456,-33.054,   0.877 }, { 0.918, 0.125}},
                                              { "B1", { 64.337, 45.852,  64.200 }, { 0.087, 0.375}},
                                              { "B2", { 42.100, 22.696, -49.750 }, { 0.250, 0.375}},
                                              { "B3", { 56.577, 54.103,   7.508 }, { 0.417, 0.375}},
                                              { "B4", { 32.278, 25.296, -29.727 }, { 0.584, 0.375}},
                                              { "B5", { 85.681,-40.170,  60.928 }, { 0.751, 0.375}},
                                              { "B6", { 74.752, 24.727,  75.084 }, { 0.918, 0.375}},
                                              { "C1", { 27.618, 24.865, -49.240 }, { 0.087, 0.625}},
                                              { "C2", { 55.308,-37.768,  28.452 }, { 0.250, 0.625}},
                                              { "C3", { 40.360, 54.430,  29.717 }, { 0.417, 0.625}},
                                              { "C4", { 89.285, -9.369,  86.651 }, { 0.584, 0.625}},
                                              { "C5", { 51.266, 53.392, -21.546 }, { 0.751, 0.625}},
                                              { "C6", { 54.410,-20.709, -24.697 }, { 0.918, 0.625}},
                                              { "D1", { 98.964,  0.005,  -0.010 }, { 0.087, 0.875}},
                                              { "D2", { 91.292,  0.005,  -0.009 }, { 0.250, 0.875}},
                                              { "D3", { 80.604,  0.004,  -0.009 }, { 0.417, 0.875}},
                                              { "D4", { 59.377, -0.191,   0.524 }, { 0.584, 0.875}},
                                              { "D5", { 42.375,  0.003,  -0.005 }, { 0.751, 0.875}},
                                              { "D6", { 20.788,  0.002,  -0.003 }, { 0.918, 0.875}} } };`

**Comment by johnny-bit** [comment]
No. That's very incorrect. cheap chinese targets have no regimen to be accurate and consisten between prints making them absurdly finnicky. They also tend to have different reflective properties between each colour patch and react differently in different lighting scenarios. that makes them unusable for color calibration and prohibits them from being included in released module.

We don't even accept colour targets that are of high quality but vary between print runs (like say Wolf Faust).

If you wish to use that colour target then you can maintain your own patchset that adds them to color calibration.

**Comment by XAndrey** [comment]
> If you wish to use that colour target then you can maintain your own patchset that adds them to color calibration.
How can i make it?
Do i need to maintain my own fork with 2 files for it: "channelmixerrgb.c" and "colorchecker.h"? I already have done this custom build for myself.
Or there is another way, more convenient and versatile?

**Comment by johnny-bit** [comment]
You need to maintain a fork and I think only `colorchecker.h` is needed

Now regarding the chinese color target you have - can you answer following questions:
- what color space does it use to specify values? (many colorspaces have tri-stimilus "R/G/B" values)
- what are the primaries for colorspace used?
- what is the min/max value?
- does your conversion yeld bi-directionally correct results?
- are the patches verifiable with accurate colorimeter?

If you can't answer at least one of those questions then really using said color target is no better than guessing.

I'm not trying to discourage you from maintaining own fork etc, but only warning to all that unverifiable color targets aren't viable.

**Comment by XAndrey** [comment]
channelmixerrgb.c file i have updated to add another one target without replacing existing.

About other things - i am agree. Cheap chinese target looks not as RGB numbers on back side of it and i'm going to get spyder checkr 24.

Maybe you are totally right - rough target will not do a work, that we are waiting from color calibration.
I was interesting to do some custom target profile to this Adour target, but if it so different from front side to back side - it doesn't make sense at all.
