### ISSUE TITLE
watermark: fails on exporting at >32K pixels

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#8715]
**Describe the bug/issue**
When exporting an image at size greater than 32K pixels in the larger dimension, the watermark iop fails to apply a watermark, instead generating an error message to the console after Cairo fails to allocate a drawing surface.  The failure occurs even if the scale is set very small such that the actual stamp is far smaller than 32K pixels.

The watermark is correctly applied regardless of input image size if the output size is less than 32K pixels, whether or not high quality resampling is enabled (so clearly the resampling happens before watermark).

**To Reproduce**
1. Open an image with larger dimension greater than 32767 pixels
2. Apply a `simple-text` watermark
3. Observe that everything looks fine in darkroom, regardless of zoom level (though actions on an image that large will be slow)
4. Export the image at full size
5. Observe that the watermark has not been applied to the exported image, and an error message has been printed to the console:
   * `[watermark] Cairo surface error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)`
6. Export the image at size 32700 pixels and observe that the watermark is correctly applied.

**Expected behavior**
The watermark should be applied regardless of output size.

**Platform**
* darktable version : 3.5.0+1726~g1dc69e0b1
* OS                : Linux
* Memory            : 64GB 
* OpenCL installed  :  no
* gcc               :  8.4.0
* CMAKE_BUILD_TYPE  :  Release

**Additional context**
I found this on post-editing some very large stitched panoramas (250-350 megapixels).  I looked at the code in the watermark module, and while it's technically possible to avoid the Cairo limit when the actual stamp size is below the limit, doing so would require a substantial rewrite.  Low priority since processing images that large will be rare for the foreseeable future.

**Comment by TurboGit** [comment]
This is a limitation of cairo. To bypass it a part of the watermark module needs to be rewritten. Probably not easy and the current code is so to have a good quality output.
