### ISSUE TITLE
quick-access panel interferes with shape displays

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#8716]
**Describe the bug/issue**
While the quick-access panel is the active tab in darkroom, drawn shapes do not display their outlines, and in create mode the cursor remains the default arrow cursor instead of changing to a custom cursor.  Paths and brushes can not be created, and existing shapes can't be edited.

This affects both blend masks and the retouch module.

**To Reproduce**
1. Load an image into dt using a new/empty config dir
2. Ensure that the Quick Access Panel is the current tab in the right-hand panel
3. Type "exposure" in the search box
4. Set +2 EV (to make things obvious) and enable a drawn mask
5. select Circle
   * notice that the cursor stays unchanged and there is no circle outline drawn
   * try Scroll, Shift-Scroll and Ctrl-Scroll to see that size, feathering, and opacity can be adjusted as normal
   * click to place a circle and note that it is in fact placed
6. repeat Steps 5.x using Ellipse
7. select Path
   * notice that clicking has no effect
8. select Brush
    * again, no change in cursor, but Scroll, Shift-Scroll, and Ctrl-Scroll work as normal
    * attempting to Click-Drag has no effect
9. select Gradient
    * again, no shape outline is drawn, the cursor remains unchanged
    * note that Shift-Scroll and Ctrl-Scroll work as normal; plain Scroll has no effect (as will be seen later)
    * click to set the gradient is successful, but the gradient will be straight even if Scroll was used
10. select Brush again, and switch to the active-modules tab by clicking the tab's icon
    * notice on moving the mouse back into the image that the cursor has now changed to the Brush cursor, and drawing a brush is successful
    * after placing a brush, the other shapes are now drawn as well
11. repeat 2-10 using the Retouch module

Note that in step 3 it is necessary to use the search box rather than following the full-module link in the QAP, as the latter also switches tabs while a search does not.

**Expected behavior**
Shapes should be drawn, brushes/paths should be creatable regardless of which tab is current.

**Platform**
* darktable version : 3.5.0+1747~gc22f6a90e
* OS                : Linux
* Memory            : 64GB
* OpenCL installed  :  no
* gcc               :  8.4.0
* CMAKE_BUILD_TYPE  : both Release and Debug

**Comment by elstoc** [comment]
@AlicVB could you take a look please
