### ISSUE TITLE
Liquify should allow users to set location and strength with: mouse down - move cursor - mouse up

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8727]
When using liquify, it seems the moment I trigger the mouse down event e.g. to drop a point into my image, the module starts processing without taking the mouse cursor move and then mouse up event into account. This means users are unable to set the point's location and vector strength based on: mouse down - cursor move - mouse up.

To reproduce, in the liquify module
- click on draw point
- mouse-down somewhere and move the mouse
- after the first mouse down event the module starts processing and the gui freezes for a second

Users then need to manually adjust the strength vector once the gui un-freezes again instead of being able to draw it.

Is there for this design decision? Can liquify take the mouse down and mouse up events into account to set both an initial location as well as a strength vector?

Thoughts?

**Comment by TurboGit** [comment]
> When using liquify, it seems the moment I trigger the mouse down event e.g. to drop a point into my image, the module starts processing without taking the mouse cursor move and then mouse up event into account. This means users are unable to set the point's location and vector strength based on: mouse down - cursor move - mouse up.

This works for me ! And you didn't specify the version in which it was reproduced on your side.

**Comment by daniel-j-h** [comment]
It is the latest Darktable 3.4.1, I've tried the pre-built binary and also compiled it on my own on another laptop.

I've just tried it on an image I _just_ imported without any modules applied (other than the scene-referred workflow defaults) and it works smoothly. It looks like I hit this problems only when I have already some modules applied, on images I want to liquify a tiny bit more after modifying them.

The use case I have is modifying my image (filmic, crop & rotate, lens correction, denoise, tone equalizer, etc.) and then down the road liquifying some smaller parts like the background. And then liquify hangs as described and does not allow me to use the mouse movement for the strength vector.

**Comment by MStraeten** [comment]
liquify is very early in the pipe, so changing something there results in reprocessing the whole later parts of the pipe. Depending on your hardware this kills responsiveness.
So if you need a responsive behaviour you'd better use liquify at the beginning of your editing process. Or temporarily deactivate modules later in the pipe, liquify, then reactivate the modules...

**Comment by TurboGit** [comment]
> That's exactly what this ticket should be about! hugs Liquify should not start the processing when the user triggers the mouse down event, but only when the user triggers the following mouse up event.

I agree with that. It makes sense indeed.

**Comment by TurboGit** [comment]
@daniel-j-h I have a fix in #8736 if you can test this on your side it would be great.

I have been able to reproduce the issue disabling OpenCL on my side and enabling many slow modules. Now the pipe is refreshed only when the button is release making the placement of a liquify node lot more fluid.
