### ISSUE TITLE
Retouch module: restrict inpaint source to visible pixels

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8731]
When using the retouch module, some tools in there allow the user to select a target (inpaint here) and a source (take pixels from here). When inpainting at the borders, the source by default gets sometimes set by Darktable outside of the image.

This has two problems
1. The inpainting can not properly work because the source pixels are non-existent, but more importantly
2. if the source area is completely outside of the image (and e.g. hidden by the modules menu gui on the right), there is no way for the user to move the source back into the image, making it impossible to retouch some of the borders (especially the right one for me, since the default source area seems to be right of the target area)

Is there a way to make the default source selection smarter and e.g. clip to the image's bounds?

**Comment by MStraeten** [comment]
You can first select the source with shift+click inside the image

**Comment by daniel-j-h** [comment]
Great to know! But should the source still be restricted to visible pixels?

**Comment by MStraeten** [comment]
Unfortunately by default retouch comes after crop and rotate in the pixel pipe. So you can‘t use a cropped source by default. If you move retouch below crop and rotate in the right side panel it might be a working solution.

**Comment by MStraeten** [comment]
Btw the current behaviour is discussed in https://github.com/darktable-org/darktable/pull/8673

**Comment by MStraeten** [comment]
seems to be solved via new standalone crop module (later in the pipe) so think about closing this …

**Comment by johnny-bit** [comment]
I'll pre-emptively close since now a more streamlined "crop" module is after retouch, which makes proper retouch & crop sense.

If there's still problem even using new crop module then we can either re-open this one or start a new one.
