### ISSUE TITLE
Tiling failed for module 'demosaic' output might be garbled

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8735]
I just ran into a glitch resulting in the demosaic module erroring out producing garbage.

I can reproduce it and because the image neither contains personal nor sensitive data (I was playing around with glass refraction) I want to share the image and xmp sidecar file with you.

Here is how it looks like; before and after the crop is applied (see history). Without the last crop applied, it works just fine.

![screengrab-1](https://user-images.githubusercontent.com/527241/115424325-e7f09180-a1fe-11eb-8cad-279ae0114eee.png)

![screengrab-2](https://user-images.githubusercontent.com/527241/115424311-e1621a00-a1fe-11eb-876a-3b006cc90689.png)

I've uploaded the original image and the xmp sidecar file here: https://we.tl/t-3ktEnPibvW (the link is valid for 7 days, if you need the data for longer, please back it up or tell me to re-upload it).

In case it matters: Ubuntu 20.04, Darktable 3.4.1, OpenCL not active, Camera is a Fuji X-T20, demosaic settings are Markesteijn 3-pass, color smoothing: 5 times. In settings host memory limit (in MB) for tiling is set to 8192, and minimum amount of memory (in MB) for a single buffer in tiling is set to 2.

Anything else you need from me?

**Comment by daniel-j-h** [comment]
Note: I've just found https://github.com/darktable-org/darktable/issues/8491 which might be related (unclear to me).

**Comment by TurboGit** [comment]
For some reasons that I don't explain the last step (crop&rotate) is having a crop of 0x0 pixel. Reset the module and crop again, all seems fine.

**Comment by jenshannoschwalm** [comment]
> For some reasons that I don't explain ...

You probably meant "I can't explain" ? I guess we might want to look into crop&rotate, it should not allow such a crop in committing parameters ?
