### ISSUE TITLE
Please fallback the removal of zone system tool

### ISSUE THREAD

**Issue by feeshy** [darktable-org/darktable#8737]
Zone System is removed in darktable 3.4.

With Zone System, which part of the image is going to change is previewed clearly,

while Tone Equalizer does not come with a preview, it is not a qualified alternative for Zone System.

**Comment by MStraeten** [comment]
zone system is further available in the group of deprecated modules. If you need to use it, you can include it in a style you can apply whenever you need it or simply select it from the group.
Btw: there’s also a preview of the mask in toneequalizer.

**Comment by feeshy** [comment]
> zone system is further available in the group of deprecated modules. If you need to use it, you can include it in a style you can apply whenever you need it or simply select it from the group.

It's not easy to find it. However, thanks for not removing it completely.

> Btw: there’s also a preview of the mask in toneequalizer.

Zone system highlights the affected areas in an intuitive way. In tone equalizer, you just don't know which areas are going to change when you move the sliders, the preview is quite hard to understand.

**Comment by MStraeten** [comment]
if you want to change a specific area you can do this without dragging sliders by pointing on the area and scrolling the mousewheel.

**Comment by feeshy** [comment]
> if you want to change a specific area you can do this without dragging sliders by pointing on the area and scrolling the mousewheel.

There's some slight difference in their way of previewing. I don't see one of them as an alternative for the other:
  zone system - highlights all the affected lightness areas of the adjustment. You see the change BEFORE the sliders are moved.
  tone equalizer - preview acts like operating a mask. You know the specific area you point, and some other parts at same level, are going to get affected, yet not knowing which other parts exactly until you scroll the wheel.
