### ISSUE TITLE
confusing names in import

### ISSUE THREAD

**Issue by kevinvermassen** [darktable-org/darktable#8744]
Hi 

I don't know if this is the right place but here I go.

I'm using 3.5.0~git1792.411f33fde-1

When importing pictures there used to be two options: image... and folder...

Now there are import-in-place... and copy and import... The tooltips are saying 'select a folder to import from' and 'select a folder to import from (shortcut: CTRL + SHIFT +I)'. I think that's a lot more confusing than 'image' and 'folder'. Maybe it can/should be renamed again?
![Screenshot from 2021-04-21 17-10-06](https://user-images.githubusercontent.com/76734170/115578084-3ff1cb80-a2c5-11eb-8110-e696a30d38ab.png)
![Screenshot from 2021-04-21 17-10-40](https://user-images.githubusercontent.com/76734170/115578086-408a6200-a2c5-11eb-96fd-36b749edec09.png)

**Comment by phweyland** [comment]
The names reflect correctly the function but the tooltips are weird, agreed.

**Comment by kevinvermassen** [comment]
Thank you!
