### ISSUE TITLE
Fujifilm X-E4 support

### ISSUE THREAD

**Issue by zinga666** [darktable-org/darktable#8750]
Note: I already opened an [issue](https://github.com/darktable-org/rawspeed/issues/268) at darktable-org/rawspeed - don't know if this is enough and/or if you want to keep this here for reference or close as duplicate.

**Comment by kmilos** [comment]
@zinga666 If you have the camera, please also consider [submitting the white balance presets](https://github.com/darktable-org/darktable/wiki/White-balance-presets) - it's not guaranteed we can just copy those over from X-T4 or X-S10...

**Comment by zinga666** [comment]
@kmilos Hi, unfortunately I don't - I rather plan on buying it in the future and just wanted to make sure it would be supported in darktable until then... Should the WB presets still be missing when I bought the camera I would of course try to help out. :-)

**Comment by mtoupsUNO** [comment]
Hello, I am attaching white balance presets for the X-E4 as generated by `extract_wb_from_images.sh`. I hope this helps.

[darktable-whitebalance-20210521.tar.gz](https://github.com/darktable-org/darktable/files/6527063/darktable-whitebalance-20210521.tar.gz)

**Comment by johnny-bit** [comment]
thanks @mtoupsUNO ! once darktable-org/rawspeed#272 lands I'll be able to add it :)

**Comment by kmilos** [comment]
@johnny-bit Please consider adding all darktable requests ahead of rawspeed - users can edit camera.xml by hand and enable their cameras after the release if need be. They can edit the source files and recompile.

**Comment by LebedevRI** [comment]
This was fixed by e8b2af41a065d74d9b7ff29f85675191ed886d71.
