### ISSUE TITLE
Black rectangles along darkroom image view edges

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/darktable#8755]
Issue: Open opening an image file in the darkroom, the user may encounter a series of black rectangles along the left and top edges of the image

**To Reproduce**

1. Open an image into the darkroom.  Black blocks appear along the images as described above.  Sometimes they will appear after zooming in or out after modifying a module setting.  There are also times when they will simply disappear and not return.
2. This only affects the editing screen.  The blocks do not appear in exported images.
3. This is more of a distraction than anything else, but it's probably worth correcting.

**Screenshots**
See attached.

**Which commit introduced the error**
I first noticed this with Development verision 3.5+1620.  It does not occur in Release 3.4.1.1

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

darktable version : 3.5.0+1620~g47fbd509a (but occurs in all versions of 3.5)
OS : Windows 10
Memory : 8 GB
Graphics card : AMD A8-7410 APU with AMD Radeon R5 Graphics, 2.20 Ghz
Graphics driver : Unk
OpenCL installed : Yes
OpenCL activated : No (Open CL always causes my system to lock up - different issue)
Xorg : Unk
Desktop : HP Pavalion
GTK+ : Unk
gcc : Unk
cflags : Unk
CMAKE_BUILD_TYPE : Unk

![darktable 3 5+1785 Screenshot](https://user-images.githubusercontent.com/61152378/115799698-08f3e680-a3a7-11eb-8966-a6d25aa21990.png)

**Comment by MStraeten** [comment]
which demosaic algo is active?

**Comment by Dave22152** [comment]
Hi Martin, I had RCD enabled.  I went ahead and tried different algos, and sometimes the blocks would disappear, change around or minimize.  But it was always temporary and they return at one point or another.  I also tried different options for color smoothing and match greens.  They have an impact, but don't fully eliminate the occurrence.  It's definitely something new with ver 3.5

**Comment by MStraeten** [comment]
There was a fix for this behaviour: #8696 
Maybe there are some further issues...

**Comment by Dave22152** [comment]
Reading through #8696, there was a comment that AMaZE seemed immune, but I can say with certainty that the problem occurs there as well.  Screen shot attached.

Is it best to continue the discussion on #8696, or here?  I'm new to the process and will do what's best for the group.

![darktable 3 5+1785 Screenshot with AMaZe](https://user-images.githubusercontent.com/61152378/115935749-d6f38a80-a461-11eb-9764-361deadb19aa.png)

**Comment by paolodepetrillo** [comment]
I am seeing the exact same thing now, running the latest 3.5.0+1865~gcef01d03b on Arch Linux with OpenCL disabled. Just noticed it a few minutes ago, haven't tried to troubleshoot yet.

**Comment by jenshannoschwalm** [comment]
This is not a zipper artefact. 

It might be NaNs generated somewhere.

**Comment by TurboGit** [comment]
Can you try again with latest version on master branch ? TIA.

**Comment by paolodepetrillo** [comment]
I'm not seeing it now, on master with or without the #8767 change. But I was only ever seeing it intermittently, never had any consistent steps to reproduce it. And I did see it with demosaicers other than RCD.

When I saw it yesterday, it was always exactly 32 black squares starting from the upper left corner and running along the top. At 'small' and 'fit to zoom' zoom levels where the entire image was visible, the artifact appeared to extend over the same region of the image:
![Screenshot_20210423_235027](https://user-images.githubusercontent.com/3238173/115963539-c0931080-a4ed-11eb-87be-6108c8204205.png)
![Screenshot_20210423_235240](https://user-images.githubusercontent.com/3238173/115963540-c0931080-a4ed-11eb-91d2-cb4b73c8e4dd.png)

I never saw it on the left side or any other edge. In one case the blocks appeared with the topmost row of pixels black, and then the remainder of the blocks was blue. Didn't get a screenshot of that one.

**Comment by jenshannoschwalm** [comment]
I do not really think it's rcd related, I just remembered such artifacts and wanted to make sure until thecause has been found

**Comment by Dave22152** [comment]
I just tried it with the latest master (3.5+1874, compiled this morning) and did not see the artifacts under any of the demosiac algos.

**Comment by jenshannoschwalm** [comment]
@Dave22152 is the issue still valid? If so --> please confirm so i will further investigate or if not valid any more --> please close issue.

**Comment by Dave22152** [comment]
@jenshannoschwalm - I haven't seen the issue in the last several build versions, so I think we can close it.  Thanks!

**Comment by Dave22152** [comment]
I've been working with DT 3.5.0+2226 and have been seeing this issue again.  There is a difference in that the squares are no longer black, but are colored.  

The circumstances are pretty much the same... and seem independent of the demosaicing algo. Open a file and the square appear.  Changing the demosaic option, zooming in or, or changing the color smoothing or match greens will temporarily remove them, but they're reappear at some later point.  

One curious thing is that the artifacts will affect masking (see attached), and DT modules will respond to them, but fortunately they do not show up as part of the exported JPEG.  For example, I can isolate the artifacts and darken them with the exposure module, but the edit does not appear on the exported JPEG.
![DT 3 5+2226 showing square artifacts](https://user-images.githubusercontent.com/61152378/119266467-f8f34080-bbb8-11eb-92e4-c8b8e069e884.JPG)
![DT 3 5+2226 - artifacts while masking](https://user-images.githubusercontent.com/61152378/119266470-fabd0400-bbb8-11eb-86dc-b1a4057a8df7.JPG)



I'm not sure if this is new issue or a continuance of this now-closed one.  Please let me know how to proceed.

**Comment by jenshannoschwalm** [comment]
I think this is an issue again with NANs fired up the pipeline. A late merged pr has made the default compiler math as -ffast-math so there might be more modules affected. This is certainly not a zipper artefact or demosaicing issue

To further investigate i would suggest to open a more precise new issue, you should add
1. a raw file
2. plus the sidecar xmp file for that
3. log output from darktable -d all
4. use the very latest master code

ok?

**Comment by Dave22152** [comment]
No problem, but I might need some additional guidance on step 3, because I’ve had problems getting DT to run in debug mode. I’ll let you know.

**Comment by johnny-bit** [comment]
IS this in any way connected to https://github.com/darktable-org/darktable/issues/8644?

**Comment by Dave22152** [comment]
It could be, except that report cites Fuji, where I am experience this with Canon. Also, he’s observing artifacts along the bottom edge, where I see them mainly along the left edge 

And most importantly, his artifacts show up on export, where mine seem to disappear on export

That doesn’t mean that they aren’t related, but I don’t think he’s seeing the same issue that I’m experiencing

**Comment by jenshannoschwalm** [comment]
I think we can focus here on something working wrong with a module, whatever we find out. But it is not reasonable to assume a demosaicing issue here - for the fuji there can be such a problem in markj.

But let's go first with the image, xmp plus deb output.
Open a terminal and do "darktable -d all" until you observe the problem, close darktable and save the console output to a text file or write directly to a log file via redirection.

**Comment by Dave22152** [comment]
Ok, I ran DT in debug mode and performed more testing.  GitHub won't allow me to upload the raw and XMP files, so I need to guidance on how to get them to you.  The debug file is blank, but I can send that to you for completeness.  Also, I ran this on DT 3.5.0+2226, which is not the latest, but it's still fairly recent (I just didn't have the time to compile a new version as of yet... I hope this is ok)

I'm coming to believe more strongly that this is somehow related to demosaicing.  I ran through all of the modules in the XMP file and the problem only begins when modifying Demosaic and zooming in or out.  There are also times where nothing happens until you change a setting within the Demosaic module.  

Let me know if you need more information or testing.

**Comment by jenshannoschwalm** [comment]
Yes, i certainly need
1. the raw file, please use any file sharing service to provide that
2. open any text console like "gnome-terminal" or whatever you have and type "darktable-disable-opencl  -d all". There will be a huge amount of text written and that is exactly what i need.
3. start development on that image (click on the "discard history" button to do so) until you observe the issue.
4. do a screenshot
5. close darktable
6. send xmp plus the screenshot also to the filesharing service. (you can also rename the files by adding a .txt at the end of filename)
7. Please update you dt to latest master and don't forget to clean up before compilig

Please understand, i can't reproduce here and really need all that to get an access to the "maybe problem". Also you have a windows system and that's unknown to me. Plus a system with a maybe wrong opencl as you desrcibed. I am really interested in fixing this - if there is a problem on dt side - but i have no chance until all this is provided ...

**Comment by Dave22152** [comment]
Hi there,

 David Goldberg ***@***.***) invited you to edit the folder " darktable display anamoly " on Dropbox.

 David said:
 "Copies of raw file, XMP, screenshot, and debug data, as requested" 

 [1] 
Enjoy!
The Dropbox team
 

[1]: https://www.dropbox.com/l/scl/AADllyy2pVOm0siDLfPJs0e560jeuvW3p9s

**Comment by Dave22152** [comment]
@jenshannoschwalm, yes I fully understand and I appreciate your help.  I was able to get the debug log to work correctly and sent everything to you via my Dropbox account. Hopefully you can access the files from the link above.

For this test, built the latest master from this morning and started with a clean raw file with no XMP.  In settings, I selected workflow default to "none" and chromatic adaptation to "legacy", so that neither Filmic RGB, basecurve, or Color Calibration were active. OpenCL was inactive and demosaic was set to RCD (but as I mentioned, it occurs under any of the options)

The anomaly appeared upon opening the files after I zoomed in and out.  You can see them as dark blue squares on the left edge (usually they are more pronounced along the left and top edges) I did not change any active module settings and did not invoke any other modules.

I hope this helps, otherwise let me know what I can provide.

Thanks again!

**Comment by jenshannoschwalm** [comment]
@Dave22152 , thanks for the files. I read through the log file, looked the xmp and there isnothing suspicious. Also tested on my system and there is nothing to reproduce. At least we have no NaNs here. So - atm i have no idea whats going wrong.

What's worrying me, what you describe seems so obvious and easy to reproduce, why is it "just you". Not in an offending way but what might be the reason for your system being affected and not those by the majority of people using master branch.
1. Windows? Mmmh
2. Relatively low memory 
3. cpu specific problem with reaching wrong code path
4. ...

Point 2 could result in tiling issues. Unfortunately there is no dt switch option to "force tiling" so i can't test here. 
Lets try it with more debug output on your side.
`darktable -d memory -d dev --disable-opencl` 

@paolodepetrillo can you still confirm by using the images provided? A short info about your system if affected?

**Comment by piratenpanda** [comment]
Same stuff happens to me as well from time to time on latest git. Looks also a bit different here (Arch Linux, 32 GB RAM, intel i5 7600K)
![Bildschirmfoto von 2021-05-23 10-32-34](https://user-images.githubusercontent.com/920721/119622940-f89cb480-be07-11eb-9b9a-ad0562ec9062.jpg)

Also I didn't find a way to reproduce this yet. It can happen if you open the image the first time, default modules, and it doesn't seem to be affected by the demosaicing method as has been mentioned

**Comment by jenshannoschwalm** [comment]
@piratenpanda your 32GB of ram makes a tiling problem very unlikely. You have no dedicated graphics card and have opencl disabled?

**Comment by Dave22152** [comment]
Hi there,

 David Goldberg ***@***.***) invited you to edit the folder " DT Additional Debug " on Dropbox.

  [1] 
Enjoy!
The Dropbox team
 

[1]: https://www.dropbox.com/l/scl/AAC42u2YwQgFV3rdbf_RFhe1UF7crseKQzo

**Comment by piratenpanda** [comment]
> @piratenpanda your 32GB of ram makes a tiling problem very unlikely. You have no dedicated graphics card and have opencl disabled?

both images were still with opencl on. And yes AMD RX580. I am currently trying to see if it still hapens with the command you posted above (disabling opencl and full debug output)

**Comment by Dave22152** [comment]
@piratenpanda, could you try zooming in to 100x to see if you the same edge issues that I'm experiencing?  FWIW, they're easier seen at 400x.  I'm only seeing this at the left and top, but it seems you have it all around the perimeter.

**Comment by jenshannoschwalm** [comment]
AMD and OpenCL are sometimes sort of an adventure...

**Comment by piratenpanda** [comment]
Can't seem to reproduce it anymore it seems. Maybe a driver update fixed it for me. Can't say for sure. Will keep an eye on it

**Comment by Dave22152** [comment]
FWIW, I just completes a full system and driver update and still have the problem

**Comment by paolodepetrillo** [comment]
I haven't seen the problem at all since my last post Apr 24 and cannot reproduce the problem now with @Dave22152 file.
I am running Arch Linux with a Core i7-5820K, 16GB RAM, GTX 1080, tried with OpenCL on and off, and have been keeping Arch up to date and always running the latest darktable master.

I did see the blue squares instead of black once.

**Comment by jenshannoschwalm** [comment]
@Dave22152 what you describe and screenshotted with the "working" message is normal, that's just a preliminary image to get you informed whats going on. 

I am sorry here, can't find anything that gives me a clue and as i can't reproduce so far.

**Comment by Dave22152** [comment]
@jenshannoschwalm, I understand.  It might very well be system specific and not reproducable.  I appreciate you putting the time and effort into it.  Perhaps some others might encounter the issue and provide better clues as to what's going on.

**Comment by jenshannoschwalm** [comment]
I think we sorted out it's not a demosaicer issue.

You observe "strange border colors with the working message", that is ok as we use a "preliminary" and very fast primitive demosaicing step only to show that something is happening.

There have been some issues around with NaN generated in some modules, this looks very much like that.

Did you hear of someone else with a "likely same" issue, if yes please give me a hint to further investigate. Otherwise it seems to be a very specific issue for you. BTW you made sure all residules in the building or runtime directories have been removed before building, also you checked to clear the opencl kernels?

Otherwise i think you should concider to close this issue until there is a better understanding of what might be wrong.

**Comment by Dave22152** [comment]
@jenshannoschwalm, whenever I create a new build I completely delete the darktable folders under the home and opt directories, so I beleive I'm starting out from scratch each time with no residual files.  I'd appreciate any advice if I'm missing something else.

I can go ahead and send a query out on the PIXLS site to see if anyone else has seen this and if they can give better clues.  If nothing comes up then I'll go ahead and close out the issue.

**Comment by jenshannoschwalm** [comment]
Don't know about any maybe win-specific things. If you are using opencl that would also mean to remove the cached kernels but i understand you disable that while compiling or via --disable-opencl. I am just curious what might be the problem - there have been some issues around describing "symptoms" as you have but they could all be tracked down - at least i am not aware of any report either here on github or pixls that seems alike. If you find something i have overseen, i would appreciate a hint!

I think low-mem has been ruled out here.

Any problem with one of your build libs - i simply don't know anything about that.

We could also have some sort of race condition, you could check with darktable -t 1 - that will slow down the whole dt thing but at least would give another hint.

**Comment by Dave22152** [comment]
Open CL is now completely disabled on my machine, so its not even an option!  I've asked on the PIXLS site, so maybe someone could provide some insight.

I'll check into the potential race condition and let you know.

**Comment by Dave22152** [comment]
Compiling the build under the -O3 settings and as a generic build appears to have corrected the problem, so I'm closing the issue.
