### ISSUE TITLE
[dt_ioppr_check_so_iop_order] missing iop_order for module vibrancergb

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#8757]
**Describe the bug/issue**

I just built DT from master and now I get the following error msg:
```
[dt_ioppr_check_so_iop_order] missing iop_order for module vibrancergb
ERROR: iop order looks bad, aborting.
```

I just saw the changes w.r.t. the vibrancergb slider, e.g. https://github.com/darktable-org/darktable/commit/d746b56304eb9f476ae70d1ed932d222eacc27c9, what does this mean for old DT database entries / sidecar files which use the old vibrance(rgb) module?

The commit (by @TurboGit) which causes this error is: d8da4de28555bd61fc6dad3b3d9e1dad7843b3f1
Can we just remove `vibrancergb` from all operations without making sure older database entries / sidecar files are not updated accordingly?

**Comment by TurboGit** [comment]
Clean the build AND install directory.

**Comment by da-phil** [comment]
Thanks for pointing out the simple solution :sweat_smile: 
Ups, I didn't know this could happen, I guess I shall delete my install folder before each DT cmake install call.

**Comment by TurboGit** [comment]
> Ups, I didn't know this could happen

It happens very very rarely (except for devs trying things) but here we have a special case where a module as just been removed. This is not something we do often, in fact I think it is the first time as the module was live since only 2 months and the formulae used was not up to the quality desired.
