### ISSUE TITLE
Import in place seems broken....at least for WIndows version

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#8761]
![image](https://user-images.githubusercontent.com/44409419/115908282-f70e5400-a437-11eb-9849-3f88475017ae.png)

I get to the first step ...the files are shown

![image](https://user-images.githubusercontent.com/44409419/115908428-27ee8900-a438-11eb-9666-5b93d4e13c80.png)

Then I am left with this...doesn't matter what folder I try.

![image](https://user-images.githubusercontent.com/44409419/115908586-5c624500-a438-11eb-8aed-f0e9e8203542.png)

Not sure if there is a subtle change I missed about how to use this????

**Comment by elstoc** [comment]
What folder are you selecting to start with. The idea is that you should select your "pictures" folder or something high level (so that most of the folders you might want to import from are sub-folders of that one). Then you should see the file tree on the left-hand pane.

**Comment by todd-prior** [comment]
I’ll check again…it looks like going to the second dialogue nothing is transferred so its just blanked …..recursive on or off…..It was a two step process…that doesn’t look to have changed but I think that recent commit may have messed things up in windows at least I am sure you will hear from others if this is the case…

**Comment by todd-prior** [comment]
Sorry just hiding my folder paths.....basically as of a few build ago import in place was a two step process...pick a folder...you selected open and then you got the second dialogue that was populated based on what you selected in the first dialogue...well now the second one comes up blank...no files or directories can be selected for import......if this still doesn't make sense I will create some dummy dir so I can show the full screen shots...

**Comment by elstoc** [comment]
Ultimately it needs a Windows dev to investigate really

**Comment by todd-prior** [comment]
There was a comment on the commit from Mint user….it was cryptic but it said neither works for me??

**Comment by LViatour** [comment]
I have the same problem on Linux Ubuntu 20.04 and 20.10 and OpenSuse

**Comment by elstoc** [comment]
I'm still not sure exactly what you're trying to do. When you select a root folder (top-left button) are you selecting a folder that contains folders or a folder that only contains files? If the latter, then we've still some work to do to make it clear how to use this functionality (but in the meantime #8758 might make it less painful). If the former then there might be an issue. As I said, without full screenshots it's hard to diagnose.

**Comment by todd-prior** [comment]
Invoking import gives the folder selection...so shown here 

![image](https://user-images.githubusercontent.com/44409419/115928402-08655980-a454-11eb-84c5-060488593a57.png)

Selecting the folder takes you normally to the next dialogue

![image](https://user-images.githubusercontent.com/44409419/115928512-36e33480-a454-11eb-87fa-f0e2999be88e.png)

With a newer build this dialogue will be empty. The files are not shown and I could find no way to ever display any files

**Comment by phweyland** [comment]
I'll try to build it on window

**Comment by LViatour** [comment]
first capture I chose an import folder containing raw files.
[https://lucnix.be/_data/i/upload/2021/04/23/20210423225621-32eec2b6-sm.png](url)

But after when I click on open darktable does not show raw files and import is not possible.
[https://lucnix.be/i.php?/upload/2021/04/23/20210423225617-21874991-sm.png](url)

Several of us have the exact same problem.

**Comment by todd-prior** [comment]
@LViatour  Just FYI your screenshot links don't work for me...again I always assume its me but maybe you might need to add them again..

**Comment by elstoc** [comment]
Again... **When you select a root folder (top-left button) are you selecting a folder that contains folders or a folder that only contains files?** You should do the former. For example I have my entire library in `/home/chris/photos`all stored in dated subfolders. So I select `/home/chris/photos` as my root and then the entire folder tree is displayed in the import dialog. I will probably never change the root folder again.

If you are selecting a folder that contains raw files but no subfolders then it currently won't work in master and you'll have to wait until #8758 is merged.

**Comment by phweyland** [comment]
My try on windows:

![image](https://user-images.githubusercontent.com/23012047/115939174-a61c5100-a473-11eb-8bde-556bfd1f3cb9.png)

**Comment by todd-prior** [comment]
Ya in that example above I see how it should work for sure. Just imagine instead you had gone at first to your \2020\2020 folder as the root...nothing would show so you tried now to go to the photos directory. I was not able to do that it just kept coming back to my first choice. I have since deleted all references stored in darktablerc and restarted DT and set it correctly to my base photo's folder at the outset and I am good...looks like maybe you have made some changes....thanks for looking in to it....

**Comment by s7habo** [comment]
Same Problem here. I'm on Kubuntu 20.04

If you open folder in "Import in place" you can clearly see raw files:

![Filder1](https://user-images.githubusercontent.com/38165484/115948083-39817080-a4cc-11eb-94e4-44b6948aee06.jpg)

but, if you click on "open" nothing is in the list:

![Filder2](https://user-images.githubusercontent.com/38165484/115948110-603fa700-a4cc-11eb-84dd-555b204dfd2a.jpg)

**Comment by s7habo** [comment]
> **When you select a root folder (top-left button) are you selecting a folder that contains folders or a folder that only contains files?** You should do the former.

This does not work:

https://drive.google.com/file/d/1d9sipDL3EsR_rr8rVPCBkkl0MUhntb5O/view?usp=sharing

**Comment by elstoc** [comment]
Again you're all reporting the fault I've mentioned (https://github.com/darktable-org/darktable/pull/8758#issuecomment-825648277) where you can't change back to a folder higher in the hierarchy. This is fixed in #8758.

**Comment by elstoc** [comment]
Now that #8758 has been merged could this be closed? Or are there other issues not resolved by that PR?

**Comment by s7habo** [comment]
Now it works to me. Thanks!
