### ISSUE TITLE
histogram constantly redrawn

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#8765]
Opening darktable with `darktable -d perf` shows that histogram is redrawn all the time, even when standing still, and seems to recompute the RGB color transform at each redraw in an infinite loop fashion. This pollutes `stdout` for other debugging and burn CPU cycles for nothing (about 15-20 ms of computation for each redrawing).

Color conversion should run only when pipeline is recomputed. The color-converted buffer should be cached otherwise.

Similarly, redrawings should happen only when the histogram buffer is invalidated or the mouse is over the histogram widget (easy to do through a GUI coordinates check, see all the curves and EQ modules for examples).

**Comment by ralfbrown** [comment]
Confirmed, under limited circumstances.  I'm only seeing the extra scope draws when the mouse pointer moves into or out of the text box in the watermark module (a big burst each time) and when the text cursor blinks on or off in the "search modules" text box (once each time).  Plus there's a single scope draw each time the dt window is exposed and when the mouse moves into or out of the histogram.  Each of these with three attendant colorspace transforms.

**Comment by johnny-bit** [comment]
Tagging @dtorop for him to see this report of constant redraw of histogram :)

**Comment by aurelienpierre** [comment]
I see the redraws even when the darktable window is minified on screen (not visible), for example when I'm in my IDE and started dt in its console.

**Comment by dtorop** [comment]
Ah! I'll look into it... More in a bit...

**Comment by dtorop** [comment]
>  extra scope draws when the mouse pointer moves into or out of the text box in the watermark module (a big burst each time) and when the text cursor blinks on or off in the "search modules" text box (once each time)

> even when the darktable window is minified on screen

Likewise here. A GTK-level bug? I tried "Show Graphic Updates" in GTK Inspector, which doesn't help much. Will keep looking.

>  Plus there's a single scope draw each time the dt window is exposed and when the mouse moves into or out of the histogram.

This may be "normal", but isn't ideal. Will see if can avoid this.

>  Each of these with three attendant colorspace transforms.

This is only in waveform mode, yes? The draw code uses `dt_ioppr_transform_image_colorspace_rgb()` for each channel as a "fast" gamma change routine, essentially to replace `powf()` with a lookup. At the time, this seemed like a clever speedup, but now it's quite clear that the better way would be to simply create a lookup and use `extrapolate_lut()`. Clearer, and less noisy to stdout.

Furthermore, this code doesn't need to run on every draw, just on process. (Perhaps I wrote it to work during draw back when it explicitly dealt with the display colorspace?)

I've been meaning to fix this for a bit. Will now...

**Comment by ralfbrown** [comment]
Yes, I had the histogram in waveform mode (my default).

**Comment by dtorop** [comment]
It appears that the many unnecessary redraws of the histogram widget is a long-standing problem, at least back to 1ab227ccb936d7f22c8062be3cad6b330920d69f (as far back as I could get the code to compile). The behaviors mentioned in https://github.com/darktable-org/darktable/issues/8765#issuecomment-826031856 will trigger this.

This wasn't that noticeable up until 855c230401f0c585b38c3ab7660d37f9d034f13a, which was the first commit that added `-d perf` output upon calls to `_lib_histogram_draw_callback()`, and hence exposed the problem.

There's two angles to deal with this. One is to improve the waveform drawing code so it doesn't do a bunch of needless colorspace transforms and hence chatter to stdout. I've got that nearly done, and will make a PR. The histogram draw code will still produce `scope draw took 0.0XX secs (0.0XX CPU)` messages on each redraw, though.

There's the underlying problem of what causes the multiple histogram redraws. "Show Graphic Updates" in GTK Inspector shows that the entire top part of the darktable window (down to the bottom of "search module") is redrawn every time the cursor flashes in the "search modules" textbox. I also see a lot of redraws in the right panel. I haven't been able to sort that out yet, but will keep on trying.

**Comment by dtorop** [comment]
I think this relates to #8698. Calling `dtgtk_drawing_area_set_aspect_ratio()` in widget draw calls `gtk_widget_queue_resize()` which bubbles up through the right panel and forces some redraws including to the histogram. You can test this by expanding a module affected by this (e.g. filmic rgb or contrast equalizer). The noisy stdout output happens then.

A fix is something like this (using filmicrgb as an example):

```diff
@@ -2688,9 +2688,6 @@ static gboolean dt_iop_tonecurve_draw(GtkWidget *widget, cairo_t *crf, gpointer
   dt_iop_filmicrgb_gui_data_t *g = (dt_iop_filmicrgb_gui_data_t *)self->gui_data;
   dt_iop_filmic_rgb_compute_spline(p, &g->spline);
 
-  const float aspect = dt_conf_get_int("plugins/darkroom/filmicrgb/aspect_percent") / 100.0;
-  dtgtk_drawing_area_set_aspect_ratio(widget, aspect);
-
   // Cache the graph objects to avoid recomputing all the view at each redraw
   gtk_widget_get_allocation(widget, &g->allocation);
 
@@ -3693,7 +3690,7 @@ static gboolean area_scroll_callback(GtkWidget *widget, GdkEventScroll *event, g
       //adjust aspect
       const int aspect = dt_conf_get_int("plugins/darkroom/filmicrgb/aspect_percent");
       dt_conf_set_int("plugins/darkroom/filmicrgb/aspect_percent", aspect + delta_y);
-      gtk_widget_queue_draw(widget);
+      dtgtk_drawing_area_set_aspect_ratio(widget, aspect / 100.0);
     }
     return TRUE; // Ensure that scrolling cannot move side panel when no delta
   }
```

I can work on a PR for this. There may be other problems as well, of course. And even with the above fix, the scroll still triggers a redraw of the histogram which doesn't seem strictly necessary.

**Comment by dtorop** [comment]
A further note for reference -- I think the scope redraws when moving mouse into/out of the scope and when clicking scope buttons is coming from GTK transitions on those buttons. Due to overlaying of the buttons on top of the scope, every update to the buttons during the transition triggers a redraw of the scope graph.
