### ISSUE TITLE
channelmixerrgb updating gui when not enabled

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#8766]
**Describe the bug/issue**
Digging into bauhaus sliders I added print statements to the sections where the slider values were changed.  I used the exposure slider to test, but I noticed that every time I changed exposure the chroma, hue, and temperature sliders were also getting set.  The problem was that I was using legacy chromatic adaptation and the color calibration module wasn't enabled.

**To Reproduce**
1. Replace bauhuas.c with the attached version and compile
2. Run dt from a terminal
3. Set chromatic adaptation defaults to legacy
4. Select an image in lighttable and discard the history stack to ensure that color calibration is not enabled
5. Open the image in darkroom
6. Once all the slider messages stop, scroll the exposure slider to change the value.
7. Notice that the hue, chroma, and temperature slider values get set from the messages in the console

**Console Output**
```
printing temp in gui_changed at 3359

in slider set setting pos to 5003.000000 for temperature
in slider_set_normalized with pos of 0.142973 for slider temperature
in slider_set_normalized with pos of 0.480000 for slider exposure
in slider set setting pos to 274.955994 for hue
in slider_set_normalized with pos of 0.763767 for slider hue
in slider set setting pos to 19.071577 for chroma
in slider_set_normalized with pos of 0.190716 for slider chroma

```
**Expected behavior**
Slider values shouldn't be getting set when the module is disabled.

**Additional context**
A simple check to ensure the module is enabled in gui_update() fixes the problem, but I"m not sure it's the best fix.  @aurelienpierre could you look at it please?

[bauhaus.zip](https://github.com/darktable-org/darktable/files/6368999/bauhaus.zip)

**Comment by aurelienpierre** [comment]
All GUI widgets are inited like that. gui_init then gui_update are run, no matter if module is enabled or not, because we need something to draw in their box. Or does that run continuously ?

**Comment by aurelienpierre** [comment]
Additionnaly, channelmixer does nothing particular and uses the general `iop_api.h`, so that would be something to address in there directly by avoiding `gui_update` and `gui_changed` to be called if module is disabled or doesn't have focus.

**Comment by dterrahe** [comment]
Parameter values are still saved, even if the module is disabled, so that it can later be enabled with the appropriate values.

In theory we could skip gui_update when module currently disabled and not expanded (so values not visible anyway) and then do a gui_update when enabling or expanding. But using a shortcut to change a slider _also_ enables the module so we'd have to make sure the correct parameters have been gui_updated _before_ executing any shortcut. With complexity and (slight) perf implications.

Not saying it would be impossible. Just that I would keep an eye on the feature freeze date because I see a potential for many bugs when changing such a fundamental assumption.

**Comment by aurelienpierre** [comment]
Right, forgot about key accels.

**Comment by wpferguson** [comment]
> Or does that run continuously ?

It runs every time a slider is changed in the gui.  The reason I raised the issue is that it's the only module that does that, so the behavior is different.  Not sure if it was intended or accidental.  If it's intended, then let's close the issue.

**Comment by aurelienpierre** [comment]
temperature, hue and chroma don't have a parameter, they are all generated by the program from the x and y chromaticity coordinates stored in params. So the program needs to constantly update them. The thing is there is no way anymore to check in `gui_changed()` if x and y actually changed before updating the others, but that was done in the original code before introspecting it.

**Comment by wpferguson** [comment]
That's why I asked :smile:
