### ISSUE TITLE
The Mix control of Contrast Equalizer behaves inconsistently

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#8769]
**Describe the bug/issue**

Contrast Equalizer has a mix control to adjust the strength of the effects. The provided presets are often heavy-handed when used with mixture  value of 1.0 but become useful when turned down.

But this mix adjustment  behaves differently in different scenarios: using saved presets and adjusting masks for two things. I think this is a solely a UI issue.

I just guess from the behavior that the value of the mix control is baked in the curves of the Contrast Equalizer, therefore the mix control loses usefulness with very subtle changes.

**To Reproduce**

Two distinct ways I have encountered the problem.

1. Open up a clean instance of Contrast Equalizer
2. Select one of the provided presets
3. Set mix to 0.5
4. Save as a new preset
5. Load up the preset in a clean history. The effect of the module will be as "should be": the preset mixed to 0.5. But the mix control shows 1.0. In this scenario if I set mix to 2 then I get the preset in its original strength (0.5 * 2 = 1). 

Second is a more difficult, only discovered this today.

1. Open up a clear instance of CE 
2. Make curves or select one of the presets
3. Set mix to 0 (I often want to apply a mask and brush before seeing any effects)
4. Set masking to "drawn mask"
5. Now mix is 1 but the previously set 0 as a starting point. (0 * 2 is still 0.) Because the control has a value range of -2 to +2 I cannot recover the effects of the module without resetting.

**Expected behavior**

Mix control value should be restored when loading preset, separately, likewise it shouldn't reset when adjusting masking options.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.4.1
* OS                : linux
* Linux - Distro    : gentoo

**Comment by parafin** [comment]
I guess they are some left-over use-cases not handled by #8219

**Comment by progo** [comment]
> I guess they are some left-over use-cases not handled by #8219

Sorry, I didn't notice there was some work being done in master about this.

I went through the issues mentioning "contrast equalizer" but #8197 must have escaped me. 

My bad!
