### ISSUE TITLE
Adopt user-friendly localization system

### ISSUE THREAD

**Issue by issu-shooter** [darktable-org/darktable#8779]
**Is your feature request related to a problem? Please describe.**
I found darktable years ago, and recently decided to help translate it into Chinese. But I'm a non-tech guy and find the translation process you provided which involved building the software from source brings some pain. I think such localization method is not that straightforward and not easy for all the non-tech guys, which is also the majority of darktable's users. Also, using such method translators can't work closely with development, make translation easy to become outdated.

**Describe the solution you'd like**

Other projects I have contributed use Weblate or Crowdin, which I found very useful. If darktable supports these platforms I suggest adopting them. If FLOSS software are preferred, then Weblate is best choice. Both services offer FREE OF CHARGE plans for Free Software/open source software.
**Alternatives**

Here are some alternatives beside weblate
https://alternativeto.net/software/weblate/
**Additional context**
darktable is not just software, it is about photography and color, people who both have a gift in this and is  multilingual 
I find Chinese media industry is dominated by Adobe and other proprietary software, but I think it's time to change. Let's make darktable popular over there!

**Comment by elstoc** [comment]
We already use weblate for [dtdocs](https://github.com/darktable-org/dtdocs) so that doesn't seem an unreasonable request. @paperdigits would this be a simple thing to do?

**Comment by Nilvus** [comment]
And do you talk here about documentation or darktable UI translation too? For that last one, po files are a really great way and easy to do with software like poedit. For documentation, indeed solutions you describe are way better and that's a work in progress with dtdocs.

**Comment by paperdigits** [comment]
Setting up a new weblate component is easy, but we would need everyone to use weblate. It doesn't work well if some use weblate and some don't.

**Comment by issu-shooter** [comment]
Well, actually I mean both the UI and documents. In facr PO files themselves are fine to me, but the hard part lies in the compile part. I understand compiling from newest source means having the newest strings in the POT file, but compile from source is not that a user-friendly action...

In fact I convinced a few friends who are familiar with Adobe lightroom and Davinci Resolve to contribute here, and they have no knowledge in GNU/Linux at all. I am learning photography stuff and find most people in this field have few computer skills. I want things become easier for them, in terms of using and contributing.

**Comment by paperdigits** [comment]
> but the hard part lies in the compile part. I understand compiling from newest source means having the newest strings in the POT file, but compile from source is not that a user-friendly action. 

Compiling actually isn't that hard, and there are literally step-by-step instructions on how to do so.

**Comment by issu-shooter** [comment]
well as long as I learned how to compile, it won't be a problem for me (learning now actually). But this still blocks those who have no Linux device, my point is to make others contribute in an easier way.
Man, I failed to get to the point in last comment...

**Comment by TurboGit** [comment]
Notre that there is no need to compile to do the translation. See 

https://github.com/darktable-org/darktable/wiki/Translations

**Comment by issu-shooter** [comment]
Well, that's a good method, but still lacks straightforwardness. And I think since Weblate requires less steps than current method and is just as simple as poedit, people won't have too much trouble migrating.

**Comment by paperdigits** [comment]
> people won't have too much trouble migrating.

yes well we need to actually check with the people who do the translation, rather than just speculating.
