### ISSUE TITLE
Increase max height of "collect images" Box in lighttable

### ISSUE THREAD

**Issue by Kn0rk** [darktable-org/darktable#8780]
**Is your feature request related to a problem? Please describe.**
I am using quite a few tags and the amount of scrolling needed in the default (fixed) height of the "collect images" box in lighttable is really annoying. 

**Describe the solution you'd like**
I would like the box to be larger (at least the same height as image information) or ideally grow in height dependent on content up to a max-height.

**Additional context**

I did some digging and it might be here:
https://github.com/darktable-org/darktable/blob/master/data/darktableconfig.xml.in
```
<dtconfig>
    <name>plugins/lighttable/collect/windowheight</name>
    <type>int</type>
    <default>500</default>
    <shortdescription>height of the collect list</shortdescription>
    <longdescription>maximum height the collect list in lighttable will grow to before scrolling</longdescription>
  </dtconfig>
```
Can this also be adjusted in the new CSS feature? I would like to avoid compiling my own version of Darktable.

**Comment by elstoc** [comment]
You should be able to Ctrl+scroll over the collect module to increase its height.

**Comment by Kn0rk** [comment]
Thanks for the reply. I am on Version 3.4.1 in Ubuntu and using CTRL+Mouse wheel does not change the height of the module for me.

**Comment by elstoc** [comment]
Works fine for me on 3.4.1 (ArchLinux). You need to be hovering the scrollable part of the module.

**Comment by Kn0rk** [comment]
Ah okay, I hovering over the Title. Hovering over the entries and CTRL+Scroll works. Thanks a lot!
