### ISSUE TITLE
New import dialog is slow in Windows

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#8782]
The new dialogs "import in place" / "copy and import" are quite slow, especially in Windows.
I have a collection not that big, 6.5K images, nevertheless when I start DT the dialog takes around 10 seconds to appear after pressing the button. Subsequent calls after the first take around 3 seconds.
In Linux times are about half of the above, still quite slow.
An there is no visual feedback, the buttons seem unresponsive, quite confusing.
At least the dialog should appear immediately and being progressively filled in, to provide feedback to the user.

**Comment by elstoc** [comment]
It's probably trying to build the folder tree. It only builds the first couple of levels to start off with, to try and reduce this time. Do you have a link to a slow device or a network share in your folder structure?

We didn't have an opportunity to test on Windows when merging this so any additional information you can provide would be useful.

Ping @phweyland.

**Comment by phweyland** [comment]
Just built the last master on windows (3.5.0+1882). I don't really see a difference between windows and linux (50.000 images).
As @elstoc said the recursive flag may make the difference.
When changing the root folder, this flag is automatically reset not to browse accidentally files in huge trees, except if there a last_directory. In that case I've considered that the flag should be valid. May be a mistake.
Could you confirm the problem is related to this recursive flag ?

**Comment by elstoc** [comment]
I still think it's best to clear the last_directory when changing root folder.

**Comment by phweyland** [comment]
> I still think it's best to clear the last_directory when changing root folder.

That's like that actually.
My last comment was just related to migration to the new version (root folder not defined).
I'll reset it in that case as well.

**Comment by Mark-64** [comment]
Ok, some more info.
I tun DT on a decent machine (Ryzen 3700x, 16GB RAM, nVidia 1060).
The program is on M.2 drive, while the collection is on a regular 7200RPM HDD drive. No links to network drives or slow media.
Recurse directory is not flagged, while ignore jpeg is.
Also in prefs "look for updated xmp" is not checked.
My collection is almost entirely one level only, a list of about 200 image folders inside the main folder, no multi-level organization (I am lazy).
To reproduce: 

- start the computer
- start DT
- press "import in-place"
- dialog appears in 10.3 seconds

From that moment, any further call takes 3.1 seconds.

**Comment by elstoc** [comment]
By default it iterates through the first two levels of directory structure looking for sub-directories. In that setup it's probably iterating through all of your files on the first go. I could see that taking a while.

**Comment by ralfbrown** [comment]
I saw much the same under Linux yesterday.  Left the dialog pointing at a test folder with (symlinks to) 43k images -- which takes 2m50 to load and build the dialog.  Restarted dt, and opening the dialog now takes 2m50....  In mousing over the folder names, something must have kicked off a reload, as dt went unresponsive again and I killed it after about a minute and a half....

Leaving the dialog pointed at a folder whose subtree contains 20k images, with the "recurse" flag checked, results in 50 seconds of apparent hang on opening the dialog while dt cranks through the tree.

BTW, a single directory of 5800 images takes less than a second to be shown, so there seems to be a point at which the Gtk tree build slows **way** down.  The 20k and 43k processing pegs a core for the entire time, so they aren't disk-bound.

Gtk 3.24.8
Glib 2.60.2

**Comment by phweyland** [comment]
I haven't found any file info saying that a folder has at least one subfolder (without scanning the folder)...

**Comment by elstoc** [comment]
There are some asynchronous ways to do some of these things. Is it possible those might help?

**Comment by phweyland** [comment]
> a list of about 200 image folders inside the main folder

how many images ?




> Left the dialog pointing at a test folder with (symlinks to) 43k images -- which takes 2m50 to load

@ralfbrown, With the change in #8787 I get 3-4 seconds for nearly 60k images. Could you be kind enoug to check if that improves your results ? TIA.

**Comment by AlicVB** [comment]
> Problem is we need to know if there are any subdirectories to know whether the folder is expandable. Is there a way to do that without going through all of the other files as well?

it's less beautiful, but there's lot of app that present all folders as expandable by default (with the arrow) and it's just when you try to expand them that the arrow disappear if there's no sub directories (I suspect they put a "dummy" sub-entry at first)...

for the population of the list of images (with recursive ticked or not) the ideal would be indeed to do that asynchronously (but that would mean lot of work too, I fear...)

**Comment by elstoc** [comment]
> it's less beautiful, but there's lot of app that present all folders as expandable by default (with the arrow) and it's just when you try to expand them that the arrow disappear if there's no sub directories (I suspect they put a "dummy" sub-entry at first)...

Yeah that might be the least-worst solution for now. Ugly though.

**Comment by phweyland** [comment]
> Could perhaps that behaviour be changed to scan the content of a folder only if it is actually selected?

If we have no way to guess if a folder has subfolders or not I see only one possibility: assume that all folders have subfolders, and make appear a fake expander everywhere. Clicking on an expander would scan the subfolder, and remove it if necessary. But that looks like a regression for the better organized users.

**Comment by AlicVB** [comment]
@phweyland : no problem, as it's for you, I won't claim any royalties :-D
Just to know, have you tried to just check for first subdir existence ? I'm not sure, but maybe this won't take so much time if we don't check for all subdir and don't add them to the treeview one by one (iirc, the treeview reconstruct lot of things each time the associated list change)

**Comment by phweyland** [comment]
> Just to know, have you tried to just check for first subdir existence

No, but if I'm not mistaken there is no subfolder in the critical case described first. So we need to check until the last file.
Also, this suggestion only works in the context of the fake expander.

**Comment by phweyland** [comment]
When one looks at the browser nemo for example, there is no fake expander, but it still needs some time to load the list of files when one clicks on the expander. I'm wondering how they do.

**Comment by elstoc** [comment]
Nemo _does_ use fake expanders on its directory-only view.

If you set up nemo to show the folder tree on the left-hand pane it includes expanders for every non-empty directory (presumably it just checks if there are any files and then exits when it finds the first one). 

When you expand the directory it just says _(Empty)_ if it has no sub-folders. For example, in the following, the directory `/bin/core_perl` has files (shown in the right-hand pane) but no subdirectories:

![Screenshot_2021-04-25_19-31-56](https://user-images.githubusercontent.com/9555491/116004978-fe328f00-a5fc-11eb-81f5-cfb02c5413ad.png)

**Comment by parafin** [comment]
On UNIX there is a well-known way to find how many subdirectories does a directory have without reading its contents - subtract 2 from number of hard links (second column of `ls -l` output).

**Comment by phweyland** [comment]
> Nemo _does_ use fake expanders on its directory-only view.

OK, you are right. On the right pane there is no expander if the folder is empty, but in that case that's easy.

**Comment by Mark-64** [comment]
> > a list of about 200 image folders inside the main folder
> 
> how many images ?

around 6.5k, I wrote in the first post.

#8787 does not solve the issue unfortunately

**Comment by phweyland** [comment]
> > > a list of about 200 image folders inside the main folder
> > 
> > 
> > how many images ?
> 
> around 6.5k, I wrote in the first post.

sorry, I haven't read correctly.

> #8787 does not solve the issue unfortunately

For sure, it improves only the images list.

to resume:
on one side: 200 folders + 6.5k images (HDD) + no images list display (no recursive) => 10 seconds the first time then 3 seconds
on the other side: 1200 folders + 58k images (HDD) + display images list (recursive) => 12 seconds the first time (after reboot) then 4 seconds (exit dt or not) (with #8787)

The cache disk does help ! :smile: 
The only folders scanning may not explain the slowness you see.

**Comment by ralfbrown** [comment]
> On UNIX there is a well-known way to find how many subdirectories does a directory have without reading its contents - subtract 2 from number of hard links (second column of `ls -l` output).

Doesn't work on btrfs partitions -- `ls -l` always shows 1 there....

**Comment by Mark-64** [comment]
> to resume:
> on one side: 200 folders + 6.5k images (HDD) + no images list display (no recursive) => 10 seconds the first time then 3 seconds
> on the other side: 1200 folders + 58k images (HDD) + display images list (recursive) => 12 seconds the first time (after reboot) then 4 seconds (exit dt or not) (with #8787)

With #8787
In Windows: first run 5.5 s, then 2.7 s
In Linux: all runs about 2.6 s
Recursive flag makes almost no difference in my case due to the flat folder structure

I would prefer fake expanders, but at the very minimum there should be a gui feedback "loading..." or similar when waiting for the dialog to appear

**Comment by parafin** [comment]
> > On UNIX there is a well-known way to find how many subdirectories does a directory have without reading its contents - subtract 2 from number of hard links (second column of `ls -l` output).
> 
> Doesn't work on btrfs partitions -- `ls -l` always shows 1 there....

This feature also isn't available on Windows (I suppose), so it can't be a solution anyway, but may be a heuristic that covers a lot of cases - if hard link number is 2, there are no subfolders. Though maybe there are cases when it's not true either.

**Comment by Dave22152** [comment]
I have noticed this behavior and it is VERY slow.  The previous releases that allowed you to type in the folder names was much faster and far more convenient (I will write this up as a separate issue).
