### ISSUE TITLE
Darktable crashes with Lightroom export selections and other issues (Windows 10)

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/darktable#8790]
**Issue**: Darktable crashes in the Lightroom mode when selecting either the reset or preset “hamburger”  In addition, target storage and file format options are unavailable so the user cannot select JPEG, TIFF, etc. Backtrace is attached.

**Steps to reproduce:** Open darktable and within Lightroom, click on either the reset or presets icons and the program will crash due to an unhandled exception

Before doing that, note that the options for target storage and file format will not expand, so the user cannot select a file export destination or the file format.

**Which commit introduced the error**
I first noticed all these issues with Development version 3.5+1874, it did not occur with version 3.5+1785 or earlier releases

**System Information**

darktable version : darktable 3.5.0+1874~g0f7dbd009
OS : Windows 10
Memory : 8 GB
Graphics card : AMD A8-7410 APU with AMD Radeon R5 Graphics, 2.20 Ghz
Graphics driver : Unk
OpenCL installed : Yes
OpenCL activated : No (Open CL always causes my system to lock up - different issue)
Xorg : Unk
Desktop : HP Pavalion
GTK+ : Unk
gcc : Unk
cflags : Unk
CMAKE_BUILD_TYPE : Unk
[darktable_bt_30FL20.txt](https://github.com/darktable-org/darktable/files/6377828/darktable_bt_30FL20.txt)

**Comment by phweyland** [comment]
Just had a look on window build 3.5.0+1882. Both export module reset and storage targets work fine.
Have you tried with a fresh config ?

**Comment by Dave22152** [comment]
I'll try that later today.  Can you verify that you can select the export file type as well?

**Comment by Dave22152** [comment]
Ok, I just pulled 3.5+1894, and the export module reset, storage targets and file type selections all work.  Recommended closing.
