### ISSUE TITLE
crop & rotate : disappearing grid lines

### ISSUE THREAD

**Issue by UsefGeorge** [darktable-org/darktable#8791]
**Describe the bug/issue**
switching between "darkroom" view to "lightroom"  view and back again ( without any changes ) the grid lines disappear :(

**To Reproduce**
1) remove data.db, library.db.  There is a .db that has the _Crop & Rotate defined with existing grid lines_ ( 3x3 ) ( i dont know who has it defined/retained). I can erase everything wiithout care, so dont do it on real productions.
2) run darktable
3) import a .JPG image ( no associated .xmp file ) crop & rotate Grid lines should be visible on the image.
4) "darktable" should be visable
5) switch to "lighttable"
6) switch back to "darktable"
at this point the **grid lines have disappeared**.
7) to continue on, if you rotate the image, the picture will loose some 5ev brightness. No cropping done, or shown. Thumbnail image in upper left corner seems unaffected,
8) switching back and forth between "lightroon" and "darkroom" does nothing - image retains the loss of light.  I think crop settings does nothing at this point either.

Fedora 32, dt 3.4.1

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**

**Comment by Nilvus** [comment]
@AlicVB: I think this is for you (probably) and maybe help to solve other issues about this module. On actual master (last commit from this morning), a step by step (tested on multiple images) to reproduce similar issue with that module:

- open an image in darkroom (with crop and rotate module never used/activated on that image)
- activate the module
- then only rotate the image (at this step crop grid is still there)
- close the module
- reopen it
- try then to crop : it's impossible (the grid is not visible and crop couldn't be done).

Switch the module to off then on make lines reappear and so crop possible.

**Comment by AlicVB** [comment]
I can reproduce. Seems to be a problem of focus : on reopening c&r doesn't get the focus, and so doesn't show all its on canvas drawings... What is surprising is that the crop module doesn't seems to be affected...

I'll try to have a look !

**Comment by AlicVB** [comment]
ok, I've found the bug, and I have the fix. It's the same fix as what I've done for crop module in https://github.com/darktable-org/darktable/commit/e4960d53ca7cb675e0f6e559aa6561b48bb41037
I've done it in the branch : https://github.com/AlicVB/darktable/tree/clipping_preview_ready

That said, I'm quite reluctant to push the fix in master now, because c&r is so sensible, that I'm really not sure to not have broken something else...
So the question is : is this issue critical enough to take the risk or not (open question, really)

**Comment by johnny-bit** [comment]
If it fixes the issue properly then why not integrate solution and have broader testing field in master? we'll have till code freeze to either revert or fix if anything bad pops up... or do point release if something pops up in general populace ;)

**Comment by Nilvus** [comment]
> That said, I'm quite reluctant to push the fix in master now, because c&r is so sensible, that I'm really not sure to not have broken something else...
> So the question is : is this issue critical enough to take the risk or not (open question, really)

I agree with @johnny-bit. We need to integrate this in master. It's a critical issue for this module, so need to be fixed. And we have a monnth to test this in master before 3.6.

**Comment by AlicVB** [comment]
OK, I've done the PR #9110 with a copy-paste of my warnings ;)
