### ISSUE TITLE
CSS for db lock dialog (and possible others)

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#8792]
**Introduction**
There is no margin for the db lock dialog.

**Describe the bug/issue**

**To Reproduce**
0. Before starting darktable create a lock file
    `$ echo > ~/.config/darktable/data.db.lock`
1. Start dt
2. See the dialog where text is close to border and not really readable.

**Expected behavior**
Some margins would be nice.

**Screenshots**

![image](https://user-images.githubusercontent.com/467069/116124891-2685c080-a6c5-11eb-8032-3744c886ee60.png)

press right button.

![image](https://user-images.githubusercontent.com/467069/116124994-474e1600-a6c5-11eb-86a0-8062b41b6e43.png)

press oui:

![image](https://user-images.githubusercontent.com/467069/116125041-52a14180-a6c5-11eb-9e25-4936127abd76.png)

**Platform**

* darktable version :master
* OS                : Linux

**Additional context**

For the first window this does not reproduce on English UI as there is some padding on the strings directly. As soon as a proper CSS is in place I'll remove the spaces.

**Comment by TurboGit** [comment]
@Nilvus : I have assigned this to you, let me know if you need more information. TIA.

**Comment by Nilvus** [comment]
Should be easy. I will try to spent some time really soon on CSS.

**Comment by Nilvus** [comment]
@TurboGit: this will need more than CSS visibly. The window is a simple window then box then label widget. I have tried many choices and no one is applied (margin and padding in window, box and/or label...) but it's always applied in other parts of the UI and breaks a lot of thing.

So one thing at least: add a specific tag for all those window (to avoid apply a margin on other darktable parts

Then find why margin or padding in such window (I tested here only db log dialog window) is not applied but applied on all other parts of darktable UI (where we don't want margin/padding added...). Is something in Gtk code that could that (some hardcoded setting)? And maybe for just this thing a hardcoded setting for all pop-up with same margin would be easier?

What your thoughts about that? @elstoc: if you have some ideas too.

**Comment by TurboGit** [comment]
@Nilvus : Nothing to do in CSS because at the time the dialogs are opened the CSS is not yet loaded. I'll add hard coded borders for this dialog.

**Comment by TurboGit** [comment]
This will give:

![Capture d’écran de 2021-05-05 19-59-56](https://user-images.githubusercontent.com/467069/117187717-81619b00-addc-11eb-8d33-a795fab72b37.png)

![Capture d’écran de 2021-05-05 20-00-24](https://user-images.githubusercontent.com/467069/117187759-8c1c3000-addc-11eb-9218-d6b243bcd46c.png)

![Capture d’écran de 2021-05-05 20-00-40](https://user-images.githubusercontent.com/467069/117187787-94746b00-addc-11eb-803e-ff73c61e4581.png)

**Comment by TurboGit** [comment]
This is with #8871.

**Comment by Nilvus** [comment]
> @Nilvus : Nothing to do in CSS because at the time the dialogs are opened the CSS is not yet loaded. I'll add hard coded borders for this dialog.

I was quite sure of something like that.

**Comment by Nilvus** [comment]
Your screenshot looks just great. I love that! Thanks.

**Comment by Nilvus** [comment]
I close this as your PR is not linked and we could consider this fixed.

**Comment by TurboGit** [comment]
> I close this as your PR is not linked and we could consider this fixed.

It is linked in one of the committ in the PR so would have been closed.
