### ISSUE TITLE
ICC input profiles unsupported?

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#8794]
**Describe the bug/issue**
Two ICC input profiles I sometimes used previously are no longer loadable. They appear in the input colour profile's selection menu, but attempting to load them results in the following messages on the console:
```
[dt_ioppr_set_pipe_input_profile_info] unsupported input profile 0 /home/kofa/.config/darktable/color/in/Nikon_D7000_Rawstudio_Advanced_Profile.icc, it will be replaced with linear rec2020
[dt_ioppr_set_pipe_input_profile_info] unsupported input profile 0 /home/kofa/.config/darktable/color/in/Nikon_D7000_ssf.icc, it will be replaced with linear rec2020
```

**To Reproduce**
1. Get the profiles from https://tech.kovacs-telekes.org/files/2021-04-26-darktable-icc/ (one is Glenn Butcher's profile from https://github.com/butcherg/ssf-data/blob/master/Nikon/D7000/spectroscope/, the other an old ICC I've extracted from RawStudio's https://github.com/rawstudio/rawstudio/blob/master/profiles/Nikon_D7000_Rawstudio_Advanced_Profile.dcp with some command I no longer recall :-P).
2. Place them in `~/.config/darktable/color/in/`
3. (Re)start darktable
4. Load a raw file
5. Assign either of the profiles
6. Check the console output

**Expected behavior**
Profiles are accepted as previously.

**Which commit introduced the error**
I'll try to bisect when I have more time.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.5.0+1867~ge33eb1469
* OS                : Linux - kernel 5.11.0-16-lowlatency #17-Ubuntu SMP PREEMPT
* Linux - Distro    : Ubuntu 21.04
* Memory            : 64 GB
* Graphics card     : nVidia 1060/6GB
* Graphics driver   : 460.73.01-0ubuntu1 
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 1:7.7+22ubuntu1 
* Desktop           : KDE (5.80.0 )/Plasma( 5.21.4)
* GTK+              : 2.24.33, 3.24.25
* gcc               : 10.3.0
* cflags            : 
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Comment by kofa73** [comment]
Hmm, I get the same with darktable 3.4.1.1 as well. I'm pretty sure the profile used to work. Maybe an OS issue? (I updated last week.)

**Comment by johnny-bit** [comment]
This might be the case where profiles are LUT based.

If this is false alert as you say, we wouldn't want to have false alert message ;)

Do you still observe the issue?

@dtorop - would you be able to take a brief look if the issue isn't already fixed?

**Comment by kofa73** [comment]
Glenn's profile is definitely LUT-based.

**Comment by dtorop** [comment]
I'll check. I do remember the relevant code has changed...

**Comment by kofa73** [comment]
I've checked with darktable 3.5.0+2353~gb3bc49ba4 and the situation has not changed: Glenn's profile gets applied, but the warning is printed:
`[dt_ioppr_set_pipe_input_profile_info] unsupported input profile 0 /home/kofa/.config/darktable/color/in/Nikon_D7000_ssf.icc, it will be replaced with linear rec2020`

**Comment by dtorop** [comment]
I think that the two profiles include CLUTs. A hacky check:

``` shell
$ iccdump in/Nikon_D7000_ssf.icc|grep 'A2B\|B2A'
  sig      'A2B0'
$ iccdump in/Nikon_D7000_Rawstudio_Advanced_Profile.icc|grep 'A2B\|B2A'
  sig      'A2B0'
$ iccdump out/Rec2020.icm|grep 'A2B\|B2A'
$ 
```

So long as there is a CLUT, `dt_colorspaces_get_matrix_from_profile()` will not return a matrix. That's just fine for colorin, as it will fall back to LCMS.

So I think the warning is erroneous.

But I'm trying to untangle the logic of `dt_ioppr_set_pipe_input_profile_info()` which is generating the error. The cases seem to be:

1. matrix profile: all fine
2. CLUT profile: all fine, colorin will use LCMS
3. camera input matrix: use it as matrix profile
4. error generating profile or invalid profile: generate a warning and fall back to linear rec2020

I think cases 2-4 are currently muddled. More as I think this through.

**Comment by dtorop** [comment]
Getting closer. There's no need to warn on CLUT profiles. To be proper, the input profile matrix only needs to be set to the camera matrix when the input profile _is_ a camera profile.

More in a bit.

**Comment by dtorop** [comment]
PR made to fix this logic -- curious if it works there.

The short version is that the warning is generally spurious and was triggered by CLUT input profiles. Despite it saying that linear rec 2020 would be used, colorin already had set itself up to use the requested profile. So in most cases this warning could be ingored.

**Comment by TurboGit** [comment]
@kofa73 : Please double check that current master is working for you now. TIA.

**Comment by kofa73** [comment]
Thanks, the warning is gone, the CLUT-based profile from Glenn is still working good.
