### ISSUE TITLE
Module order is always in `legacy` mode

### ISSUE THREAD

**Issue by baloe** [darktable-org/darktable#8803]
Upon importing `NEF` files into darktable, the module order is set to legacy and I have to manually switch it to v3.0 for every single file. As far as I know v3.0 should be the default.

**Platform**

* darktable version : 3.4.1.1
* OS                : Win10

**Comment by elstoc** [comment]
Have you checked `preferences > processing > auto-apply pixel workflow defaults`? It should be set to "scene-referred" (or "none") in order to use the v3.0 module order by default. If it is set to "legacy" it will continue to use the old module order for new images.

**Comment by baloe** [comment]
> Have you checked `preferences > processing > auto-apply pixel workflow defaults`? It should be set to "scene-referred" (or "none") in order to use the v3.0 module order by default. If it is set to "legacy" it will continue to use the old module order for new images.

Aha! That was the key. `auto-apply pixel workflow defaults` was indeed set to legacy.
