### ISSUE TITLE
[collect images] image filtering got severe regression after new import dialog got introduced by ee9ac742f

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#8804]
**Describe the bug/issue**
I have organised my pictures as following:

~/pictures/YYYY/YYYYMMDD_(event or job-code)/(subfolder per day of shoting)

That means the parent folder for event or job-code does not include any RAW files but the subfolder, they do.

I do move and rename my pictures with RapidPhotoDownloader (which actually offers the function to separate the pics per shooting day)

_In the past_ 
I imported the parent directory with dt and all was fine, I got that parent directory listed in the film roll of "collect images" module and saw all pictures at once and still did have the chance to further filter the collection per day if I wanted (and leave/remove that filter if I do not want anymore).

_Now wIth the new import dialog_ 
introduced by 3.5.0-1415-gee9ac742f (if I am not mistaken), you have to import a complete collection, e.g. for my case ~/pictures/YYYY. So far so good, but now in the "collect images" module you merely see the day by day folders but no more the parent folder with event or jobcode.

In below screenshot (sorry is German due to --configdir /tmp) you see several folders from August 2020. Those are all from a trip to Rostock in Germany. 
- There is no way _anymore_, to have all those pics in one collection in lighttable (e.g. to export them all at once)

![grafik](https://user-images.githubusercontent.com/49004103/116312751-282ab380-a7ad-11eb-824e-7c8fe5d0014b.png)

PLEASE no recommendations such like "...oh you better organize your photos differently..." 
- That org is not so uncommon, 
- it worked for many years, 
- more than 85k pics 
- and a five years differential backup behind. 
So there is no way for me to re-arrange. 

From my point of view we recently introduced a **severe regression**.

SIDE NOTE: me and my family we are in the progress of moving home. That situation has some issues in the background making it more severe and prioritised than usual. Any expected reply or involvement from my side might have huge delays (even my PC will be packed soon). I am expecting my self coming back to a little bit normal around August time frame but didn't want to let this rest by the time 3.6 would be out.

**Expected behavior**
Actually I just want to have it as it was before (e.g. like in the current official branch of 3.4.1)

**Which commit introduced the error**
AFAIK 3.5.0-1415-gee9ac742f 
@phweyland may I kindly ping you here

**Platform**
* darktable version : 3.5.0+1415~gee9ac742f-dirty and 3.5.0-1908-g26428873c
* OS                : Linux - kernel 5.11.11-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-465.19.01
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.11
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.26
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo" 

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes all since ee9ac742f*
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by elstoc** [comment]
It's not clear if you're using "import in place" or "copy and import" here. If you're using import in place, your folder structure should be entirely viewable in the collect.

If you change the collect module to folder view (rather than film roll) and shift+click on the parent folder name, this should show all images from the parent and all sub-folders at the same time in the lighttable. That would at least be a feasible alternative workaround for now (I hope). You can then double-click on the individual sub-folders to view them one-at-a-time.

**Comment by phweyland** [comment]
I think I got it.
Some time ago I've said that filmrolls and folders were not always equivalent. I have been contradicted and I haven't been able to show it.
Now, with the @AxelG-DE's example I understand better the code of dt_file_import and I have to admit this make sense.
Before the changes, with [folders...], import was creating only one filmroll corresponding to the selected folder and importing all images (recursive flag or not) into the same filmroll.
Now, import imports each image in its own folder = filmroll. In recursive cases, we get several filmrolls.

The previous behavior is more open than the current one (can group several folders into a single filmroll).

If everyone agree I can mimic this behavior with [import in-place...].
That will probably create a bug on collect on the go and come between folder and filmroll, but we should be able to solve that...

**Comment by phweyland** [comment]
> There is no way anymore, to have all those pics in one collection in lighttable (e.g. to export them all at once)

This may be not completely true as darktable-cli still uses the former filmroll process.

**Comment by ptilopteri** [comment]
I agree that filmrolls are not "folders" and should only be the same when
purposely imported as such.  I frequently imported a combination of images from 
differing directories as filmrolls in the past and all of the images were contained
in that filmroll.  I would expect that capability to continue.

tks,

**Comment by AxelG-DE** [comment]
> It's not clear if you're using "import in place" or "copy and import" here, or whether all of the images are imported correctly. If you're using import in place, your folder structure should be entirely viewable in the collect module.

Sorry for being unclear:
import in place and it practically imports all pictures correctly

Nope, the folder structure is not visible in image collection, merely the subfolders per day as shown in screenshot

> If you change the collect module to folder view (rather than film roll) and shift+click on the parent folder name, this should show all images from the parent and all sub-folders at the same time in the lighttable. That would at least be a feasible alternative workaround for now (I hope). You can then double-click on the individual sub-folders to view them one-at-a-time.

I found the "folder" filter, but how could I ever come to the idea to shift+click. (jaja, I know the doc....) I merely clicked it and found it does not show pics either.
Shift+Click is definitely an alternative

> > PLEASE no recommendations such like "...oh you better organize your photos differently..."
> 
> Nobody has suggested that you change your photo organization structure 

I was just anticipating and this is a preventive defence :-) [the hit doc barks, as we have a saying :-> ]

**Comment by AxelG-DE** [comment]
> > There is no way anymore, to have all those pics in one collection in lighttable (e.g. to export them all at once)
> 
> This may be not completely true as darktable-cli still uses the former filmroll process.

luckily I said "in lighttable", then it is true :-D

**Comment by AxelG-DE** [comment]
> The previous behavior is more open than the current one (can group several folders into a single filmroll).
> 
> If everyone agree I can mimic this behavior with [import in-place...].
That might be it. Thanks!
Actually I'd be happy (did not try yet) if copy and import also offers to paste the pic in day-by-day subfolder struct. Then you also need it in that branch, not merely in [import in-place]

> That will probably create a bug on collect on the go and come between folder and filmroll, but we should be able to solve that...

**Comment by TurboGit** [comment]
> Some time ago I've said that filmrolls and folders were not always equivalent. I have been contradicted and I haven't been able to show it.

I think I'm the one have said that filmrolls = folders.

Now, I still don't see how it could be otherwise when looking at the darktable database.

Tables:
- film_rolls : id + directory
- images : film_rolls.id + filename

So how can we have images in different directories placed into the same film_rolls ?

The only solution is maybe that filename could be a sub-path to the directory (a relative pathname) ? I have never seen that but I have also never imported recursively, so maybe that explain that.

**Comment by TurboGit** [comment]
> Actually I'd be happy (did not try yet) if copy and import also offers to paste the pic in day-by-day subfolder struct.

Isn't this already possible using the pattern when renaming files?

**Comment by elstoc** [comment]
I think this is the perfect use case for the folder filter in collect (due to my library structure I'd never really found one before). I'd never thought of using filmrolls like this but if there's a useable alternative, is there anything to fix?

**Comment by parafin** [comment]
I think having filmroll not always map directly to one directory is confusing.

**Comment by TurboGit** [comment]
I 100% agree with parafin. Seems confusing and needs corner case implementation to properly support this. I would be in favor of simplifying this part.

**Comment by phweyland** [comment]
> Now, I still don't see how it could be otherwise when looking at the darktable database.

Humm,... right. I should be wrong again. :(

Just tried `darktable --library :memory /path/to/images` with recursive flag (does not work with the new mechanism).
I get one filmroll by folder, confirming I was wrong.

Then I'm wondering how to reproduce the @AxelG-DE former behavior...

**Comment by AxelG-DE** [comment]
> Then I'm wondering how to reproduce the @AxelG-DE former behavior...

dt 3.4.1 and a sample set, as I outlined in the issue 😊 

Yes, using "folder" and shift+click in "collect" is a work around. However, in the past you didn't need to do anything after import, as it was the default behaviour with importing recursively, now several (3) additional actions required (recently we discussed one additional click :D) 

(sorry if I oversaw something in above tech discussions, just quick reaction on a notification email via phone)

**Comment by phweyland** [comment]
> I got that parent directory listed in the film roll of "collect images" module and saw all pictures at once

Just rebuilt 4.4.x branch to check.
Using [folders...] on parent folder, I get one filmroll per subfolder, ... as today.

**Comment by AxelG-DE** [comment]
@phweyland yes, I just now figured the same thing while creating a screen-recording.
3.5.0 adds that % after the folder name, current master does not.

If I add that % manually ot the filmroll, it works. So that would mean "mimik the behaviour" :-)

The screen-recording got 28MB in size (as I am currently out of training for kdenlive, but wanted to cut some part in between). Let me know if that is still needed, but I have the feeling, not necessary

**Comment by phweyland** [comment]
#8811 should mimic import 3.4.x behavior. Thanks for your patience.

**Comment by AxelG-DE** [comment]
It is on my to say thank you very much for patience and support @phweyland !

Did not test yet, as busy with packing but will do some time later...
