### ISSUE TITLE
segfault import Dt 3.5.0~git1909.3cfcb8e90a-1

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#8806]
I import in-place from the usb3 harddrive (recursive, ignore jpg & exif rate, apply metadata, 39635 img), Dt crash immediately

Ubuntu studio 19.10, 2x nvidia card, opencl on, ryzen7 32gb, upload from usb3 harddrive 1Tb

[darktable_bt_VJOM20.txt](https://github.com/darktable-org/darktable/files/6390459/darktable_bt_VJOM20.txt)
[terminal-dt23042021.txt](https://github.com/darktable-org/darktable/files/6390461/terminal-dt23042021.txt)

**Comment by elstoc** [comment]
I see there's an error in your log that seems to indicate your database is corrupt (sqlite 3 error 11).

Please could you retry with a clean configuration directory (or just temporarily rename your library and data databases) and see what happens?

**Comment by dim162** [comment]
I've done that before i published the report... I'm not an expert in database. So, i removed everything (backup before), restart & reinstall, it works. It happens after an upgrade, before le last one done this morning.

**Comment by dim162** [comment]
Thank you!

**Comment by elstoc** [comment]
So you're saying it works fine with a new configuration/database but that possibly the upgrade from an older version might have corrupted your database?

**Comment by dim162** [comment]
I don't know. I update every day, twice, & the last time, the upgrade asked me to modify the database, was last week. My workflow is very busy, since some months. I shoot twice a week, 50, 80 images. I keep the database as small as possible, so i purge non-essential images once a week. Furthermore, I kept back the data.db after restarted from scratch, all my presets!
