### ISSUE TITLE
import: scroll to selection doesn't work

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8809]
The new import-in-place functionality is supposed to expand the folder structure to the last selected folder and then scroll to it, but the call to `gtk_tree_view_scroll_to_cell` doesn't seem to work and I can't figure out why. If the last selected folder is off the bottom of the scrollable area, it remains invisible on launch of the dialog and you have to manually scroll to it.

@phweyland any ideas?

**Comment by elstoc** [comment]
I think it might have been introduced by #8787 because I'm sure it was working before that.

**Comment by phweyland** [comment]
> @phweyland any ideas?

not yet ....

> because I'm sure it was working before that.

You're lucky to have such a confidence in your memory  :)

**Comment by elstoc** [comment]
> You're lucky to have such a confidence in your memory :)

I reproduced the correct behaviour on an earlier version of master but I forgot to check what commit it was on before I upgraded to the latest. I'd assumed it was introduced by #8798 and I thought I'd still reproduce the correct behaviour after the upgrade, but I didn't.

**Comment by phweyland** [comment]
In fact expand was called twice ...
