### ISSUE TITLE
checkboxes retain background formatting after un-ticking them

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8816]
When ticking a checkbox its background changes (examples below from the "import in-place" dialog)

From this:
![Screenshot_2021-04-29_08-40-10](https://user-images.githubusercontent.com/9555491/116517330-b34b9c80-a8c6-11eb-942b-9f519c9ee133.png)

To this:
![Screenshot_2021-04-29_08-40-30](https://user-images.githubusercontent.com/9555491/116517349-bcd50480-a8c6-11eb-8eb4-c9d1f604ae18.png)

However, when unticking, the altered background color remains until you click somewhere else:
![Screenshot_2021-04-29_08-40-58](https://user-images.githubusercontent.com/9555491/116517385-c8c0c680-a8c6-11eb-83b5-dd1f0cf6d48e.png)

I think this is probably because the checkbox retains focus but it looks odd. IMO this needs to be fixed

**Comment by elstoc** [comment]
@Nilvus what do you think?

**Comment by elstoc** [comment]
I think removing the following from darktable.css would fix a lot of these sorts of odd issues I've been seeing recently:
```
dialog button:focus,
dialog checkbutton check:focus
{
  color: @button_hover_fg;
  background-color: @field_hover_bg;
}
```

**Comment by Nilvus** [comment]
> I think removing the following from `darktable.css` would fix a lot of these sorts of odd issues I've been seeing recently:
> 
> ```
> dialog button:focus,
> dialog checkbutton check:focus
> {
>   color: @button_hover_fg;
>   background-color: @field_hover_bg;
> }
> ```

I totally agree that no different background on checkboxes is better. But this is an add from @phweyland PR #8479 and as you can read in first comment, it's seems that you pinpointed this idea. So, if you want to remove those lines, I'm totally on for that, even if I approved the PR (I didn't check that behavior). And of course, if @phweyland agree on that.

**Comment by elstoc** [comment]
I can see the use case but it just looks messy most of the time (I've seen it a lot on the module groups setup window).

**Comment by phweyland** [comment]
I agree to remove this. gtk_widget_grab_focus() calls have already gone. Enter is captured at any time thanks to @elstoc suggestion. So highlighting focused items does seem to be useful anymore.

**Comment by elstoc** [comment]
Ok I'll submit a PR now

**Comment by Nilvus** [comment]
> EDIT: I still think that dt should have a kind of global behavior to show the focus, but that is another story...

On which part you would see that? I don't need that personally but with precise places you would see that, maybe we could start a "feature request" here and start thinking of ideas to do that?

**Comment by elstoc** [comment]
There may be a way to do things like that subtly with outlines or very slightly adjusted shading perhaps. They'd have to also take into account other shading as well so it might be difficult to do consistently.

Most of the time it will just draw attention to the fact that you can't tab between widgets in a logical manner though. Tab order isn't very well managed in Gtk.

**Comment by phweyland** [comment]
@Nilvus, The most evident part is about dialogs. In a lot of applications, hitting <tab>, you move from one item to the other, and you see on which item you are, either to key in a value or see the button which will be activated kicking <enter>.

On this particular dialog it doesn't seem very useful anymore, but others like collect or metadata preferences are good examples where we could set up everything only with the keyboard.

On core dt, people use shortcuts or mouse, which may be enough. Even so we could imagine having a standard way to navigate through the different components with the keyboard. But the benefit is not as obvious as for dialogs.

**Comment by elstoc** [comment]
For entry fields it's more obvious anyway, since there's a cursor. I seem to recall having to explicitly handle the tab to force the import module to let you tab between entries though, which was a pain to do. And again, Gtk is crap at this.

**Comment by Nilvus** [comment]
So if I understand you well, adding focus on buttons from keyboard move is not only CSS thing? Something to do (and if I understand you @elstoc, something hard to do) with Gtk?

**Comment by elstoc** [comment]
Something I've not found an easy way to do anyway. It doesn't seem to work by default, though I suppose it may do for simple cases.
