### ISSUE TITLE
Interface preferences / introspection

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#8818]
**Is your feature request related to a problem?**
For the preference setting we currently have defaults defined as "constant" expressions and if we change any of them
we see a marker as **not default** as here

![Bildschirmfoto von 2021-04-29 16-52-42](https://user-images.githubusercontent.com/50982232/116571438-5d4d1800-a90b-11eb-8171-70dc3086bac5.png)

A non default value seems to be detected via string compare but here i am absolutely not sure as i don't know and understand the introspection stuff at all.

While working on the `dt_configure_performance()` (i would like to have sane defaults depending on the hardware found) i ran into this problem (just one example)

Assume we define a function `int dt_default_worker_threads()` returning a proper number of threads it is perfectly valid to
include `dt_conf_set_int("worker_threads", dt_default_worker_threads());` in `dt_configure_performance()`.

Also we can have it in `darktableconfig.xml.in` as
```
  <dtconfig prefs="cpugpu" restart="true">
    <name>worker_threads</name>
    <type min="1" max="16">int</type>
    <default>dt_default_worker_threads()</default>
    <shortdescription>number of background threads</shortdescription>
    <longdescription>this controls for example how many threads are used to create thumbnails during import. the cache will grow to a maximum of twice this number of full resolution image buffers (needs a restart).</longdescription>
  </dtconfig>

```
This is fine but unfortunately the "default marking dot" as shown above does not recognize this as default any more.

**Describe the solution you'd like**
The introspection should **somehow** be able to handle this at least for bools and integers. Any hints / suggestions?

**Comment by TurboGit** [comment]
This is not really introspection.

All configs are in `darktableconfig.xml.in`. From this file we generate the preference code for the GUI and a set of routine for each config given the `type`, `min`, `max`, `default`, `description`. In the preference code we check the current selected value against the default value for the corresponding pref key which is just a plain string. So using a function call in there won't work and it is not design to work this way.

Now what could be done?

There is no static default so we could remove the default tag in `darktableconfig.xml.in` and when there is no default we could check for a value whose key is named `<key>-dynamic-default.` In your case `worker_threads-dynamic-default` and use that to check whether the current value is the default or not. I'm opened to any other better proposal.
