### ISSUE TITLE
Incorrect transfer function used for Rec709 files

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#8822]
Both https://github.com/darktable-org/darktable/blob/bc55e88285d0e76ef394be1c82f5dd9563cf2c0e/src/common/imageio_avif.c#L263 and https://github.com/darktable-org/darktable/blob/e8cb2cb1d9a2b34a4bbe27278247dae0ff09c3c8/src/imageio/format/avif.c#L301 use AVIF_TRANSFER_CHARACTERISTICS_BT470M (I presume because of the [2.2 gamma label confusion](https://github.com/darktable-org/darktable/blob/bc55e88285d0e76ef394be1c82f5dd9563cf2c0e/src/common/colorspaces.c#L1698)), while [dt constructs the Rec709 color space](https://github.com/darktable-org/darktable/blob/bc55e88285d0e76ef394be1c82f5dd9563cf2c0e/src/common/colorspaces.c#L445) using the linear and exponential parts like specified by AVIF_TRANSFER_CHARACTERISTICS_BT709; however there is also a discrepancy there that the exponential should be 1/0.45 and not exactly 2.2. In any case neither presently implemented inaccurate nor the fully correct 709 transfer functions are equivalent to constant 2.2 gamma tagging in AVIF files:

![image](https://user-images.githubusercontent.com/4973094/116675659-57f0db80-a9a6-11eb-8f0c-434d0f519919.png)

@cryptomilk I guess dt should probably only write files w/ AVIF_TRANSFER_CHARACTERISTICS_BT709 (and fix the small discrepancy in Rec709 color space construction), but support both tags on read for legacy/incorrect files?

See also [ITU H.273](https://www.itu.int/rec/T-REC-H.273/en).

**Comment by cryptomilk** [comment]
Can you write a patch?
