### ISSUE TITLE
JPEG and RAWs not auto grouping

### ISSUE THREAD

**Issue by b177y** [darktable-org/darktable#8824]
**Describe the bug/issue**

According to the docs here https://www.darktable.org/usermanual/en/lighttable/digital-asset-management/grouping/

"if you import multiple images with the same base name, but different extensions (eg. IMG_1234.CR2 and IMG_1234.JPG), these images will automatically form a group."

I have imported images with different extensions but the same base name, but they are not being grouped automatically.
I am able to manually group images.

UPDATE: the grouping works when the raw and jpegs are in the same directory.

**To Reproduce**

1. Imported images, including 20210430_GENERAL_F.jpg and 20210430_GENERAL_F.raf
2. View images by date in lighttable, showing images taken 30/04/2021
3. Enable grouping mode (collapse grouped images)
4. Both the jpg and raf are both present as separate images

**Expected behavior**

jpg and raf files should be grouped automatically

**Darktable Version**

```
> darktable --version
this is darktable 3.4.1
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

Using `darktable-2:3.4.1-2` from arch `community` repo

**Platform**

* darktable version : 3.4.1
* OS                : 5.11.15-hardened1-1-hardened
* Linux - Distro    : arch
* Memory            : 16GB
* Graphics card     : Unknown
* Graphics driver   : Unknown
* OpenCL installed  : Unknown
* OpenCL activated  : Unknown
* Xorg              :  1.20.11
* Desktop           : Qtile
* GTK+              : Unknown
* gcc               :  10.2.0
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Comment by elstoc** [comment]
> UPDATE: the grouping works when the raw and jpegs are in the same directory.

I think this is the only scenario we support.

**Comment by b177y** [comment]
I guess it would be possible to group by similar base name when the metadata is the same (same camera settings and timestamp) but might not be worth the effort.

Updating the docs should help others avoiding my mistake! Thanks!

**Comment by elstoc** [comment]
Not everything has metadata. Safest to just keep the simple case that if they're together on the file system we can assume they're related.

Should be resolved now (see https://github.com/darktable-org/dtdocs/commit/0a3c88be7b35f0837764a925cc1110b0281441a6)

**Comment by Nilvus** [comment]
As it's not wanted to implement that and now doc is updated, I think we can close this issue (feel free to reopen or answer if needed). Thanks.
