### ISSUE TITLE
Missing translation in new import dialog window

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#8825]
In actual master (compile just few minutes ago to check), there's still some text not translated and not included in last update pot/po files. So probably missing in code and I don't find (with my limited skills) where to fix that.

See text not translated (copy and import text in bottom right button and on window title) on french window below:

![2021-04-30_13-44](https://user-images.githubusercontent.com/45535283/116690954-ae134e00-a9a9-11eb-9e63-26402d5aedfb.png)

@TurboGit?

**Comment by TurboGit** [comment]
Good catch ! Now fixed, thanks.
