### ISSUE TITLE
GPS exported incomplete

### ISSUE THREAD

**Issue by waschulte** [darktable-org/darktable#8827]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported 
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Describe the bug/issue**
After some modifications on a JPG file with complete GPS data (ic. GPSDate, GPSTime, GPSLatitude, GPSLatitudeRef, GPSLongitude, GPSLongitudeRef, GPSAltitude, GPSAltitudeRef) I exported the picture to a new JPG file, but there GPSLatitude, GPSLatitudeRef, GPSLongitude, GPSLongitudeRef are missing. Also after adding GPSLatitude and  GPSLongitude to the metadatea to be exported (btw. I was missing the tags for GPSLatitudeRef and GPSLongitudeRef !).

**To Reproduce**
1. Load a JPG with complete GPS data in the Exif and do some minor changes.
2. Export the picture with CTRL-E and check the metadata in the exported picture.

**Expected behavior**
Expected is that all Exif:GPS data is exported, but Latitude and Longitude (and their Refs) are missing.
**Platform**
* darktable version : 3.4.1
* OS                : Linux, kernel 5.4.0-70-generic
* Linux - Distro    : LinuxMint 20.1
* Memory            : 16 GB
* Graphics card     : NVIDIA GP107M
* Graphics driver   : nvidia v: 450.102.04
* Xorg              : X.Org X Server 1.20.9
* Desktop           : Gnome
* GTK+              : 3

**Comment by phweyland** [comment]
Have you checked in `export/preferences` that `geo tags` is ticked ?  `exif data` ?

> Also after adding GPSLatitude and GPSLongitude to the metadatea
> btw. I was missing the tags for GPSLatitudeRef and GPSLongitudeRef !

where ?

**Comment by waschulte** [comment]
Hello Philippe,
Yes, I checked the export preferences for exif data:
if you click the "+" (arrow in screenshot) you get a list:

O..o. Now I do see them :"-). Sorry, I must have been blind. Wait, I
check them and see what happens ..Nope, still no latitude or longitude.
Only AltitudeRef.
With kind regards, Willy Schulte.

**Comment by phweyland** [comment]
I don't see...
Could you please share, the imported image, the exported one and a screenshot of your export preferences ?

**Comment by waschulte** [comment]
(! this has escaped my attention, sorry. I had problems uploading the pitures, so now in a Dropbox folder)

Hello Philippe,

No problem. In this [dropbox](https://www.dropbox.com/sh/5qrzjv5vc4n02sn/AAASvbaRGqEhHi19aeClLIX0a?dl=0)-folder the imported picture (P1150414.JPG), the exported one (P1150414_01.jpg)

and here my preferences:
![image](https://user-images.githubusercontent.com/59023045/120419223-4febd900-c362-11eb-90c2-581a032d26ea.png)


And just for reference:
exiftool -s -gps:* P1150414.JPG
GPSVersionID                    : 2.3.0.0
GPSLatitude                     : 52 deg 10' 35.57"
GPSLongitude                    : 4 deg 49' 42.90"
GPSAltitudeRef                  : Above Sea Level
GPSTimeStamp                    : 06:01:14
GPSDateStamp                    : 2021:04:28
and
exiftool -s -gps:* darktable_exported/P1150414_01.jpg 
GPSVersionID                    : 2.2.0.0
GPSAltitudeRef                  : Above Sea Level
GPSTimeStamp                    : 06:01:14
GPSDateStamp                    : 2021:04:28


With kind regards, Willy Schulte.

**Comment by phweyland** [comment]
Hi Willy,  you have set empty formula for these data,  which by convention prevents to export them. So, removing these lines you should get them back.

**Comment by johnny-bit** [comment]
Yup, seems like it.

Please see https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/export/#per-metadata-settings that mentions it explicitly:

>The right-hand-side of this dialog allows you to define formulas to populate image metadata. The formulas defined here have priority over the settings in the left-hand-side of the dialog. The first column identifies the entry to be edited. The second column allows you to define how to calculate the value for that metadata entry using a formula.
>See the variables section for details of the variables you can use in your metadata formula. Press Enter to validate the formula. Leave the formula empty to prevent a given metadata entry from being exported (Exif.GPSInfo.GPSVersionID in the above example).

Try removing those lines or using proper replacement for them, it should work :)

**Comment by waschulte** [comment]
Sorry, you are right. There were empty formula for some fields, so I removed then:
![image](https://user-images.githubusercontent.com/59023045/120453416-50e92e80-c393-11eb-912e-f0208211cd20.png)

And then exported again, but no change:
    $exiftool -s -gps:* P1150414_02.jpg 
    GPSVersionID                    : 2.2.0.0
    GPSAltitudeRef                  : Above Sea Level
    GPSTimeStamp                    : 06:01:14
    GPSDateStamp                    : 2021:04:28

so I guess I am doing something else wrong. I tried the same with a completely different picture, but same result. Funny thing is that the altitude reference is exported as the only field ...

**Comment by johnny-bit** [comment]
Huuuuhhhh...

ok, I can confirm that both latitude and longitude aren't being exported.

even if writting `$(LATITUDE)` in export formula it's not it...

@phweyland - can you check and see if it works for you?

**Comment by phweyland** [comment]
I take an image, drop it on the map to give a position and export:

`$ exiv2 -PE 20210512_Ipoema_020.jpg`

```
Exif.GPSInfo.GPSVersionID                    Byte        4  2.2.0.0
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  South
Exif.GPSInfo.GPSLatitude                     Rational    3  19deg 32' 0"
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  West
Exif.GPSInfo.GPSLongitude                    Rational    3  43deg 26' 0"
Exif.Image.DateTimeOriginal                  Ascii      20  2021:05:12 10:28:33
Exif.GPSInfo.GPSVersionID                    Byte        4  2.2.0.0
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  South
Exif.GPSInfo.GPSLatitude                     Rational    3  19deg 32' 0"
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  West
Exif.GPSInfo.GPSLongitude                    Rational    3  43deg 26' 0"
Exif.Image.DateTimeOriginal                  Ascii      20  2021:05:12 10:28:33
```

![image](https://user-images.githubusercontent.com/23012047/120520660-1044e180-c3a2-11eb-9255-7718b8968010.png)


Seems to work for me.
Suggestions:
- share the geottaged image
- make a try with exiv2 instead of exiftool

**Comment by phweyland** [comment]
```
$ exiv2 -PEX 20210512_Ipoema_020.jpg | grep GPS
Exif.Image.GPSTag                            Long        1  11238
Exif.GPSInfo.GPSVersionID                    Byte        4  2.2.0.0
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  South
Exif.GPSInfo.GPSLatitude                     Rational    3  19deg 32' 0"
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  West
Exif.GPSInfo.GPSLongitude                    Rational    3  43deg 26' 0"
Xmp.exif.GPSVersionID                        XmpText     7  2.2.0.0
Xmp.exif.GPSLongitude                        XmpText    13  43,25.608673W
Xmp.exif.GPSLatitude                         XmpText    13  19,31.566010S
```

**Comment by johnny-bit** [comment]
@phweyland - try the file provided by @waschulte in the dropbox link. the direct link to file is https://www.dropbox.com/sh/5qrzjv5vc4n02sn/AAASvbaRGqEhHi19aeClLIX0a?dl=0&preview=P1150414.jpg

**Comment by phweyland** [comment]
The Willy's image:
```
$ exiv2 -PEX P1150414.jpg | grep GPS
Exif.Image.GPSTag                            Long        1  29552
Exif.GPSInfo.GPSVersionID                    Byte        4  2.2.0.0
Exif.GPSInfo.GPSLatitude                     Rational    3  52deg 10' 36"
Exif.GPSInfo.GPSLongitude                    Rational    3  4deg 49' 43"
Exif.GPSInfo.GPSAltitudeRef                  Byte        1  Above sea level
Exif.GPSInfo.GPSAltitude                     Rational    1  40.1 m
Exif.GPSInfo.GPSTimeStamp                    Rational    3  06:01:14
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2021:04:28
Xmp.exif.GPSAltitudeRef                      XmpText     1  Above sea level
Xmp.exif.GPSAltitude                         XmpText     6  401/10
```

When imported:
![image](https://user-images.githubusercontent.com/23012047/120524898-8f87e480-c3a5-11eb-9005-15e227ce845a.png)

This image has an xmp altitude but no xmp latitude nor longitude.
It's possible that, finding the xmp altitude, dt considers the xmp geotags and overwrite the exif ones.
For me, that's the source jpg which is guilty, but dt could be more tolerant.
I'll have a look on import code to check what I've said above.

**Comment by waschulte** [comment]
Weird, I never cared much about XMP and I have no idea where it comes from. But I tried another picture (P1150741.JPG), which doesn't have XMP data and does have EXIF:GPS data. I exported it (P1150741_01.jpg). See the listings below.
Now the exported picture does have XMP data (DT), even Altitude(Ref) in the XMP, but no latitude nor longitude. The EXIF data in the exported picture has lost latitude and longitude !

So the result is still no latitude, no longitude. I am still at a loss here ..

PS. Both files are in the same Dropbox folder.


$ exiv2 -PEX **P1150741.JPG** | grep GPS
Exif.Image.GPSTag                            Long        1  30208
Exif.GPSInfo.GPSVersionID                    Byte        4  2.3.0.0
Exif.GPSInfo.GPSLatitude                     Rational    3  52deg 10' 55.384" 
Exif.GPSInfo.GPSLongitude                    Rational    3  4deg 49' 48.158" 
Exif.GPSInfo.GPSAltitudeRef                  Byte        1  Above sea level
Exif.GPSInfo.GPSAltitude                     Rational    1  42.5 m
Exif.GPSInfo.GPSTimeStamp                    Rational    3  04:27:15
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2021:06:02

$ exiv2 -PEX **P1150741_01.jpg** | grep GPS
Exif.Image.GPSTag                            Long        1  30258
Exif.GPSInfo.GPSVersionID                    Byte        4  2.2.0.0
Exif.GPSInfo.GPSAltitudeRef                  Byte        1  Above sea level
Exif.GPSInfo.GPSAltitude                     Rational    1  42.5 m
Exif.GPSInfo.GPSTimeStamp                    Rational    3  04:27:15
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2021:06:02
Xmp.exif.GPSAltitudeRef                      XmpText     1  Above sea level
Xmp.exif.GPSAltitude                         XmpText     6  425/10

**Comment by waschulte** [comment]
Did some investigation on the appearance of XMP data in the first picture I tried (P1150414.jpg). That came from DT too. What happened was:
- geotagged with exiftool (my usual tool)
- some editing with DT
- seeing the GPS information was incomplete, geotagged it again with exiftool (and all XMP information was held)
- edited some more with DT and exported it: and again the GPS information was lost, but now I realized the clue.

What puzzles me is why the GPS information is (partially) duplicated in the XMP metadata.

**Comment by phweyland** [comment]
When I import P1150741.JPG |I don't get the latitude and longitude while altitude is properly set.
Seems to be an import issue on jpg...

**Comment by waschulte** [comment]
Ok, good luck. If there is anything I can do, just mail.

**Comment by phweyland** [comment]
> What puzzles me is why the GPS information is (partially) duplicated in the XMP metadata.

If you set the geotags with exiftool, it may be the source of the error. There could be also some discrepancy between exiftool and exiv2 (which is used by dt).

On the other hand, dt exports the geotags (if geotags checked) to exif (if exif checked) and xmp.

**Comment by johnny-bit** [comment]
Sooo...

@waschulte - how exactly do you "geotag with exiftool"?

**Comment by phweyland** [comment]
```
$ exiv2 -PEX P1150741.JPG | grep GPS
Exif.Image.GPSTag                            Long        1  30208
Exif.GPSInfo.GPSVersionID                    Byte        4  2.3.0.0
Exif.GPSInfo.GPSLatitude                     Rational    3  52deg 10' 55"
Exif.GPSInfo.GPSLongitude                    Rational    3  4deg 49' 48"
Exif.GPSInfo.GPSAltitudeRef                  Byte        1  Above sea level
Exif.GPSInfo.GPSAltitude                     Rational    1  42.5 m
Exif.GPSInfo.GPSTimeStamp                    Rational    3  04:27:15
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2021:06:02
```

my current findings. 
As you see above only altitude as the Ref element. Longitude and Latitude haven't this. So they are ignored by dt.
I don't know yet if it's a dt bug or not.

**Comment by waschulte** [comment]
Now this is funny .. let me do some checking. Geotagging is done in a little program, using exiftool to set the calculated position. Lets see how it is exactly done for the P1150741.JPG picture:
  exiftool -s -G0 -m -sep ,  -lang en -fast -ec -exif:gpslatitude=52.182051 -exif:gpslongitude=4.830044 -exif:gpsaltituderef=A - 
  exif:gpsaltitude=42.50 -exif:gpsdatestamp=2021:06:02 -exif:gpstimestamp=04:27:15 -filemodifydate<datetimeoriginal - 
  filecreatedate<datetimeoriginal /home/wschulte/tmp/P1150741.JPG
seeing this I instantly saw my mistake: latitude and longitude are set as decimal degrees, _assuming_ the references are clear. Wrong assumption !
Doing the same for a picture from south of the equator did:
  exiftool -s -G0 -m -sep ,  -lang en -fast -ec -exif:gpslatitude=-18.664675 -exif:gpslongitude=24.072655 -exif:gpsaltituderef=A - 
  exif:gpsaltitude=916.00 -exif:gpsdatestamp=2019:10:06 -exif:gpstimestamp=08:34:42 -filemodifydate<datetimeoriginal - 
  filecreatedate<datetimeoriginal /home/wschulte/tmp/P1120330.JPG
Yes it is south (negative latitude), but it would have been nice to set the reference too ! Funny thing is: exiftool makes the reference for the latter case (south latitude) for latitude as well as longitude.

I am soo sorry, this is the culprit. Reference should have been set.
Thanks for the help.

**Comment by johnny-bit** [comment]
If you confirm that this fixes the issue for you and that image is properly geotagged after fixing the issue, would you consider closing the issue? :)

**Comment by waschulte** [comment]
Off course. Fixing the erroneous geotagging issue has nothing to do with DT. So I'll close this issue.

**Comment by phweyland** [comment]
> Thanks for the help.

You are welcome!
