### ISSUE TITLE
HI my x1d2  can't open the raw 

### ISSUE THREAD

**Issue by mars99** [darktable-org/darktable#8832]
isthere one ?
litghtroom can view the img ,but darkroom show "file has unknown format",

**Comment by Nilvus** [comment]
This camera is not supported. Nobody share necessary information/files to add support to this one. Lightroom is a commercial software, so they can add support more easily. darktable is made by people in their free time. You can help by providing RAW files in https://raw.pixls.us/ and check which camera are supported here: https://www.darktable.org/resources/camera-support/

I suggest you too to read first link in darktable.org camera support page: https://www.darktable.org/2012/10/whats-involved-with-adding-support-for-new-cameras/

I close this as the support could only be added by providing RAW and be sure some other infos (listed in last link posted here) shared. If you propose all RAW asked in raw.pixl.us link, you can then post a new issue with link to them and ping LebedevRI (with @ before his name).
