### ISSUE TITLE
Raster mask from rgb curve not usable e.g. in exposure module

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#8839]
**To Reproduce**
I'm working regularly with rgb curve modules and create masks which I want to use in other modules, e.g. the exposure module.
However it never shows up in the raster mask drop-down menu.

1. Open random image in a recent dt build from master
2. Create a rgb curve module and apply any mask type 
3. Create an "exposure" or "color balance rgb" module and select raster mask
4. You won't find the raster mask of the rgb curve module in the drop-down menu

I also figured out that other modules such as the denoise modules don't allow raster masks from exosure or rgb curve modules.
Is this a bug or some sort of limitation?

**Expected behavior**
Raster masks of all modules are usable in all other modules. 

**Platform**
* darktable version : 3.5.0+1966~g12d7a9967
* OS                : Linux - Ubuntu 20.04

**Comment by MStraeten** [comment]
Works as designed: a raster mask can be used in subsequent modules in the pixel pipe. Rgb curves comes after exposure, so exposure doesn’t know about masks defined later.
Have a look at https://darktable-org.github.io/dtdocs/darkroom/pixelpipe/the-pixelpipe-and-module-order/

**Comment by da-phil** [comment]
Ah, thanks for pointing out the pixelpipe order. This probably means that raster masks are calculated in the same order as the module outputs?
I looked specifically at the [documentation of raster masks](
https://darktable-org.github.io/dtdocs/darkroom/masking-and-blending/masks/raster) and it does not mention 

> Raster masks can be identified by the name of the module against which they were originally generated. Raster masks can only be selected from modules that are currently active in the pixelpipe. If a module is subsequently deactivated its raster mask can no longer be used.

As far as I understand it could be technically possible to first calculate the raster masks of all (active) modules and then use them at any point in the pipeline, as the masks only depend on their own parametrization and not on the output of any module, right?

**Comment by da-phil** [comment]
Sorry for the noise, I didn't think properly when I wrote the bug ticket.

**Comment by elstoc** [comment]
I think the user manual needed some clarity regarding these issues so I've pushed a change [here](https://github.com/darktable-org/dtdocs/commit/3f1e89d917d0e89fecb15f0186d138a809542cfb).

**Comment by da-phil** [comment]
@elstoc that definitely helps, reminding users constantly about the pixelpipe order implications ;)
thanks!
