### ISSUE TITLE
Segfault after changing opacity / hardness of brush stroke in drawn mask

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#8840]
**Describe the bug/issue**

I was working on a RAW image and playing around with a brush stroke of a drawn mask, changing the opacity and hardness of a particular brush stroke when I encountered a segfault.

**To Reproduce**
Unfortunately I couldn't reproduce the segfault so far :(
But here is the backtrace (unfortunately not a debug build): [darktable_bt_4R1I20.txt](https://github.com/darktable-org/darktable/files/6410276/darktable_bt_4R1I20.txt)

**Platform**

* darktable version : 3.5.0+1966~g12d7a9967
* OS                : Linux - Ubuntu 20.04
* Memory            :  16 GB
* Graphics card     : Intel Corporation UHD Graphics 620 (Whiskey Lake)
* Graphics driver   : Upstream kernel driver
* OpenCL installed  : yes
* OpenCL activated  : yes
* CMAKE_BUILD_TYPE  : default from `build.sh` build script

**Comment by johnny-bit** [comment]
OK, I managed to find what I though could be cause of the problem

https://github.com/darktable-org/darktable/blob/f994e13134c433eeef995deb6e5fe38c6235acc2/src/develop/masks/brush.c#L1402

This doesn't check if returned point is NULL, therefore it might crash in extreme situation (eg when `seg_selected` is greater than points list length)

@TurboGit or @ralfbrown would you be able to take a look? It's hard to reproduce but IMO the check for null should be incorporated there somehow.

**Comment by TurboGit** [comment]
I'll have a look.

**Comment by TurboGit** [comment]
@johnny-bit : See #9197.

**Comment by johnny-bit** [comment]
Yep, I think the #9197 is correct since you check if seg_select is less than nb, so it's fine

**Comment by da-phil** [comment]
Thanks for fixing guys ;)
