### ISSUE TITLE
Crash when applying crop to dng

### ISSUE THREAD

**Issue by wilecoyote2015** [darktable-org/darktable#8843]
**Describe the bug/issue**
When editing the provided DNG file, Darktable crashes while applying the crop module in darkroom. This occurs regardless of opencl activation.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open the image
2. In Darkroom, Expand the crop module
3. Specify some crom
4. Collapse the crop module

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.5.0+1966~g12d7a9967-dirty
* OS                :  Linux 5.11.16
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            :  24GB
* Graphics card     : Intel Xe
* Graphics driver   : unknown
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              :  no (sway / wayland)
* Desktop           : sway
* GTK+              : unknown
* gcc               : 10.2.0
* cflags            : unknown
* CMAKE_BUILD_TYPE  : release

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

Image: 
https://drive.google.com/file/d/1-GMp2OwchYajgKABXCEk0kdchJvxJn0c/view?usp=sharing

[IMG_20210501_133652.dng.txt](https://github.com/darktable-org/darktable/files/6411156/IMG_20210501_133652.dng.txt)

**Comment by jenshannoschwalm** [comment]
I can't confirm here on fedora 33 with nvidia.

Please start dt via a console with
1. darktable --disable-opencl -- this will disable CL from start and won't run into CL related issues
2. darktable -d all -- and report what you find in the log after crashing ...

**Comment by wilecoyote2015** [comment]
1. With `--disable-opencl`, DT crashes on opening the image already
2. This is the debug log:
    [crash.log](https://github.com/darktable-org/darktable/files/6420536/crash.log)

**Comment by jenshannoschwalm** [comment]
Well, that's a lengthy log but absolutely no sign of crash...

**Comment by wilecoyote2015** [comment]
hmm, for some reason, neither when redirecting stdout nor stderr from console to file, it  catches the last line `Segmentation fault (core dumped)`.
How to generate a proper debug log with darktable? To be honest, I couldn't find any information in the manual or in the project wiki...

I've just launched my current git build with `darktable -d all --library :memory: --configdir "/tmp"` and added the image file to the library (no xmp exists). After double clicking the image in the lighttable, darktable switches to the darkroom interface, freezes and then crashes. 
With raw images from other cameras, everything works fine.

**Comment by AlicVB** [comment]
@wilecoyote2015 : I can't reproduce either with the file you post :(
just to be sure : 
- is rawspeed up to date ? (git submodule update)
- do you reproduce with current master ? (always with a "fresh" install, without associated xmp)

If both are yes, then, are you able to run a debug session via gdb, in order to get a backtrace of the crash ?
Thanks !

**Comment by wilecoyote2015** [comment]
Rawspeed was up to date back then and I was able to reproduce it with master.

With current master, the issue is gone. I cannot determine whether it had been an issue specific to the buildscript in the arch user repository, any outdated library in the arch repository or darktable itself.

But as no crash occurs with current master, I propose that the Issue may be closed.
