### ISSUE TITLE
Applying operations on a selection of multiple pictures applies the operation in wrong order (e.g. drag and drop)

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#8844]
**Describe the bug/issue**
The user is able drag-and-drop pictures to a new position in the collection while in custom sort mode. When this is done with multiple pictures at the same time, the order of the selected pictures is inverted upon drop.

**To Reproduce**

1. Open filemanager, zoomable lighttable or culling layout (using the film strip)
2. Change sort order to "custom sort"
3. Select a few pictures that are easy to differentiate
4. Drag and drop them to a new location and observe how the order is inverted. For example selecting pictures 4 to 6 and dropping them at position 3:
1 2 3 **4 5 6**
1 2 **6 5 4** 3  <- wrong order
5. Dragging and dropping the pictures again inverts the order once more (returning to normal).
1 **4 5 6** 2 3  <- inverted a second time

**Expected behavior**
Order should remain unchanged
1 2 3 **4 5 6**
1 2 **4 5 6** 3  <- correct behaviour
1 **4 5 6** 2 3

**Which commit introduced the error**
I assume this problem was intruduced by #8719 

The selection code queries all selected pictures from the database (e.g. pictures 4, 5, 6) and joins them into a list by prepending each item. 
<pre>
{
    l = g_list_<b>prepend</b>(l, GINT_TO_POINTER(sqlite3_column_int(stmt, 0)));
}

// removed by #8719
// if(only_visible && ordering) l = g_list_reverse(l);
</pre>

Prepending instead of appending leads to an inverted list of selected files: **6, 5, 4** which will be used in that order by the for-loop in [collection.c](https://github.com/darktable-org/darktable/blob/master/src/common/collection.c#L2368-L2379) thus inverting the order of images during drag and drop. Since this list of selected pictures is used by every module throughout darktable, this code probably inverts fileoperations **everywhere**.

Originally, the order was being corrected through a call of g_list_inverse before commit #8719, which attempted to fix the inverted order of file exports. Since the order of the selection list was correct all along, I assume that the real culprit for #8719 lies elsewhere.

**Suggested fix**
Change g_list_<b>prepend</b> to g_list_<b>append</b> to correct the order of the selected pictures list and save 1 instruction over having to use g_list_inverse. Then check the file export module why files are exported in the wrong order. The order of the picture selection list was correct all along.

**Comment by ralfbrown** [comment]
g_list_append yields O(n^2) operation instead of O(n), which is very noticeable on large collections....  Better to have the order inverted in the SQL call and revert 8719.

**Comment by Solarer** [comment]
@ralfbrown is this still going to go into 3.6?
It is only about reverting #8719

**Comment by TurboGit** [comment]
@Solarer : Fix is merged in master now, can you double check all is ok on your side ? TIA.

**Comment by Solarer** [comment]
Yes, it has been fixed for drag and drop.

Are you sure that your conditionally flip of the list does not create issues elsewhere?
```if(only_visible && ordering) l = g_list_reverse(l);```

I think it is necessary to look into the export code to figure out why #8719 was occurring in the first place rather than leaving the selected list in the wrong order. I would reopen #8719 to investigate this further.

**Comment by ralfbrown** [comment]
8719 is fixed as well.  The `if` now has an inverted test compared to prior to its original removal.

**Comment by Solarer** [comment]
cool, thanks !
