### ISSUE TITLE
Why does the image change when I enter the darkroom from lighttable?

### ISSUE THREAD

**Issue by PuWenyin** [darktable-org/darktable#8846]
**Question**
1. Import a **ARW(RAW)** and a **JPG** from **Sony ILCE-6300 with Sigma 30mm F1.4 DC DN**, with default setting and sRGB.

2. In lighttable it looks normal, even when I press key W.
![image](https://user-images.githubusercontent.com/44593467/116818655-1a0ad780-ab9f-11eb-90c5-a66adb4110f1.png)
![image](https://user-images.githubusercontent.com/44593467/116818940-6dc9f080-aba0-11eb-90ed-6a15ecdcb3a5.png)
![image](https://user-images.githubusercontent.com/44593467/116818947-74f0fe80-aba0-11eb-9adf-854ccb6dff01.png)

3. But when I enter the darkroom, the ARW(RAW) and JPG look different, they become darker! Even when I set the history to original. Is it a matter of color space? But I changed the input color space all over again and still can't see the original color.
![image](https://user-images.githubusercontent.com/44593467/116818899-3ce9bb80-aba0-11eb-8fa1-3b8caeee7d31.png) 
![image](https://user-images.githubusercontent.com/44593467/116818598-cf895b00-ab9e-11eb-929a-358092628dc8.png)

4. How can I get the image looks like the lighttable? Thanks for anyone who can help me.

**Platform**
* darktable version: darktable 3.4.1 released (latest)
* OS: Win10

**Comment by ptilopteri** [comment]
*please*, read the fine documentation.  the out of camera jpg has been altered by sony with their proprietary software and is not expected to have the same look as the bare raw image.

then, please close this issue.

**Comment by ptilopteri** [comment]
ps: if you prefer the out-of-camera jpg, why are you shooting raw?

**Comment by PuWenyin** [comment]
No, you probably didn't understand what I meant or maybe I didn't describe the problem clearly. I know RAW is different from JPG, what I mean is that for a photo (say RAW) it has different colors in lighttable and darkroom (You can see the difference in the **second** and **fourth** pictures). I now find that it may be the automatic configuration of the color space for the display, after I **changed the display profile** it is now normal, but thanks for the answer.
![image](https://user-images.githubusercontent.com/44593467/116820310-f186db80-aba6-11eb-95c1-99cf86ca873f.png)
You can use this graph to compare with the **fourth** graph in the problem and you can understand what I mean.

**Comment by TurboGit** [comment]
I do think @ptilopteri understood the question and the answer is correct.

**Comment by Nilvus** [comment]
@PureWenyin: could you explain why you reopen without comment as it seems just a normal behavior as explain in your issue?

**Comment by todd-prior** [comment]
@PureWenyin --from the manual...
use raw file instead of embedded JPEG from size
When generating thumbnails for images that have not yet been processed in the darkroom, if the thumbnail size is greater than this value, generate it by processing the raw image data. If the thumbnail is below this size, use the JPEG preview image embedded in the raw file. Once an image has been processed in the darkroom, thumbnails will always be generated from raw data (you can revert back to the JPEG preview by discarding history). To render thumbnails with the best quality choose “always”.
