### ISSUE TITLE
deprecate defringe

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#8851]
With the new module for chromatic aberration that works for all kind of images and is better than defringe we probably want to deprecate defringe.

**Comment by GustavHaapalahti** [comment]
Do you mean the Chromatic Aberrations module in 3.4 that says automatic chromatic aberrations correction?

**Comment by TurboGit** [comment]
> automatic chromatic aberrations correction

I don't see one having this description or string. It is the one named **defringe**.

**Comment by ralfbrown** [comment]
I believe Gustav is referring to the (very) old cacorrect module.  I don't see a new module for CA in current master, but notice that there were significant changes to the old one in March; is that the module you are referring to as the new CA, Pascal?

**Comment by GustavHaapalahti** [comment]
> > automatic chromatic aberrations correction
> 
> I don't see one having this description or string. It is the one named **defringe**.

The reason I asked is because for me the module called "Defringe" works better than the one called "chromatic aberrations" in release 3.4.1.1. The one called chromatic aberrations have no settings and only the string "automatic chromatic aberrations correction" is shown.

**Comment by TurboGit** [comment]
@ralfbrown : no I'm referring to the new one which is about to be merged :see #7633

**Comment by TurboGit** [comment]
@GustavHaapalahti : Ok, and the new one in #7633 works even better  than defringe :)

**Comment by GustavHaapalahti** [comment]
> @GustavHaapalahti : Ok, and the new one in #7633 works even better than defringe :)

Great :-)
