### ISSUE TITLE
Vector Scope, not realy usable since last change

### ISSUE THREAD

**Issue by kikoucalou** [darktable-org/darktable#8858]
Vector Scope from last build (3.5.0+2053~g47ec421cd) became not realy usable or does not work properly.

As it was showing nice scope indications  before, Scope screen become almost black except very few points, no scope indications.

Many code changes have just intervened, notably on histogram : " histogram: do vectorscope at 1/4 resolution for speed"
Perhaps this new resolution is to low for my system ?

My system : Linux Mint 20.1 Cinnamon, kernel 5.8.0-50-generic, Intel© Xeon© CPU E5-2690 0 @ 2.90GHz × 8, NVIDIA Corporation GK107GL [Quadro K2000]

**Comment by kikoucalou** [comment]
Before and After changes

![Capture d’écran du 2021-05-04 19-50-34](https://user-images.githubusercontent.com/7946021/117057696-0fc31780-ad1e-11eb-8ed5-d40ba6a6fb98.png)

![Capture d’écran du 2021-05-04 21-13-55](https://user-images.githubusercontent.com/7946021/117057747-1fdaf700-ad1e-11eb-8658-151e054d695d.png)

**Comment by johnny-bit** [comment]
Pinging @dtorop fo vectorscope problem visibility :)

**Comment by dtorop** [comment]
I'll look into it! I know the scaling code is broken, but this looks different.

I'm working on a revision now which does log scaling, which should be a big improvement, but may not fix this. More in a bit.

**Comment by dtorop** [comment]
@kikoucalou If you had a chance to build the branch https://github.com/dtorop/darktable/tree/vectorscope-log-scale, I'd be curious if it's still broken there. It's WIP to make log scale histogram, but I also removed a bunch of the broken auto-scaling code.

I'm curious if the problem is the broken auto-scaling, or if the 1/4 resolution code or something else broke things. If the latter, it could be helpful to have an image file & sidecar which produces the broken behavior, or to know if it is broken for all images on your setup or particular ones.

**Comment by kikoucalou** [comment]
@dtorop Yes, it's broken for all images on my setup.
Unfortunatly, I will be out for a week, I'm not sure i will find the time to build your branch now, i should do it when i get back.
I would do my best to help you with your research

**Comment by kikoucalou** [comment]
@dtorop Finaly build juste before going with  the branch https://github.com/dtorop/darktable/tree/vectorscope-log-scale, 
Better scaling, but  no scope ...

![Capture d’écran du 2021-05-07 08-03-29](https://user-images.githubusercontent.com/7946021/117405045-49a54100-af0b-11eb-8060-1283fe4eb170.png)

**Comment by MStraeten** [comment]
thats quite strange; is the preview image properly displayed in the upper left corner?
is the histogram or waveform ok or also not displayed?

**Comment by kikoucalou** [comment]
@dtorop  Yes histogram parade waveform are displayed nicely

**Comment by dtorop** [comment]
@kikoucalou One more query -- for when you're back. Would you check the "histogram profile" setting (right-click gamut check or softproof button on bottom panel, as below) and let me know its setting?

![image](https://user-images.githubusercontent.com/2311860/117521682-05528900-af7d-11eb-9c8e-7d12152fd09a.png)

**Comment by dtorop** [comment]
@kikoucalou And, actually, similarly, the setting of "working profile" in the "input color profile" iop:

![image](https://user-images.githubusercontent.com/2311860/117521869-164fca00-af7e-11eb-81d3-97c0166f063e.png)

**Comment by jade-nl** [comment]
I'm having the same issue (although I do not know if it worked before): The centre of the vector scope is and always has been empty.

To start with your (@dtorop) questions in your last 2 posts:

This happens with all the images I tested with. I tested with: raf, nef, arw, rw2 and cr2 RAWs.

![Screenshot_2021-05-08_18-03-45](https://user-images.githubusercontent.com/56407344/117545952-89594f00-b017-11eb-9f1c-33c2fef80b4b.png)

I also tried just about every other combination.

I did merge #8855 and #8885 today, hoping it would solve the problem. It did not.

**Version**
this is darktable 3.5.0+2112~g63182ac93
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled


**Platform**

* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.9)
* Graphics driver   : nvidia (460.39)

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Lensfun       : 0.3.2-4

```
cmake \
    -DBUNDLE_BASE_INSTALL_DIR="$HOME/.local/${TRGT}" \
    -DBUILD_BUNDLE="ON" \
    -DCACHE_NAME_SUFFIX="5-dev" \
    -DCMAKE_BUILD_TYPE="relwithdebinfo"  \
    -DPROC_TARGET_NUMBER="2" \
    -DOPTION_OMP="ON" \
    -DBUILD_SHARED="OFF" \
    -DWITH_LTO="ON" \
    -DWITH_BENCHMARK="OFF" \
    -DWITH_MYFILE_MMAP="ON" \
    -DWITH_PROF="OFF" \
    -DWITH_SAN="OFF" \
    -DWITH_SYSTEM_KLT="OFF"
```

I do have a dual monitor setup, not sure if that might be relevant. I'm not using the second monitor for viewing when using darktable.

**Comment by MStraeten** [comment]
on win10 and osx its ok in general.
I can force a black vectorsope only if i use a softproof profile from a printer and then activate softproof or activate gamut check. But then even the frame is not shown

**Comment by dtorop** [comment]
@jade-nl: Thank you for the report. Do you have the ability to run a `git bisect` to find the bad commit? At the least, I'm interested in if 4e09091adb57107dac0a36acd25c962cfef200dd is a good commit (first before vectorscope-appearance branch) and e6c2a630a8e018a1a2b2739885a80e8e8c8afad1 is a bad commit (last of vectorscope-appearance branch, PR #8848).

> I can force a black vectorsope only if i use a softproof profile from a printer and then activate softproof or activate gamut check. But then even the frame is not shown.

@MStraeten: That is a great lead. I can replicate that here and will work on a fix.

**Comment by jade-nl** [comment]
Ran a bisect: I saw 4e09091 coming by and that was a *bisect good* step.

```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[b8e59cedebe211f253dbb522aa26602e889172f7] Merge pull request #8848 from dtorop/vectorscope-appearance
[stasis] jade ~/.local/git/darktable $ git bisect bad
b8e59cedebe211f253dbb522aa26602e889172f7 is the first bad commit
```

**Comment by dtorop** [comment]
@jade-nl Thank you for bisecting this makes sense that it is the profile-handling part of the code which is making things go awry.

Here's a theory: Your "system display profile", is a CLUT rather than a matrix profile. The "bad" commit 955ee4b3e7136454ffc555539aa8cbfd134f1a20 is switching from converting the whole image from display to histogram profile via `dt_ioppr_transform_image_colorspace_rgb()` to pixel-by-pixel converting from display profile to a "PCS" space as needed. This uses a lot less memory and less CPU, but only works with matrix profiles.

The real "right" thing to do would be to do the histogram processing before the image is converted from working profile to display profile, but that is too big a change to do here. I'll see if there's a way to nicely use LCMS in the case of CLUT profiles.

I don't think this will fix your problem, but I'm curious how #8885 works with its latest commit, 7bb87e43109c3f9715346fd8399296fd4289054e. This should set the profile to linear rec2020 in the event of a difficult (probably CLUT rather than matrix) histogram profile. This should at least fix the case @MStraeten found.

**Comment by jade-nl** [comment]
> Here's a theory: Your "system display profile", is a CLUT rather than a matrix profile. 

That is most likely correct. This is what is being reported on my main screen's profile:

```
$ file U2719DC.DELL.icc 
U2719DC.DELL.icc: color profile 2.2, type argl, RGB/XYZ-mntr device by DCAL, 965808 bytes, 4-2-2021 17:29:12, 0x422fd314a598ab7f MD5 "U2719DC-20210204.1714-.2.2-XYZLUT+MTX"
```

**Comment by MStraeten** [comment]
on osx it's fine now with my softproof profile from a printer and then activated softproof or gamut check (wasn't able to check this on windows yet)

**Comment by jade-nl** [comment]
@dtorop : Your latest chance solves the issue for me.

Thanks!

**Comment by kikoucalou** [comment]
@dtorop Sure, I'll make check and feed back when back!

**Comment by kikoucalou** [comment]
@dtorop It look woorking nicely from my end too.  Bravo !
