### ISSUE TITLE
Build 2054 not allowing mousewheel adjustment of menu items

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#8860]
Hi all.
Just downloaded the latest build of 3.5.
Amazing work, guys!
But it seems that trying to use the mousewheel to roll through a dropdown menu of items does not work. At least, not for me. 
Linux Mint 20
Cinnamon 4.6.7
Kernel 5.4.0-72 generic

**Comment by elstoc** [comment]
Works fine for me on the same build with ArchLinux. Could you give some examples of the comboboxes that don't work for you.

**Comment by brucewilliamsphotography** [comment]
Oh.... I just discovered that it WILL work if I use a SHIFT or CTRL modifier.
Is this a new change I wasn't aware of? Or a bug?

**Comment by elstoc** [comment]
This is correct behaviour if you have enabled `preferences > miscellaneous > interface > mouse wheel scrolls modules side panel by default`

**Comment by brucewilliamsphotography** [comment]
So is this a changed default preference? Because I did not (knowingly)
alter that preference.

Cheers,
Bruce Williams.

**Comment by elstoc** [comment]
Nope - it's off by default.

**Comment by brucewilliamsphotography** [comment]
Well, that's got me stumped! 😃
Don't know how that got changed.
Thanks for the heads up, though!

Cheers,
Bruce Williams.

**Comment by elstoc** [comment]
Ok. I'll assume this is working as designed and close the issue then.
