### ISSUE TITLE
Inconsistent behavior/wording in trashing error pop-up

### ISSUE THREAD

**Issue by lapineige** [darktable-org/darktable#8862]
**Describe the bug/issue**
Several actions in the "Trashing error" pop-up (that appears if you try to use the trash but darktable fails) are confusing, inconsistent or badly named, which does not make their behaviour clear enough.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. "Disable" your trash folder (`~/.local/share/Trash/`). In my case, I moved the trash folder in another location (on a separated partition), and replaced it by a symbolic link to that new location - but apparently darktable can't use it and act as if it was disabled.
2. Click on the "trash" button in the light-table. Answer Yes to the first pop-up.
3. Use some buttons in the "Trashing error" pop-up, or press Escape. See https://github.com/darktable-org/darktable/pull/8666#issuecomment-831969522 for more details about that pop-up (screenshot included).

**Expected behaviour**
I don't know what the design goal of each button. Thus I don't know what's the expected behaviour, but I will try to describe some case where I find the situation confusing.

I see several issues, either with the feature behind each action, or a wording issue that makes it unclear and unexpected (and sometimes scary):
* "Escape" key and *"stop process"* should not do the same as *"remove from collection"*. Right now each of them remove the image from darktable database… while we expect the first 2 to cancel any removal.
If there is no way to cancel that removal (from collection at least), then it should not allow us to "stop" the process. If we are excepted to be able to cancel it, it still not remove the file from darktable database it.

* The pop-up is also unclear about what *"physically delete all files"* buttons does… when you expect it to delete only one single (image) file (that is scary ! 😅). It's kind of the same *"next file"* as for a single (image) deletion we don't expect it to have "next file".

* XMPs are also removed, but with another action. I don't know if it's expected that we can remove the source image but not it's XMP (hence not removing it from the light-table… while we deleted the physical file just a second before).

More details here https://github.com/darktable-org/darktable/pull/8666#issuecomment-831969522

PS: maybe "remove from collection" could be renamed (to "remove from darktable" I guess), to be consistent with https://github.com/darktable-org/darktable/pull/8666#issuecomment-822031606 and the PR changes.

**Screenshots**
See https://github.com/darktable-org/darktable/pull/8666#issuecomment-831969522

**Platform**
* darktable version : 3.4.1
* OS                : Linux - Kernel 5.8.0
* Linux - Distro    : Kubuntu 20.10

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **not tested**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**

**Comment by Nilvus** [comment]
Humm, maybe it's me but your issue is not clear and hard to understand.

First thing, why disable trash in your system? Really strange...

2nd, you talk about darktable 3.4.0 and we are on 3.4.1 and the comment you point is from a clarification about what you talk about (on what I understand here) that had been integrated in actual master, so only for darktable 3.6 which will be release on early july.

So please be clear and how we can understand what you want by pointing a fix not integrated in the darktable version you use...

**Comment by lapineige** [comment]
Sorry about that, maybe I was a bit too hasty, hence it's not clear enough.

> First thing, why disable trash in your system? Really strange...

I did not. I put my trash folder on a separated drive, and used a symlink (from ~/.local/share/Trash to that new location on the other drive). It seems that darktable can't follow that symbolic link.
(I edited my first message)

> 2nd, you talk about darktable 3.4.0 and we are on 3.4.1

That was a typo. Fixed.

> and the comment you point is from a clarification about what you talk about (on what I understand here) that had been integrated in actual master

In fact I'm not talking about that specific PR content, but another part of the software (that is related, but not affected by the PR).
I did link to that issue to 1) avoid reposting the whole explanation 2) avoid duplicating the screenshot 3) allow tracking of the origin of this report.
I'll try to rephrase the issue description.

**Comment by parafin** [comment]
> > First thing, why disable trash in your system? Really strange...
> 
> I did not. I put my trash folder on a separated drive, and used a symlink (from ~/.local/share/Trash to that new location on the other drive). It seems that darktable can't follow that symbolic link.
> (I edited my first message)
> Maybe that should be in another bug report ?

I think this is not how trash is supposed to work - trash folder should be in the same FS as deleted files, so that simple move operation could be performed instead of slow and error-prone data copy. Since symlink points to another FS move operation fails and so does the trashing. I suspect this is how trash work on any OS - it doesn't do copying. Basically you're using it wrong.

**Comment by lapineige** [comment]
Well that's not the point of this issue… I'm reporting a strange and confusing behaviour of darktable when trash is inaccessible (including disabled trash).

**Comment by Nilvus** [comment]
> Well that's not the point of this issue… I'm reporting a strange and confusing behaviour of darktable when trash is inaccessible (including disabled trash).

That's the trash is inacessible or disabled that is strange, not darktable behavior. Trash is a part of any system and do not have to be moved, disabled or something else. You even have by default a trash on any external drive... that is for the related external drive...

**Comment by lapineige** [comment]
I would say that the trash could be disabled for reasons… but I think it's of topic.

If trash is supposed to be available, then why is there a whole pop-up to handle the case where the trash is disabled/not available ? (does this include the case when trash is full ? :thinking:)

And why does a "stop process" button does basically the same as "do [some action that we are trying to stop]" ?

**Comment by parafin** [comment]
> Well that's not the point of this issue… I'm reporting a strange and confusing behaviour of darktable when trash is inaccessible (including disabled trash).

I was answering your question whether it should be reported as a separate bug. It should not. But this bug report is valid.

**Comment by lapineige** [comment]
Ok, then I misunderstood what was your point. Sorry.
While I don't share your view about how trash folder should be handled, if you say that this (not following a symbolic link) is an expected behaviour then indeed this doesn't require a bug report. Thanks.

**Comment by parafin** [comment]
Symbolic links should be followed, just not to a different FS.

**Comment by lapineige** [comment]
You mean darktable will not follow them in that case, or that's an OS behaviour ?

(In case this matters: it not completely a different FS, it a different btrfs subvolume (linked to the same root volume) that is located on another hard drive. I suppose this has no influence, but just in case…)

**Comment by parafin** [comment]
I have no experience with btrfs, but I suspect move operation fails in the scenario you described. darktable just uses glib for trashing, it doesn’t implement it itself. It’s OS behaviour in a sense that trashing is just a move (rename) and OS returns an error, since it’s not possible to execute. The fact that it’s a symlink is completely irrelevant, it may as well be a mountpoint.

**Comment by TurboGit** [comment]
For what it's worth, I using btrfs since years without any issue.

**Comment by lapineige** [comment]
@parafin what's strange is that this move operation when trashing works perfectly with and instantly (except for big files) with all other software as far as I know…
Maybe it's a glib issue, I'll investigate (sorry for the little off-topic).

**Comment by parafin** [comment]
> @parafin what's strange is that this move operation when trashing works perfectly with and instantly (except for big files) with all other software as far as I know…

Move operation is instantaneous independent of file size, so you saying "except for big files" means exactly what I explained already several times - data is copied, which is IMHO nonsensical for trash to work this way.

**Comment by lapineige** [comment]
I understood that, but that's exactly my goal, I don't want those file to stay on their home filesystem when I put them in the trash (and btw a 1GB file takes <2s to be placed in the Trash, which I consider fairly acceptable).
Apart from darktable pop-up issues (which is the scope of this bug report), the issue (bug?) is that glib can't handle that.

**Comment by Solarer** [comment]
Hi there, I was just about to open a bug report about this myself.
I can confirm that darktable does not handle the pop-up correctly. When I hit "skip to next file" or "stop process" or hit "close button / ESC", the last picture in my selection for deletion is removed from my catalog but not removed from disk. I would expect that the file remains in my catalog since I did abort the process. This is clearly a bug.

The button "physically delete all files" could maybe be renamed to "permanently delete all selected files" and "physically delete" to "permanently delete one file".

About the reason why I ended up with this pop-up in the first place: I am also on BTRFS but I am not using any symlinks as @lapineige. But I think I am using sub-volumes so that seems to be the culprit.

People might also end up in this situation if their trash is full...

**Comment by lapineige** [comment]
> About the reason why I ended up with this pop-up in the first place: I am also on BTRFS but I am not using any symlinks as @lapineige. But I think I am using sub-volumes so that seems to be the culprit.

Good point… when I tried to re-enable the trash (in fact, create an empty trash folder, that was a temporary workaround) to check if there were another issue in darktable (than my symlink), it also didn't work. The only change I made in the midtime was to configure the subvolume differently…

> People might also end up in this situation if their trash is full...

Is that so, or does darktable handle that case differently ?

**Comment by Solarer** [comment]
> Is that so, or does darktable handle that case differently ?

I assume any problem with the trash will trigger this.

**Comment by Solarer** [comment]
I provided a PR that improves the dialog and fixes the problem of the disappearing image from the collection.
It does not fix the problem that images cannot be removed from btrfs sub-volumes. That is a glib issue.

**Comment by lapineige** [comment]
Thanks a lot. The glib issue was reported, let's hope it will eventually be fixed 🤞
