### ISSUE TITLE
Cannot run darktable from sources anymore

### ISSUE THREAD

**Issue by lock042** [darktable-org/darktable#8868]
Since a couple of day I can't run darktable from sources. It compiles well but when I try to run it I have:
```

[dt_ioppr_check_so_iop_order] missing iop_order for module vibrancergb 
ERROR: iop order looks bad, aborting.
```

I've deleted the build dir but it is the same.
Any idea?

**Comment by elstoc** [comment]
try clearing out your build and install directories before you build/install again

**Comment by lock042** [comment]
OK thanks. Already removed the build file. Will try to clean install again.

**Comment by lock042** [comment]
@elstoc : You were right about installation dir. Sorry for the noise
