### ISSUE TITLE
Markesteijn 3-pass - opencl could not copy buffer: -4

### ISSUE THREAD

**Issue by hqhoang** [darktable-org/darktable#8872]
**Describe the bug/issue**
With OpenCL, Markesteijn demosaic 1-pass works fine with tiling, but Markesteijn 3-pass failed at copy_buffer_to_buffer and fell back to CPU instead. Maybe it's by design that 3-pass needs more memory than calculated?

**To Reproduce**
1. with OpenCL activated, run `darktable -d opencl -d perf` 
2. open a RAF file
2. choose Markesteijn 3-pass as demosaic
3. export to JPG
4. see error in console output about demosaic failed on GPU

**Expected behavior**
Markesteijn 3-pass should work in OpenCL

**Platform**
* darktable version : 3.5.0+2089~g3977633f5
* OS                : Linux 5.8.0-50-generic
* Linux - Distro    : Ubuntu 20.04
* Memory            :  24GB
* Graphics card     :  nVidia GTX 1050Ti 4GB
* Graphics driver   :  460
* OpenCL installed  : yes
* OpenCL activated  :  yes

**Additional context**
Tested with 24MP RAF files from X-T20, tried different `opencl_memory_headroom` in the range of 1200 - 2000 with same result. nvidia-smi showed GPU memory usage of only 466MiB/4040MiB before exporting.

Console outputs of Markesteijn 1-pass:
`[default_process_tiling_cl_ptp] use tiling on module 'demosaic' for image with full size 6032 x 4014`
`[default_process_tiling_cl_ptp] (1 x 1) tiles with max dimensions 6032 x 4014 and overlap 12`
`[default_process_tiling_cl_ptp] tile (0, 0) with 6032 x 4014 at origin [0, 0]`
`[dev_pixelpipe] took 0.797 secs (0.627 CPU) processed 'demosaic' on GPU with tiling, blended on CPU [export]`

Console outputs of Markesteijn 3-pass:
`[default_process_tiling_cl_ptp] use tiling on module 'demosaic' for image with full size 6032 x 4014`
`[default_process_tiling_cl_ptp] (1 x 1) tiles with max dimensions 6032 x 4014 and overlap 18`
`[default_process_tiling_cl_ptp] tile (0, 0) with 6032 x 4014 at origin [0, 0]`
`[opencl copy_buffer_to_buffer] could not copy buffer: -4`
`[opencl_demosaic] couldn't enqueue kernel! -4`
`[default_process_tiling_opencl_ptp] couldn't run process_cl() for module 'demosaic' in tiling mode: 0`
`[opencl_pixelpipe] could not run module 'demosaic' on gpu. falling back to cpu path`
`scope draw took 0.001 secs (0.001 CPU)`
`[dev_pixelpipe] took 2.903 secs (8.606 CPU) processed 'demosaic' on CPU with tiling, blended on CPU [export]`

**Comment by hqhoang** [comment]
Added a bunch of `dt_print()` to `process_markesteijn_cl()` in `demosaic.c`, found out it couldn't copy the set of 4 buffers into another set on the second pass (around line 4550). The buffer copying failed after copying 2 buffers.

Given the buffer size of 387399168 bytes for a 24MP RAF, that's about 2955MB. As my 1050Ti card has only 4GB, and 500MB consumed by Ubuntu just booting up, lowering `opencl_memory_headroom` to 600MB allowed copying 3 buffers, but still failed at copying the 4th buffer.

I guess I could take the chance as justification to upgrade my laptop to a beefier one (perhaps with 6GB VRAM), but still, using 8 buffers is just too much. If we work around by copying the buffers back and forth multiple times, the performance saving might not worth running OpenCL anyway. But, I have no clue how the algorithm works, hopefully there's an easy fix.

**Comment by hqhoang** [comment]
Another interesting found while debugging: `Markesteijn 3-pass + VNG` only does 1-pass, it doesn't go through the second pass, thus works well on GPU.

Layering the outputs on top of each other in "difference" mode in GIMP, `1-pass vs 3-pass+VNG` doesn't show much differences comparing to `1-pass vs 3-pass` or `3-pass+VNG vs 3-pass`.

**Comment by jenshannoschwalm** [comment]
I had a deeper look into the the algo, i don't see a way to reduce the mem pressure for the CL path as the algo goes. We would have to do some sort of cl-specific tiling. I am not going to implement this ... maybe a dt developer with a fuji camera feels a need to do that.
