### ISSUE TITLE
"White Balance" module settings in history stack are not pasted to the destination files

### ISSUE THREAD

**Issue by kchen1** [darktable-org/darktable#8876]
When copying / pasting history stack from one file to multiple files under lightable mode, "White Balance" module settings are not pasted to the destination files.

Environment: windows v3.4.1.1
Canon CR2 from 5Ds R (both source and destination files)
scene-deferred workflow with the following modules enabled for the source history stack:
raw black/white point
white balance
demosaic
denoise (profiled)
orientation
exposure
input color profile
color calibration
contrast equalizer
sharpen
filmic rgb
vibrance
output color profile

**Comment by MStraeten** [comment]
ctrl+c just copies „safe“ modules, so use ctrl+shift+c to be able to select all modules, you want to copy/paste.
