### ISSUE TITLE
Collect Images issue?

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#8880]
Hi all,
Just noticed on 3.5 that if I go to the Collect Images module, and select "Folders" from the drop-down menu, you can ONLY view images from the lowest level of the folder structure.

Let's say I have a folder structure like this:

commercial shoots
... 2021
........ 2021-01-30
........ 2021-02-12
........ 2021-02-23

I would expect to be able to click on the 2021 folder, and see all images across the 3 sub-folders (like you can if you use the "Date taken" option), but that does not happen.

I've just checked 3.4.1, and the Folders view DOES allow you to select a mid-tier folder and see all images within all sub-folders, so I'm guessing this is a bug.

Linux Mint 20, Cinnamon 4.6.7, kernel 5.4.0-72 generic

**Comment by elstoc** [comment]
Behaviour can be changed with Ctrl+click and Shift+click. See https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/collect-images/

**Comment by todd-prior** [comment]
@elstoc  A bit off topic but under the darktable options there used to be file type so you could display only dng or only jpg or whatever...this seems to have been dropped??  It was useful for sure any thoughts why or did it disappear by accident??

**Comment by brucewilliamsphotography** [comment]
Todd,
Under collect images/tag, there is now a new option "darktable", and under THAT, you'll find "format", and under THAT, you'll find extension types! :)

**Comment by todd-prior** [comment]
Thats is the one I used to use I just didn't recall that is how I accessed it. I thought it was with the history tag....thanks must be my recall....

**Comment by elstoc** [comment]
So is everyone happy that the required options are there? Can we close this?

**Comment by brucewilliamsphotography** [comment]
Totes! :)

**Comment by todd-prior** [comment]
Fine by me
