### ISSUE TITLE
Activation of automatic presets

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#8881]
**Is your feature request related to a problem? Please describe.**

Automatic-presets are not activated directly after a raw image import

**Describe the solution you'd like**

Automatic-presets should be immediately activated as a part of the import process

**Alternatives**

The use of a style in the lighttable to activate the presets simply replicates the history entries which then requires history compression which is counter-productive

**Additional context**

**Comment by Nilvus** [comment]
Please provide more information as requested in issue where you began to write it: darktable version, OS, precise step by step, settings related you have, etc... It will be hard to help with so few infos. It works great on my side and for many users I know.

**Comment by elstoc** [comment]
> Automatic-presets should be immediately activated as a part of the import process

Automatic presets are activated when you open an image in the darkroom. If you want to auto-apply things in the lighttable, you should use a style.

**Comment by davidvj** [comment]
If one applies a style in lighttable then the presets are duplicated in 
the history which in turn requires compaction.

It is also better to see the image with the presets in the lighttable 
where decisions can be made to process or cull.

**Comment by elstoc** [comment]
> It is also better to see the image with the presets in the lighttable where decisions can be made to process or cull.

I prefer to cull using the jpeg preview, so have no processing steps before I choose to process the image.

**Comment by elstoc** [comment]
Does the setting `preferences>lighttable>use raw file instead of embedded JPEG from size` make any difference? i.e. if you set it to "always"

**Comment by ptilopteri** [comment]
perhaps an option in styles to compact history ???

**Comment by jenshannoschwalm** [comment]
Applying a style to an image without an existing valid history is not ok/safe. There are many ways to misuse that as can be seen in multiple issues.

I think the only sane solution is to check for an empty history and apply automatic presets in that case. Both for apply a style or copy&paste of history.

**Comment by AlicVB** [comment]
@davidvj : here, it works perfectly. I think you are using embedded jpeg for lighttable thumbs (and in that case, it's expected that you don't see you automatic preset applied)
as @elstoc said : check preference to be sure to not use embedded jpeg...

If that still don't work, we'll need more infos as @Nilvus said (the ones in the issue template)

**Comment by jenshannoschwalm** [comment]
Well, isn't the diffrence between using embedded jpegs or raw for thumbs that the second **has** a valid history before we can apply a style?

Apply a style without demosaic on a raw? How should that work?

**Comment by Nilvus** [comment]
@davidvj: after all those answers, think about posting here feedback and if issue solved, think about closing this issue to help us know which issues remains to work on. Thanks!

**Comment by davidvj** [comment]
I thank all those persons who provided feedback to this question .... by 
my changing to an alternate lighttable display option this question has 
been resolved for me and can be closed.

David
