### ISSUE TITLE
Color Balance Offset/Power/Slope settings placed side by side in GUI

### ISSUE THREAD

**Issue by hodapp512** [darktable-org/darktable#8884]
**Describe the bug/issue**
The image shows how my Color Balance module shows the offset/power/slope side-by-side rather than placed above and below each other. I have played around with resizing and clicking as many options as possible, but it stays in that layout.

**To Reproduce**
I don't know how to reproduce this. I'm using Darktable 3.4.1.1 on Windows 10. The layout occasionally switches back and forth between the correct layout (each section placed above/below each other) and this side-by-side layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/60491596/117372525-49676000-ae8f-11eb-8e8d-064a0f097adc.png)

**Platform**
* darktable version : 3.4.1.1
* OS                : Win10 20H2
* Memory            :  8 GB
* Graphics card     : Nvidia Geforce MX150
* OpenCL installed  : Yes
* OpenCL activated  :  Yes

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? Yes

**Comment by ralfbrown** [comment]
See the manual: https://www.darktable.org/usermanual/en/module-reference/processing-modules/color-balance/ , then set the preference or click on the section header.

**Comment by todd-prior** [comment]
Not sure about the switching but this is a setting in preferences....you can decide which way you want it displayed by default...

**Comment by elstoc** [comment]
You can also click on the section header to toggle between the options, which is probably how you accidentally set it like this.
