### ISSUE TITLE
Database upgrade takes a very long time with no visible progress

### ISSUE THREAD

**Issue by garrett** [darktable-org/darktable#8887]
**Describe the bug/issue**

After backing up my configuration, I decided to try out darktable built from the master branch.

I ran darktable and a dialog popped up to upgrade data.db. The upgrade took a few moments.

Then a second dialog popped up to upgrade the library.db. This took almost 17 minutes. During this time, there was no feedback, either from the terminal or in the UI. It looked like darktable was hanging.

**To Reproduce**

1. Have a large library, like most users of darktable.
2. Upgrade darktable from one version to another.
3. Run darkable.
4. Wait for a very long time.

**Expected behavior**

I would have expected some sort of update process. There should be at least a UI spinner. Ideally, there would be a progress bar.

This has been an issue in previous updates. I've just been patient. I don't remember the whole update taking 17 minutes before, however.

**Platform**

* darktable version : 3.5.0~git2099.cf47c7e45f-5823.2
* OS                : Linux 5.11.17-300.fc34.x86_64
* Linux - Distro    : Fedora 34
* Memory            : 16 GB
* Graphics card     : Intel 620
* Graphics driver   : Intel NEO
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : Wayland
* Desktop           : GNOME 40
* GTK+              : gtk3-3.24.29-1.fc34.x86_64

```
this is darktable 3.5.0~git2099.cf47c7e45f-5823.2
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Additional context**

 - Can you reproduce with another darktable version(s)? Yes, this has happened on every upgrade with database changes. It seemed extra excessive this time around.
 
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? No, because the delay scales with the library size, as darktable needs to upgrade the libraries.

**Comment by MStraeten** [comment]
Maybe thats just the recompilation of all opencl kernels.

**Comment by garrett** [comment]
It's definitely not the OpenCL recompilation, as (coincidentally) I ran darktable-cltest before even telling the new version of darktable to open... and I watched darktable-cltest recompile all the OpenCL kernels.

I timed it for both database upgrades: 16 minutes 59 seconds.

I have a _very large_ library of photos, mainly raw, that spans back to 1999. (The switchover to raw was in 2002.)

---

Back to OpenCL:

```
$ rm -rf ~/.cache/darktable/cached_kernels_for_IntelR*

$ time darktable-cltest

[lots of output, including stuff like...]
[opencl_init] device 0: Intel(R) HD Graphics 620 [0x5916] 
     GLOBAL_MEM_SIZE:          12578MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           21.16.19610
     DEVICE_VERSION:           OpenCL 3.0 NEO 
0.649912 [opencl_init] options for OpenCL compiler: -w  -DINTEL=1 -I"/usr/share/darktable/kernels"
0.652200 [opencl_init] compiling program `demosaic_ppg.cl' ..
0.652473 [opencl_fopen_stat] could not open file `/home/garrett/.cache/darktable/cached_kernels_for_IntelRHDGraphics6200x5916_211619610/demosaic_ppg.cl.bin'!
0.652480 [opencl_load_program] could not load cached binary program, trying to compile source
0.652491 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/demosaic_ppg.cl' MD5: 'd2f2b5f78749466c81756deb5b4b3135'
1.171776 [opencl_build_program] successfully built program
[...even more output...]

Executed in   17.27 secs
```

So OpenCL compilation took 17 seconds. Database upgrading took 17 _minutes_ (with no feedback, which is the issue here).

---

My photo library is right under 5 TB. And the library sizes are:
- data.db: 1.0M
- library.db: 460M

I do remember previous upgrades taking a while, but this upgrade feels a lot longer than what I remembered. I guess there are more things getting upgraded in the database this time around? I know most people probably won't have a library this size, but even someone with a library around 1/10 of the size of mine would be waiting for almost 2 minutes with no feedback... and it would probably even longer too, if they have a hard disk (this is on an SSD) or less RAM.

**Comment by ptilopteri** [comment]
you definitely have something weird.  

I have 950mb library.db on openSUSE Tumbleweed
plasma5/kde
36gb memory and no swap
10 year old i7 970
rotating rust
nvidia GTS 450 1gb

running dt master 5e025b46c

an "upgrade" of my library.db has never taken greater 
than 60 seconds, tmk.

**Comment by MStraeten** [comment]
Did you upgrade from a 3.4.x database? There werde some changes adding foreign keys and extending indexes.

**Comment by garrett** [comment]
> Did you upgrade from a 3.4.x database? There werde some changes adding foreign keys and extending indexes.

Yep, this was an upgrade from 3.4.1. I'm sure most others users will hit this to some degree too.
