### ISSUE TITLE
Soft proof: make importing color profiles user-friendly

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8888]
Hey folks, before printing I want to first check the soft proof with a printer's color profile.

My lab offers color profiles for their printer and the specific paper. But then importing this color profile into darktable so that I can use it in the soft proof feature looks like this
1. Download the lab's color profile
2. Create the folder hierarchy `color/out` in darktable's user dir (see below)
3. Copy the .icc color profile there and restart darktable

Reading the docs I could figure out the directory structure and could copy it there

    $DARKTABLE/share/darktable/color/out and $HOME/.config/darktable/color/out

It would be amazing to make this important feature easier to use for beginners; maybe we can have a file chooser dialog where the user just has to select the path to the .icc file?

Thoughts?

**Comment by wpferguson** [comment]
We could do a lua script to add the color profiles.

**Comment by wpferguson** [comment]
@daniel-j-h here's a lua script that will let you add and remove color profiles.  Give it a try and let me know if you have any suggestions for improvement.

[color_profile_manager.zip](https://github.com/darktable-org/darktable/files/6446348/color_profile_manager.zip)
