### ISSUE TITLE
Layout buttons can be pressed with right mouse button but do not light up

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#8890]
**Describe the bug/issue**
The buttons to change the layout can be pressed with left or right mouse button. When the right button is used, the button does not light up, but the layout is changed

Right mouse
![image](https://user-images.githubusercontent.com/2805109/117497377-b7d41d00-af78-11eb-98dd-1e573a4fa6bf.png)

Left mouse
![image](https://user-images.githubusercontent.com/2805109/117497428-c4f10c00-af78-11eb-869b-fb1c51dc27a9.png)

**To Reproduce**
Click on any of the layout buttons using the right mouse button. The layout will change but the button does not light up.

**Expected behavior**
Either, the right mouse button should not be able to press the buttons or they should at least light up.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.5.0+1967~g4024d7d73
* OS                : Manjaro Linux
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by Nilvus** [comment]
There's no right action on those buttons so it's no big deal. The real action is with left mouse (even if you find that right button do the same) so a really minor issue. And just forget right click here as nothing had never been set here!

Anyway, it's seems to be the only part which such behavior. @AlicVB: what's your view on that (even if that a really minor issue)?

**Comment by Nilvus** [comment]
And the only expected behavior is that the right mouse button should not be able to press the buttons.

**Comment by AlicVB** [comment]
Either we don't handle right click at all, either we don't differentiate between right and left click...
I don't really care...
In any case that *seems* very simple to fix ;)

**Comment by elstoc** [comment]
I think generally we don't differentiate unless we start to assign functionality to specific types of clicks or modifiers.
