### ISSUE TITLE
Allow non-uniform scale in lens correction

### ISSUE THREAD

**Issue by alegalle** [darktable-org/darktable#8895]
The scale slider in lens correction module applies evenly to the image, scaling both horizontally and vertically, preserving aspect ratio.

In the niche use case of using an anamorphic cine lens for still photography, the raw image must be stretched horizontally in post while preserving the vertical scale, thereby increasing the aspect ratio.  Currently, as far as I can see, this is not possible from within darktable.  We have to export the image and perform the stretch in Gimp etc.

Having the option to scale asymetrically in the lens correction module would allow darktable to be used in a seemless manner for this use case.  I suggest a check box to toggle the option on while leaving the current uniform scale as the default.

I have used darktable for many years but this is my first time commenting here so please forgive any omissions/errors in this report

**Comment by ralfbrown** [comment]
Anamorphic correction **is** available -- in the _perspective correction_ module.  Switch its lens model from from "generic" to "specific" to enable an aspect ratio slider.

https://www.darktable.org/usermanual/en/module-reference/processing-modules/perspective-correction/

@elstoc: While the dev manual now has a note about anamorphic unsqueezing under perspective correction, perhaps there should also be a cross-reference to it in the lens correction module's page.

**Comment by elstoc** [comment]
I'm happy to take your suggestion on that if you think it would be useful - I mostly just copy-edited these sections from the old manual. Could you propose a PR please?

**Comment by alegalle** [comment]
@ralfbrown thank you, that information solves my issues.  For me, the lens corrections modules was the obvious place to look as this is an intentional lens distortion rather than a perspective related problem
