### ISSUE TITLE
Poposal: selected images should have higher priority than images in focus

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#8898]
**Describe the bug/issue**

Currently, in culling (fixed) mode selecting a picture does not have any effect. So 
- Ctrl-A and export
- Selecting a few pictures to delete / change star rating / apply history stack

are not possible. Instead it will only affect the picture(s) that you look at.

The reason for this is that darktable seems to deal with pictures in the order: 
>hovered > focused > selected. 

I propose to change this order to 

>hovered > selected > focused. 

This should only affect fixed culling and maybe full preview mode. Since the other modes cannot focus a picture and in culling dynamic mode: selection and focus are the same.

PS: Maybe there needs to be an exception for full preview mode, because in there I would expect that actions are only applied to the picture I look at even if I selected the full collection. 

**Platform**
* darktable version : 3.5.0+1967~g4024d7d73
* OS                : Manjaro Linux
* Linux - Distro    : e.g. Ubuntu 18.4
* OpenCL installed  : yes
* OpenCL activated  :  yes

**Comment by elstoc** [comment]
You should take a look at #6025, which is essentially discussing this issue.

**Comment by Solarer** [comment]
Thanks, I will discuss this matter over there!
I am surprised something this important has been open for so long

**Comment by Nilvus** [comment]
> Thanks, I will discuss this matter over there!
> I am surprised something this important has been open for so long

It's just not so simple. implementing things could be fast, being agree on a standard way to implement in all parts of darktable, and so change some habits take time!

**Comment by Nilvus** [comment]
And especially as there's many things to work on/improve/implement and some things finish forgotten!
