### ISSUE TITLE
FR: Double click to unfold tree and include subfolders

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#8906]
**Problem**
- In import-module and collect-images you have to click on the small triangle to unfold the subfolders
- it seems to be cumbersome to some users, that a normal double click on a parent-folder does not show images of subfolders (see #8880 and IRC discussion)

**Solution**
- double-click on the name of a tree-element unfolds the subfolders in the tree
- change the shift-behaviour:
  - normal double click shows this folder + subfolders
  - shift + double click shows only this folder
  - ctrl + double click shows only subfolders (like now)

**Comment by jade-nl** [comment]
This inconsistent behaviour should indeed change.

Right now you need to use the white triangle/arrow top open a (sub)folder in this window:

![white arrow](https://user-images.githubusercontent.com/56407344/117582159-2e475b00-b0f0-11eb-9045-0b29f6064073.png)

If I click on *+ other locations...* I go to this window:
![double click](https://user-images.githubusercontent.com/56407344/117582208-651d7100-b0f0-11eb-9418-aef653a028fa.png)

But in here I cannot use a single click, on the folder icon or the name, to open a folder; I have to double click (on Miscellaneous for example). It is bad enough that the left side is single click and the right side is double click. Please don't add another variant as shown in the first screenshot.

---

On a side note: It seems to me that this new file/folder import thing is a bit of a mess and brings more confusion and extra, inconsistent, clicks then easy of use. Quick fixes and good intentions don't seem to fix it atm.

I know that another issue about this was closed but I would strongly advise the maintainer(s) to:
* Be part of #darktable (not necessarily as a participant, but at least to get an idea what lives among users/developers)
* Think again about (not) reverting this. Maybe there is a better solution then the one in current stable, but I doubt if the current solution will be user-ready for 3.6.

**Comment by elstoc** [comment]
@jade-nl: we don't have much control over the behaviour of the second window ("open folder") you've included above - that's mostly under the control of Gtk plus whatever bells-and-whistles your DE adds on to it.

**Comment by jade-nl** [comment]
@elstoc : Yep, I know that the second window is GTK+. I'm just pointing out that we need consistency: Choose for GTK+, keep using the GTK+ style even if one isn't forced to do so.

**Comment by elstoc** [comment]
In the collect module, don't forget that there's a preference to control single-click behaviour that we need to be careful of.

**Comment by elstoc** [comment]
It should be noted that double-click is generally a bit of a pain, because the "click" handler still has to work, and it won't know if there will be a second (linked) click when it fires the first time. So it probably won't be possible to implement a double-click handler that doesn't select as well as expand.

**Comment by johnny-bit** [comment]
It's possible to implement double-click along with click handler but it's annoying:

1. click event comes in: start a timer with timeout equal to double-click delay
2. in case second click didn't come execute timer handler (which is actually a single-click handler)
3. in case second click came in - cancel timer and execute double-click handler

it's annoying enough that it's rarely implemented (so you either get a single or double click handler but not both)

**Comment by johnny-bit** [comment]
Shut up bot, there's an active linked pr.
