### ISSUE TITLE
Inconsistent text for filmicrgb in quick access panel

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#8908]
**Describe the bug/issue**

Simple one but don't know where to update that. See screenshot below:

![image](https://user-images.githubusercontent.com/45535283/117587406-54c7bf00-b10d-11eb-8ddb-9d7bc3eb2c7a.png)

![2021-05-09_23-27](https://user-images.githubusercontent.com/45535283/117587419-6a3ce900-b10d-11eb-84a7-09e38bbc6fba.png)

Should be so shadows/highlights balance and middle tones saturation if using v4 or v5 (that's the case here). About middle tones saturation and extreme luminance, even if I use v4 or v5, I don't see middle tones saturation in quick access panel choices.

**Comment by elstoc** [comment]
I suspect the issue with shadows/highlights might be that the slash is used as a field separator and so has been replaced. @AlicVB please can you advise.

**Comment by AlicVB** [comment]
not so easy, but I think that PR #8929 fix it
