### ISSUE TITLE
Double-click in import-in-place doesn't work

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#8915]
Ubuntu 18.04   dt 3.5.0+1966~g12d7a9967-dirty

If I select a raw in the right-hand panel of "import in-place", double-click has no effect, whereas pressing Enter brings it into lighttable as expected.

**Comment by todd-prior** [comment]
Somewhat related in the folder pane double clicking on a folder should expand it if thereare subfolders I think,  but only the little arrow to the left works to expand the view to display subfolders...maybe intentional but not generally OS convension I don't think.

**Comment by Nilvus** [comment]
As this is more a feature request and #8906 is all about that (and discussion have been started on), @RawConvert, is it ok for you if we close this issue and continue so in #8906? Better to not have 2 "issues" opened about same thing.

**Comment by johnny-bit** [comment]
This isn't a duplicate though and is not related to #8906 directly

This issue is about: User wants to import single picture by double clicking on the image in the main view

#8906 is: user wants to unfold directory tree by double clicking the folder in the left hand view.

**Comment by elstoc** [comment]
@johnny-bit yes you're right of course. I hadn't spotted that.

**Comment by RawConvert** [comment]
@Nilvus , I don't see it as a feature request, more a bug, since it's surely normal that double click and Enter do the same thing.

**Comment by Nilvus** [comment]
So that just means I don't understand correctly this issue. Thanks for your answers.
