### ISSUE TITLE
Memory Leak on "copy & import"

### ISSUE THREAD

**Issue by robMate** [darktable-org/darktable#8925]
**Describtion**
While importing images form a SDcard via the "copy & import" menu my RAM is continuously filling until dartable is crashing because of the RAM full. This only happens when the size of selected images is bigger than my RAM. If the size is smaller than the RAM only gets released after I close darktable. 

**To Reproduce**
1. Go to "copy & import" in lighttable  
2. Select images to import
3. click "copy & import"
4. Memory is filling and doesn't get released (or darktable is crashing if memory is full) 

**Expected behavior**
RAM should not get filled until darktable crashes while importing images.

**Screenshots**
Import setup
![Bildschirmfoto von 2021-05-11 18-37-41](https://user-images.githubusercontent.com/5657121/117857001-99c62f80-b28c-11eb-9dec-3bad0fce4dd4.png)
 Memory is continuously filling until full
![Bildschirmfoto von 2021-05-11 18-44-07](https://user-images.githubusercontent.com/5657121/117857156-c37f5680-b28c-11eb-8e9a-d44dbee5dbeb.png)
![ram](https://user-images.githubusercontent.com/5657121/117857183-c8dca100-b28c-11eb-9e8c-4e2c39fe2638.png)

**Platform**
* darktable version : 3.5.0+2159~g22aba1f900-dirty
* OS                :  Manjaro 5.10.34-1-MANJARO
* Linux - Distro    : Manjaro
* Memory            :  16GB
* Desktop           : Gnome
* Package AUR  :   https://aur.archlinux.org/packages/darktable-git

**Comment by phweyland** [comment]
Oooops!
yes, awful!
In control_jobs.c, 'data' declared line 2075 is not freed. Should be freed around line 2115.
I won't be back in front of my computer before several days. If somebody could clean up this that would be great.
