### ISSUE TITLE
bauhaus sliders incorrectly formatted on popups

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8928]
When they appear on a popup, bauhaus sliders have a different background to the normal module background. The marker triangles on the sliders therefore have an obvious light grey outline on them. This correctly looks like empty space in a module but looks wrong on the popup.

On a module:
![Screenshot_2021-05-11_20-09-01](https://user-images.githubusercontent.com/9555491/117871043-da29ab80-b294-11eb-8e24-c8c5c8b1ed81.png)

On a popup:
![Screenshot_2021-05-11_20-13-05](https://user-images.githubusercontent.com/9555491/117871466-50c6a900-b295-11eb-95c0-538243051840.png)

**Comment by Nilvus** [comment]
Yes, of course. A popup needs to be distinguished. Having same background is jus awful and made popup harder to distinguish.
