### ISSUE TITLE
Canon EOS 2000D

### ISSUE THREAD

**Issue by tjapro** [darktable-org/darktable#8931]
**Describe the bug/issue**
The Canon EOS 2000D profile doesn't appear in the list.

**To Reproduce**
See the screnshots bellow, but a question: is that EOS D2000 the one I want?

**Expected behavior**
Appear the Canon EOS 2000D profile, and auto-apllied, in this case, by lens correction module.

**Screenshots**
![Captura de ecrã de 2021-05-12 02-35-32](https://user-images.githubusercontent.com/7900361/117905710-86868480-b2cb-11eb-9467-adb220a2b93d.png)
![Captura de ecrã de 2021-05-12 02-35-44](https://user-images.githubusercontent.com/7900361/117905712-87b7b180-b2cb-11eb-9dd3-f6db346cd682.png)

**Platform**

this is darktable 3.4.1
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

Linux localhost.localdomain 5.11.18-300.fc34.x86_64 #1 SMP Mon May 3 15:10:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Fedora 34

**Comment by johnny-bit** [comment]
This is not a darktable issue, but lensfun data. use steps described in https://github.com/darktable-org/darktable/wiki/Camera-support#lens-correction - most importantly run `lensfun-update-data` and restart darktable.

**Comment by tjapro** [comment]
Thanks a lot. Solved!
