### ISSUE TITLE
unwanted crop is introduced when crop / crop & rotate are combined

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8942]
With latest master, a common use case will be to crop with the crop module and do rotation with the crop & rotate module. However, there seems to be some sort of interplay between the two modules meaning that cropping gets messed up when both are enabled.

To reproduce, on a fresh edit:

1. Open the crop module and crop the image (a fairly severe crop to make it more obvious)
2. Open the crop & rotate module and enable it without cropping the image further
3. Collapse the crop & rotate module
4. An additional crop is introduced without request

darktable 3.5.0+2197~g0ee2e87be on ArchLinux

**Comment by elstoc** [comment]
@AlicVB would you mind taking a look at this please.

**Comment by AlicVB** [comment]
ouch ! good catch ! PR #8945 should fix it...
