### ISSUE TITLE
darktable crashes with "Floating point exception (core dumped)" but darktable-cli works just fine

### ISSUE THREAD

**Issue by sniklaus** [darktable-org/darktable#8951]
**Describe the bug/issue**
The following DNG makes darktable crash with an "Floating point exception (core dumped)" error: [dng.zip](https://github.com/darktable-org/darktable/files/6470557/data-631798-g50ilw7ggxkrze7lbkdc.dng.zip)

All other tools I tried are able to read this example DNG just fine though (including RawTherapee and Lightroom). Most interesting though, even darktable-cli is able to read this DNG and save it as a TIF so I am under the impression that it is a bug in darktable.

**To Reproduce**
Open the DNG referenced above in darktable, preferably having launched darktable from a terminal to also see the error message.

**Expected behavior**
That the DNG is opened without crashing, just like in RawTherapee and Lightroom.

**Platform**
* darktable version : 3.0.1
* OS : Linux 5.4.0-71-generic
* Linux - Distro : Ubuntu 20.04 LTS
* Memory : 32 GB
* Graphics card : NVIDIA GTX 1650
* Graphics driver : NVIDIA 460.56
* OpenCL installed : unknown
* OpenCL activated : unknown
* Xorg : 1.20.9
* Desktop : Xfce 4.14.0
* GTK+ : 3.24.20
* gcc : 9.3.0
* cflags : unknown
* CMAKE_BUILD_TYPE : unknown

**Comment by TurboGit** [comment]
We won't handle a bug report from ld darktable version : 3.0.1. Please update and create another issue if the problem still exists. Thanks.

**Comment by jenshannoschwalm** [comment]
Anyway, confirmed for todays master here.

**Comment by TurboGit** [comment]
@jenshannoschwalm : ok thanks for testing, I'm reopening then.

**Comment by TurboGit** [comment]
@jenshannoschwalm : should I assign this to you ?

**Comment by jenshannoschwalm** [comment]
You can do so. Already did some testing and yet don't understand whether it's the gtk stuff or commited parameters maybe in colorin or temp.

**Comment by TurboGit** [comment]
Done, thanks.

**Comment by jenshannoschwalm** [comment]
I will try to fix the crashing for such images as there might me more coming in of such files **BUT** some really strange data shown via exiftool

1. There is no Active Area tag
2. we have a Original Default Crop Size == undef undef
3. There is no color matrix and no Calibration Illuminant

not a nice file at all.

**Comment by sniklaus** [comment]
Thanks everyone for working on this!
