### ISSUE TITLE
Exported output does not correspond to export settings

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8952]
Hey folks,

I think I just ran into two separate but related issues here with the export settings, when trying to export for a 21cm x 21cm print.

The first one is there's a difference between entering `21,4` and `21.4`. It looks like this is related to floating point parsing depending on the user locale? For the user it's confusing and I was wondering what's going on here.

In the following gif, focus on the input sizes in cm and the gray text showing the computed size in pixel.

![print-21x21](https://user-images.githubusercontent.com/527241/118137112-20058180-b405-11eb-8149-91836e07ce4d.gif)

What's even more confusing is that if I enter `21.4` (dot), close darktable and open it again, the value now shows up as `21,01` (comma, and yes the value shows up as 21,01 and not 21,04 what I expected).

The second issue is that no matter if I use comma or dot, I never get an actual square. Check this out, here are some images exported with `21,4 x 21,4` and `21.4 x 21.4`. Neither of them have `width == height` pixels in their output:

```
$ file *
DSCF0306.png:    PNG image data, 2528 x 2523, 8-bit/color RGB, non-interlaced
DSCF0306_01.png: PNG image data, 2528 x 2527, 8-bit/color RGB, non-interlaced
DSCF0306_02.png: PNG image data, 2481 x 2476, 8-bit/color RGB, non-interlaced
DSCF0306_03.png: PNG image data, 2481 x 2480, 8-bit/color RGB, non-interlaced
```

What's going on here? :thinking: 

For context: my use case is printing a 21x21cm print @300 DPI with 2mm border at each side (for :scissors:).

**Comment by daniel-j-h** [comment]
For the record this is with the latest stable Darktable 3.4.1.

**Comment by magicgoose** [comment]
re. 2nd issue: is the image cropped to square (using "crop and rotate" module)?
if not, I guess resizing just isn't allowed to crop or distort aspect ratio. It would normally constrain the largest dimension, and then the other dimension will be smaller, if it's different.

**Comment by daniel-j-h** [comment]
Yes, I have the crop module set to give me a square crop. That's why not getting a square output is unexpected to me 🤔

**Comment by jenshannoschwalm** [comment]
I checked that on todays master  and can **not** reproduce.

Have you checked the exported images in other ways for the dimensions? (Your export settings with "allow upscaling" seem to be fine)

**Comment by johnny-bit** [comment]
I've checked and while the dot vs comma issue is present, I can't reproduce issue with non-square output with square crop.

**Comment by daniel-j-h** [comment]
Unfortunately I can not share the picture with you - here are the crop module's settings, in case it heps

![crop-module](https://user-images.githubusercontent.com/527241/122726999-da936a00-d276-11eb-8d4d-d1b90039224a.gif)


> Have you checked the exported images in other ways for the dimensions? (Your export settings with "allow upscaling" seem to be fine)

I have checked them with the `file` command line utility, with gimp, and with the gnome image previewer - in all cases the pictures are not squares (width pixels != height pixels).

**Comment by jenshannoschwalm** [comment]
@TurboGit can be closed too ...

**Comment by TurboGit** [comment]
Closed !
