### ISSUE TITLE
crop / crop & rotate focus issue

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8956]
As mentioned in #8945, and now in darktable 3.5.0+2208~gbea8e81fd on ArchLinux.

1. Add a crop in the crop module and double-click to commit
2. Expand crop & rotate but don't make any changes
3. Expand crop again
4. Preview image is no longer cropped (you have to collapse the crop module to get it back again)

**Comment by MStraeten** [comment]
reproduced with osx. 
Reexpanding cop should activate the edit mode and so show the crop frame instead of just expanding the gui.
Like it is done if c&r wasnt just expanded but also activated.
