### ISSUE TITLE
No export_width / export_height metadata displayed

### ISSUE THREAD

**Issue by vithom** [darktable-org/darktable#8958]
## Describe the bug/issue
In the image information module, the metadata corresponding to *export_width* and *export_height* are always displayed like "-"

![Screenshot_2021-05-13 22-30-33](https://user-images.githubusercontent.com/74423292/118184330-80171a80-b43b-11eb-83fd-99ab99310d90.png)

I have checked in the database the columns "output_width" and "output height" from the *images* table (I suppose that this is the corresponding data) and almost everything is *NULL* as value. Exception for image cloned where the fields contain the original image width and height, but the display still remains "-" in the *image information* module.

![Capture d’écran de 2021-05-13 22-37-30](https://user-images.githubusercontent.com/74423292/118185319-b0ab8400-b43c-11eb-8d0e-66d4af226c04.png)

## To Reproduce
Just launch darktable and check for several images in your lighttable if you have something different than "-" for the *export_width* and *export_height* metadata lines in the *image information* module

## Expected behavior
To have the right height and width displayed

## Idea for resolution
If the intention is to display the width/height of thelast export, it should be filled in the database when the export is done.

To me, this information is not really useful but the final size of the image after a crop could be a much more relevant information to display.

### Platform
* darktable version : master branch
* OS                : Linux - kernel 5.12.1
* Linux - Distro    : arch
* Memory            : 16 Go
* Graphics card     : [AMD/ATI] RV770 [Radeon HD 4850]
* Graphics driver   : Kernel driver in use: snd_hda_intel
* OpenCL installed  : No
* OpenCL activated  : No
* Xorg              : No (Wayland)
* Desktop           : Gnome 40.1.0
* GTK+              : 
* gcc               : 10.2
* cflags            : 
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Comment by jenshannoschwalm** [comment]
I also think the info is not useful at all for a normal user situation. What do you think of doing a pr displaying this only if used in a "dt -d print" scenario? I would certainly like that!

**Comment by vithom** [comment]
I could do that.
And what about the idea to instead display the real size of the image after a crop/crop & rotate module ? This is more useful to me.

**Comment by jenshannoschwalm** [comment]
Hi @vithom the verified size was somewhat broken so i checked that and did a pr on that.

About your idea with the cropping? Why not, personally i would like that and would appreciate you going into it :-)

**Comment by AlicVB** [comment]
I would prefer indeed if final_width/height could show what they are for : the final image size including the crop if needed...

What is the more difficult is how to do that without loosing too much perfs... 
Getting final size is not so difficult if we have the main pipe all initialized...

So what I would propose is to let final dimension empty (or equal to initial size) until  we need it for zoom preview or until we enter darkroom. In this case, I would propose to rewrite (and rename ?) `dt_image_reset_final_size` so it keep values up to date, using `dt_dev_pixelpipe_get_dimensions` with current `darktable.develop->pipe`. That should cost about to nothing !

What could also be added is to update this dimension each time we loose focus on a "distort" module. Again, as we already have the main pipe running, that should cost about to nothing.

**Comment by vithom** [comment]
Thanks for the clarification on how to do it. I will try.

**Comment by dterrahe** [comment]
@AlicVB it seems that when this is done when a module is collapsed, the routine `dt_image_update_final_size` has to wait on a mutex for the pipe to finish a complete calculation. This makes the ui unresponsive for a prolonged period of time. Perhaps it would be better to do this in a DT_SIGNAL_DEVELOP_PREVIEW_PIPE_FINISHED signal?

**Comment by AlicVB** [comment]
@dterrahe : not sure to remember exactly how it works, but iirc, doing this would significantly increase the number of time dt_image_update_final_size is called.
actually, it should only be called in the case where the output size is changed...

in which case exactly do you see such behavior ?
