### ISSUE TITLE
new crop module not shown in list of all modules

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#8959]
**Describe the bug/issue**
In darkroom, when one clicks on a module-group tab which is already open, dt toggles between showing the modules belonging to that group and showing all (non-deprecated) modules.  However, the new crop module only appears in the list of all modules if it is currently active.

**To Reproduce**
1. Open a new image (or discard history)
2. Activate any of the tabs, for example the "active modules" tab
3. Click the tab again to show all modules
4. Note that there is nothing between "tone equalizer" and "graduate density"
5. Type "crop" in the search box, and click on the new crop module's on/off button to activate it
6. Clear the search box, and note that now "crop" appears between "tone equalizer" and "graduated density"
7. Select the prior step in the edit history and note that "crop" disappears again
8. step forward and back between the last two steps of the edit history and watch "crop" appear and disappear

**Expected behavior**
The new crop module should always appear when all modules are being displayed.

**Platform**
* darktable version : 3.5.0+2235~g8d688a8b6
* OS                : Linux
* Linux - Distro    : Mageia
* OpenCL installed  : no
* gcc               : 8.4.0
* CMAKE_BUILD_TYPE  : Release

**Comment by elstoc** [comment]
My understanding is that "all modules" is only intended to include modules that are currently visible in a group or currently active and this is how it appears to work at the moment. If you add "crop" to a group and then try again, you should see it when you click twice.

So I think this is behaving as designed.

**Comment by ralfbrown** [comment]
You're right, after I added the new crop module to a group, it shows up as expected.  May be worth mentioning in the manual if it isn't already (I don't remember seeing anything like this).

Sorry for the noise.

**Comment by elstoc** [comment]
Done: https://github.com/darktable-org/dtdocs/commit/0d487d82d10f4d6c1764f92707b3370550101ee3
