### ISSUE TITLE
Noise profile for Canon M50/KISS M

### ISSUE THREAD

**Issue by matt-maguire** [darktable-org/darktable#8961]
For noise profiles, please also attach the entire archive with `.pdf` plots.

I created some noise profile for the Canon M50 / KISS M ("KISS M" is the Japanese brandname for the M50).

Originally the scripts populated the json with model name "EOS KISS M", but the denoise(profiled) module couldn't find the profiles. Since EOS KISS M is just an alias, I updated the model name in the json to EOS M50, and then the profiles were correctly detedcted.

@rawfiner Can you please review the output and let me know if it looks ok? I can also supply tthe jpgs and/or raw files as well if it is of interest.
file:///home/mmaguire/canon-m50.tar

**Comment by matt-maguire** [comment]
Looks like github doesn't like tar files, here is the archive in ZIP format:
[canon-m50.zip](https://github.com/darktable-org/darktable/files/6478349/canon-m50.zip)

**Comment by rawfiner** [comment]
Output is ok for me
