### ISSUE TITLE
OpenCL Compile eror in colorspace,h

### ISSUE THREAD

**Issue by MartinScharnke** [darktable-org/darktable#8966]
**Describe the bug/issue**

OpenCL compile error

**To Reproduce**

/usr/share/darktable/kernels/colorspace.h:427:12: error: subscripted access is not allowed for OpenCL vectors
  RGB.x -= D65[0];
           ^   ~
/usr/share/darktable/kernels/colorspace.h:428:12: error: subscripted access is not allowed for OpenCL vectors
  RGB.y -= D65[1];
           ^   ~
/usr/share/darktable/kernels/colorspace.h:442:39: error: subscripted access is not allowed for OpenCL vectors
  RGB.x = Ych.y * native_cos(Ych.z) + D65[0];
                                      ^   ~
/usr/share/darktable/kernels/colorspace.h:443:39: error: subscripted access is not allowed for OpenCL vectors
  RGB.y = Ych.y * native_sin(Ych.z) + D65[1];
                                      ^   ~

1.656964 [opencl_init] failed to compile program `extended.cl'!
1.656977 [opencl_init] no suitable devices found.
1.656980 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
1.656981 [opencl_init] initial status of opencl enabled flag is OFF.

**Expected behavior**
Successful compile, OpenCL available

**Platform**

 darktable --version
this is darktable 3.5.0~git2210.85569c3aa2-1
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

uname -a
Linux baraddur 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

free
              total        used        free      shared  buff/cache   available
Mem:       32871492     2488344    26929120      307764     3454028    29610684
Swap:      34815996           0    34815996

[opencl_init] device 0: GeForce GTX 1660 
     GLOBAL_MEM_SIZE:          5942MB
     MAX_WORK_GROUP_SIZE:      1024
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 64 ]
     DRIVER_VERSION:           460.73.01
     DEVICE_VERSION:           OpenCL 1.2 CUDA

**Comment by TurboGit** [comment]
Fixed some minutes ago. Please upgrade sources.
