### ISSUE TITLE
SSD cache for RAW files

### ISSUE THREAD

**Issue by asdkant** [darktable-org/darktable#8975]
**Is your feature request related to a problem? Please describe.**
A very common scenario is to have a fast SSD as the system drive and one or more HDDs for storing large amounts of data

My situation is very similar to that scenario: I have a pretty large collection of RAW files that I'd like to keep in my DT database, to the level that it's not economically viable to have them all in SSDs.
I've looked into caching solutions, but the only option I've found is basically something like bcache or ZFS's L2ARC, both of which require a dedicated drive, are not available everywhere, and are complex to implement.

I've tried having a "working" folder in the SSD and then moving the RAWs as I finish working with them, but that requires extra work and is prone to failure. I want to be able to just store everything in a large device, so I can easily backup without worrying if I missed something because it's in my "working" folder.

**Describe the solution you'd like**
A way to specify a path for Darktable to store a read cache for RAW files, which would be assumed is backed by a faster device. The idea here is to avoid the complexity/hassle/unavailability of the lower level solutions and be able to just throw in a faster device which doesn't have to be dedicated to just being a cache for faster disk access.

A nice to have would be the capability to mark a group of pictures for caching, for when I know I'm about to work with a set of files and want to have them cached as early as possible.

**Alternatives**
As I mentioned, low level solutions like [bcache](https://en.wikipedia.org/wiki/Bcache) or [ZFS L2ARC](http://www.brendangregg.com/blog/2008-07-22/zfs-l2arc.html)

**Additional context**

**Comment by johnny-bit** [comment]
wouldn't "local copy" feature work for you?

**Comment by asdkant** [comment]
@johnny-bit that covers my use case perfectly, thanks!
