### ISSUE TITLE
GUI slider units

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#8980]
GUI numbers should have an unit whenever possible. It makes their purpose clearer. 

The masks GUI lacks units in:
* details threshold : goes from -1 to +1, the suitable unit should be % (with a ×100 factor),
* feathering radius : it seems that the values is in px (to be confirmed),
* mask blur : it should be renamed "blurring radius" for consistency, and the unit seems to be px (or maybe % of the image diagonal length, to be confirmed),
* mask opacities and contrast should be in %.

Same in retouch module, for the blurring parameters, radius should be in px and opacity in %.

**Comment by jenshannoschwalm** [comment]
Generally i agree here. But for details threshold there is no unit, it's just a "something" so yopu said %. But % of what?

**Comment by Mark-64** [comment]
#8913 falls in the same category, IMO

**Comment by aurelienpierre** [comment]
> #8913 falls in the same category, IMO

It's a tad more work because there are angle conversions involved. Here, it's only display.

> Generally i agree here. But for details threshold there is no unit, it's just a "something" so yopu said %. But % of what?

So what does "1" represent ? Isn't it a ratio of something ? It is is a gradient threshold, then it's a rate of variation.

**Comment by jenshannoschwalm** [comment]
> So what does "1" represent

1.0f of "something" we defined as the endpoint of a used variable. It's not a joke or me being reluctant, we can go as you like but i really don't know what would be the best indicator. Does a rate of variation have a unit :-?

**Comment by aurelienpierre** [comment]
> Does a rate of variation have a unit :-?

yes, the unit of the numerator over the unit of the denominator (like m/s for speed, m/s² for acceleration, etc.). So in that case, that would be "intensity" / px I guess. 

I generally like % better because it gives more workable numbers (1% is easier to remember and to read than 0.001).

**Comment by jenshannoschwalm** [comment]
> (1% is easier to remember and to read than 0.01

Yeah.

**Comment by aurelienpierre** [comment]
Shut up bot.

**Comment by johnny-bit** [comment]
Shut up bot.

**Comment by johnny-bit** [comment]
OK, my stupid self sees no other explaination for "feathering radius" rather than straight up px, same for mask blur... so let's go with that :)
