### ISSUE TITLE
Some icons incorrectly rendered on macOS

### ISSUE THREAD

**Issue by lhietal** [darktable-org/darktable#8981]
**Describe the bug/issue**
Uncommon characters that are used to render icons for some parts of the UI seem to be somewhat OS dependent. I'm using macOS and some icons aren't displaying as intended.

**To Reproduce**
Following places in the UI are not rendering correctly on my system.
- Import dialog, "already imported" icon
https://github.com/darktable-org/darktable/blob/1d8e11a0171c00c220e9b03a6482152db5bc41ea/src/libs/import.c#L674
- Darkroom iop header tooltip
https://github.com/darktable-org/darktable/blob/1d8e11a0171c00c220e9b03a6482152db5bc41ea/src/develop/imageop.c#L3113-L3116
- Crop & rotate, symmetry lock icon
https://github.com/darktable-org/darktable/blob/1d8e11a0171c00c220e9b03a6482152db5bc41ea/src/iop/clipping.c#L2429

**Expected behavior**
Icons should be rendered as similarly as possible on all supported OSs.

**Screenshots**
<img width="68" alt="screenshot" src="https://user-images.githubusercontent.com/62325790/118393160-4b2ae380-b646-11eb-8c3e-bb3085871de8.png"> Import dialog
<img width="364" alt="screenshot2" src="https://user-images.githubusercontent.com/62325790/118395259-fa20ec80-b651-11eb-907b-acd27a8ccc01.png"> Iop tooltip
<img width="52" alt="screenshot3" src="https://user-images.githubusercontent.com/62325790/118395265-ff7e3700-b651-11eb-9ce4-aada4747fe39.png"> Lock icon

**Platform**
* darktable version : 3.5.0+2228~gabfd8d42e
* OS                        : macOS 10.14.6
* GTK+                    : 3.24.29

**Additional context**
Could this be influenced by what fonts are installed?

**Comment by johnny-bit** [comment]
The "icons" are actual UTF-defined characters and should theoretically work in any font... but generally Roboto font should cover it all.

**Comment by parafin** [comment]
> The "icons" are actual UTF-defined characters and should theoretically work in any font... but generally Roboto font should cover it all.

Not any obviously, it has to have these characters;)

**Comment by lhietal** [comment]
This seems to be font related. I can get "icons" to display correctly if I change the `font-family` in custom css. On my system there are no fonts installed by default that includes all these characters. Roboto doesn't have them either. Could it be that other OSs have some fallback font that handles these unusual characters?

**Comment by parafin** [comment]
Definitely. Roboto doesn't have such glyphs: https://fonts.google.com/specimen/Roboto#glyphs
IMHO using these icons is a bad idea, it already required some custom workaround for Windows. But on my Mac I think these icons are displayed correctly and I didn't install any additional fonts knowingly.

**Comment by johnny-bit** [comment]
The alternative would be custom tooltip with cairo-drawn icons.

**Comment by lhietal** [comment]
Cannot reproduce with macOS 12.6.8 and darktable 4.4.2.

**Comment by victoryforce** [comment]
Reproducible with macOS 11.7.9 and darktable 4.4.2. Presumably macOS 12 has fixed this issue?

**Comment by victoryforce** [comment]
@zisoft @Nilvus 
Could I kindly ask you to take the optimal solution and solve this before 4.6 release?

> Import dialog is not fixed in macOS 12.

I can't even test this or the solution suggested above as my very old Air won't update macOS past 11.x.

**Comment by zisoft** [comment]
Wow, never noticed this before!

Reproducible on macOS 14.1.2:
<img width="444" alt="Bildschirmfoto 2023-12-04 um 18 12 43" src="https://github.com/darktable-org/darktable/assets/4083281/ba10b4ce-8abe-47cf-990d-26e27f58e208">

and the proposed css fix from @lhietal solves it:

<img width="485" alt="Bildschirmfoto 2023-12-04 um 18 15 25" src="https://github.com/darktable-org/darktable/assets/4083281/1b80511b-2ca6-4c17-8428-fde1905e1342">

**Comment by Nilvus** [comment]
@victoryforce: I don't use Mac so I can't test.

@zisoft: such css fix seems safe to me. So as you can and have tested it, could you propose that fix as a PR. Thanks.
