### ISSUE TITLE
DT 3.4.1.1 win10 - crash when resetting orientation via dbl click

### ISSUE THREAD

**Issue by plemon** [darktable-org/darktable#8988]
Env:
Windows 10.0.19042
Nvidia Geforce GTX 1070 Ti
DT version 3.4.1.1

Steps to reproduce:

- Open any img in Darkroom
- Expand the Orientation module(the same behavior regardless if on or off)
- Double click to reset where tooltip is
- Provokes an exception Prompt with log dump path

Attached log dump file and screen shot of where to click to get the ex.

[darktable_bt_2H9R30.txt](https://github.com/darktable-org/darktable/files/6495726/darktable_bt_2H9R30.txt)

![2021-05-17_19h19_58](https://user-images.githubusercontent.com/12614383/118531445-228a1300-b746-11eb-977e-c778afd65491.png)

**Comment by victoryforce** [comment]
Fixed by #9178

**Comment by johnny-bit** [comment]
Thank you @victoryforce!
