### ISSUE TITLE
Nightlies (Windows) crash on import

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#8994]
Great to have Windows nightly packages available again, but they crash for me as soon as I try to import something.

Log attached when running `darktable -d all --disable-opencl` with a clean configuration folder.

Note also the `lut3d.dll` [module missing message](https://github.com/darktable-org/darktable/runs/2605809937?check_suite_focus=true#step:5:45) in the `darktable-cli` CI test run output (also confirmed in my GUI run), but that doesn't seem to be the cause of this crash. (The file is present on disk btw.)

[darktable-log.zip](https://github.com/darktable-org/darktable/files/6500323/darktable-log.zip)

**Comment by johnny-bit** [comment]
The nightly builds started to work because it seems like llvm on windows started to produce runnable executables. I was pondering whether to switch build to GCC... Now I wonder even more about it TBH. The log does not indicate any problem I can spot...

**Comment by parafin** [comment]
same lut3d error is present in attached log too. It most likely means that liblut3d.dll depends on some missing dll (gmic maybe?). I think there is a Windows application that can show information about DLL, dependency walker it's called or something like that.

**Comment by kmilos** [comment]
Good catch @parafin - indeed `libgmic.dll` tries to load non-existent `libopencv_core440.dll` and `libopencv_videoio440.dll`, but we ship `libopencv_core451.dll` and `libopencv_videoio451.dll` in the Windows package, so something is a bit weird re linking in the build process or msys packaging.

Again, I don't think this is the cause of the crash, as this lut3d message seems to happen earlier and `darktable-cli` task seems to produce the output just fine...

**Comment by parafin** [comment]
Probably different issues indeed, but better to solve the apparent one to be sure.

**Comment by kmilos** [comment]
The `lut3d.dll` load error is now gone after mingw-w64-gmic repackaging, but the crash on initial import is still there with the nightly c90260a9 package...

**Comment by johnny-bit** [comment]
Can you generate log from crash?

**Comment by kmilos** [comment]
@johnny-bit There's no significant difference or any new hints compared to the log already attatched above...

**Comment by johnny-bit** [comment]
but that log is `-d all`, not a backtrace or crash support... I wonder if making a matrix for CI job that would build on GCC and LLVM and then compare results would make a dent in figuring this out.

**Comment by kmilos** [comment]
Ah, sorry, currently don't have the setup to launch in a debugger...

**Comment by hoewweken** [comment]
As a side hnote,
 i worked around an issue for my case, 
 a crash on generating a hdr of "selected images".

i deleted (renamed) the darktable folder in
c:\users<username>\AppData\Local\
and tried again. Now the hdr image was created.

I don't know if this is a workaround for this bug, though.
But this workaround implies theres is *something* in the local settings that triggers crashes :-/

**Comment by johnny-bit** [comment]
I need to work on this... Ideally I'd love to FINALLY have windows+linux+mac nightlies... That could be a bit problematick :)

**Comment by johnny-bit** [comment]
Please test build from this run: https://github.com/johnny-bit/darktable/actions/runs/1120564743

PR #9795 fixes this and should generally work well :)

**Comment by kmilos** [comment]
This one segfaults immediately because of the known libpango issue :(

**Comment by johnny-bit** [comment]
:shipit: 

You can try with workarounds mentioned https://github.com/darktable-org/darktable/issues/9793#issuecomment-896789437 and https://github.com/darktable-org/darktable/issues/9793#issuecomment-896915586 it should start nicely.

When testing I deliberately set my theme to `darktable-elegant-light` as to avoid the pango issue. Fortunately the pango issue is fixed in pango repo and release 1.48.8 is comming :)
