### ISSUE TITLE
regression: crash entering darkroom, c3a2a9e4a is failure-inducing commit

### ISSUE THREAD

**Issue by mandree** [darktable-org/darktable#8998]
**Describe the bug/issue**
double clicking an image from the normal lighttable view leads to an instant crash, backtrace attached [darktable_bt_WVHI30.txt](https://github.com/darktable-org/darktable/files/6504594/darktable_bt_WVHI30.txt) and bisect below

**To Reproduce**
1. open darktable without file path, to open the lighttable view
2. double click a raw image, to enter darkroom view
3. observe darktable crash and dump a backtrace

**Expected behavior**
enter darktable view for further processing

**Which commit introduced the error**
@AlicVB and @TurboGit  can you take a look? git bisect flags your recent culling commit
```
git bisect start
# bad: [c3a2a9e4a9023af30d63ea36c7f09be6b90796f8] culling : fix oddities when enter/quit dynamic mode
git bisect bad c3a2a9e4a9023af30d63ea36c7f09be6b90796f8
# good: [cf47c7e45f48bb120d0c593e5d15d12b63edb440] Fix fuji dual demosaicing
git bisect good cf47c7e45f48bb120d0c593e5d15d12b63edb440
# good: [b41956aca4756a85b8d78475f11514b61276be68] CI : add LLVM 11
git bisect good b41956aca4756a85b8d78475f11514b61276be68
# good: [48ced170830d842e9fc7b98b8a110c4e5657fede] histogram: slightly increase maximum height
git bisect good 48ced170830d842e9fc7b98b8a110c4e5657fede
# good: [1d7dd25031e31cbe665f9ec76f2431bad8b772c4] update README
git bisect good 1d7dd25031e31cbe665f9ec76f2431bad8b772c4
# good: [0b3bb466cce41e9911d1297c6686d8568c9e149a] filmic: add negative clipping at critical places
git bisect good 0b3bb466cce41e9911d1297c6686d8568c9e149a
# good: [74e939cf24e9fb5767f813e3dcfaf483f6db2290] Update darktable.pot for translators.
git bisect good 74e939cf24e9fb5767f813e3dcfaf483f6db2290
# good: [36a971f94f1df7670bce87446ba01c7c376a79d4] Update de.po
git bisect good 36a971f94f1df7670bce87446ba01c7c376a79d4
# good: [d48e51476a5c82e26f954406721e278af9aa7979] Update French translation.
git bisect good d48e51476a5c82e26f954406721e278af9aa7979
# first bad commit: [c3a2a9e4a9023af30d63ea36c7f09be6b90796f8] culling : fix oddities when enter/quit dynamic mode
```

**Platform**

* darktable version : 3.5.0 whatever Git c3a2a9e4a
* OS                : Linux kernel 5.11.20-200.fc33.x86_64
* Linux - Distro    : Fedora 33
* Memory            :  32 GB
* Graphics card     :  nvidia GeForce GTX 1060-6GB, opencl enabled
* Graphics driver   : nvidia proprietary 465.27
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 
* Desktop           : GNOME
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by TurboGit** [comment]
I cannot reproduce ! Maybe I do not understand well:

> open darktable without file path, to open the lighttable view

Can you clarify this ? TIA.

**Comment by AlicVB** [comment]
I can't reproduce either, and I don't get how the commit you point can be the issue (but I may be false)
Reading your backtrace, it seems that you enter darkroom with an invalid image. I've done a PR to fix this exact problem, but I fear we may have others...
Can you do the following : 
- test PR #9001 and say if it solve your issue
- if that solve the issue, do you get a valid image in darkroom ???
- Are you sure there's no other steps involved ? like starting with specific lighttable mode, special selection or whatever...
- Do you experience the same problem if you enter darkroom by pressing 'd' shortcut ? by using the top button ?

Thanks in advance

**Comment by mandree** [comment]
OK so my description should have been 
- "run darktable from command line. Do not specify image file name or directory name." 
- from the file manager view of the lighttable (not culling), double click.

It was really just "launch darktable, double click, see crash". No special modes. Any settings file I need to preserve next time?

For reasons beyond me, I cannot reproduce this with 15604dff7ee6ebff14cf946d428905776f15a16c or c3a2a9e4a9023af30d63ea36c7f09be6b90796f8. 
I had built d48e51476a5c82e26f954406721e278af9aa7979 and used that to edit images after initial import, so perhaps this bug was limited to unprocessed images?

The image looks reasonable in lighttable and darkroom view and also the 8-bit sRGB JPG after export.

I cannot answer the questions about pressing "d" any more either, but will try to remember next time something similar happens.

Thank you.

**Comment by mandree** [comment]
One more question, what do you mean with "invalid image"? 

It is not currupt if that's what you mean. 

But I had accidentally used "copy & import" (figured that ARW and JPG don't group because of sequential numbering on the copy&import), then marked all the images, erased them, manually rm -rf'd Pictures/Darktable, and then re-imported the same images with "add to library". Does that make it any more understandable?

**Comment by ptilopteri** [comment]
I have opened release-3.5.0-2292-gc90260a97 from command line
with no image cited

so now there is no image preview available in lighttable view
nor in the filestrip and clicking anywhere on the filestrip or the blank 
lighttable area does not crash.


openSUSE Tumbleweed 20210517
