### ISSUE TITLE
(minor) thumbnails misaligned by 1 pixel in filmstrip depending on aspect ratio

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9003]
**Describe the bug/issue**

This is really nitpicking here, so I would understand if this issue was closed with a "won't do". 

Anyway, thumbnail pictures are not perfectly centered in their 'slot' in the filmstrip. The left border is 1 pixel too wide (or the right one is 1 pixel too thin, depending on your point of view). Since my pictures have a 3:2 aspect ratio and vertical/square pictures are not affected, I assume that this occurs because the pixel width of the 'box' is always the same and therefore thumbnails with an even or uneven pixel number can not be centered properly.

A fix would probably require to crop a single pixel row from the thumbnail to make the count always even/uneven or by making the width of the box one pixel wider/smaller depending on the shape of the thumbnail. 

To reproduce, use this CSS snippet to better visualize the area around a picture. My screen has a 1680/1080 resolution - other resolutions might require different values.
```
#thumb_main:active #thumb_back
{
  border: 4px solid shade(@thumbnail_selected_bg_color, 1.25);
}
```
![image](https://user-images.githubusercontent.com/2805109/118855844-8e02ea80-b8d6-11eb-9e1e-d9d2b210a973.png)
As you can see, the thumbnail overlaps on the right side but not on the left side.

![image](https://user-images.githubusercontent.com/2805109/118856396-3153ff80-b8d7-11eb-8d80-3b5e1eefe21c.png)
Without the white border it is really hard to spot, but the splitting line is not perfectly centered.

Like I said, it is nitpicking, but once you see it, you cannot unsee it ;)

Manjaro Linux - 3.5.0+1967~g4024d7d73

**Comment by TurboGit** [comment]
@Nilvus : I have assigned this to you, there is no urgency and we can miss the 3.6 target, no big deal.

**Comment by Nilvus** [comment]
I'm seeing that actually. Not so easy but I seems related to the fact we don't affect hover and active state on exact part of the image. Borders are set to thumb_back as hover and active are set to parent one, so thumb_main. That explain this difference (really hard to show on some states and depending on thumbnail size.

I've began to rewrite CSS (some lines to update and then test I don't break anything) but should be done this week, maybe with some other things.

**Comment by Nilvus** [comment]
And thanks @Solarer or pointing that one. Really minor but point a bad CSS code there!

**Comment by Nilvus** [comment]
@AlicVB: I assign this to you since @xfh comment here: https://github.com/darktable-org/darktable/pull/9074#issuecomment-850599966

**Comment by xfh** [comment]
@AlicVB, I just made an attempt with roundf in view.c, but the result is not good at all. It can yield to black border artifacts, when the actual image is smaller than the cairo surface :-(

![image](https://user-images.githubusercontent.com/9366771/120035723-51826d80-bfff-11eb-9edf-82293ce98bf1.png)
