### ISSUE TITLE
Segfault when duplicating image

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#9008]
**Describe the bug/issue**
darktable crashes with a segfault when duplicating an image.  The image is duplicated but it appears that the segfault occurs when the image information is being updated.

The back trace shows

`in _lib_imageinfo_update_message (instance=<optimized out>, self=<optimized out>) at /home/bill/src/darktable/darktable/src/libs/tools/image_infos.c:113
`
**To Reproduce**
1. Open an image in darkroom view
2. Open duplicate manager
3. Click the original button
4. darktable crashes

**Expected behavior**
duplicated image should be displayed

**Which commit introduced the error**
9941551e3bb620efba73c86ec446cf38df05e091

@AlicVB could you look at this?  Thanks

**Platform**

* darktable version : latest git
* OS                :Linux
* Linux - Distro    : Ubuntu 18.04
* Memory            : 16G
* Graphics card     : Nvidia 970
* Graphics driver   : 460.73
* OpenCL installed  : yes
* OpenCL activated  : yes

**Additional context**
Duplicating an image in lighttable mode works fine.

**Comment by TurboGit** [comment]
Probably fixed by 28997dc2f350149b11ee4c53e108b47231079801.

**Comment by wpferguson** [comment]
@TurboGit works for me, thanks
