### ISSUE TITLE
capture mode broken

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#9013]
**Introduction**

Capture mode unusable.

**Describe the bug/issue**

Crash enterring capture mode with new capture session (empty) or clicking on capture.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'capture"
2. Click on 'capture"
3. See crash

**Expected behavior**

No crash.

**Platform**

* darktable version : current master
* OS                : Linux
* 
**Additional context**

Bisect to:

```
f343c997606d156ffa31722f3f88fcf1de3301bf is the first bad commit
commit f343c997606d156ffa31722f3f88fcf1de3301bf
Author: Dan Torop <dant@pnym.net>
Date:   Fri Apr 30 23:42:05 2021 -0400

    histogram: make process know about input & output colorspace
    
    Don't assume output colorspace is histogram profile -- in some cases
    for tether this will not be so.
    
    This is to clear the way for doing colorspace conversion during
    histogram process, saving a temp buffer and maybe time.
    
    Also, use dt_iop_order_iccprofile_info_t rather than type & filename
    to represent profiles.

 src/develop/pixelpipe_hb.c |  9 +++++++--
 src/libs/histogram.c       | 41 ++++++++++++++---------------------------
 src/libs/lib.h             |  3 ++-
 src/views/tethering.c      | 25 +++++++++++--------------
 4 files changed, 34 insertions(+), 44 deletions(-)
```

**Comment by dtorop** [comment]
Drat! I'll look at it. I may need to borrow a tether-able camera to test, if so I'll see if I can get ahold of one tomorrow.

**Comment by dtorop** [comment]
Is there a backtrace for the crash? Trying to guess what's wrong, without a camera...

Regardless, the fix above should be just fine. Or probably this is slightly more correct (assuming no crash):

```diff
modified   src/views/tethering.c
@@ -394,10 +394,10 @@ static void _expose_tethered_mode(dt_view_t *self, cairo_t *cr, int32_t width, i
                                      FALSE, FALSE, FALSE, FALSE, NULL, FALSE, FALSE, icc_type, icc_filename,
                                      DT_INTENT_PERCEPTUAL, NULL, NULL, 1, 1, NULL))
     {
-      const dt_iop_order_iccprofile_info_t *const histogram_profile =
-        dt_ioppr_get_histogram_profile_info(darktable.develop);
+      const dt_iop_order_iccprofile_info_t *const prof =
+        dt_ioppr_add_profile_info_to_list(darktable.develop, icc_type, icc_filename, DT_INTENT_RELATIVE_COLORIMETRIC);
       darktable.lib->proxy.histogram.process(darktable.lib->proxy.histogram.module, dat.buf, dat.head.width,
-                                             dat.head.height, histogram_profile, histogram_profile);
+                                             dat.head.height, prof, prof);
       dt_control_queue_redraw_widget(darktable.lib->proxy.histogram.module->widget);
       free(dat.buf);
     }
```

Either will effectively disable the profile conversion in `dt_lib_histogram_process()`. It's possible there will still be a crash in the vectorscope with this code -- I'll have to check once I have a camera.

The sad thing is that f343c997606d156ffa31722f3f88fcf1de3301bf was to clear the way for doing fast profile conversion work without an intermediate buffer (955ee4b3e7136454ffc555539aa8cbfd134f1a20). But that's pretty much walked by 3dbc240ea80d2d958fcdf318a4a195c0eea54b7b, as this failed for CLUT profiles. Hence the above diff or using sRGB is just fine, or even backing out f343c997606d156ffa31722f3f88fcf1de3301bf should be OK. If scope processing can happen before the colorout iop (using data in working profile), all this code will become useful, though.

More when I have a camera here to test this.

**Comment by TurboGit** [comment]
@dtorop : Indeed, still crash with the vectorscope but the issue is fixed for other scopes.

To answer the question, the line crashing was the call to `dt_ioppr_get_histogram_profile_info(darktable.develop); `(2nd red line above).

**Comment by aurelienpierre** [comment]
It's weird, I have used the tethering view with no issue in the past weeks.

**Comment by TurboGit** [comment]
It's a recent regression introduce on April 20th. Does that matches your timeframe ?

**Comment by dtorop** [comment]
It's also possible that it depends on profile settings -- or whether the display profile is a CLUT vs matrix. I should be able to diagnose better soon!

**Comment by dtorop** [comment]
Got a camera. I can replicate this when the histogram profile is "work profile" or "export profile". There's no crash when the histogram profile is one of the dt internal profiles (e.g. sRGB or Rec.2020).

I'm also seeing some other weirdness related to tether. A crash when using AI servo, the initial image photographed into a film roll not showing up (I think I saw that as well last summer), and flakiness with the camera connection (could be a flaky camera to blame). I'll try to document (and maybe fix) as much as I can.
