### ISSUE TITLE
Color Balance RGB tooltips are repeated

### ISSUE THREAD

**Issue by pitbuster** [darktable-org/darktable#9016]
In the **masks** tab, the tooltip for _contrast gray frulcrum_ is the same as the one for _white fulcrum_.

**Comment by TurboGit** [comment]
Good catch, now fixed. Thanks.

**Comment by pitbuster** [comment]
Thanks @TurboGit, but I am not sure "peak gray" makes sense 😔

**Comment by TurboGit** [comment]
> Thanks @TurboGit, but I am not sure that "peak gray" makes sense pensive

Hum... embarrassing indeed :) @aurelienpierre : can you have a look at this duplicate tooltip ? TIA.
