### ISSUE TITLE
Black squares / rectangles while editing an image

### ISSUE THREAD

**Issue by AndDiSa** [darktable-org/darktable#9022]
Describe the bug/issue

When editing images there are sometimes black squares / rectangles distributed all over the image, especially when enabling the contrast equalizer module

To Reproduce
Edit an image and enable e.g. the contrast equalizer module

Expected behavior:

It should be able to edit the images without issues

Platform

    darktable version : 3.5.0+2324~gd885276ed
    OS : 5.4.0-73-generic
    Linux - Distro : Ubuntu 20.04
    Memory : 32 GB
    Graphics card : Nvidia Quadro M1200 
    Graphics driver : nvidia-460 5.4.0-73.82+1
    OpenCL installed : yes
    OpenCL activated : yes
    gcc :  9.3.0

Additional context:

Looks to me as if commit 13832bdaaf5632fc936e2b5c40fe212bba3d02c1 is causing the issue as reverting this commit fixes the wrong behaviour of darktable.

Extract from the logs:
...
[dev_pixelpipe] module `contrast equalizer' outputs NaNs! [full]
[dev_pixelpipe] module `contrast equalizer' min: (2,276892; -29,403776; -36,262226) max: (151,329422; 22,420048; 33,385468) [full]
...
[dev_pixelpipe] module `sharpen' outputs NaNs! [full]
[dev_pixelpipe] module `sharpen' min: (-3,664654; -29,403776; -36,262226) max: (151,329422; 22,420048; 33,385468) [full]
...

**Comment by Nilvus** [comment]
@aurelienpierre: should be for you

**Comment by johnny-bit** [comment]
@AndDiSa - can you share a `.xmp` file which produces such output (preferably along with sample image - can be one from say raw.pixls.us or any playraw from discuss.pixls.us)? that way it'll be easier to debug :)

**Comment by AndDiSa** [comment]
Yes, for sure :-)
I used the image taken from https://discuss.pixls.us/t/sunset-on-brusvikken-darktable-filmic-vs-sigmoid/25058

and this is an .xmp which is causing the issue:
[DSCF9668_02.RAF.xmp.txt](https://github.com/darktable-org/darktable/files/6523350/DSCF9668_02.RAF.xmp.txt)

the issue starts as soon as contrast equalizer is added to the previous existing module stack
and the screen looks like this:
![Bildschirmfoto zu 2021-05-21 16-50-42](https://user-images.githubusercontent.com/550244/119157162-2f17af80-ba55-11eb-8b35-9004f8b4dcf7.png)

**Comment by TurboGit** [comment]
@AndDiSa : I'll let @aurelienpierre have the final word, but this happens only if the `clip negative RGB from gamut` option is not ticked in your  CorrectGreens instance of **color calibrarion** module.

**Comment by AndDiSa** [comment]
Ah, ... I didn't imagine that this might be the reason, but good to know. I'll check that immediately.

**Comment by kofa73** [comment]
Yes, clipping negative RGB avoids the issue, but if I turn off OpenCL, the problem also goes away. It seems the OpenCL implementation lacks some sanitising / does different arithmetics?

**Comment by aurelienpierre** [comment]
OpenCL has different compiling options that essentially remove many NaN checks for the sake of speed. The C/CPU and OpenCL/GPU will process NaN differently, unless you build with `Release`. It's possible that some mistakes have been made in translation, but unlikely. Although I proof-read the code myself, and it's almost impossible to spot errors in your own code, unless you have completely forgotten it.

**Comment by AndDiSa** [comment]
Looks to me as if the PR from @flannelhead is fixing the issue. At least with my first tests I was no longer able to reproduce the issue.

**Comment by flannelhead** [comment]
Thanks for confirming! Yes, I was able to reproduce the same issue with the combination of color calibration followed by contrast equalizer, and the PR https://github.com/darktable-org/darktable/pull/9119 fixed it for me too.
