### ISSUE TITLE
OSX building with exiv2 0.72.4 RC3 - no ISOBMFF support detected

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9024]
need help:
i built exiv2 0.72.4 RC2 with ISOBMFF option (the resulting exiv2 binary can handle cr3 files) but darktable (current master) doesnt recognize ISOBMFF support during cmake configuring the enviroment:

```
-- Found Exiv2: /usr/local/lib/libexiv2.dylib (Required is at least version "0.24")
-- Looking for EXV_ENABLE_BMFF
-- Looking for EXV_ENABLE_BMFF - not found
-- Exiv2 >= 0.27.4 found, but was not compiled with ISOBMFF support (CR3, AVIF, HEIF)
```
is there something i need to do with my build environement (OSX following https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt but with disabled macports exiv2 0.73)

build environment is set using:
```
cmake .. \
 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
 -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
 -DCMAKE_OBJCXX_FLAGS=-stdlib=libc++ \
 -DOpenMP_C_INCLUDE_DIR=/opt/local/include/libomp \
 -DOpenMP_CXX_INCLUDE_DIR=/opt/local/include/libomp \
 -DCMAKE_LIBRARY_PATH=/opt/local/lib/libomp \
 -DBINARY_PACKAGE_BUILD=ON \
 -DRAWSPEED_ENABLE_LTO=ON \
 -DBUILD_CURVE_TOOLS=ON \
 -DBUILD_NOISE_TOOLS=ON \
 -DCMAKE_BUILD_TYPE=Release
```

**Comment by MStraeten** [comment]
/usr/local/include/exiv2/exiv2.hpp
includes: exiv2/config.h
includes: exiv2/exv_conf.h
and that contains:
```
// Define if you want BMFF support.
#define EXV_ENABLE_BMFF
```

**Comment by MStraeten** [comment]
it seems ` check_cxx_symbol_exists(EXV_ENABLE_BMFF "exiv2/exiv2.hpp" HAVE_EXV_ENABLE_BMFF)
` fails since even replacing exiv2/exiv2.hpp by the whole path for exv_conf.h doenst result in a proper detection

**Comment by MStraeten** [comment]
issue keeps present with exiv2 0.27.4 

affects ./src/CMakeLists.txt
my workaorund on osx : add `set(HAVE_EXV_ENABLE_BMFF 1)` after line 404

**Comment by johnny-bit** [comment]
Does it work on linux?

@cytrinox - can you check what can be changed here?

**Comment by johnny-bit** [comment]
I see that the cmake docs make mention of the symbol not being reliable and instead try using `check_cxx_source_compiles`

**Comment by MStraeten** [comment]
msys/mingw on windows detects EXV_ENABLE_BMFF properly so it seems to be osx specific

**Comment by parafin** [comment]
@MStraeten, does this commit solve the issue: 2bc5b6a66c8e0be4b4cee6831447f3e94aa3c8e9 ?

**Comment by MStraeten** [comment]
yes, thats fine, so i'll close the issue
