### ISSUE TITLE
filmstrip doesn't show first tethered image captured

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#9025]
**Describe the bug/issue**

The first picture made in tether mode doesn't appear in an empty filmstrip. Subsequent images do.

**To Reproduce**

1. start with a clean install
2. connect camera
3. in lighttable, expand `import` on left panel
4. wait for camera entry to appear
5. click `tethered shoot` button
6. expand `camera settings` on right panel
7. click `capture image(s)` button
8. camera will take a picture, after a pause it will display it in center view (top panel reads `1 image of 1 (#1) in current collection is selected`)
9. **filmstrip in bottom panel remains empty**
10. click `capture image(s)` button again
11. camera will take a picture, after a pause it will display it in center view (top panel reads `1 image of 2 (#2) in current collection is selected`)
12. now there are two pictures in the filmstrip

_-or-_

10. switch to darkroom view
11. switch back to tether view
12. now there are two pictures in the filmstrip

This bug can also be reproduced even w/out a clean install

1. once in tether view with a connected camera, open `session` on right panel
2. enter a `jobcode` which doesn't correspond to an extant film roll
3. click `create`
4. in `camera settings` click `capture image(s)`
5. **the first image taken will not appear in the filmstrip**
6. on the second image taken, two images appear in the filmstrip

**Expected behavior**

The first image taken should appear in the filmstrip.

**Platform**

* darktable version : 3.5.0+2300~g374b971eb
* OS                : Linux 5.10.28
* Linux - Distro    : Debian testing
* Memory            : 32GB
* Graphics card     : GP104GLM [Quadro P4000 Mobile]
* Graphics driver   : nvidia-driver  460.73.01
* OpenCL installed  : yes
* OpenCL activated  : no
* Xorg              : 7.7
* Desktop           : Gnome
* GTK+              : 3.24.24
* gcc               : clang 

**Additional context**
I first saw this bug last summer, but am only documenting this now. One guess is that it's a corner case having to do with the extensive reworking of filmstrip/filemanager/culling & lighttable view in general.

**Comment by TurboGit** [comment]
I have seen that also. Not sure when it happends exactly but I would say after rework of filmstrip/filemanager as you.

**Comment by TurboGit** [comment]
Now fixed.
