### ISSUE TITLE
issues with constrained cropping

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9034]
In both the "crop" and "crop & rotate" modules, it is possible to constrain resize actions to the current aspect ratio by holding shift while dragging on the resize handles.

There are two main issues with this:

- when used with a preset aspect ratio, the crop can move as well as resizing when the edges of the image are reached. Often when the extreme is reached, the size starts to reduce again. These sorts of issues seem to happen when the initial crop (before resize) is off-center.
- when used with a freehand aspect ratio it is possible to resize the crop beyond the edges of the current image area

darktable 3.5.0+2292~gc90260a97 on ArchLinux

**Comment by elstoc** [comment]
@AlicVB I think I recall you saying that you understand these modules now :)

**Comment by AlicVB** [comment]
crop module yes, crop&rotate, a little bit, but touching anything there is ... risky !
I'll have a look for the crop module, and if not too complex port it back to c&r ;)

**Comment by AlicVB** [comment]
good news : PR #9048 should fix it for both modules (I think it's save enough to not provoke side effects in c&r)

For the record, there was an even a bigger issue here as in fact the ratio was not kept at all : the code was in fact *adding* the same value to both height and width... (I've fix that too)
