### ISSUE TITLE
tether: center view redrawn repeatedly as mouse moves over it

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#9036]
**Describe the bug/issue**

In tether view, every time a mouse move event occurs, the center view is redrawn. This can max out CPU and could potentially make darktable (or other software running) less responsive.

Redrawing the center view also triggers redrawing the histogram. When tether is showing an image from the current film roll, this calls `dt_imageio_export_with_flags()` which runs the export pixelpipe, which can easily use 1/2 second of wall clock time (and much more CPU time). None of this should be necessary.

**To Reproduce**
1. Start darktable with "-d perf"
2. Go to tether view
3. Select an image from the filmstrip in the bottom panel (assuming you're in a collection with extant images) or make a photograph via `camera settings` -> `capture image(s)`
4. Move mouse back and forth over the center view
5. Note all the [dev], [export], [dev_pixelpipe], [dev_process_export], and [histogram] messages. It's also possible to observe all CPUs at 100% via a tool such as htop.

**Expected behavior**
All this center view processing should only happen on image change. There should be minimal/no spike in CPU usage when moving the mouse over the center view.

**Which commit introduced the error**
Refresh on mouse move behavior is longstanding tether view behavior. See 85edb8c607f888ae7e598732bf6dfd2886a5184f.

Calculating histogram using export pixelpipe (7fa93a1f2a64a399ecd293053f0931539f75e2db) greatly increased the amount of processing required per mouse move.

**Platform**

* darktable version : 3.5.0+2330~g4fb67a1a1
* OS : Linux 5.10.28
* Linux - Distro : Debian testing
* Memory : 32GB
* Graphics card : GP104GLM [Quadro P4000 Mobile]
* Graphics driver : nvidia-driver 460.73.01
* OpenCL installed : yes
* OpenCL activated : no
* Xorg : 7.7
* Desktop : Gnome
* GTK+ : 3.24.24
* gcc : clang

**Additional context**

This is less of a problem in live view mode, which doesn't run the export pipeline to generate the histogram.

The good news is that when the user is moving the mouse over the center view, there isn't that much opportunity for UI interaction, hence the wasted CPU usage isn't that noticeable.

It's possible the fix is as simple as not redrawing the center view on each `mouse_moved()`:

```diff
modified   src/views/tethering.c
@@ -597,7 +597,6 @@ void mouse_moved(dt_view_t *self, double x, double y, double pressure, int which
     snprintf(str, sizeof(str), "%u,%u", cam->live_view_zoom_x, cam->live_view_zoom_y);
     dt_camctl_camera_set_property_string(darktable.camctl, NULL, "eoszoomposition", str);
   }
-  dt_control_queue_redraw_center();
 }
 
 int button_pressed(dt_view_t *self, double x, double y, double pressure, int which, int type, uint32_t state)
```

But there may be other wrinkles. Not least the `gui_post_expose()` calls which create overlays from libs/live_view.c and libs/camera.c. It might be cleaner if there were various widgets in center view, rather than it being one big widget which is drawn into by various bits of code.

Here is an example of perf log output after each mouse move event

```
587.416578 [dev] took 0.000 secs (0.000 CPU) to load the image.
587.518710 [export] creating pixelpipe took 0.096 secs (0.419 CPU)
587.530005 [dev_pixelpipe] took 0.011 secs (0.035 CPU) initing base buffer [export]
587.541701 [dev_pixelpipe] took 0.012 secs (0.068 CPU) processed `raw black/white point' on CPU, blended on CPU [export]
587.549511 [dev_pixelpipe] took 0.008 secs (0.049 CPU) processed `white balance' on CPU, blended on CPU [export]
587.556113 [dev_pixelpipe] took 0.007 secs (0.043 CPU) processed `highlight reconstruction' on CPU, blended on CPU [export]
588.013004 [dev_pixelpipe] took 0.457 secs (3.223 CPU) processed `demosaic' on CPU, blended on CPU [export]
588.022270 [dev_pixelpipe] took 0.009 secs (0.034 CPU) processed `exposure' on CPU, blended on CPU [export]
588.023540 [dev_pixelpipe] took 0.001 secs (0.007 CPU) processed `input color profile' on CPU, blended on CPU [export]
588.024703 [dev_pixelpipe] took 0.001 secs (0.009 CPU) processed `sharpen' on CPU, blended on CPU [export]
image colorspace transform Lab-->RGB took 0.000 secs (0.003 CPU) [filmicrgb ]
588.037625 [dev_pixelpipe] took 0.013 secs (0.055 CPU) processed `filmic rgb' on CPU, blended on CPU [export]
image colorspace transform RGB-->Lab took 0.001 secs (0.004 CPU) [colorout ]
588.039548 [dev_pixelpipe] took 0.002 secs (0.011 CPU) processed `output color profile' on CPU, blended on CPU [export]
588.039560 [dev_process_export] pixel pipeline processing took 0.521 secs (3.535 CPU)
588.053312 [histogram] took 0.010 secs (0.028 CPU) final waveform
588.109236 [histogram] took 0.009 secs (0.027 CPU) scope draw
```

**Comment by jenshannoschwalm** [comment]
I have never touched a tethering camera myself and don't understand what should be done while moving the mouse but from reading the code, wouldn't the redraw only be necessary if a mouse button is pressed?

**Comment by dtorop** [comment]
> I have never touched a tethering camera myself and don't understand what should be done while moving the mouse but from reading the code, wouldn't the redraw only be necessary if a mouse button is pressed?

Yes, I think that's right. Last summer I looked this over and for some reason thought that it was a more complicated problem, but I can't figure out why now.

I just returned my borrowed tether-able camera, but will try to borrow it back and test this as a fix.
