### ISSUE TITLE
very slow star rating or using filer in lighttable

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#9042]
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Use a database with lot of collections
2. Go to 'lighttable'
3. Over and image and click on the star on the thumb
4. See error, it takes long time before the star is actually applied

**Expected behavior**

Should be just instantaneous (as before).

**Platform**

* darktable version master
* OS                : Linux

**Additional context**

See line 16,638286 where the SQL query tales 1 full second.

```
16,636658 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1058, function dt_collection_get(): prepare "SELECT id FROM main.selected_images AS s JOIN (SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/mnt/photos/Photos/2021/avril/pâques liam'))) ORDER BY filename, CASE WHEN flags & 8 = 8 THEN -1 ELSE flags & 7 END DESC, version) AS mi WHERE mi.id = s.imgid LIMIT -1, ?3"
16,637492 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:2193, function dt_collection_image_offset_with_collection(): prepare "SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/mnt/photos/Photos/2021/avril/pâques liam'))) ORDER BY filename, CASE WHEN flags & 8 = 8 THEN -1 ELSE flags & 7 END DESC, version"
16,638227 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:238, function _thumb_get_rowid(): prepare "SELECT rowid FROM memory.collected_images WHERE imgid=95735"
16,638261 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:238, function _thumb_get_rowid(): prepare "SELECT rowid FROM memory.collected_images WHERE imgid=95735"
16,638286 [sql] /home/obry/dev/builds/darktable/build/src/src/dtgtk/thumbtable.c:1923, function dt_thumbtable_full_redraw(): prepare "SELECT rowid, imgid FROM memory.collected_images WHERE rowid>=1 LIMIT 12"
16,640496 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/collect.c:1885, function list_view(): prepare "SELECT folder, film_rolls_id, COUNT(*) AS count FROM main.images AS mi JOIN (SELECT id AS film_rolls_id, folder       FROM main.film_rolls)   ON film_id = film_rolls_id  WHERE (1=1) GROUP BY folder ORDER BY film_rolls_id DESC"
17,577917 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/duplicate.c:403, function _lib_duplicate_init_callback(): prepare "SELECT i.version, i.id, m.value FROM images AS i LEFT JOIN meta_data AS m ON m.id = i.id AND m.key = ?3 WHERE film_id = ?1 AND filename = ?2 ORDER BY i.version"
17,578277 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1037, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
17,578377 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/image.c:250, function _update(): prepare "SELECT COUNT(id) FROM main.images WHERE group_id = ?1 AND id != ?2"
17,588142 [sql] /home/obry/dev/builds/darktable/build/src/src/common/collection.c:1037, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
17,588261 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/tools/timeline.c:621, function _time_read_bounds_from_collection(): prepare "SELECT db.datetime_taken FROM main.images AS db, memory.collected_images AS col WHERE db.id=col.imgid AND LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '0001:01:01 00:00:00' COLLATE NOCASE ORDER BY db.datetime_taken ASC LIMIT 1"
17,588502 [sql] /home/obry/dev/builds/darktable/build/src/src/libs/tools/timeline.c:642, function _time_read_bounds_from_collection(): prepare "SELECT db.datetime_taken FROM main.images AS db, memory.collected_images AS col WHERE db.id=col.imgid AND LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '0001:01:01 00:00:00' COLLATE NOCASE ORDER BY db.datetime_taken DESC LIMIT 1"
17,588788 [sql] /home/obry/dev/builds/darktable/build/src/src/common/history.c:1582, function dt_history_hash_get_status(): prepare "SELECT CASE  WHEN basic_hash == current_hash THEN 1  WHEN auto_hash == current_hash THEN 2  WHEN (basic_hash IS NULL OR current_hash != basic_hash) AND       (auto_hash IS NULL OR current_hash != auto_hash) THEN 4  ELSE 1 END AS status FROM main.history_hash WHERE imgid = 95735"
17,589015 [sql] /home/obry/dev/builds/darktable/build/src/src/common/image.c:320, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
```

**Comment by TurboGit** [comment]
I confirm the issue is in list_view and probably also in tree_view update.

Add a return on first line of:

`static void update_view(dt_lib_collect_rule_t *dr)`

Makes the star rating or change of filtering instantaneous again.

**Comment by TurboGit** [comment]
The slow part is:

```
        if(property == DT_COLLECTION_PROP_FILMROLL)
        {
          gtk_list_store_set(GTK_LIST_STORE(model), &iter,
                             DT_LIB_COLLECT_COL_UNREACHABLE, !(g_file_test(value, G_FILE_TEST_IS_DIR)), -1);
        }
```
Which is used to display folder name with a strike when not reachable. A nice feature but quite slow ! This is done on each refresh of the view list. We probably want to cache the values ?

@phweyland : What is your thoughts on this ?

**Comment by ralfbrown** [comment]
I've been looking at avoiding calling `update_view` when the Collections module is collapsed (will require some extra code elsewhere to ensure an update when later expanded again).  For the particular case of a change in star ratings, there shouldn't be a call to `update_view` anyway, since there is no possible way for a changed star rating to change the result of any of the filter rules....

**Comment by TurboGit** [comment]
@ralfbrown : Sure, this is a case we can work around.

But in general if we can avoid the insane number of g_file_test() calls it would be good. My idea is during the first filing of the list (and checking for all folder accessibility) we record the status of each root directory. Later we check for folder accessibility only if the root directory access has changed. This should speed things up as I suppose the collections are probably all rooted under a very limited number of directory. In my case I have only 2 different root directory but hundred of folders (975 exactly). The only issue is that this won't cover the case of renamed or deleted directory out of darktable while the darktable session is running. Probably a sane compromise.

**Comment by ralfbrown** [comment]
> But in general if we can avoid the insane number of g_file_test() calls it would be good.

Of course.  Not doing an update at all is even faster :-).

**Comment by TurboGit** [comment]
Or just check the accessibility for the visible items only (~ 15), not much and so can be done every time.

**Comment by phweyland** [comment]
Sorry for being late on this.
If I understand properly this feature is mainly related to (un)mountable devices. Isn't there any associated event ?

> Or just check the accessibility for the visible items only (~ 15), not much and so can be done every time.

This sounds reasonable.

Another option could be to check the validit and update the display only when hovering (and/or clicking on) a folder.

**Comment by TurboGit** [comment]
@phweyland : I have tried to update the visible part of the tree, but :

`gtk_tree_view_get_visible_range(GTK_TREE_VIEW(d->view), &start_path, &end_path) `

Always fails (returns FALSE) and does not return the start_path & end_path. Any idea why ?

The update on hover could be ok but not nice as each refresh of the tree destroy all the items so we will get change of status again and again.

**Comment by phweyland** [comment]
> Always fails (returns FALSE) and does not return the start_path & end_path. Any idea why ?

Strange. Found nothing yet about this...



> The update on hover could be ok but not nice as each refresh of the tree destroy all the items so we will get change of status again and again

As the tree doesn't need to be rebuilt, no need to call tree_view(). I think than updating DT_LIB_COLLECT_COL_UNREACHABLE should be enough.

**Comment by TurboGit** [comment]
> As the tree doesn't need to be rebuilt, no need to call tree_view().

What I mean is that each time you'll change a star or filer the tree is rebuilt and so the DT_LIB_COLLECT_COL_UNREACHABLE  flag is cleared.

**Comment by TurboGit** [comment]
> Strange. Found nothing yet about this...

Seems like for this to work the widget must be realized which makes sense when you think about it but the Gtk+ doc was not really clear about this.

**Comment by phweyland** [comment]
> What I mean is that each time you'll change a star or filer the tree is rebuilt and so the DT_LIB_COLLECT_COL_UNREACHABLE flag is cleared.

... Changing stars or filter should not trigger the rebuilt of the tree.  They act on the current collection, don't they?

**Comment by ralfbrown** [comment]
> Changing stars or filter should not trigger the rebuilt of the tree

That's what #9046 is about, but there are lots of other user actions that will require a tree rebuild (tags, color labels, etc.) so avoiding a big lag is still worthwhile.

**Comment by TurboGit** [comment]
@phweyland : I just can't get this right. I have a working implementation for the list_view but this is not working for the tree_view. I'm not expert on Gtk and after spending hours I surrender :) Do you mind looking at it ? I can push my current PR even if the code is a bit of a mess after trying too many things if you like.

**Comment by AlicVB** [comment]
As said in #9046 I'm not a fan of making an exception for rating...
- because I don't like exceptions ;)
- because that don't solve the same issue than happens with colorlabels, etc...
- because I think that one day rating will be added to collect module too, in order to allow more complex query with rating too

as @ralfbrown explain in PR #9046 we can't just skip the tree refresh in the case of `DT_COLLECTION_CHANGE_RELOAD` event and `DT_COLLECTION_PROP_FOLDERS` or `DT_COLLECTION_PROP_FILMROLL` because that will cause problems if we have a query with first rule to colorlabels (for example) and second to filmroll.

so what I see as a solution could be (only change are in libs/collect.c) :
1. skip the tree rebuild if `DT_COLLECTION_CHANGE_RELOAD` and all query steps are with `DT_COLLECTION_PROP_FOLDERS` or `DT_COLLECTION_PROP_FILMROLL`
2. add a flag to `_lib_collect_gui_update` to choose if we want to "remember" the "directory reachable" state. That can be something like "construct a list of all actual dir with their reachable values" + "refresh the tree and check the directory in the list before doing the `g_file_test` "

**Comment by TurboGit** [comment]
@AlicVB : I'm not looking at making an exception, my goal was to compute the g_file_test() status only when moving over the treeview/listview. So some king of lazy computing and only for the currently visible part of the tree.

**Comment by TurboGit** [comment]
If we can avoid some collection update fine, but even so having a lazy computing and only for the visible part is a good foal.

**Comment by AlicVB** [comment]
@TurboGit : sorry, the exception was in reference of PR #9046 :)



> If we can avoid some collection update fine, but even so having a lazy computing and only for the visible part is a good goal.

agree ! That plus avoid the compute when not needed would be great !

**Comment by phweyland** [comment]
>  Do you mind looking at it ?

I'll make a try :)



>  I can push my current PR even if the code is a bit of a mess after trying too many things if you like.

That could help too if you can push this to your repository.

**Comment by TurboGit** [comment]
Thanks a lot ! See branch  po/collect-update-visbale  on my repository.

**Comment by ralfbrown** [comment]
I think the root cause underlying all the discussion we've been having about skipping/not skipping the tree rebuild is simply that the Collections module has no idea what the user changed, it only gets a signal to update.  If we were able to pass along the class of item that changed (rating, color, tag, etc.), then Collections could make a proper choice of whether it needs to update or not (yes if one of the filter rules includes that class, no otherwise), and we don't need exceptions elsewhere that rely on knowledge of what items might be in filtering rules.

**Comment by AlicVB** [comment]
@ralfbrown : I agree :)  That shouldn't be too difficult, just another item to pass with the signal and underlining fct... The most difficult part will be to change all the place where this is used, which is a lot !

@phweyland : if you want, we can split the task in 2 : I'm doing the part to avoid as much as possible unneeded tree rebuild (I know the collection update part quite well) and you do the lazy load ?

**Comment by AlicVB** [comment]
@ralfbrown @phweyland : see PR #9058 for an implementation of @ralfbrown idea... That limit drastically the number of treeview rebuild :)

**Comment by phweyland** [comment]
OK, i'll see what I can do for lazy load.

**Comment by phweyland** [comment]
Even at the end of tree_view() gtk_tree_view_get_visible_range() doesn't work. At this point the tree should be realized.
Even gtk_tree_view_get_visible_rect() doesn't return always a valid rectangle. It returns the rectangle of the previously displayed view (at start, first display: width=1 and height=1).
In that case dt_ui_scroll_wrap() doesn²t work neither (no way expand the view).

dt 3.5.0+2360~ge734491a9

**Comment by TurboGit** [comment]
Note: The situation has improved drastically by limiting the number of refresh of the collections (avoiding unneeded signals). Yet, it would be good to avoid recomputing endlessly the file status as this is a very slow operation.
