### ISSUE TITLE
Darktable shows different preview depending on the zoom level

### ISSUE THREAD

**Issue by KristijanZic** [darktable-org/darktable#9043]
Darktable (master branch on Ubuntu 20.04) is showing different preview depending on the zoom level.

You can see in these screenshots that when zoomed out completely, the highlights are completely blown out but as I zoom in, I can start to see all the detail in the highlights as if it was processed differently on with different exposure settings.
![Screenshot from 2021-05-23 19-47-56](https://user-images.githubusercontent.com/10299892/119271483-097bd900-bc02-11eb-9773-82cfbf70a32f.png)
![Screenshot from 2021-05-23 19-48-22](https://user-images.githubusercontent.com/10299892/119271485-0bde3300-bc02-11eb-9575-8b946b81e412.png)
![Screenshot from 2021-05-23 19-48-43](https://user-images.githubusercontent.com/10299892/119271486-0e408d00-bc02-11eb-824e-6aa67a1c2d65.png)
![Screenshot from 2021-05-23 19-48-56](https://user-images.githubusercontent.com/10299892/119271488-10a2e700-bc02-11eb-9170-343f9ccb2a71.png)

Even the clipping indicator changes:
![Screenshot from 2021-05-23 20-08-25](https://user-images.githubusercontent.com/10299892/119271661-c3734500-bc02-11eb-90e1-7bcfa9e17d7f.png)
![Screenshot from 2021-05-23 20-08-39](https://user-images.githubusercontent.com/10299892/119271663-c53d0880-bc02-11eb-889b-cb9fc420fd1f.png)

When the image is exported, the highlights are blown out no matter on which zoom level you look at it:

![2020-12-14-X-T3-DSCF2168_01](https://user-images.githubusercontent.com/10299892/119271540-4c3db100-bc02-11eb-8b43-f62c9199fe62.jpg)

**Comment by AlicVB** [comment]
That's the "normal" behavior : 
You are facing the difference between the preview jpeg embedded inside the raw files and the raw file as developped by dt.
The export files is how dt develop the image == blown highlight in our case.

So in our case, lighttable show the embedded jpeg preview until a certain zoom level, after what dt develop the image to produce the preview. This can have 2 reasons : 
- in the preference dialog, you have set the option "use embedded preview..." to use the raw file after a certain level.
- the jpeg preview embedded in your raw file is smaller than the raw file (some cameras does that)

I'm closing for now, but if I'm wrong in my assumption, just reopen (or ask for)
