### ISSUE TITLE
Retouch/clone conflicting with crop

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#9061]
**Introduction**
_Cropping an image after retouch/clone is a problem when the cloned area is outside of the final crop.

**Describe the bug/issue**
A series of images demonstrates the problem:
1. I wish to eliminate the white area along the top edge
![stump1](https://user-images.githubusercontent.com/6267270/119436623-5bd7fb00-bcd1-11eb-9f04-35af1b987e0f.png)
2. First I clone a section of trees to cover the blank space
![stump2](https://user-images.githubusercontent.com/6267270/119436834-d0129e80-bcd1-11eb-8a59-4380de001517.png)
3. The clone is now in place and looks correct
![stump3](https://user-images.githubusercontent.com/6267270/119436955-fe907980-bcd1-11eb-990d-44ecbf1b1b21.png)
4. The retouch is now closed and I start a crop 
![stump4](https://user-images.githubusercontent.com/6267270/119437055-2ed81800-bcd2-11eb-8cd3-2ba36f203762.png)
5. The crop is now closed but the clone is incorrect
![stump5](https://user-images.githubusercontent.com/6267270/119437115-5202c780-bcd2-11eb-9a27-244f81712875.png)

**Expected behavior**
Cropping should not change the clone process

* darktable version : darktable 3.5.0+2197~g0ee2e87be-dirty

* OS                : e.g. Linux - kernel 5.13 rc1
* Linux - Distro    : Manjaro/Arch
* Memory            : 16 Gb
* Graphics card     : Quadro K1000M
* Graphics driver   : Nvidia
* OpenCL installed  : Not active
* OpenCL activated  : 
* Xorg              : 
* Desktop           : XFCE
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes 
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/JpegRAW no test with JPG
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")?

**Comment by MStraeten** [comment]
Did you use the new crop or the old crop and rotate module? The new crop should avoid this behaviour since it’s later in the pixel pipe then the old crop&rotate

**Comment by elstoc** [comment]
Agreed. You should use crop & rotate for rotations and keystone corrections only and perform cropping with the crop module. Crop & rotate should hopefully be phased out by v3.8 due to the difficulty of maintaining it and the issues of pipe order.

**Comment by davidvj** [comment]
I have now installed the 'new' crop and it works correctly making the 
crop after the clone.

Thank you it appears that this now closes the issue.

**Comment by johnny-bit** [comment]
> Thank you it appears that this now closes the issue.

OK :)
