### ISSUE TITLE
Original date/time in geotagging

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#9064]
https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/geotagging/

In the new geotagging module there is an entry called "original date/time".

For the casual user this is puzzling: it can be either
- the original actual statutory time of exposure
- the time the camera writes into the exif "originally".

If it is the latter (and that's what I read from the docs linked above) - I'd suggest renaming that field to something like "EXIF date/time" or "Camera date/time" or the like.

**Comment by phweyland** [comment]
Well, I don't have the same feeling.
date/time represents the current value (with or without change), original date/time represents the value before change, which seems straight forward to me.

**Comment by johnny-bit** [comment]
I think it's more of a doc issue (https://github.com/darktable-org/dtdocs) than interface one. Suggested `EXIF date/time` could be confusing/too complex and `camera date/time` does mean for me the same as "original date/time" and here's no confusion...
