### ISSUE TITLE
Darktable produces corrupted output

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#9070]
Hello. I've got a problem at exporting both jpg and tiff - images look wrong, while they look OK in both lighttable and darktable modes. 

Darktable is compiled from git at commit c89f6bace18895e0c33f8b0a0de08b1f569e9b76

Mint Linux 20.1 Mate x64. OpenCL is enabled at output.

**Comment by BigSerpent** [comment]
![DSC05705_01](https://user-images.githubusercontent.com/47396887/119656709-aa9da600-be33-11eb-8d97-6b2b1cbc929a.jpg)

**Comment by BigSerpent** [comment]
That file should be black and white. Regular color files look similar after exporting.

**Comment by johnny-bit** [comment]
Can you share an xmp file along with a sample input file please?

**Comment by aurelienpierre** [comment]
Quickly and from afar, that issue looks like a white point mismatch in your exporting space ICC, or a user mistake in pipeline.

**Comment by BigSerpent** [comment]
The issue can be closed - with the current git version the files what caused corrupted output before are exported correctly. I do not know what was the reason for the error as I've deleted build directory before compiling and rebooted the computer. Nevertheless, now that files are exported correctly.

**Comment by TurboGit** [comment]
Thanks, closed.
