### ISSUE TITLE
Mask indicator only works with some right-side button modes

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9073]
The mask indicator that appears in processing module headers only appears to work when `preferences > darkroom > show right-side buttons in processing module headers` is set to "always", "active" or "dim".

In the other modes it will sometimes display, but usually this only seems to happen if you change mode while still in the darkroom view (presumably because it still "remembers" the state from a previous setting?)

darktable 3.5.0+2356~g8462ec043 on ArchLinux

**Comment by elstoc** [comment]
@dterrahe, @Mark-64 hopefully one of you might have an idea :)

**Comment by Mark-64** [comment]
I will have a look

**Comment by dterrahe** [comment]
@Mark-64 You may already have figured this out and solved, but in the "dynamic" modes, there is an invisible gtkdrawingarea between the label and the buttons on the right that is used to monitor the available space. When you add the new button using
`gtk_box_pack_end`, it is added to the _left_ of this widget and therefore is never considered for unhiding.
So you'll have to put it to the _right_ of this widget, if it exists, but to the left of all other buttons.

**Comment by Mark-64** [comment]
@dterrahe yes, thanks for the hint, PR coming
