### ISSUE TITLE
image information does not show "<various values>" in culling fixed mode when selecting multiple pictures

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9084]
**Describe the bug/issue**
When multiple pictures are selected that diverge in some image information (such as different exposure, focal length, ...) darktable will display "various values" in that field. This does not work for culling fixed mode. Here, only "image id" is replaced by "various values". Every other field displays information of the last picture that has been selected

**To Reproduce**
1. Enter culling (fixed) mode with a selection of images or select pictures after entering the mode.
2. Check out the image information.

**Screenshots**

Culling fixed
![image](https://user-images.githubusercontent.com/2805109/119894577-0c960280-bf3d-11eb-9853-3a700839ddd6.png)

Culling dynamic and other modes
![image](https://user-images.githubusercontent.com/2805109/119894495-f720d880-bf3c-11eb-89af-7b700d1aa2ee.png)

**Platform**

* darktable version : 3.5.0+2370~gd06912666
* OS                : Manjaro Linux

**Comment by AlicVB** [comment]
@Solarer : I can't reproduce your second screenshot. Are you sure you don't hover anything with your mouse (try to put your mouse inside the right panel to be sure)
For the first one, The reason is certainly that you have grouped images, so as soon as your mouse don't hover an image, it shows the selection == the 2 grouped images, with different ids...

**Comment by Solarer** [comment]
The second screenshot shows the correct behavior. You should be able to reproduce that :smile:. The first one shows the bug.
I am positive that I don't hover anything. As soon as I hover my mouse over an image I only see that picture's information and not a single "various values" which is the correct behavior.
If I select multiple pictures and don't hover anything, the result is what I described above.

None of my pictures are part of a group. If I group some pictures and select only those that are part of a group, screenshot 1 still looks the same and in screenshot 2 I can see the group ID since it is the same for all selected pictures (correct behavior).

To reproduce try to select as many pictures as possible (so that you have some variation in your image information) and enter culling fixed mode. You need to move your mouse a bit because the image information will not refresh directly upon entering culling mode.

**Comment by johnny-bit** [comment]
@Solarer - can you try doing eg screenrecording? it might help with figuring out exactly what's wrong...

**Comment by Solarer** [comment]
I will try to do that on Sunday

**Comment by Solarer** [comment]
@johnny-bit First I failed to reproduce this for screenrecording and thought it was fixed, but then I found the missing information:
In culling fixed mode you need to set the slider to display only 1 image while having selected more than 1 picture.

If you display 2 or more pictures, darktable will take the image information from all displayed images to calculate the "various values" fields (correct behaviour).
If you display only a single image, unless you hover it darktable does not display the information of the image in focus but the information of a different picture in your selection  -> wrong behavior 

Additionally, the information of the picture that is displayed instead is not displayed properly since "image id" is replaced by "various values" instead of the image id (see first screenshot).

**Comment by AlicVB** [comment]
ok, I can reproduce now :)
That's quite strange... The good news is that it doesn't affect "image to act on" so at least the issue is not in this delicate area...
I'll have a look !

**Comment by AlicVB** [comment]
@Solarer : PR #9306 should fix it !

**Comment by Solarer** [comment]
yeah, "images to act on" could not be the problem. As much as I don't agree with WHAT it does, it has been coded well and does it correctly :D

fixed!
