### ISSUE TITLE
number of images displayed does not update in culling (fixed) mode when changing the slider

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9087]
**Describe the bug/issue**
The number of images displayed does not update in culling (fixed) mode when changing the slider. The number only updates when the mouse hovers over the filmstrip or over the central view.

**To Reproduce**
1. Enter Culling (fixed) mode
2. Change the number of images displayed with your mouse and the slider
3. Images will not update until you hover them or the filmstrip with the mouse.

**Expected behavior**
Images update right away

**Which commit introduced the error**
This was not the case a few weeks ago. I am too busy today so I cannot check for the exact commit.

**Platform**

* darktable version : 3.5.0+2373~gb3bc49ba4 (latest master)
* OS                : Manjaro Linux
* Linux - Distro    : e.g. Ubuntu 18.4

**Comment by AlicVB** [comment]
Confirmed, I'll have a look !
