### ISSUE TITLE
Lens correction: add autocrop option or crop suggestion

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9090]
**Describe the bug/issue**
Sometimes, I use stereographic geometry in lens correction to avoid distorting people close to the edge of the photo taken at a wide angle.
Previously, this resulted in a black area surrounding image content, which I was then able to crop away:
![](https://tech.kovacs-telekes.org/files/2021-05-28-darktable-lens-correction/stereographic-correction-darktable-3.4.1.1-windows.png) For privacy, there is no person in this image, but you get the idea. The screenshot is from Windows, v3.4.1.1, without OpenCL, but I had the same behaviour on Linux with OpenCL as well.

With recent versions, the black border is replaced with the last pixels repeated until the original image edge. ~~Maybe~~ As discussed below, this is intended to ~~e.g. fill the black with sky colour etc.~~ to help modules that apply operations that would produce artefacts due to the black pixels (e.g. blurs), but I think it's rather distracting, and much harder to crop (since setting the crop rectangle now requires more careful pixel peeping compared to the previous abrupt transition to black):
![](https://tech.kovacs-telekes.org/files/2021-05-28-darktable-lens-correction/stereographic-correction-darktable-b3bc49ba4-linux.png) darktable b3bc49ba4 on Linux, OpenCL en/disabled changes nothing.
![](https://tech.kovacs-telekes.org/files/2021-05-28-darktable-lens-correction/stereographic-correction-darktable-b3bc49ba4-linux-zoomed-in.png) same as above, zoomed in.

**To Reproduce**
1. Go to https://tech.kovacs-telekes.org/files/2021-05-28-darktable-lens-correction/ and download the raw file.
2. In darkroom, go to lens correction.
3. Switch geometry to 'stereographic'.
4. See result.

**Expected behavior**
~~Black border around image.~~ An auto-crop option to remove the automatically filled area (but still allowing the user to select their own region).

**Which commit introduced the error**
I don't know. I first saw this for at least a month ago, but didn't have time to report it (also, I'm not sure if it's a new feature that I don't like, or a genuine bug).

**Platform**
Ubuntu Linux, 64-bit

* darktable version : 3.5.0+2353~gb3bc49ba4
* OS                : Ubuntu Linux, kernel 5.11.0-17
* Linux - Distro    : Ubuntu 21.04
* Memory            : 64 GB
* Graphics card     : NVidia 1060/6GB
* Graphics driver   : 460.73.01
* OpenCL installed  : yes
* OpenCL activated  : yes & no, same result
* Xorg              : xserver-xorg 1:7.7+22ubuntu1; xserver-xorg-core 2:1.20.11-1ubuntu1
* Desktop           : KDE Plasma (kd5 5.80.0-0ubuntu1)
* GTK+              : 3.24.25-1ubuntu4.1  
* gcc               : 10.3.0-1ubuntu1 
* cflags            : unknown
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Additional context**
 - Can you reproduce with another darktable version(s)? as I said, I've had this for at least a month
 - Can you reproduce with a RAW or Jpeg or both? only tried raw
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes

**Comment by kofa73** [comment]
```
kofa@eagle:~/darktable$ git bisect bad
5b1864c0a8d9cf6652b0410caa8ef4342cee57a2 is the first bad commit
commit 5b1864c0a8d9cf6652b0410caa8ef4342cee57a2
Author: rawfiner <rawfiner@gmail.com>
Date:   Thu May 6 12:12:41 2021 +0200

    lens: restrict values to [0,width[... bounds also for opencl kernels

 data/kernels/basic.cl | 144 +++++++++++++++++++++++++++++++++++++++-----------
 1 file changed, 114 insertions(+), 30 deletions(-)
```

**Comment by kofa73** [comment]
I don't know if important or not: lensfun is at 0.3.2-6.

**Comment by TurboGit** [comment]
@rawfiner : Can you have a look ? TIA.

**Comment by rawfiner** [comment]
The problem is that borders are bad, they have side effect as they impact algorithms that use blurs

**Comment by kofa73** [comment]
So my hunch with 

> Maybe this is intended to e.g. fill the black with sky colour etc.

was correct. I can live with this, even though cropping out the 'invalid' part is now more difficult.

**Comment by kofa73** [comment]
So, do I understand correctly that one should remove the artificially filled area using the new 'final' crop module? https://github.com/darktable-org/darktable/pull/8838.
If so, I think it's worth mentioning in https://darktable-org.github.io/dtdocs/module-reference/processing-modules/lens-correction/ that the filling of areas is not a bug, but rather a feature to support blurs and the like (e.g. contrast EQ, I guess), and also update the documentation of https://darktable-org.github.io/dtdocs/module-reference/processing-modules/crop/ (currently it only mentions _retouch_ as a module that benefits from a late crop).

**Comment by rawfiner** [comment]
> So, if I crop, and _then_ apply a blur, will that blur take the area outside the crop into account?

It depends on the module, but yes module can ask for an input image which is wider than what we see, so it can be wider than the crop

**Comment by rawfiner** [comment]
> one should remove the artificially filled area using the new 'final' crop module

You can use whatever crop you like actually, not necessarily the final one. 
Ideally, I guess the module should have an option to crop automatically, but that is more work to do so I don't think it will be possible before 3.6 release.

> I think it's worth mentioning in https://darktable-org.github.io/dtdocs/module-reference/processing-modules/lens-correction/ that the filling of areas is not a bug, but rather a feature to support blurs and the like

Good idea. I'll do that!

**Comment by kofa73** [comment]
> the module should have an option to crop automatically

Yes, but it'd be nice to really have it as an option (e.g. when using a wider crop ratio than that of the input image).

**Comment by TurboGit** [comment]
Rescheduled for 3.8.

**Comment by johnny-bit** [comment]
Given the discussion and docummentation change I'd consider this issue to have now remaining one element: add an auto-crop/recommended crop feature to lens correction module.

@kofa73 - if you agree would you mind changing the title while I change the tags?

**Comment by kofa73** [comment]
@johnny-bit : done, thanks for the update.

**Comment by rawfiner** [comment]
@kofa73 sorry for the long wait, I was finally starting to work on this. But actually I figured out the feature is already there: on the right of the scale slider, the circular arrow button does exactly that.
So I guess maybe it is just a matter of adding a line in the documentation to encourage users to use that button when needed?
What do you think?

**Comment by rawfiner** [comment]
if that helps, we could add a mode that always set scale automatically, to avoid having to click on the button

**Comment by kofa73** [comment]
Thanks for the investigation @rawfiner, sorry it took me so long to respond. I'm perfectly happy with the 'auto scale' button. I'm closing the issue.

**Comment by rykzon** [comment]
Would it be possible to apply the "auto scale" by default? Its rather tedious to manually apply that to all images since the actual value can't be copied from images with other lenses/lens settings.
