### ISSUE TITLE
Ricoh GR III white balance presets

### ISSUE THREAD

**Issue by grattus** [darktable-org/darktable#9091]
Attached is the tar.gz generated by extract_wb_from_images.sh for the Ricoh GR III (finetuned lazy method, 8 presets).
[darktable-whitebalance-20210528.tar.gz](https://github.com/darktable-org/darktable/files/6562974/darktable-whitebalance-20210528.tar.gz)

**Comment by johnny-bit** [comment]
Full support for GR III depends on https://github.com/darktable-org/rawspeed/pull/279 so I'm removing 3.6 milestone.

Thanks for the samples
