### ISSUE TITLE
color balance rgb gamut clipping

### ISSUE THREAD

**Issue by xfh** [darktable-org/darktable#9095]
Hi

I am not sure if this is a bug, or if I am just too stupid to get my head around the color science. For some learning exercise I've loaded some artificial test images and played with the color balance rgb module.
According to the manual:

> At its output, color balance RGB checks that the graded colors fit inside the pipeline RGB color space (Rec 2020 by default) and applies a soft chroma clipping at constant luminance and hue. This prevents the out-of-gamut colors that can quickly be produced when increasing chroma and saturation.

But to me, the color changes are rather surprising. @aurelienpierre I hope you don't mind to elaborate what's happening and whether this is the intended behaviour.

I've downloaded one of the graphs from https://eng.aurelienpierre.com/2021/04/the-srgb-book-of-color/ and pushed chroma respectively saturation (beyond reason, I know). 
What surprises me, is that blue (hue 243) turns cyan (hue 185) before it eventually turns black when pushing chroma. Isn't that contrary to what's written in the manual?
Pushing saturation skips the cyan conversion and just goes black.

Activating filmic with default settings mitigates the cyan issue, since everything high luminance is desaturrated.

I am not sure if my approach was doomed from the start due to testing with a png, but I can also reproduce with a tif file.

EDIT: There are actually two things I am wondering:
1. Why is there a hue shift to cyan? This doesn't botter me really, since it seems to not happen when filmic is switched on
2. Shouldn't increased chroma clipping result in white instead of black? Looking at the 2nd image, right corner, this would avoid the harsh transition.

darktable 3.5.0 98ba99f784736c7c261e5f28209e33588142db48 (recent master)
Linux, OpenCL active - but can reproduce without.

 **Screenshots** 
chroma pushed - filmic off
![ColorBalanceRGB-ChromaClipping-filmic-off](https://user-images.githubusercontent.com/9366771/120051766-45f46e00-c022-11eb-9ac3-55a0c04b13fd.png)
chroma pushed - filmic on
![ColorBalanceRGB-ChromaClipping-filmic-on](https://user-images.githubusercontent.com/9366771/120051768-47259b00-c022-11eb-9e6f-919ff2794b17.png)
saturation pushed - filmic off (filmic on does not change the clipping)
![ColorBalanceRGB-SaturationClipping](https://user-images.githubusercontent.com/9366771/120051769-47be3180-c022-11eb-84bf-32324165325f.png)

**Test Images**
[test-images.zip](https://github.com/darktable-org/darktable/files/6563763/test-images.zip)

**Comment by aurelienpierre** [comment]
Blue degrading to cyan is not normal. I'm not sure what happens and at what place in the pipeline it happens, but don't forget color balance RGB works in large gamut RGB (if you use the default working RGB space) so there is necessarily an extra gamut conversion step from working RGB to display. 

Forget filmic, whether it hides some of the issue or not is irrelevant. Also, saturation and chroma operate in different color spaces internally, so they are not linked in implementation.

It might just be another computation mistake somewhere. Although I have checked that part quite a lot.

**Comment by xfh** [comment]
I have linear Rec2020 RGB as histogram profile and a (calibrated) display profile, with some 90% or so of Adobe RGB.

I am adding two darktable exports, first one with output profile sRGB, second with linear Rec2020. That way we should be able to exclude my display profile, right?

**linear Rec2020 RGB**
![sRGB-primary-blue-continuous-sRGB](https://user-images.githubusercontent.com/9366771/120084379-fd938980-c0cf-11eb-9c16-582c4a137ba1.jpg)
**sRGB (web-safe)**
![sRGB-primary-blue-continuous-linearRec2020](https://user-images.githubusercontent.com/9366771/120084377-fcfaf300-c0cf-11eb-8cc4-d5134257c707.jpg)

The export still hast the cyan and black.

**Comment by aurelienpierre** [comment]
Confirmed, the issue is in the Ych -> Yrg -> LMS backtransform. The gamut mapping actually helps a lot, I tried without it and the color clips to magenta or yellow (!) instead. Maybe the gamut mapping can be improved to avoid the black part (I don't know how yet…), but it's already an improvement over the naive way (which makes things bad starting at +25% chroma).

**Comment by aurelienpierre** [comment]
@xfh can you test #9107 ?

**Comment by xfh** [comment]
I tested and could stills see some cyan shifts. My first thought was that I din't build correctly, so I wiped build and config directories and tried again. But even then, I managed to get some strange effects. The small preview, the filmstrip and the main preview can still show a cyan image, although a much smaller area than before. With the same settings, not all of them are showing the same casts. I haven't found a way to reproduce unfortunately.

I've also noticed cyan in the live color picker, just before the black clipping, but I am not sure if that's the same effect that happened to my previews. I know there are some more profile conversions when it comes to the histogram. I've thus set the output profile to linear Rec2020 RGB but can still reproduce. I have no idea why the color picker behaves like that.
What's interesting to see though: the cyan shift is not actually a hue shift. It seems to be the extreme lightness, that causes the hue shift.

I tried one more time, with a release build instead, and not attaching the debugger. Now I can't reproduce the cyan shifts any more. The only way to get these shifts in the color picker are happening when using a too small histogram profile, e.g. sRGB. I thought I was doing exactly the same as before - I guess I wasn't.
Anyway, for the curious, here is a screen recording of what I saw earlier with in the color picker. 
https://user-images.githubusercontent.com/9366771/120119816-15374480-c19a-11eb-8208-f9c5092685be.mp4

When I choose sRGB as histogram profile, I am still able to get the cyan hues in the color picker, while preview and exported image look correct. Changing display profile to sRGB finally fixes the hue shift. Are the patches of the color picker only using the display profile? I had assumed it would be the histogram or softproof profile. 

Any way, all this has nothing to do with your changes, they do alleviate the hue changes. Thanks!

**Comment by aurelienpierre** [comment]
The whole gamut clipping business is tricky to debug because several parts are involved in the process: our internal color spaces conversions (for histogram space), and our internal conversions or Little CMS2 for the final image color conversion (preview). And actually, the histogram is computed on top of the thumbnail preview, so you stack several color space conversions on top of each other. At the end, what you get in color picker may not be what you get in exported picture or preview, because the gamut boundaries may be handled differently (or even not handled at all if LittleCMS2 is not used for exports).

**Comment by xfh** [comment]
Thanks for the explanation.

**Comment by todd-prior** [comment]
> I tested and could stills see some cyan shifts. My first thought was that I din't build correctly, so I wiped build and config directories and tried again. But even then, I managed to get some strange effects. The small preview, the filmstrip and the main preview can still show a cyan image, although a much smaller area than before. With the same settings, not all of them are showing the same casts. I haven't found a way to reproduce unfortunately.
> 
> I've also noticed cyan in the live color picker, just before the black clipping, but I am not sure if that's the same effect that happened to my previews. I know there are some more profile conversions when it comes to the histogram. I've thus set the output profile to linear Rec2020 RGB but can still reproduce. I have no idea why the color picker behaves like that.
> What's interesting to see though: the cyan shift is not actually a hue shift. It seems to be the extreme lightness, that causes the hue shift.
> 
> I tried one more time, with a release build instead, and not attaching the debugger. Now I can't reproduce the cyan shifts any more. The only way to get these shifts in the color picker are happening when using a too small histogram profile, e.g. sRGB. I thought I was doing exactly the same as before - I guess I wasn't.
> Anyway, for the curious, here is a screen recording of what I saw earlier with in the color picker.
> https://user-images.githubusercontent.com/9366771/120119816-15374480-c19a-11eb-8208-f9c5092685be.mp4
> 
> When I choose sRGB as histogram profile, I am still able to get the cyan hues in the color picker, while preview and exported image look correct. Changing display profile to sRGB finally fixes the hue shift. Are the patches of the color picker only using the display profile? I had assumed it would be the histogram or softproof profile.
> 
> Any way, all this has nothing to do with your changes, they do alleviate the hue changes. Thanks!

I have just noticed something similar with the channel mixer. As long as my display and output profile match then it behaves as you would explect a channel mixer to work. If your display profile is not the same as the output profile then there is a lot of crosstalk in the channels when moving one of the primary color sliders in its own tab so for eg g-g is producing changes in the other channels. If you match the profiles then this behaviour seems corrected....

**Comment by aurelienpierre** [comment]
I just found a better fix:

![sRGB-primary-blue-continuous](https://user-images.githubusercontent.com/2779157/121489194-240ccb00-c9d4-11eb-91d5-ce7ae08f7337.jpg)

I will commit tomorrow.

**Comment by Yardlongbean** [comment]
I wonder how well the latest fix

 works with this image which produced black artefacts when the saturation was increased in  colour balance rgb. The files can be downloaded from this thread [](https://discuss.pixls.us/t/strange-effects-with-saturation-in-colour-balance-rgb-and-filmic/25403)
