### ISSUE TITLE
Ricoh GR III noise profile

### ISSUE THREAD

**Issue by grattus** [darktable-org/darktable#9099]
Attached is the tar.gz generated by darktable-gen-noiseprofile for the Ricoh GR III (31 presets). I tested it successfully. Note that I had to edit presets.json since maker and model were incorrect (see #9100 and #8992).
[darktable-noiseprofile-20210528.tar.gz](https://github.com/darktable-org/darktable/files/6564206/darktable-noiseprofile-20210528.tar.gz)

**Comment by grattus** [comment]
I am also attaching the original archive generated by the profiler, if useful. @johnny-bit pushed a commit on rawspeed to update the maker and model IDs of the Ricoh GR III (here: [darktable-org/rawspeed#279](https://github.com/darktable-org/rawspeed/pull/279)) - I don't know which `presets.json` will work once this commit will be merged.
[darktable-noiseprofile-20210528 (original).tar.gz](https://github.com/darktable-org/darktable/files/6565125/darktable-noiseprofile-20210528.original.tar.gz)

**Comment by rawfiner** [comment]
Thanks!
