### ISSUE TITLE
Dual demosaic increases coarse noise

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9101]
**Describe the bug/issue**
Turning on dual demosaic seems to increase noise. For example:
* Amaze: ![](https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/skin-amaze.png)
* VNG4: ![](https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/skin-vng4.png)
* Amaze+VNG4:
  * Threshold = 0.2: ![](https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/skin-amaze%2Bvng4-threshold02.png)
  * Threshold = 0 (should give pure Amaze, if I understand correctly): ![](https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/skin-amaze%2Bvng4-threshold0.png)
  * Threshold = 1(should give put VNG4): ![](http://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/skin-amaze%2Bvng4-threshold1.png)

More examples at https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/

Also, colour smoothing options are not available with dual demosaic.

**To Reproduce**

1. Download the raw from https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/
2. Switch between demosaic settings

**Expected behavior**
Noise is not increased

**Platform**

* darktable version : 3.5.0+2368~g98ba99f78
* OS : Ubuntu Linux, kernel 5.11.0-17
* Linux - Distro : Ubuntu 21.04
* Memory : 64 GB
* Graphics card : NVidia 1060/6GB
* Graphics driver : 460.73.01
* OpenCL installed : yes
* OpenCL activated : yes & no, same result
* Xorg : xserver-xorg 1:7.7+22ubuntu1; xserver-xorg-core 2:1.20.11-1ubuntu1
* Desktop : KDE Plasma (kd5 5.80.0-0ubuntu1)
* GTK+ : 3.24.25-1ubuntu4.1
* gcc : 10.3.0-1ubuntu1
* cflags : unknown
* CMAKE_BUILD_TYPE : RelWithDebInfo

**Comment by jenshannoschwalm** [comment]
Yes, color smoothing is intentionally not offered, the low-freqency demosaicer VNG gets the smoothing automatically before mixing. If a raw file needs smoothing it is not well suited for dual-dem.

Yes, 0.0 means fully RCD or AMaZE but 1.0 means not completely VNG but "mostly", you can see the mixing via the mask button (you are probably aware of that)

Yes, VNG is far from optimal for high iso or otherwise noisy data. For 3.8 i will go for IGV or LMMSE instead - both are much better suited for that and run here as preliminary versions but need a lot of performance tuning or are not well mathematically documented / analysed.

I looked at the image you provided, i don't **see** noise added, maybe my eyes are wrong and if i would do statistics ... don't know. I just think your example demonstrates that dual demosaicing is not optimally suited for such images, you have pushed by 3 stops in exposure having a 12bit sensor. Thats pretty hard :-)

**Comment by kofa73** [comment]
Yes, I know it's a small and old sensor, and the photo was much underexposed.
However, check out these:
* The mask, threshold set to 1.0. The area of the skin should use VNG4 only: ![](https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/mask.png)
* RCD+VNG4 (left) vs RCD (right): ![](https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/rcd%2Bvng4-left_vs_rcd_right.png)
* RCD+VNG4 (left) vs VNG4 (right): ![](https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/rcd%2Bvng4-left_vs_vng4_right.png) -- according to the mask, there should be no difference on the skin, right?
* RCD (left) vs VNG4 (right): ![](https://tech.kovacs-telekes.org/files/2021-05-29-darktable-dual-demosaic-noise/rcd-left_vs_vng4-right.png)

**Comment by jenshannoschwalm** [comment]
Mmh, i see now what you mean. i will have a deeper look at this.

**Comment by jenshannoschwalm** [comment]
@kofa i have some old rawfiles from my LX3 and others, unfortunately none with high iso .. I would appreciate it very much if you would share a file, you can of course do so to hanno@schwalm-bremen.de, i would treat it confidentially. I already have an idea what might be going on but thats difficult to reproce on the files i have available. Or if you are aware of a public file showing this issue, that would be appreciated as well.

**Comment by kofa73** [comment]
Sure, I'll send some files later (now off for a walk with the family). Is the landscape I've shared not good enough?

**Comment by jenshannoschwalm** [comment]
Thanks, it is good but the face image has that reddish color noise. Don't worry, have fun walking. My kids are all out of home, will find time tomorrow afternoon. Hanno
Am 29. Mai 2021, 18:53 +0200 schrieb Kofa ***@***.***>:

**Comment by kofa73** [comment]
I've uploaded the photo I'd used in the examples above, P1040525.RW2.

**Comment by jenshannoschwalm** [comment]
Thanks @kofa73 for making me aware of this stupid bug!
