### ISSUE TITLE
darktable.exe caused an Integer division by zero at location 00007FFBA284CA68 in module libdarktable.dll.

### ISSUE THREAD

**Issue by ccvca** [darktable-org/darktable#9112]
**Describe the bug/issue**
Crash when accessing images from a roll, when the folder of the roll has been renamed.

**To Reproduce**
1. Import Directory as a Roll (Only contains CR2 (Canon RAW) )
2. Rename the directory.
3. Click on multiple of the preview images (just try to open some of them in a row)
4. See error (files attached, see "Additional context")

**Expected behavior**
Don't crash. Maybe ask to remove the image from the roll, as it cann't be found.

**Platform**
* darktable version : 3.4.1.1
* OS                : Win10 (20H2)
* Memory            :  16GB
* Graphics card     :  Radeon RTX 570
* Graphics driver   : unknown
* OpenCL installed  : unknown
* OpenCL activated  : unknown

**Additional context**
Reproduced two times:
[darktable_bt_RYO730.txt](https://github.com/darktable-org/darktable/files/6566179/darktable_bt_RYO730.txt)
[darktable_bt_DMWI40.txt](https://github.com/darktable-org/darktable/files/6566180/darktable_bt_DMWI40.txt)

**Comment by johnny-bit** [comment]
Cannot replicate on current master.

Shows: "image `imagename` currently unavailable"

And I can't see whether anything would break, the code checking image presence is quite robust. I tried with 50+ images collection, nothing bad happened.

Can you add more details?

Also - refraining from renaming directory after importing it would be great idea ;) Right click on the roll and select "search filmroll" then point to new location can be nice workaround ;)
