### ISSUE TITLE
denoise (profiled) tooltip references non-existent 'details' slider

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9118]
**Describe the bug/issue**
Not really a bug, but a tooltip issue -- should be 'documentation'?

In the _denoise (profiled)_ module, the tooltip for the _patch size_ parameter talks about adjusting the _details_ slider:
![image](https://user-images.githubusercontent.com/3177739/120120205-149fad80-c19c-11eb-89a5-5da7692e7957.png)
However, there's no such control:
![image](https://user-images.githubusercontent.com/3177739/120120187-005bb080-c19c-11eb-8ff7-5dc74205c087.png)

* darktable version : 3.5.0+2379~g0bb81f9cb
* OS                : Linux - kernel 5.11.0-17-generic
* Linux - Distro    : Ubuntu 21.04

**Comment by ralfbrown** [comment]
I believe that should be _central pixel weight_ instead of _details_.

**Comment by kofa73** [comment]
That's quite likely indeed.
