### ISSUE TITLE
Darktable not working with copy history

### ISSUE THREAD

**Issue by heikkiwaan** [darktable-org/darktable#9125]
---------------------------------------------------------------

**Describe the bug/issue**
Darktable is making garbage when i copy the history from a raw file to another.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Make something lilke watermarks
2. i copied the watermark and changed something on it
3. i enabled the lens correction
4. copy the history
5. and paste to another raw file.

**Expected behavior**
like a smooth looking photo

**Screencast**
https://youtu.be/GFhV2J-TYuc

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.4.1 built from source.
* OS                : Linux 5.8.0-53-generic
* Linux - Distro    : Ubuntu 20.04.2 LTS
* Memory            : 16 GB
* Graphics card     : Nvidia GeForce GTX 1650
* Graphics driver   : Nvidia 460.80
* OpenCL installed  : ??
* OpenCL activated  : ??
* Xorg              : X.Org X Server 1.20.9
* Desktop           : Gnome 3.36.7
* GTK+              : 
* gcc               : gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
No, the default version of darktable for ubuntu 20.04.2 works somehow better. Has different bugs but that's a different story.

 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
Canon EOS 6D Mark II, Both RAW and JPEG files result the same.

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
yes, that's what i did

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
i did not do  --configdir "/tmp"
But i did rm -rf ~/.config/darktable

But after that it is even worse...
![Captura de pantalla de 2021-06-01 00-29-34](https://user-images.githubusercontent.com/85135616/120243530-821d0e00-c270-11eb-8aa0-66f36fa4cef4.png)

**Comment by heikkiwaan** [comment]
Darktable 3.5.0+2412~g1c305c71c, all works fine. Thanks.

**Comment by jenshannoschwalm** [comment]
@heikkiwaan you should then close this issue if everything is fine :-)

**Comment by johnny-bit** [comment]
Well, I can help with that :)
