### ISSUE TITLE
Denoise output is corrupted when zoomed or in the thumbnail

### ISSUE THREAD

**Issue by matze** [darktable-org/darktable#9136]
**To Reproduce**

1. Enable OpenCL on AMD.
2. Open a raw file and apply the denoised profile module.
3. Lightable thumbnail looks wrong (see screenshot). In the Darkroom view, the wavelet mode causes an almost completely black image, NLM is just weird (see screenshot).

**Expected behavior**

A denoised image regardless of zoom level.

**Screenshots**

Lighttable thumbnail:

![thumbnail](https://user-images.githubusercontent.com/115270/120511991-3763d900-c3cb-11eb-923a-7625bbcdf920.jpg)

Darkroom (NLM):

![darkroom-nlm](https://user-images.githubusercontent.com/115270/120512011-3a5ec980-c3cb-11eb-962b-3bbaaa67a6c8.jpg)

**Which commit introduced the error**

6a4aaae061ad3da561835ff526b73c957839f5f4

Reverting that change on master fixes the issue for me.

**Platform**

* OS                : Linux 5.8.0
* Linux - Distro    : Ubuntu 20.04.2
* Memory            : 64 GB
* Graphics card     :  AMD Radeon RX 5600 XT
* Graphics driver   : Mesa 20.2.6
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : no
* Desktop           : GNOME 3.36.8
* GTK+              : 3.24.20
* gcc               : 9.3.0

**Comment by johnny-bit** [comment]
Well... shit. Guess the comment was right. AMD has cool devices, cool new CPU & GPU tech comming... they could fix their opencl...

@aurelienpierre - can the `-cl-fast-relaxed-math` be enabled for nVidia, and for others `-cl-finite-math-only`? Or some other mechanism?

**Comment by matze** [comment]
Not Aurelien here but yes, you can of course test the vendor string and adjust the build flags accordingly.

**Comment by johnny-bit** [comment]
@matze what would you recommend? as I said: relaxed on nvidia and on others finite-math-only?

**Comment by matze** [comment]
That would probably the easiest and quickest way to fix it. But maybe someone knowledgeable could review the denoiseprofile kernel code and check all the conditions NaNs could be produced as outlined in #8923. However that would probably take a while and might introduce other regressions. I'd wait for @aurelienpierre to chime in.

**Comment by johnny-bit** [comment]
I think #9137 is sensible approach.

**Comment by aurelienpierre** [comment]
Meh. Better find the culprit than disable the optimization. I don't like when we hide shit like that. I will have a look to the OpenCL in the next days.
