### ISSUE TITLE
Cannot start Darktable 3.4.1 on MacOS 11.4

### ISSUE THREAD

**Issue by tmab2003** [darktable-org/darktable#9147]
I have to delete darktablerc in ~/.config/darktable/ if I want darktable to launch successfully. I am not sure what is causing this to happen in my darktablerc.

Please let me know what information I can provide to help debug this issue.

https://pastebin.com/GHFjEFYc here is the current darktablerc.

**Comment by tmab2003** [comment]
FYI: terminal output:

./darktable    

(process:7065): GLib-GObject-CRITICAL **: 16:40:21.343: g_object_set: assertion 'G_IS_OBJECT (object)' failed

But this line shows up even on a good launch, I think.

**Comment by MStraeten** [comment]
run darktable with debugging output:
`darktable -d all`
to get an idea what’s the last successful step

**Comment by tmab2003** [comment]
```
./darktable -d all
0.001134 application_directory: /Applications/darktable.app/Contents/MacOS
0.001232 darktable.datadir: /Applications/darktable.app/Contents/Resources/share/darktable
0.001273 darktable.plugindir: /Applications/darktable.app/Contents/Resources/lib/darktable
0.001308 darktable.localedir: /Applications/darktable.app/Contents/Resources/share/locale
0.001347 darktable.configdir: /Users/name/.config/darktable
0.001376 darktable.cachedir: /Users/name/.cache/darktable
0.001408 darktable.sharedir: /Applications/darktable.app/Contents/Resources/share
0.001451 darktable.tmpdir: /private/var/folders/g0/4270kf6n5tv_z6lng77x1hj80000gn/T
[memory] at startup
[memory] max address space (vmpeak):         unknown
[memory] cur address space (vmsize):      8732612 kB
[memory] max used memory   (vmhwm ):         unknown
[memory] cur used memory   (vmrss ):        52960 kB
0.001807 new_xdg_data_dirs: (null)

(process:28761): GLib-GObject-CRITICAL **: 19:07:06.197: g_object_set: assertion 'G_IS_OBJECT (object)' failed
0.104154 [init sql] library: /Users/name/.config/darktable/library.db, data: /Users/name/.config/darktable/data.db
129.501321 [crawler] `/Volumes/507_Nas/Photography/iPhone Photos/IMG_0115.JPG' (id: 13424) is missing.
131.194220 [crawler] `/Volumes/507_Nas/Photography/iPhone Photos/IMG_0205.JPG' (id: 13489) is missing.


```

The process is still running...so is it just the crawler running still?

**Comment by tmab2003** [comment]
Ok a few more prints came up showing some more images missing. The UI should definitely load and show me some sort of progress bar to show how it is doing with looking for the updated XMP files.

**Comment by MStraeten** [comment]
the initialization stuff is made before loading the UI. This makes sense since you can run darktable as a commandline application without a GUI.

**Comment by tmab2003** [comment]
Is there a way to force scan for updated xmp for a collection of images within Darktable then? If the scan for updated xmp at startup is taking so long for a large collection, it might be necessary for me to just scan selected files.

**Comment by johnny-bit** [comment]
It seems like you have huge collection or slow (eg network) drive which can impact performance.

Can you change the title of the issue to reflect the problem - that scanning for updated xmps on start takes ages? And I think thish should be an fr - currently you can eitehr totally disable or totally enable scanning for updated xmps on startup. You'd like to force update consciously in GUI and probably as a background job so it won't interfere with normal ui operation?
