### ISSUE TITLE
Focusing or defocusing darktable briefly freezes X server (i3 wm)

### ISSUE THREAD

**Issue by dllu** [darktable-org/darktable#9148]
**Describe the bug/issue**

When focusing or defocusing darktable on i3 window manager (either by using the keyboard, or by moving the mouse cursor in or out of the window), the X server has extreme lag and freezes for about half a second, during which the mouse cursor becomes unresponsive.

**To Reproduce**

1. Run darktable with i3 window manager (I suspect the problem also happens on other window managers but I don't have any installed at the moment)
2. Open any file
3. move mouse cursor into darktable or out of darktable
4. observe the huge lag spikes of the mouse cursor

In `htop` I can see that the `Xorg` process uses 100% of one CPU core for a brief period while the lag  spike happens.

In `~/.local/share/xorg/Xorg.0.log` there are logs resembling the following:

```
[193495.635] (EE) event23 - SINOWEALTH Wired Gaming Mouse: client bug: event processing lagging behind by 24ms, your system is too slow
[193496.135] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193496.352] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193539.679] (EE) event23 - SINOWEALTH Wired Gaming Mouse: client bug: event processing lagging behind by 18ms, your system is too slow
[193539.679] (EE) event23 - SINOWEALTH Wired Gaming Mouse: WARNING: log rate limit exceeded (5 msgs per 60min). Discarding future messages.
[193559.142] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193560.046] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193566.243] (EE) client bug: timer event23 debounce short: scheduled expiry is in the past (-4ms), your system is too slow
[193569.826] (EE) client bug: timer event23 debounce short: scheduled expiry is in the past (-0ms), your system is too slow
[193587.929] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193590.644] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193591.350] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193592.176] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193592.918] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193594.125] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193594.125] (II) event23 - SINOWEALTH Wired Gaming Mouse: WARNING: log rate limit exceeded (5 msgs per 30s). Discarding future messages.
[193622.060] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193626.536] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193630.180] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
[193638.056] (II) event23 - SINOWEALTH Wired Gaming Mouse: SYN_DROPPED event - some input events have been lost.
```

although the `your system is too slow` is rather implausible and frankly a bit insulting since I have a beastly computer (see specs in the platform section)

This problem cannot be reproduced with any other program that I have (I have tried several GTK apps like GIMP and Inkscape and none have this problem). Also the problem only seems to hapen in darkroom mode and not lighttable mode. 

My guess is that Darktable has some event processing bug where it accumulates many events when the window is defocused.

**Expected behavior**

Darktable should not freeze the entire X server for half a second when focusing or defocusing it.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.5.0+2429~gf684738d13
* OS                : 5.12.7-arch1-1
* Linux - Distro    : Arch Linux
* Memory            :  64 GB
* Graphics card     : NVIDIA GeForce RTX 3090
* Graphics driver   : nvidia 465.31
* OpenCL installed  : OpenCL 3.0 CUDA 11.3.116
* OpenCL activated  : 
* Xorg              : 1.20.11-1
* Desktop           : i3 4.19.2-1 (no compositor)
* GTK+              : 1:3.24.29-1
* gcc               : 11.1.0
* cflags            : 
* CMAKE_BUILD_TYPE  : 

```
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version  3.4.1**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) n/a
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by wilecoyote2015** [comment]
I cannot reproduce this on Arch Linux...
I have an Intel Xe integrated GPU, using kernel driver. 
Tried without compositor as well as picom with glx backend

**Comment by dllu** [comment]
Can you try to reproduce it with an Nvidia GPU? The lag is really bothering me and I can reproduce it on my machine every time. It makes it nearly impossible to use Darktable. Furthermore it seems that typing in the module search bar has serious lag issues, especially with the debouncer, so what I type gets duplicated quite often (e.g. trying to type "perspective" results in "pperspective") with the following logs in `~/.local/share/xorg/Xorg.0.log`:

```
[   288.274] (EE) client bug: timer event23 debounce: scheduled expiry is in the past (-141ms), your system is too slow
[   288.274] (EE) client bug: timer event23 debounce short: scheduled expiry is in the past (-154ms), your system is too slow
[   291.996] (EE) event2  - USB Keyboard: client bug: event processing lagging behind by 199ms, your system is too slow
```

I am at my wits' end how to solve this. I have a huge backlog of photos that I cannot process as a result. This problem really seems to affect _only_ Darktable, and only in the dark room mode, and no other application on my machine.

**Comment by dllu** [comment]
Hmm I ran `sudo perf report -p $(pgrep "Xorg")` while moving my mouse in and out of the Darktable window and then `sudo perf report` reveals that the Xorg high CPU usage is indeed due to `nvidia` drivers:

![image](https://user-images.githubusercontent.com/14482624/120909797-accee400-c62d-11eb-9966-db9355f095d2.png)

But the question remains why Darktable is the only applicaiton that is causing a serious problem, and why the problem exists even on my extremely powerful hardware. Is it perhaps spamming some redraws on focus?

**Comment by ptilopteri** [comment]
I have used dt for many years with nvidia w/o experiencing anything like your description.

**Comment by dllu** [comment]
I have also used darktable but only noticed the problem recently. Perhaps it is caused by a recent kernel or nvidia driver version?

**Comment by jenshannoschwalm** [comment]
Do you use other apps that use opencl at all? Try 'darktable -d opencl' to see if there is something wrong on dt side but this sounds very much like a driver install issue.

**Comment by dllu** [comment]
I don't think it's a problem with OpenCL. `clinfo` and `clpeak` work as expected, and here's the output from `darktable -d opencl`:

[opencl.log](https://github.com/darktable-org/darktable/files/6605018/opencl.log)

I don't think it is a driver install issue either since all my CUDA apps work perfectly, as well as some extremely demanding games (such as Metro Exodus with RTX raytracing, which runs natively on Linux).

**Comment by dllu** [comment]
Upon further investigation it seems that my previous profiling run had a bug in it and I reran it (and updated the screenshot in my previous comment), revealing high usage of `libpixman-1.so`.

I have discovered, when googling, that setting `nvidia-settings -a InitialPixmapPlacement=0` greatly reduces the lag spike when focusing and defocusing Darktable (the original setting was `InitialPixmapPlacement=2`). However with `InitialPixmapPlacement=0`, Xorg continues to suffer extremely high CPU usage due to `nvidia_drv.so` when focusing Darktable, and general performance seems quite a bit more sluggish despite not having any serious spikes.

**Comment by jenshannoschwalm** [comment]
I remember (from years ago) such issues with  `InitialPixmapPlacement` setting difficulties, this is clearly a problem of your distro & nvidia driver configuration or somethin you did with configuring gtk. Not a dt issue at all. Please concider to close this github issue as this is about dt bugs/issues

**Comment by dllu** [comment]
I am pretty sure there is some inefficiency or bug that is in darktable that is causing this. The problem seems to affect exclusively darktable. No other GTK app has this problem. For example, GIMP with a 50 megapixel image loaded is perfectly smooth, and so are Blender, Libreoffice, Firefox, etc. As I mentioned, the GPU is also working perfectly in highly intensive games and compute situations.

Probably darktable is doing some spurious redrawing on focus or using an inefficient render path. As I recall, there are many pitfalls with cairo/pixman that can lead to slow performance and I recall that darktable uses cairo/pixman extensively.

**Comment by ptilopteri** [comment]
also quite odd that the problem as described appears to be unique to
*only* your system.  I don't see it even on my 10 yer old i7/nv G04

**Comment by johnny-bit** [comment]
On irc channel there's been discussion about this issue and interestingly enough there are people using i3 with less beefy specs and do not experience the issue you're experiencing.

Have you tried other wms and do they also exhibit issue for you? new drivers? updated bios? have you tried nvidia forums (https://forums.developer.nvidia.com/c/gpu-graphics/linux/148) and/or i3 issues (https://github.com/i3/i3/issues)/forums?

**Comment by dllu** [comment]
> have you tried other wms

I just tried it in OpenBox, it seems to be better than i3, but the issue is still present and `~/.local/share/xorg/Xorg.1.log` shows that there are some missed events. It seems somewhat usable but the lag is still noticeable.

> less beefy specs

This is clearly a weird bug rather than a specs issue. It is quite possible that it only affects RTX 3000 series graphics cards due to some nvidia bug. Or perhaps it is some combination of the latest nvidia drivers not working properly with the latest linux kernel 5.12. Not sure though.

> new drivers

As you can see in the original issue, I always use the latest nvidia drivers, which are currently at 465.31. I also use the latest kernel (5.12.12 right now). I just updated the bios just now (bios 4002 for my asus prime x570-p) and it did not fix the problem either.

I guess I could try the i3 forums and nvidia forums...

> Another thing may be the fact that grading icon in module groups is a bit hefty draw, but that shouldn't be much of a problem if you're not in darkroom.

As explained in the original issue, the problem only manifests in the darkroom mode. But I highly doubt that drawing an icon will cause this sort of lag. How is the grading icon drawn anyway? I couldn't find it in `darktable/data/pixmaps`.

**Comment by johnny-bit** [comment]
The icons are actually in `src/dtgtk/paint.c` because they're drawn IN CODE rather than pixmap :)

Please check issue https://github.com/darktable-org/darktable/issues/6522 then and try workaround specified there - eg chage icons for modulegroups

If that does fix your issue then this issue is essentially a duplicate of https://github.com/darktable-org/darktable/issues/6522 :)

as I mentioned in https://github.com/darktable-org/darktable/issues/6522#issuecomment-745513748 my guess that proper workaround would be to "simply" create and use cache for icons. It wasn't normally necessary but it seems that it could minimize performance impact of icon drawing when icon is not nice with pixman ;)

**Comment by dllu** [comment]
> Please check issue #6522 then and try workaround specified there - eg chage icons for modulegroups

omg that fixed it!!!!!!!!!!!!!!!1 You're the best! I changed the grading and effect icons to the `dtgtk_cairo_paint_modulegroup_correct` icon and it works smoothly now.

![hooray](https://purplepuppy.com/puphooray.png)

I think that pixman has some serious performance issues with nvidia but that will be outside the scope of darktable ;) 

I guess I can close this issue as a duplicate now.
