### ISSUE TITLE
Ctrl+Alt does not scroll left sidebar when mouse pointer is over expanded module

### ISSUE THREAD

**Issue by Konzertheld** [darktable-org/darktable#9149]
**Describe the bug/issue**
With the option "mouse wheel scrolls modules" deactivated, regarding the option's description, ctrl+alt+mouse wheel should scroll the module list up and down. It does for the right sidebar. It only kinda does for the left:
- scrolling with ctrl+alt when on a module title, it works as expected, the module list scrolls up and down
- scrolling with ctrl+alt when on a module's content does nothing, except
- scrolling with ctrl+alt when on the "collect photos" module's roll list extends the length of that module, on the filter textbox it scrolls the module list
- scrolling with only ctrl on the "collect photos" module's roll list also extends the length of the module, on the filter textbox it does nothing

In addition,
- ctrl+alt scrolling on the tag list in the right sidebar also extends that module's length without scrolling the module list, while scrolling on modules' contents in the right sidebar works as expected

**To Reproduce**
No additional prerequisites

**Expected behavior**
The left sidebar should also scroll the module list up and down when using the mouse wheel with ctrl+alt.

**Platform**
* darktable version : 3.4.1
* OS                : Linux Kernel 5.9.16-1-MANJARO
* Linux - Distro    : Manjaro
* Memory            : 16 GB
* Graphics card     : Radeon RX 570 8 GB
* Graphics driver   : open source
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : no Wayland
* Desktop           : Gnome

**Additional context**
- issue persists when config dir is removed
- tested in lighttable and darkroom

**Comment by dterrahe** [comment]
Quite a bit of work was done in the upcoming 4.6 to correctly deal with (combinations of) modifiers keys pressed (thanks @ralfbrown!). It would be great if you could test with master if this resolves this issue for you. If not, please test after release of 4.6 and close this bug if it works.

There is a remaining, separate, issue that scrolling while the mouse is in a box that has a scrollbar, _only_ the box tries to scroll, even when it has reached its end. It would be nice if then it switches to scrolling the _panel_, so the cursor doesn't get "caught" by boxes like that. But I have not found a way to do this.

**Comment by johnny-bit** [comment]
I'd consider the issue fixed in current master :)

Closing - see the new release comming in 2 weeks :) 3.6 will have new bug fixes (and bugs)

**Comment by Konzertheld** [comment]
I can confirm that the issue is fixed in 3.6. Thanks! :)
