### ISSUE TITLE
WIN10: darktable does not find database because path separators / \ get mixed up

### ISSUE THREAD

**Issue by infjb** [darktable-org/darktable#9151]
With MSYS2 compiled darktable complains about not finding the database.

$ /opt/darktable/bin/darktable
ERROR : cannot open database
[init] database `C:\Users\frank\AppData\Local\darktable/data.db' couldn't be opened. aborting

The path contains \ and / which can not work.

I compiled darktable the last time in January. Everything worked fine than. I reinstalles MSYS2 an all prerequisites according to the instructions for Windows 10.The outcome is the same. 

You can reproduce it by following this instructions step by step:
https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.md

Edition	Windows 10 Pro
Version	21H1
Installiert am	‎06.‎09.‎2020
Betriebssystembuild	19043.1023
Leistung	Windows Feature Experience Pack 120.2212.2020.0

The MSYS2 installation is from the day before yesterday with all updates from today.

Sadly I don't have the binary from January any more and the database has a newer format than the release version can read.

**Comment by ptilopteri** [comment]
until someone with much more window/darktable knowledge than I 
solves this for you, you can start dt from the control-line by specifying
the location of the library:
darktable --library "C:\Users\frank\AppData\Local\darktable\data.db"

I am assuming that is possible in windows.

**Comment by johnny-bit** [comment]
This is weird. Both `/` and `\` should work essentially the same in paths.

Can you check if path is read-and-write? and no antivir or anything interferes?

**Comment by infjb** [comment]
The path is readable and writeable:

frank@WORKMATE MINGW64 ~/devel/darktable/build
$ ll "C:\Users\frank\AppData\Local\darktable\data.db"
-rw-r--r-- 1 frank Kein 2097152 May  2 03:04 'C:\Users\frank\AppData\Local\darktable\data.db'

frank@WORKMATE MINGW64 ~/devel/darktable/build
$ ll -d "C:\Users\frank\AppData\Local\darktable"
drwxr-xr-x 1 frank Kein 0 Jun  4 17:44 'C:\Users\frank\AppData\Local\darktable'

frank@WORKMATE MINGW64 ~/devel/darktable/build
$ ll -d "C:\Users\frank\AppData\Local"
drwxr-xr-x 1 frank Kein 0 Jun  4 02:59 'C:\Users\frank\AppData\Local'

frank@WORKMATE MINGW64 ~/devel/darktable/build
$ ll -d "C:\Users\frank\AppData"
drwxr-xr-x 1 frank Kein 0 Sep  6  2020 'C:\Users\frank\AppData'

frank@WORKMATE MINGW64 ~/devel/darktable/build
$ ll -d "C:\Users\frank"
drwxr-xr-x 1 frank Kein 0 May 31 23:11 'C:\Users\frank'

frank@WORKMATE MINGW64 ~/devel/darktable/build
$ ll -d "C:\Users"
drwxr-xr-x 1 frank Kein 0 Sep  6  2020 'C:\Users'


The Microsoft Defender is the only installed antivir.


"C:\Program Files\darktable\bin\darktable.exe" --library "C:\Users\frank\AppData\Local\darktable\data.db" results in a crash:

this is darktable 3.5.0+2438~g941122872 reporting an exception:

-------------------

Error occurred on Friday, June 4, 2021 at 18:14:33.

darktable.exe caused an Access Violation at location 00007FFFAB7F021E in module libdarktable.dll Writing to location 0000000000000000.

AddrPC           Params
00007FFFAB7F021E 000002A907FC7FE0 000002A900000001 000002A906771F80  libdarktable.dll!dt_database_show_error
00007FFFAB7E3A2E 00007FF800000001 000002A907FBB360 00007FF800000001  libdarktable.dll!dt_init
00007FF663512A69 00007FF663511670 0000000000000010 0000000000000000  darktable.exe!0x7ff600002a69
00007FF6635115C5 000000000000005E 0000000000000002 00007FF6635170A0  darktable.exe!0x7ff6000015c5
00007FF6635113E4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff6000013e4
00007FF663511516 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff600001516
00007FF81D377034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FF81E102651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.5.0.2438
ntdll.dll   	10.0.19041.1023
KERNEL32.DLL	10.0.19041.1023
KERNELBASE.dll	10.0.19041.1023
msvcrt.dll  	7.0.19041.546
libintl-8.dll	0.19.8.0
ADVAPI32.dll	10.0.19041.610
sechost.dll 	10.0.19041.906
RPCRT4.dll  	10.0.19041.1023
libglib-2.0-0.dll	2.68.2.0
ole32.dll   	10.0.19041.746
ucrtbase.dll	10.0.19041.789
combase.dll 	10.0.19041.928
GDI32.dll   	10.0.19041.746
win32u.dll  	10.0.19041.1023
gdi32full.dll	10.0.19041.928
msvcp_win.dll	10.0.19041.789
USER32.dll  	10.0.19041.906
SHELL32.dll 	10.0.19041.1023
WS2_32.dll  	10.0.19041.546
libiconv-2.dll	1.16.0.0
libwinpthread-1.dll	1.0.0.0
libdarktable.dll
PSAPI.DLL   	10.0.19041.546
libpcre-1.dll
libcairo-2.dll
exchndl.dll 	0.9.2.0
libgdk-3-0.dll	3.24.29.0
IMM32.dll   	10.0.19041.546
SETUPAPI.dll	10.0.19041.844
cfgmgr32.dll	10.0.19041.546
bcrypt.dll  	10.0.19041.1023
libgdk_pixbuf-2.0-0.dll	2.42.4.0
libgio-2.0-0.dll	2.68.2.0
SHLWAPI.dll 	10.0.19041.1023
libgobject-2.0-0.dll	2.68.2.0
libgtk-3-0.dll	3.24.29.0
comdlg32.dll	10.0.19041.906
shcore.dll  	10.0.19041.1023
libharfbuzz-0.dll
libpango-1.0-0.dll	1.48.5.0
libpangocairo-1.0-0.dll	1.48.5.0
zlib1.dll
libgcc_s_seh-1.dll
libstdc++-6.dll
libavif.dll
libgomp-1.dll
libcurl-4.dll
CRYPT32.dll 	10.0.19041.844
WLDAP32.dll 	10.0.19041.546
libgmodule-2.0-0.dll	2.68.2.0
libexiv2.dll
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libicuuc68.dll
libicuin68.dll
libIlmImf-2_5.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
libopenjp2-7.dll
libpugixml.dll	1.11.0.0
libpng16-16.dll
librsvg-2-2.dll
libsoup-2.4-1.dll
libsecret-1-0.dll
libsqlite3-0.dll
libxml2-2.dll
libtiff-5.dll
libfontconfig-1.dll
MSIMG32.dll 	10.0.19041.546
libpixman-1-0.dll
libfreetype-6.dll	2.10.4.0
mgwhelp.dll 	0.9.2.0
dwmapi.dll  	10.0.19041.746
VERSION.dll 	10.0.19041.546
libepoxy-0.dll
libcairo-gobject-2.dll
libfribidi-0.dll
WINMM.dll   	10.0.19041.546
libpangowin32-1.0-0.dll	1.48.5.0
gdiplus.dll 	10.0.19041.1023
IPHLPAPI.DLL	10.0.19041.546
DNSAPI.dll  	10.0.19041.1023
COMCTL32.dll	6.10.19041.844
libffi-7.dll
WINSPOOL.DRV	10.0.19041.1023
libatk-1.0-0.dll	2.36.0.0
USP10.dll   	10.0.19041.546
libpangoft2-1.0-0.dll	1.48.5.0
libgraphite2.dll
libthai-0.dll
libaom.dll
rav1e.dll
libdav1d.dll	5.1.0.0
libbrotlidec.dll
libidn2-0.dll
libcrypto-1_1-x64.dll	1.1.1.11
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.11
libzstd.dll
libexpat-1.dll
libltdl-7.dll
libexif-12.dll
libsystre-0.dll
libicudt68.dll
libbz2-1.dll
libIex-2_5.dll
libHalf-2_5.dll
libIlmThread-2_5.dll
libImath-2_5.dll
USERENV.dll 	10.0.19041.572
libgcrypt-20.dll	1.9.2.0
liblzma-5.dll	5.2.5.0
libdeflate.dll
libwebp-7.dll
libjbig-0.dll
dbghelp.dll 	10.0.19041.867
libunistring-2.dll	0.9.10.0
libbrotlicommon.dll
libdatrie-1.dll
libtre-5.dll
CRYPTBASE.DLL	10.0.19041.546
libgpg-error-0.dll	1.42.0.0
dbgcore.DLL 	10.0.19041.789
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.546
bcryptPrimitives.dll	10.0.19041.1023
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.1023
Wldp.dll    	10.0.19041.662
kernel.appcore.dll	10.0.19041.546
uxtheme.dll 	10.0.19041.746
OLEAUT32.dll	10.0.19041.985
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.1023
profapi.dll 	10.0.19041.844
mswsock.dll 	10.0.19041.546
DEVOBJ.dll  	10.0.19041.546
MSCTF.dll   	10.0.19041.964
WINTRUST.dll	10.0.19041.804
MSASN1.dll  	10.0.19041.546
Wintab32.dll	1.0.5.9
HID.DLL     	10.0.19041.546
WTSAPI32.dll	10.0.19041.546
MPR.dll     	10.0.19041.546
Pen_Tablet.dll	5.3.5.3
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.1023
winhttp.dll 	10.0.19041.1023
TextShaping.dll
textinputframework.dll	10.0.19041.1023
CoreMessaging.dll	10.0.19041.746
CoreUIComponents.dll	10.0.19041.546
wintypes.dll	10.0.19041.928
ntmarta.dll 	10.0.19041.546
Oleacc.dll  	7.2.19041.746
AppXDeploymentClient.dll	10.0.19041.1023
Windows.ApplicationModel.dll	10.0.19041.746
twinapi.appcore.dll	10.0.19041.964
Windows.FileExplorer.Common.dll	10.0.19041.867
iertutil.dll	11.0.19041.1023
mssprxy.dll 	7.0.19041.1023
mrmcorer.dll	10.0.19041.1023
windows.staterepositorycore.dll	10.0.19041.844
bcp47mrm.dll	10.0.19041.867
Windows.UI.dll	10.0.19041.746
InputHost.dll	10.0.19041.906
WindowManagementAPI.dll

Windows 10.0.19043
DrMingw 0.9.2

**Comment by infjb** [comment]
Darktable works if I delete / rename my database. I'm suspecting a bad database upgrade.

**Comment by johnny-bit** [comment]
you should have backups/snapshots made by darktable (i introduced the snapshots in dt 3.4). DB upgrade should never cause non-working db and since the devs are running them all the time it's very much tested code.

If it is working with new db - would you like to close the issue and with closed issue we could investigate if the file is recoverable if necessary.

**Comment by infjb** [comment]
The second last snapshot was usable and got upgrade without any trouble.
