### ISSUE TITLE
Allow easier access to adjust hue and chroma from colour calibration in quick access panel

### ISSUE THREAD

**Issue by Yardlongbean** [darktable-org/darktable#9158]
In darktable 3.5.0+2159~g22aba1f90 I have set up 
I have set up 'Illuminant, hue and chroma' to be accessible from the quick access panel.
My default illuminant is 'as shot in camera'. With this setting, the hue and chroma sliders are not present, as expected.
However, if I change the illuminant to 'custom', the hue and chroma sliders are still hidden:
![image](https://user-images.githubusercontent.com/41417273/120881631-685e2c80-c5ca-11eb-8ee0-18dfcf0ba732.png)

It would be great, if changing the illuminant from the quick access panel made the hue and chroma sliders appear. At present, you need to go to the actual calibration tool to make this happen, so it defeats the purpose of having this tool on the quick access panel.

I appreciate that this might not be a simple fix, but just thought I would point it out.

**Comment by dterrahe** [comment]
Could you please confirm if #12404 solved this for you and close this issue if it does or provide more information if there are still remaining problems. Thanks!

**Comment by Yardlongbean** [comment]
Many thanks for your work on this. I will try it out in a weekly build when I get a chance and feed back to you.

**Comment by Yardlongbean** [comment]
I can confirm that having tried weekly insider build 4.1 for Windows 70da6dcc8 this works perfectly now, it is great to have a functioning colour calibration in the quick access panel. Many thanks for your work.

**Comment by Yardlongbean** [comment]
Thanks!
