### ISSUE TITLE
metadata - height of entries

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#9159]
**Describe the bug/issue**

The height of entries in metadata view is too small by default which means that the scrollbars are always visible.

**To Reproduce**

1. Go to lighttable
2. Expand metadata editor

A somewhat recent regression.

**Expected behavior**

No scrollbar.

**Screenshots**

![image](https://user-images.githubusercontent.com/467069/120883987-b9791b00-c5e0-11eb-8357-1157c5508915.png)

**Platform**

* darktable version : current master
* OS                : Linux

**Comment by TurboGit** [comment]
@Nilvus : I think this is a regression due to a recent change in CSS, can you have a look ? TIA.

**Comment by Nilvus** [comment]
@TurboGit: a simple one. 

The fix is just by removing line 320 (padding setting). Is it ok for you to post the commit (it's a simple line to update and would avoid a PR to check and merge)?

**Comment by TurboGit** [comment]
Sure I'll do and post a PR for you to review.

**Comment by TurboGit** [comment]
Fixes works for me,  see #9161.

**Comment by Nilvus** [comment]
Ok, I was thinking about merging the commit directly to do it quickly. Thanks, it's all good!
