### ISSUE TITLE
New blending layers mode

### ISSUE THREAD

**Issue by age1988** [darktable-org/darktable#9160]
Is it possible to add a value+saturation and lightness+chroma blend mode?
Basically this copies the hue from the bottom layer

**Comment by johnny-bit** [comment]
Sooo... a dedicated blending mode to prevent hue shifts?

@hlecleme - what do you think?

**Comment by RawConvert** [comment]
Is this for masks?  @age1988 , could you say a little more about where this happens and why it's good pls?
