### ISSUE TITLE
darktable 3.8 Lua roadmap

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#9165]
This is the current plan for the Lua API for darktable 3.8.

* **Move to Lua 5.4.x** Replace Lua 5.3 with Lua 5.4.  This is planned for early in 3.7 so that there is plenty of time for testing.  I have it currently running in 3.5 without issue, but it hasn't undergone much testing.
*  **Lua API test suite** Develop a test suite to validate the API is working correctly.  Integrate the test suite with CI for automated checks and problem detection.
* **API code cleanup** Improve code readability and add more comments documenting how the code works.
* **Continue script deactivation work** Finish adding the capability to turn a script off without having to restart darktable.
  * lib destruction
  * guides destruction
  * filter destruction
* **Integrate with new input system** Integrate with #8078

**Comment by wpferguson** [comment]
Lua 5.4 upgrade PR submitted, #9299

**Comment by TurboGit** [comment]
@wpferguson : This should be closed now that move to Lua 5.4 is done. Rigth?
