### ISSUE TITLE
Changing date in geotagging module gives weird results

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#9174]
**Introduction**
see title

**Describe the bug/issue**
Changing date/time in geotagging module behaves somewhat weird.
Changing time is ok, I can enter any valid value and this is shown in the input field.
Changing date is different:
- changing year seems to be ok, but 
- when changing month or day the input value is not accepted and 
- when changing month the year jumps to another value

**Expected behavior**
Entering a figure in one of the fields should not affect other values of the date/time-string

**Screencast**
https://www.bilddateien.de/github/darktable-issue-9174.mp4

**Platform**
```
darktable version : 3.5.0+2458~g33deb6bb1
System:
  Kernel: 4.19.0-16-amd64 x86_64 bits: 64 compiler: gcc 
  v: 8.3.0 Desktop: Cinnamon 3.8.8 Distro: Debian GNU/Linux 10 (buster) 
Machine:
  Type: Desktop Mobo: ASUSTeK model: P8Z77-M v: Rev 1.xx serial: <filter> 
  UEFI: American Megatrends v: 2203 date: 12/18/2015 
CPU:
  Topology: Quad Core model: Intel Core i5-3570 bits: 64 type: MCP 
  arch: Ivy Bridge rev: 9 L2 cache: 6144 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 27280 
  Speed: 3714 MHz min/max: 1600/3800 MHz Core speeds (MHz): 1: 3661 2: 3640 
  3: 3663 4: 3636 
Graphics:
  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics 
  vendor: ASUSTeK P8H77-I driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ivybridge Desktop v: 4.2 Mesa 18.3.6 
  direct render: Yes 
```

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts?
   - What lua scripts start automatically? none
   - What lua scripts were running when the bug occurred? none
- also checked with `3.5.0+2330~g4fb67a1a1` and 
  - clean profile
  - some images in a clean folder with no xmp
  
  same behavior

**Comment by ralfbrown** [comment]
Confirmed.  I saw this behavior a couple of weeks ago when I set a date for a TIFF that didn't have any ExIF data, but didn't get around to reporting it.

There's some mod-12 action on the month value; you can't directly enter a value of 9..12, but if the second digit you type yields a value > 12, the actual entry changes to the typed amount mod 12 (after which one can fix the year).

**Comment by phweyland** [comment]
yep, mktime is used to recalculate the date/time when the field under/overflows by scrolling, but some values entered directly lead to the same correction, which not desired.
I'll try to find a fix on this.

**Comment by bilddateien** [comment]
> EDIT: meantime, (shift-)scrolling over the fields to change the value works correctly.

can confirm this - but didn't know about this feature.
