### ISSUE TITLE
Adjusting singlebuffer_limit does not allow 0 or negative

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9176]
**Describe the bug/issue**
According to the tooltip, setting 0 or negative values should be possible:

> if set to a positive, non-zero value this variable defines the minimum amount of memory (in MB) that tiling should take for a single image buffer. has precedence over heuristics based on host_memory_limit

However, since it's marked with a minimum value of 2, it cannot actually be set (on the UI) to 0:
```
<type min="2" max="64">int</type>
```
https://github.com/darktable-org/darktable/blob/5047749c15d0418ed0503a7e9db62413eae3a8e5/data/darktableconfig.xml.in#L199_L203

According to the code, however, overriding only occurs if it's set to a value higher than the heuristics yield:
```
we ignore the above value if singlebuffer_limit (is defined and) is higher than available/tiling.factor.
this will mainly allow tiling for modules with high and "unpredictable" memory demand which is
reflected in high values of tiling.factor (take bilateral noise reduction as an example).
```
https://github.com/darktable-org/darktable/blob/e8cb2cb1d9a2b34a4bbe27278247dae0ff09c3c8/src/develop/tiling.c#L620_L627

**To Reproduce**
1. Open settings
2. Try to set 0 or negative value
3. Press TAB
4. Minimum value of 2 is restored

**Expected behavior**
Not quite sure, since it only overrides the heuristics-based value if higher than that. Change wording of tooltip to match the logic or vice versa?
'If set to a higher value than that calculated using host_memory_limit, overrides the calculated value; otherwise, has no effect.'
Of course the user won't really know how that value is calculated and what value was calculated.

**Screencast**
![config](https://user-images.githubusercontent.com/3177739/120925038-e60f5e80-c6d6-11eb-87e0-6e9eaa2b9521.gif)

**Which commit introduced the error**
According to git blame, this has been like this for 7-8 years :-D

**Comment by johnny-bit** [comment]
Actually it became simply minimum tilling mem. The calculation is simple: if `mem amount` / `factor` is lower than `singlebuffer_limit` - use `singlebuffer_limit`, otherwise use `mem amount` / `factor`

So imo the tooltip should read:

> minimum amount of memory (in MB) that tiling should take for a single image buffer.
