### ISSUE TITLE
Allow minimum number of images on the map function to be reduced to the image currently being worked on.

### ISSUE THREAD

**Issue by jbinpg** [darktable-org/darktable#9182]
Current minimum number of images rendered on the map is ten. I often would like this to be just the image being worked on.

It would be great if the number of rendered images could be set to one.

I am not expecting to this to be handled before the 3.6 release.

**Comment by Nilvus** [comment]
@phweyland: what's your view on that? The comment is not completely clear for me but I think @jbinpg  talks about max images setting in 3.4/actual master @jbinpg: it's always good to precise which darktable version you use).

**Comment by jbinpg** [comment]
No, Nicholas, I meant minimum number of images. I am on current git. You can see what I mean by trying to set the map to only show the current image - it can't bne done.

**Comment by Nilvus** [comment]
> No, Nicholas, I meant minimum number of images. I am on current git. You can see what I mean by trying to set the map to only show the current image - it can't bne done.

It's Nicolas (I'm French). I don't understand the purpose (that's not the goal I think of map module) but I will let other people discussed that and especially @phweyland as he works and improved a lot map part recently.

**Comment by phweyland** [comment]
Trying to understand...
when you say one image,  do you mean one group or cluster of images (one thumbnail whatever the number of images)?

**Comment by jbinpg** [comment]
Sorry for the misspelling, Nicolas. Yes, I wish the map would only show the location of the selected image currently being worked on. As it is now, in Map Settings, setting max images to 1 resets to 10 as soon as you click away from the setting, even if you set group size factor and min images per group to 1. If you frequently visit a location over many years, you end up with a jumble of locations placed atop one another making it difficult to see the actual location.

**Comment by jbinpg** [comment]
Thanks. I will try the available controls. Closing this now.
