### ISSUE TITLE
Set filmicrgb default mid-tones saturation level in preferences

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9183]
**Is your feature request related to a problem? Please describe.**
Some users prefer a more saturated, more out-of-camera look when they open an image in the darkroom. Others prefer to tune colours manually. Currently, not to scare new users away, filmic boosts mid-tone saturation, even though this is not the preferred way. If one needs to use e.g. color balance RGB to control saturation, first this value has to be set to 0 manually. This is what @aurelienpierre discusses here: https://discuss.pixls.us/t/proposal-for-a-linear-highlight-roll-off-tonemapping/25128/18

**Describe the solution you'd like**
By adding an option in preferences to set the initial value of the mid-tone saturation slider, both groups could be catered for. darktable could ship with a default preference value of 10% (mirroring the current filmic RGB default); more advanced users could set this to 0.

**Alternatives**
- Advanced users may create a preset for filmic RGB; however, this disables setting the the black and white points automatically (see https://discuss.pixls.us/t/proposal-for-a-linear-highlight-roll-off-tonemapping/25128/16)
- Partial module presets have been mentioned, but do not currently exist.

**Comment by elstoc** [comment]
I'd prefer if we could find a more generic solution to allow defaults to be altered for individual module parameters, or a way to force that (black/white) auto-calculation to be done in presets. Perhaps something similar to the "compensate camera exposure" in the exposure module.

The ideal long-term solution would be something like "partial presets" - e.g. to be able to create a preset that uses the default module parameters but just overrides one of them.

**Comment by aurelienpierre** [comment]
Partial presets is a can of worms, too many heuristics. Better set filmic saturation to 0% for everybody and have color balance RGB enabled by default with some extra chroma.

**Comment by johnny-bit** [comment]
How about this: 

currently in processing there's pixel workflow - display or scene referred
in chromatic adaptation - it's legacy or modern
then there's auto applying per-camera basecurve and sharpen

There's plenty of space there for "chroma boost" setting if necessary :) 

But yeah - the color balance rgb chroma boost looks super nice compared to filmic mid-tone saturation boost so it could be the default (but then more modules became enabled by default). Having option to Disable chroma boost would in ideal world mean "I did read the manual, yes, thank you, I know what I'm doing, really." :)

**Comment by aurelienpierre** [comment]
@TurboGit your thoughts ?

**Comment by elstoc** [comment]
Is this the only setting in filmic that you'd recommend be used differently to the defaults? I'm thinking, for example, of "safe" mode.

**Comment by kofa73** [comment]
@aurelienpierre, I thought previously somewhere you said that increasing chroma is more likely to push colours out of gamut than raising saturation. Do I remember wrong? If not, wouldn't **saturation** be a safer choice than to 'have color balance RGB enabled by default with some extra **chroma**'? Or even global vibrance, which pushes less saturated colours more?

**Comment by aurelienpierre** [comment]
> @aurelienpierre, I thought previously somewhere you said that increasing chroma is more likely to push colours out of gamut than raising saturation. Do I remember wrong? If not, wouldn't saturation be a safer choice than to 'have color balance RGB enabled by default with some extra chroma'? Or even global vibrance, which pushes less saturated colours more?

Yes, but color balance RGB is fully gamut-mapped at the output, so whatever you do in the module (vibrance, chroma, saturation, color shifts, hues shifts) is fixed before injecting the result back in the pipeline. And all that happens at constant hue, which is not the case of the filmic desaturation, which algo was developed for desaturation rather than re-saturation.

> Generally though if we think that saturation is better done by default in color balance rgb just do it there. Is there a need for another preference for this?

It is better, yes. The need for a preference is the whole discussion, I guess.

**Comment by elstoc** [comment]
Sorry just to be explicit here: I believe another preference is not required if we are sure it's an improvement.

**Comment by rawfiner** [comment]
I also think another preference is not required, better have midtone saturation at 0 by default in filmic and color balance rgb enabled by default with some increase of chroma. If needed, filmic midtones saturation slider could be reversed and with soft bounds to become a "midtones desaturation" with values starting at 0, to encourage the user to use color balance rgb instead

**Comment by kofa73** [comment]
Or maybe consider the saturation slider legacy, and hide it by default, like it happened to filmic's mid-grey slider? If color balance rgb is enabled by default (given that its role is properly documented), it should be fairly obvious for users to go there to tweak chroma / saturation / vibrance.

**Comment by TurboGit** [comment]
I agree, let's avoid a new preference. I would just set mid-tone saturation to 0 in filmic.

If people need more saturation by default they can create an auto-preset with color balance or whatever and apply it. I would not apply by default a color balance in the code. We have never search to have a good out-of-camera kind of look in dt, this goes in the same direction.

**Comment by aurelienpierre** [comment]
Ok, so let's change the default to 0 now, we will see for the rest later.

**Comment by aurelienpierre** [comment]
53b35b25861b6b0022cf79f520ae991aaa80a7dc

**Comment by elstoc** [comment]
We should probably put those recommendations into the user manual (and the blog post) if we're not going to auto-apply them.

**Comment by johnny-bit** [comment]
@elstoc - Yes, please. That would be wonderful.

**Comment by aurelienpierre** [comment]
It's just a rough sketch for now

**Comment by kofa73** [comment]
> We should probably put those recommendations into the user manual (and the blog post) if we're not going to auto-apply them.

How about adding such recommended module settings (or, if multiple modules are involved, styles) on GitHub in a contrib directory, just like for LUA scripts? There's also dtstyle.net, but:
- it only handles styles (not individual module presets)
- there are simply too many styles there
- has no search facility as far as I know
- it's not possible to link to any specific entry, unless I'm mistaken.

On the other hand, the contrib entries could be linked from the manual, people could download and use them if they wish.

**Comment by TurboGit** [comment]
Just remember that we are in bug fix only mode at this stage. So all this should wait for 3.8, as there is no bug in sight !
