### ISSUE TITLE
darkroom: preview of duplicate shows only a section of image

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#9198]
**Describe the bug/issue**
When in darkroom view with an image with multiple versions, using the "duplicate manger" to "preview" another version shows only the top left corner of that version.

**To Reproduce**
1. Select a newly imported raw file in lighttable view
2. Enter darkroom view
3. Expand `duplicate manager` in left panel
4. Click `duplicate`
5. In duplicate manager, click on the original image (identified by "0")
6. Center view shows the top left corner of that image

_alternate_

1. Import a raw file
2. Select the image in lighttable view
3. In right panel, click `selected image[s]` -> `duplicate`
4. Select the first of the duplicates and enter darkroom view
5. Expand `duplicate manager` in left panel
6. Click on the second image (identified by "1")
7. Center view shows the top left corner of that image

**Expected behavior**
Should show all of the image as a "preview" in the center view. Possibly preceded by a "working..." overlay then pause while the other image is being loaded/processed.

**Which commit introduced the error**

29f459e78f9113b70be4ac5133a9b6bb6cd93669 keep final sizes up to date

**Platform**

* darktable version : 3.5.0+2493~g4097c761f
* OS                : Linux - kernel 5.10.40
* Linux - Distro    : Debian/testing
* Memory            : 32GB
* Graphics card     : Nvidia Quadro P4000 Mobile
* Graphics driver   : Nvidia 460.84
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 7.7
* Desktop           : Gnome 3.38.5
* GTK+              : 3.24.24
* gcc               : 11.0.1
* CMAKE_BUILD_TYPE  : Release

**Additional context**

Switching to the duplicate and waiting a moment will "fix" this behavior. Perhaps the error results from a mipmap cache which isn't loaded?

Sometimes on clicking to preview a duplicate, the center view flashes white then the preview of the duplicate is shown.

Even when things work, the duplicate preview is slightly (1-2 pixels) less wide/high than the non-preview image, when it is shown in the center view.

 - Can you reproduce with another darktable version(s)? **see bisect above**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format** (perhaps JPEGs process too fast to show this problem?)
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **can reproduce without scripts**
 - Are you using a hidpi display? **yes**

When bisecting I also saw crashes when clicking `duplicate` in a few more recent commits: 246694209824113483eebf7828e7aba7b402476a and c90260a977b91acf43f6f600e047149c5edd99e9. It seems that crash has been fixed in current code, though.

**Comment by elstoc** [comment]
Yes I noticed this too.

**Comment by AlicVB** [comment]
> Even when things work, the duplicate preview is slightly (1-2 pixels) less wide/high than the non-preview image, when it is shown in the center view.

Let's first answer the easy part : this behavior id "normal"... well we should better say that it's a known issue ;)
It's due to how the preview is computed compared to the "real" image. We have tried many things to solve it but we only manage to leverage a bit the issue, not to fix it :(

For the rest of your issue, I don't manage to reproduce...
- You say that waiting a bit a moment "fix" it. What does that mean exactly ? does it mean that if you keep the mouse pressed longer enough on the thumbnail, the preview get it's normal size/position ?
- You have a hdpi screen... by any chance, are you able to test on a "normal" screen ?

**Comment by dtorop** [comment]
@AlicVB: Thanks for looking at this!

> You say that waiting a bit a moment "fix" it. What does that mean exactly ? does it mean that if you keep the mouse pressed longer enough on the thumbnail, the preview get it's normal size/position ?

Here's a better write-up:

1. Follow setup steps above (clean conf, load image into darkroom view, etc.).
2. Click "duplicate" in the "duplicate manager".
3. Darkroom view now shows the new duplicate (version 1)
4. Clicking on version 0 shows a preview of the top-left 1/4 of version 0
5. Keeping the mouse pressed doesn't "fix" it -- the 1/4 image remains for as long as I hold down the mouse button.
6. If I release the mouse button then press the mouse button again, this behavior repeats (1/4 image shown)
7. Double-click on version 0 to switch to it.
8. Clicking on version 1 shows a preview of the entire image (not top-left 1/4). The image is too light (see below).
9. Double-click on version 1 to switch to it.
10. Clicking on version 0 shows a preview of the entire image (not top-left 1/4), but the image is too light.

This is with a single RAF raw file newly imported (no edit history).

> You have a hdpi screen... by any chance, are you able to test on a "normal" screen ?

Tested with `GDK_SCALE=1`. The 1/4 image preview problem goes away.

If I shut down darktable then restart and edit version 0, when I click on the v1 preview, the center view window flashes white then shows the full image preview. If I release the mouse then click the v1 preview again, I see the full image preview without the white flash.

With `GDK_SCALE=2` or no `GDK_SCALE` set (and a hidpi display), the 1/4 image preview is visible.

Regarding the too light preview problem, here are two ways to avoid seeing it (regardless of `GDK_SCALE`):

1. Open a raw file without an edit history, adjust its exposure, make a duplicate, then click to preview the original image.
2. Set `plugins/lighttable/thumbnail_raw_min_level` to `always`.

So perhaps there are two bugs?

1. A missing dpi_factor somewhere in the code path of previewing a duplicate.
2. For a raw image without edit history, it would be better to avoid showing the embedded JPEG as a duplicate preview, but force processing from the raw file.

>> the duplicate preview is slightly (1-2 pixels) less wide/high than the non-preview image
> this behavior id "normal"... well we should better say that it's a known issue ;)

Good to know! I think at one point the preview image was also shown at low resolution on a hidpi screen. That seems fixed now. It makes sense that this would be tricky...

**Comment by AlicVB** [comment]
@dtorop : I think I got it... see #9024 Can you confirm that it fix the issue on your side too ? (I don't own an hdpi screen, so I've just changed GDK_SCALE to mimic that)

It's great that you manage to bisect the issue ! otherwise I'm not sure that I would have the idea to look for there... Even now, I'm still unsure how the fix can be related to hdpi only...

**Comment by AlicVB** [comment]
>     2\. For a raw image without edit history, it would be better to avoid showing the embedded JPEG as a duplicate preview, but force processing from the raw file.

that may have some unwanted implications, as what we use here is the same thumbnail cache which is used for lighttable (culling and preview, especially) So user that don't want it may have a sudden image change when zooming in the image...
I don't say it's bad, just that we have to do it carefully (and not for 3.6)

In fact, if you want my opinion, I would love to find a way to speedup a little thumbnail generation, so we can remove completely the embedded jpeg use. imo the only advantage of using them is that they are quicker to load (here ~x4) but they have lot of drawbacks, confusing users about the rendering for example...

**Comment by elstoc** [comment]
I prefer to see the jpeg in the lighttable before I've started processing and it would be a shame to remove it.

**Comment by dtorop** [comment]
>  I think I got it...

Yes from here! #9204 fixes this for me.

**Comment by dtorop** [comment]
>> raw image without edit history, it would be better to avoid showing the embedded JPEG

It's definitely a corner case, as generally previewing via the duplicate manager is there to compare edit histories.

> and not for 3.6

Yes!

> I prefer to see the jpeg in the lighttable before I've started processing and it would be a shame to remove it.

I guess, if thumbnail generation became faster, `plugins/lighttable/thumbnail_raw_min_level` could default to `always` in order not to confuse new users between the JPEG and the processed raw file. Default scene-referred processing provides for legible images. But via conf, more experienced users could choose `never` to see the JPEG.

But that's a different issue... It could be good (for now) not to touch the lighttable thumbnail behavior. But for v3.8 to think about having a different behavior for the duplicate manager: always preview via the processed raw, as we're now in darkroom mode and that's what we'll see when double-clicking that version. Plus in darkroom mode users may be OK with a slight "working..." pause before the initially preview loads. Is the code is flexible enough to allow for different behaviors between the two views, though?

**Comment by elstoc** [comment]
yes agreed it makes sense to process the raw once an image has been loaded in the darkroom

**Comment by TurboGit** [comment]
Just a note that I cannot reproduce the original issue. As I didn't found issue with the fix I'll merge.
