### ISSUE TITLE
zoom does not focus position of mouse cursor but upper left corner

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9206]
**Describe the bug/issue**
When I am in culling fixed mode with 1 image, under certain conditions the zoom with `Ctrl+wheel` will not zoom to the position of the mouse but instead into the upper left corner of the image.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to culling fixed and open a picture that you have not zoomed in previously!
2. Press and hold Ctrl and scroll your mouse wheel.

How it does **not** reproduce:
* If you zoomed into the image previously. It only works once per image!
* If you zoom too slow. I need to scroll multiple levels at once for the zoom to fail. If I zoom in real slow, it works fine.

**Expected behavior**
* Zoom should always be focused on the mouse location.

**Platform**
* Manjaro Linux
* 3.5.0+2493~g4097c761f1
* OpenCL installed  :  yes
* OpenCL activated  :  yes

**Comment by Solarer** [comment]
When I say "works once per image" that includes reboots. You need to remove the image from the catalog and reimport it for the effect to reoccur once.

**Comment by AlicVB** [comment]
@Solarer : That's an interesting information.
Once an image has been zoomed, can you reproduce if you just remove the cache, or does it need a full reimport ?
In the second case, that would (again) point to the "real" size things...

**Comment by Solarer** [comment]
What command should I use to clear the cache?

**Comment by AlicVB** [comment]
you need to remove (backup first) the cache directory. For me it's located at `~/.cache/darktable`

**Comment by AlicVB** [comment]
ok, thanks for the test. At first sight that would (again) point to "real" size computation... I'll try to test soon...

**Comment by AlicVB** [comment]
OK, I think I got it : this is exactly the same issue as #9207 except that in this case the effect is worst due to the "real" full size computation...
