### ISSUE TITLE
Perspective module: cannot set the automatic cropping value untile some perspective correction is set

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#9214]
If I try to set automatic cropping to some value which is not off before changing the rotation, lens shift, etc. values, I get an error message on the image "automatic cropping failed".

**Comment by Nilvus** [comment]
Which darktable version do you use? Think about precise that (and for some, other infos like OS, etc.) on each issue (as asked on bug report explanation). Thanks.

**Comment by paolobenve** [comment]
3.4.1 on ubuntu. And I could verify that the bug is present in 3.5.0, compiled on my pc

**Comment by AlicVB** [comment]
confirmed. This seems to happen if the module is not enabled before the change.

As said in your other issue, perspective and crop & rotate will certainly see some big changes for 3.8...
