### ISSUE TITLE
Rawspeed submodule update breaks recognition of correct noise profile

### ISSUE THREAD

**Issue by tduell** [darktable-org/darktable#9221]
**Introduction**
_
---------------------------------------------------------------
release-3.5.0-2516-g859a6adf8 which included RawSpeed submodule update: major BitStream rewrite and noted * Pentax K-3 Mark III camera support. Fixes #8991
in fact causes a disconnect between Pentax K-3 Mark III images and the correct noise profile data.
Prior to this release the noise profile data for the Pentax K-3 Mark III was being correctly recognised.

**Describe the bug/issue**
Images from the Pentax K-3 Mark III do not have access to the profiled denoise data for the camera.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. load images from the Pentax K-3 Mark III
2. view image in darkroom
3. select module 'denoise (profiled)'
4 only generic poissonian is available

**Expected behavior**
the module would note the profiled denoise for the image ISO was found

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
in release-3.5.0-2516-g859a6adf8 and looks like commit 6751588efdea336b83c2df2a1485a888f328b756

_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : release-3.5.0-2516-g859a6adf8
* OS                : 
* Linux - Distro    : Fedora 34
* Memory            : 16 GB
* Graphics card     : Nvidia Geforce GTX 750Ti
* Graphics driver   : open source supplied by Fedora
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 
* Desktop           : Cinnamon
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 -  No. release-3.5.0-2510-g1c60f3532 behaved as expected, ie found the appropriate profiled denoise for the image ISO
 - 
 - Can you reproduce with a RAW or Jpeg or both?  RAW-file-format
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) No
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts? no
   - What lua scripts start automatically? 
   - What lua scripts were running when the bug occurred?

**Comment by johnny-bit** [comment]
Fixed by #9220

**Comment by johnny-bit** [comment]
the #9220 got merged so I think this can be closed :) if there's still issue, please ping me and I'll reopen.
