### ISSUE TITLE
OnePlus 6 embedded matrice colour is off

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#9223]
It seems the embedded matrice isn't giving the right colour.
!
[IMG_20210609_102647.zip](https://github.com/darktable-org/darktable/files/6638304/IMG_20210609_102647.zip)
[IMG_20210611_130134.zip](https://github.com/darktable-org/darktable/files/6638291/IMG_20210611_130134.zip)

**Comment by kmilos** [comment]
FWIW, found a few more cases on RPU where there is no D65 calibration in smartphone DNGs, and they put the higher D55 in set1: Google Pixel 3a, Samsung S10, a couple Xiaomis, a Realme... So I guess there indeed might be a case for the DNG profile parsing overhaul? @jenshannoschwalm @johnny-bit

**Comment by johnny-bit** [comment]
DNG is can of worms?

eg: scanner DNGs are not raws but we can't be sure (https://github.com/darktable-org/darktable/pull/7129)
there's an FR for "cleaner DNG": https://github.com/darktable-org/darktable/issues/3591
dual pixel raws are a thing too: https://github.com/darktable-org/darktable/issues/4006
then lightroom embeds data and doesn't use XMP files when dealing with DNGs: https://github.com/darktable-org/darktable/issues/5992
there's this "cool" lens shading map feature: https://github.com/darktable-org/darktable/issues/8728
then there's the issue of weirdo make/model being read from dngs by noise tools: https://github.com/darktable-org/darktable/issues/8992

:P yeah. there MIGHT be a case for dng profileparsing overhaul :P

**Comment by jenshannoschwalm** [comment]
> DNG is can of worms?

Maybe. Unfortunately the standard is pretty clear for most cases but there is lot's of software in firmware or scanners that write "non-standard" files. My ideas about an "overhaul"

- many parts of the "cleaner" dng stuff has been integrated already
- dual pixels, first problem is implementing black point correction in rawspeed, we need more than 4 for those images.

**But** this illumination thing should be fixed for 3.8 First problem for me would be how to interpolate between the matrices ...
