### ISSUE TITLE
Access Violation in libglib-2.0-0.dll

### ISSUE THREAD

**Issue by yuri1969** [darktable-org/darktable#9224]
**Introduction**

**Describe the bug/issue**
Darktable 3.4.1.1 crashes during startup under Windows 10. It finishes loading one or two JPEG shots from the library and then crashes.

**To Reproduce**
1. Start Darktable

**Expected behavior**
To load start with loaded JPEG library.

**Platform**
* darktable version : 3.4.1.1
* OS                : Win10 19042
* Memory            :  4GB
* Graphics card     : Intel

[darktable_bt_ECRT40.txt](https://github.com/darktable-org/darktable/files/6640540/darktable_bt_ECRT40.txt)

**Comment by Nilvus** [comment]
Please provide more infos on precise steps to reproduce. It could be not related directly to darktable. We don't had other reports about crashes by just loading one or 2 JPG. So without any more information, it will be hard to reproduce and help.
By the way, 4GB of RAM is most of the times not recommended for any photo processing (for all photo software). Having 8Gb at least is recommended.

Crash report doesn't rely to opencl but did you have opencl enabled? It's quite buggy with Intel graphics card. Could you test by adding `--disable-opencl` to darktable.exe command path (right-click to darktable shortcut then properties). Please report here if you reprouce with that tag added (or not). If you don't reproduce, consider closing this issue as we can't do anything about buggy drivers. If you reproduce, please the more precise as possible (step by step).

**Comment by johnny-bit** [comment]
Tested on Win10 update 21H1 & dt 3.4.1.1 

loaded up 100+ 24MPix JPEGs, browsed all, no crash.
exported them - still no crash

Ram: 8GB
GraphicsCard: AMD

Can you describe EXACTLY what steps you took which resulted in crash? Have you tried with empty config/db?

**Comment by yuri1969** [comment]
Thank you for the feedback. I will report back as soon as I can get access to that particular Windows-based machine.

**Comment by yuri1969** [comment]
After forcing the `--disable-opencl` the problem seems to be gone. So Intel's OpenCL driver might be the culprit. Cheers!

**Comment by johnny-bit** [comment]
Cool, thanks for the info! We've seen couple times that "broken" drivers can lead to all kinds of weird errors.
