### ISSUE TITLE
darktable crashes while importing my images

### ISSUE THREAD

**Issue by glide007** [darktable-org/darktable#9228]
darktable crashes while importing my images, it has crashed twice so far, posting the trrace

this is darktable 3.4.0 reporting an exception:

-------------------

Error occurred on Saturday, June 12, 2021 at 20:55:26.

darktable.exe caused an Access Violation at location 00007FFD10F8D2F1 in module msvcrt.dll Reading from location 0000000000000000.

AddrPC           Params
00007FFD10F8D2F1 000000001C5028D0 0000000000000002 00000000FFFFFFFF  msvcrt.dll!strlen
00000000652057F7 00000000636C2B30 00007FFCECACC056 000000006520EC98  libcollect.dll!tree_count_show
0000000065207362 0000000003A9E500 0000000000000003 0000000000000000  libcollect.dll!tree_count_show
0000000000D64921 00000000652075E0 0000000000000000 000000000061F310  libffi-7.dll!ffi_prep_go_closure
0000000000D6456E 0000000000000000 000000000061F9B0 0000000000000005  libffi-7.dll!ffi_closure_free
0000000000D64732 000000000061F2D0 000000006638ECA3 0000000003C04598  libffi-7.dll!ffi_call
00007FFD01A6739A 0000000014A6BC00 0000000000000000 0000000000000004  libgobject-2.0-0.dll!g_cclosure_marshal_generic
00007FFD01A66BA9 0000000000E00000 00007FFD11BD47B1 00000000664A3210  libgobject-2.0-0.dll!g_closure_invoke
00007FFD01A78189 0000000003C01F40 00007FFC00000000 0000000003A9E500  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFD01A7D151 0000000000000050 00007FFD01A84026 0000000003B87F20  libgobject-2.0-0.dll!g_signal_emitv
00000000636C2B50 00007FFD01AA7238 0000000063981840 00000000026EB7B0  libdarktable.dll!dt_control_progress_cancellable
00007FFCECACC056 00000000027A7000 00007FFD10F49C45 0000000000000006  libglib-2.0-0.dll!g_main_context_invoke_full
00007FFCECACC1EA 0000000000000006 0000000000000002 0000000000000000  libglib-2.0-0.dll!g_main_context_invoke
00000000636C3151 0000000003C11C90 00007FFD00000001 0000000000000003  libdarktable.dll!dt_control_signal_raise
00000000635DBC64 0000000000000004 00000000001502EE 00000000168049A0  libdarktable.dll!dt_collection_new
00007FFD01A66BA9 0000000014032020 00007FFD06E45930 0000000000000002  libgobject-2.0-0.dll!g_closure_invoke
00007FFD01A78189 0000000003C034B0 0000000000000000 0000000003A9E500  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFD01A7D151 0000011705107E86 00000000027058A0 0000000000000000  libgobject-2.0-0.dll!g_signal_emitv
00000000636C2B50 00000000026F51B0 00007FFCECACA98D 0000000000000000  libdarktable.dll!dt_control_progress_cancellable
00007FFCECAC7B1F 0000000000000002 00000000167AACB0 00000000167AACB0  libglib-2.0-0.dll!g_clear_list
00007FFCECACADA6 0000000000000001 00000000026ED8E0 00000000026F6980  libglib-2.0-0.dll!g_main_context_check
00007FFCECACB2CC 0000000000000000 0000000000000000 00000000639FD0A0  libglib-2.0-0.dll!g_main_loop_run
00007FFCB27D272D 0000000000000000 0000000000402720 00000000026F68F0  libgtk-3-0.dll!gtk_main
00000000637FA96C 00007FFD00000001 00000000026ED8E0 00007FFD00000001  libdarktable.dll!dt_gui_gtk_run
0000000000402AAC 0000000000401670 0000000000000010 0000000000000000  darktable.exe!0x2aac
00000000004015C5 000000000000005A 0000000000000000 00000000004070A0  darktable.exe!0x15c5
00000000004013E4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x13e4
0000000000401516 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x1516
00007FFD11387034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFD11C02651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.4.0.0
ntdll.dll   	10.0.19041.1023
KERNEL32.DLL	10.0.19041.1023
KERNELBASE.dll	10.0.19041.1023
msvcrt.dll  	7.0.19041.546
libintl-8.dll	0.19.8.0
ADVAPI32.dll	10.0.19041.1052
sechost.dll 	10.0.19041.906
RPCRT4.dll  	10.0.19041.1052
libglib-2.0-0.dll	2.66.3.0
ole32.dll   	10.0.19041.746
ucrtbase.dll	10.0.19041.789
combase.dll 	10.0.19041.1052
GDI32.dll   	10.0.19041.746
win32u.dll  	10.0.19041.1052
gdi32full.dll	10.0.19041.928
msvcp_win.dll	10.0.19041.789
USER32.dll  	10.0.19041.906
SHELL32.dll 	10.0.19041.1023
WS2_32.dll  	10.0.19041.546
libdarktable.dll
PSAPI.DLL   	10.0.19041.546
libiconv-2.dll	1.16.0.0
libwinpthread-1.dll	1.0.0.0
libpcre-1.dll
libgcc_s_seh-1.dll
libgomp-1.dll
libstdc++-6.dll
libavif.dll
libcurl-4.dll
CRYPT32.dll 	10.0.19041.844
WLDAP32.dll 	10.0.19041.546
libcairo-2.dll
exchndl.dll 	0.9.2.0
libexiv2.dll
libgdk-3-0.dll	3.24.24.0
libgdk_pixbuf-2.0-0.dll	2.42.0.0
IMM32.dll   	10.0.19041.546
SETUPAPI.dll	10.0.19041.844
cfgmgr32.dll	10.0.19041.546
bcrypt.dll  	10.0.19041.1023
libgmodule-2.0-0.dll	2.66.3.0
libgobject-2.0-0.dll	2.66.3.0
libgio-2.0-0.dll	2.66.3.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libharfbuzz-0.dll
libgtk-3-0.dll	3.24.24.0
comdlg32.dll	10.0.19041.906
shcore.dll  	10.0.19041.1023
SHLWAPI.dll 	10.0.19041.1023
libIlmImf-2_5.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
lua53.dll
liblcms2-2.dll
libpangocairo-1.0-0.dll	1.48.0.0
libpango-1.0-0.dll	1.48.0.0
libpng16-16.dll
libpugixml.dll	1.11.0.0
librsvg-2-2.dll
libsecret-1-0.dll
libsoup-2.4-1.dll
libsqlite3-0.dll
libtiff-5.dll
libxml2-2.dll
zlib1.dll
libaom.dll
rav1e.dll
libdav1d.dll	4.0.2.0
libbrotlidec.dll
libidn2-0.dll
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.9
MSIMG32.dll 	10.0.19041.546
libzstd.dll
libfontconfig-1.dll
libfreetype-6.dll	2.10.4.0
libcrypto-1_1-x64.dll	1.1.1.9
VERSION.dll 	10.0.19041.546
libpixman-1-0.dll
dwmapi.dll  	10.0.19041.746
gdiplus.dll 	10.0.19041.1023
WINMM.dll   	10.0.19041.546
mgwhelp.dll 	0.9.2.0
libexpat-1.dll
libcairo-gobject-2.dll
libepoxy-0.dll
libfribidi-0.dll
DNSAPI.dll  	10.0.19041.1023
IPHLPAPI.DLL	10.0.19041.546
libpangowin32-1.0-0.dll	1.48.0.0
libexif-12.dll
USP10.dll   	10.0.19041.546
COMCTL32.dll	6.10.19041.1052
WINSPOOL.DRV	10.0.19041.1023
libbz2-1.dll
libgraphite2.dll
libatk-1.0-0.dll	2.36.0.0
libpangoft2-1.0-0.dll	1.48.0.0
libHalf-2_5.dll
libIlmThread-2_5.dll
libIex-2_5.dll
USERENV.dll 	10.0.19041.572
libImath-2_5.dll
libgcrypt-20.dll	1.8.7.13461
liblzma-5.dll	5.2.5.0
libbrotlicommon.dll
dbghelp.dll 	10.0.19041.867
libunistring-2.dll	0.9.10.0
dbgcore.DLL 	10.0.19041.789
CRYPTBASE.DLL	10.0.19041.546
libgpg-error-0.dll	1.39.0.0
libopenjp2-7.dll
libffi-7.dll
libsystre-0.dll
libltdl-7.dll
libthai-0.dll
libdatrie-1.dll
libtre-5.dll
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.1052
bcryptPrimitives.dll	10.0.19041.1023
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.1023
Wldp.dll    	10.0.19041.662
kernel.appcore.dll	10.0.19041.546
uxtheme.dll 	10.0.19041.746
OLEAUT32.dll	10.0.19041.985
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.1023
profapi.dll 	10.0.19041.844
mswsock.dll 	10.0.19041.546
MSCTF.dll   	10.0.19041.964
DEVOBJ.dll  	10.0.19041.546
WINTRUST.dll	10.0.19041.1052
MSASN1.dll  	10.0.19041.546
OpenCL.dll  	2.2.1.0
amdocl64.dll	10.0.3075.13
OPENGL32.dll	10.0.19041.928
GLU32.dll   	10.0.19041.844
atiadlxx.dll	27.20.11044.5003
atig6txx.dll	27.20.11044.5003
amdocl12cl64.dll	0.8.0.0
amd_comgr.dll
winhttp.dll 	10.0.19041.1023
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.1023
libpixbufloader-png.dll
mscms.dll   	10.0.19041.746
ColorAdapterClient.dll	10.0.19041.546
icm32.dll   	10.0.19041.546
textinputframework.dll	10.0.19041.1023
CoreUIComponents.dll	10.0.19041.546
CoreMessaging.dll	10.0.19041.746
ntmarta.dll 	10.0.19041.546
wintypes.dll	10.0.19041.1052
libdarkroom.dll
libknight.dll
liblighttable.dll
libmap.dll
libosmgpsmap-1.0-1.dll
libslideshow.dll
libtethering.dll
libavif.dll
libcopy.dll
libexr.dll
libj2k.dll
libjpeg.dll
libpdf.dll
libpfm.dll
libpng.dll
libppm.dll
libtiff.dll
libwebp.dll
libwebp-7.dll
libxcf.dll
libdisk.dll
libemail.dll
libgallery.dll
liblatex.dll
libpiwigo.dll
libashift.dll
libatrous.dll
libbasecurve.dll
libbasicadj.dll
libbilat.dll
libbilateral.dll
libbloom.dll
libborders.dll
libcacorrect.dll
libchannelmixer.dll
libchannelmixerrgb.dll
libclahe.dll
libclipping.dll
libcolisa.dll
libcolorbalance.dll
libcolorchecker.dll
libcolorcontrast.dll
libcolorcorrection.dll
libcolorin.dll
libcolorize.dll
libcolormapping.dll
libcolorout.dll
libcolorreconstruct.dll
libcolortransfer.dll
libcolorzones.dll
libdefringe.dll
libdemosaic.dll
libdenoiseprofile.dll
libdither.dll
libequalizer.dll
libexposure.dll
libfilmic.dll
libfilmicrgb.dll
libfinalscale.dll
libflip.dll
libgamma.dll
libglobaltonemap.dll
libgraduatednd.dll
libgrain.dll
libhazeremoval.dll
libhighlights.dll
libhighpass.dll
libhotpixels.dll
libinvert.dll
liblens.dll
liblensfun.dll
liblevels.dll
libliquify.dll
liblowlight.dll
liblowpass.dll
liblut3d.dll
libmask_manager.dll
libmonochrome.dll
libnegadoctor.dll
libnlmeans.dll
liboverexposed.dll
libprofile_gamma.dll
librawdenoise.dll
librawoverexposed.dll
librawprepare.dll
librelight.dll
libretouch.dll
librgbcurve.dll
librgblevels.dll
librotatepixels.dll
libscalepixels.dll
libshadhi.dll
libsharpen.dll
libsoften.dll
libsplittoning.dll
libspots.dll
libtemperature.dll
libtonecurve.dll
libtoneequal.dll
libtonemap.dll
libvelvia.dll
libvibrance.dll
libvignette.dll
libwatermark.dll
libzonesystem.dll
libbackgroundjobs.dll
libcamera.dll
libcollect.dll
libcolorlabels.dll
libcolorpicker.dll
libcopy_history.dll
libdarktable_label.dll
libduplicate.dll
libexport.dll
libfilmstrip.dll
libfilter.dll
libgeotagging.dll
libglobal_toolbox.dll
libhinter.dll
libhistogram.dll
libhistory.dll
libimage.dll
libimage_infos.dll
libimport.dll
libioporder.dll
liblighttable_mode.dll
liblive_view.dll
liblocation.dll
libmap_locations.dll
libmap_settings.dll
libmasks.dll
libmetadata.dll
libmetadata_view.dll
libmodulegroups.dll
libmodule_toolbox.dll
libnavigation.dll
libratings.dll
librecentcollect.dll
libselect.dll
libsession.dll
libsnapshots.dll
libstyles.dll
libtagging.dll
libtimeline.dll
libviewswitcher.dll
libview_toolbox.dll
libpixbufloader-svg.dll
explorerframe.dll	10.0.19041.1023
TextShaping.dll

Windows 10.0.19043
DrMingw 0.9.2

**Comment by ptilopteri** [comment]
dt version 3.4.1.1 is available.  have you tried it to see if your problem
as already been fixed?

**Comment by glide007** [comment]
Let me give it a try

**Comment by glide007** [comment]
I am not getting error after upgrade.

Cheers

**Comment by ptilopteri** [comment]
then, please consider closing this issue.
tks
