### ISSUE TITLE
Strange artifacts and image not updated after processing

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#9242]
**Describe the bug/issue**
2 issues with colorbalance rgb since last update (can't reproduce on 859a6adf8212be1e0c7de1ef6130631801fa73f2, posted 4 days ago)

**To Reproduce**

Not so easy to explain but I can have issues easily when setting colorbalance rgb (see screenshot below) and when I go back to lighttable, image displayed is not updated correctly with latest changes. Those issues only happen with Opencl activated. I can't reproduce with Opencl disabled. So seems to be related to Opencl code of colorbalancergb.

**Expected behavior**
Have same behavior with opencl like without opencl, so no issues on image and image processed updated directly when go back to lighttable.

**Screenshots**

![2021-06-14_22-35](https://user-images.githubusercontent.com/45535283/121956362-91ac5480-cd50-11eb-936e-b76405b272a8.png)

**Which commit introduced the error**
Quite probably colorbalance rgb fix added yesterday, so probably #9227

@aurelienpierre: I'm not sure if you will need more precise steps but it's not so easy to explain. I could reproduce with different settings AND have same settings tried on same image at different times that do not display artifacts first time and display them the other time. It's just seems related to Opencl. Maybe an update you forgot on Opencl code in #9227?

**Platform**

* darktable version : 3.5.0+2540~g0e44925d0
* OS                : Linux Ubuntu 21.04
* Graphics card     : Intel Irix Xe
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by Nilvus** [comment]
@aurelienpierre: I'm quite surprised as I can't reproduce now on my side, even on that image. I have tried and restarted 3 or 4 times and reproduce each time. And now I don't have reproduced. I don't know why. I so close it but maybe you will see sometimes here, so if you want more infos, you're of course welcomed. Thanks.

**Comment by aurelienpierre** [comment]
That looks a lot like negative RGB or even NaN.

**Comment by Nilvus** [comment]
> That looks a lot like negative RGB or even NaN.

Ok, but how I have that with your last fix but not before? And how we can avoid that? And why only with OpenCL?

**Comment by aurelienpierre** [comment]
Well, I will need a much narrower reproducer to get a hint of what happens. Right now, it can be anything. 

Then, CPU and OpenCL don't use the same optimizations at compilation time, so it's perfectly possible that the error is silently handled on CPU. Or it could be a code discrepancy. Or possibly a mix of both.

So… yeah… narrower reproducer please :D

**Comment by Nilvus** [comment]
Ok, I will try to post one... if possible.

**Comment by Nilvus** [comment]
Maybe it could help but with that RAW and XMP, just increasing global chroma in colorbalance rgb make grey artifacts appears (and image in lighttable is different than in darkroom). Only with Opencl enabled.

https://acloud.zaclys.com/index.php/s/sp7dZoctdECne6w

**Comment by aurelienpierre** [comment]
I don't reproduce on Nvidia…

**Comment by Mark-64** [comment]
Can't reproduce with latest git and provided file on Windows 10, nVidia GPU

**Comment by Nilvus** [comment]
> I don't reproduce on Nvidia…
> 
> Edit: neither on Intel(R) HD Graphics P630. What is your OpenCL driver ?

I use Intel OpenCL Neo drivers for Linux, from this repository: https://github.com/intel/compute-runtime
