### ISSUE TITLE
more than a single processing module stays open when using search

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9251]
**Describe the bug/issue**
In darkroom the search modules field does not respect the setting "expand a single processing module at a time".
Setting this to true should close all open modules but one, once a new module is expanded. This does not work as expected when opening modules from the search result list.

**To Reproduce**
1. Activate the setting: "expand a single processing module at a time"
2. Go to darkroom
3. Search for "color" in the modules - this should return a long list of potential modules.
4. Expand some of the modules - they will all stay open.

**Expected behavior**
Only a single module should be expanded from the search results IF "expand a single processing module at a time" has been set to true.

**Platform**

* darktable version : 3.5.0+2526~gb3a4335e57
* OS                : Manjaro Linux

**Comment by johnny-bit** [comment]
@AlicVB - Search of modules is part of module groups... what do you think about this issue?
