### ISSUE TITLE
documentation: Imported images are *not* stored in the library database

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9252]
**Which new feature or section need to be documented/updated**
https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/collections/

> All images imported into darktable are stored in darktable’s library database, along with attributes describing each image. 

This sentence suggests that the images (data) are stored in the database, in addition to metadata (_'along with attributes')_.

How about something like
_'Information (such as path and EXIF details, as well as the processing history stack) about imported images are stored in darktable's library database.'_

**Comment by Nilvus** [comment]
@kofa73: for all documentation proposals or issues, please post them on dtdocs github repository, not here: https://github.com/darktable-org/dtdocs

I so close this one as documentation is now no more integrated in darktable repository but has it's own one. Thanks!
