### ISSUE TITLE
Database not protected against malformed Exif timestamps.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#9254]
**Introduction**
Darktable's "date taken" collection, the bottom-bar timeline, _etc._, assume that all images in the database have a timestamp in the [standard Exif format](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/datetimeoriginal.html) `YYYY:MM:DD hh:mm:ss`.
However, the database itself will allow any string for a timestamp, and the import process does not protect against files created by cameras that do not write their timestamps exactly in the required format.

**To Reproduce**
1. Import the two attached files, [`red.jpg`](https://user-images.githubusercontent.com/3303477/122164485-7dde1c80-ce3c-11eb-8688-de476de10469.jpg) and [`green.jpg`](https://user-images.githubusercontent.com/3303477/122164371-55562280-ce3c-11eb-88a0-32c7a52adac3.jpg). `red.jpg` contains an Exif header taken from an image created by an off-brand camera phone, which wrote its dates in the format `YYYY/MM/DD hh:mm:ss`. `green.jpg` has the same header but with the timestamps changed to the standard format.
2. Select the "date taken" collection.
3. Note the malformed date entry appearing in the module's tree view (see attached screenshot).
4. Note that only `green.jpg` shows up in the bottom-bar timeline.

**Expected behavior**
Darktable should take steps to normalize all timestamps on import, or at the very least filter out the malformed ones instead of writing them straight to the database.

**Screenshots**
![CollectByDateError](https://user-images.githubusercontent.com/3303477/122164567-9d754500-ce3c-11eb-9caf-21ec7201ee15.png)

**Platform**
* darktable version : 3.5.0+2550-g876c71575

**Comment by kmilos** [comment]
Wouldn't call HTC an off-brand, but a no-no from them in any case ;) Thanks for reporting.

It would be great if you could confirm whether the proposed PR fixes it for you.

**Comment by schwerdf** [comment]
The pull request fixes it for these specific photos, but does not resolve the broader problem of allowing malformed timestamps into the database when other parts of Darktable are assuming that all timestamps in the database are well-formed.

The Exif standard mandates the `YYYY:MM:DD hh:mm:ss` format for timestamp tags, but the Exif data representation allows these tags to be assigned any string whatsoever. In order to meet the assumptions Darktable is making, if any image's timestamp tag does not adhere to the proper Exif format, and is not normalized by the `_sanitize_datetime` function, the image should be treated the same as an image with no timestamp tag, thus keeping malformed timestamps out of the database.

**Comment by kmilos** [comment]
Thanks for checking. I purposely went for a minimal fix so it can stand a chance to be included in the impending release.

While it is true there is no strict input checking in this case, that also holds for other Exif fields. Implementing an Exif validator would have to be approached very differently indeed, if there is any appetite for it that is.
