### ISSUE TITLE
The snapshots split line break image when collapse the Film Strip

### ISSUE THREAD

**Issue by vanviethieuanh** [darktable-org/darktable#9260]
**The split line of snapshots feature look good until I collapse the Film Strip**
Here the split-line work normally
![image](https://user-images.githubusercontent.com/29355962/122390179-e7287180-cf9b-11eb-930f-ebd2947b65f4.png)

Until I collapse the Film Strip or the Bottom Bar, it looks like the original image container get stuck in the past and can't be stretched out
![image](https://user-images.githubusercontent.com/29355962/122390131-d972ec00-cf9b-11eb-9570-b3c8eb70d2c6.png)
Collapse the top bar and the problem clearly appear, it seems like the container of origin image not stretch out
![image](https://user-images.githubusercontent.com/29355962/122392491-1c35c380-cf9e-11eb-8e94-c8d95697d6e8.png)

**To Reproduce**
1. Import an image
2. Take a snapshot
3. Open split line
4. Collapse the Film Strip
5. Issues

I think they should be aligned with each other.

**Platform**
I installed darktable with PopOs Store 
![image](https://user-images.githubusercontent.com/29355962/122391187-f2c86800-cf9c-11eb-8971-7370ab7c4b59.png)

Here the log from `apt list | grep darktable`:
```sh
darktable/focal,now 3.0.1-0ubuntu1 amd64 [installed]
```
from `neofetch`
![image](https://user-images.githubusercontent.com/29355962/122392077-c3662b00-cf9d-11eb-933f-d7c8f1656031.png)

* OS: Pop!_OS 20.04 LTS x86_64 
* Kernel: 5.11.0-7614-generic
* Memory: 5112MiB / 7640MiB
* GPU: Intel UHD Graphics 620

**Comment by ralfbrown** [comment]
Snapshots are simple bitmaps.  They also won't adjust if you change zoom ratio, or take one while zoomed in and then pan the image.

**Comment by johnny-bit** [comment]
this is working as intended.

The wish for "adjustable" snapshots is tracked in this fr: https://github.com/darktable-org/darktable/issues/2784
