### ISSUE TITLE
new crop module: presets do not include margins

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#9263]
**Describe the bug/issue**
When applying a preset in the new crop module, only the aspect ratio is set, not the margins.

**To Reproduce**
1.  Set up a crop with nonzero borders on all sides, preferably with an aspect ratio other than that of the image
2. Save as a new preset
3. Apply the preset
4. Notice that the crop area is now the maximal possible given the aspect ratio, and all four margin sliders show 0% (even though that isn't actually possible when the aspect ratio differs from that of the image)

**Expected behavior**
The crop at the time the preset is saved should be restored, as is the case for the old crop&rotate module.  Since in the above steps nothing is changed between storing the preset and appying it, the crop should not change.

**Additional information**
A little further investigation showed that setting the sliders manually rather than by resizing the crop box creates a preset which applies more-or-less correctly.  While playing with the sliders, it became clear that they aren't correctly updating the horizontal margins when changing vertical margins (or vice versa) when the aspect ratio is other than "freehand".

**Which commit introduced the error**
Presumably present since the new crop module was added.

**Platform**

* darktable version : 3.5.0+2510~g1c60f3532
* OS                : Linux, kernel 5.10.33
* Linux - Distro    : Mageia 7.1
* Memory            :  64GB
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : no
* OpenCL activated  : no
* gcc               : 8.4.0
* CMAKE_BUILD_TYPE  : Release

**Comment by elstoc** [comment]
@AlicVB can you take a look at this please

**Comment by AlicVB** [comment]
@ralfbrown : PR #9273 should fix your main issue.
For the margin sliders one, I'll have a look...
