### ISSUE TITLE
crop&rotate: presets must be applied twice when module is collapsed

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#9264]
**Describe the bug/issue**
When applying a preset using the crop&rotate module's hamburger menu while the module does **not** have GUI focus, the first application of a preset only gives it focus, but neither applies the preset nor turns on the module.  Further applications of presets once the module has focus then actually set the cropping and turn it on, as expected.

* darktable version : 3.5.0+2558~g1fc2d0e22
* OS                : Linux
* Linux - Distro    : Mageia 7.1
* Memory            :  64GB
* OpenCL installed  : no
* OpenCL activated  : no
* gcc               : 8.40
* CMAKE_BUILD_TYPE  : Release

**Comment by elstoc** [comment]
Probably clicking on the menu(s) should give the module focus.
