### ISSUE TITLE
Export black and whites images as grayscale

### ISSUE THREAD

**Issue by pierre04** [darktable-org/darktable#9266]
**Is your feature request related to a problem? Please describe.**
I have noticed that I can significantly reduce the filesize of my black and white photos (png format) exported from Darktable by converting them to grayscale (for example using convert image.png -colorspace Gray image-converted.png)

**Describe the solution you'd like**
A button in the export section to choose to export to grayscale / or a colorspace to select in the menu.

**Alternatives**
An automatic detection of grayscale images. For example pick 100 random pixels in the image, check if the r,v,b value are the same. If more than 95% are the same, prompt user if the image should be exported as grayscale.

**Comment by parafin** [comment]
There's already such feature (automatic detection) for TIFF and I think AVIF formats, So I don't see why not add it to PNG too.

**Comment by pierre04** [comment]
Excellent :)

Would it make sense to also do it for webm (I plan to use this format in a near future instead of png). I don't know if this would help reducing the filesize though.

**Comment by ralfbrown** [comment]
It could also be added for JPEGs, though the size reduction will be small as JPEG uses YCbCr internally, so the two color channels already compress extremely well on monochrome images.  I just did a quick check with ImageMagick's `convert` on a 1280px dt output file, which went from 342k to 330k at the same quality setting due to storing only the Y channel.
```
>identify *.jpg
DSF61835-gray.jpg JPEG 1280x855 1280x855+0+0 8-bit Gray 256c 330131B
DSF61835.jpg JPEG 1280x855 1280x855+0+0 8-bit sRGB 342448B
```

**Comment by kmilos** [comment]
> There's already such feature (automatic detection) for TIFF and I think AVIF formats,

For TIFF yes, but not quite for AVIF: we do have a grayscale AVIF option, but it will always force grayscale, even for RGB images (there is an implicit RGB->YUV conversion happening for AVIF in all cases, and I guess chroma components just get discarded for grayscale). So there is some difference in (expected?) export behaviour, and it would indeed be nice to make it somewhat uniform across formats. But first we need to agree on the spec:

1. Do we allow blanket dropping of chroma for RGB images for formats that have implicit YUV conversion (AVIF, JPEG, etc.)?
1a. If so, I guess we need to then implement/force the same RGB->luma conversion for other formats (e.g. TIFF)?

or

2. We only allow singe channel export if it is a true B&W image already _and_ grayscale option is checked, [like TIFF export currently tries to auto-detect](https://github.com/darktable-org/darktable/blob/0c01bab2392ce59520415126eed2f184d59929bd/src/imageio/format/tiff.c#L157-L228) (AVIF export currently breaks this as mentioned)

**Comment by pierre04** [comment]
I went through the different milestones and could not find this issue (search terms : gray, grey, export). So I believe it is still needed.
