### ISSUE TITLE
Huawei P30 Pro

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#9268]
Like this post https://github.com/darktable-org/darktable/issues/9223 also Huawei P30 Pro and its colour looks off.
Three cameras, 14 mm, 5 mm and 2 mm. 14 mm camera seems ok but not the 5 mm camera. darktable (exiv2) reports two different focal length for this camera. 6 mm and 5 mm.
![Skärmbild från 2021-06-18 14-11-18](https://user-images.githubusercontent.com/34200649/122559015-117f3b00-d03f-11eb-84e0-7dd9d01123bd.png)

CC0 files at https://drive.google.com/file/d/1X95Ta2Jt62o5IM1pDQtHv8FWWpZ8WF2a/view?usp=sharing

**Comment by johnny-bit** [comment]
there's raw for it in raw.pixls.us - https://raw.pixls.us/getfile.php/3060/nice/HUAWEI%20-%20VOG-L29%20-%2016bit%20(4:3).dng ?

**Comment by PeterWem** [comment]
My mistake about the 14 mm camera then. What about the 40 mpix camera? Same name, VOG-L29, but 40 mpix.

**Comment by johnny-bit** [comment]
If camera produces more than 1 kind of file, it'd be best to upload all to raw.pixls.us

**Comment by PeterWem** [comment]
Before I wrote here I added the three raw files. 14 mm (already there), 5 mm and 2 mm.

**Comment by kmilos** [comment]
Does it look any better if you pass through the Adbobe DNG converter? The [list support for this model](https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html), wonder if they do anything to the color profile...

**Comment by PeterWem** [comment]
Yes.
https://drive.google.com/file/d/16wKtRzG5MLBVfWgeLHK8sWBwz44fHBYV/view?usp=sharing
