### ISSUE TITLE
Use additional mouse buttons to navigate

### ISSUE THREAD

**Issue by andsunds** [darktable-org/darktable#9271]
**The solution I'd like**

I have a mouse with additional buttons, which I use to navigate back and forth in, e.g., web browsers. It would be nice if I could use the same mouse buttons to navigate backward and forward among the images in darktable.

**Additional context**

I'm trying to migrate to darktable, so I'm still quite new to the software, and I don't know if there already is any solution.

**Comment by ralfbrown** [comment]
There's a new input system being prepared which should allow such a setup in 3.8.  The plan is to merge it immediately after the upcoming 3.6 release.  See #8078.

**Comment by andsunds** [comment]
Wonderful!
