### ISSUE TITLE
eigf posterization

### ISSUE THREAD

**Issue by HansBull** [darktable-org/darktable#9279]
eigf produces posterization effects, while averaged eigf does not (with all other settings the same). Changing filter diffusion, edges refinement has no effect.

![eigf settings](https://user-images.githubusercontent.com/67728709/122635724-d8e66c80-d0e5-11eb-93b7-d4f15aae7e04.png)
![eigf](https://user-images.githubusercontent.com/67728709/122635725-d97f0300-d0e5-11eb-9ceb-2754ab941357.jpeg)
![averaged eigf](https://user-images.githubusercontent.com/67728709/122635726-dab03000-d0e5-11eb-9cc1-818ae08ec22b.jpeg)

**Expected behavior**
No posterization

**Platform**

* darktable version : current master
* OS                : Linux - kernel 5.0.37
* Linux - Distro    Ubuntu 18.04
* Memory            8G
* OpenCL installed  : no 
* OpenCL activated  :  no
* Desktop           : KDE
* gcc               : 11

**Comment by elstoc** [comment]
@rawfiner can you look at this please?

**Comment by rawfiner** [comment]
Please provide you raw and xmp
Also, please show the settings in "simple" tab, and the exposure mask

**Comment by HansBull** [comment]
reproduce: random 
Interestingly, it was gone in the file above after a restart. It appeared in another file though - but I can't share any of them.

**Comment by johnny-bit** [comment]
can you try with any playraws or raws from raw.pixls.us?

**Comment by rawfiner** [comment]
Also, please post screenshots of the 2 other tabs of the module, as well as the displayed mask, and please upload your xmp
Thanks!

**Comment by HansBull** [comment]
Will reopen when I can reproduce it
