### ISSUE TITLE
documentation: apply preset to current module or new instance

### ISSUE THREAD

**Issue by xfh** [darktable-org/darktable#9293]
Hi all

I am on Gentoo Linux with latest master (3.5.0+2583~g81f514ea9-dirty). Since a few weeks I started having problems applying presets to a module: sometimes it would seemingly random create a new instance instead of simply applying the preset to the current module. I finally manged to get it reproducible.

### Preset applied as a new instance
1. Open any image
2. Right-click and hold the right mouse button pressed on a module header
3. Left-click on a preset

### Preset applied to selected instance
1. Open any image
2. Right-click on a module header and release the right mouse button
3. Left-click on a preset

Usually, I just right-click somewhere on the module name to open the preset popup and pick one. Either my right-clicks have become more sloppy and I keep hold much more than I used to, or the behaviour changed recently. I haven't tested with older versions. But it caused some confusion until I figured out why the new instance was created.

Since I am not sure if this is intentional or not, I open an issue here in the main repo for you to decide.
I guess it's a feature once you realise how to control it and should be documented. I couldn't find anything related in the module-header nor presets documentation.

**Comment by ralfbrown** [comment]
Right-clicking on the icon that brings up the multiple-instances action menu (the one that includes 'new instance', 'rename', etc.) now creates a new instance of the module,  where that used to be done with middle-click.

**Comment by xfh** [comment]
That would explain why it happens more often than before. I am assuming while holding the right mouse button, the event is still propagated to the "create new instance" handler - even when I am not pressing on that button.

I am still split whether I find this a useful feature or too confusing :-)

**Comment by ralfbrown** [comment]
More likely that you are accidentally moving the mouse into the icon while holding the mouse button,  thus triggering that handler.

**Comment by xfh** [comment]
Nope, I am nowhere close to that button. Please try for yourself.

**Comment by johnny-bit** [comment]
I tested it and it's TBH prooobably some funny event handling shennenigans

For starters I managed to reproduce first like:

1.Open any image
2.Right-click and hold the right mouse button pressed on a module header
3.Left-click on preset while releasing right click

but then I had a thought - if you right click on a preset in presets menu - you'll get preset applied to new instance!

It's even easier though:
right click and hold and then release while on selected preset: it'll apply preset to new instance :D 

It's not a bug, it's a feature!

**Comment by johnny-bit** [comment]
Please note - it works like that by design: menu is opened on mouse DOWN even while preset is applied on mouse UP event. Given that the "appy to new instance" changed from middle to right button (since many mices don't have middle buttons) it's perfectly fine feature.

If you think it should be documented in it's intricacies then you can open issue/pr on dtdocs repo

the behaviour might change and/or be customized with #8078 (or in some further version) though...

**Comment by xfh** [comment]
Thanks for the clarification @johnny-bit , I somehow missed that I am not even left-clicking on the pressed but just releasing the mouse button...

I notice now, that it's not even necessary to keep hold of the right-click. Simply right-clicking on a preset will create a new instance.

I'll open a PR in dtdocs.
