### ISSUE TITLE
Can't saturated blue channel for noise profile - Canon EOS D60

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#9300]
In the link I have some couple of raw files from Canon EOS D60. It seems that no matter what I do I will not be able to saturate the blue channel at ISO 200 and ISO 400.
![Skärmbild från 2021-06-21 12-58-48](https://user-images.githubusercontent.com/34200649/122752487-526e8e00-d291-11eb-9310-a123d318d53a.png)

CC0 https://drive.google.com/file/d/1TTQhR6Q18FwRm21Jqbbw6NRKuCVQCNYn/view?usp=sharing

**Comment by PeterWem** [comment]
The noise profile script actually accepted the files even if ISO 200 and 400 weren't saturated in blue channel.
[darktable-noiseprofile-20210621.tar.gz](https://github.com/darktable-org/darktable/files/6686678/darktable-noiseprofile-20210621.tar.gz)

Anyway, I got a new problem. The script didn't accept ISO 1000. Perhaps because darktable is reporting ISO 1007.
![Skärmbild från 2021-06-21 14-51-23](https://user-images.githubusercontent.com/34200649/122764825-29a1c500-d2a0-11eb-8eb8-b681f2183f34.png)

**Comment by rawfiner** [comment]
@PeterWem I don't know how to fix this
One question though, you have a ISO 1000 on this camera but no ISO 500 or 640?
Maybe you can generate the profile skiping the ISO 1000 image, darktable can interpolate the values from ISO 800 and next ISO value, I don't have a better solution for now...

**Comment by PeterWem** [comment]
No  ISO 500 or 640 on[ this old camera](https://en.wikipedia.org/wiki/Canon_EOS_D60). Should I do anything else or is my tar file enough for getting it into official darktable?

**Comment by rawfiner** [comment]
thanks for the url, I misinterpreted it to 60D
If ISO 1000 is the maximum ISO value, darktable won't be able to interpolate for this value, so we need the script to work for this... I downloaded your raws, I will try to see if I can circumvent the issue.

**Comment by rawfiner** [comment]
Good news, the noise profile creation succeeded on my side.
The ISO values reported on the profile were wrong, but I corrected them manually. I checked that the profile is correctly detected within darktable.

**Comment by PeterWem** [comment]
Great to hear!
