### ISSUE TITLE
Crash when exporting, with or without gpu acc

### ISSUE THREAD

**Issue by bilacc** [darktable-org/darktable#9302]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to Export
2. Click on export...
3. Scroll down to '...'

**Expected behavior**
Export crashes

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g.Win10 - newest update 06/2021

* Memory            :  16GB
* Graphics card     :  Ryzen 7 APU (5800H)
* Graphics driver   :  newest
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?
[darktable_bt_338F50.txt](https://github.com/darktable-org/darktable/files/6687000/darktable_bt_338F50.txt)
[darktable_bt_PDZV50.txt](https://github.com/darktable-org/darktable/files/6687001/darktable_bt_PDZV50.txt)
[darktable_bt_SN0N50.txt](https://github.com/darktable-org/darktable/files/6687002/darktable_bt_SN0N50.txt)
[darktable_bt_TUFD50.txt](https://github.com/darktable-org/darktable/files/6687003/darktable_bt_TUFD50.txt)
[darktable_bt_6H8S50.txt](https://github.com/darktable-org/darktable/files/6687004/darktable_bt_6H8S50.txt)

**Comment by bilacc** [comment]
It happens even when I try exporting 1 image (after messing with exposure for example), didnt try exporting without modifying the image. My guess is that it has something to do with my configuration, maybe its compatibility issue with Ryzen 7 5800h.

**Comment by johnny-bit** [comment]
Please edit the issue and remove bits that do not apply to you, eg lua questions, screenshots etc and make sure you put in correct data, most importantly correct darktable version. Do you really have darktable 3.5.0+250? that's rather old(ish) master build

The error happens somewhere in `dt_dev_pixelpipe_cache_get_weighted` (in a loop?) and then memset tries to set null location? WEIRD...

**Comment by bilacc** [comment]
Hi, Im using latest Darktable, downloaded from  the main website. I just updated my AMD drivers, will test  and get back to you, hpefully I will have time to edit the issue a bit.

**Comment by bilacc** [comment]
Just tested export after installing latest AMD Adrenaline drivers, works fine now.

**Comment by johnny-bit** [comment]
Great!

btw: 3.6 release is in less than 2 weeks :)

**Comment by bilacc** [comment]
Great! Thank you so much for your time and energy invested in the app.
