### ISSUE TITLE
Quick access panel → Color calibration description (null)

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#9308]
1. Run latest git dt build
2. Open any file in editing mode
3. Hover color calibration widget in quick access panel

Problem: Widget description shows "(null)" instead of something more sensible (or, don't show it at all, if description is not available for that widget).

**Comment by timur-davletshin** [comment]
> Not sure which color calibration widget you mean

Darkroom mode → Quick access panel → Color calibration → Temperature slider → Hover with mouse pointer → Popup contains "(null)" as a description.

**Comment by timur-davletshin** [comment]
Looks like popup drawing function is lacking for simple null value check and tries it anyway (temperature slider in color calibration module doesn't provide description for temperature slider). Probably in src/libs/modulegroups.c

**Comment by AlicVB** [comment]
@dterrahe : do you prefer me to fix that now or we wait for your work to land ? I don't want to complicate things for you more than needed (and that's not really a critical issue)

**Comment by dterrahe** [comment]
This is _already_ fixed in #8078 and @TurboGit is planning to merge that before anything else (unless he finds a heap of problems, presumably) so there's no point creating a separate PR to just address this.

**Comment by AlicVB** [comment]
thanks ! I'm aware that it's already fixed in your PR and that we plan to merge that really early. That's why I've asked ;)
