### ISSUE TITLE
Color calibration → String not available for translation

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#9309]
1. Run latest git dt
2. Open color calibration module, part used for color checker calibrtion
3. Run calibration
4. Illuminant type string is not available for translation (see attached file)

![color cal](https://user-images.githubusercontent.com/65483426/122917211-6e902f00-d366-11eb-9ba7-ee87d657bf15.png)

**Comment by Nilvus** [comment]
Unfortunately, it's too late for 3.6
