### ISSUE TITLE
Proposal for allowing l10n requests for online help in darktable 3.6

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#9312]
Well, I understand that this proposal may be rejected, but I will try to find arguments in favor of the proposal, because for me, as a translator into Ukrainian, it is an opportunity to make the translated user manual accessible from within darktable 3.6 as soon as it will be ready.

Currently, only English is in the hard-coded list of languages. This is understandable, because at the time of release the help in other languages will not be 100% ready. This means that only English reference manual will be requested by darktable's help system.

But this also means that released darktable 3.6 will not be able to find out that, for example, the Ukrainian reference manual has been published and the program will offer online help only in English as long as this version installed on user's system, despite the fact that he/she uses Ukrainian interface of the program.

I suggest including in the list of supported languages those languages which will receive full translations of the reference manual in the near future. This way the program will make a request for online help in the interface language.

Because requested non-English pages will not be ready and published for some time, we just have to rewrite the URL on the web server side (like ngx_http_rewrite_module for NGINX), redirecting all requests to English version of the page until appropriate language version will be available.

**Comment by elstoc** [comment]
None of the dtdocs translations are yet complete enough to be published and we will not be publishing them (to darktable.org) with darktable 3.6. There are also still some unresolved issues with translated pdf and epub versions, that will not be resolved until 3.8.

The next release is due to be released in a couple of weeks and it is much too late to change either project now.

**Comment by elstoc** [comment]
So since we're not going to do this for 3.6, this is now a duplicate of #7792

**Comment by johnny-bit** [comment]
IMO darktable part is indeed duplicate of #7792 but redirects in usermanual should be issue in dtdocs... and so this issue IMO can be closed.

**Comment by victoryforce** [comment]
> None of the dtdocs translations are yet complete enough to be published and we will not be publishing them (to darktable.org) with darktable 3.6.

Exactly! This is the issue I try to overcome with my proposal. Translations are not yet complete and currently darktable have no code that can find out in run-time when translated online help will be accessible. The worst option would be to wait for 3.8 leaving 3.6 without access to translated help. The best solution would be to implement the approach when client-side (darktable)  indicate the desired language in the request for online help and it's up to the server to decide whether to ignore the language if it is not already supported, or to handle such a request when the language is ready.

> darktable 3.6 is due to be released in a couple of weeks and it is much too late to change either project now.

All changes required to implement this approach are:
- simple one-line patch to array of supported_languages in `global_toolbox.c`
- one rule for ngx_http_rewrite_module on server-side to ignore language indication in the URL and rewrite it to canonical form
It's so simple I'd not call it a change of the project.

> To clarify: we have no intention to republish the docs to darktable.org until darktable 3.8. At that point we will publish any translations that are complete.

Let my clarify the goal I try to achieve. The translated interface will make darktable more accessible to a larger number of users who do not understand English very well, or are not accustomed to specific terminology in English (not such a rare situation in Ukraine). The translated reference manual (online help system) will make the program much easier to learn and master.

I understand that you do not intend to publish translations before 3.8. But I still do not understand the reasons and rationale for such a postponing. In about three weeks I will finish translating the text into Ukrainian. From now on, users could receive online help in Ukrainian. But due to the refusal to publish this translation, users will have to wait half year for version 3.8. Why?

**Comment by elstoc** [comment]
> But due to the refusal to publish this translation, users will have to wait half year for version 3.8. Why?

The translation will still be published on https://darktable-org.github.io/dtdocs/ but we don't intend to maintain a separate branch in dtdocs for version 3.6.x (for ease of maintenance, difficulty of operating that branch with weblate, and the fact that we no longer intend to release new features with point releases). 

Once darktable master moves on so will dtdocs, at which point dtdocs will no longer represent the contents of darktable 3.6 but darktable 3.7 (dev).

**Comment by victoryforce** [comment]
> So let's see how it goes and revisit it when you're done translating.

Let's see. 

Unfortunately, the translation is only 75% ready at the moment, so I lost race against time and couldn't make it to the release. :)

It was only a proposal and by no means a pressure on you or anything like that (I'm sorry if you look at it this way).

I opened this issue for discussion and therefore I'll close it because it has fulfilled its function and now I understand what is the complexity of maintaining docs for moving target (i. e. darktable).

And thank you for doin' a great job!
