### ISSUE TITLE
Nikon D6

### ISSUE THREAD

**Issue by dawnrazor99** [darktable-org/darktable#9328]
Permutations of compression and depth, etc. are uploaded.

Producing defiles for the camera noise profiles is not possible, because "darktable-gen-noiseprofile" dosen't work with raw-files from the above mentioned camera.

**Comment by dawnrazor99** [comment]
Hi @kmilos 
hi, @LebedevRI,

sorry for the stupid question, what have I to do to forward this issue?

**Comment by LebedevRI** [comment]
Nothing

**Comment by dawnrazor99** [comment]
Hi, what have I, the issuer, to do to reach the next steps?

**Comment by johnny-bit** [comment]
Have patience. You've contributed samples and the support must be developed on rawspeed side of things. Once rawspeed devs get a round tuit, the support will be in rawspeed. Once it's in rawspeed it then will get into draktable master. And once it gets in darktable master it'll get added to the nearest release.

So... have patience.
