### ISSUE TITLE
Settings - Additional setting to apply Auto-Sharpen to either  "ALL Images" OR "Only RAW images - (default)"

### ISSUE THREAD

**Issue by OK-One** [darktable-org/darktable#9337]
**Is your feature request related to a problem? Please describe.**

I love darktable, superb application. In addition to using it as a raw processor, and photo retoucher, I especially cherish its use as my central repository of all manner of images, including images which were developed, in other apps.

I therefore use darktable, in many ways as my primary viewer and comparator for images. My central window, into my entire image archive.

Obviously I must first import these images into the darktable "library" as part of a collection, etc, etc.

I have just noticed that the sharpen module is turned on, by default on all images, raw and jpg, and tiff, not just on raw images.

Which means, when I view an Out of Camera Jpg in dt, I am viewing it though a 2nd stage of sharpening, as it has already been sharpened in camera. Same applies to jpgs and tiff files, which have been processed in other apps.

For these kinds of images, which were processed in other apps, or which I had no contribution to their processing, and I simply want to use the darktable lighttable to view, cull, compare, and have no intention of making any edits in darktable, it should be possible to ensure that darktable does not automatically turn on the sharpen module, for such "already sharpened" images. So any viewing I make in Lighttable,  or in the darkroom, will be accurate.

This applies to version 3.5+, but I can imagine that this has been an issue with darktable for previous versions, which have the same autosharpen option in the settings window/page.

A good example of this is when you develop a raw image in the darkroom, and wish to compare it in the lighttable view, with the Out-of-Camera jpg, and you are not aware that darktable has added an extra sharpen automatically to the jpg, as you view it and compare to your image developed in darkroom.

Most people would not notice any difference, but I did, and it would be nice to have this inadvertent anomaly avoided.

**Describe the solution you'd like**

In the same way that it is possible to set presets to auto apply to different types of images. it would be wonderful in the settings page/window, if the autosharpen setting (in addition to having an on or off). could also have options to select what kind of images would this apply to when set to on.

So an additional setting such as auto-sharpen-scope, could be added, with a drop down, to choose which kinds of images, auto sharpen will apply to.

The values in this drop down for auto-sharpen-scope, would be :

1. All images
2. Raw Images only (default)

**Alternatives**

1. Until such a feature is implemented, maybe a note in the documentation, to alert anyone who uses darktable for similar archiving, or review of images developed elsewhere, to be aware of this inadvertent undesirable double sharpening of non raw , already processed images, when viewed in the lighttable or when viewed in the darkroom.

2. My workaround, before I import new images, will be to create a new preset in the sharpen module that is identical to the default preset, and in my preset copy, enable auto apply for only raw images.

**Additional context**

Unfortunately, I have to now disable sharpen on hundreds of non-raw photos, and there is no simple way to do this globally, unless maybe I investigate scripting, which is another level of complexity for most users.

So for non raw images which I have already imported into darktable, I must remember to disable sharpen, using one of the following methods

1. Open darkroom for each one, and disable sharpen.
2. Disable sharpen in one image, and then use selective copy in darktable's lighttable, to copy this single disabled sharpen module (i.e turned off) to all jpg and tiff files. (On second thoughts this should not be too difficult for an intermediate level user who is familiar with these sorts of things

So that's two workarounds, one for previously imported images, and another to avoid the issue in non raw images to be imported, in the future.

I do hope this ties in with the vision of darktable as a central point of truth for whatever images are developed or processed in whatever other photo app, and we can have darktable remain as the librarian of these images without the unwanted "side-effect" of this unintended additional sharpening.

Thanks for reading. I am the same person known as OK1 on pixlus forum, and rather than rant on a forum, I felt its far more constructive to become a formal contributor of ideas for improvement, via github.

Thank you.

**Comment by elstoc** [comment]
This can be achieved already. Simply disable the "auto-apply sharpen" preference and instead create a sharpen preset that only applies to raw images. Given that "auto-apply sharpen" is essentially discouraged for most modern cameras I think that's probably the easiest solution here.

**Comment by MStraeten** [comment]
the sharpen module is applied when opening an image in darkroom. You can disable this in peferences.
It's highly reccommended to read the manual before filing feature requests.

**Comment by elstoc** [comment]
If you want to tidy up old images then create a style in which the sharpen module is disabled and then apply that style to those images

**Comment by johnny-bit** [comment]
Auto apply sharpen is enabled by default since it's "desireable" for pics with AA filter. Others do not benefit from it. Disabling it is recommended if you don't have AA filter or if you plan to use dt on already sharpened images. I think it's already mentioned in the manual.

For auto-applying to selected images dt has auto-presets functionality, so ideally you'd disable auto-apply sharpen and rely on presets.

And for correcting images use style or paste disabled sharpen with combination of collections modle (you CAN filter by extension)

Personally - I think auto-apply sharpen should be by default disabled with scene-refered workflow and ultimately removed as an option so people who'd like to use auto-apply sharpen would create auto-apply preset.

does that solve your feature request? If so - please close it. Or I'll close it

**Comment by OK-One** [comment]
With all due respect, telling me to read the manual when I have just spent time, trying out all the options, is a bit high handed, and like a slap in my face.

It was not needed, and I did not enjoy being spoken to in this manner. 

We do read manuals, and if it was in the manual, I would have found a solution. Which is why for the 1st time in my life, I have bothered to come to the darktable github, to do the right thing, discuss it directly with those who should know enough about it, and can fix the issue.

Whomever made this statement to me about reading the manual, made an assumption that I have not read the manual, a false assumption.

Kindly appreciate, I clearly must have known, how the auto-sharpen is initiated, via the settings, cos I referred to this, in my request. And it appears my request was not fully read or appreciated.

Please do not be so quick to dismiss comments of users, as if we the users are not diligent, enough to read the manual. We are diligent. And we have read the manual, and what we need is not in the manual, and is also not in darktable, which is why we make an issue of it.

There is nothing additional that the manual has to say about this, that could have resolved the issue I have raised.

And I am resolute about this. There is nothing in the manual that solves my request.

I have gone further to try the workaround that I considered might have solved my issue, by using the conditional apply in a preset, to apply the sharpen ONLY to raw files. Regrettably, this also does not solve the issue. darktable only obeys what was set in the settings menu/page/window(whatever you prefer to call it).

Which implies that the setting of sharpen(on or off - to ALL images on import) is hard coded, to whatever  is configured in the settings(preferences) page, and overrides any other settings in the conditional sharpen module preset, which I created.

At this time, and I stand to be corrected, cos I have just spent the last few minutes testing this out, Importing images, removing them from the database, making sure I have deleted the xmp's created by dt, before reimporting them again, so that the import obeys the revised default settings, and creates new xmp's based on the new status of the Auto-Apply Sharpen setting.

Do check, and I will be most surprised if I am wrong about this, I have checked.

The only functionality in dt for controlling the automatic management of sharpening, is either it is on by default, or off, based on whatever I set in the settings page. So that means its either on for ALL types of images, or OFF for all types of images. By this I mean images you import after changing the settings, will have the current setting at time of import applied to ALL images, or any type.

Any images imported before any change in settings, already have the de-facto sharpen settings applied to their xmp's, at the time of import.

Clearly, we need to stop being defensive about this. There is as issue. The sharpening module should NOT be automatically added as a module to non raw images such as jpgs and tiff files. and there is no current method to selectively apply this, based on image type.  And the only option to correct this is to turn off auto apply of sharpening via the settings page., which turns of sharpening for ALL images including raw images.

So at this time, the only option is to 

1. Turn off Auto - Apply Sharpen in the preferences/settings, which turns it off for ALL new images imported.
2. And for any image, where sharpening would be desirable, such as raw images, you have to manual remember to turn this on, by hand., every single time. for every image.

This is the only way I can import jpgs, into darktable, without having a 2nd sharpening applied, by darktable.

I thoroughly appreciate, those who manage darktable are obviously passionate about it, but please see the perspective of others. Especially we the end users, who do not yet write code for darktable.  If there is an issue, accept it, even if at this point in time there is no elegant solution to the problem.

We should not be arguing about this. Why?

You already have modules which are selectively added or not added based on file type.

Modules like white balance and filmic, and demosaicing are not added when you import a non raw file like a jpg or tiff, all you have to do to fix the issue I have raised, is apply a similar logic to the sharpen module. Darktable is intelligent enough to know that jpgs do not need white balance or filmic turned on. It cannot be so difficult to simply add the sharpen module to the logic that implements this decision, to turn on sharpen module for raw files, and turn off sharpen module for non raw files.

There you go, we have an even more elegant way to handle this, than whatever I had suggested earlier, which was to use a setting.

The most elegant solution which I have now described above, does not need any settings, and should not take more than a few weeks, to change in the code. Probably no more than a few hours, to modify the logic, which is already used to decide when to apply white balance, filmic, or demosaicing, or modules like raw denoise, for raw files, and to disable them for non raw files, like jpgs and tiffs.

The solution already exists in darktable, we simply need to add the sharpen module to the list of modules turned on automatically for raw files, and turned off otherwise.

The solution to this issue, is simple, and should not need an argument, or debate, especially when it will not take much coding to create this change request.

I go one step further, I am sure it will not take more than a few hours for those who know the dt code, to look at this issue and fix it. 100% sure of this. It is a simple and easy issue to resolve.

**Comment by OK-One** [comment]
> 

For my old images (jpgs and tiffs), I could also turn off sharpen in one image, and via lighttable, copy this sharpen module which has been turned off, to all the affected images, throughout the entire database. ! 

Not a big issue, I thought one could contribute something and make darktable better, which was why I raised this issue. Minor point. We'll leave it at that.

What makes it a bit cumbersome is that the current implementation means that.

1. When I turn off auto apply sharpen, this is turned off for all images. ALL.
2. Even if I set a default sharpen preset for the sharpen module, which is supposed to selectively apply sharpening only to RAW files, this default conditional preset, is NOT applied.

Therefore, there is no way to automatically add sharpening to RAW files, NONE, absolutely no way to achieve this in dt, which defeats the purpose of presets, cos in this case, these presets will not work with the sharpen module.

So I have to go and manually turn on sharpening for every single raw file, manually, for every single raw file I edit. Or copy a sharpen module which has been turned on, to all my raw files. Definitely not an elegant solution.

**Comment by elstoc** [comment]
Please can you try to keep your comments short and to-the-point - walls of text are not helpful.

I have given you a solution and I checked that it worked before I suggested it. Here it is in more detail (again, all thoroughly documented in the manual)

1. Disable the auto-sharpen preference. 
2. Enter the darkroom.
3. Manually enable sharpen and select "store new preset" from the preset menu, give it a name and then choose to "auto-apply" the preset to matching images
4. Uncheck "normal images"
5. Save the preset

If you start a new edit on a raw file it will be applied. If you do the same on non-raw files it will not.

**Comment by johnny-bit** [comment]
As shown in #9339 (https://github.com/darktable-org/darktable/issues/9339#issuecomment-869031204 <- screenshot of working autosharp config) Auto apply presets to raw files (in case of that screenshot ALL raw files) is possible and works nicely.

when applying or disabling sharpening via style make sure to set mode to "append" otherwise you'll overwrite your edits.

I think this covers 100% of this FR and so this can be closed.

> I go one step further, I am sure it will not take more than a few hours for those who know the dt code, to look at this issue and fix it. 100% sure of this. It is a simple and easy issue to resolve.

well if we'd change the setting to be "eval" allowing user to choose as you said, then we'd have to implement setting transfer akin to module param versioning and that's super hard and would be most likely one-time-migration that would be kinda problematic
if we had to add new setting, we'd have to figure out how to not break configs for defaults of new setting...

Usually what sounds easy - isn't.
