### ISSUE TITLE
Raw files from A7RIV open up in lighttable but not in dark room

### ISSUE THREAD

**Issue by slash33VDL** [darktable-org/darktable#9347]
**To Reproduce**
1 Copy files from SD card on to PC HDD
2. Right click on one of the files and select open with> darktable photo workflow software
3. Darktable opens up and prompts with an error file"file name and path here" has an unknown format
4. Preview of the image is available in light table
5. Double click to open the image in dark room.
6. error message: darktable could not load 'filename here', switching to lighttable now. please check the image.....

Ive tried opening the file with darktable on 2 different computers with the same result.
I've tried with compressed and uncompressed raw formats with the same result
Same file in Rawtherapee and capture one opens and edits fine

**Screenshots**
![image](https://user-images.githubusercontent.com/86544511/123533888-59e3da80-d75c-11eb-98df-054816376c61.png)

![image](https://user-images.githubusercontent.com/86544511/123533838-1f7a3d80-d75c-11eb-9fd0-d0fec1aeff48.png)

**Platform**

* darktable version : release 3.4.1
* OS                : Windows 10
* Memory            :  16 GB
* Graphics card     : NVIDIA GeForce GTX 650

**Additional content**
uncompressed and compressed file can be found here
https://www.dropbox.com/sh/sa053qk2tdaibxw/AADptw1XrKu_YUNHARGdsUZza?dl=0

**Comment by jade-nl** [comment]
That camera is not yet supported in version 3.4.1 / 3.6.

This is shown in the terminal for both your provided RAWs (haven't been able to find any other RAW to test on-line):

```
RawSpeed:Unable to find camera in database: 'SONY' 'ILCE-7RM4A' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (DSC07181.ARW) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData *, const std::__cxx11::string &, const std::__cxx11::string &, const std::__cxx11::string &), line 169: Camera 'SONY' 'ILCE-7RM4A', mode '' not supported, and not allowed to guess. Sorry.
```

It is also not listed here: [darktable camera support](https://www.darktable.org/resources/camera-support/)

**Comment by johnny-bit** [comment]
Please follow [recommended path to get camera support in darktable](https://github.com/darktable-org/darktable/wiki/Camera-support) and in this case [RAW format support](https://github.com/darktable-org/darktable/wiki/Camera-support#raw-format-support)

Please then open new [Camera support request](https://github.com/darktable-org/darktable/issues/new?assignees=LebedevRI&labels=scope%3A+camera+support&template=new_camera_support.md&title=%3CEnter+your+camera+name+here%3E) and close this one.

**Comment by paul-pw** [comment]
seems like sony has quietly updated the A7RIV. The A7RIV used to have the model number ILCE-7RM4 (which is listed in the supported cameras) but the new A7RIV has the model number ILCE-7RM4A [see this b]

**Comment by johnny-bit** [comment]
Still, we need to follow the process and can't use assumptions. Please follow what I outlined above and it'll be fine :)

**Comment by kmilos** [comment]
Uploading samples (please do) and following the camera support process is the best long term way obviously.

If you feel adventurous (reviews seem to claim the sensor and processor didn't change), and you want to see if you can *temporarily* work with these files in the meantime, you could try adding an alias to your `cameras.xml` though, in the 7RM4 section, e.g.:

```xml
	<Camera make="SONY" model="ILCE-7RM4">
		<ID make="Sony" model="ILCE-7RM4">Sony ILCE-7RM4</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="0" y="0" width="-32" height="0"/>
		<Sensor black="512" white="16383"/>
		<Aliases>
			<Alias id="ILCE-7RM4A">ILCE-7RM4A</Alias>
		</Aliases>
	</Camera>
```

**Comment by slash33VDL** [comment]
Thanks  for the input.
I've made the temporary change Milos has suggested here and it works.
I will go through the process of adding the RAW files for the camera support.
Thanks for the assistance and keep up the good work! :)

**Comment by LebedevRI** [comment]
Duplicate of #9751.
