### ISSUE TITLE
segfault on 3.5.0~git2651.f3119daa93-1

### ISSUE THREAD

**Issue by phil20099** [darktable-org/darktable#9353]
**Describe the bug/issue**
ubuntu has just prompted me to update darktable from http://download.opensuse.org/repositories/graphics:/darktable:/master/xUbuntu_20.04/, when I try to run darktable it segfaults.  Prior to this update it was working fine as I ran darktable successfully this morning.

I've tried running darktable with a new config directory and it still segfaults.

Ubuntu 20.04, synaptic shows the version as 3.5.0~git2651.f3119daa93-1

Attached is the backtrace.

What other info can I provide please ?

[darktable_bt_F3WR50.txt](https://github.com/darktable-org/darktable/files/6722019/darktable_bt_F3WR50.txt)

**Comment by TurboGit** [comment]
Fixed.
