### ISSUE TITLE
darktable starts repeatably only on 2nd attempt (manjaro linux)

### ISSUE THREAD

**Issue by navpp** [darktable-org/darktable#9362]
Hi guys, 

I am facing a minor problem here on my manjaro linux pc.

When clicking the darktable Icon first time, darktable appers in taskbar only for some seconds but then disappears again. On second click its starts normally. 
When starting from a console, there is the same behavior. (i'll attach the console output as well as the logfile it mentions)
The issue can be reproduced, so if you need more logfiles I can provide them.

Thanks,
Bernhard
[bash.txt](https://github.com/darktable-org/darktable/files/6742499/bash.txt)
[darktable_bt_XHIL50.txt](https://github.com/darktable-org/darktable/files/6742500/darktable_bt_XHIL50.txt)

**To Reproduce**
1. Start darktable
2. nothing happens
3. start darktable again
4. all fine

**Expected behavior**
start on first attempt ;)

**Which commit introduced the error**
Darktable version that is included in the official manjaro repos. I have nonfree-openCL installed for the free AMD graphics driver (at least I think that).

**Platform**
* darktable version : 3.4.1
* OS                : Linux - Kernel 5.10.42-1-MANJARO
* Linux - Distro    : Manjaro Linux; Build ID: rolling
* Memory            : 32GB
* Graphics card     :  Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.10.42-1-MANJARO, LLVM 12.0.0)
* Graphics driver   :  vulkan-radeon 21.1.2-1 ? (not sure actually) 
* OpenCL installed  : opencl-amd 21.10.1247438-1
* OpenCL activated  : Yes
* Xorg              :  Wayland
* Desktop           :  Gnome 40.1.0

**Comment by johnny-bit** [comment]
Log points to problem with OpenCL driver. Not darktable.

**Comment by johnny-bit** [comment]
There's an issue in other repo abvout that driver version being unable to init device: https://github.com/todxx/teamredminer/issues/267#issuecomment-833732329

Please open an issue with AMD OpenCL drivers and link here for reference.

**Comment by johnny-bit** [comment]
interestingly enough there's another bug report https://github.com/darktable-org/darktable/issues/8831, but with same driver vers as you... so it seems issue might be a bit related. can you start darktable in console with `darktable -d opencl` to show why it hangs/crashes.

**Comment by navpp** [comment]
Thanks for your reply. Interestingly I started darktable several times today and it always worked, no matter if I used the option "-d opencl" or not, but then again it failed multiple times. Strange behavior. Probably you are right and the problem is caused by the driver and darktable only shows it.
I hope the logs are helping.

[servaral_fails_then_success.txt](https://github.com/darktable-org/darktable/files/6745973/servaral_fails_then_success.txt)

**Comment by johnny-bit** [comment]
The `free()` crashing is crashing inside `libamdocl64.so` - it's IMO on drivers. can you update whole opencl subsystem on your os? both libopencl and amd drivers?

**Comment by navpp** [comment]
In the meantime openCL was updated to opencl-amd 21.20.1271047-1. Concerning updating the driver: I do not want to step away from the driver the distro maintainer is providing as I just don't have enough experience to mess around with it. I rely on this pc-system to be working.

**Comment by johnny-bit** [comment]
Did update fix your problem?
Have you also filled the bug with your distro about opencl problem?

**Comment by navpp** [comment]
Yesterday immediately after the installation no. But today after a reboot I could start darktable now 10 times without a crash. I will observe the behavior and raise a ticket if it wasn't fixed with that update. Thanks for your support!

**Comment by johnny-bit** [comment]
Generally darktable tends to be good about initiating OpenCL, so any crash due to opencl is more likely to be caused by drivers ;) Next time crash like the one here happens - start with distro and/or drivers :)

> Thanks for your support!

No prob!

> after a reboot I could start darktable now 10 times without a crash.

I'm assuming then that the issue got fixed. GPU drivers & kernel fixes always require restart (or play with module reloading, kexec etc but let's not go there)
