### ISSUE TITLE
Import to library with a single image should open it

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#9363]
**Is your feature request related to a problem? Please describe.**

When importing a single image to library, in a collection or folder that already contains images (let's say my `~/Downloads` folder), it gets lost in the collection. I have to find it manually.

**Describe the solution you'd like**

If only a single image is imported, open it straight in darkroom.

**Alternatives**

At least, center the lighttable view on the recently imported image.

**Comment by johnny-bit** [comment]
This should be IMO connected with https://github.com/darktable-org/darktable/issues/8915 since I'd say that double click (or enter) is essentially wanting to import and open a single image.

**Comment by elstoc** [comment]
the import image button used to do this

**Comment by phweyland** [comment]
> the import image button used to do this

In fact the first image of imported images was opened in darkroom. But the images importation was synchronous while it's now asynchronous, turning this behavior undesirable (you start doing something else and dt interrupts you to open the first imported image...).

This said, importing only one image should not lasts long and we may trig the image opening in darkroom from background job. 
Not really smart however. I'll try to find out if we can make the main thread wait for the background job ends. Any tip for this is welcome.

**Comment by elstoc** [comment]
I would be happy enough with just jumping to the last imported image in the lighttable (if it's open) or even doing so with each imported image (though I suppose that might get tiresome with a big import). At least then we'd be doing something consistent with both image and directory imports.

**Comment by phweyland** [comment]
> At least then we'd be doing something consistent with both image and directory imports.

Could you elaborate a bit more on this ?

**Comment by phweyland** [comment]
> I'll try to find out if we can make the main thread wait for the background job ends

dt_control_job_wait() should do the job.

**Comment by elstoc** [comment]
I mean when the import job has finished (how ever many images it's importing) lighttable should focus and scroll to the last image imported. The alternative is to do that that each time an image is imported - so if importing a directory, each image would be added to the lighttable and then focus given to that image, in turn. You don't need to care whether the user is importing an image or a directory, and can work in a consistent way whatever they're doing.

I haven't looked at the code so I have no idea if/how this would work.

**Comment by johnny-bit** [comment]
previously "import image" imported image and opened it in darkroom while import folder just imported bunch of images to lighttable with none highlighted.

i think the suggestion from @elstoc is to highlight last image in import

**Comment by phweyland** [comment]
Idea. Now that we can open in darkroom a single image, we could easily add the following.
- add a flag "open the first imported image in darkroom"
- both in [add to library] and in [copy & import], if this flag is set, we execute the first image import in synchronous mode, open this image in darkroom, and continue the import in background.
- not applicable for [import from camera]

What do you think ?

**Comment by johnny-bit** [comment]
Interesting idea... but wouldn't that complicate ui to open the image?

**Comment by elstoc** [comment]
Personally I would want to open the image in the darkroom only if I was importing a single image, and having to toggle an option to do this only in that scenario would be cumbersome.

**Comment by phweyland** [comment]
> only if I was importing a single image, and having to toggle an option to do this only in that scenario would be cumbersome

The idea was to always open in darkroom a single imported image but to add this option in case of importing several images.
Anyway, that's just an idea. And probably the most common next step after importing several images is culling not developing...

**Comment by johnny-bit** [comment]
Well... If I import single image it's either directly for testing or directly for editing.
If i import whole card or whole dir - then it's browse, rate, cull, maybe (geo)tag... editing is done actually on probably 1-2 images from whole shooting day if we're lucky ;) (or is done on whole bunch of product shots, but thats commercial work)
