### ISSUE TITLE
darktable 3.4.1 crashes trying to display an RW2 file from Panasonic GH5ii

### ISSUE THREAD

**Issue by peti** [darktable-org/darktable#9365]
I've imported a couple of RAW images shot on my Panasonic Lumix GH5 Mark II into Darktable. Darktable displays a proper thumbnail for them in the lighttable, but once I try to view any of the images in the darkroom, it says that it couldn't load the file and eventually crashes. You can download a sample image from <http://cryp.to/_1000014.RW2>. I've examined the file with `exiv2` and couldn't find any obvious errors:

~~~
$ exiv2 _1000014.RW2
File name       : _1000014.RW2
File size       : 24068096 Bytes
MIME type       : image/x-panasonic-rw2
Image size      : 5264 x 3904
Thumbnail       : image/jpeg, 3847 Bytes
Camera make     : Panasonic
Camera model    : DC-GH5M2
Image timestamp : 2021:06:29 16:09:39
File number     : 
Exposure time   : 1/30 s
Aperture        : F4.3
Exposure bias   : +33/50 EV
Flash           : No, compulsory
Flash bias      : 0
Focal length    : 23.0 mm
Subject distance: 
ISO speed       : 3200
Exposure mode   : Auto
Metering mode   : Multi-segment
Macro mode      : Off
Image quality   : Raw
White balance   : Auto
Copyright       : 
Exif comment    : 
~~~

**Comment by jade-nl** [comment]
This camera is not yet supported (both 3.4.1 and the upcoming 3.6 versions).

Start darktable from the terminal an see this:

```
RawSpeed:Unable to find camera in database: 'Panasonic' 'DC-GH5M2' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (pl.gh5ii.02.RW2) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData *, const std::__cxx11::string &, const std::__cxx11::string &, const std::__cxx11::string &), line 169: Camera 'Panasonic' 'DC-GH5M2', mode '' not supported, and not allowed to guess. Sorry.
```

It is also not on the [supported cameras list](https://www.darktable.org/resources/camera-support/)

Please have a look here: [Getting new cameras to work with darktable](https://github.com/darktable-org/darktable/wiki/Camera-support), specifically: [Raw format support](https://github.com/darktable-org/darktable/wiki/Camera-support#raw-format-support)

PS: I've tried RAWs from this camera model on both 3.4.1 and 3.7.0 both do not crash but will not load the RAWs for editing.

**Comment by johnny-bit** [comment]
@peti please follow steps outlined by @jade-nl and then open [New camera support issue](https://github.com/darktable-org/darktable/issues/new?assignees=LebedevRI&labels=scope%3A+camera+support&template=new_camera_support.md&title=%3CEnter+your+camera+name+here%3E) and close this one.

Thanks.

**Comment by kmilos** [comment]
Please note that you'll need to provide samples for all the different aspect ratios for this camera.

**Comment by peti** [comment]
New camera support request: https://github.com/darktable-org/darktable/issues/9370

**Comment by johnny-bit** [comment]
Great, Thanks!
