### ISSUE TITLE
Program unresponsible at exporting images and after it

### ISSUE THREAD

**Issue by tjapro** [darktable-org/darktable#9367]
**Describe the bug/issue**
When darktable is exporting images it becames unresposible, even after the exporting job is done.
The only solution is closed it and re-open it.

**To Reproduce**
1. Choose a image.
2. Export it (in my case, in overwrit mode)
3. The darktable turn unresponsible, but the files are generated.

**Expected behavior**
No unresponsiveness.

**Platform**

darktable 3.4.1

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

* OS                : linux
* Linux - Distro    : Fedora 34
* Memory            : 8GB
* Graphics card     : AMD® Radeon r7 m260 / Intel® HD Graphics 4400 (HSW GT2)
* Graphics driver   : 
* OpenCL installed  : 
```
clinfo -a
Number of platforms                               0
```
* OpenCL activated  : 
* Xorg              : wayland
* Desktop           : gnome 40.1.0
* GTK+              :
```
gtk2.x86_64                                                                                2.24.33-4.fc34                                                               @fedora 
gtk3.x86_64                                                                                3.24.29-1.fc34                                                               @updates
gtk4.x86_64                                                                                4.2.1-1.fc34                                                                 @updates
```
* gcc               : gcc (GCC) 11.1.1 20210531 (Red Hat 11.1.1-3)
* cflags            : 
* CMAKE_BUILD_TYPE  : 

 - Can you reproduce with another darktable version(s)? I only have this version.
 - Can you reproduce with a RAW or Jpeg or both? I only work with CR2.
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? NA
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) NO
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? NO
 - Do you use lua scripts? NO
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by johnny-bit** [comment]
If darktable was unresponsive after export we wouldn't be able to use it ;) so I'd say the issue is isolated to your environment.

Now couple questions:

1. Graphics card : AMD raedon - WHAT radeon?
2. Graphics driver : ??? Please specify version
3. OpenCL installed : ??? AMD offers either ROCm or AMDGPU-PRO drivers. which one of those are you using and what version?
4. OpenCL activated : ??? This is needed too.
5. Xorg : wayland - wayland is not recommended for graphics related work - AFAIK there's no color management in it.
6. Desktop : gnome - that does not narrow things down at all..
7. GTK+ : ??? please check which gtk you have installed.
8. s the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? NA - Please try with empty config dir. sometimes bad values in config or database may lead to all kinds of problems.

**Comment by tjapro** [comment]
> 2. Graphics driver : ??? Please specify version
> 3. OpenCL installed : ??? AMD offers either ROCm or AMDGPU-PRO drivers. which one of those are you using and what version?
> 4. OpenCL activated : ??? This is needed too.
> 7. GTK+ : ??? please check which gtk you have installed.

How to I check these?
I guess I haven't OpenCL installed, and GTK sems to be version 4.

> 8. s the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? NA - Please try with empty config dir. sometimes bad values in config or database may lead to all kinds of problems.

I'll try.

**Comment by Nilvus** [comment]
> > 1. Graphics driver : ??? Please specify version
> > 2. OpenCL installed : ??? AMD offers either ROCm or AMDGPU-PRO drivers. which one of those are you using and what version?
> > 3. OpenCL activated : ??? This is needed too.
> > 4. GTK+ : ??? please check which gtk you have installed.
> 
> How to I check these?
> I guess I haven't OpenCL installed, and GTK sems to be version 4.

Search with Fedora package manager gtk packages and check which release. Even if you have version 4, you also have Gtk 3 installed. darktable is based on Gtk 3, not Gtk 4, so we need Gtk 3 version.

For OpenCL, you have a tool named clinfo that you could launch in a Terminal (if you don't ind clinfo, you need to install it). You have also a GUI tool named hardinfo that can provide system information.

**Comment by johnny-bit** [comment]
Also... jugding by your edited post you have a laptop from roughly ~2014-15, right? Are you sure it's not thermal and/or power throttling? export operation is VERY resource intensive and i wouldn't be surprised if it thermally throttles your system.

**Comment by tjapro** [comment]
> Also... jugding by your edited post you have a laptop from roughly ~2014-15, right? Are you sure it's not thermal and/or power throttling? export operation is VERY resource intensive and i wouldn't be surprised if it thermally throttles your system.

No, I'm sure.

**Comment by tjapro** [comment]
@Nilvus Please see if there is more info that I can give.

**Comment by johnny-bit** [comment]
Run darktable with
```sh
darktable --configdir /tmp -d all
```
(it'll be big log)

in your favourite resource monitors start looking at following data: CPU Temp, GPU Temp, CPU Clock, GPU Clock, CPU Load, GPU Load, Memory Used, Memory Free, Swap utilization.
in 2nd console start `dmesg -w` and observe messages
in 3rd console start `journalctl -f` and observe messages

now start export process and observe patterns.

if CPU temp shoots up along with cpu clock and then cpu clock goes down while temp stays the same - it's thermal throttling
if memory used shoots up and then Swap utilization show up - then your system is pegged for memory
if dmesg starts spamming messages - focus on them
if journalctl logs something - check it too.

As for opencl - theoretically your gpu should be opencl capable, which would probably save a bit of cpu load if were possible to do but that's on you to figure out.

I douubt there's something that darktable itself causes it to be slow...

**Comment by tjapro** [comment]
So, I ran two commands. This are the results:

> darktable --configdir /tmp -d all > darktable_tmp.log

[darktable_tmp.log](https://github.com/darktable-org/darktable/files/6754040/darktable_tmp.log)

> darktable -d all > darktable_original.log

[darktable_original.log](https://github.com/darktable-org/darktable/files/6754047/darktable_original.log)

> dmesg

```
[ 1040.363900] nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based firewall rule not found. Use the iptables CT target to attach helpers instead.
[ 2538.939073] systemd-sysv-generator[7451]: SysV service '/etc/rc.d/init.d/livesys' lacks a native systemd unit file. Automatically generating a unit file for compatibility. Please update package to include a native systemd unit file, in order to make it more safe and robust.
[ 2538.950019] systemd-sysv-generator[7451]: SysV service '/etc/rc.d/init.d/livesys-late' lacks a native systemd unit file. Automatically generating a unit file for compatibility. Please update package to include a native systemd unit file, in order to make it more safe and robust.
[ 2545.979098] systemd-sysv-generator[7562]: SysV service '/etc/rc.d/init.d/livesys' lacks a native systemd unit file. Automatically generating a unit file for compatibility. Please update package to include a native systemd unit file, in order to make it more safe and robust.
[ 2545.979145] systemd-sysv-generator[7562]: SysV service '/etc/rc.d/init.d/livesys-late' lacks a native systemd unit file. Automatically generating a unit file for compatibility. Please update package to include a native systemd unit file, in order to make it more safe and robust.
....
[ 2761.961309] [drm] PCIE GART of 256M enabled (table at 0x000000F400000000).
[ 2761.966012] amdgpu: can't get the mac of 5
[ 2768.224812] amdgpu: VI should always have 2 performance levels
[ 3206.767528] perf: interrupt took too long (2504 > 2500), lowering kernel.perf_event_max_sample_rate to 79000
....
[ 4301.900744] perf: interrupt took too long (3141 > 3130), lowering kernel.perf_event_max_sample_rate to 63000
```

> journalctl

Nothing.

**Comment by tjapro** [comment]
Now the program doesn't stayed unresponsible.

**Comment by johnny-bit** [comment]
> Now the program doesn't stayed unresponsible.

with no change in hw or software such behaviour indicates usually either thermal throttling or swapping problem. And since now darktable is responsive and you have all the tools necessary to next time diagnose problem, please consider closing the issue.

**Comment by tjapro** [comment]
I forgot to add some images (during operation and after operation):

1st try:
![1](https://user-images.githubusercontent.com/7900361/124265407-89645f80-db2d-11eb-88f3-999adea30c61.png)
![2](https://user-images.githubusercontent.com/7900361/124265411-8a958c80-db2d-11eb-9b9c-9842ac9eb05c.png)

2nd try:
![3](https://user-images.githubusercontent.com/7900361/124265414-8b2e2300-db2d-11eb-9e0a-75a434b3e197.png)
![4](https://user-images.githubusercontent.com/7900361/124265415-8b2e2300-db2d-11eb-9f97-f7cba9e1b60c.png)

**Comment by johnny-bit** [comment]
As you can see - each export process causes significant bump in mem usage and grinds all cores. Also see that your swap usage gets bigger and bigger. In extreeme conditions you could reach the state of swapping which would cause the system to slow down to a crawl.
Since you haven't shown thermals/frequency we can't see/monitor thermal throttling. - which would also slow the system down to a crawl (i know, i experienced that firsthand).

lastly:

>Now the program doesn't stayed unresponsible.

so... please close the issue :)

**Comment by tjapro** [comment]
> so... please close the issue :)

Ok, If occours later, I'll reopen it.

**Comment by johnny-bit** [comment]
of course! But fist please make sure that the system isn't being throttled or isn't pegged for memory (swapping).

aslo: 8GB ram and 2cores (4 cpu threads) is really recommended minimum which can get swamped by some intensive processing so do take that into consideration :)
