### ISSUE TITLE
Backtrace error when using retouch module

### ISSUE THREAD

**Issue by spdqueen** [darktable-org/darktable#9369]
I used the retouch module and encountered a backtrace error which is attached per the error message.
[darktable_bt_B52H50.txt](https://github.com/darktable-org/darktable/files/6750320/darktable_bt_B52H50.txt)

**Comment by Nilvus** [comment]
The txt file is quite empty and you didn't precise any infos to help reproduce and know which system (config, OS, darktable release, etc.) asked when opening an issue. It will so be impossible to help and understand how this could happen.

Thus, a new darktable release with some improvements, fixes in some modules, will be released his saturday.

I so close this one. Please wait to see darktable 3.6 release and test again with this 3.6 release. If you can reproduce, just open a new issue with as much information asked in issue model as possible. Thanks.

**Comment by spdqueen** [comment]
Appreciate the quick response. Next time I will be more specific :). I think I resolved the issue. I uninstall and reinstalled darktable with the latest version that's on the darktable.org site. I think I had an outdated version. Currently, I'm able to use the retouch module without anything issue so far and I'll be sure to look for the 3.6 release.  Thanks!
