### ISSUE TITLE
Panasonic GH5M2

### ISSUE THREAD

**Issue by peti** [darktable-org/darktable#9370]
I have uploaded all requested samples to <https://raw.pixls.us/>.

I uploaded two sets: one with Adobe RGB and one with sRGB. Now, I have the sneaking suspicion that the color space doesn't matter for RAW, actually, which means that you'll have two copies of these images in every aspect ratio. I'm sorry about that.

**Comment by Nilvus** [comment]
The color space in camera is indeed only for jpg, not raw. Anyway, thanks for providing raw.

**Comment by peti** [comment]
I'm sorry, but I am still confused. I uploaded the requested RAW files to the darktable repository months ago. Is there anything left that I can do to help this issue progress?

**Comment by Nilvus** [comment]
Just read that following comment: https://github.com/darktable-org/darktable/issues/9328#issuecomment-886574852

And remember that it is free and opensource software made by people in their free time.

**Comment by kmilos** [comment]
@LebedevRI Although GH5M2 claims to be PanasonicRaw v6, compression seems somewhat different to the S series: because it is 12-bit instead of 14-bit data, I had to set `PixelsPerBlock=14` in order to get `haveBlocks` and `numBlocks` to match, so that needs to be parametrizable... The image still looks a bit weird after that though...

**Comment by asbachb** [comment]
@kmilos I don't know of it's helpful, but it seems that `libraw` added support for that model: https://github.com/LibRaw/LibRaw/commit/2a9a4de21ea7f5d15314da8ee5f27feebf239655

**Comment by pgassmann** [comment]
@asbachb Can you tell me if there is a ready-to-use software that is based on libraw? or any other free software to process the raw files?

**Comment by asbachb** [comment]
@pgassmann sorry I'm not aware of any.

**Comment by asbachb** [comment]
Have yochecked current darktable release? From my understanding the files should be readable as libraw should now support the camera?!

**Comment by pgassmann** [comment]
@asbachb I tried with darktable-4.0.1 now. but its not supported. the `libraw20` package on my ubuntu system is still on version 0.20.2 which is the latest release. gh5m2 support is still only in the beta version or on the master branch in source code.

**Comment by asbachb** [comment]
I had another look into it. From my understanding raw processing is done by `rawspeed` not `libraw`.

@shoffmeister @LebedevRI I saw you were part of bringing support of GH5S support. Do you think we need to to something similar for GH5M2?

**Comment by shoffmeister** [comment]
I am on a G9 only, so I cannot comment on the GH5M2, I am afraid.

**Comment by asbachb** [comment]
@shoffmeister thanks for your feedback.

I wonder if we just need to add the camera to camera.xml just like for GH5S: https://github.com/darktable-org/rawspeed/commit/d982cabc845892f695034be035cc9f29c0c9e8db

**Comment by pgassmann** [comment]
@peti Wrote that he uploaded samples to  https://raw.pixls.us/ . But the GH5M2 is not listed in the available samples, but also not in the missing list: https://raw.pixls.us/?missing#repo

@asbachb Don't know if copying the settings from GH5S will work as @kmilos wrote that it has a different format. https://github.com/darktable-org/darktable/issues/9370#issuecomment-996021411

**Comment by asbachb** [comment]
@pgassmann When I search for GH5M2 I'm able to find the samples.

I see. I missed that comment.

**Comment by AndrewManHayChiu** [comment]
I'm also keen to have the GH5M2 supported in Darktable.

What's the workaround for now? Convert raw files to DNG?
