### ISSUE TITLE
Makernote corruption on Pentax DNG export

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#9371]
See https://discuss.pixls.us/t/invalid-tiff-directory-tags-are-not-sorted-in-ascending-order/25678 and https://github.com/Exiv2/exiv2/issues/1757#issuecomment-873018564 

Confirmed w/ recent Windows 3.5.0+2591~gb8df223ce build using exiv2 0.27.4

**Comment by johnny-bit** [comment]
darktable doesn't mess explicitly with Pentax DNG Tags... so wouldn't that be more of a case for exiv2? Or does darktable need to implement workaround? (imo exif stuff should vendor-agnostic if possible and any low-level ops done by specific data handlers - in this case exiv2)

**Comment by kmilos** [comment]
IMHO this is on dt: exiv2 can't know that you're changing image formats on export, so one has to make a careful transition from DNGPrivateData (exclusive to input DNG) to a MakerNote inside an ExifIFD dt crates and attaches to TIFF, JPEG, etc.

**Comment by parafin** [comment]
Or just throw them away maybe?

**Comment by cytrinox** [comment]
I've worked a lot with DNG spec these days. The requirements for DNGPrivateData is:

- The private data must start with a null-terminated ASCII string identifying the data. The first part of this string must be the manufacturer's name, to avoid conflicts between manufacturers.
- The private data must be self-contained. All offsets within the private data must be offsets relative to the start of the private data, and must not point to bytes outside the private data.
- The private data must be byte-order independent. If a DNG file is converted from a big-endian file to a little-endian file, the data must remain valid.

So if Pentax fulfill these requirements, it should be safe to transfer the DNGPrivateData tag.

**Comment by kmilos** [comment]
The problem is that one is exporting a TIFF, or JPEG, etc.

There is no DNGPrivateData tag in those formats.

**Comment by cytrinox** [comment]
> There is no DNGPrivateData tag in those formats.

Can't speak for JPEG but for TIFF you can simply copy such tags. Readers should always ignore unknown tags in TIFF. It gives you the chance that readers like exiv2 are aware of this tag and can handle it.

**Comment by kmilos** [comment]
And it's not only that, exiv2 tries to be too clever and interprets DNGPrivateData as PentaxDng Makernote, with the same 0xc634 tag value. I have a suspicion we have both in the Exif data structure and try to write 0xc634 twice on export...

So we either drop both DNGPrivateData AND PentaxDng if we think no app can use this, or make an effort to transform the latter to an Exif compliant Pentax Makernote at 0x927c (dropping DNGPrivateData as well in the process).

**Comment by kmilos** [comment]
Yep, `exiftool -v2` confirms the 0xc634 duplication on export ([tested on DNG and PEF from RPU](https://raw.pixls.us/data/Pentax/K-1%20Mark%20II/)):

```
  | Warning = Duplicate tag 0xc634 MakerNotePentax5 in IFD0
  | 39) MakerNotePentax5 (SubDirectory) -->
  |     - Tag 0xc634 (23512 bytes, undef[23512])
  | + [MakerNotes directory with 115 entries]
```

No problem w/ PEF as MakerNote there is already at 0x927c inside the Exif IFD, so there's no confusion.

**Comment by johnny-bit** [comment]
Reading this again... and... If I'm not mistaken both pentaxDngMakernotes and DNGPrivateData should be removed within `dt_exif_read_blob` and currently only DNGPrivateData is removed? So it should be enough to remove it?

**Comment by kmilos** [comment]
What I don't get is how we end up w/ duplicate 0xc634 tags even though DNGPrivateData is seemingly removed?

Unfortunately I can't find the time for a debug session...
