### ISSUE TITLE
bauhaus: allow sliders/curves to be reset without double-click

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9375]
Now that the new input system has been merged, virtually the only thing stopping me from bringing my Wacom tablet out of mothballs is the fact that it doesn't do double-click very well (because the tip almost always moves between clicks), meaning that I have a great deal of difficulty resetting bauhaus sliders and tone curves.

Does anyone object to also including an alternate method of resetting sliders? Perhaps ctrl+shift+clicking on the slider or on the label?

**Comment by dterrahe** [comment]
Gtk has a property gtk-double-click-distance which sounds like it should be useful in avoiding your issue as well. Not sure where one would configure it though...

**Comment by elstoc** [comment]
I've tried configuring things like that in my mouse settings and they never seem to make much difference.
