### ISSUE TITLE
NG Input: shortcut search is unintuitive and no clues are given

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9378]
Use Ctrl+F to search for a shortcut in preferences > shortcuts. A few useability issues for me:

- It's far from obvious that the up/down keys cycle through the search results - I stumbled upon this by accident
- The search generally locates entries at the bottom of the screen and I naively tried to scroll to get the found entry to the middle of the pane. I was surprised to find that scroll also went backwards and forwards through entries
- Once I had found what I wanted I naively pressed Enter to dismiss the search which instead tried to set a shortcut for the located entry
- I then tried to press Escape to escape from the madness and was asked if I wanted to delete shortcuts 

I know that an extensive manual entry will be required for all of this, but I think we can make something a bit more obvious for the search functionality. I still much prefer the search UI that previously existed (obviously I wrote it so I'm biased) as it was clearly signposted and fairly obvious what it did and how (though it would have been better with Ctrl+F shortcut as well).

**Comment by dterrahe** [comment]
The incremental search is standard gtk functionality and may therefore be familiar to a section of users. I _much_ prefer incremental search over "type your whole search term" and then enter and get no feedback which character was the first without match. The forward/backward keys are crucial to make that even more useful.

Yes, the first time you use it, it is unintuitive and surprising. This describes dt. I would be sad if we traded power for "user friendliness" (for the type of user that is likely to soon abandon dt anyway). I like that it doesn't waste space in a dialog that by necessity is already crowded.

Having said all that, I haven't tried using gtk_tree_view_set_search_entry  but the discription suggests it would allow putting a permanent gtkentry somewhere that feeds the incremental search. I suppose it would still have all the behaviour you find problematic, but at least it would be somewhat more discoverable, at the cost of wasting two extra lines. Or one, if we can put both search boxes, for actions and shortcuts, at the bottom, together with future import export reset buttons.

**Comment by elstoc** [comment]
The advantage of a permanent entry is that we can have a tooltip explaining how it works. Don't know if we can also have buttons as alternative to arrow keys.

**Comment by johnny-bit** [comment]
>  A few useability issues for me:

Actually that's native gtk behaviour working according to their HID guidelines... which is... sometimes surprising.

> Or one, if we can put both search boxes, for actions and shortcuts, at the bottom, together with future import export reset buttons.

Quite frankly that would be great.

**Comment by elstoc** [comment]
> that's native gtk behaviour 

That's a great argument but I've been using Gtk apps for years and if I'm still confused by it, and I bet others will be as well. I would assume people likely haven't encountered all this stuff before because nobody's ever known it existed. It is pretty well hidden.
