### ISSUE TITLE
Input System NG: w keyboard shortcuts switches to permanent preview

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9381]
**Describe the bug/issue**
pressing w to open preview switches to preview mode but never returns after releasing
the behaviour depends on the duration of the pressed key: 
if the key is pressed very short the preview occurs and is closed again 
if the key is hold a bit longer it switches into full size preview mode, but this can't evev be terminated by hitting escape
like full size preview icon below the thumbtable i can switch to other images if the filmstrip is active, but not leave it by es -just by switching the mode e.g. by pressing x and then leave the split view via esc

**To Reproduce**
1. select image in lighttable
2. press w and hold a bit --> preview is displayed
3. release w --> preview keeps being displayed

**Platform**

darktable version : darktable-3.7.0+178~gfb034c530
OS : OSx

**Comment by johnny-bit** [comment]
Same for Linux so you can drop osx :)
