### ISSUE TITLE
OSX: Input System NG: arbitrary recognition of shift+ctrl if midi devices (keyboards) are attached

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9384]
**Describe the bug/issue**
Just pressing shift and ctrl and c is usuallly recognized as a plain "c" 
best way to get this accel is to hold ctrl and shift key and press c several times. 
unfortunately it's behaves very arbitrary ... sometimes even the first attempt is successful

**To Reproduce**
1. edit shortcutsrc and replace cmd by ctrl to avoid the issue with cmd recognition.
2. try to copy paste in lighttable or darkroom via shift+ctrl+c
3. get a message "c not assigned" 
4. keep holding shift and ctrl and press c several times until the dialog appears
repeat this several times since the first attempt might be successful ;)

**Platform**
* darktable version : darktable-3.7.0+178~gfb034c530
* OS                : OSx

**Comment by dterrahe** [comment]
Unfortunately I cannot reproduce :-(
Is this only when using _both_ shift and ctrl, or also with only one?

**Comment by MStraeten** [comment]
even one of them - ctrl+c or cmd+c (after the fix) needs several attempts to be detected.
pressing cmd+c results in "c not assigned"
pressing cmd+a results in "a not assigned" after a few attempts select all is done

it seems to be a sideeffect of having midi devices attached. After disconnecting everything it's fine ...

**Comment by MStraeten** [comment]
downloaded a midi monitor and checked if there're events around - nothing. 
is there a way to define midi sources to be ignored?

**Comment by dterrahe** [comment]
> it seems to be a sideeffect of having midi devices attached. After disconnecting everything it's fine ...

Yep; reproduced! So the loop that is updating the midi lights is clearing the mods. Should be fixable.

> is there a way to define midi sources to be ignored?

Not yet. There definitely is a bit of work to be done in the area of midi configuration.

**Comment by dterrahe** [comment]
This is reproducable under Windows but not under Linux (for me).

Seems like gdk_keymap_get_modifier_state is not portable/doesn't work as expected under Windows and OSx.
