### ISSUE TITLE
Applying style causes image to go black (Mac, 3.6)

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#9385]
**Describe the bug/issue**
When applying a style, it causes the image to go black. This occurs when applied in either darkroom or lighttable.

**To Reproduce**
1. Open an image (raw or otherwise)
2. Apply a style in either darkroom or lighttable. Image turns black.

**Expected behavior**
Image should not turn black.

**Screenshots**
Here is the image as it appears when first opened, and whenever you reset or discard history.
![reset](https://user-images.githubusercontent.com/69561443/124349663-c450bb00-dc33-11eb-9f6b-64320d3a1037.png)

Here is the resulting image in darkroom when style is applied.
![apply style darkroom](https://user-images.githubusercontent.com/69561443/124349675-da5e7b80-dc33-11eb-8974-60863200980a.png)

And here is the same image (top left thumbnail) in lighttable.
![apply style lighttable](https://user-images.githubusercontent.com/69561443/124349687-ea765b00-dc33-11eb-8c60-202c05eed89d.png)

**Which commit introduced the error**
The last version I used 3.4.1 did not have this error. Today I downloaded the new release 3.6, which has the issue. However I noticed my .dmg says 3.6.0.3 and the program it self says 3.6.0+3~g4287791fe

**Platform**
* darktable version : .dmg says 3.6.03 and the program it self says 3.6.0+3~g4287791fe
* OS                :  Mac OS Sierra 10.12.6
* Memory            : 4 GB 1600 MHz DDR3
* Graphics card     : Intel HD Graphics 4000 and NVIDIA GeForce GT 650M
* OpenCL installed  : Y
* OpenCL activated  : Not sure how to check but it was working on 3.4.1

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? Have reproduced on raw, png and tiff.
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? Y
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? Don't know how to do this.
 - Do you use lua scripts? Not to my knowledge.

**Comment by johnny-bit** [comment]
What style?

**Comment by SoupyGit** [comment]
I tried on many for the same result. Here is one:
[Fast Default (7.5.21).dtstyle.txt](https://github.com/darktable-org/darktable/files/6758270/Fast.Default.7.5.21.dtstyle.txt)

However I notice now the issue does not occur on all styles. For example, here is one that works fine, does not produce black:
[t3mujinpack - Color Negative_Kodak Portra 160.dtstyle.txt](https://github.com/darktable-org/darktable/files/6758275/t3mujinpack.-.Color.Negative_Kodak.Portra.160.dtstyle.txt)

**Comment by SoupyGit** [comment]
Actually, it seems now not to do with styles at all. I have just opened an old edit and it too is black. It also exported black. Here is the xmp:
[_DSC0377_05.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/6758284/_DSC0377_05.NEF.xmp.txt)

It does not happen with all my old edits, only some. Will see if I can spot the difference in modules.

**Comment by MStraeten** [comment]
you need to activate "clip negative rgb from gamut" in color calibration

**Comment by SoupyGit** [comment]
Yes that solved the issue. Thanks!

**Comment by Nilvus** [comment]
So this could be closed.
