### ISSUE TITLE
darktable 3.6 windows version does not have Lua support

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#9393]
**Describe the bug/issue**
The windows build of dt 3.6 appears to have been built without Lua support

**To Reproduce**
1. Install darktable 3.6 on windows
2. Open a terminal
3. Run the command "\Program Files\darktable\bin\darktable.exe" -- version
4. See output
```
this is darktable 3.6.0
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```
5. Notice Lua support disabled

**Expected behavior**
Lua support should be enabled

**Platform**

* darktable version : 3.6.0
* OS                : Win 7

**Comment by kmilos** [comment]
I guess this because msys now ships lua 5.4 in the repo, so a manual step involving installing 5.3 explicitly is required.

G'MIC support is also missing.

**Comment by johnny-bit** [comment]
HUH... The build should use then internal lua interpreter AFAIK

**Comment by wpferguson** [comment]
That was always my understanding because I don't think there is a windows installer package that puts the Lua libs in the right place.

**Comment by phweyland** [comment]
> G'MIC support is also missing.

I've just checked it works. Could you describe a bit more ? Have you cleared the build folder before building ?

**Comment by wpferguson** [comment]
I've built a 3.6.0 package with Lua enabled using the instructions for building a generic package.  Tested on Win 7 and Win 10.

**Comment by wpferguson** [comment]
Tested with luts3d and it also works so G'MIC is included

**Comment by Haribo-66** [comment]
Good to know that is is possible and working.

Will there be an updated installer coming?

Enable LUA would be great for the NIGHTLY packages as well! 

Thanks for your help.

**Comment by Mark-64** [comment]
Yeah, it's the same as in #8563.
Following the Windows build instructions you get no lua. Manual install of mingw-w64-x86_64-lua version 5.3.x is required

**Comment by wpferguson** [comment]
@Haribo-66 there is an updated installer coming.  In the meantime, you can download it from here: https://drive.google.com/file/d/1K2ozGFmusMpTdnrY87bVS2PlmfANyqNA/view?usp=sharing

**Comment by TurboGit** [comment]
Closing now, Installer uploaded in our release page. Thanks!
