### ISSUE TITLE
Input NG regression : cannot add | in tag module

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#9397]
**Describe the bug/issue**

Cannot enter a hierarchical tag in tag module. The pipe character cannot be entered in the tagging entry.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'lighttable'
2. Select tagging module
3. Click on 'entry'
4. Try entering 'parent|child'
4. See error, cannot enter |

**Comment by TurboGit** [comment]
@dterrahe : One for you :)

**Comment by TurboGit** [comment]
Forgot to say that it could be because I'm using a French keyboard since | is accessible with `AltGr 6`

**Comment by dterrahe** [comment]
Somewhat related to this issue https://github.com/darktable-org/darktable/pull/9373#issuecomment-873196178 (messages generated for {}[] shortcuts)

Gtk doesn't seem to flag AltGr as a modifier key. I'll need to find a workaround.
