### ISSUE TITLE
Black squares, crash with color calibration and color assessment conditions mac 3.6.0.3

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#9399]
**Describe the bug/issue**
This perhaps follows on from #9385 where it was determined the black image I was seeing in both darkroom and lighttable was due to "clip negative rgb from gamut" being unticked in color calibration. However with more use, I've discovered the issue doesn't end there.

Here is the screenshot showing black squares appearing in lighttable. Those black squares are not present when viewed in darkroom. xmp: [_DSC0371_01.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/6759407/_DSC0371_01.NEF.xmp.txt)

![Screen Shot 2021-07-04 at 3 12 44 pm](https://user-images.githubusercontent.com/69561443/124374033-2d3f3e00-dcdb-11eb-9a61-9f34587b4927.png)

The program also crashed while playing around with Color Calibration 1 (2nd instance) I think I was in either colorfulness or brightness tab.

As you can see, both instances of color calibration have "clip negative rgb from gamut" ticked.

Here is another screenshot:
![Screen Shot 2021-07-04 at 3 28 21 pm](https://user-images.githubusercontent.com/69561443/124374208-ae4b0500-dcdc-11eb-995b-5d12dfe30576.png)
And xmp:
[_DSC0307_06.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/6759420/_DSC0307_06.NEF.xmp.txt)

What is happening here? Well, I have multiple instances of color calibration. I turn on color assessment conditions. I turn off color calibration 2, and the image goes black. Noticeably, this only happens when the color assessment conditions are turned on. However sometimes it goes black when the module is turned off. And sometimes it goes black when the module is turned off then on again.

Here is the same image, but a different way of turning the image black:
![Screen Shot 2021-07-04 at 3 33 11 pm](https://user-images.githubusercontent.com/69561443/124374272-3fba7700-dcdd-11eb-8a0b-5aa3163c1356.png)

To reproduce this one, in the same xmp as above, move to colorfulness tab of color calibration 6 and change saturation algorithm from version 1 to version 3, with color assessment conditions on.

All of the above occurs on old edits - that is, edits that were made on 3.4.1. The issues did not occur in 3.4.1, they have only occurred since upgrading to 3.6.0+3~g4287791fe 
I have tried to recreate on fresh edits made in 3.6.... by resetting history, adding multiple instances of color calibration, and applying all sorts of weird and wonderful adjustments - but I can't recreate. It only seems to happen on edits that were first made in 3.4.1

I am wondering if it is something to do with the different saturation algorithm in colorfulness tab. Check this.

Opacity 100%:
![Screen Shot 2021-07-04 at 3 44 58 pm](https://user-images.githubusercontent.com/69561443/124374504-23b7d500-dcdf-11eb-8be5-e11983671530.png)

Opacity 65% (despite less opacity, it somehow got MORE saturated):
![Screen Shot 2021-07-04 at 3 45 24 pm](https://user-images.githubusercontent.com/69561443/124374509-3a5e2c00-dcdf-11eb-8297-91408a0392f1.png)

But wait... opacity 65% (now less saturated. Only difference being whether I went down from 100<65% opacity, or up from a lesser value, say 50>65% opacity):
![Screen Shot 2021-07-04 at 3 45 44 pm](https://user-images.githubusercontent.com/69561443/124374515-48ac4800-dcdf-11eb-84c2-79705f31ada4.png)

[_DSC0345.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/6759437/_DSC0345.NEF.xmp.txt)
That xmp has Version 1 selected for saturation algorithm as per screenshots. If I instead select version3, it behaves as expected.

However, as per the xmp for _DSC0307_06 provided, i am able to reproduce the black image even when the color calibration module does not display saturation algorithm version.

**Which commit introduced the error**
_3.6.0+3~g4287791fe
Was working fine on 3.4.1

**Platform**
* darktable version : e.g. _3.6.0+3~g4287791fe
* OS                : Mac OS Sierra 10.12.6
* Memory            : 4 GB 1600 MHz DDR3
* Graphics card     : Intel HD Graphics 4000 and NVIDIA GeForce GT 650M
* OpenCL installed  : Y
* OpenCL activated  : Y I think. It was on 3.4.1

**Comment by SoupyGit** [comment]
A further update. Sometimes toggling the clipping indicator on/off can cause a color shift. After doing that, its possible the thumbnail in lighttable shows different colors from the image in darkroom. The color shift is the same as if color calibration had simply been turned on and off. In other words, the difference between white balance module D65 with no color calibration, and white balance module D65 with color calibration set to x (eg. 3950k, or any other value).

**Comment by Nilvus** [comment]
@aurelienpierre: what do you think of that one?

**Comment by aurelienpierre** [comment]
darktable 3.4 did not have OpenCL kernel for color calibration, so let's split the problem here. Please try again with OpenCL off and report. Once we have assessed how the CPU path behaves, we can investigate the OpenCL one.

**Comment by SoupyGit** [comment]
OK I deactivated gpu in darktable settings, but it is still problematic:
![Screen Shot 2021-07-04 at 11 01 22 pm](https://user-images.githubusercontent.com/69561443/124386169-78c60c00-dd1c-11eb-9f9d-c07e03b8ce08.png)

Compressing history momentarily solved the problem, but it came back later. Toggling the clipping indicator still produced black when in color assessment.

> Also, ditch masking. That's not helping and completely irrelated.

I certainly won't be ditching masks in my editing workflow - its one of the great advantages of darktable - but for the sake of testing this issue I turned all color calibration masks off by hitting the X, and the issue remains:

![Screen Shot 2021-07-04 at 11 11 17 pm](https://user-images.githubusercontent.com/69561443/124386324-39e48600-dd1d-11eb-80b3-878c090c70aa.png)

**Comment by aurelienpierre** [comment]
@SoupyGit can you test the PR that tries to fix that ?
