### ISSUE TITLE
darktable 3.6.0 crashes when turning local contrast on and off in Quick Access Panel

### ISSUE THREAD

**Issue by Macchiato17** [darktable-org/darktable#9403]
**Description / Reproduction sequence**
Import a RAW, then go to darkroom view. In Quick Access Panel activate Local Contrast. Then deactivate it again. Perhaps you need to repeat this sequence once again. Then darktable will crash with an access violation in module libgtk-3-0.dll (crashdump attached).
[darktable_bt_WO0950.txt](https://github.com/darktable-org/darktable/files/6759701/darktable_bt_WO0950.txt)

The crash does NOT occur when you turn on/off (even several times) this module in the "full" module interface, i.e. not in Quick Access Panel.

**Expected behavior**
Please don't crash ;-)

**Platform**
* darktable version : 3.6.0
* OS                : Win10 (20H2 19042.1052, latest Patches applied)
* Memory            : 7,4GB
* Graphics card     : dual - Intel HD 530 (3,7GB) + NVIDIA Geforce 940MX (5,7GB)
* Graphics driver   : Intel -> 27.20.100.8854 / NVIDIA -> 27.21.14.5749
* OpenCL installed  : yes
* OpenCL activated  : no

**Additional context**
 - tested with two types of RAW (NEF and NRW)
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - see stacktrace attached to this BUG

**Comment by AlicVB** [comment]
it looks very similar to #9386 
but of course I can't reproduce... and the backtrace doesn't provide useful infos...
- can you try with opencl deactivated ?
- can you try with a empty config dir (backup first) ?
- does it happen with all "built-in" layout manager presets (click on the hamburger icon in the modulegroups line) ?

Thanks !

**Comment by Spidermarc** [comment]
crashdumps on my system of similar problems:
simply switching on or of (sometimes several times) **any** module in quick access panel or moving a slider in one of the quick access panel modules crashes darktable.

darktable version : 3.6.0
OS : Win10 pro  19041.1052
Memory : 128GB
Graphics card :  NVIDIA Quadro RTX 4000
Graphics driver : NVIDIA -> 27.21.14.6259

Additional context

    tested with NEF files (Camera Nikon D500)
    


[darktable_bt_4D6J60.txt](https://github.com/darktable-org/darktable/files/6759816/darktable_bt_4D6J60.txt)
[darktable_bt_6GQ350.txt](https://github.com/darktable-org/darktable/files/6759817/darktable_bt_6GQ350.txt)
[darktable_bt_18W150.txt](https://github.com/darktable-org/darktable/files/6759818/darktable_bt_18W150.txt)
[darktable_bt_799B60.txt](https://github.com/darktable-org/darktable/files/6759819/darktable_bt_799B60.txt)
[darktable_bt_AZP950.txt](https://github.com/darktable-org/darktable/files/6759820/darktable_bt_AZP950.txt)
[darktable_bt_BYH050.txt](https://github.com/darktable-org/darktable/files/6759821/darktable_bt_BYH050.txt)
[darktable_bt_IVWC60.txt](https://github.com/darktable-org/darktable/files/6759822/darktable_bt_IVWC60.txt)
[darktable_bt_R7OC60.txt](https://github.com/darktable-org/darktable/files/6759823/darktable_bt_R7OC60.txt)
[darktable_bt_S14950.txt](https://github.com/darktable-org/darktable/files/6759824/darktable_bt_S14950.txt)
[darktable_bt_SG5250.txt](https://github.com/darktable-org/darktable/files/6759825/darktable_bt_SG5250.txt)
[darktable_bt_UED550.txt](https://github.com/darktable-org/darktable/files/6759826/darktable_bt_UED550.txt)
[darktable_bt_WO0950.txt](https://github.com/darktable-org/darktable/files/6759827/darktable_bt_WO0950.txt)

**Comment by Macchiato17** [comment]
Thanks for you rquick reply. Ups, didn't realize the request you mentioned, even though I did a query. But anyhow...
 - openCL is alread deactivated in darktable settings
 - I also tried "denoise (profiled)", "exposure" and "color calibration" with the same result
 - starting darktable with an empty config directory => works without crash.

By changing one option by another with this default config, I think I found which toggle is responsible for the crashing: as soon as I set (activate) the option "expand the module when it is activated, and collapse it when disabled", then the crash will occur as described. Disabling this option again won't result in a crash anymore.

**Comment by Spidermarc** [comment]
disabling "expand the module when it is activated, and collapse it when disabled" solved the issue also for me

**Comment by AlicVB** [comment]
great. Thank you for the help !
Your finding is very helpful...
I don't reproduce the crash, but I've manage to get lot of gtk-critical... so I think I will be able to do something !

**Comment by AlicVB** [comment]
@Macchiato17 @Spidermarc  : I think that PR #9410 should fix it (it avoid the gtk-critical here). By any chance, are you able to test it ? (you need to compile from source)

**Comment by Macchiato17** [comment]
I will try to compile your branch on my machine, cloning was already successful ;-)

**Comment by johnny-bit** [comment]
Current master should have this fixed :) plz confirm.

**Comment by Macchiato17** [comment]
@AlicVB and @johnny-bit -> I compiled [0d72ed4269] on master (already containing a merge of @AlicVB 's fix). No crash anymore, even if the mentioned option is activated now. Works like a charm. Thanks a lot for your effort to fix this 👍 🥇 Have a good time...
