### ISSUE TITLE
Quick Access Panel does not show modules content (many are hidden and cannot be opened) - Darktable  v3.6.0.3- OSX Big Sur 11.4 @ Apple Silicon M1

### ISSUE THREAD

**Issue by rfeg** [darktable-org/darktable#9412]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Describe the bug/issue**
Quick Access Panel does not show all modules content, it shows only the title. The modules that show some content are "Color Balance rgb", "Exposure", "Crop And Rotate"
Activating them does not show content below, going to module and back, sometimes show more, bit others remain "closed" with no option to open.

I'm using: OSX Big Sur 11.4 / Apple Silicon M1 / Darktable  v3.6.0.3

**To Reproduce**
1. install in OSX Big Sur 11.4 (did not check other versions) in Apple Silicon (did not check Intel)
2. Open Darktable
3. select an image on lighttable
4. Go to darkroom
5. Open Quick Access Panel
6. See that modules can be activated but most you can not see content, remaining closed
7. going to real module and back does not solve the issue
8. sometimes activist one module temporarily show first line of color calibration

**Expected behavior**
See module content right from Quick Access Panel and interact with it

**Screenshots**
![QAP_1](https://user-images.githubusercontent.com/65315402/124401048-ebd08200-dd1e-11eb-917f-b2a95ebe4f90.png)

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0.3
* OS                : OSX Big Sur 11.4
* Linux - Distro    : n/a
* Memory            : 16G
* Graphics card     :  Apple M1
* Graphics driver   :  Supported, Metal GPUFamily Apple 7
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              :  n/a
* Desktop           :  
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **n/a**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) ªª NO ªª
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no** N/A
 - Do you use lua scripts? ªª NO ªª
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by elstoc** [comment]
This is entirely as expected. We have added commonly-used controls to the quick access panel as a starting point and you should add other controls as you see fit. Some modules just require the on/off button to have an effect so for these we have only included these buttons.

When you raise issues please _read_ the issue template and delete the unnecessary text. You have included a lot of this instructional detail in your issue which makes it hard to see what your actual problem is. If text is not giving _us_ useful information, its presence in your issue is not useful.

**Comment by rfeg** [comment]
My apologies, it was my first post.

Sidenote: some quick access panel should have more controls: e.g. "crop and rotate" should have also crop controls and not only angle rotate (including lining up picture). I will add these modules to quick access panel.

rfeg

**Comment by elstoc** [comment]
I believe the basic principle was to start off by reproducing the controls that used to be on the basic adjustments module
