### ISSUE TITLE
DT dies with "ERROR: iop order looks bad, aborting." after upgrade.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#9413]
Ubuntu 20 WSL
Built DT 3.7. Upgraded from a DT 3.5.
Ran the new DT executable.
Saw the following:
Dialog popup for DB upgrade. Allowed it. Then window disappeared.
Shell that started DT had the following:
```
[imageop_init_presets] updating 'bloom' preset 'MULTIPLY' from blendop version 10 to version 11
[imageop_init_presets] updating 'demosaic' preset 'SLOW' from blendop version 10 to version 11
[dt_ioppr_check_so_iop_order] missing iop_order for module vibrancergb
ERROR: iop order looks bad, aborting.
```

Tried running DT again.

```
[dt_ioppr_check_so_iop_order] missing iop_order for module vibrancergb
ERROR: iop order looks bad, aborting.
```

**Comment by johnny-bit** [comment]
Clean up your build and install dirs. `vibrancergb` was removed since it never reached stable ver.

**Comment by chhil** [comment]
Clean build/install fixed it. Thank you.
