### ISSUE TITLE
Raw Chromatic Abberations module says error, but no further details given

### ISSUE THREAD

**Issue by abnormally-distributed** [darktable-org/darktable#9414]
The new raw chromatic abberations module does not appear to work for raw files from the Sony DSC-F828 camera. I suspect that this is due to the four color RGBE color filter array the sensor in the camera has. However, the old chromatic abberations module from 3.4.1 never had an issue with this camera. This camera definitely benefits from chromatic abberation correction, so is there a way to access the old chromatic abberations module in 3.6.0? Or is support for this camera going to be added at a later date perhaps?

**Comment by elstoc** [comment]
We have provided an issue template to help guide you as to the information that we need in order to analyse a bug. Please review that template and provide the requested information. FYI the "raw chromatic aberrations" module _is_ the same as the old "chromatic abberations" module, just renamed and with an added control. My understanding is that the raw chromatic aberrations module does indeed assume a Bayer filter array. Perhaps you would have more success with the new "chromatic aberrations" module, which does not depend on undemosaiced input data.

**Comment by jenshannoschwalm** [comment]
The non-standard-bayer -> non-working assumption is true and it never worked before. In 3.6 we just inform the user :-)

**Comment by abnormally-distributed** [comment]
> We have provided an issue template to help guide you as to the information that we need in order to analyse a bug. Please review that template and provide the requested information. FYI the "raw chromatic aberrations" module _is_ the same as the old "chromatic abberations" module, just renamed and with an added control. My understanding is that the raw chromatic aberrations module does indeed assume a Bayer filter array. Perhaps you would have more success with the new "chromatic aberrations" module, which does not depend on undemosaiced input data.

Hi, I didn't utilize the template because it did not seem like an issue where the hardware and operating system details would be pertinent. In any case, after using the new chromatic abberations module, it gives decent results generally. However, I find that to adequately eliminate all fringing the defringe module is necessary on not just the Sony DSC-F828, but my other cameras with standard color filter arrays. I think the defringe module should be un-deprecated personally, but I ought to make a feature request for this, I imagine.

**Comment by elstoc** [comment]
Agreed that some of that information might not be applicable but the only information you gave us was that the module "does not appear to work" which is far short of the information that we need to investigate an issue.
