### ISSUE TITLE
Crop and rotate module behaves erratically

### ISSUE THREAD

**Issue by eezacque** [darktable-org/darktable#9418]
Looks like this bug has been reported repeatedly in the past, without a proper fix.
For me, this renders darktable useless, so it is a showstopper.

Every now and then, the crop and rotate module stops working properly.
Symptoms, which do not always occur:
- the guides used for cropping are not shown
- the numbers shown while cropping do not make sense, they are negative or 0
- the preview is blank
- the main view is blank or grayed out

I added some screenshots
![Screenshot from 2021-07-05 14-33-01](https://user-images.githubusercontent.com/37875990/124473212-55907080-dd9f-11eb-80b5-9c40030dc284.png)
![Screenshot from 2021-07-05 14-34-14](https://user-images.githubusercontent.com/37875990/124473481-ae600900-dd9f-11eb-8207-c165266fdae7.png)
![Screenshot from 2021-07-05 14-36-10](https://user-images.githubusercontent.com/37875990/124473610-d2bbe580-dd9f-11eb-9bd6-e9e8279cfcd3.png)
![Screenshot from 2021-07-05 14-38-20](https://user-images.githubusercontent.com/37875990/124473736-f4b56800-dd9f-11eb-9f1d-5508bb825b45.png)
![Screenshot from 2021-07-05 14-39-16](https://user-images.githubusercontent.com/37875990/124473848-1adb0800-dda0-11eb-9517-e5c2ee1fc641.png)

**Platform**

* darktable version : 3.6.0, 3.4.1
* OS                : Linux kernel 5.4.0-77-generic
* Linux - Distro    : Ubuntu 20.04.2 LTS
* Memory            :  16 GB
* Graphics card     :  Intel® HD Graphics 4600 (HSW GT2)

**Comment by elstoc** [comment]
Please can you retry with the crop module in darktable 3.6. We're in the process of deprecating the crop & rotate module because it's very hard to maintain.

**Comment by eezacque** [comment]
On 05/07/2021 15:24, Chris Elston wrote:
>
> Please can you retry with the crop module in darktable 3.6. We're in 
> the process of deprecating the crop & rotate module because it's very 
> hard to maintain.
>
Works for me, thanks! Please add an explicit warning to the original 
crop and rotate module, to save users from wasting their time!

-- 

Grinnikend door het leven...

**Comment by elstoc** [comment]
We will when it's fully deprecated. For now it's still a necessary evil for rotate and keystone corrections.

**Comment by ralfbrown** [comment]
Perspective correction can do the fine rotation, if you don't mind not being able to drag the mouse along a horizontal or vertical line to set the rotation.  In principle, it could also do the keystone correction, but setting the shift and skew sliders correctly by hand is nearly impossible.

**Comment by elstoc** [comment]
Agreed - this is already discussed in #8834.
