### ISSUE TITLE
Request: Add ability to preview sharpen module's unsharp mask

### ISSUE THREAD

**Issue by TeknikalDomain** [darktable-org/darktable#9425]
**Is your feature request related to a problem? Please describe.**

More of a mild inconvience than a *problem,* when using the *sharpen* module, there's no way to preview the calculated unsharp mask (USM), which leads to me doing a lot of guess-and-check to make sure that my threshold is set in the right place to target the areas I intend, without sharpening anything unintended, like noise.

**Describe the solution you'd like**

Add some ability to toggle a preview of the USM, similar to a mask display, or, with 3.6, something similar to the "display blending mask" button within the demosaic module, this way I could, say, enable displaying of the USM, tweak the threshold until it looks about right for my intentions, and then turn that display off.

**Alternatives**

Currently, I can kinda hack together this functionality by using a parametric mask, displaying that, and modifying the mask details threshold until I get to something that looks good, and then setting the module's threshold parameter to 0, which does work perfectly fine, but feels a little bit like I'm working around a glaring feature deficiency.

**Additional context**

Admittedly, this could just be a **me** issue, I've used Rawtherapee a lot before switching to Darktable, and within RT, there's a pretty prominent button to toggle displaying the sharpening mask in effect.
Not that anyone probably **needs** to see that, but this is what that looks like, for reference:

![Rawtherapee's "Preview sharpening contrast mask" feature, for reference](https://user-images.githubusercontent.com/17773093/124514959-42d06880-ddac-11eb-9bff-d2a44eeae162.png)

**Comment by TurboGit** [comment]
This is already possible by using an uniform blending and selecting the fusion "difference". Not as easy than a single button, but at least achievable, I'm using this from time to time.

**Comment by TeknikalDomain** [comment]
Having just tested that out, seems that method is missing some details, I can see modifications being made that don't get highlighted with that approach.
