### ISSUE TITLE
denoise (profiled) not working in 3.6 (jpg)

### ISSUE THREAD

**Issue by andrewk8** [darktable-org/darktable#9426]
**Describe the bug/issue**
darktable 3.6 on Windows 10 x64.  This happens on all JPG (4 I've tried).

I have a photo taken at ISO 160 that has quite a bit of noise in solid-colored areas that are out of the focus plane. Turning on denoise (profiled), DT says “found match for ISO 160”. But I don’t see any change toggling the module on and off. In 3.4, the module defaults would give a visible noise reduction.

**To Reproduce**
1. Open jpg in darkroom
2. exposure module, enable compensation for camera exposure
3. filmic rgb module, click auto tune levels
4. denoise (profiled). turn on.  Observe message (e.g. found match for ISO 160).  Observe no change to the display (i.e. still noisy).

At this point, changing the sliders doesn't change the display.  Picking the camera model from the profile (ILCE-6400 iso 160) doesn't change the display. Changing the blend color space between scene and display doesn't change the display.

Setting the mode to wavelets and the color mode to RGB changes the histogram (slightly) but not the display.  You can toggle denoise (profiled) on/off and see a slight change in the histogram, but not the display.  Resetting the parameters to defaults reverts to the above behavior (i.e. toggling denoise (profile) doesn't affect the display or histogram).

**Expected behavior**
display shows noise reduction.

**Screenshots**
![2021-07-05 13_49_27-darktable](https://user-images.githubusercontent.com/16465258/124515190-cab67280-ddac-11eb-8119-686d26821cba.png)

**Screencast**

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
Installed from the official Windows x64 binary.

* darktable version : 3.6.0
* OS                : Windows 10
* Memory            :  32 GB
* Graphics card     :  NVidia GeForce GTX 1660
* Graphics driver   : NVidia 466.77
* OpenCL installed  :  Y? (see output below)
* OpenCL activated  : 
` C:\Program Files\darktable\bin>darktable-cltest.exe
0.126174 [opencl_init] opencl related configuration options:
0.128112 [opencl_init]
0.128827 [opencl_init] opencl: 1
0.129716 [opencl_init] opencl_scheduling_profile: 'default'
0.131286 [opencl_init] opencl_library: ''
0.132575 [opencl_init] opencl_memory_requirement: 768
0.134156 [opencl_init] opencl_memory_headroom: 400
0.135647 [opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
0.137591 [opencl_init] opencl_mandatory_timeout: 200
0.140182 [opencl_init] opencl_size_roundup: 16
0.141662 [opencl_init] opencl_async_pixelpipe: 0
0.143082 [opencl_init] opencl_synch_cache: active module
0.144900 [opencl_init] opencl_number_event_handles: 25
0.146486 [opencl_init] opencl_micro_nap: 1000
0.147401 [opencl_init] opencl_use_pinned_memory: 0
0.148802 [opencl_init] opencl_use_cpu_devices: 0
0.150333 [opencl_init] opencl_avoid_atomics: 0
0.151967 [opencl_init]
0.156789 [opencl_init] found opencl runtime library 'OpenCL.dll'
0.159011 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded
0.347240 [opencl_init] found 1 platform
0.348769 [opencl_init] found 1 device
0.349935 [opencl_init] device 0 `NVIDIA GeForce GTX 1660' has sm_20 support.
0.352173 [opencl_init] device 0 `NVIDIA GeForce GTX 1660' supports image sizes of 32768 x 32768
0.354941 [opencl_init] device 0 `NVIDIA GeForce GTX 1660' allows GPU memory allocations of up to 1536MB
[opencl_init] device 0: NVIDIA GeForce GTX 1660
     GLOBAL_MEM_SIZE:          6144MB
     MAX_WORK_GROUP_SIZE:      1024
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 64 ]
     DRIVER_VERSION:           466.77
     DEVICE_VERSION:           OpenCL 3.0 CUDA`

**Additional context**
denoise (profiled) with JPG was working on DT 3.4.

**Comment by wpferguson** [comment]
Did you install from the darktable-3.6.0 or darktable-3.6.0.1 link?

**Comment by andrewk8** [comment]
> Did you install from the darktable-3.6.0 or darktable-3.6.0.1 link?

It is 3.6.0.

Does 3.6.0.1 have a bug fix for this?

**Comment by Nilvus** [comment]
> > Did you install from the darktable-3.6.0 or darktable-3.6.0.1 link?
> 
> It is 3.6.0.
> 
> Does 3.6.0.1 have a bug fix for this?

First package was wrongly built (with some missing dependencies. 3.6.0.1 fix missing dependencies. So better install it and try it. You will see if it fixes your issue or not.

**Comment by rawfiner** [comment]
I cannot reproduce the issue on linux
Have you tried on jpg from different cameras and iso values?
Do you see any effect by setting strength to huge values (1000 for example)?
Also, could you try without opencl?

**Comment by Thanatomanic** [comment]
I cannot reproduce on my own Windows `release-3.6.x` build. In some cases no profile is found, but noise reduction is always visible in all JPEGs I tested. However, sometimes the effect is _very_ small initially, but when you crank up the Strength, it always works.

Note: the effect of profiled denoising is vastly different for the raw file and an exported jpeg of the same image. I don't know if that is expected behavior, but I can imagine it is.
