### ISSUE TITLE
define pipeline-wise scene-referred white value

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#9427]
**Context**

Scene-referred workflow means white can have any luminance value > 100%. However, some functions like power exhibit a particular behaviour in [0 ; 1] that require normalization by the white value to get the expected behaviour. Such normalizations happen:

* in color balance RGB (white fulcrum),
* in tone equalizer (mask exposure compensation),
* in all LUT-based modules (3D LUTs and tonecurves – they don't happen yet, but they should),

Then, filmic makes use of the scene white corrected by all earlier modules to define the upper bound of its tone mapping.

**Problem**

When editing pictures in batch, only one of them is fully edited (look and corrections), then the edit is transferred to the other pictures of the same series.

Global exposure minor tweaks are however necessary on a picture-wise basis. In this case, all settings of scene white for normalization purposes need to be manually re-adjusted in all the modules that use it. It is unnecessarily time consuming.

**Solution**

1. Create a "global exposure" module. This one would apply the base exposure that is default in scene-referred, would not be allowed multiple instances, but will also define a scene-referred white exposure for the whole pipeline.
2. Create a `compute_white()` method in the IOP API. This will use, as input, a virtual 9×9 image with the center 3×3 pixels inited to the global exposure scene-referred white. Each module implementing that method will run its own `process()` method with current params on top of that image. At the end, the central white value will serve as an update of the scene-referred white at this stage of the pipe. If the module instance is using drawn mask, `compute_white()` will be bypassed.
3. Allow "auto" or "pipeline" setting for all modules using scene white as a normalization, reading the updated white at the current place in the pipe.

The reason for using an image rather than a single value is to support modules applying blurs and local filters. This also allows a completely blind evaluation of the white point, that doesn't require a-priori knowledge of the internals of the module.

**Comment by ralfbrown** [comment]
That reminds me of something I held off on raising as an issue while the final push to 3.6 was on: clipping and LCh reconstruction in the highlight reconstruction module make an assumption which is broken by the modern color adaptation: that no further modules will mess with the white balance, so the white it outputs will stay white.  Given that most of the photos I take are in lighting with a color temperature below 6500K, areas clipped by the highlight reconstruction module tend to turn cyan after the color calibration module (and with the reference WB red multiplier on a D7200 being nearly 3, that happens a lot even without sensor saturation).  Bumping up the clipping threshold fixes that about half the time.

The approach you describe above sounds like it may also solve the HR/ColorCalibration mismatch.
