### ISSUE TITLE
Windows installer does not ship glib translations

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#9433]
**Describe the bug/issue**

glib (and other dependencies?) translations are not shipped w/ the dt Windows installer, so some UI elements remain unlocalized.

See e.g. https://github.com/darktable-org/darktable/pull/9261#issuecomment-874880256

**Platform**

* darktable version : 3.6.0.1
* OS                : Win10

**Additional context**

Inkscape Windows installer e.g. ships glib and gtk translations in addition to their own, so does GIMP...

**Comment by wpferguson** [comment]
I'll look at how Inkscape and GIMP do it and see if I can make it fit...

**Comment by parafin** [comment]
You might want to check macOS bundle list: https://github.com/darktable-org/darktable/blob/master/packaging/macosx/darktable.bundle

I include gtk translation, but not glib (not sure what glib translation gives). Also iso_639 translation is include for language names in preferences.

There's other stuff aside from translations in there too... Maybe something is missing. I guess I should compare files installed on macOS and on Windows at some point.

**Comment by wpferguson** [comment]
Thanks @parafin.  You were on my list of people to ask about packaging.  I looked at your bundle and then went and finally found all the translation files under /mingw64/share/locale.   Now I just need to add them to the cmake so they get copied over as part of the build process.

**Comment by wpferguson** [comment]
@parafin I decided what mo files to add based on the way darktable runs when built under msys2.  When you just install you have access to all of the msys2 translation files, so that's what I ended up adding to the package.  I looked up some of them and they were dependencies installed for gtk.  I'll add them to my weekly build this week and let people test them to see if things get cleared up.

**Comment by kmilos** [comment]
Something still doesn't look quite right w/ the just released 3.6.1 install package: I have `C:\Program Files\darktable\share\locale\LC_MESSAGES\` with a bunch of translations, but don't know which locale they belong to (I presume the last `zu` in the list)? Individual locale folders still contain only the `darktable.mo` and `iso_639.mo` translations.

And I'm not sure we really want to include all of these msys2 present translations for all the locales, the package will grow substantially.

**Comment by wpferguson** [comment]
I'll take a look at this and see what's going on

**Comment by wpferguson** [comment]
I coded populating the translations separately, then ended up merging it with the IsoCode stanza.  It appears that something got lost in the merge, `${language}`, which now evaluates to an empty string, so everything got shoved into `share/LC_MESSAGES`

**Comment by kmilos** [comment]
I'm weirdly still missing e.g. `en_GB` glib translations in the nightly installer (in fact, any `en` variant, `en_CA` also has glib translations), while almost all others are there? It looks like detection for locale shipping is done solely on `iso_639.mo`, perhaps that is too restrictive?

**Comment by kmilos** [comment]
@wpferguson GIMP and Inkscape ship any the following translations for whatever local they exist, i.e. _unconditionally_:

```
glib20.mo
gtk20-properties.mo
gtk20.mo
iso_15924.mo
iso_3166.mo
iso_3166_2.mo
iso_4217.mo
iso_639.mo
iso_639_3.mo
libexif-12.mo
```

and

```
glib20.mo
gtk30.mo
gtkspell3.mo
```

**Comment by wpferguson** [comment]
Can you download last Sunday's snapshot that I built and check that.  Here's the link - https://drive.google.com/file/d/1F1RLclQ6z79fM87ggPSxQFby9betEGmL/view?usp=sharing  I have a step in my build script where I populate the translations to make sure everything is there.

**Comment by kmilos** [comment]
I don't see `en_GB` translations in the `darktable-3.9.0+6~gc6e8ed544-win64.exe` either...

**Comment by kmilos** [comment]
@wpferguson While we're on the installer topic, [the lensfun database shipped is also not recent](https://github.com/darktable-org/darktable/pull/10650).
