### ISSUE TITLE
darktable segfaults when told to print an image with a selected area, if nothing was dragged&dropped into that area.

### ISSUE THREAD

**Issue by jpellegrini** [darktable-org/darktable#9435]
**Describe the bug/issue**

darktable segfaults when told to print an image with a selected area, if nothing was dragged&dropped into that area.

**To Reproduce**

1. Go to the print view
2. Select an image area, but do NOT drag&drop any image on it
3. Try to print
4. darktable segfaults!

Trying to reference the image that was not dropped, I suppose.
There's a backtrace (se at the end of the report)

**Expected behavior**

Either:
* darktable prints the image ignoring that selected area, or
* darktable pops up an error message

**Platform**

* darktable version : git commit `66e79e18fc20613fbdf4947649e0318ab23c8665`
* OS                : `Linux socrates 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux`
* Linux - Distro    : Debian sid
* Memory            :  32Gb
* Graphics card     : AMD Radeon (TM) R9 380 Series (TONGA, DRM 3.40.0, 5.10.0-7-amd64, LLVM 11.0.1) 
* Graphics driver   : amdgpu
* OpenCL installed  : yes
* OpenCL activated  : no (darktable cannot use it, no Image support)
* Xorg              :  1:7.7+22
* Desktop           : blackbox
* GTK+              : libgtk-3-dev:amd64            3.24.24-4
* gcc               : 10.2
* cflags            : did not change, used default from darktable's build system
* CMAKE_BUILD_TYPE  : ?

**Additional context**

 - Can you reproduce with another darktable version(s)? **did not try**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**

**Backtrace**

[darktable_bt_0AR250.txt](https://github.com/darktable-org/darktable/files/6772290/darktable_bt_0AR250.txt)

**Comment by johnny-bit** [comment]
And to think that in all my testing of new print module it didn't occur to me to print without image :/

btw: your version string looks trippy 3.1.0+7477... while it "normally" should be 3.7.0+... (but that has nothing to do with your issue)
