### ISSUE TITLE
Importing with "add to library..." not working on 3.6.0 on Windows 10 under certain conditions

### ISSUE THREAD

**Issue by javimm77** [darktable-org/darktable#9436]
Hello.

I've been experiencing a problem with the new import module under Windows.
I've been using darktable for a few weeks now. My usual workflow is copying my images from the SD card under a folder I create manually. Then I import my pictures in several programs (C1, Lightroom) and now darktable.
As I don't want my pictures to be moved, I use the "add to library..." function. This method worked perfectly in 3.4 both under Windows 10 and Ubuntu. I use a dual boot system, with a shared data 2TB SSD with my pictures.

Since updating darktable to 3.6.0, "add to library..." does not work under Windows 10, but it does under Ubuntu.
Darktable reports that a number of pictures have been imported, but they don't appear anywhere. In Ubuntu, the pictures just appear as expected.

After some testing, I've discovered that **the issue is caused by the use of accents in the path** . I'm spanish and my folders contain accents in some cases. For instance, if the pictures are in "d:\javimm\Downloads\Cámaras" , the pictures are not imported, but if I use a folder with no accents ie "d:\javimm\Downloads\Camaras", the pictures are then imported and eberything is fine, so the issue is caused by accents in the path.

Regards.

**Comment by johnny-bit** [comment]
Windows needs path normalization :/ again. That's always trippy tbh.

**Comment by mmhh76** [comment]
Same problem for me in Windows. But works in Ubuntu. I am swedish and we are using åäö in our alphabet. So can't use those letters in Windows, if I want to use Darktable 3.6.

It's always something that doesn't work in Windows ;).

**Comment by bengtfalke** [comment]
I have the same problem. After the import all looks fine and I can work with the photos. But after I restart Darktable they are gone from the DB however they are in the proper location in the file system so I can easily add them to the DB again.

**Comment by daenur** [comment]
I have the same problem with a folder name in Russian Cyrillic

**Comment by PontiacCZ** [comment]
I confirm this issue, the import procedure success really depends on diacritics/accents in the file path on Windows 10.  :-(
