### ISSUE TITLE
The main window doesn't load on MacOS 

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#9438]
Hi!
It has been one or two weeks I had not compiled Darktable.
I just did it and there is a bug on the actual version : just after lauching, Darktable doesn't finish loading the main window (see picture) and loads forever...

![22a](https://user-images.githubusercontent.com/75432524/124670000-a4c7c580-deb3-11eb-914f-d5fe23f51152.jpg)

A bisect search showed that the first bad commit is [e3da6ed5420321d83d48153488f8587d864f963f] **"Input System NG"**
from **Dec 02 2020** and apparently merged recently. 🤷‍♂️

* OS                : MacOS 10.15.7 (19H1030)
* Memory            :  16 Go 133MHz
* Graphics card     :  Radeon RX 580 8 Go
* OpenCL             : yes 
* gtk mac bundler  : 0.7.4
* CMAKE_BUILD_TYPE  :  Release

I applied the last changes from BUILD.txt, tried compiling again but no luck.

**Comment by johnny-bit** [comment]
Can you try cleaning up your build and install dirs and then rebuild? That should help.

**Comment by Jiyone** [comment]
I delete usr\local and darktable\build folder and compile, all this using a script ...
I don't know if there is something else to clean. 🤷‍♂️

**Comment by Jiyone** [comment]
I've deleted ~/ports and restarted all instalation from build.txt and now it works fine. 👍
I believe it was an issue with one of those lib, strange that it didn't solved with a 'sudo port upgrade' ...
Thank you anyway :)
