### ISSUE TITLE
Silverfast DNG Raw Files shown as corrupt

### ISSUE THREAD

**Issue by 0x10** [darktable-org/darktable#9447]
I imported some DNG Files which were created by Silverfast (Film-Scanning Tool, Settings 48-Bit HDR RAW) and Darktable imports them, but shows them as corrupt. 

Exiftool data is fine (see 
[exiftool.log](https://github.com/darktable-org/darktable/files/6780206/exiftool.log)) and ufraw is able to process the image.
The images are quite big (~240MB) but if needed you can download one here: https://deadlock.cc/ImageDng.tar.gz

**Platform**
* darktable version : 3.4.1
* OS                : Linux - Kernel 5.7.7-gentoo
* Linux - Distro    : Gentoo
* Memory            :  32GB
* Graphics card     : AMD Vega RX
* Graphics driver   :  Mesa
* OpenCL installed  : yes, but darktable shows it as "not available"
* OpenCL activated  : no, darktable shows it as "not available"
* Desktop           :  openbox

 - Can you reproduce with another darktable version(s)? unknown

**Comment by mmhh76** [comment]
I downloaded the dng and tried it in Darktable 3.6. In Ubuntu 21.04. I get the same error as you. Can't open it at all in Darktable.
But I can open it in a software called Shotwell, which is in many Linux distributions installed by default.

If I in Shotwell go to the menu File -> Save as... and choose another name. Now I can open the dng file in Darktable. But the dng file is now only 6.7 MB.

Maybe Silverfast save some information to the DNG that Darktable doesn't support. Or maybe the DNG file is too big for Darktable. But Shotwell is just a simple image viewer and it can open your dng.

**Comment by kmilos** [comment]
@mmhh76 Shotwell probably extracted and saved just the "lower" quality preview (see "Preview TIFF" inside the attached exiftool log).

@0x10 This is a (less usual) 3-channel LinearRaw DNG, but luckily not compressed, and should in theory work... Are there any more clues in the error message? You can also run darktable from CLI as `darktable -d all` and inspect/attach the log.

**Comment by kmilos** [comment]
If Silverfast allows you to change the output resolution/dpi, please also upload a sample to [RPU](https://raw.pixls.us/).

**Comment by 0x10** [comment]
Wow thanks for the responses!
I can provide a smaller file in a few hours (when I'm home from work). 

@kmilos I ran darktable-cli and got following output:
```
$ darktable-cli Bild_120_01886.dng bild_out.png

[rawspeed] (Bild_120_01886.dng) virtual std::unique_ptr<rawspeed::RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData*), line 91: No decoder found. Sorry.
[dt_imageio_export_with_flags] mipmap allocation for `bild_out.png' failed
```

**Comment by kmilos** [comment]
Hm, for some reason it fails to be detected as a DNG/TIFF...

At this point you can only [create new camera support issue](https://github.com/darktable-org/darktable/issues/new?assignees=LebedevRI&labels=scope%3A+camera+support&template=new_camera_support.md&title=%3CEnter+your+camera+name+here%3E) (I guess use scanner model + software instead of camera name) and supply the small (<10MB) low res sample at RPU. You can close this one after.

**Comment by 0x10** [comment]
I will go this way, thanks @kmilos 
How long does it typically take, until I can provide feedback?

**Comment by 0x10** [comment]
Ah, quite interesting. I just created a smaller file for reporting, but the smaller file can be read by darktable...
So maybe its a size issue?

**Comment by kmilos** [comment]
Do you mind sharing a link to that one as well?

**Comment by 0x10** [comment]
Of course! Here you go. 
[Bild_120_01913_raw.dng.tar.gz](https://github.com/darktable-org/darktable/files/6786601/Bild_120_01913_raw.dng.tar.gz)

**Comment by kmilos** [comment]
Also, the link to the original large one is not working currently?

**Comment by 0x10** [comment]
Sorry... I prematurely deleted the file... Its online again. 
https://deadlock.cc/ImageDng.tar.gz

**Comment by kmilos** [comment]
They have slightly different TIFF structure (the large file has an additional IFD1 image inside, which seems to be another preview),  maybe that confuses rawspeed...

You could start increasing the output slightly until you get the same structure (I check w/ `exiftool -v` for more details), or is there a setting to include/exclude this preview? In any case, uploading 240 MB to RPU is not reasonable, would be nice to reproduce this with a smaller sample...

**Comment by 0x10** [comment]
Thank you for your investigation @kmilos .
I scanned a full set of variations (unfort. there are not options for "scan as raw") of a sample image I can provide under CC0.
And I can reproduce the bug with a smaller image!
Here are the downloads:
https://deadlock.cc/dt_dng_test/SampleImage_Full_1600ppi.dng (70MB, reported as corrupt)
https://deadlock.cc/dt_dng_test/SampleImage_Crop3_3200ppi.dng (100MB, reported as corrupt)
https://deadlock.cc/dt_dng_test/SampleImage_Full_3200ppi.dng (250MB, reported as corrupt)

https://deadlock.cc/dt_dng_test/SampleImage_Crop1_3200ppi.dng (5MB, is read correctly)
https://deadlock.cc/dt_dng_test/SampleImage_Crop2_3200ppi.dng (10MB, is read correctly)
https://deadlock.cc/dt_dng_test/SampleImage_Full_1280ppi.dng (40MB, is read correctly)
https://deadlock.cc/dt_dng_test/SampleImage_Full_150ppi.dng (<1MB, is read correctly)
https://deadlock.cc/dt_dng_test/SampleImage_Full_300ppi.dng (3MB, is read correctly)
https://deadlock.cc/dt_dng_test/SampleImage_Full_320ppi.dng (3MB, is read correctly)
https://deadlock.cc/dt_dng_test/SampleImage_Full_640ppi.dng (10MB, is read correctly)
https://deadlock.cc/dt_dng_test/SampleImage_Full_800ppi.dng (16MB, is read correctly)

**Comment by kmilos** [comment]
Yep, the difference between the working full 1280dpi DNG and "corrupt" 1600dpi one is still the additional IFD1 and the weird "PreviewTIFF" structure that probably throws rawspeed off.

![image](https://user-images.githubusercontent.com/4973094/125052678-870d8280-e0a4-11eb-8af8-eff603799eba.png)

Actually, you might want to report this to Silverfast, as that DNG is not really compliant to TIFF/EP or DNG spec.

**Comment by 0x10** [comment]
Okay, if I write a script/tool which removes these superfluous IFD1 structure, then darktable is able to read them?
Would be an option for me, as it doesn't seem to affect the actual image data.

**Comment by kmilos** [comment]
Could be worth a shot I guess, maybe exiftool can do it already... Unfortunately I don't know anything about this "PreviewTIFF" structure apart from what's written [here](https://exiftool.org/TagNames/Extra.html), and don't have time right now to try to figure it out. Asking on exiftool forum or discuss.pixls.us might be helpful as well.

**Comment by 0x10** [comment]
I'll take this one. I will close this issue for now and investigate further. If removing doesn't work, I may reopen a ticket with further information.

Thanks for your time and patience @kmilos! I really appreciate that.

**Comment by kmilos** [comment]
Please share your findings if you do, as it might be helpful to others. If not, should probably start a new issue and discussion over at [rawspeed](https://github.com/darktable-org/rawspeed/issues) directly.

**Comment by 0x10** [comment]
Good point... I will open a follow up issue on rawspeed. 
I tried removing the metadata and it does not seem to be directly connected to the IFD1 block.. but more in the follow up issue.
