### ISSUE TITLE
NG Input: Can't assign "h" to a keyboard shortcut

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9449]
Tried to assign "h" key to the haze removal module and the full-screen keyboard shortcut summary appeared instead while the h key was depressed.

When I tried to do the same thing via the preferences dialog, the the same thing happened. However, this time I could not dismiss the shortcut summary screen or switch to another application. I had to reboot my PC to resolve.

3.7.0+229~g85ea5120c

**Comment by HansBull** [comment]
Similiar behaviour on current master on Plasma 5.12.9 no OpenCL when exiting from darkroom to lighttable, pressing ctrl+e to export. Impossible to switch to another application or even to console. Had to ssh into the machine and kill the darktable process.
