### ISSUE TITLE
Darktable crashes when I attempt to edit another image, e.g another duplicate, by single mouse click on the image in the thumbnail, in darkroom

### ISSUE THREAD

**Issue by OK-One** [darktable-org/darktable#9450]
**Introduction**

**Describe the bug/issue**

Darktable crashes, with an exception, in the darkroom, when I attempt to open a different duplicate, by single click on the thumbnail in the row of images, at the bottom of the screen.

The two autogenerated bug reports for two occasions when this has happened is attached.

I'm on Windows 10 - i5-4200U (dual core, 4 hyperthreaded cores), 8GB RAM laptop.

The first time this occurred I was running version 3.6

The second time this occurred, I was running version 3.6.0.1 with the config directory using the same config (Database, etc) created clean install by version 3.6.

[darktable_bt_KLFY50.txt](https://github.com/darktable-org/darktable/files/6780588/darktable_bt_KLFY50.txt)
[darktable_bt_RX5I60.txt](https://github.com/darktable-org/darktable/files/6780589/darktable_bt_RX5I60.txt)

**To Reproduce**

I cannot pinpoint exactly why it does not occur every time I attempt to edit another duplicate, using the same method, clicking on a thumbnail at the bottom of the darkroom screen.

Strange. But the crash is consistent with this specific action, cos it has occured twice, while I did the same action, even though, I can go a whole day editing images, and not experiencing the disruption/crash.

**Expected behavior**

Darktable should not crash.

**Screenshots**

**Screencast**

**Which commit introduced the error**

**Platform**

I'm on Windows 10 Home - Version	10.0.19042 Build 19042 64 bit.
Processor	Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz, 2301 Mhz, 2 Core(s), 4 Logical Processor(s)
GPU's

Adapter Description	AMD Radeon HD 8850M
Adapter RAM	(2,147,483,648) bytes
Installed Drivers	aticfx64.dll,aticfx64.dll,aticfx64.dll,amdxc64.dll
Driver Version	15.201.1101.0

+

Adapter Description	Intel(R) HD Graphics Family (Integrated GPU)
Adapter RAM	1.00 GB (1,073,741,824 bytes)

Open CL is enabled in the settings, to accelerate using multiple GPU's.

**Additional context**

**Comment by elstoc** [comment]
Please can you tidy up this bug report to remove the unnecessary information from the bug template. It's very hard to separate the information you have provided from the guidance in the template.

**Comment by johnny-bit** [comment]
the error is essentially "reading from location -1" in `dt_gui_quit_callback`

**Comment by OK-One** [comment]
> Please can you tidy up this bug report to remove the unnecessary information from the bug template. It's very hard to separate the information you have provided from the guidance in the template.

Done
