### ISSUE TITLE
Spellcheck for tags and metadata

### ISSUE THREAD

**Issue by GitFr33** [darktable-org/darktable#9452]
I would be interested in attmpting to implement spellchecking if there is a library that someone can recommend.

**Comment by johnny-bit** [comment]
The "official" library recommended by gnome as of my recent readings of gnome wiki is [gspell](https://gitlab.gnome.org/GNOME/gspell)

Keep in mind that we must NOT depend on it and it has to be at best optional.

**Comment by parafin** [comment]
There are aspell and myspell, which are not GNOME-related.
