### ISSUE TITLE
TAB key no longer works properly in Export module

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#9459]
This is similar to closed #8661.

Pressing the Tab key from the second pixel size in Export causes the side panels to disappear.

dt master today 3.7.0+245~g05f381e95

**Comment by elstoc** [comment]
I think the only difference here is that on the previous version you needed to hit tab twice before that happened, which was perhaps better behaviour. May have been introduced by NG Input. @dterrahe?

**Comment by TurboGit** [comment]
Yes definitely a regression from NG input system.

**Comment by dterrahe** [comment]
What is the behavior you'd want me to recreate? That the first tab is silently swallowed and the second is handled by the shortcut system as normal? Is pressing tab on the last entry something people regularly do? Even when they don't expect any useful result?

Pressing tab yet again shows the panels again, so there's not too much damage done...

Personally, I'd find it more useful if focus moved to the Export button (and if Enter then triggered it).

**Comment by RawConvert** [comment]
It used to be the tab is "silently swallowed" but putting focus on the export button seems better so you can then just press Enter.

**Comment by elstoc** [comment]
Well generally when you're tabbing between inputs the tab key removes focus from one input and transfers it to another. So if you're on the last input box, the tab should take focus away from the input and give it back to whatever is handling key presses for the view (for example, until you tab away you can't use the arrow keys to navigate the lighttable). Having the tab key both remove focus from the input and then also perform some keyboard shortcut action is disconcerting. 

Observe the same thing happening when you tab out of the search input in the darkroom. I for one always tab away from search when I'm done.

**Comment by RawConvert** [comment]
If you tab off export button, go to first pixel size field?

**Comment by todd-prior** [comment]
Bit off topic but Ctrl+A is not working in Win10  for me ..
![image](https://user-images.githubusercontent.com/44409419/124998171-ee322500-e019-11eb-854e-7d02eee651ea.png)

**Comment by phweyland** [comment]
Other modules like geotagging, metadata, and probably some others are impacted as well.

When a module field has the focus, Tab should move the focus to the next field and should not be treated on the global window (toggle the side panels).

**Comment by dterrahe** [comment]
I haven't had time to thoroughly investigate solutions yet. They might have side effects or cause new bugs so I'll have to experiment and test.
