### ISSUE TITLE
Ctrl+A not working...no way to select all files in FileManager view...could not find entry in new presets either

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#9464]
My apologies if i am missing something but it seems at least in Windows...ctrl A is no longer defined and so you can't use it to select all files....

I tried to look through the new presets and only found a reference for select file not all files....

![image](https://user-images.githubusercontent.com/44409419/124998809-0a829180-e01b-11eb-90da-7f33a76cb201.png)

EDIT: Seems to be defined in config file after some deeper digging

**Comment by darkelectron** [comment]
Works for me. One easy way to find out if its assigned, is to use the `define shortcuts` button (found between `preferences` button and `question mark` button) and then click on the `select all` button in `select' module.

**Comment by s7habo** [comment]
I can confirm the problem.
For me it only works when I open "select" menu in lighttable. Otherwise not.

darktable 3.7.0~git244.86e542c125-1 on Kubuntu 20.04

**Comment by todd-prior** [comment]
For me it seems defined in shortcutsrc the config file for these definitions...it just doesn't seem to work???

bracketleft=lib/timeline/start selection
bracketright=lib/timeline/stop selection
a;ctrl=lib/select/select all
a;shift;ctrl=lib/select/select none
b=global/toggle panels collapsing controls
b;shift;ctrl=global/toggle bottom panel
c;ctrl=lib/copy_history/copy
c;shift;ctrl=lib/copy_history/copy parts
d=global/darkroom view

**Comment by todd-prior** [comment]
Update so when I first open DT and add new files to the library it creates the collection but does not activate it. I really can't say if that happened before but I never recall having to activate the collection. If I do that then it works as expected selecting all the images in the collection....

**Comment by s7habo** [comment]
@todd-prior 

Please do an experiment. Close "select" subwindow in lighttable and try Ctrl+A (should not work). Unfold it and try again (should work).

**Comment by s7habo** [comment]
For example, in the darkroom I have instructed "s" to create the snapshot. shortcut works if the right side window where the menu for snapshot is visible. But if I close all side windows with "TAB", shortcut does not work anymore.

**Comment by todd-prior** [comment]
You are right that is what I see that so if the selected files buttons are collapsed then Ctrl+a doesn't work....this may then be the case for a bunch of potential actions....
