### ISSUE TITLE
Crashes using pipette to perform auto selection or optimizations   

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#9468]
Using dev build 3.7+277 on Windows 10.

I seem to be getting quite a few crashes when using any of the auto pipettes in filmic or the second tab of color balance rgb. Example to have filmic set white relative with the picker....
[darktable_bt_DKEH60.txt](https://github.com/darktable-org/darktable/files/6788871/darktable_bt_DKEH60.txt)
[darktable_bt_D0E050.txt](https://github.com/darktable-org/darktable/files/6788872/darktable_bt_D0E050.txt)

See files attached

**Comment by s7habo** [comment]
#9470

**Comment by wpferguson** [comment]
Same line of code as #9480
