### ISSUE TITLE
[DT 3.7]  The keyboard shortcuts work only if corresponding menu items are visible/active/opened

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#9469]
I just found out from issue #9464 that keyboard shortcuts behavior has basically changed in darktable 3.6/3.7. Keyboard shortcuts work only if corresponding entries or menus are visible or active. 

In some cases this leads to unnecessary limitation of usability. 

An example is described in issue #9464. Ctrl+a selects only if the "select" menu in lighttable is expanded. Here is the short screen capture:

https://user-images.githubusercontent.com/38165484/125025512-143fdf80-e083-11eb-8618-0f12f95bc942.mp4

Another example is my use of the keyboard shortcut "s" for creating a snapshot in darkroom. I used this keyboard shortcut to create a snapshot in full screen with closed side panels. This was very useful to compare before and after photos without disturbing side panels. This in turn I use as thumbnail for Youtube videos. Here is an example: 

![Darktable_38](https://user-images.githubusercontent.com/38165484/125025586-3b96ac80-e083-11eb-8d9d-3e3ffbf9a49f.jpg)

This is not possible anymore:

https://user-images.githubusercontent.com/38165484/125026294-88c74e00-e084-11eb-8234-013e48387527.mp4

**Expected behavior**

Keyboard shortcuts should work regardless of the visibility/activation of the corresponding menu. 

**Platform**

* darktable version :3.7.0~git277.0f575bc2bd-1
* Linux - Distro    : Kubuntu 20.04
* OpenCL activated  : yes

**Comment by dterrahe** [comment]
@s7habo many thanks for reporting this bug.

I believe #9431 now fixes this issue. If you are able to compile pull requests and test, I would be grateful if you would report back any further similar issues; the "activatable" logic may need further refinement.

**Comment by s7habo** [comment]
@dterrahe thanks for your effort! I'm sorry I can't compile it, but once the fix is merged in master I'll test it and report back.
