### ISSUE TITLE
Darktable crashes when using white/contrast gray fulcum color picker in color balance rgb module

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#9470]
**Describe the bug/issue**

Darktable crashes when using white/contrast gray fulcum color picker in color balance rgb module

**To Reproduce**

1. Open corlor balance rgb module
2. Go to "masks" tab and click on one of color picker in section "treshold" (white or contrast gray fulcrum)

Darktable crashes.

[darktable_bt_TMZG60.txt](https://github.com/darktable-org/darktable/files/6789325/darktable_bt_TMZG60.txt)

* darktable version : 3.7.0~git277.0f575bc2bd-1
* OS                : Linux
* Linux - Distro    : Kubuntu 20.04
* Memory            : 
* Graphics card     : GeForce GTX 1070
* Graphics driver   : nvidia 460.80
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by TurboGit** [comment]
Indeed, can reproduce !

**Comment by s7habo** [comment]
This bug is connected #9468

**Comment by s7habo** [comment]
This behavior might have to do with the color picker _in general_. I just had a crash when using the color picker with color look up module.
