### ISSUE TITLE
FR: Consolidate guide lines and add shortcuts

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9471]
As part of the recent guide generalisation in #8891 we no longer have the ability to change the type of guide lines that are overlaid on the image with a keyboard shortcut (you used to be able to allocate them to a dynamic shortcut in the C&R module).

In order to make the shortcut easier to use, it might also be worth consolidating the golden mean "extras" combobox into the guide lines combobox, perhaps with the following entries:

golden sections
golden spiral sections
golden spiral
golden mean (all guides)

Obviously we'll still need the extra grid comboboxes and the flip guides combobox but one less would be nice.

The ability to toggle guides in the separate distort modules via a shortcut would also be useful.

**Comment by AlicVB** [comment]
I completely agree here.
For the shortcuts, I'll have to learn how to define them now with @dterrahe big work
For avoiding a combobox for golden section, it was planned, but I've finally preferred to not include that in my PR to simplify things a bit.

I'll have a look, but this will certainly have to wait for the end of the summer holidays ;) 
if someone want to do the work earlier, no problem :)

**Comment by AlicVB** [comment]
so PR #9864 implement the golden guides separation as suggested here.

For the shortcuts, @dterrahe can you have a look ? (and I promise to study your proposal to learn how how to deal with shortcuts now ;) thanks !

**Comment by dterrahe** [comment]
I'm currently working on shortcuts directly for an item in a combobox. This only works for a constant list of items (needs to be known at startup) so not sure if it will be usable here, but will have a look.

**Comment by johnny-bit** [comment]
Would ability to add guides via lua be a problem for guides shortcuts?

**Comment by dterrahe** [comment]
I'm not going to try to add _shortcuts_ for lua guides, but as long as they are added to the _end_ of the list, it shouldn't cause _additional_ complications. I.e. only the built-in guides would have direct shortcuts.

**Comment by elstoc** [comment]
Personally I'm just looking for something that will cycle through the available values in the list rather than a direct shortcut for each option, i.e. to match the dynamic combobox shortcut that's available in v3.6.

**Comment by dterrahe** [comment]
Of course, that will definitely work.
