### ISSUE TITLE
FR: Display Auto Focus point from EXIF

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#9473]
**Is your feature request related to a problem? Please describe.**

*Problem*
My original camera software shows the position of the AF point when editing and on the thumbnails (obviously, this is optional).
I find this extremely useful when culling. I can very quickly determine that a photo is not worth looking at because the AF point was wrong.    
The alternative is to open the photo and zoom in to see if it was in focus at the crucial point. 

I appreciate the Shift-Crtl-F function but it is not the same.

This AF point is mainly very useful on action shots with multiple AF points.  I can them immediately see that (1) the camera did not focus outside the subject (the background) and (2) if the camera focussed on the face, the body or the rear leg.
It would not be helpful when using focus-and-recompose.

**Describe the solution you'd like**
I would very much like an option which would display a green rectangle on which AF point was used when the photo was shot.
I know many cameras (Canon, Nikon Olympus) include this information in their Exif data. 
On my Olympus it looks like it indicates the relative coordinates of two corners of this rectangle.  Example: It reads "203/640" which I think means "When you divide the horizontal into 640 parts, the AF box was at number 203 out of 640". 

This function could be implemented on a per-brand basis to see if it makes people happy. 

**Alternatives**
I do use CTRL-SHIFT-F which is brilliant, but different.
It is post-picture analysis, not the actual information from the camera.  It also shows different results at different zoomlevels.
The two functions would complement each other.

**Comment by aurelienpierre** [comment]
Since there is no uniform way of declaring active collimators in EXIF among manufacturers, this is likely to never be implemented. Notice we already haze focus peaking and focus detection, so it's probably unnecessary as well.

**Comment by rekcodocker** [comment]
Update: Digikam has it. In their latest release 1.7.4, they can show and use the autofocus-point from the Exif data, supporting cameras from Canon, Nikon, Sony and Panasonic, and they are looking to expand.
They use it for their automatic picture quality analysis.  
So it's in open source, for some 40+ cameras over 5 different brands.
