### ISSUE TITLE
I can't Import any new collection on Win10

### ISSUE THREAD

**Issue by jmviade** [darktable-org/darktable#9475]
Hi, friends, 

Congratulations for this new step for this great plataforme of photo edition.

**Describe the bug/issue**
I've tried to install the last version 3.6.0.1 of Darktable and the main issue is that I CAN'T ADD any new collection. I can work with the existing collections but it's impossible to add a new one.

I follow the normal steps: select a folder, select some files, press the button, etc.  and then, it seems that Darktable is working (it even appears a messages saying that the process has finished correctly) but the new Collection never arrives and Darktable doesn't create any new .xmp files.

I've tried this process several times with two different installations: 
   * a FRESH installation of 3.6.0.1 with a new database and 
   * an UPDATE installation from 3.4.1 with the existing database

In both cases Darktable failed and it's impossible to add a new collection from my hard disk to the Darktable database.

**Platform**
Windows 10, 64-bits

I worked with darktable the 3.4.1
I've been trying to uptate to the new 3.6.0.1
I've been trying to install a fresh 3.6.0.1

Sincererly, 

Joan Miquel Viadé

**Comment by wpferguson** [comment]
When you tried to import did you use _add to library_ or _copy & import_?

Did the path to the files, or any of the filenames have any special characters (characters with accents, umlauts, etc.)?

**Comment by mmhh76** [comment]
Darktable 3.6 for Windows doesn't like special character in file path. It can be something like á, å, ä, or ë or whatever. But it does work in Linux. 3.4 didn't had this issue on Windows.

**Comment by wpferguson** [comment]
I can recreate this.  I created a directory with an umlaut in the name and 3 images.  The directory showed up fine in the import dialog.  Imported using add to library.  Got a response of 3 images imported.  No images showed up in lighttable.  Opened the database with sqlite3 and the film_roll was there, but the image table was empty.  I'm going to check 3.4.1.1, since that is reported to work.  If so, I'll bisect.

**Comment by wpferguson** [comment]
No XMP files were created either

**Comment by mmhh76** [comment]
What is the file path exactly for the directory umlaut you just created? Darktable 3.6 for Windows doesn't like special character in a name. I am not a Darktable developer so I don't know why.

But I can tell you I have the same issue in Windows. To me personally it's not a big issue because I prefer Linux and it works there.

**Comment by wpferguson** [comment]
I understand what the issue is, I'm trying to find the code commit that caused the problem.  I'm just logging my steps to help whoever works on it.

**Comment by mmhh76** [comment]
Oh I see :). I hope you find the code.

**Comment by wpferguson** [comment]
Bisect is 22026cf6b7cf7352fde973c1a47b7225afbf5c81

It's the dt_util_test_image() function

@jenshannoschwalm can you take a look?  TIA

**Comment by mmhh76** [comment]
@wpferguson I see now that you are not the one who started this thread. So embarassing 🥴. So sorry about that.

**Comment by wpferguson** [comment]
Not a problem :)

**Comment by wpferguson** [comment]
@jenshannoschwalm I added a couple of print statements and got the following from dt_util_test_image_file()

```
checking C:\Users\bill\Pictures\üîdir\_7D_4098.jpg
return value was -1
checking C:\Users\bill\Pictures\üîdir\_7D_4098.tif
return value was -1
checking C:\Users\bill\Pictures\üîdir\_7D_4261.jpg
return value was -1

```
3.4.1.1 will import the files without a problem.

**Comment by jenshannoschwalm** [comment]
got the issue and will take care of it. Unfortunately i can't test on windows myself ... maybe we need some utf8 conversion.

**Comment by jmviade** [comment]
**When you tried to import did you use add to library or copy & import?**
I tried both "Import" and "Copy & Import"

**Special Characters in the path?**
No, there aren't special characters in the path
The base directory naming pattern is $(PICTURES_FOLDER)/Darktable
and ${PICTURES_FOLDER} is just D:/Imatges/

**Continuing with the comment of** @wpferguson 
Effectively, the database doesn't add the individual images, but when you work with external .xmp support files, the images don't appear, neither.

**Comment by johnny-bit** [comment]
@jenshannoschwalm - The path to file is (or should be) normalized with `dt_util_normalize_path` (which should be used wherever we're dealing with paths that MIGHT be non-ascii). I see that it's called in one place dealing with import but not in other place dealing with detecting duplicates...

the `-1` output as received by @wpferguson looks weird, but then the return of `dt_util_test_image_file` is or should be boolean...

**Comment by bengtfalke** [comment]
There is something odd with the copy & Import function. I am on win10 with dt 3.6. No unusual characters in the file path.
When I copy & Import all looks fine at first and I can work with the photos. When I restart dt the import is not present in dt but the files are in the right place so I can just add to library again. Next time I start dt I get the message about updated sidecar files found. I do update the database from the selected sidecar files and all looks ok.

**Comment by johnny-bit** [comment]
@bengtfalke - if the path doesn't contain non-ascii characters then the isue you describe is different one than this one and if you haven't seen similar issue to yours mentioned you're free to create new issue :)

**Comment by jenshannoschwalm** [comment]
Was lost a bit in a free error while importing so i couldn't get into this so far. Will likely find time tomorrow if none of you fixes it until then :-)

@wpferguson the -1 results are interesting :-)

**Comment by wpferguson** [comment]
I'll try and look at this later today.  I think I'll go back prior to the commit that broke, and see how and why that worked, then see what changed and how it broke.

**Comment by wpferguson** [comment]
> the -1 output as received by @wpferguson looks weird, but then the return of dt_util_test_image_file is or should be boolean...

That was the output from _stati64().

I just tested the old code (3.4.1.1) with the same _stati64() function and it can find files just fine even when they are not on the C: drive.  So whatever is being passed in makes _stati64() unhappy.  Tracing further back....

**Comment by wpferguson** [comment]
Ok, I'm stumped....

In 3.4.1.1 this works...  (specifically the _stati64() test)

```
off_t dt_util_get_file_size(const char *filename)
{
#ifdef _WIN32
  struct _stati64 st;
  if(_stati64(filename, &st) == 0) return st.st_size;
#else
  struct stat st;
  if(stat(filename, &st) == 0) return st.st_size;
#endif

  return -1;
}

```

In 3.6 this doesn't...

```
gboolean dt_util_test_image_file(const char *filename)
{
  if(g_access(filename, R_OK)) return FALSE;
#ifdef _WIN32
  struct _stati64 stats;
  if(_stati64(filename, &stats)) return FALSE;
#else
  struct stat stats;
  if(stat(filename, &stats)) return FALSE;
#endif

  const gboolean regular = (S_ISREG(stats.st_mode)) != 0;
  const gboolean size_ok = stats.st_size > 0;
  return regular && size_ok;
}

```

It fails on the _stati64() call with ENOENT.  Both calls are receiving a valid utf8 pathname from dt_util_normalize_path().

Both (3.4 and 3.6) calls come from _image_import_internal() in src/common/image.c with almost the same path

**Comment by esq4** [comment]
This problem also exists in Win7. But I was unable to solve it with this patch. Maybe because Win7 uses ANSI code pages, not UTF8?

**Comment by wpferguson** [comment]
I wrote the patch and tested it in win 7.

**Comment by wpferguson** [comment]
@esq4 can you give me a specific example, so I can test?  Thanks

**Comment by esq4** [comment]
@wpferguson sorry but I missed a few commits. After update, your patch started work.
