### ISSUE TITLE
darktable.exe caused an Access Violation at location 00007FF85FEC0929 in module libgtk-3-0.dll Reading from location FFFFFFFFFFFFFFFF.

### ISSUE THREAD

**Issue by jazzfanster** [darktable-org/darktable#9477]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'Quick Access Panel'
2. Click on 'any module. then click on another module in same panel'
error immediately appears

this is darktable 3.6.0 reporting an exception:

-------------------

Error occurred on Friday, July 9, 2021 at 10:03:03.

darktable.exe caused an Access Violation at location 00007FF8366B0929 in module libgtk-3-0.dll Reading from location FFFFFFFFFFFFFFFF.

AddrPC           Params
00007FF8366B0929 00000018B99FEBF0 00007FF86111EF61 0000018E3D7A06C0  libgtk-3-0.dll!gtk_viewport_get_view_window
00007FF8366B63F2 0000000000000000 0000000000000001 0000018E00000001  libgtk-3-0.dll!gtk_widget_has_focus
00007FF8611070E3 0000018E3D7A0648 0000018E3D7A0640 0000000000000000  libgobject-2.0-0.dll!g_closure_invoke
00007FF86111EE9B 0000018E60044DD0 00007FF86110B202 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FF86111EFE8 0000000000000030 0000018E3B870D50 0000018E3BA60000  libgobject-2.0-0.dll!g_signal_emit
00007FF8366B7929 0000000000000020 0000000000000008 0000018E00000002  libgtk-3-0.dll!gtk_widget_grab_focus
00007FF836447354 0000000000000020 00007FF800000000 0000018E3D0811E0  libgtk-3-0.dll!gtk_builder_get_application
00007FF8611070E3 0000018E3D083090 0000018E3D0F49E0 0000000000000651  libgobject-2.0-0.dll!g_closure_invoke
00007FF86111EE9B 0000018E603A64F0 0000018E5CAF0F40 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FF86111EFE8 0000018E3B870000 00007FF800000003 00000018B99FF0C8  libgobject-2.0-0.dll!g_signal_emit
00007FF8365164AF 0000018E43865A70 0000000000000149 0000000000000000  libgtk-3-0.dll!gtk_gesture_long_press_new
00007FF8611099DA 0000000000000008 00007FF8BAD007B0 0000000000000000  libgobject-2.0-0.dll!g_cclosure_marshal_VOID__BOXEDv
00007FF8611070E3 0000018E3D8247B0 00007FF8BAD007B0 00000018B99FF3A0  libgobject-2.0-0.dll!g_closure_invoke
00007FF86111EE9B 0000018E603A64F0 402E000000000011 000000CE00000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FF86111EFE8 0000018E3D822B90 0000018E00000008 0000000000000001  libgobject-2.0-0.dll!g_signal_emit
00007FF83651302D 0000000000000001 0000000000000000 0000018E603A64F0  libgtk-3-0.dll!gtk_glade_catalog_init
00007FF836514547 0000000000000002 0000018E60044CE0 0000018E603A64F0  libgtk-3-0.dll!gtk_gesture_handles_sequence
00007FF8365177B4 0000018E00000000 00007FF86110B993 00000018B99FF6C8  libgtk-3-0.dll!gtk_gesture_rotate_get_angle_delta
00007FF8364DC61D 4036000000000000 00007FF857F2F44C 4031000000000001  libgtk-3-0.dll!gtk_event_controller_handle_event
00007FF8366B1B0C 0000000000000000 00007FF861126936 0000000000000000  libgtk-3-0.dll!gtk_requisition_free
00007FF836402DC1 00000000000000DB 00007FF836512D2D 0000018E3D7A06C0  libgtk-3-0.dll!0x7ff800002dc1
00007FF8611070E3 0000018E3D7A06C0 00007FF85AB088D0 0000018E3D11F140  libgobject-2.0-0.dll!g_closure_invoke
00007FF86111E42B 0000018E60044DD0 0000000000000000 0000018E00000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FF86111EFE8 0000018E60044DD0 00007FF861126936 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
00007FF8366B3425 0000018E00000000 00007FF8366DBC7A 0000018E5C968F20  libgtk-3-0.dll!gtk_requisition_copy
00007FF8365612DF FFFFFFFF00000000 00007FF8B938E703 00007FF8B938EB96  libgtk-3-0.dll!gtk_lock_button_set_permission
00007FF836563308 0000000000000000 00007FF857F56680 0000000000000000  libgtk-3-0.dll!gtk_main_do_event
00007FF857F1F56A 00000018B99FFA30 0000018E3D80D170 00007FF8B938E040  libgdk-3-0.dll!gdk_event_free
00007FF857F566BF 0000018E3D0F49E0 00007FF85AB1B62D 0000000000000000  libgdk-3-0.dll!gdk_win32_drag_context_get_type
00007FF85AB188F4 0000000000000002 0000018E43952740 0000018E43952740  libglib-2.0-0.dll!g_clear_list
00007FF85AB1BA46 0000000000000001 0000018E3D0BFA70 0000018E3D0E5520  libglib-2.0-0.dll!g_main_context_check
00007FF85AB1BF6C 0000000000000000 0000000000000000 00007FF836FB70C0  libglib-2.0-0.dll!g_main_loop_run
00007FF8365621ED 0000000000000000 00007FF710C826E0 0000018E3D0E55B0  libgtk-3-0.dll!gtk_main
00007FF836D5B27C 00007FF800000001 0000018E3D0BFA70 00007FF800000001  libdarktable.dll!dt_gui_gtk_run
00007FF710C82A6C 00007FF710C81660 0000000000000010 0000000000000000  darktable.exe!0x7ff700002a6c
00007FF710C815B5 000000000000005A 0000000000000000 00007FF710C87090  darktable.exe!0x7ff7000015b5
00007FF710C813D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff7000013d4
00007FF710C81506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff700001506
00007FF8BA477034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FF8BAD02651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.6.0.0
ntdll.dll   	10.0.19041.1081
aswhook.dll 	21.5.6354.0
KERNEL32.DLL	10.0.19041.1023
KERNELBASE.dll	10.0.19041.1081
msvcrt.dll  	7.0.19041.546
libglib-2.0-0.dll	2.68.3.0
ADVAPI32.dll	10.0.19041.1052
sechost.dll 	10.0.19041.906
RPCRT4.dll  	10.0.19041.1081
libintl-8.dll	0.19.8.0
ole32.dll   	10.0.19041.746
ucrtbase.dll	10.0.19041.789
combase.dll 	10.0.19041.1081
GDI32.dll   	10.0.19041.746
win32u.dll  	10.0.19041.1081
gdi32full.dll	10.0.19041.928
msvcp_win.dll	10.0.19041.789
USER32.dll  	10.0.19041.906
SHELL32.dll 	10.0.19041.1023
WS2_32.dll  	10.0.19041.546
libdarktable.dll
libiconv-2.dll	1.16.0.0
PSAPI.DLL   	10.0.19041.546
libwinpthread-1.dll	1.0.0.0
libpcre-1.dll
libcairo-2.dll
exchndl.dll 	0.9.2.0
libgdk-3-0.dll	3.24.29.0
libgdk_pixbuf-2.0-0.dll	2.42.4.0
IMM32.dll   	10.0.19041.546
libgio-2.0-0.dll	2.68.3.0
SHLWAPI.dll 	10.0.19041.1023
SETUPAPI.dll	10.0.19041.844
libgobject-2.0-0.dll	2.68.3.0
libgtk-3-0.dll	3.24.29.0
libharfbuzz-0.dll
libpango-1.0-0.dll	1.48.5.0
libpangocairo-1.0-0.dll	1.48.5.0
comdlg32.dll	10.0.19041.906
zlib1.dll
shcore.dll  	10.0.19041.1023
libgcc_s_seh-1.dll
libgomp-1.dll
cfgmgr32.dll	10.0.19041.546
libstdc++-6.dll
libcurl-4.dll
bcrypt.dll  	10.0.19041.1023
CRYPT32.dll 	10.0.19041.844
WLDAP32.dll 	10.0.19041.546
libgmodule-2.0-0.dll	2.68.3.0
libgphoto2-6.dll
libexiv2.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libicuin68.dll
libIlmImf-2_5.dll
libjpeg-8.dll
liblcms2-2.dll
libopenjp2-7.dll
libpng16-16.dll
libpugixml.dll	1.11.0.0
libjson-glib-1.0-0.dll
libsecret-1-0.dll
librsvg-2-2.dll
libavif.dll
libicuuc68.dll
libtiff-5.dll
libsqlite3-0.dll
libxml2-2.dll
MSIMG32.dll 	10.0.19041.546
libfreetype-6.dll	2.10.4.0
libfontconfig-1.dll
libpixman-1-0.dll
VERSION.dll 	10.0.19041.546
mgwhelp.dll 	0.9.2.0
dwmapi.dll  	10.0.19041.746
gdiplus.dll 	10.0.19041.1081
IPHLPAPI.DLL	10.0.19041.546
DNSAPI.dll  	10.0.19041.1023
libffi-7.dll
USP10.dll   	10.0.19041.546
libfribidi-0.dll
libthai-0.dll
libgraphite2.dll
COMCTL32.dll	6.10.19041.1083
libpangowin32-1.0-0.dll	1.48.5.0
libpangoft2-1.0-0.dll	1.48.5.0
WINSPOOL.DRV	10.0.19041.1023
libatk-1.0-0.dll	2.36.0.0
libcairo-gobject-2.dll
libepoxy-0.dll
WINMM.dll   	10.0.19041.546
libbrotlidec.dll
libidn2-0.dll
libcrypto-1_1-x64.dll	1.1.1.11
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libzstd.dll
libssl-1_1-x64.dll	1.1.1.11
libsoup-2.4-1.dll
libexif-12.dll
libltdl-7.dll
libsystre-0.dll
libexpat-1.dll
libbz2-1.dll
libHalf-2_5.dll
libIex-2_5.dll
libImath-2_5.dll
libIlmThread-2_5.dll
libgcrypt-20.dll	1.9.2.0
libdav1d.dll	5.1.0.0
USERENV.dll 	10.0.19041.572
libaom.dll
libdeflate.dll
rav1e.dll
libjbig-0.dll
libicudt68.dll
liblzma-5.dll	5.2.5.0
libwebp-7.dll
dbghelp.dll 	10.0.19041.867
libdatrie-1.dll
libunistring-2.dll	0.9.10.0
libbrotlicommon.dll
libtre-5.dll
libgpg-error-0.dll	1.42.0.0
CRYPTBASE.DLL	10.0.19041.546
dbgcore.DLL 	10.0.19041.789
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.1052
bcryptPrimitives.dll	10.0.19041.1023
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.1081
Wldp.dll    	10.0.19041.662
kernel.appcore.dll	10.0.19041.546
uxtheme.dll 	10.0.19041.1081
OLEAUT32.dll	10.0.19041.985
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.1023
profapi.dll 	10.0.19041.844
mswsock.dll 	10.0.19041.546
DEVOBJ.dll  	10.0.19041.546
WINTRUST.dll	10.0.19041.1052
MSASN1.dll  	10.0.19041.546
msctf.dll   	10.0.19041.1081
OpenCL.dll  	2.2.8.0
AppXDeploymentClient.dll	10.0.19041.1081
dxgi.dll    	10.0.19041.964
igdrcl64.dll	23.20.100.9466
igdgmm64.dll	27.20.100.9466
dxcore.dll  	10.0.19041.546
igdfcl64.dll	27.20.100.9466
igc64.dll   	27.20.100.9466
winhttp.dll 	10.0.19041.1081
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.1023
libpixbufloader-png.dll
mscms.dll   	10.0.19041.746
ColorAdapterClient.dll	10.0.19041.546
icm32.dll   	10.0.19041.546
textinputframework.dll	10.0.19041.1081
CoreMessaging.dll	10.0.19041.746
CoreUIComponents.dll	10.0.19041.546
wintypes.dll	10.0.19041.1081
ntmarta.dll 	10.0.19041.546
Oleacc.dll  	7.2.19041.746
libdarkroom.dll
libknight.dll
liblighttable.dll
libmap.dll
libosmgpsmap-1.0-1.dll
libslideshow.dll
libtethering.dll
libavif.dll
libcopy.dll
libexr.dll
libj2k.dll
libjpeg.dll
libpdf.dll
libpfm.dll
libpng.dll
libppm.dll
libtiff.dll
libwebp.dll
libxcf.dll
libdisk.dll
libemail.dll
libgallery.dll
liblatex.dll
libpiwigo.dll
libashift.dll
libatrous.dll
libbasecurve.dll
libbasicadj.dll
libbilat.dll
libbilateral.dll
libbloom.dll
libborders.dll
Windows.ApplicationModel.dll	10.0.19041.746
twinapi.appcore.dll	10.0.19041.964
libcacorrect.dll
libcacorrectrgb.dll
mssprxy.dll 	7.0.19041.1023
libcensorize.dll
libchannelmixer.dll
libchannelmixerrgb.dll
libclahe.dll
libclipping.dll
libcolisa.dll
libcolorbalance.dll
libcolorbalancergb.dll
libcolorchecker.dll
libcolorcontrast.dll
libcolorcorrection.dll
libcolorin.dll
libcolorize.dll
libcolormapping.dll
libcolorout.dll
libcolorreconstruct.dll
libcolortransfer.dll
libcolorzones.dll
libcrop.dll
libdefringe.dll
libdemosaic.dll
libdenoiseprofile.dll
libdither.dll
libequalizer.dll
libexposure.dll
libfilmic.dll
libfilmicrgb.dll
libfinalscale.dll
libflip.dll
libgamma.dll
libglobaltonemap.dll
libgraduatednd.dll
libgrain.dll
libhazeremoval.dll
libhighlights.dll
libhighpass.dll
libhotpixels.dll
libinvert.dll
liblens.dll
liblensfun.dll
liblevels.dll
libliquify.dll
liblowlight.dll
liblowpass.dll
liblut3d.dll
libgmic.dll
libGraphicsMagick++-12.dll
libfftw3-3.dll
libopencv_videoio452.dll	4.5.2.0
libopencv_core452.dll	4.5.2.0
tbb.dll
libopencv_imgcodecs452.dll	4.5.2.0
libopencv_imgproc452.dll	4.5.2.0
OPENGL32.dll	10.0.19041.1081
libopenblas.dll
GLU32.dll   	10.0.19041.1081
libgfortran-5.dll
libquadmath-0.dll
libmask_manager.dll
libmonochrome.dll
libnegadoctor.dll
libnlmeans.dll
liboverexposed.dll
libprofile_gamma.dll
librawdenoise.dll
librawoverexposed.dll
librawprepare.dll
librelight.dll
libretouch.dll
librgbcurve.dll
librgblevels.dll
librotatepixels.dll
libscalepixels.dll
libshadhi.dll
libsharpen.dll
libsoften.dll
libsplittoning.dll
libspots.dll
libtemperature.dll
libtonecurve.dll
libtoneequal.dll
libtonemap.dll
libvelvia.dll
libvibrance.dll
libvignette.dll
libwatermark.dll
libzonesystem.dll
libbackgroundjobs.dll
libcamera.dll
libcollect.dll
libcolorlabels.dll
libcolorpicker.dll
libcopy_history.dll
libdarktable_label.dll
libduplicate.dll
libexport.dll
libfilmstrip.dll
libfilter.dll
libgeotagging.dll
libglobal_toolbox.dll
libhinter.dll
libhistogram.dll
libhistory.dll
libimage.dll
libimage_infos.dll
libimport.dll
libioporder.dll
liblighttable_mode.dll
liblive_view.dll
liblocation.dll
libmap_locations.dll
libmap_settings.dll
libmasks.dll
libmetadata.dll
libmetadata_view.dll
libmodulegroups.dll
libmodule_toolbox.dll
libnavigation.dll
libratings.dll
librecentcollect.dll
libselect.dll
libsession.dll
libsnapshots.dll
libstyles.dll
libtagging.dll
libtimeline.dll
libviewswitcher.dll
libview_toolbox.dll
libpixbufloader-svg.dll
TextShaping.dll

Windows 10.0.19042
DrMingw 0.9.2

**Expected behavior**

should not error out

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

Newly installed DT 3.6.0 

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0
* OS                : Win10 v20H2 Build 19042.1083
* Processor - Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.71 GHz
* Memory            : 8GB 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : HP 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no** No
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both** JPEG
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no** YES
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts? They are installed. Haven't used them.
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by TurboGit** [comment]
Already reported and known problem.

**Comment by Nilvus** [comment]
And fixed (should be for a probabe 3.6.1)
