### ISSUE TITLE
Deletion of raw file and folder containing it.

### ISSUE THREAD

**Issue by maesejofial** [darktable-org/darktable#9478]
Hello friends,

I didn't realise until now, that if I deleted a raw photo, the folder that contained it was deleted.

**Bug description (I think)**

1. Downloads folder: empty
2. I download a raw file to the downloads folder
3. I open the raw file directly with Darktable (right click->open with Darktable)
4. As I don't want to save the file, but use the .xmp from the **Lighttable**, I delete the file with _Delete (trash)_. When I go to the folder that contained the raw, raw and folder are deleted.
5. This happens if there is no other sub-folder within Downloads. It only happens if there are only the raw and .xmp files, then it deletes the files and the folder

**Platform:**
Distribution: Linux Ubuntu 20.04.2
Desktop: Gnome 3.36
Kernel: 5.10.0
Memory: 16GB
CPU:AMD Ryzen 9 5900HX with Radeon Graphics
Graphics: Device-1: NVIDIA driver: nvidia v: 460.80 
OpenGL: renderer: GeForce RTX 3070 Laptop GPU/PCIe/SSE2 v: 4.6.0 NVIDIA 460.80/activated

**Additional context**
Tested on Debian Testing with KDE

Cheers

Jose Figueres

**Comment by parafin** [comment]
Execute `touch ~/Downloads/.keep` as a workaround.

**Comment by maesejofial** [comment]
Thank you very much, this works for me.

But, this way of dealing with folders by darktable is a bit irregular. I think ;-)

**Comment by elstoc** [comment]
There's an option that should stop that happening - try checking `preferences > security > ask before removing empty folders`.

**Comment by maesejofial** [comment]
This is the elegant solution.
Thank you

**Comment by elstoc** [comment]
Ok I'll assume that's problem solved and we can close this then.
