### ISSUE TITLE
Seg Fault with Filmic

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#9480]
**Describe the bug/issue**
Any attempt to use the 'auto-tune' button on filmic causes dt to freeze and then close.

**To Reproduce**
1. Open any image
2. Click on 'Filmic'
3. Check that sliders are working correctly ... OK
4. Click on 'auto-tune' button
5. darktable freezes and then closes.

[darktable_bt_CZS250.txt](https://github.com/darktable-org/darktable/files/6793367/darktable_bt_CZS250.txt)
[Terminal-bt.txt](https://github.com/darktable-org/darktable/files/6793371/Terminal-bt.txt)

2 log files attached

Which commit introduced the error** Git version:3.7.0+277~g0f575bc2bd 
I have tried a later version and the problem remains

**Platform** Linux

* darktable version : version:3.7.0+277~g0f575bc2bd 
* OS                : Linux - kernel 5.12.9-1
* Linux - Distro    :Manjaro/Arch
* Memory        16Gb.    : 
* Graphics card     Nvidia 
* Graphics driver   :Quadro K1000M 
* OpenCL installed  no
* OpenCL activated  no
* Xorg              : 
* Desktop           XFCE: 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? Version from prior day did NOT behave in this manner.
 - Can you reproduce with a RAW or Jpeg or both? RAW and DNG ... I do not have JPG for processing
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)?Yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes
   - What lua scripts start automatically? None
   - What lua scripts were running when the bug occurred? None

**Comment by elstoc** [comment]
Could be linked to #9468 and #9470.

**Comment by wpferguson** [comment]
I can reproduce.  

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f13ff7f2492 in __GI___waitpid (pid=pid@entry=863, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
warning: Currently logging to /tmp/darktable_bt_8YCF60.txt.  Turn the logging off and on to make the new setting effective.
#0  0x00007f13ff7f2492 in __GI___waitpid (pid=pid@entry=863, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007f13ffc2c3b8 in _dt_sigsegv_handler (param=11) at /home/bill/src/darktable/darktable/src/common/system_signal_handling.c:114
#2  0x00007f13ff74d040 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f13ffdbf774 in _iop_color_picker_callback_button_press (button=<optimized out>, e=0x0, self=0x55fc59a63470) at /home/bill/src/darktable/darktable/src/gui/color_picker_proxy.c:160
#4  0x00007f13fd08f0bd in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007f13fd0a200e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f13fd0aa6f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f13fd0ab5e8 in g_signal_emit_by_name () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f13ffb7e409 in dt_bauhaus_widget_press_quad (widget=<optimized out>) at /home/bill/src/darktable/darktable/src/bauhaus/bauhaus.c:957
#9  0x00007f13ffb80468 in dt_bauhaus_combobox_button_press (widget=0x55fc59a62e60, event=0x55fc58d6da90, user_data=<optimized out>) at /home/bill/src/darktable/darktable/src/bauhaus/bauhaus.c:2322

```

That line changed in commit c8eadc479f2ee23258986ee90056f9d55dcc1d45

@dterrahe can you look at this?
