### ISSUE TITLE
NG Input: Allow long-press actions to be disabled

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9481]
I find it easy to long press a key when I mean to short press, and I doubt I am ever going to create any long-click/press actions. When I do accidentally long-press I get a message saying no action is defined and I then have to try again.

I would prefer to be able to remove the distinction between these events (i.e. to have long-press treated the same as short-press). Similarly with long-click. This could be done via a preference option.

Perhaps a suitable alternative would be to have a fallback that treats a long-click/press the same as a short-click/press where there is no long-click/press action defined.

**Comment by dterrahe** [comment]
Fallbacks would have to be defined for each type of widget of the "main" shortcut. I could add those fallbacks by default for each of them, yes. Or make them do something "useful" (toggle buttons already treat long press as right-click, to mimic a long click on any of the overexpose etc buttons which will call up the popover). But I guess you wouldn't want them to do anything different by default?

This would take away discoverability; new users might never be aware they could do something with long-press if they wanted... (just saying. Devil's advocate and all that).

There's a few bugs in setting up _new) fallbacks yet. You should be able to double click on the slider fallback action in the bottom of the dialog and then, say, press just the modifiers ctrl+shift+alt and now have a new fallback for those all held together. Doesn't work yet, but I intend to fix when I also implement modifier key emulation by devices (midi etc).

In general, I've kept Input NG as configuration free as possible until people started testing. Easier to add configs when we find they are needed (maybe this is such a case, I thought maybe double/triple needed to be disableable too, but seems that testing if there aren't any and then not delay waiting for them dealt with that sufficiently) than later taking them away. But if we introduce configs, and if there is a sufficient number of them, we need to consider where to put those. Might need a separate tab, especially when we add configuring midi and other devices (#9445)

**Comment by elstoc** [comment]
I would want to be able to explicitly assign short-click to something and have that action work on both short and long click. If there are long-click fallbacks I would like to be able to disable them. For your point about discoverability, a config option might be the way to go (though honestly if people won't read the manual they should expect to miss features).

I'm generally unsure about default fallbacks that use long-click and long-press actions due to the ease of activating them by accident, and I wonder whether we shouldn't reduce the number of default fallbacks available (some of them are quite obscure) just to reduce the initial complexity.

I think additional configs (to disable some of the complexity or remove certain types of shortcut/fallback in bulk) will prove necessary and probably provide a good excuse for a setup window that's entirely independent of preferences, perhaps with 2 tabs (one for shortcuts and one for preferences and bulk actions).

I've been playing with this on and off for a while now and I still find it very confusing, though certainly very useful and powerful. I worry what the "free version of Lightroom" crowd will make of it.

**Comment by dterrahe** [comment]
> though honestly if people won't read the manual they should expect to miss features

You are being funny, right? ;-)

More seriously, a "what's changed" popup on first launch may be needed, alongside a longer blurb-with-pointers in the release announcement.

> 2 tabs one for shortcuts and one for preferences and bulk actions

I've been thinking along those lines, but rather than an excuse I've been looking for a justification. I don't want to end up with just one or two options there, or with a load of options that cause everybody to have different behavior making debugging or support a nightmare. If needed, yes. But if we can make everyone transition without too much pain and without having them switch off features completely, they could benefit more in the long term. Being confused a few times before getting used to something is worth the investment; this is dt, not Word. But being annoyed all the time and it never going away, that's definitely _not_ what I'm aiming for!

> I worry what the "free version of Lightroom" crowd will make of it.

We know what they will and I'm not going to worry about _them_ too much. I seriously don't believe they are a threat to dt; their complaining about complexity would often be an endorsement for those who are looking for the power we are aiming for. Dumbing down to them might just leave us with no audience at all.

**Comment by dterrahe** [comment]
Also, remember that shortcuts are not the first feature one _needs_ when getting up to speed with dt. Only when you reach that point where your workflow could benefit from a boost does it pay to customise your setup. And only then do you know _how_ to set it up to your liking anyway.

So for newbies, the only criterium is to avoid shortcuts getting in the way unexpectedly. I'm not worried if the first look at the configuration dialog scares them away and they only come back months later (after reading the manual); that's probably better!

**Comment by elstoc** [comment]
>  don't want to end up with just one or two options there

There are already options for multi-instance shortcut handling that could be moved.

> We know what they will and I'm not going to worry about them too much

Don't worry we'll just allocate all the issues to you and tag you in all the pixls posts ;-P

**Comment by dterrahe** [comment]
> Don't worry we'll just allocate all the issues to you

The ones that can be closed as invalid in a second? I can handle those. Might occasionally paste a link to the manual if I'm bored. Or to the adobe sales page.
