### ISSUE TITLE
NG Input: clicking on module header opens "processing modules"

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9482]
Enter the visual shortcut mapping mode and single-click on a module header (for example, exposure). The shortcut mapping window opens with the "processing modules" section expanded instead of the "exposure" section.

Is this correct?

3.7.0+277~g0f575bc2b

**Comment by dterrahe** [comment]
Nope, you are right; needs to be fixed. That header is fiddly because a label needs an event box wrapping blah blah. Thanks for putting a reminder here.
