### ISSUE TITLE
NG Input: Consider using dt_toast_log

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9484]
When pressing a key that is not mapped, a message appears on the screen stating that it doesn't do anything. While this is better than the previous solution (which didn't show any indication on screen), the message stays in place for a while and sits on top of the image while in the darkroom.

Given that this is just an informational message and not strictly an error, it might be better to use `dt_toast_log` rather than `dt_control_log` for the message.

**Comment by dterrahe** [comment]
Fair enough. I thought it might be helpful for newcomers but can see that it gets annoying quite quickly. I briefly thought about forcing the toast to disappear as soon as a valid shortcut is used, but that could hide valid other error messages as well...

There are also a fair number of new shortcuts that don't show toasts yet and therefore don't provide any visual feedback if the panels are hidden. For example changing notebook tabs. Or button presses.

This is one of the todo's to pollish Input NG. If you think this might be too spammy or have other suggestions, please let me know!

**Comment by elstoc** [comment]
I think the general principle should be that if the shortcut has clear UI impact then don't show a toast.

**Comment by dterrahe** [comment]
> I think the general principle should be that if the shortcut has clear UI impact then don't show a toast.

Though we are not doing that for sliders/combos now; the toast is always shown, whether the widget is visible or not...

**Comment by elstoc** [comment]
The affect of those is not always obvious, so I was mainly referring to the bigger things like showing/hiding panels
