### ISSUE TITLE
[FR] Bring back guide ratio selection in cropping module

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#9486]
**Is your feature request related to a problem? Please describe.**
I am quite used to cropping portraits with golden ration guides. It seems latest git doesn't have a selector anymore to select different guide ratios. For me this is quite a step back in functionality.

**Describe the solution you'd like**
I liked the way it worked up to 3.6. I understand that so many types of guides could be overwhelming but other modules have even more options so I don't quite understand why it was removed.

**Alternatives**
As there currently is no guide selector there are no alternatives I am afraid.

**Comment by ralfbrown** [comment]
In darkroom, right-click on the crossing-lines icon at the bottom right of your image so select which style of guide lines you want.

**Comment by piratenpanda** [comment]
Ah thanks for showing me this, have missed the toggle. Golden ratio, grid and other types don't show up though while others do. For many I only see the border of the crop highlighted. Does golden ratio work for you on latest git?

**Comment by ralfbrown** [comment]
All of them work for me in master as of five minutes ago.  Be sure that you haven't accidentally toggled the overlay off (left-click on the guides icon).

**Comment by piratenpanda** [comment]
I think the other options would not show up either when the toggle would be off. A clean build didn't change the behaviour here
![Bildschirmfoto von 2021-07-10 09-35-45](https://user-images.githubusercontent.com/920721/125155772-5a1fa500-e162-11eb-9ea9-1f69dd174e10.png)

**Comment by AlicVB** [comment]
I confirm that I can't reproduce :( but you are not alone here... seems that @TurboGit and @Nilvus have the same issue...
I'll need some help to find the problem...
1. do you have activated the "always show guides" option for the crop and rotate module ?
2. does it happens also if another module has the focus (try exposure for example) ?
3. does it happen if you remove your darktablerc file (backup first) ?
4. does it happen after a dt restart ? with a completely new image ?

Sorry to annoy you, but that's the only solution, as I'm doing some blind debugging here ;)
Thanks !

**Comment by AlicVB** [comment]
Oh wait, I think I got it : I reproduce the bug :)
That happen as soon as the language is not english... certainly some erroneous check with/without translation...
I'll have a look. Don't bother with all my previous question !

**Comment by piratenpanda** [comment]
@AlicVB maybe I'm missing something here but shouldn't the standard golden ratio be symmetric to the perpendicular bisectors and thus symmetry invariant? But when ticking any of the options the grid moves slightly.

**Comment by AlicVB** [comment]
What we see is certainly a rounding error...
I've not touched the drawing routines, so I think that was already the case before...

**Comment by piratenpanda** [comment]
Yeah I think so too. Was just noticing that, never touched the mirror switch before :)
