### ISSUE TITLE
Odd behviour with copy & import function

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#9491]
There is something odd with the copy & Import function. As I am new to dt I am not sure this is a bug but I think this behaviour looks like a bug to me. I am on win10 with dt 3.6. No unusual characters in the file path.
When I copy & Import all looks fine at first and I can work with the photos. When I restart dt the import is not present in dt but the files are in the right place so I can just add to library again. Next time I start dt I get the message about updated sidecar files found. I do update the database from the selected sidecar files and all looks ok. At random new updated sidecar files pops up when I restart dt.

Settings in the dialogue:
Base directory naming pattern: d:/foton/2021
sub directory naming pattern: $(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY)
keep original file name: yes

**Expected behavior**
Copy the files from the SD-card to the location selected and add them to the database.

**Platform**

* darktable version : 3.6 from release day
* OS                : Win10 home: 10.0.19042
* Memory            : 32 GB
* Graphics card     : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : 30.0.14.7111

* OpenCL installed  : OpenCL 3.0 - NVIDIA GeForce RTX 2070 SUPER - CUs:40@1815MHz
* OpenCL activated  : yes

**Comment by wpferguson** [comment]
I tried to reproduce while testing PR #9498 and couldn't, so maybe that PR will fix this.
