### ISSUE TITLE
Error when migrating library.db schema from version 32 to 34.

### ISSUE THREAD

**Issue by matthuska** [darktable-org/darktable#9492]
**Describe the bug/issue**
Start darktable (Ubuntu package version 3.6.0-1.1) from the command line. A popup appears, stating that the database schema needs to be updated. Click "upgrade database" and the schema update fails with the following message:

```
[init] can't drop table images_old
[init]   FOREIGN KEY constraint failed
[init] database `library.db' couldn't be upgraded from version 32 to 34. aborting
ERROR : cannot open database
```
**Expected behavior**
Schema is updated to the current version (34) and darktable starts.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0 (ubuntu package number is 3.6.0-1.1)
* OS                : Linux 5.4.0-77-generic
* Linux - Distro    : Ubuntu 20.04.2 LTS

**Comment by HansBull** [comment]
Please open a terminal in the folder where your database is located, i.e. `/home/myusername/.config/darktable/`

Make a copy of your current `library.db` to e.g. `library.db.test`

Install package `sqlite3`

In the terminal, open the copy with the command `sqlite3 library.db.test`

Issue, one after another, the following sql queries

ALTER TABLE 'images' RENAME TO 'images_old';

CREATE TABLE 'images' (id INTEGER PRIMARY KEY AUTOINCREMENT, group_id INTEGER, film_id INTEGER, width INTEGER, height INTEGER, filename VARCHAR, maker VARCHAR, model VARCHAR, lens VARCHAR, exposure REAL, aperture REAL, iso REAL, focal_length REAL, focus_distance REAL, datetime_taken CHAR(20), flags INTEGER, output_width INTEGER, output_height INTEGER, crop REAL, raw_parameters INTEGER, raw_denoise_threshold REAL, raw_auto_bright_threshold REAL, raw_black INTEGER, raw_maximum INTEGER, license VARCHAR, sha1sum CHAR(40), orientation INTEGER, histogram BLOB, lightmap BLOB, longitude REAL, latitude REAL, altitude REAL, color_matrix BLOB, colorspace INTEGER, version INTEGER, max_version INTEGER, write_timestamp INTEGER, history_end INTEGER, position INTEGER, aspect_ratio REAL, exposure_bias REAL, import_timestamp INTEGER DEFAULT -1, change_timestamp INTEGER DEFAULT -1, export_timestamp INTEGER DEFAULT -1, print_timestamp INTEGER DEFAULT -1, FOREIGN KEY(film_id) REFERENCES film_rolls(id) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY(group_id) REFERENCES images(id) ON DELETE RESTRICT ON UPDATE CASCADE);

DELETE FROM 'images_old' WHERE film_id NOT IN (SELECT id FROM 'film_rolls');

UPDATE 'images_old' SET group_id=id WHERE group_id NOT IN (SELECT id from 'images_old');

INSERT INTO 'images' SELECT * FROM 'images_old';

DROP INDEX IF EXISTS 'image_position_index';

CREATE INDEX 'image_position_index' ON 'images' (position);

DROP INDEX IF EXISTS 'images_filename_index';

CREATE INDEX 'images_filename_index' ON 'images' ( 'filename', 'version' );

DROP INDEX IF EXISTS 'images_film_id_index';

CREATE INDEX 'images_film_id_index' ON 'images' ( 'film_id', 'filename' );

DROP INDEX IF EXISTS 'images_group_id_index';

CREATE INDEX 'images_group_id_index' ON 'images' ( 'group_id', 'id' );

DROP INDEX IF EXISTS 'images_latlong_index';

CREATE INDEX 'images_latlong_index' ON 'images' ( latitude DESC, longitude DESC );

DROP TABLE 'images_old';

Report back.

**Comment by matthuska** [comment]
All commands ran without any error or output:

```
~/.config/darktable$ cp library.db library.db.test
~/.config/darktable$ sqlite3 library.db.test
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> ALTER TABLE 'images' RENAME TO 'images_old';
sqlite> CREATE TABLE 'images' (id INTEGER PRIMARY KEY AUTOINCREMENT, group_id INTEGER, film_id INTEGER, width INTEGER, height INTEGER, filename VARCHAR, maker VARCHAR, model VARCHAR, lens VARCHAR, exposure REAL, aperture REAL, iso REAL, focal_length REAL, focus_distance REAL, datetime_taken CHAR(20), flags INTEGER, output_width INTEGER, output_height INTEGER, crop REAL, raw_parameters INTEGER, raw_denoise_threshold REAL, raw_auto_bright_threshold REAL, raw_black INTEGER, raw_maximum INTEGER, license VARCHAR, sha1sum CHAR(40), orientation INTEGER, histogram BLOB, lightmap BLOB, longitude REAL, latitude REAL, altitude REAL, color_matrix BLOB, colorspace INTEGER, version INTEGER, max_version INTEGER, write_timestamp INTEGER, history_end INTEGER, position INTEGER, aspect_ratio REAL, exposure_bias REAL, import_timestamp INTEGER DEFAULT -1, change_timestamp INTEGER DEFAULT -1, export_timestamp INTEGER DEFAULT -1, print_timestamp INTEGER DEFAULT -1, FOREIGN KEY(film_id) REFERENCES film_rolls(id) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY(group_id) REFERENCES images(id) ON DELETE RESTRICT ON UPDATE CASCADE);
sqlite> DELETE FROM 'images_old' WHERE film_id NOT IN (SELECT id FROM 'film_rolls');
sqlite> UPDATE 'images_old' SET group_id=id WHERE group_id NOT IN (SELECT id from 'images_old');
sqlite> INSERT INTO 'images' SELECT * FROM 'images_old';
sqlite> DROP INDEX IF EXISTS 'image_position_index';
sqlite> CREATE INDEX 'image_position_index' ON 'images' (position);
sqlite> DROP INDEX IF EXISTS 'images_filename_index';
sqlite> CREATE INDEX 'images_filename_index' ON 'images' ( 'filename', 'version' );
sqlite> DROP INDEX IF EXISTS 'images_film_id_index';
sqlite> CREATE INDEX 'images_film_id_index' ON 'images' ( 'film_id', 'filename' );
sqlite> DROP INDEX IF EXISTS 'images_group_id_index';
sqlite> CREATE INDEX 'images_group_id_index' ON 'images' ( 'group_id', 'id' );
sqlite> DROP INDEX IF EXISTS 'images_latlong_index';
sqlite> CREATE INDEX 'images_latlong_index' ON 'images' ( latitude DESC, longitude DESC );
sqlite> DROP TABLE 'images_old';
sqlite> 
```

**Comment by HansBull** [comment]
At that point, one can go all the way to version. Let's see if there are errors





ALTER TABLE 'history' RENAME TO 'history_old';

CREATE TABLE 'history' (imgid INTEGER, num INTEGER, module INTEGER, operation VARCHAR(256), op_params BLOB, enabled INTEGER, blendop_params BLOB, blendop_version INTEGER, multi_priority INTEGER, multi_name VARCHAR(256), FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE);

DELETE FROM 'history_old' WHERE imgid NOT IN (SELECT id FROM 'images');

INSERT INTO history SELECT * FROM history_old;

DROP INDEX IF EXISTS 'history_imgid_index';

CREATE INDEX 'history_imgid_op_index' ON 'history' ( 'imgid', 'operation' );

CREATE INDEX 'history_imgid_num_index' ON 'history' ( 'imgid', 'num' DESC );

DROP TABLE 'history_old';

ALTER TABLE 'history_hash' RENAME TO 'history_hash_old';

CREATE TABLE 'history_hash' (imgid INTEGER PRIMARY KEY, basic_hash BLOB, auto_hash BLOB, current_hash BLOB, mipmap_hash BLOB, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE);

DELETE FROM 'history_hash_old' WHERE imgid NOT IN (SELECT id FROM 'images');

INSERT INTO 'history_hash' SELECT * FROM 'history_hash_old';

DROP TABLE 'history_hash_old';

ALTER TABLE 'tagged_images' RENAME TO 'tagged_images_old';

CREATE TABLE 'tagged_images' (imgid integer, tagid integer, position INTEGER, primary key(imgid, tagid), FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE);

DELETE FROM 'tagged_images_old' WHERE imgid NOT IN (SELECT id FROM 'images');

INSERT INTO 'tagged_images' SELECT * FROM 'tagged_images_old';

DROP INDEX IF EXISTS tagged_images_imgid_index;

DROP INDEX IF EXISTS tagged_images_position_index;

CREATE INDEX tagged_images_position_index ON tagged_images (position);

DROP INDEX IF EXISTS tagged_images_tagid_index;

CREATE INDEX tagged_images_tagid_index ON tagged_images (tagid);

DROP TABLE 'tagged_images_old';

ALTER TABLE 'masks_history' RENAME TO 'masks_history_old';

CREATE TABLE masks_history (imgid INTEGER, num INTEGER, formid INTEGER, form INTEGER, name VARCHAR(256), version INTEGER, points BLOB, points_count INTEGER, source BLOB, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE);

DELETE FROM 'masks_history_old' WHERE imgid NOT IN (SELECT id FROM 'images');

INSERT INTO 'masks_history' SELECT * FROM 'masks_history_old';

DROP INDEX IF EXISTS 'masks_history_imgid_index';

CREATE INDEX 'masks_history_imgid_index' ON 'masks_history' ( imgid, num );

DROP TABLE masks_history_old;

ALTER TABLE 'color_labels' RENAME TO 'color_labels_old';

CREATE TABLE 'color_labels' (imgid INTEGER, color INTEGER, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE);


DELETE FROM 'color_labels_old' WHERE imgid NOT IN (SELECT id FROM 'images');

INSERT INTO 'color_labels' SELECT * FROM 'color_labels_old';

DROP TABLE color_labels_old;

CREATE UNIQUE INDEX 'color_labels_idx' ON 'color_labels' (imgid, color);

ALTER TABLE 'meta_data' RENAME TO 'meta_data_old';

CREATE TABLE 'meta_data' (id integer, key integer, value varchar, FOREIGN KEY(id) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE);

DELETE FROM 'meta_data_old' WHERE id NOT IN (SELECT id FROM 'images');

INSERT INTO 'meta_data' SELECT * FROM 'meta_data_old';

DROP TABLE meta_data_old;

CREATE UNIQUE INDEX 'metadata_index' ON 'meta_data' (id, key, value);

ALTER TABLE 'selected_images' RENAME TO 'selected_images_old';

CREATE TABLE 'selected_images' (imgid INTEGER PRIMARY KEY, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE);

DELETE FROM 'selected_images_old' WHERE imgid NOT IN (SELECT id FROM 'images');

INSERT INTO 'selected_images' SELECT * FROM 'selected_images_old';

DROP TABLE selected_images_old;

ALTER TABLE 'module_order' RENAME TO 'module_order_old';

CREATE TABLE 'module_order' (imgid INTEGER PRIMARY KEY, version INTEGER, iop_list VARCHAR, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE);

DELETE FROM 'module_order_old' WHERE imgid NOT IN (SELECT id FROM 'images');

INSERT INTO 'module_order' SELECT * FROM 'module_order_old';

DROP TABLE module_order_old;

**Comment by matthuska** [comment]
Again, no errors on any of those commands.

**Comment by HansBull** [comment]
Strange. Does a `pragma integrity_check;` on the original database show any errors?

In any case, your copy should now be up to v33. You can try to bump it to 34 with

CREATE INDEX IF NOT EXISTS images_datetime_taken_nc ON images (datetime_taken COLLATE NOCASE);

CREATE INDEX IF NOT EXISTS metadata_index_key ON meta_data (key);

INSERT OR REPLACE INTO db_info (key, value) VALUES ('version', 34);

and try to open the copy with darktable. 
You could check via `SELECT sql FROM sqlite_master` if the table definitions in the manually upgraded copy match those of a virgin database.

**Comment by matthuska** [comment]
The integrity check passed without any errors. I bumped the database to version 34, and darktable starts successfully now. I diffed the output sql (after removing some quote characters that were causing spurious differences), and the differences are all related to cascading deletes that are only in my database and not in the freshly created database. Some are just a change in the ordering of the DELETE and UPDATE, but in some cases that trigger is missing from the freshly created database:

```
$ diff <(sort schema-fresh.txt) <(sort schema-manually-upgraded-noquotes.txt)
17c17
< CREATE TABLE color_labels (imgid INTEGER, color INTEGER)
---
> CREATE TABLE color_labels (imgid INTEGER, color INTEGER, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)
20,21c20,21
< CREATE TABLE history_hash (imgid INTEGER PRIMARY KEY, basic_hash BLOB, auto_hash BLOB, current_hash BLOB, mipmap_hash BLOB, FOREIGN KEY(imgid) REFERENCES images(id) ON UPDATE CASCADE ON DELETE CASCADE)
< CREATE TABLE history (imgid INTEGER, num INTEGER, module INTEGER, operation VARCHAR(256), op_params BLOB, enabled INTEGER, blendop_params BLOB, blendop_version INTEGER, multi_priority INTEGER, multi_name VARCHAR(256), FOREIGN KEY(imgid) REFERENCES images(id) ON UPDATE CASCADE ON DELETE CASCADE)
---
> CREATE TABLE history_hash (imgid INTEGER PRIMARY KEY, basic_hash BLOB, auto_hash BLOB, current_hash BLOB, mipmap_hash BLOB, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)
> CREATE TABLE history (imgid INTEGER, num INTEGER, module INTEGER, operation VARCHAR(256), op_params BLOB, enabled INTEGER, blendop_params BLOB, blendop_version INTEGER, multi_priority INTEGER, multi_name VARCHAR(256), FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)
22a23
> CREATE TABLE iop_defaults (operation varchar, op_params blob, enabled integer, model varchar, maker varchar)
24,27c25,28
< CREATE TABLE masks_history (imgid INTEGER, num INTEGER, formid INTEGER, form INTEGER, name VARCHAR(256), version INTEGER, points BLOB, points_count INTEGER, source BLOB, FOREIGN KEY(imgid) REFERENCES images(id) ON UPDATE CASCADE ON DELETE CASCADE)
< CREATE TABLE meta_data (id INTEGER, key INTEGER, value VARCHAR)
< CREATE TABLE module_order (imgid INTEGER PRIMARY KEY, version INTEGER, iop_list VARCHAR)
< CREATE TABLE selected_images (imgid INTEGER PRIMARY KEY)
---
> CREATE TABLE masks_history (imgid INTEGER, num INTEGER, formid INTEGER, form INTEGER, name VARCHAR(256), version INTEGER, points BLOB, points_count INTEGER, source BLOB, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)
> CREATE TABLE meta_data (id integer, key integer, value varchar, FOREIGN KEY(id) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)
> CREATE TABLE module_order (imgid INTEGER PRIMARY KEY, version INTEGER, iop_list VARCHAR, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)
> CREATE TABLE selected_images (imgid INTEGER PRIMARY KEY, FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)
30c31
< CREATE TABLE tagged_images (imgid INTEGER, tagid INTEGER, position INTEGER, PRIMARY KEY (imgid, tagid),FOREIGN KEY(imgid) REFERENCES images(id) ON UPDATE CASCADE ON DELETE CASCADE)
---
> CREATE TABLE tagged_images (imgid integer, tagid integer, position INTEGER, primary key(imgid, tagid), FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)
33c34
```

**Comment by johnny-bit** [comment]
@HansBull - would that mean that new db is created without necessary indexes or old dbs don't have correct indexes? Bunch of missing Primary & foreign keys...
