### ISSUE TITLE
Darktable 3.4 and now 3.6 hangs randomly when using some modules

### ISSUE THREAD

**Issue by mmoqui** [darktable-org/darktable#9496]
**Introduction**

In a new laptop (a Lenovo Thinkpad T15Gen1 of December 2020) running Linux Mint 20.2, Darktable 3.4 and 3.6 hang randomly when using a module in the scene-referred workflow and it is impossible to kill it. I have to shutdown electrically my PC.

**Describe the bug/issue**

Some times, when using some modules like Filmic RVB, Tone Equalizer or Balance RVB, Darktable hangs.  It can also occurs with others modules but latters are those I use the most. It hangs during the work of a module (the message as being processing is displayed on the image). It is then impossible to kill it. I can kill the UI (with `xkill`) but not the engine. When I wish to know the PID of Darktable, the command `ps` and `htop` hangs after listing some running processes whereas `top` is ok. The command `kill -9` or `kill -15` doesn't work against the Darktable process. The only solution is to shutdown my PC but it cannot do it correctly because `systemd` is waiting for Darktable to stop; so I have to push the startup/shutdown button of my laptop for a while until to stop electrically the system. 

**To Reproduce**

The issue is occurring randomly. So it is hard to list a sequence to reproduce the bug.

**Platform**

* darktable version : 3.4 and 3.6
* OS                :  Linux 5.8.0-59-generic (required for having some hardware to work correctly)
* Linux - Distro    : Linux Mint 20.2
* Memory            :  32Go
* Graphics card     : nvidia GeForce MX330 (nvidia on-demand)
* Graphics driver   : nvidia-driver-460 460.80-0ubuntu0.20.04.2
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              :  1:7.7+19ubuntu14
* Desktop           : Cinnamon 5.0.4+uma
* GTK+              :  3.24.20-0ubuntu1 and 2.24.32-4ubuntu4
* gcc               :  4:9.3.0-1ubuntu2
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**

The bug doesn't occur with another old laptop, a Lenovo Thinkpad T450 without any external graphic cards running the same Linux distribution and the same version of this distribution (but with a kernel 5.4 instead of 5.8). So I think it comes from hardware configuration.
I uploaded the last output of Darktable when the bug was occurring (`darktable -d all &> darktable.log`)

[darktablerc.txt](https://github.com/darktable-org/darktable/files/6795892/darktablerc.txt)
[darktable.log](https://github.com/darktable-org/darktable/files/6795874/darktable.log)

**Comment by elstoc** [comment]
Have you tried disabling OpenCL to see if you still get the error?

**Comment by mmoqui** [comment]
> Have you tried disabling OpenCL to see if you still get the error?

Not yet. I will do the next time

**Comment by RawConvert** [comment]
Do you put linux into sleep mode with dt still invoked, i.e. not quit?

**Comment by mmoqui** [comment]
> Do you put linux into sleep mode with dt still invoked, i.e. not quit?

No. Why do such a thing?

**Comment by RawConvert** [comment]
I say sleep, perhaps that's the windows term, for linux "suspend" maybe. Anyway, it's that function that saves your open apps and environment whilst you shut down the computer for hours or days, and when you resume, everything is quickly ready for you to continue working.  Do you do that?

**Comment by mmoqui** [comment]
No, but I will give it a try

**Comment by RawConvert** [comment]
ok but before you do....    The reason I asked is that I have a suspicion that using suspend can cause dt to crash!  I used to get a certain number of random crashes, and became suspicious it was related to suspending (I use Ubuntu).  Several months ago I got into the habit of quitting dt before going into suspend, and I have had few or maybe no crashes since then.  So had you been suspending, I'd have suggested quit dt first and see how it goes...

**Comment by mmoqui** [comment]
> ok but before you do.... The reason I asked is that I have a suspicion that using suspend can cause dt to crash! I used to get a certain number of random crashes, and became suspicious it was related to suspending (I use Ubuntu). Several months ago I got into the habit of quitting dt before going into suspend, and I have had few or maybe no crashes since then. So had you been suspending, I'd have suggested quit dt first and see how it goes...

Ha ok. In fact because my laptops start and stop quickly (even the 5 years old one, thanks to GN/Linux and the SSD disk), I haven't the need to use the suspend/hibernate functionality. And the problem occurs when I launch Darktable, do some stuffs and then after some minutes Darktable hangs in the middle of a task!

**Comment by mmoqui** [comment]
For information, after disabling OpenCL and do some images postprocessing, I didn't encounter the problem. Seams to be related to the use of OpenCL by Darktable to perform some tasks.

**Comment by johnny-bit** [comment]
with "nvidia on demand" i assume ou have integrated graphics card and geforce for "heavy lifting". In that case  you have to configure the system to use only geforce when doing opencl and to not disable it for powersaving or anythink, because darktable won't switch off bound devices.

**Comment by mmoqui** [comment]
> with "nvidia on demand" i assume ou have integrated graphics card and geforce for "heavy lifting". In that case you have to configure the system to use only geforce when doing opencl and to not disable it for powersaving or anythink, because darktable won't switch off bound devices.

Yes. Both graphic cards (the Intel HD and the nvidia ones) support OpenCL. So it seams to me the setting "multiple GPU" is chosen automatically by Darktable (I've played with this settings to see if it fixes the problem). Nevertheless, even with the setting "default", the problem also occurs.
For the on-demand management, on GNU/Linux (and particularly on my distribution), the use of the nvidia GPU is done when asked explicitly when running a given application (it is not done automatically like in Windows or MacOS X). Otherwise it is the Intel HD that is used by default. It seams to me Darktable uses all the available GPUs  when they support OpenCL, whatever the GPU system setting. When I start Darktable to run explicitly on the nvidia GPU, it hangs quickly just by switching the modules group tab (Just tested right now)! And hence the command `nvidia-smi` blocks at the displaying of the usage in resources of the hanged Darktable process.

**Comment by johnny-bit** [comment]
sounds more and more like drivers issue tbh. youd have to observe dmesg, systemlog, darktable log... but switching module group NEVER uses opencl (after all, switching module group has nothing to do with processing)

**Comment by mmoqui** [comment]
dmesg and syslog output the same trace. There is nothing in Darktable log because it is blocked.

[dmesg.txt](https://github.com/darktable-org/darktable/files/6802101/dmesg.txt)

**Comment by johnny-bit** [comment]
actually that's bad idea.

opencl on intel when you have "beefy" card is really suboptimal and really we've had several issues with intel's opencl. it's never gotten to the point of being reliable. Try it this way - uninstall intel's opencl and see if you still get hangs. if not - there's your culprit.

**Comment by mmoqui** [comment]
> actually that's bad idea.
> 
> opencl on intel when you have "beefy" card is really suboptimal and really we've had several issues with intel's opencl. it's never gotten to the point of being reliable. Try it this way - uninstall intel's opencl and see if you still get hangs. if not - there's your culprit.

Ok, I've just tested it and, indeed, the culprit is the Intel's OpenCL driver (or the OpenCL hardware support of the Intel HD chipset)

**Comment by johnny-bit** [comment]
Great! So - please fill issue report with intel drivers then and link here :) I bet people would love if their drivers were working ok.
