### ISSUE TITLE
exiv2 error messages when importing raw file

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#9499]
3.7.0+245~g05f381e95    Ubuntu
When I import a new raw, or drag/drop it into lighttable, I'm getting this pair of lines in the Terminal window from which I'm running dt -

[exiv2 read_exif_tag] Invalid tag name or ifdId `CalibrationIlluminant3', ifdId 1
[exiv2 _exif_decode_exif_data] _5D_02692.CR2: Invalid tag name or ifdId `ColorMatrix3', ifdId 1

**Comment by Nilvus** [comment]
Your master version is quite old. A fix about exiv2 and illuminant had been merged few hours ago. So this is probably fix. See  #9479. Please update to last master. If you can't reproduce, please so close this issue. Thanks.

**Comment by johnny-bit** [comment]
IMO the issue was fixed with #9479 so plz check and if it's the case close. At least I cannot reproduce problem after #9479

**Comment by RawConvert** [comment]
Yes, no longer happening, cheers.
