### ISSUE TITLE
Pressing hotkey 't' in darkroom crashes darktable

### ISSUE THREAD

**Issue by Thanatomanic** [darktable-org/darktable#9505]
**To Reproduce**
Self-evident from the title. Press 't' in darkroom. It will crash darktable, regardless of the opened image. "An unhandled exception" is thrown.

**Expected behavior**
No crash. Not sure if 't' should be mapped to something.

**Which commit introduced the error**
It is present in `3.7.0+279~g5ffce60f0` on Windows 10 as per attached crash log. I have not tried to reproduce on Linux yet.

**Crash log**
[darktable_bt_AKR250.txt](https://github.com/darktable-org/darktable/files/6797559/darktable_bt_AKR250.txt)

**Comment by Thanatomanic** [comment]
On Linux it doesn't crash, but gives the message "no camera with tethering support available for use...".

I am not sure if I should have done anything during compilation to enable/disable tethering or something. In any case, I don't think the application should crash.

**Comment by TurboGit** [comment]
I suspect this is fixed now.

**Comment by ralfbrown** [comment]
3.7.0+279 crashes under Linux, current +331 does not.

**Comment by TurboGit** [comment]
The fix is 5b7ef5de357d679858b2d378953c1315695c7d0f.

**Comment by Thanatomanic** [comment]
@TurboGit Apologies, I incorrectly believed I had pulled the latest sources.
