### ISSUE TITLE
Export overwrite warning -- is there a way to turn this off?

### ISSUE THREAD

**Issue by SteveLamont** [darktable-org/darktable#9506]
**Is your feature request related to a problem? Please describe.**
In earlier versions of Darktable, when you pressed Ctrl-E to export an image and you had "overwrite" set in the export controls, it just exported the image. Now you get a warning message saying that overwrite is set. This happens whether an image by the current name exists or not.

**Describe the solution you'd like**
I'd like to be able to turn off this redundant message. I very intentionally set export to "overwrite" and am aware that the output will be overwritten. Either make it a "Preferences" option or revert to the earlier behavior (the former probably being preferable).

**Alternatives**
N/A

**Additional context**
N/A

**Comment by ralfbrown** [comment]
preferences|security|ask before exporting in overwrite mode

**Comment by johnny-bit** [comment]
> is there a way to turn this off?

yes

> Either make it a "Preferences" option

it is:
https://www.darktable.org/usermanual/3.6/en/preferences-settings/security/

also was part of release notes:

https://www.darktable.org/2021/07/darktable-360-released/

> The prompt that appears when exporting in overwrite mode is now optional and controlled by a security preference.
