### ISSUE TITLE
Newest NVidia Drivers (47X.XX) disables OpenCL

### ISSUE THREAD

**Issue by jinzapper** [darktable-org/darktable#9507]
**Describe the bug/issue**
OpenCL fails to compile with this error when running darktable-cltest.exe:
Unresolved extern function '__nv_fast_exp2f'
[opencl_init] failed to compile program `blendop.cl'

**To Reproduce**
1. Make sure you have the latest game ready drivers from Nvidia Installed  (47X.XX) and using Windows 10 (2020H2 or 2021H1)
2. Install darktable 3.4 or 3.6
3. Run  darktable-cltest.exe in command prompt
4. blenop.cl will fail to compile

**Expected behavior**
OpenCL shoudl remain enabled as the system remains able to run OpenCL.

**Platform**

* darktable version : 3.6.0
* OS                :  Windows 10 (2020H2, 2021H1)
* Memory            :  32GB DDR4 2666
* Graphics card     :  RTX 2070
* Graphics driver   :  471.11
* OpenCL installed  :  Yes
* OpenCL activated  :  Yes
* CMAKE_BUILD_TYPE  :

**Comment by wpferguson** [comment]
This is a bug with the Nvidia drivers.  Downgrade to 460.xxx.
