### ISSUE TITLE
darktable 3.6 broken.

### ISSUE THREAD

**Issue by biggestpersonalive** [darktable-org/darktable#9508]
Darktable was working just fine before 3.6 but now it's completely broken; my pictures look fine in preview but when I go to edit them darktable randomly edits them in ways that I can't even track down and it's very frustrating how bad it is now. Please fix or allow me to load a previous version or something. Thanks

**Comment by Nilvus** [comment]
Please provide an issue with precise step by step and infos asked in template issue. How do you want to understand "darktable randomly edits them in ways that I can't track down".

I never see randomly edits things. So please be more precise. You can also provide examples (screenshots, raw, xmp...). If you want help, help us understand your issue.

**Comment by MStraeten** [comment]
using https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title= can help to be more precise

**Comment by johnny-bit** [comment]
Please describe the problems you're facing in clear and concise manner using full [new issue template](https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title=)

Closing this one since it has no actionable info.
