### ISSUE TITLE
segfault at start dt 3.7.0+337~ge691a05835

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#9510]
Morning!

Manjaro
Ryzen 3900+
32 gig RAM
gfx 1660-Ti
Nvidia proprietary drivers 465.31
opencl

I just fetched present darktable-git (AUR) 3.7.0+337~ge691a05835.
Removed old darktable folders in .config and .cache.
_darktable-cmstest_ gave normal response
_darktable-cltest_ gave normal response
But I cannot start _darktable_ it segfaults when I try, leaving this backtrace
[darktable_bt_X10E60.txt](https://github.com/darktable-org/darktable/files/6799690/darktable_bt_X10E60.txt)

**Comment by TurboGit** [comment]
I have just pushed a possible fix. Can you check on your side and report? TIA.

**Comment by ClaesGitHub** [comment]
Thank you for swift handling!
I just fetched _darktable 3.7.0+338~ge1d7ef8a95_
and it gives normal responses.
