### ISSUE TITLE
Interesting behavior when switching languages

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#9511]
Hello

When I try to switch the language, I get the following:
- the mouse pointer changes from an ordinary arrow to pic.1.
- messages as in pic.2 appear in the lower half of the screen as a reaction to mouse manipulations. No other reaction takes place. Doesn't react to the keyboard either.

Loss of focus by the application (switching to the window of any other program) helps. After that, the working capacity is restored. 

On Debian 10 everything works fine.

Darktable Version: master
OS: Win 7

![pic 1](https://user-images.githubusercontent.com/15331117/125326773-9888b000-e36c-11eb-8fd3-6e1e76c40d9e.jpeg)
![pic 2](https://user-images.githubusercontent.com/15331117/125326774-9aeb0a00-e36c-11eb-9760-0b35dd744967.jpeg)

**Comment by wpferguson** [comment]
@esq4 steps to reproduce?

**Comment by esq4** [comment]
> @esq4 steps to reproduce?

Hmm... I use Russian and English languages on Win 7. Steps: to switch the language in lighttable or darkroom.

**Comment by wpferguson** [comment]
So, do you start darktable with one language active, then switch to the other while it is running?  If this is the case, do other windows applications handle the transition without problems?

**Comment by esq4** [comment]
> So, do you start darktable with one language active, then switch to the other while it is running? 

Yes.

> If this is the case, do other windows applications handle the transition without problems?

Yes.

This problem was definitely not present in version 3.5 (I didn't build version 3.6).

**Comment by dterrahe** [comment]
Do you use a (windows) shortcut key combination to switch languages? It would be helpful if you described in detail the individual actions you take, to the level of key presses, even if they are completely obvious _to you_. We don't use our systems in the same way, so they are not obvious _to us_.

The completely overhauled shortcut system interacts with the keyboard in a different way and if this interferes with the way you use windows, I need to find a workaround. What I suspect happens is that dt tries to interpret the windows change-keyboard-layout shortcut (you switch keyboard layouts, not languages, correct?) as the start of a new-style dt shortcut.

**Comment by esq4** [comment]
![image](https://user-images.githubusercontent.com/15331117/126074875-8030375a-5f51-4398-a524-542197c75d47.png)
I switch Language here by mouse.

**Comment by esq4** [comment]
```
11.777394   [dt_shortcut_move] shortcut received: 0xffffff, diagonal, up
11.789394   [dt_shortcut_move] shortcut received: 0xffffff, diagonal, up
```
When I run the _darktable_ with the option _-d input_, such lines appear in the log only after switching the language.

**Comment by dterrahe** [comment]
Many thanks for reporting this issue @esq4 

Apparently Windows sends a code GDK_KEY_VoidSymbol when switching languages. The shortcut interpreter will need to explicitly ignore this.
