### ISSUE TITLE
problem with defining shortcuts

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#9512]
I use Russian and English languages on Win 7.
When I try to define the shortcuts in English, it still gets saved in Russian. For example, **ctrl+a** is saved as **ctrl+ф**. 
And, accordingly, in the future it does not react to **ctrl+a**.

String in _shortcutsrc_ 
`Cyrillic_ef;ctrl=views/thumbtable/select all`

On Debian 10 everything works fine.

Darktable Version: master
OS: Win 7

![pic 3](https://user-images.githubusercontent.com/15331117/125329880-38940880-e370-11eb-9f52-049c59fef6a4.jpeg)

**Comment by wpferguson** [comment]
@esq4 steps to reproduce?

**Comment by esq4** [comment]
> @esq4 steps to reproduce?

_There are Russian and English languages on my Win 7._

Steps: open _preferences/shortcuts_ and define the English letter on some shortcut.

**Comment by wpferguson** [comment]
When you started darktable, what language was active?  The software doesn't check while it's running to see if the user changed languages while it was active.

**Comment by esq4** [comment]
> When you started darktable, what language was active?

English by default.

> The software doesn't check while it's running to see if the user changed languages while it was active.

May be "the software does not have to check while it's running to see if the user changed languages while it was active"?

This problem was definitely not present in version 3.5 (I didn't build version 3.6). True, there was another bug in it, but it did not interfere with the work.

**Comment by dterrahe** [comment]
What is the name of the keyboard layout you are using?

> For example, **ctrl+a** is saved as **ctrl+ф**.

To enter "ctrl+a" do you just press those two keys, or do you also need to press the AltGr key?

> in the future it does not react to **ctrl+a**.

Do you mean it _never_ reacts to ctrl+a (even if you haven't changed languages and enter the combination in exactly exactly the same way)?

**Comment by esq4** [comment]
> What is the name of the keyboard layout you are using?

For English - USA, for Russian - Russian.



> To enter "ctrl+a" do you just press those two keys, or do you also need to press the AltGr key?

I press 2 keys. There is no AltGr key on my keyboard.



> Do you mean it _never_ reacts to ctrl+a (even if you haven't changed languages and enter the combination in exactly exactly the same way)?

hmm ... strange, but I can't reproduce it anymore. I'll take a break and maybe close this issue.

**Comment by dterrahe** [comment]
I have not been able to reproduce either, but I am using Windows 10, so I started to suspect there might be differences in behavior between versions. This is why we ask that exact detailed steps are provided by the user/tester to reproduce so that we can quickly verify we have the same issue or that possibly there are other causes related to configuration differences. Trying to reproduce a bug that only occurs under particularly use cases that the maintainer isn't familiar with can take a lot of time and effort that we then do not have to spend on other bugfixes or features. If we cannot reproduce, we cannot determine the cause and therefore not implement and test remedies.

**Comment by esq4** [comment]
This problem no longer occurs.

**Comment by XAndrey** [comment]
Yes, i have same bug and i may to reproduce it all the time.

**Comment by dterrahe** [comment]
Reproducing means providing a set of steps that will _always_ (also, crucially, on someone else's machine, not just yours) to the bug as reported. As you can see above, I spent some time with @esq4 trying to reproduce the bug on my machine and we only succeeded in making it go away on _his_.

The only alternative is to invite me over for tea sometime so I can have a look at what is happening on _your_ machine. Or remotely if you were happy with that. But that would mean not having access to my development environment.
