### ISSUE TITLE
CANON EOS M50 m2

### ISSUE THREAD

**Issue by blonchkman** [darktable-org/darktable#9513]
Dear all, 
If needed, I just uploaded  to  https://raw.pixls.us  two  image samples (RAW and C-RAW) of a color target taken by a canon eos-m50m2  

1. canon_eos-m50ii_color-target_3:2_craw.cr3
2. canon_eos-m50ii_color-target_3:2_raw.cr3

Unfortunately, during the transfer there was a hiccup and I'm not sure if the second one was saved.

Both files have neither Artist nor Copyright in the metadata. 

Please let me know if it's not OK or if it needs to be redone for any reason. 

A gigantic thank you and a huge bravo for the latest version of the darktable.

Kind regards

**Comment by kmilos** [comment]
Should be working since dt 4.0, please close.
