### ISSUE TITLE
Adjust thumbnail borders based on rating/rejection

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#9518]
**Describe the solution you'd like**

I like the clutterless look of the thumbnails in lighttable and darkroom mode. But at the same time I want to edit and cull the photos while keeping my eye on the rejected ones. Ideally I would want to see darkened or otherwise styled borders for thumbnails of rejected images.

**Alternatives**

I can always activate the "permament overlays" in lighttable module. It won't have an effect in darkroom film roll, though.

**Additional context**

The custom CSS rules was my initial place to venture but the CSS3 selectors aren't flexible enough to allow this modification.

I don't know GTK but if these UI elements + CSS work like the web browser equivalents, perhaps it would be trivial to add some suitable classes to thumbnail elements and let the rest up to the stylesheets.

**Comment by TurboGit** [comment]
Would be nice indeed. Let's see what other think about this especially @Nilvus who is handling most of the GUI stuff.

**Comment by Nilvus** [comment]
> **Alternatives**
> 
> I can always activate the "permament overlays" in lighttable module. It won't have an effect in darkroom film roll, though.

You can activate that too for film roll in darkroom. Just make film roll visible and be sure top bar is also visible. and you can click on star icon and so select overlay for film roll.

> Ideally I would want to see darkened or otherwise styled borders for thumbnails of rejected images.

This is a good idea. As @johnny-bit said, this would need more than CSS for image rating but maybe not for rejected one. Will check and test some things. Will come back later to post feedback of my testings.

**Comment by Nilvus** [comment]
I was quite optimist and just forget that CSS allow to apply something to a child or an item following another but not in the opposite way like here. So this will not be possible without Gtk code to apply a specific class in thumb_back widget related thumb_reject for rejected images. As @johnny-bit answers! So not my skills here for that first part. If someone want to do the Gtk part, I could finish after the CSS one.

**Comment by TurboGit** [comment]
@Nilvus : See #9532 for fist step to support rejected images styling.

**Comment by TurboGit** [comment]
@AlicVB : I may have a better idea, what could be nice is to have a faded thumb, not only the background but the whole thumb including the image. Do you think something like that could be possible? I'm thinking of some overlay on top of the thumb with witch we could change the opacity to fad it.

**Comment by Nilvus** [comment]
> @AlicVB : I may have a better idea, what could be nice is to have a faded thumb, not only the background but the whole thumb including the image. Do you think something like that could be possible? I'm thinking of some overlay on top of the thumb with witch we could change the opacity to fad it.

I love the idea personally!
