### ISSUE TITLE
(BUG) Latest master: Add to library creates strange characters/ is unusable (bisected)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#9522]
**Describe the bug/issue**
When trying to add/use the *add to library...* section I get garbed glyphs were my directory used to be.

The top entry (home) is readable, the rest is not and there are related messages create din the terminal:

`(darktable:29762): Pango-WARNING **: 15:34:05.981: Invalid UTF-8 string passed to pango_layout_set_text()`

It is also impossible to remove this entry using right mouse click once it is garbled. Only removing it from darktablerc will get you back to its original (= home dir only) state.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Activate *add to library...*
2. a) If you already have a second entry: It is garbled.
2. b) Created a second entry. Press cancel and/or restart dt: Entry is now garbed.

**Expected behaviour**
No garbled text and a useable link

**Screenshots**

![atlsc](https://user-images.githubusercontent.com/56407344/125464913-1aa40db6-6130-44bb-a348-4fbe243f46f6.jpg)

**Screencast**
Starting from a clean slate:

https://user-images.githubusercontent.com/56407344/125465113-8a65b68c-3834-4f61-8738-de41a68434d6.mp4

When you see the glyphs change I'm pressing right mouse click to try to remove the entry.

**Which commit introduced the error**

```
[stasis] jade ~/.local/git/darktable $ git bisect bad
4a41b080a7bcd926827bdd0a045e56ad6f74b6d1 is the first bad commit
commit 4a41b080a7bcd926827bdd0a045e56ad6f74b6d1
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Tue Jun 22 02:40:57 2021 -0400

    use dt_conf_get_conststring where possible, ensure return from dt_conf_get_string freed

:040000 040000 cb27ddf9536c91eb457276ec973396f53339b1ae b6cc49785c80637212922608e5d42f644611cd0b M      src
```

During the bisecting of this issue dt crashed multiple times when I started it. Not even being able to test this bug (I marked these as *bad*). All of these where steps with the following shown: *use dt_conf_get_conststring where possible, ensure return from dt_conf_get_string freed*

Pinging: @ralfbrown

**Platform**
* darktable : 3.7.0+356~g114a3d248 (noticed it in the previous one, updated to make sure).
* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : clang 10.0.1
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Sqlite        : 3.27.2
* Optimization  : None

**Additional context**

 - Can you reproduce with another darktable version(s)? NO 3.6.0 is fine. See bisect info for 3.7
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? YES
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? YES

**Comment by johnny-bit** [comment]
Pinging @ralfbrown on this...

**Comment by TurboGit** [comment]
Not sure the bisected commit is the right one, we know this commit has some bug fixed later like a double-free. But of course everything is possible :)

**Comment by jade-nl** [comment]
@ralfbrown : Just pulled, merged and build your import_fix branch and this fixes the problem for me.

You (or @TurboGit) can close this one when your PR gets merged into master.

**Comment by TurboGit** [comment]
This is closing automatically when the branch is merged. Thanks for testing.
