### ISSUE TITLE
copy/paste history stack does not work with custom module order

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#9523]
self compiled DT 3.6.0 on Windows 10 (but same on Ubuntu), OpenCL activated on nVidia GPU

When copying/pasting history stack between images, a custom module order is not applied correctly.
To reproduce:

1. Start with a fresh edit
2. Do an edit which involves a custom module order. For example, I often use the module lowpass put after filmic rgb and blended in softlight mode
3. Take a snapshot
4. Now copy paste the history on a another image. For example on a virgin duplicate of the same image
5. From the gui, it seem lowpass is pasted in the right place, after filmic rgb, however...
5. Compare with the snapshot taken in point 3 and see they are not the same, this is wrong
6. As a counter-proof, reset the module order
7. Re-position manually lowpass after filmic rgb
8. Now the image is equal to the snapshot

**Comment by johnny-bit** [comment]
You mean 3.6.0 surely?

**Comment by Mark-64** [comment]
Yes, 3.6.0, sorry for the mistake, fixed now

**Comment by johnny-bit** [comment]
@TurboGit do you think you could take a look at this? Perhaps the same is true for styles.

**Comment by TurboGit** [comment]
Sure, looks like another one for me :)

**Comment by TurboGit** [comment]
I have played a bit with this and as far as I see it seems just a refresh issue. Indeed I see the difference, but if I switch from the original to the copy via the filmstrip on darkroom the difference cannot be seen. So probably a pipe refresh missing, but the order of modules seems OK and corresponds to what is seen on the GUI. Can you confirm that @Mark-64 ?

**Comment by Mark-64** [comment]
@TurboGit 
Yes, you are right, forcing a refresh by switching the image back and forth fixes the inconsistency between the module order in the gui and the centre image, so it is indeed a refresh issue.
However, with CTRL+C the module order is not copied, to force copy the module order I have to do SHIFT+CTRL+C, is that correct? The manual doesn't say that.

**Comment by TurboGit** [comment]
> However, with CTRL+C the module order is not copied, to force copy the module order I have to do SHIFT+CTRL+C, is that correct? The manual doesn't say that.

Yes, that's expected. The Ctrl+C is always on safe side we now require that a copy-part be used to copy everything and unsafe modules.

**Comment by TurboGit** [comment]
@Mark-64 : If you can check #9588 and report if it fixes the issue on your side it would be good !

**Comment by Mark-64** [comment]
Yes it does! Thank you.
