### ISSUE TITLE
Darktable (3.6.0 on windows 10) crashes when applying style

### ISSUE THREAD

**Issue by ajschmid** [darktable-org/darktable#9526]
Hi, 
I recently upgraded to 3.6.0 (windows 10)

Darktable crashes in the following scenario on my machine:

I create a new style and save it
When  I try to apply this new style to a single image --> this typically works
When I try to apply this new style to a several images (e.g. 5+ images)  --> darktable crashes and I get the attached report

[darktable_bt_V5U650.txt](https://github.com/darktable-org/darktable/files/6812016/darktable_bt_V5U650.txt)

can you help? ... - thanks a lot Alex

**Comment by johnny-bit** [comment]
Applying style to several images works normally for me...

Can you share both the style and whether it's applied in "append" or "overwrite" mode?

**Comment by ajschmid** [comment]
Hi Hubert, thanks for coming back!
here is the style  (zipped, as the upload does not support the type "dtstyle")
[Panasonic TZ81 v03.zip](https://github.com/darktable-org/darktable/files/6814354/Panasonic.TZ81.v03.zip)

During apply I used the defaults i.e.
In lighttable I simply selected several picture and did an 'apply' of the above style in 'append'-mode.

thanks again ... - Alex

**Comment by ajschmid** [comment]
I completely uninstalled and re-installed dt and for whatever reasons everything looks fine.
I cannot re-produce the original crashes which I saw.
So from my perspective everything looks good at the moment
thanks for your help .. - Alex

**Comment by johnny-bit** [comment]
I actually tested your style and it worked for me on both win and linux... but then i forgot about it.
It might've been some weird free() error etc, but since it's working let's close it for now.
