### ISSUE TITLE
OpenCL doesn't work on Linux with NVIDIA proprietary driver 470.42.01

### ISSUE THREAD

**Issue by elman22** [darktable-org/darktable#9528]
**Describe the bug/issue**
When I upgraded both darktable to 3.6.0 and NVIDIA proprietary driver to 470.42.01, opencl is disabled.

**To Reproduce**
1. Install darktable 3.6.0 and NVIDIA proprietary driver 470.42.01

**Expected behavior**
OpenCL should be enabled.

**Platform**

* darktable version : 3.6.0
* OS                : Manjaro Linux / Kernel 5.12.16
* Memory            : 16 GB
* Graphics card     : NVIDIA GeForce GTX 970
* Graphics driver   : 470.42.01
* OpenCL installed  : yes
* OpenCL activated  : yes, but darktable fails to enable it
* Desktop           : Plasma 5.22.3

`darktable-cltest` relevant output:

```
0.187684 [opencl_init] compiling program `basic.cl' ..
0.187829 [opencl_fopen_stat] could not open file `/home/user/.cache/darktable/cached_kernels_for_NVIDIAGeForceGTX970_4704201/basic.cl.bin'!
0.187836 [opencl_load_program] could not load cached binary program, trying to compile source
0.187867 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/basic.cl' MD5: '4f8b7e85b261318d29dbeb221c8c5896'
0.330019 [opencl_build_program] could not build program: -9999
0.330035 [opencl_build_program] BUILD STATUS: -2
0.330038 BUILD LOG:
0.330039 ptxas fatal   : Unresolved extern function '__nv_fast_log2f'
```

**Comment by johnny-bit** [comment]
We know. This is nvidia's fault and nvidia's bug. Please file an issue with them and link here.

**Comment by elman22** [comment]
I was actually going to post an update that I have seen other reports indicating it's the nvidia driver, not darktable. Thank you for confirming.

**Comment by matt-maguire** [comment]
NVIDIA are aware of the bug:
https://forums.developer.nvidia.com/t/opencl-compilation-fails-with-unresolved-extern-function-nv-fast-exp2f-with-drivers-470-42-01/181632
