### ISSUE TITLE
Missing library in /external/lua/src

### ISSUE THREAD

**Issue by jbinpg** [darktable-org/darktable#9530]
After a rebase tonight, the compile of master failed with the following error:

==========

-- Configuring done
CMake Error at src/external/lua/CMakeLists.txt:36 (add_library):
  Cannot find source file:

    src/lbitlib.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at src/external/lua/CMakeLists.txt:36 (add_library):
  No SOURCES given to target: lua

CMake Generate step failed.  Build files cannot be regenerated correctly.
=========

I checked and indeed lbitlib.c is missing from the source directory.

OS: Ubuntu 21.04.
Toolchain: llvm-12

**Comment by johnny-bit** [comment]
Please see if https://github.com/darktable-org/darktable/pull/9525 fixes the issue for you.

**Comment by johnny-bit** [comment]
Weird... @wpferguson would this be for you? Similar to what was discussed on the IRC recently...

@jbinpg there was a weird workaround mentioned... can you... try creating a directory in your home dir named `0`? eg: `/home/jbinpg/0`?

**Comment by wpferguson** [comment]
Yes, this looks like mine... :/

**Comment by jbinpg** [comment]
Yes, all fine now. Thanks, Bill. Closing.
