### ISSUE TITLE
Raw files open error if folder name contains umlauts.

### ISSUE THREAD

**Issue by AufDerMauer** [darktable-org/darktable#9531]
**Problem:**

On Win10 and Darktable 3.6.0 I can't open RAW files if the folder name contains any Umlauts. (äöü)
With the previous version of darktable everything was fine.

---------------------------------------------------------------

**To Reproduce:**

1. Open Windows Explorer (Win10)
2. Navigate to a folder which contains umlauts in name
3. Choose a RAW file (in my case Panasonics RW2)
4. Right click on the image and choose "open image with Darktable"
5. When the program ist loaded the open error message appears. (Error while loading the file ...)

---------------------------------------------------------------

**Platform:**

Darktable version : 3.6.0
OS : Win10
Memory : 16 GB
Graphics card :  NVIDIA GeForce GTX 1660 Ti

---------------------------------------------------------------

**Additional context:**

RAW files from folders without Umlauts are loaded correctly.

**Comment by johnny-bit** [comment]
This bug is known and had been fixed. The fix will be present in 3.6.1 release.
see https://github.com/darktable-org/darktable/pull/9498
