### ISSUE TITLE
3D LUT strange behavior

### ISSUE THREAD

**Issue by EtToiTKi** [darktable-org/darktable#9543]
I try to use a 3dLut created with Affinity Photo.

I already entered a path for my LUTS

Sometimes my LUT looks applied on my picture but not not thumbnail, sometimes on Thumbnail but not on picture, sometimes both, sometimes none.

When I move any cursor from any module, the result changes: Sometimes my LUT looks applied on my picture but not not thumbnail, sometimes on Thumbnail but not on picture, sometimes both, sometimes none, but not the same as before.

When I export The picture, it is never applied. In The light table it is never applied.

I use the last release on Win10 x64, it happened with the previous one too.
I tryed with 32x32x32 and 64x64x64 for the same behavior.

This is the begining of my Lut File:

#Created by: Affinity Photo (Serif Europe Ltd.)
TITLE "test32"

#LUT size
LUT_3D_SIZE 32

#data domain
DOMAIN_MIN 0.0 0.0 0.0
DOMAIN_MAX 1.0 1.0 1.0

#LUT data points
0.000000 0.000000 0.000000
0.031217 0.000000 0.000000
0.060354 0.000000 0.000000
...

**Comment by johnny-bit** [comment]
lut 3d works for meee... can you attach the lut that doesn't work for you? also - seems like you havent used issue template so bunch of info is missign. things like opencl, logs etc ;)

**Comment by EtToiTKi** [comment]
Thanks for your reply. I will try to prodive ASP tif+xmp+lut  files and some screenshots, but where can I find the log file on win10? I didn't found it in %AppData%\Local\darktable

**Comment by Mark-64** [comment]
In Windows the log sits in 
C:\Users\<your-username>\AppData\Local\Microsoft\Windows\INetCache\darktable

**Comment by phweyland** [comment]
Any LUT file to play with ?

**Comment by EtToiTKi** [comment]
Sorry for the late reply. This more informations about this problem:

**Did you buy darktable from an application store ?**
	official github download

**Describe the bug/issue**
	sometimes the 3Dlut is applied on picture but not on thumbnail
	sometimes on thumblail but not on picture
	sometimes both
	sometimes there is artifacts with lut applied (see screenshots)
	this state change as I play with any cursor

**To Reproduce**
	open a file
	apply a 3Dlut file
	-> screenshot 1.jpg
	play with any cursor
	-> screenshot 2.jpg
	play with any cursor
	-> screenshot 3.jpg
	export to 5D4_9935.darktable.tif

**Screenshots**
	see zip file

**Screencast**
	nope

**Which commit introduced the error**
	I do not know
	at least current release and 2 before

**Platform**
	windows 10 x64 laptop (full up to date)
	see setup screen shot in the zip for graphic card, proc & SSD hardware details

* darktable version : e.g. 3.6.0
* OS                : e.g. Win10 (up to date)
* Memory            : 16 Go
* Graphics card     : see screenshots
* Graphics driver   : 23.21.13.8873 (18/12/2017)
* OpenCL installed  : yes?
* OpenCL activated  : yes?

**Additional context**
	this happens with any file (raw, jpeg, tif), any lut.
	the lut file was created with affinity photo (last release)
	this happens with any lut size (32*32*32, 64*64*64, etc...)

	source + xmp + lut + export files are in zip file
	download https://ufile.io/gh87aiu2 (before 21/08/2021)

	I have no lua script installed

**Comment by phweyland** [comment]
Thanks, downloading your file.

> this happens with [...] any lut.

Even with common LUT downloaded from web ?

**Comment by phweyland** [comment]
Sorry, no LUT file in downloaded zip ...

**Comment by EtToiTKi** [comment]
sorry, I forgot to put the lut + xmp files in the zip file
you can download them here:
https://ufile.io/j1s3ojy7
Yes it happens as well with a lut downloaded from web

**Comment by phweyland** [comment]
> Yes it happens as well with a lut downloaded from web

Humm... that will not simplify the problem. To find a solution we need to understand what's happening and normally the first step is to reproduced the problem.
Anyway I'll make a try with you LUT. Thanks.

**Comment by EtToiTKi** [comment]
As a software developer, maybe I could help a little more, if I could get a debug version or something like that more verbose than the public release, but the toolchain to build it is not installed on my computer, so I need a binary.
Tell me if I can help.
I'm wondering if my graphics card model could be the cause of the problem?

**Comment by phweyland** [comment]
What does happen if you disable opencl ?

**Comment by EtToiTKi** [comment]
It works, lol

**Comment by johnny-bit** [comment]
> I'm wondering if my graphics card model could be the cause of the problem?

Or drivers...

**Comment by EtToiTKi** [comment]
I'll try to update them. And I'll tell you

**Comment by EtToiTKi** [comment]
I updated my graphics card drivers to 471.41 (forced update from nvdia website) The result is still the same when opencl is enabled...

**Comment by johnny-bit** [comment]
opencl 1.2 is required.

**Comment by EtToiTKi** [comment]
maybe this explains why it does not works correctly :'(
Thanks
