### ISSUE TITLE
darktable master will no longer build with LUA support  on Ubuntu 20.04:

### ISSUE THREAD

**Issue by dtteufel** [darktable-org/darktable#9544]
-- The following OPTIONAL packages have not been found:
 * Lua54 (required version >= 5.4)

LUA 5.4 is not available on Ubuntu 20.04 :

**Comment by parafin** [comment]
pass -DDONT_USE_INTERNAL_LUA=OFF option to cmake then.

**Comment by dtteufel** [comment]
Noted, will investigate further.
Thanks

**Comment by wpferguson** [comment]
I"m thinking of building a Lua 5.4 PPA for 18.04 and 20.04, but it will be a couple of weeks before I can start on it

**Comment by dtteufel** [comment]
Ubuntu 20.04 / Mint 20.2
@wpferguson
I experimentally installed testing version of Lua5.4.0 from:
http://ftp.de.debian.org/debian/pool/main/l/lua5.4/liblua5.4-dev_5.4.2-2_amd64.deb
http://ftp.de.debian.org/debian/pool/main/l/lua5.4/liblua5.4-0_5.4.2-2_amd64.deb

dt now compiles without issue and issue #9547 no longer occurs.

**Comment by ptilopteri** [comment]
since it is no longer happening, please consider closing the issue.

**Comment by dtteufel** [comment]
Not so much 'no longer happening' as an 'experimental' workaround.

**Comment by rabauke** [comment]
Ihmo, it is a more solid work-around to build the required Lua packages fror Ubuntu 20.4 than just installing 20.10 packages on 20.4. (Both approaches have in common, that one has to watch manually for security updates.) 

As a temporary work-around I built Lua 5.4 packages on Ubuntu 20.4 essentially by the following steps:

1. Install build dependencies (of Lua 5.3, which are the same as for 5.4):
```
$ sudo apt-get build-dep lua5.3
```

2. Download [source files](https://launchpad.net/ubuntu/+source/lua5.4/5.4.2-2): `lua5.4_5.4.0-2.dsc`, `lua5.4_5.4.0.orig.tar.gz` and `lua5.4_5.4.0-2.debian.tar.xz`

3. Extract sources via
```
$ dpkg-source -x lua5.4_5.4.0-2.dsc
```

4. Build deb packages from sources via
```
lua5.4-5.4.0$ debuild -i -us -uc -b
```

5. Install packages via
```
$ sudo dpkg -i lua5.4_5.4.0-2_amd64.deb liblua5.4-0_5.4.0-2_amd64.deb liblua5.4-dev_5.4.0-2_amd64.deb
```
