### ISSUE TITLE
Browse button on Copy & Import dialogue

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#9548]
Hi devs,
The new import dialogue is a beautiful leap forward, but is, in my humble opinion, lacking one final feature.
Open up the import dialogue box, and select "Copy & Import".
Twirl the down arrow for the "Naming rules" section.
See the "Base directory naming pattern" field?
It needs a 'browse' button on the right hand end, so you could simply browse to a parent folder, and have that path loaded into the field.
For me, this would be the final nail in the coffin for Rapid Photo Downloader.
At the moment, you need to pull up your system's file browser, find the parent directory (you wish to copy your images to), copy the path, and then paste it into the "Base directory naming pattern" field.
Thanks in advance for the consideration!

**Comment by johnny-bit** [comment]
This field supports variables, that's why it doesn't have browse button AFAIK. But I don't think adding such button would hurt the field functionality...

**Comment by elstoc** [comment]
So something similar to how the export module works?

**Comment by brucewilliamsphotography** [comment]
Yeah! Just like that!

Cheers,
Bruce Williams.

**Comment by johnny-bit** [comment]
Can you try PR #9556 ? should cover your needs :)

**Comment by brucewilliamsphotography** [comment]
Hubert,
Thanks!
When you say "could I try it", are you saying I can somehow build this from
source now?
Cheers,
Bruce Williams
------------------------------
brucewilliamsphotography.com
shuttersincpodcast.com
------------------------------
e-mail ***@***.***> | Twitter
***@***.***> | LinkedIn
<http://au.linkedin.com/pub/bruce-williams/1/318/489> | Facebook
<http://www.facebook.com/audio2u>
------------------------------

**Comment by johnny-bit** [comment]
It's not in master, no... If you can try the PR it'd be great ;) or I can make a screenshot...

**Comment by brucewilliamsphotography** [comment]
Sorry... bit of a noob on this stuff.
What do I do to try the PR?
Cheers,
Bruce Williams
------------------------------
brucewilliamsphotography.com
shuttersincpodcast.com
------------------------------
e-mail ***@***.***> | Twitter
***@***.***> | LinkedIn
<http://au.linkedin.com/pub/bruce-williams/1/318/489> | Facebook
<http://www.facebook.com/audio2u>
------------------------------

**Comment by johnny-bit** [comment]
That depends on how you bulid from source.

personally i have this alias in my `~/.gitconfig`:
```ini
[alias]
	pr = "!f() { git fetch -fu ${2:-upstream} refs/pull/$1/head:pr/$1 && git checkout pr/$1; }; f"
	pr-clean = "!git checkout master ; git for-each-ref refs/heads/pr/* --format=\"%(refname)\" | while read ref ; do branch=${ref#refs/heads/} ; git branch -D $branch ; done"
```

and to test PR i just do
```sh
git pr 9556
```

then compile normally

and after I'm done testing
```sh
git pr-clean
```

Or... you could wait for others to test and then test if it makes to master :)

**Comment by brucewilliamsphotography** [comment]
I understood "That depends on how you bulid from source.".
:)
I guess I'll just wait!
Cheers,
Bruce Williams
------------------------------
brucewilliamsphotography.com
shuttersincpodcast.com
------------------------------
e-mail ***@***.***> | Twitter
***@***.***> | LinkedIn
<http://au.linkedin.com/pub/bruce-williams/1/318/489> | Facebook
<http://www.facebook.com/audio2u>
------------------------------
