### ISSUE TITLE
Canon camera not showing in lens correction list and not reconized but is supported

### ISSUE THREAD

**Issue by schoolsplay** [darktable-org/darktable#9562]
I have a Canon 800D. 
When I open a RAW image in darkroom the lens correction always fails to detect the camera. It will recognize the lens but not the camera. It tells me to add it manually. 
But the list with Canon cameras doesn't show a 800D/Rebel T7i.
Looking in /usr/share/darktable/rawspeed/cameras.xml I see that the 800D is supported (also the 80D is in the xml but not in the list)
I have double checked that the exif data displays the correct camera type and the firmware in the camera is up to date.
Not sure why multiple cameras that are inside the xml file don't show up in the "manual add" camera list?

This is the out put of the exiftool:
exiftool IMG_1638.CR2 | grep -i "camera.*name"
Camera Model Name               : Canon EOS 800D

Im using darktable 3.6.0 on Ubuntu 20.04

![camrea-list](https://user-images.githubusercontent.com/1059713/126068570-4a5165fb-7b68-4e63-b730-d9bc167a3c9b.jpg)
![Screenshot_2021-07-18_15-08-42](https://user-images.githubusercontent.com/1059713/126068572-ffb5205d-a490-4435-8248-ba2d61eb60c8.png)
![Screenshot_2021-07-18_15-09-20](https://user-images.githubusercontent.com/1059713/126068573-7a148c4c-f1ad-4eec-982d-2266d5b386fb.png)

**Comment by elstoc** [comment]
try running `lensfun-update-data` in a terminal

**Comment by schoolsplay** [comment]
Yep that solved it, the camera is found and all the 'missing' cameras are now available.
Thanks for the quick reply!

So to recap for anyone who might be having the same troubles with the Ubuntu deb from ```https://www.darktable.org/install/#3rdparty ``` eg ```https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable```.

It seems that the darktable ppa deb for Ubuntu 20.04,  is missing the dependency for ```liblensfun-bin``` which contains the above mentioned  ```lensfun-update-data```
So first install ```liblensfun-bin, sudo apt install liblensfun-bin``` and the do the ```lensfun-update-data```

I will file a bug report against the Ubuntu package for the missing dependency

**Comment by NightMyst** [comment]
used the install command and then the update command on my Zorin OS 17.3, Kernel: Linux 6.8.0-60-generic
    Architecture: x86-64.

I opened Darktable and it instantly recognized my T7i. Great info!!!
