### ISSUE TITLE
dji mini2/FC7303 raw support

### ISSUE THREAD

**Issue by zhengwy888** [darktable-org/darktable#9566]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by kmilos** [comment]
I can open [a sample](https://dronexl.co/2020/11/05/mini-2-low-light-performance-raw-auto-exposure-bracketing/) just fine (dt 3.6.0.1 on Windows).

**Comment by Nilvus** [comment]
> DT complains about 'no color matrix found'

See color matrices part on this page (at the middle of the page) for that: https://www.darktable.org/2012/10/whats-involved-with-adding-support-for-new-cameras/

**Comment by kmilos** [comment]
@Nilvus These are DNGs, so the mechanism for "adding support" and color matrix determination is slightly different...

@zhengwy888 Please be more specific (which dt version) and share a sample, i.e. is it from normal mode or something else? The sample I have linked has the expected metadata when checked w/ exiftool and causes no problems w/ dt 3.6:

```
ColorMatrix1                    : 1.6804 -0.9787 -0.2259 -0.3295 1.366 -0.0113 -0.0307 0.159 0.6367
ColorMatrix2                    : 0.6883 -0.1326 -0.0981 -0.4557 1.3643 0.0632 -0.1285 0.2585 0.4512
CalibrationIlluminant1          : Standard Light A
CalibrationIlluminant2          : D65
```

**Comment by zhengwy888** [comment]
oh I was running 3.4, upgrading to 3.6 resolved this. closing this issue and thank you!
