### ISSUE TITLE
Color Calibration module does not remember the location of the color card and reuses stale quality reports.

### ISSUE THREAD

**Issue by Waiwei8k** [darktable-org/darktable#9570]
When I have created a calibration from a color-checker in several images, I often want to return to image to 1) check if I actually calibrated it and 2) check the quality of the calibration. When I select an image, the tool aligns the patches consistent with the last image I calibrated, rather than the current image. It will also show a calibration report from the previous calibration image until I recalibrate the current image. 

I would like the module to store the location of the color card so I can perform a calibration check or recalibration without having to realign the card. It should also not show stale data. It should either show up-to-date data, or no data.

**Comment by elstoc** [comment]
IMO the calibration report should be cleared when changing images in the darkroom - i.e. the same behaviour as if you exit to the lighttable and re-enter the darkroom. I would expect the same behaviour when resetting the module parameters (which currently also fails to clear the report).
