### ISSUE TITLE
Diffuse.cl fails to build on macos Catalina

### ISSUE THREAD

**Issue by semperit89** [darktable-org/darktable#9572]
When compiling darktable on macos Catalina I get this failure for building the diffuse.cl

0.110764 [opencl_init] compiling program diffuse.cl' ..
0.110831 [opencl_fopen_stat] could not open file /Users/David/.cache/darktable/cached_kernels_for_GeForceGT755M_1403235511111010143/diffuse.cl.bin'!
0.110855 [opencl_load_program] could not load cached binary program, trying to compile source
0.110871 [opencl_load_program] successfully loaded program from '/Applications/darktable.app/Contents/Resources/share/darktable/kernels/diffuse.cl' MD5: '81cb925202461a6512a96b17f50b0cf6'
0.276237 [opencl_build_program] could not build program: -11
0.276254 [opencl_build_program] BUILD STATUS: -2
0.276267 BUILD LOG:
0.276268 ptxas application ptx input, line 363; error   : Argument 1 of instruction 'add': must be register
ptxas fatal   : Ptx assembly aborted due to errors
0.276271 [opencl_init] failed to compile program `diffuse.cl'!
0.276292 [opencl_init] no suitable devices found.
0.276294 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
0.276296 [opencl_init] initial status of opencl enabled flag is OFF.

**Comment by johnny-bit** [comment]
what nvidia drivers version?

**Comment by parafin** [comment]
As far as I know Nvidia doesn’t release drivers for macOS anymore, so I’m guessing it’s whatever version Apple shipped. Apple and Nvidia are no longer friends, so degrading support is to be expected. But, you could try removing ~/.cache/darktable/cached_kernels* and/or restarting darktable several times. Or try downgrading/upgrading the OS, which isn’t probably what you want to hear:))

**Comment by semperit89** [comment]
> what nvidia drivers version?

As parafin said, there is nothing I can do about the Nvidia drivers, they come from Apple.  My iMac is from 2013, it's getting a few security updates, but no more new drivers.


>  But, you could try removing ~/.cache/darktable/cached_kernels* and/or restarting darktable several times. Or try downgrading/upgrading the OS, which isn’t probably what you want to hear:))

I tried removing the cache, no success. Also tried a loop to build the kernel, no success. Don't think that a os downgrade would help.

Two questions come to my mind:
1. I wonder if other Mac users have the same problem?

2. Why is opencl support canceled completely just because of one missing kernel? All other kernels built successful. If I remove the diffuse things opencl is working again.

**Comment by johnny-bit** [comment]
The error looks as if it was 100% compiller fault and that it generates incorrect code.
If you're using master you could technically add to darktablerc something like

```
opencl_building_gpu0=
```
which would clear all optimization flags (or you could specify your own, although you'd have to know which ones to use :) ) and see how it behaves.

> Why is opencl support canceled completely just because of one missing kernel? All other kernels built successful. If I remove the diffuse things opencl is working again.

this is a complex question. On one hand it makes sense to enable only buildable kernels so that those that got built get used and still claim opencl support. On the other hand one unbuildable kernel can mean a whole loads of problems are about and it's best to ignore opencl support wholesale. I mean if you got blown tire in the car you don't go "3 tires are perfectly fine" you can't drive anyway :P. It might be worth discussing as an advanced option but it may create compilation/dependency hell for slight benefit of being able to use couple compilled kernels.

**Comment by semperit89** [comment]
> The error looks as if it was 100% compiller fault and that it generates incorrect code.
> If you're using master you could technically add to darktablerc something like
> 
> ```
> opencl_building_gpu0=
> ```

Tried it, but didn´t work, the same failure appears.

> this is a complex question. On one hand it makes sense to enable only buildable kernels so that those that got built get used and still claim opencl support. On the other hand one unbuildable kernel can mean a whole loads of problems are about and it's best to ignore opencl support wholesale. I mean if you got blown tire in the car you don't go "3 tires are perfectly fine" you can't drive anyway :P. It might be worth discussing as an advanced option but it may create compilation/dependency hell for slight benefit of being able to use couple compilled kernels.

Okay, that´s understandable. At least as a workaround I will just delete the diffusion kernel stuff, since all other things are working.

**Comment by semperit89** [comment]
Is there any chance to get a better log, to get an idea where the build fails?

**Comment by johnny-bit** [comment]
you might want to try adding `-cl-nv-verbose` to `opencl_building_gpu0` options

**Comment by semperit89** [comment]
I tried the option, but there was no other log created. So I tried to find the lines which cause the failure by commenting parts of the code out. 

The kernel builds succesfull, when I comment this line out (in kernel void diffuse_pde):
>    write_imagef(output, (int2)(x, y), out);

**Comment by semperit89** [comment]
I guess the only one, who could help here is @aurelienpierre. 
Still, it seems to be just me having this problem.

**Comment by semperit89** [comment]
Again I had some time and tried to understand the failure. I was not successful, but I have another question. In Line 224 of diffuse.cl there is a variable sampleri:

`const char opacity = (has_mask) ? read_imageui(mask, sampleri, (int2)(x, y)).x : 1;`

Shouldn‘t it be samplerA, that’s the only defined variable with „sampler“, which I could find in the code.

**Comment by semperit89** [comment]
Used `export CL_LOG_ERRORS="stdout"` and the debug log shows more information:
```
[CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: Build Program driver returned (10007)
Break on OpenCLErrorBreak to debug.
OpenCL Warning : clBuildProgram failed: could not build program for 0x1022700 (GeForce GT 755M) (err:-2)
Break on OpenCLWarningBreak to debug.
[CL_BUILD_ERROR] : OpenCL Build Error : Compiler build log:
ptxas application ptx input, line 363; error   : Argument 1 of instruction 'add': must be register
ptxas fatal   : Ptx assembly aborted due to errors

Break on OpenCLErrorBreak to debug.
0.531545 [opencl_build_program] could not build program: -11
0.531561 [opencl_build_program] BUILD STATUS: -2
0.531563 BUILD LOG:
0.531564 ptxas application ptx input, line 363; error   : Argument 1 of instruction 'add': must be register
ptxas fatal   : Ptx assembly aborted due to errors
0.531567 [opencl_init] failed to compile program `diffuse.cl'!
0.531589 [opencl_init] no suitable devices found.
```
I guess this line shows, that there are problems with my nvidia card:
[CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: Build Program driver returned (10007)
