### ISSUE TITLE
darktable crash importing Leica dng file.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#9573]
**Describe the bug/issue**
I was trying to import a Leica DNG file and darktable crash.

**To Reproduce**
1. Go to import module 'add to library'
2. Select the folder with the .dng files (the image preview does not visualize anything) Click on 'add to library'
3. darktable close.

**Expected behavior**
Import the dng file

**Platform**
OS: Fedora 34 (Workstation Edition) x86_64 
Host: Z390 AORUS MASTER 
Kernel: 5.12.15-300.fc34.x86_64 
Uptime: 1 hour, 16 mins 
Packages: 2619 (rpm), 8 (flatpak), 13 (snap) 
Shell: zsh 5.8 
Resolution: 3840x2160 
DE: GNOME 40.3 
WM: Mutter 
WM Theme: Materia-dark-compact 
Theme: Mojave-dark [GTK2/3] 
Icons: Os-Catalina-icons-master [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-9700K (8) @ 4.900GHz 
GPU: NVIDIA GeForce GTX 1070 
GPU: NVIDIA GeForce GTX 1080 Ti 
Memory: 3281MiB / 32037MiB 

darktable 3.7.0~git394.f5b1912af5-6284.1
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0-dev
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by difrkaguilar** [comment]
If the .dng file is needed, I can send it to test.

**Comment by jenshannoschwalm** [comment]
Please share a suspect raw file and xmp, also using leica dng's and never had an issue for years.

**Comment by tduell** [comment]
It might be worth checking if this issue still occurs using a build of the current master, as the issue sounds very much like the one that was causing dt to exit when selecting add to library.
You could check with your current version by starting dt from a console/terminal, and seeing if a message similar to '/home/***/0 not found'

Cheers,
Terry

**Comment by difrkaguilar** [comment]
Yesss, I just realized the problem is with the import, every file I trying to add to library I got the same message:

'/home/***/0 not found'
So, it isn't the dng format.

**Comment by difrkaguilar** [comment]
Solved with the last update.
3.7.0~git426.58263ac077-6295-3

Thanks a lot.
