### ISSUE TITLE
Crop & Crop and rotate bug

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [darktable-org/darktable#9576]
In Darktable 3.6 on Xubuntu 20.04, both crop tools often "lock up" and allow cropping in only one direction ( e.g. only horizontally ) or in no direction at all. Resetting the module sometimes helps, but it's not reliable. It seems to happen on images that have around 50 edits on the history stack or more.

**Comment by elstoc** [comment]
crop limitations are usually initiated by holding down shift or ctrl while cropping. I assume you're definitely not holding either of these keys.

**Comment by elstoc** [comment]
Sorry I misremembered - ctrl and shift are for constraining movement, not cropping (shift can be used to retain the aspect ratio when cropping). Either way I can't reproduce your issue.

**Comment by Pizzacutter-at-tty3** [comment]
> Sorry I misremembered - ctrl and shift are for constraining movement, not cropping (shift can be used to retain the aspect ratio when cropping). Either way I can't reproduce your issue.

That's fine, I pretty much got what you meant there. As I said it happens to me when there are enough edits done to the image. But then I've got relatively low end setup for editing images, so you could try images where changes take long to apply.
