### ISSUE TITLE
Crash when renaming a shape in mask manager

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#9580]
DT current master (but same in 3.6), Windows 10, OpenCL active

To reproduce:
1) start with a fresh edit
2) create a drawn mask in a module, for example a path in exposure
3) go to the mask manager
4) double click on the name of the shape to rename it 
5) now click outside the entry box (it doesn't matter if you actually renamed the shape or not)
6) see the crash

Here is the backtrace created in debug mode
[darktable_bt_DY8M60.txt](https://github.com/darktable-org/darktable/files/6851044/darktable_bt_DY8M60.txt)

**Comment by TurboGit** [comment]
Duplicate of #9504.
