### ISSUE TITLE
Exporting and editing images end up in a black rectangle

### ISSUE THREAD

**Issue by LuisGAbarca-DT** [darktable-org/darktable#9582]
**Introduction**
When editing an image and/or exporting it the final exported image is a black file, either tiff or jpg.

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Updated from version 3.4 to 3.6
2. Edited one file, export it and a black file was the result
3. Not all files behave the same way

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.6.0
* OS                : Windows 10

* Memory            :  RAM 8 GB
* Graphics card     : AMD RADEON
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **NO**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/ NEF
![DSC_1580](https://user-images.githubusercontent.com/87626332/126428059-41e195ea-d24b-4860-b1ca-f798676b44fd.jpg)
[DSC_1580.NEF.txt](https://github.com/darktable-org/darktable/files/6852709/DSC_1580.NEF.txt)
**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **YES**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **YES**
 - Do you use lua scripts? NO
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Nilvus** [comment]
When posting an issue, please be as clear as possible (in that case, modules activated and options ; the best way here is to provide a link to download an affected RAW and the related XMP (that contains all your processing) and remove all unuseful lines and comment.
Thus, we already have some reports about that one. Mainly due to clip negative rgb from gamut unticked in color calibration module or some bad settings in denoise profile. Please just search in issue before posting (here with simple words like "black" and "export" , see https://github.com/darktable-org/darktable/issues?q=is%3Aissue+is%3Aopen+black+export).

I close so as this is a duplicate.

**Comment by Nilvus** [comment]
Oh, a last thing, don't forget to especially check closed issues in link I posted above.
