### ISSUE TITLE
noiseprofile for Leica D-Lux 7

### ISSUE THREAD

**Issue by mabod** [darktable-org/darktable#9584]
I have created a noiseprofile for the Leica D-Lux 7. Please include it in one of the next darktable releases.

https://www.dropbox.com/s/9w4ozwoa81jvrk3/darktable-noiseprofile-20210721.tar.gz?dl=0

**Comment by mabod** [comment]
I figured that the `presets.json` in the `darktable-noiseprofile-20210721.tar.gz` file contains multiple presets per ISO because I used multiple images per ISO. That is obviously not needed. Here are the revised presets where I just kept only the first entry for each ISO.

```
{
          "comment": "d-lux 7 contributed by matthias bodenbinder",
          "model": "D-Lux 7",
          "profiles": [
            {"name": "D-Lux 7 iso 200", "iso": 200, "a": [7.47516436202308e-06, 2.46844158346893e-06, 5.1809675677528e-06], "b": [1.42426316256908e-08, 7.85774943584172e-09, 1.49797885332244e-08]},
            {"name": "D-Lux 7 iso 250", "iso": 250, "a": [9.32850481015955e-06, 3.15980146136451e-06, 6.44457542290316e-06], "b": [2.10059583583206e-08, 8.39050869060353e-09, 2.17961504262073e-08]},
            {"name": "D-Lux 7 iso 320", "iso": 320, "a": [1.16785390999106e-05, 3.99206675418461e-06, 8.15622744655642e-06], "b": [3.24791063354137e-08, 1.23691263128359e-08, 2.38537247321193e-08]},
            {"name": "D-Lux 7 iso 400", "iso": 400, "a": [1.46074263568207e-05, 4.82599837304978e-06, 1.02072065013246e-05], "b": [3.08742512218869e-08, 1.74781083661327e-08, 3.37579796395815e-08]},
            {"name": "D-Lux 7 iso 500", "iso": 500, "a": [1.8343404496349e-05, 6.31207193834511e-06, 1.30605405339826e-05], "b": [6.05776182038155e-08, 1.90833136681345e-08, 4.03588954808103e-08]},
            {"name": "D-Lux 7 iso 640", "iso": 640, "a": [2.30582308613517e-05, 7.71745737030144e-06, 1.59081237449005e-05], "b": [6.94700293642542e-08, 3.13769181836197e-08, 5.84034613217873e-08]},
            {"name": "D-Lux 7 iso 800", "iso": 800, "a": [2.87076876685881e-05, 9.75403238462522e-06, 2.02711865697991e-05], "b": [9.27035767871649e-08, 3.04528811924759e-08, 5.85570432014817e-08]},
            {"name": "D-Lux 7 iso 1000", "iso": 1000, "a": [3.59125226311817e-05, 1.21451911548231e-05, 2.50080352448648e-05], "b": [8.8363808228198e-08, 4.30121215547763e-08, 9.25087878706063e-08]},
            {"name": "D-Lux 7 iso 1250", "iso": 1250, "a": [4.52774965368715e-05, 1.51100949333751e-05, 3.14811536226338e-05], "b": [1.28568722374818e-07, 6.50704380383652e-08, 1.08320799150238e-07]},
            {"name": "D-Lux 7 iso 1600", "iso": 1600, "a": [5.66935183440472e-05, 1.91534593194069e-05, 3.99447413478979e-05], "b": [1.8331060328747e-07, 7.93452648376039e-08, 1.39163479907587e-07]},
            {"name": "D-Lux 7 iso 2000", "iso": 2000, "a": [7.16429205278605e-05, 2.38068607862341e-05, 4.93084757397271e-05], "b": [1.77254313446102e-07, 1.07775297458744e-07, 1.88286039359388e-07]},
            {"name": "D-Lux 7 iso 2500", "iso": 2500, "a": [8.96358008362269e-05, 2.99008737429642e-05, 6.28245830621012e-05], "b": [2.58204464086174e-07, 1.55739519185636e-07, 2.46228803288064e-07]},
            {"name": "D-Lux 7 iso 3200", "iso": 3200, "a": [0.00011392317788068, 3.84404017480665e-05, 7.98345675644352e-05], "b": [4.45055526949849e-07, 2.20727509548738e-07, 4.06186881029347e-07]},
            {"name": "D-Lux 7 iso 4000", "iso": 4000, "a": [0.000143709387802207, 4.79624945858196e-05, 9.89427655680384e-05], "b": [4.87475913124482e-07, 2.96619131233199e-07, 5.15772151127226e-07]},
            {"name": "D-Lux 7 iso 5000", "iso": 5000, "a": [0.00018089384410813, 5.95980760283586e-05, 0.000125559367976104], "b": [5.10664537994349e-07, 3.93999328385326e-07, 5.7372939649651e-07]},
            {"name": "D-Lux 7 iso 6400", "iso": 6400, "a": [0.000225831183408179, 7.45536170945211e-05, 0.000157209103689251], "b": [6.99474327302804e-07, 5.5731462820492e-07, 8.07360918835466e-07]},
            {"name": "D-Lux 7 iso 8000", "iso": 8000, "a": [0.000284169087708228, 9.35599680814793e-05, 0.000197705268762258], "b": [1.06118168906003e-06, 8.58104641959915e-07, 1.23655278044128e-06]},
            {"name": "D-Lux 7 iso 10000", "iso": 10000, "a": [0.00036243475124656, 0.000118653768298497, 0.000245138702803466], "b": [2.18094201528324e-06, 1.51197754569152e-06, 2.53047479139305e-06]},
            {"name": "D-Lux 7 iso 12500", "iso": 12500, "a": [0.000449640776725114, 0.000148446440408457, 0.000311886091782767], "b": [2.37996955034241e-06, 2.00015896812575e-06, 2.88449986496872e-06]},
            {"name": "D-Lux 7 iso 16000", "iso": 16000, "a": [0.000283067530749418, 9.35090443171114e-05, 0.00019806078346406], "b": [1.05913275268099e-06, 8.56211171321623e-07, 1.24206348899041e-06]},
            {"name": "D-Lux 7 iso 20000", "iso": 20000, "a": [0.000357916782226216, 0.000118289345484384, 0.000249054892994411], "b": [1.59063650580094e-06, 1.29866798859529e-06, 1.8919995222713e-06]},
            {"name": "D-Lux 7 iso 25000", "iso": 25000, "a": [0.000447900876269519, 0.000148891527550444, 0.000312481699207148], "b": [2.39306717704209e-06, 1.97777706381915e-06, 2.90082699795567e-06]}
          ]
        }
```

**Comment by kmilos** [comment]
What about just copying the profile from DC-LX100M2 instead if sensor is the same (as was done for adobe_coeffs) for more consistent results?

Curiously the ISO list is somewhat different...

**Comment by mabod** [comment]
I gave it a try and compared my Leica profile with the Panasonic profile. The Panasonic settings look good to me. In fact, the Panasonic settings are even more tough on the noise. 

OFF TOPIC:
What about copying lens correction as well? I am struggling with doing that. Asked for help on pixls.us: 
https://discuss.pixls.us/t/lens-correction-for-leica-d-lux-7/26002/2

Any help is appreciated.

**Comment by jenshannoschwalm** [comment]
Lens correction taking the pana 100LXII data should be ok as the lens is the same. coeffs are also safevto be used as has been merged.

About the profiled denoise, likely ok and better than nothing but there could be differences here depending on how the signal are amplified depending on ISO setting so it would probably best to generate a new set of data for this. You will find a HOWTO at pixls ...

**Comment by mabod** [comment]
> You will find a HOWTO at pixls ...

HOWTO for waht? Creating a noise profile? I did that.

But I can not figure out how to copy the Panasonic lens correction and make it work for the Leica automatically. Please see: https://discuss.pixls.us/t/lens-correction-for-leica-d-lux-7/26002/2

I know this is off topic. shall I create a new issue for this?

**Comment by kmilos** [comment]
> About the profiled denoise, likely ok and better than nothing but there could be differences here depending on how the signal are amplified depending on ISO setting so it would probably best to generate a new set of data for this.

Why would this be the case given all the specs and evidence that there are, in fact, identical cameras?

**Comment by jenshannoschwalm** [comment]
> HOWTO for waht? Creating a noise profile? I did that.

You are absolutely right! I missed that while reading on my cellphone, sorry about this!

> I have also converted the RWL and RW2 from RPU with DNG converter, and the results have identical color matrices and noise profiles

I didn't know that ...

**Comment by mabod** [comment]
So what will happen now? Two options here: Take the noiseprofiles I have provided or copy&paste the noiesprofile from Panasonic dc-lx100m2 contributed by ddyakov. This also seems good to me.

**Comment by rawfiner** [comment]
Sorry for the long wait, I'll integrate your noise profile (which looks good, thanks!) in a PR
