### ISSUE TITLE
Copy paste history stack not copying all module changes

### ISSUE THREAD

**Issue by aeroflux** [darktable-org/darktable#9585]
Hello everyone,

I am currently batch processing a bunch of RAW files in darktable 3.6. After adjusting the pictures, I proceed to copy and paste the history stack from one edited file to all in the collection. What I have noticed though is that lens correction enabling and white balance temperature change aren't copied over. Is this by design?

**Comment by johnny-bit** [comment]
> What I have noticed though is that lens correction enabling and white balance temperature change aren't copied over. Is this by design?

yes:

https://www.darktable.org/2020/12/darktable-3-4/

> By default the copy button now exclude some modules that can cause issues when pasted between images. You can still include these modules by using the “copy parts” button

https://www.darktable.org/2020/12/darktable-340-released/

> The history copy has been changed to include only safe modules. Modules like “raw white/black point” and “scale pixels” are no longer copied, for example. To copy such modules, use the “copy parts…” button. Note that the unsafe modules are not selected by default in the resulting dialog.

If you have concerns about that, please see https://github.com/darktable-org/darktable/issues/6586
