### ISSUE TITLE
quick zoom in culling mode

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#9587]
A feature I would really like to see in DT is a quick way to zoom 100% while in culling mode.
For example by long click, or right click, zooming 100% centered on the mouse position.
It could be either reset by releasing the mouse button or clicking again
I believe this would speed up the culling workflow, as zooming with CTRL+scroll is pretty slow.

**Comment by wpferguson** [comment]
Middle click

**Comment by Mark-64** [comment]
@wpferguson Thank you, happy to see it there already.
It this documented in the manual, I couldn't find it.
Closing
