### ISSUE TITLE
Artifacts in highlight reconstruction module

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#9592]
A `highlight reconstruction module` created artifacts (vertical and horizontal stripes) in `reconstruct color` mode.

**To Reproduce**
1. Enable highlight reconstruction in reconstruct color mode
2. View reconstructed area in 100%
3. See the stripes

**Screenshots**
![snap0034](https://user-images.githubusercontent.com/2641120/126647485-7b2efc0d-48a7-4620-a36a-d210fb4e317a.jpg)

**Platform**
* darktable version : 3.6.0
* OS                : Linux - kernel 5.11.0-pf8
* Linux - Distro    : Gentoo
* Memory            : 
* Graphics card     :  [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev cf)
* Graphics driver   :  amdgpu
* OpenCL installed  : yes
* OpenCL activated  : does not matter -- artifacts are there in both cases
* Xorg              :  1.20.11-r2
* Desktop           : Compiz
* GTK+              :  2.24.33 3.24.29
* gcc               : 11.1.0-r1
* cflags            :  "-march=native -O3 -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -msse3"

**Comment by jenshannoschwalm** [comment]
I think this is a duplicate of #3022 , it's a problem of the algorithm. Some people think this is currently darktables weakest point :-(

**Comment by kanyck** [comment]
Probably yes. I haven't dug this far while searching for dupes...

**Comment by johnny-bit** [comment]
I'm almost 100% certain it's duplicate of #3022.

@kanyck if you agree it's dup - plz close this one and add your details to 3022 so it wont get closed.

**Comment by kanyck** [comment]
Closed in favor of #3022.
