### ISSUE TITLE
Exported exif data changed/broken since 3.6

### ISSUE THREAD

**Issue by timsn** [darktable-org/darktable#9594]
**Describe the bug/issue**

It seems that with 3.6 something with the exported exif data has changed. I notice it with using the hugo static site generator (https://gohugo.io). Hugo has the ability to read exif data from images (https://gohugo.io/content-management/image-processing/#exif) such as the date.

Everything worked fine with all the images I have exported with Darktable in the past. But since version 3.6 the images I export can't be used with hugo. It simply stops reading the image exif data with this error:

    exif: decode failed (zero length tag value)

I know that exif data is acually somehow present in the images exported with 3.6 as I can read them without any problems using `ExifTool` for example. But something has changed with DT 3.6 and I'm not sure if it's a problem with darktable or with the used go exif library. But I know it wasn't a problem before 3.6.

**To Reproduce**

You can reproduce the behaviour by running the goexif library used by hugo with the minimal example from the README: https://github.com/rwcarlsen/goexif/
You just have to add a main function and replace the image filename.
Run it once with an image exported by Darktable 3.4 and then with an image exported by Darktable 3.6.

**Platform**

* darktable version : 3.6.0
* Linux - Distro    : Fedora 34

**Comment by phweyland** [comment]
dt uses exiv2 to import/export metadata. So a criteria to check if that's a dt issue or not is to verify the exported data with exiv2.

**Comment by timsn** [comment]
I've found the issue. It is caused by an empty exif value for the "ImageDescription".

```
$ exiv2 -pa exported_with_darktable_3.6.jpg
[...]
Exif.Image.ImageDescription                  Ascii       0  
[...]
```
I have no custom exif settings in the export module. The only thing I've set is the checkbox for "exif data" nothing else. Can someone confirm that behaviour?

**Comment by parafin** [comment]
I guess instead of zero-byte value it should be an empty string (one NUL byte)...

**Comment by phweyland** [comment]
Pinging @kmilos.
I think this behaviour is introduced with 577a6620950c7cddc327e389cb1773edc1190e81.
Could check this please ?

**Comment by kmilos** [comment]
Which exiv2 version is used in this build?

[We fixed this (empty strings should still write the null byte and have count of 1) in 0.27.4](https://github.com/Exiv2/exiv2/issues/1484).

**Comment by timsn** [comment]
How can I find that out? In my case it's the packaged version from the official fedora repository.

```
$ dnf info darktable
Last metadata expiration check: 0:00:05 ago on Mon 26 Jul 2021 02:57:15 PM CEST.
Installed Packages
Name         : darktable
Version      : 3.6.0
Release      : 2.fc34
Architecture : x86_64
Size         : 25 M
Source       : darktable-3.6.0-2.fc34.src.rpm
Repository   : @System
From repo    : updates
Summary      : Utility to organize and develop raw images
URL          : http://www.darktable.org/
License      : GPLv3+
Description  : Darktable is a virtual light-table and darkroom for photographers:
             : it manages your digital negatives in a database and lets you view them
             : through a zoom-able light-table.
             : It also enables you to develop raw images and enhance them.

$ darktable --version
this is darktable 3.6.0
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Comment by ptilopteri** [comment]
how about
 dnf info exiv
or
 dnf info exiv2

**Comment by timsn** [comment]
Ok, I thought this is somehow built into Darktable.

```
$ dnf info exiv2
Last metadata expiration check: 1:37:00 ago on Mon 26 Jul 2021 02:57:15 PM CEST.
Installed Packages
Name         : exiv2
Version      : 0.27.3
Release      : 7.fc34
Architecture : x86_64
Size         : 4.4 M
Source       : exiv2-0.27.3-7.fc34.src.rpm
Repository   : @System
From repo    : updates
Summary      : Exif and Iptc metadata manipulation library
URL          : http://www.exiv2.org/
License      : GPLv2+
Description  : A command line utility to access image metadata, allowing one to:
             : * print the Exif metadata of Jpeg images as summary info, interpreted values,
             :   or the plain data for each tag
             : * print the Iptc metadata of Jpeg images
             : * print the Jpeg comment of Jpeg images
             : * set, add and delete Exif and Iptc metadata of Jpeg images
             : * adjust the Exif timestamp (that's how it all started...)
             : * rename Exif image files according to the Exif timestamp
             : * extract, insert and delete Exif metadata (including thumbnails),
             :   Iptc metadata and Jpeg comments
```
So I assume that this would be fixed as soon as exiv2 is updated on my system. Is that correct?

**Comment by kmilos** [comment]
Yes, but who knows when/if that happens. In the meantime, you could just try force installing the exiv2 0.27.4 RPM from Rawhide...

**Comment by phweyland** [comment]
What about having some conditional code for those who have not the last exiv2 version ?
That's the common way to introduce new features without breaking the old code.
