### ISSUE TITLE
Parametric mask in Surface Blur generates unhandled exception

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#9595]
**Describe the bug/issue**
When I try to add a parametric mask to surface blur, dt gets an unhandled exception. I haven't noticed any other module where parametric or drawn & parametric mask doesn't work.

**To Reproduce**
1. Open an image
2. Add _surface blur_
3. Select _parametric mask_
4. See exception

**Which commit introduced the error**
Don't know

**Platform**
darktable version : 3.7.0+442~g7f1303a53
OS : Win10 Enterprise 19042.1110
Memory : 32GB
Graphics card : NVIDIA Geforce 940MX
Graphics driver : 466.77
OpenCL installed : yes
OpenCL activated : no
Xorg : n/a
Desktop : n/a
GTK+ : n/a
gcc : (Rev10, Built by MSYS2 project) 10.2.0
cflags : ?
CMAKE_BUILD_TYPE : Release

**Additional context**
 - cannot reproduce on virtual Ubuntu 21.04 (sate dt version, no OpenCL)
 - cannot reproduce with OpenCL activated
 - [darktable_bt_OFMK60.txt](https://github.com/darktable-org/darktable/files/6864309/darktable_bt_OFMK60.txt)

**Comment by Mark-64** [comment]
Can't reproduce in 3.6, Windows 10

**Comment by juhavlintula** [comment]
I cannot reproduce the issue any more after I have rebooted my laptop.
