### ISSUE TITLE
NG Input: issue with compress history shortcut (maybe others) in darkroom view

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#9597]
**Describe the bug/issue**

It's hard to compress history with shortcut in darkroom view (works great in lighttable one).

**To Reproduce**

1. First set (or be sure) 'c' shortcut to compress history button with the new NG input framework
2. Press 'c' to compress history in darkroom view.
3. See the CSS hover effect applied in compress history (so shortcut is working) but history is not compressed.

Few quick press of 'c' shortcut make compress history works sometimes (hard to do and reproduce).

See that when you do same operation in lighttable view, history is compress as it should when applying 'c' shortcut.

I tested that with left panel visible and hidden, same issue.

**Expected behavior**

'c' shortcut to apply each time and on first press compress history applied. I don't see other shortcut but I don't really use others in darkroom view by now. But maybe it's not only this button but some issue in darkroom view for applying correctly shortcuts in buttons.

**Platform**

* darktable version : 3.7.0+455~g4eead2b23
* OS                : Ubuntu 21.04

**Comment by elstoc** [comment]
Yep I reproduce this too

**Comment by ralfbrown** [comment]
Likewise.  I noticed this on Wednesday, but hadn't gotten around to reporting it yet.
