### ISSUE TITLE
NG Input: search field missing in new shortcut preferences view

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#9598]
**Is your feature request related to a problem? Please describe.**

Previous system were having a search feature to quickly find a shortcut or action. 

**Describe the solution you'd like**

Even if the new system allow to find it by clicking on the button/widget to find line in shortcuts preferences, it could be good to have also the search feature come back in shortcut preferences view.

**Comment by elstoc** [comment]
It looks like some commit has broken the search feature in the bottom panel of the window. It does exist but it's not very discoverable (you just have to start typing then use arrow keys to navigate between matches). I've used it before but for some reason it now only works in the top panel.

**Comment by elstoc** [comment]
There's also a draft PR to add actual widgets for the search but it looks like @dterrahe has had trouble getting it to work properly (https://github.com/darktable-org/darktable/pull/9382)

**Comment by Nilvus** [comment]
> There's also a draft PR to add actual widgets for the search but it looks like @dterrahe has had trouble getting it to work properly (#9382)

Thanks. I've missed that PR
