### ISSUE TITLE
Darktable Crashed when renaming mask

### ISSUE THREAD

**Issue by OK-One** [darktable-org/darktable#9599]
**Describe the bug/issue**

When I attempted to change the name of a mask, (using feature at bottom left of window), in the darkroom view, darktable crashed. with an error report which is attached

[darktable_bt_MORK60.txt](https://github.com/darktable-org/darktable/files/6865945/darktable_bt_MORK60.txt)

**To Reproduce**

1. Attempt to change the name of a mask. It is definitely a bug, cos its repeatable, and occurs every single time I attempt to rename a mask.

**Expected behavior**

I expected the name of the mask to change. 1st time I ever tried to use this feature in any version of darktable.

**Screenshots**
Not applicable cos I lost all the most recent changes to the image. A bit painful, cos I has spent quite a bit of time editing the image

!!

**Platform**
Windows 10.
Darktable 3.6.0.1
Memory        8GB RAM
* Graphics card     :  Adapter Description	AMD Radeon HD 8850M + INtegrated GPU in INtel CPU - Processor	Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz, 2301 Mhz, 2 Core(s), 4 Logical Processor(s)

**Comment by Nilvus** [comment]
#9504 duplicate. Please check if an issue exist before.
