### ISSUE TITLE
css styling for the timeline module in lightable

### ISSUE THREAD

**Issue by eyedear** [darktable-org/darktable#9600]
**Is your feature request related to a problem? Please describe.**
I have tried all the themes that is provided in darktable. In my situation I find the contrast of the UI to be too low  which is very fatiguing to the eyes after a very long session. 

I have tried to modify the css to change the contrast of the UI. Generally I have manage to get the UI to become more contrasty. the one area I am unable to change is the timeline. 

i have search and it seem that currently the timeline UI CSS is not modifiable.

i have attached a screenshot to show the low contrast of the timeline module below
![image](https://user-images.githubusercontent.com/7136598/126728161-edd9b2ce-4e23-41aa-bf39-937e9a925eb5.png)

**Describe the solution you'd like**
would the devs consider providing a way to use CSS to style the timeline module. that would be much appreciated  

thanks

**Comment by Nilvus** [comment]
For others devs: it's following this pixl.us discussion: https://discuss.pixls.us/t/css-styling-the-timeline-in-darktable/25987/4

**Comment by eyedear** [comment]
just an update. i was tinkering with the css and i found that the following would allow the shading of the timeline. not ideal but workable

@define-color thumbnail_hover_bg_color @grey_20;

I change it grey_20 but when you hover over the thumbnail it will become grey_20 too
below is a grey them version 
![image](https://user-images.githubusercontent.com/7136598/126765580-6561e044-de6a-4ff7-a7ed-ef2f028a5e42.png)

and this one is the dark theme version
![image](https://user-images.githubusercontent.com/7136598/126765672-a08edeb5-1c85-422d-a8bc-791eb7ccc399.png)
 for the dark theme version I had to set it to @grey_30 any thing less than that the shading would be too low contrast or disappear

**Comment by Nilvus** [comment]
> @define-color thumbnail_hover_bg_color @grey_20;
> 
> I change it grey_20 but when you hover over the thumbnail it will become grey_20 too

That's because this timeline part use thumbnail hover background setting. So if you change that, you break thumbnail hover background. Could be a workaround for you but of course not a solution for darktable code. This would need a Gtk change to separate timeline to thumbnail settings and allow more CSS tuning. Something maybe for @AlicVB when he will have time as he works on those parts.

**Comment by Nilvus** [comment]
@eyedear: changes are coming for timeline. See #9854. If you know how to build from source, you could test this pull request.
