### ISSUE TITLE
Duplicate manager issue

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#9601]
Hi devs,
The duplicate manager is 3.7.x does not appear to be playing by the rules.
I've created a short video explaining the situation:
https://youtu.be/lGSwIM-MIPI
If I've simply misinterpreted something, feel free to close the issue.
Cheers.

**Comment by MStraeten** [comment]
have a look at 0:26: it seems there's already an xmp file (e.g. lightroom) available from which settings are imported.

**Comment by brucewilliamsphotography** [comment]
Sorry? I don't understand what you're looking at.
I clicked on ORIGINAL, which SHOULD have created a new xmp file with no processing included. You can see from the number 4 (alongside the duplicate) that this was my 3rd attempt at this.
What am I missing?

**Comment by MStraeten** [comment]
this beaviour looks like described here: https://www.darktable.org/usermanual/3.6/en/overview/sidecar-files/sidecar-import/

**Comment by brucewilliamsphotography** [comment]
Ok, so even if the original rendition was performed in Adobe Lightroom, hitting "original" for a new xml file won't actually create a clean start? Is that what you're saying?

**Comment by TurboGit** [comment]
Yes, LR xmp will ever been imported when found next to the image. This is automatic, we don't want to give more from the GUI. If Lr XMP is not wanted anymore better remove it or rename it. This is really a corner case. For image only edited in dt it works properly.
