### ISSUE TITLE
Allow hinter message (and module order?) to be repositioned

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9612]
I don't really like to expose the top bar (in which the hinter message is contained) because it takes up useful vertical real-estate, but I do sometimes like to be able to see the hinter messages (usually because I forget which shortcuts change opacity/size/hardness of masks).

It would be great if we could, with a preference, relocate the hinter messages to the bottom of the left or right panels. I've tried this out and personally, I prefer it in the bottom of the left-hand panel and for the module order module to be relocated to the right-hand panel. 

Allowing both of these to be repositioned with a preference (even a hidden one in darktablerc) would really be great.

**Comment by eyedear** [comment]
I agree with @elstoc. Maybe the hinter message can be shown on the filter/preference bar since the center of that area is not use.

**Comment by elstoc** [comment]
I'm not sure that will work. The hinter message can go to multiple lines and putting it on the filter/preference bar will require more vertical space, or for the hints to be limited to one line. I usually also hide this bar in the darkroom (I use keyboard shortcuts to access those buttons).

**Comment by eyedear** [comment]
noted. you are right

**Comment by dterrahe** [comment]
This information is also available in the "h" screen. Could that be improved to better serve your needs?
