### ISSUE TITLE
Presets of the metadata editor are not applied immediately

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9614]
**Describe the bug/issue**
If I select a preset from the Metadata editor module, the display is not updated immediately.

**To Reproduce**
1. Create a preset "test" and a preset "foo".
2. Select Preset "test" from the list of presets
![image](https://user-images.githubusercontent.com/2805109/126867917-5e5db1bd-7289-4714-9922-5ca365ef7500.png)
The display is not updated:
![image](https://user-images.githubusercontent.com/2805109/126867945-a2a1cc1f-e233-443a-927a-fb94ef0113bb.png)

Now, click on "delete this preset" and then cancel -> View will be updated
![image](https://user-images.githubusercontent.com/2805109/126867984-250deccd-ec1e-47d3-8d8a-d504c44978eb.png)

**Expected behavior**
View should update immediately.

**Platform**

* darktable version : list+305~gc1925dcc6
* OS                : Manjaro Linux

**Comment by phweyland** [comment]
I can reproduce this on master.

**Comment by phweyland** [comment]
Regression from c262ce222680097ee9dac3b66e379fcafb9c6dd2. 
Trying to find a fix without revert it.
