### ISSUE TITLE
FR: Lower Contrast Preset Menu Checkboxes

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#9624]
I find the checkboxes that now appear in the preset menu to be a little too high contrast for my taste. The boxes currently have the same colour as those on the body of the modules but against a darker background.

Current:

![Screenshot_2021-07-25_00-09-41](https://user-images.githubusercontent.com/9555491/126883023-b01dae8b-815a-4afc-9d7c-099363bd4f0d.png)

With `@plugin_bg_color;`:

![Screenshot_2021-07-25_00-10-09](https://user-images.githubusercontent.com/9555491/126883036-074d5ffb-d2ec-4111-bac7-5f2b700b60ed.png)

Given that the only intention here is to highlight the selected option (with a tick) my preference would be to make the checkbox entirely blend into the background:

![Screenshot_2021-07-25_00-13-18](https://user-images.githubusercontent.com/9555491/126883073-73e06bf2-d804-40dc-943a-9427cc916310.png)

**Comment by Nilvus** [comment]
I like your ideas and I agree that contrast is higher. And I'm completely on for @plugin_bg_color.

About hiding background, even if I like it, I'm not for that option. I fear that some users will be lost by not seeing check boxes. More, that make a sort of large empty margin on the left when nothing is checked. Thus, I think we need to find something that is consistent in all checkbox list like in treeview. No background in treeview is worse (see copy/paste dialog window).

I've made some tests and I think this CSS code seems a good compromise (tested on all themes ; I've also change border color to make the change good in all themes and in treeview and menuitem):

```
treeview check, /* set specific background color about check buttons like in copy/paste dialog window */
menuitem check
{
  background-color: @plugin_bg_color;
  border-color: @border_color;
}
```

Hope you will like it. If it's ok, I will post a PR to fix your FR.

**Comment by elstoc** [comment]
> I fear that some users will be lost by not seeing check boxes.

Really? There's no reason the user has to know or care that these are check boxes - the tick is the important element. My preference is still for no box but I do take your point about the margin.

**Comment by MStraeten** [comment]
`I fear that some users will be lost by not seeing check boxes. `
Usually checkboxes are used if there several checks can be set. So i doubt someone expects a checkbox in a preset selection dialog

**Comment by Nilvus** [comment]
I hope I'm wrong about potential users complaints (we've seen such ones...).

I so propose PR #9628 that should fix this FR.

-
