### ISSUE TITLE
Darktable crashes when importing tiff scans windows 10

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#9625]
I am doing scans with an Epson Perfection 850 scanner and saving files to a folder. I then ask DT to add those images to the library and an unhandled exception occurs causing DT to crash. The images are actually added to the library when I restart DT. This has happened numerous times. Here are some of the backtrace files. 
[darktable_bt_COR660.txt](https://github.com/darktable-org/darktable/files/6873282/darktable_bt_COR660.txt)
[darktable_bt_4CIK60.txt](https://github.com/darktable-org/darktable/files/6873283/darktable_bt_4CIK60.txt)
[darktable_bt_LTWS60.txt](https://github.com/darktable-org/darktable/files/6873284/darktable_bt_LTWS60.txt)
[darktable_bt_416160.txt](https://github.com/darktable-org/darktable/files/6873285/darktable_bt_416160.txt)
[darktable_bt_WE9360.txt](https://github.com/darktable-org/darktable/files/6873286/darktable_bt_WE9360.txt)
[darktable_bt_LXRW60.txt](https://github.com/darktable-org/darktable/files/6873287/darktable_bt_LXRW60.txt)
[darktable_bt_IHSS60.txt](https://github.com/darktable-org/darktable/files/6873288/darktable_bt_IHSS60.txt)
[darktable_bt_VVEV60.txt](https://github.com/darktable-org/darktable/files/6873289/darktable_bt_VVEV60.txt)
[darktable_bt_V7K460.txt](https://github.com/darktable-org/darktable/files/6873290/darktable_bt_V7K460.txt)

**Comment by MStraeten** [comment]
please add an image that causes the crash to be able to reproduce the behaviour.

**Comment by tpinfold** [comment]
Hi Michael,
      next time it crashes I will send the image.

**Comment by tpinfold** [comment]
When I tried to add the tiff file it said this file type was not supported. Any advice how to upload?

**Comment by jenshannoschwalm** [comment]
put it into a zip archive

**Comment by tpinfold** [comment]
Have attempted to add a zip file. Lets see if it attaches.

**Comment by ralfbrown** [comment]
Something is going wrong on refreshing the display **after** the import has updated the database.
Too bad we don't get line number information in Windows backtraces, but this looks to have a similar cause as #9504 (not a duplicate) -- some GUI element or pointer is uninitialized at the time it is used.

**Comment by tpinfold** [comment]
Thanks for looking at this. I can confirm that the crash seems to occur when it is trying to refresh the display. This is consistent with the fact that when I reopen DT the images are displayed so the import went ahead. It is a minor issue in the grand scheme but hopefully this information helps you produce a more stable DT. I really appreciate the generous nature of the people who develop DT and and compile the various versions.

**Comment by jenshannoschwalm** [comment]
@tpinfold still i can't find the image file here ...

**Comment by johnny-bit** [comment]
understood: unclear.

@tpinfold  - please send sample files otherwise we can't check and therefore can't fix any issue you're experiencing.

**Comment by tpinfold** [comment]
OK next time it happens I will try and send the sample image that is causing crash. I understand that you can't resolve the problem if you can't reproduce it. It is more of an inconvenience that DT has to close and then be reopened to show the images have been imported. Thanks for taking an interest in this.


________________________________

**Comment by tpinfold** [comment]
Thanks for considering the problem I have been having with importing the TIFF files. I suspect it may be a resource issue on my computer and I can live with the issue.
