### ISSUE TITLE
feature to hide mandatory modules in basic mode

### ISSUE THREAD

**Issue by eyedear** [darktable-org/darktable#9635]
**Is your feature request related to a problem? Please describe.**
Currently the mandatory modules such as the **raw black/white point, demosaic, input color profile & output color profile** are shown at all times in the **show only active modules** section. I do understand that this is a feature of Darktable that shows all that is happening in the image pipeline. 
Would it be possible to hide these modules when its set to workflow beginner. It would make it simpler for new user to grasp the active modules that would need to be adjusted for their images. As most of the time we don't adjust the mandatory modules unless in certain specific situation. it is also not possible to add 2 mandatory modules in one images

**Describe the solution you'd like**
to hide the mandatory modules when switch to workflow beginner

or 

provide a checkbox to show or hide the mandatory modules

hope the DEVS would consider this and thanks for the amazing work

**Comment by johnny-bit** [comment]
Active modules are active modules. If you enable module that is not in your workflow set it gets displayed there and only there. Hiding those modules just for the "benefit" for beginner would hinder everybody else or would have to have settings & special case handling.

so:
> to hide the mandatory modules when switch to workflow beginner

would be a NO from me ;)

> provide a checkbox to show or hide the mandatory modules

This is more negotiable but would still cause issues. I understand that with "mandatory" modules you mean modules that can't be disabled... But then there are cases where adjusting demosaic or output color profile is beneficial even for begginers so I doubt it's best case scenario.

Other solution would be for user to read the manual or use online help available for those modules (click on `?` and then on the module you don't understand).

**Comment by eyedear** [comment]
i am not asking that the mandatory modules be completely hidden. i mean an option to hide it would be nice. as most of the time they are not use to change any of its properties. yes there are situation that the demosaic algorithm need to be change or there is a need to tweak the RAW Black/White Point. but those situation are not many in most cases. I just hope you would consider providing a hide option that's all. if its not in line with how darktable should be then its ok

**Comment by TurboGit** [comment]
> Would it be possible to hide these modules when its set to workflow beginner.

No, this was done in previous release of darktable (before 2.6.x IIRC) but it was not really good, it made people (especially beginners) confused about what is done by darktable. So after lot of discussion we decided to expose all modules to have a clear idea of the full pixelpipe. The fact that some modules were hidden made also some internal implementation harder. So all in all, there is probably zero chance that we go backward.
