### ISSUE TITLE
Problematic behavior of color calibration module

### ISSUE THREAD

**Issue by abnormally-distributed** [darktable-org/darktable#9643]
**To Reproduce**

First issue:
1. Ensure white balance is at camera default
2. Click on color calibration module
3. Select Non-Linear Bradford 
4. Observe that nothing changes. 

Second issue: 
1. Ensure white balance is at camera default
2. Click on color calibration module
3. Deselect clip negative values from gamut
4. Observe that image goes black. 

###  Expectation: ###

![image](https://user-images.githubusercontent.com/24922749/127127549-2ca802d7-757f-42be-87cc-2cc458a46a61.png)

**(But with clip engative RGB from gamut disabled and/or using non-linear bradford)**

### Reality: ###

![image](https://user-images.githubusercontent.com/24922749/127127165-5a700866-9ca0-4a5c-bced-3b8ab2a05415.png)

![image](https://user-images.githubusercontent.com/24922749/127127415-dc56d9fc-5421-49d2-93ff-cf8421438ddb.png)

**Which commit introduced the error**
I am using the latest 3.6 release 

**Platform**
* darktable version : e.g. 3.6.0
* OS                : Windows 10 
* Memory            : 8 GB of DDR4 (1333 Mhz)
* Graphics card     :  Geforce 1650
* OpenCL installed  :  Yes
* OpenCL activated  :  Yes

**Comment by Nilvus** [comment]
Those are not issues. For the first, color picker find sometimes good colors and sometimes not. It's something hard to do as colors implies a lot of things and the software can't really know what we want. But @aurelienpierre will probably be more precise than me on that.

For second issue, please search with just black patches or even only black and check closed issues, if you unselect negative clipped values checkbox you so authorize the software to go outside gamut and especially on shadows part. So clipped shadows values are black. Depending on image and calibration set, you will have less or more black patches without this. In general it is recommended to let that checkbox ticked, unless really know what to do and how to deal with it.

**Comment by aurelienpierre** [comment]
First issue is a known effect of the non-linear Bradford. Use CAT16, it's more accurate.

Second issue is solved in master and 3.6.1 branch.

**Comment by abnormally-distributed** [comment]
> Those are not issues. For the first, color picker find sometimes good colors and sometimes not. It's something hard to do as colors implies a lot of things and the software can't really know what we want. But @aurelienpierre will probably be more precise than me on that.
> 
> For second issue, please search with just black patches or even only black and check closed issues, if you unselect negative clipped values checkbox you so authorize the software to go outside gamut and especially on shadows part. So clipped shadows values are black. Depending on image and calibration set, you will have less or more black patches without this. In general it is recommended to let that checkbox ticked, unless really know what to do and how to deal with it.

The issue isn't that I don't like the auto-white balanced colors, the issue is that the non-linear bradford method does nothing.

**Comment by abnormally-distributed** [comment]
> First issue is a known effect of the non-linear Bradford. Use CAT16, it's more accurate.
> 
> Second issue is solved in master and 3.6.1 branch.

Is the non-linear bradford issue intended to be fixed? I usually use CAT16 though sometimes I find using a different CAT gives subtle differences which may be more or less pleasant compared to another.

**Comment by aurelienpierre** [comment]
The fix is to use another method. The maths are as they should be. The problem is not in the code but in the maths.

**Comment by abnormally-distributed** [comment]
I didn't think the math would result in pixel-for-pixel identical values
to having the module disabled (checked with color picker) regardless of the
illuminant for non-linear bradford (implying an identity matrix), but it
seems like it's a settled issue. Thanks for getting back to me!

**Comment by aurelienpierre** [comment]
I don't understand what your goal is. There is no identity matrix involved and there should not be one. 

We do a linear map to go to CAT space, scale the RGB values in this space by a coeff = (D50_RGB / scene_illuminant_RGB), then go back to the initial RGB space. In the non-linear Bradford transform, there is an extra power transform applied only on the blue channel, that was meant to minimize the perceptual error for a particular dataset. It is not used in the linear variant.

**Comment by abnormally-distributed** [comment]
> There is no identity matrix involved and there should not be one.... In the non-linear Bradford transform, there is an extra power transform applied only on the blue channel, that was meant to minimize the perceptual error for a particular dataset. It is not used in the linear variant.


This is why I expected NL-Bradford to give comparable results to the bradford. Instead, it does nothing, as if it were just multiplying by an identity matrix. I didn't mean that this is literally the case, only that it may as well be. My point was that unless the problem with the math is that unless it results in no changes, I'd expect _something_ to happen when selecting NL-Bradford.  Sorry, I can be needlessly abstract sometimes. 

I think it will be clearer if I show rather than explain.. Note how the live samples don't change their RGB values, nor does the image appear any different, regardless of what illuminant I set. This happens regardless of what image I load, and regardless of the camera.


![image](https://user-images.githubusercontent.com/24922749/127410327-6770cb3a-6ac3-4ee4-a19a-de451720232d.png)

![image](https://user-images.githubusercontent.com/24922749/127410339-9980ad51-3545-4e3e-85e6-80ae16d9dc3d.png)

![image](https://user-images.githubusercontent.com/24922749/127410348-adb52b42-7bc4-4d76-bacc-feafc4fbba6f.png)

**Comment by aurelienpierre** [comment]
Wow, ok, that was really not what I understood on the first read.

Confirmed, there is a bug in non-linear Bradford for OpenCL path.
