### ISSUE TITLE
Keybinds broken with Linux / i3 WM

### ISSUE THREAD

**Issue by tasnad** [darktable-org/darktable#9655]
DT version: 3.5.0+3112~gb85d54af1 (from git commit b85d54af16844195343af11876d93a9c849ff218)  but also before.

Keybinds do not work any more since roughly one or two months.
If I use xfce, everything is fine, but with [i3](https://i3wm.org/) it does not. 
It seems the window looses focus and the key is not registered by darktable.

The problem started some versions before and unfortunately I don't know where exactly. However, I can try different git checkouts and compiles to bisect the problem, if needed.

Side note: "darktable -d all" does not log anything when pressing a button except "[lighttable] expose took 0.0000 sec".

**Comment by dterrahe** [comment]
@tasnad would you be able to test if #9719 resolves this issue?

**Comment by dterrahe** [comment]
Maybe you can provide more details about your setup. I'm not an i3 user, but I just now installed it on my debian box, logged out and back into i3 and managed to run dt just fine; all key shortcuts seem to be working.

Now I need to figure out how to log out of i3 again... ;-)

**Comment by tasnad** [comment]
On that part, Windows+Shit+E :)

Well then I am confused. The mainline darktable from the master branch works as well?

I am not sure what part of my setup might cause the issue, but let's try:
- Thinkpad T480s (-> intel graphics)
- i3 (also tried with clean config)
- arch linux with kernel 5.13.7
- mesa 21.1.6-1
- gtk3 1:3.24.30-1
- libx11 1.7.2-1

Which other packages would you suspect?
I will also try in a VM and see if it works there.

**Comment by johnny-bit** [comment]
I've seen already couple issues related to either keys or bauhaus widgets limited to less-mainstream WMs... and I wanted to ask... is the issue in darktable or WM?

**Comment by tasnad** [comment]
Ok I will have to further investigate. In the arch VM it works, in the hosts it does not.
I am not exactly sure where the issue lies, I will try to find it out.

**Comment by tasnad** [comment]
Ok, I figured it out. I had set "GDK_CORE_DEVICE_EVENTS=1" to "combat tiling window manager focus issued". 
So this is probably not darktable's fault. However, issueing a warning would be great.

**Comment by johnny-bit** [comment]
> However, issueing a warning would be great.

yes, but how?

**Comment by tasnad** [comment]
I meant simply check if it is set and if yes, write a console warning like "You have set GDK_CORE_DEVICE_EVENTS. Please note that darktable does not support the old GTK2 input method and keybinds are broken.".
However, I'm not sure if it's darktables job to check this. But shouldn't it support the old input method then?
I know almost nothing about GTK, so I might misunderstand what's happening.
