### ISSUE TITLE
Filmstrip select options no longer available in DT 3.6

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/darktable#9656]
Previous darktable versions provide keystroke actions to select multiple files while in darkroom, and these options appear to be unavailable in DT 3.6 and forward.  For example, the attached screenshot shots eight files as highlighted, but only one image was actually selected for export. Holding "h" on darkroom appears to confirm these options are no longer available.

These features were very useful for applying edits, ratings and exporting across multiple images.  Now they must be individually selected or deselected.

My version is for Windows 10, but I suspect this applies across all versions.

![DT Screen Shot - highlighted but not selected](https://user-images.githubusercontent.com/61152378/127232713-7a24044e-8ad0-4b0e-aeae-3599074a831b.JPG)

**Comment by ralfbrown** [comment]
Export is acting the same as the Ctrl-E shortcut while in darkroom has always done -- export only the image showing in the center view.  Export while in lighttable exports all selected images.

@elstoc: documentation tweak appropriate?

**Comment by Dave22152** [comment]
Thanks.  I think I was a bit hasty when I wrote this.  I've gone back to the 3.6 manual and exercised each of the Filmstrip options in both 3.6 and the dev 3.7:

![DT Select Options](https://user-images.githubusercontent.com/61152378/127361562-bc64f05c-35e1-439d-9e7a-e5fbeb9a4f4e.JPG)

So it appears the selective copy and paste function doesn't work in 3.6, and many other operations aren't functioning in 3.7.  I don't know if the 3.7 changes were intentional, but they sure are handy...  ;-)

Thanks for your attention!

**Comment by ralfbrown** [comment]
#9633 fixes the first three and Ctrl-D.  Selective copy is Shift-Ctrl-C/V, not Alt-Ctrl (and has been for many versions).

**Comment by Dave22152** [comment]
@ralfbrown, I'm going to apologize in advance because I'm afraid I'm nickel-and-diming you, but I double checked the 3.6 manual and may have found a typo:

![DT Filmstrip Shortcuts](https://user-images.githubusercontent.com/61152378/127386175-aa689359-5a74-458b-904d-ce2691a964d5.JPG)

The selective copy function in Lighttable is Shift+Ctrl+C/V but the manual shows it as Alt+Ctrl+C/V.  Regardless, the copy function doesn't seem to work...

**Comment by ralfbrown** [comment]
Shift-Ctrl-C/V works just fine for me in both lighttable and darkroom....

**Comment by Dave22152** [comment]
Using both DT 3.6.0 and 3.7.0+393 on Windows 10.  In lighttable, applying Shift+Ctrl+C simply copies the history settings with no option to select or deselect modules.  But when applying Shift+Ctrl+V, I get the expected window:

![Selective Paste from Shift+Ctrl+V](https://user-images.githubusercontent.com/61152378/127392039-4a5e8179-6e9d-434e-85c9-505e9a7edbab.JPG)

Going to the darkroom, I find the same behavior.  Shift+Ctrl+C is a blind copy and Shift+Ctrl+V provides the menu:

![Darkroom Selective Paste from Shift+Ctrl+V](https://user-images.githubusercontent.com/61152378/127392254-e4d9a4e0-cbe8-4b73-b9c9-ab0c87d17602.JPG)

I find this in both 3.6 and 3.7 versions.  What O/S are you using?  Is this potentially a Windows specific issue?

**Comment by ralfbrown** [comment]
I'm on Linux, so perhaps Windows is doing something weird.

**Comment by Dave22152** [comment]
I’ll check with some other Windows users.

**Comment by johnny-bit** [comment]
Regarding documentation saying <kbd>Alt</kbd> instead of <kbd>Shift</kbd> - please raise an issue on https://github.com/darktable-org/dtdocs

**Comment by Dave22152** [comment]
@johnny-bit - done.

@ralfbrown, a friend on Windows didn't see the problem either, so it may just be a fluke on my machine. I'll close the issue.
