### ISSUE TITLE
shortcut key to progressively increment or decrement the rotation of an image fails

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#9660]
**Did you buy darktable from an application store ?**

no, built from github 

**To Reproduce**

open image
enable crop&rotate
rotate image +0.25 and save as preset
assign keystroke to preset
do same for -0.25

initiating keystroke rotates image *once* by 0.25 
repeating does not increment the degree of rotation, remains at 0.25

**Expected behavior**

before the shortcut(s) rewrite I was able to make minor rotation adjustments which would add or subtract to each other, ie: first 0.25, second 0.50, third 0.75

this appears no longer possible ???

**Which commit introduced the error**
committing the shortcuts rewrite to incorporate the midi devices

**Platform**
darktable 3.7.0+534~g327ac1a00
Linux Kernel: 5.13.2-1-default x86_64 bits: 64 
openSUSE Tumbleweed 20210726
36 GB
NVIDIA GF106 [GeForce GTS 450], 390.144
OpenCL installed: yes
OpenCL activated: yes
Xorg 1.20.12
KDE5/plasma5 5.84.0-1.1.x86_64
GTK 3.24.30
gcc11-11.1.1
build.sh --enable-opencl --install --build-type RelWithDebInfo -DDONT_USE_INTERNAL_LUA=On 

**Additional context**

 - Can you reproduce with another darktable version(s)? 
yes, all since shortcut key rewrite

 - Can you reproduce with a RAW or Jpeg or both? 
 both

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? 
yes

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes

happens with lua enable or not.

**Comment by ptilopteri** [comment]
attn: @dterrahe

**Comment by ralfbrown** [comment]
If you make a preset that rotates the image +0.25, that's what you get -- a preset always sets the parameters to the stored value.

In 3.6, for a shortcut that **increments** the angle, go into `preferences|shortcuts` and assign a key to `crop&rotate|angle|increase` or `crop&rotate|angle|decrease`.  I just checked, and we do seem to have lost that capability in master with the new input system.

**Comment by ptilopteri** [comment]
so I was incorrectly configuring but the result is still failure.
tks, will leave open.

**Comment by ptilopteri** [comment]
@ralfbrown 
there does not appear to be a way to define c&r|angle|increase or decrease
or, I cannot determine the method to do so.

**Comment by ralfbrown** [comment]
I don't have 3.6 installed atm, but it should be the same as in 3.4, where I've just verified that you go to `processing modules|crop and rotate|angle` under the `shortcuts` tab in the preferences dialog to see the `increase` and `decrease` settings.  I had shortcuts assigned to them right up until the new input system got merged.  As far as I can tell, the capability is indeed gone in master.

**Comment by dterrahe** [comment]
when you assign a shortcut key to the angle slider, at first the default effect, which is "edit", is set.
This means just pressing the key (and releasing it) will show the pop-up box. (For this to work, the slider has to have been visible at least once, since start, due to a bug in bauhaus.)
Pressing (and holding) the key and then making a move (scroll or move the mouse) will change the value up or down. You can change the stop size by editing the speed in the shortcut.

If you want the shortcut key, by itself, to change the value by one step (or multiplied by speed), you can set the "effect" of the shortcut to "up" or "down".

**Comment by ptilopteri** [comment]
@dterrahe 

> when you assign a shortcut key to the angle slider, at first the default effect, which is "edit", is set.
> This means just pressing the key (and releasing it) will show the pop-up box. (For this to work, the slider has to have been visible at least once, since start, due to a bug in bauhaus.)
> Pressing (and holding) the key and then making a move (scroll or move the mouse) will change the value up or down. You can change the stop size by editing the speed in the shortcut.
> 
> If you want the shortcut key, by itself, to change the value by one step (or multiplied by speed), you can set the "effect" of the shortcut to "up" or "down".

ok, I have set "e" as
   e=iop/clipping/angle;up
and this works as you describe.  thankyou

but I am unable to set "w" as
   w=iop/clipping/angle;down

dt removes that setting w/o comment.

as the right hand works the mouse and the left hand is free to remain on the keyboard, 
setting keys readily and familiarly available to the left hand is desirable to maintain some
degree of speed.  Plus I have been doing it this way for >10 years.

**Comment by dterrahe** [comment]
w is by default used for "full preview". If you use a shortcut combination multiple times in shortcutrc, the last will silently overwrite previous (or default) ones.

Did you not manage to assign w to angle and then change its effect in the shortcuts configuration dialog box (or tab in  prefs)? There you should have received a warning about such a clash and would be allowed to overwrite it.

**Comment by ptilopteri** [comment]
@dterrahe 

> w is by default used for "full preview". If you use a shortcut combination multiple times in shortcutrc, the last will silently overwrite previous (or default) ones.
> 

yes, I understand this

> Did you not manage to assign w to angle and then change its effect in the shortcuts configuration dialog box (or tab in prefs)? There you should have received a warning about such a clash and would be allowed to overwrite it.

I assigned "e" and was able to change it's effect, but then was unable to assign "w".  
I wanted:  w=iop/clipping/angle;down
but I was able to assign "c" as it is unused

I may swap functions assigned to "w" with "c" to *enhance* my workflow.

Assigning shortcuts in the manner you have described is not obvious, though, and should
be described in the fine manual.


tks, will close this issue

**Comment by ptilopteri** [comment]
fwiw: it is much easier to accomplish by editing ~/.config/darktable/shortcutrc 
with a text editor.

**Comment by dterrahe** [comment]
> dt removes that setting w/o comment.

>Assigning shortcuts in the manner you have described is not obvious, though, and should
be described in the fine manual.

You are running master. It is not a finished product. Many changes are made, things get broken and fixed, with the help of testers like yourself. Documentation is updated when the changes settle down. If you are worried things break, and they may unexpectedly and cause you to lose data, or you don't have time to follow developer channels to know which major changes are underway, you may save yourself time and aggravation by using the released versions.

Many thanks for your understanding.

**Comment by ptilopteri** [comment]
I have been running either master or previously the development version for quite some years.  I do read the dev list and all the github traffic.

But still when *major* changes happen such as reassigning *all* the shortcuts, makes much
confusion.

fwiw:  I have only once had dt corrupt data and was easily able to recover.

and I do appreciate the work involved.
