### ISSUE TITLE
Remove exposure and black compensation from the histogram UI

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#9663]
**Context**

The histogram lib has grown in code size and features in a way that makes the current code highly non-systematic, full of particular cases and difficult to maintain. It is also slow to paint in the GUI (here, it takes almost twice as much time on Xeon to paint this widget than needed to color-convert a full 4K buffer), so it needs better caching mechanisms.

I'm planning a revamp of this widget, as started in #9640 aimed at:
1. enabling several scopes to be displayed from a single preview buffer (efficient),
2. enabling scopes snapshots.

The current state of the code doesn't allow this. So I need, at least to:

1. break the current scopes into unitary files, each of them having a unified API like `init()`, `cleanup()`, `process()`, `draw()`, `button_callback()` and its own data structure. This is much like what IOP and masks do, and avoids to switch cases. From the main histogram, we only need to know the type of the scope and then call the proper sub-module,
2. force each scope to pass its graph as an anonymous image buffer, to be painted in the background of the widget, and separated from GUI buttons. This allows efficient caching of the background graphs and uniform handling of Cairo buffers across scopes. Then, it's only a matter of overlaying GUI buttons on top. The buttons could be the same for all scopes, but scopes could all define their own callbacks.

This plan is threatened by the way the basic histogram acts: both as a read-only scope AND as an exposure GUI control. That's unique across all scopes, and it creates an annoying special case to make the code more systematic.

**Do we really need exposure control in histogram ?**

So far, there are 4 different ways to setup the exposure control:
1. using the usual exposure module,
2. using the quick access panel,
3. using the dynamic shortcuts (so E + scroll could be mapped to exposure setting and be used without widget),
4. using the histogram dragging feature.

The histogram way has many flaws:
* is is not aware of the multiple instances of exposure that may be used,
* it does not give feedback about the current exposure setting and, with tone mapping operators in place, the relationship between histogram shape and exposure value is neither direct nor reliable,
* when using darktable with a touch pad (especially set with two-fingers scroll), it's easy to scroll the histogram by accident, resulting in unwanted exposure changes.

**My proposal**

Get rid of the interactive layer of the histogram, to make it uniform with other scopes and use this opportunity to simplify the code, then resort to the dynamic shortcuts and/or quick access panel for quick setting.

**The discussion**

I understand this feature is an old beloved one, but it comes on top of a widget that does a lot more now than in the past. So, here is your chance to defend it.

Arguments that will not be accepted:
* I like it,
* Software X has the same feature,
* People are used to it.

Arguments that will be accepted:
* When doing X in view Y, it gives a faster access to exposure than using method Z,
* When using input device A, it is more convenient,
* It requires fewer steps/key strokes/… than method Z,
* anything factual.

Main topic (stay on it please):
* Do other exposure setting methods provide at least a similarly efficient workflow ?

Constraints:
* All suggested solutions need to be reasonable in terms of man-hours, amount of code changes and overall quantity of work.

**Comment by TurboGit** [comment]
I can adapt to anything. I think the best alternative to me is the dynamic key shortcut `E + scroll`. After reading your comment @aurelienpierre I'm certainly ok to remove the interactive layer from the histogram.

**Comment by dtorop** [comment]
@aurelienpierre: If this is a go, I'm happy to do the work of ripping out exposure control, as I'm all too familiar with this code. OTOH, if you've got a bunch of changes queued up and ideas of how to do them, I'm even happier leaving it to you!

The only counter-proposal I could see would be making drag regions on the scope widget be configurable via callbacks. For example, it could be nice to adjust white/black relative exposure in filmic rgb via histogram/waveform drag regions. Or to make dragging the vectorscope adjust color calibration. I think it's reasonable, though, to rip out the exposure drag regions now, and eventually add in configurable drag overlays.

> force each scope to pass its graph as an anonymous image buffer, to be painted in the background of the widget, and separated from GUI buttons. This allows efficient caching of the background graphs and uniform handling of Cairo buffers across scopes.

Yes! Currently GTK redraws the entire scope for each step of button fade up/down when the mouse enters/leaves the scope. Any optimization by image buffers would help here, though this may be a limitation of GtkOverlay.

**Comment by aurelienpierre** [comment]
@dtorop yeah I need that ASAP and already started the work, but you can still review my bugs ;-)

**Comment by dtorop** [comment]
@aurelienpierre: Sounds good. I have one PR pending against current code (#9209) but it needs a bit more work yet... Will look forward to seeing the scope changes.

**Comment by difrkaguilar** [comment]
I always use the sliders in the module because it's better to control everything. The e+scroll it's not so good for me because it controls only the exposure, but not the black point. 

On the other hand, with the histogram and vectorscope it's easy to visually control both of them. I think this feature comes since the beginning of the software, and  a lot of people may use this feature, many of them may prefer to use it visually dragging the mouse over the histogram/vectorscope areas to change exposure and black point, and don't like to use the sliders in the module.

Maybe a change like this one that implies some users experience should be put in consideration in Pixls.us using something like a poll.

Using the arguments explained by @aurelien

or others (explain your reasons).

just evaluate that.

I know the code may be astronomically big and complex but take in consideration the opinions of final users of the app.

**Comment by dtorop** [comment]
A couple notes, if scope drag continues to adjust iops (or this UI returns):

- Unlike the bauhaus widgets, dragging the scope re-runs the pixelpipe every time there is a mouse event, resulting in jerky/stuttering results. This should be trivial to fix by comparing to `dt_bauhaus_slider_postponed_value_change()` and delaying processing until the pixelpipe can update based on `dev->preview_average_delay`.
- The draggable overlays code is mucked in with the DrawingArea which displays the scope. Ideally the draggable areas would be separate widgets as part of the GtkOverlay holding the scope, assuming that the general disinterest of GTK in overlaid controls would allow this.
