### ISSUE TITLE
unable to run Darktable on windows

### ISSUE THREAD

**Issue by djpeter84** [darktable-org/darktable#9665]
Unable to start on windows. I looked at different threads and no solution for me yet.
"An I handled exception occurred... "

-------------------

Error occurred on Sunday, August 8, 2021 at 15:03:36.

darktable.exe caused an Integer division by zero at location 00007FFDFED493B9 in module igdrcl64.dll.

AddrPC           Params
00007FFDFED493B9 0000000000000000 0000000000000048 000002093DA545F0  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFED81D2A 000002093D9D2520 00000209FFFFFFFF 00000AEFC9283EA2  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFED6E6AE 000002093D6CBE80 0000000000000000 000002093D9D1F80  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFED32CA9 000002093C41D850 00007FFDFED402E8 000002093DA4FB90  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFEDE1782 000002093D6C83F0 000002093D6C83F0 0000000000000000  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFEDE1C01 0000000000000000 2AAAAAAAAAAAAAAB 0000000000000003  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFEB9A644 0000000000000048 00007FFDFED94EEB 000000A76E1FE318  igdrcl64.dll!GTPin_Init
00007FFDFED46B80 0000000000000000 00007FFDFED40794 000002093DA4FB90  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFED46A46 000000A76E1FE5C0 000002093D6CBE80 000002093DA4FB90  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFED46634 0000000000000000 0000000000000000 0000000000000000  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFED77881 000002093D6CBE80 000002093D6CBE80 0000000000000000  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFED45CC6 000000A76E1FE630 0000000000000000 000000A76E1FE7C8  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFED45B57 0000000000000000 0000000000000000 0000000000000000  igdrcl64.dll!clReleaseGlSharedEventINTEL
00007FFDFEB6E456 0000000000000000 0000000000000000 0000020900000000  igdrcl64.dll!0x7ffd0000e456
00007FFDFEB81FAE 000002093C3BD250 000002093C3BD250 00007FFE1FF83948  igdrcl64.dll!clGetExtensionFunctionAddress
00007FFE1FF1118D 000002093C3734F0 0000000000000000 00007FFDFEB60000  OpenCL.dll!0x7ffe0000118d
00007FFE1FF17148 00007FFE1FF83948 000002093CC4D7C0 0000000000000001  OpenCL.dll!clWaitForEvents
00007FFE506138B0 000002093CC36D50 0000000000000000 000000A76E1FEF44  ntdll.dll!RtlRunOnceExecuteOnce
00007FFE4E29A5FB 0000000000000000 0000000000000014 000002093CC35561  KERNELBASE.dll!InitOnceExecuteOnce
00007FFE1FF15B9C 0000000000000300 000002093CC36D50 000002093CD0CA20  OpenCL.dll!clGetPlatformIDs
00007FFE16F55D16 000000A76E1FF550 0000000000000000 0000020900000000  libdarktable.dll!dt_opencl_init
00007FFE16EB290C 00007FFE00000001 000002093B9DF780 00007FFE00000001  libdarktable.dll!dt_init
00007FF6B5012A39 00007FF6B5011660 0000000000000010 0000000000000000  darktable.exe!0x7ff600002a39
00007FF6B50115B5 000000000000005A 0000000000000000 00007FF6B5017090  darktable.exe!0x7ff6000015b5
00007FF6B50113D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff6000013d4
00007FF6B5011506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff600001506
00007FFE500E7034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFE50622651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.6.0.0
ntdll.dll   	10.0.19041.1110
KERNEL32.DLL	10.0.19041.1023
KERNELBASE.dll	10.0.19041.1110
msvcrt.dll  	7.0.19041.546
libintl-8.dll	0.19.8.0
libglib-2.0-0.dll	2.68.3.0
ole32.dll   	10.0.19041.746
ucrtbase.dll	10.0.19041.789
RPCRT4.dll  	10.0.19041.1081
combase.dll 	10.0.19041.1081
GDI32.dll   	10.0.19041.746
win32u.dll  	10.0.19041.1110
gdi32full.dll	10.0.19041.1110
msvcp_win.dll	10.0.19041.789
USER32.dll  	10.0.19041.906
SHELL32.dll 	10.0.19041.1023
WS2_32.dll  	10.0.19041.546
libdarktable.dll
PSAPI.DLL   	10.0.19041.546
libwinpthread-1.dll	1.0.0.0
libpcre-1.dll
libcairo-2.dll
exchndl.dll 	0.9.2.0
libgdk-3-0.dll	3.24.29.0
IMM32.dll   	10.0.19041.546
SETUPAPI.dll	10.0.19041.844
cfgmgr32.dll	10.0.19041.546
bcrypt.dll  	10.0.19041.1023
libgdk_pixbuf-2.0-0.dll	2.42.4.0
libgio-2.0-0.dll	2.68.3.0
libgobject-2.0-0.dll	2.68.3.0
SHLWAPI.dll 	10.0.19041.1023
libharfbuzz-0.dll
libpango-1.0-0.dll	1.48.5.0
libpangocairo-1.0-0.dll	1.48.5.0
libgtk-3-0.dll	3.24.29.0
zlib1.dll
ADVAPI32.dll	10.0.19041.1052
libgcc_s_seh-1.dll
sechost.dll 	10.0.19041.906
libstdc++-6.dll
comdlg32.dll	10.0.19041.906
libgomp-1.dll
libavif.dll
shcore.dll  	10.0.19041.1023
libcurl-4.dll
CRYPT32.dll 	10.0.19041.844
libexiv2.dll
libgmodule-2.0-0.dll	2.68.3.0
WLDAP32.dll 	10.0.19041.546
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libicuuc68.dll
libicuin68.dll
libIlmImf-2_5.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
libopenjp2-7.dll
libpugixml.dll	1.11.0.0
librsvg-2-2.dll
libpng16-16.dll
libsecret-1-0.dll
libsoup-2.4-1.dll
libsqlite3-0.dll
libtiff-5.dll
libxml2-2.dll
MSIMG32.dll 	10.0.19041.546
libfreetype-6.dll	2.10.4.0
libfontconfig-1.dll
libpixman-1-0.dll
mgwhelp.dll 	0.9.2.0
dwmapi.dll  	10.0.19041.746
libcairo-gobject-2.dll
WINMM.dll   	10.0.19041.546
libepoxy-0.dll
libfribidi-0.dll
gdiplus.dll 	10.0.19041.1110
libpangowin32-1.0-0.dll	1.48.5.0
libffi-7.dll
IPHLPAPI.DLL	10.0.19041.546
DNSAPI.dll  	10.0.19041.1023
USP10.dll   	10.0.19041.546
libthai-0.dll
libgraphite2.dll
libpangoft2-1.0-0.dll	1.48.5.0
libiconv-2.dll	1.16.0.0
COMCTL32.dll	6.10.19041.1110
libaom.dll
libdav1d.dll	5.1.0.0
rav1e.dll
libatk-1.0-0.dll	2.36.0.0
WINSPOOL.DRV	10.0.19041.1023
libexpat-1.dll
libbrotlidec.dll
libidn2-0.dll
libcrypto-1_1-x64.dll	1.1.1.11
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libexif-12.dll
libssl-1_1-x64.dll	1.1.1.11
libltdl-7.dll
libzstd.dll
VERSION.dll 	10.0.19041.546
libsystre-0.dll
libbz2-1.dll
libIex-2_5.dll
libicudt68.dll
libIlmThread-2_5.dll
libImath-2_5.dll
USERENV.dll 	10.0.19041.572
libHalf-2_5.dll
libgcrypt-20.dll	1.9.2.0
libdeflate.dll
libjbig-0.dll
liblzma-5.dll	5.2.5.0
libwebp-7.dll
dbghelp.dll 	10.0.19041.867
libdatrie-1.dll
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
libtre-5.dll
libgpg-error-0.dll	1.42.0.0
CRYPTBASE.DLL	10.0.19041.546
dbgcore.DLL 	10.0.19041.789
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.1052
bcryptPrimitives.dll	10.0.19041.1023
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.1081
Wldp.dll    	10.0.19041.662
kernel.appcore.dll	10.0.19041.546
uxtheme.dll 	10.0.19041.1081
OLEAUT32.dll	10.0.19041.985
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.1023
profapi.dll 	10.0.19041.844
mswsock.dll 	10.0.19041.546
MSCTF.dll   	10.0.19041.1081
DEVOBJ.dll  	10.0.19041.546
WINTRUST.dll	10.0.19041.1110
MSASN1.dll  	10.0.19041.546
Wintab32.dll	1.0.0.1
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.1023
AppXDeploymentClient.dll	10.0.19041.1110
Windows.ApplicationModel.dll	10.0.19041.746
twinapi.appcore.dll	10.0.19041.964
Windows.FileExplorer.Common.dll	10.0.19041.867
iertutil.dll	11.0.19041.1081
mssprxy.dll 	7.0.19041.1023
OpenCL.dll  	2.2.8.0
dxgi.dll    	10.0.19041.964
IntelOpenCL64.dll	23.20.16.4973
intelocl64.dll	7.6.0.611
task_executor64.dll	7.6.0.611
OPENGL32.dll	10.0.19041.1081
GLU32.dll   	10.0.19041.1081
cpu_device64.dll	7.6.0.611
igdrclneo64.dll
dxcore.dll  	10.0.19041.546
igdrcl64.dll	23.20.100.8682
igdgmm64.dll	27.20.100.8682
TextShaping.dll
textinputframework.dll	10.0.19041.1081
CoreUIComponents.dll	10.0.19041.546
CoreMessaging.dll	10.0.19041.746
ntmarta.dll 	10.0.19041.546
wintypes.dll	10.0.19041.1081

Windows 10.0.19043
DrMingw 0.9.2

 It works great on Linux!

**Comment by djpeter84** [comment]
#windows

**Comment by dterrahe** [comment]
You provide very little information, but if you are running master, this may be a duplicate of #9519

Please let us know if https://github.com/darktable-org/darktable/issues/9519#issuecomment-882010577 helps you.

**Comment by djpeter84** [comment]
After hours of research i was able to fix this (OpenCL User Mode Driver ) by rolling back the graphics driver

![image](https://user-images.githubusercontent.com/39010720/128735264-8f80c9ac-fbb1-4808-a9d6-cfd9bdaccfd4.png)


see also
https://www.dll-files.com/igdrcl64.dll.html
https://community.amd.com/t5/drivers-software/problems-with-igdrcl64-dll-solved/td-p/105803
https://www.gitmemory.com/issue/darktable-org/darktable/6749/721992584
