### ISSUE TITLE
crash when switching off quick access items

### ISSUE THREAD

**Issue by jochen-01** [darktable-org/darktable#9668]
**Darktable 3.6**: When switching off a module in the quick access panel darktable crashes instantly. Switching on a module works as expected.

**Steps to reproduce**
Switch a module on with the switch icon left of the module name, then switch it off --> crash.

**Expected behaviour**
Just switch off the module in question and let me continue working. ;-)

As I am still using Ubuntu 18.04 LTS I had to install the flatpak version from https://flathub.org/apps/details/org.darktable.Darktable (if that matters).

**Comment by Mark-64** [comment]
Can't reproduce in DT 3.6, Windows 10

**Comment by wpferguson** [comment]
Can't reproduce on DT 3.6 Ubuntu 18.04 LTS

**Comment by Nilvus** [comment]
Can't reproduce too on Ubuntu 21.04. Maybe it's an issue in flatpak (if that the case, darktable team can't do anything, you will have to see with flatpak manager (I don't know who made it).

Or why not update to at least Ubuntu 20.04 LTS? You will then be able to use deb package from Opensuse repository and maybe have this works.

**Comment by jochen-01** [comment]
> Can't reproduce on DT 3.6 Ubuntu 18.04 LTS

Did you build it from source? Is it possible on Ubuntu 18.04?

**Comment by jochen-01** [comment]
> Or why not update to at least Ubuntu 20.04 LTS?
I'll do it later this year. Have to wait for other reasons.

**Comment by wpferguson** [comment]
> Did you build it from source? Is it possible on Ubuntu 18.04?

Yes, building from source works just fine on 18.04

**Comment by jochen-01** [comment]
Meanwhile I found out that the reason was a subtile error in one of the configuration files. Resetting the config solved the problem.
Thank you for your help.
