### ISSUE TITLE
minor usability: position of "module order" tickbox in selective copy-paste dialog

### ISSUE THREAD

**Issue by moy** [darktable-org/darktable#9671]
**Is your feature request related to a problem? Please describe.**

I use a lot the selective copy-paste (Control-Shift-C) to copy just the last few modules I edited. Using the keyboard, I do:

1. Control-Shift-C to open the selective copy-paste dialog
2. Alt-n for "select none"
3. Space or Enter to re-select the module to copy
4. If needed, downarrow, space, as many times as there are modules to copy
5. Alt-O for "OK"

At step 3., with old versions of dt, I needed just a single press to space. Now that "module order" is also offered, I need one more down-arrow press. Not a big deal, but it used to be slightly more fluent when done with the keyboard only. However, having the option to tick/untick the module order is good.

**Describe the solution you'd like**

Moving the "module order" checkbox to the end of the list make it easier for keyboard users, and would probably also be convenient for mouse-users since it would make it easier to focus on the last edited modules, which is most likely the ones the user is interested in.

**Comment by Nilvus** [comment]
Hi @moy. Was a long time we see you on darktable channels!

I support your idea. Module order is rarely the thing we change. I always use 3.0 one and never change it (or really rarely). Putting it at the end would make more sense than actual behavior.
