### ISSUE TITLE
Ability to import multiple GPX files at once

### ISSUE THREAD

**Issue by Clorix1** [darktable-org/darktable#9673]
**Is your feature request related to a problem? Please describe.**
The problem I have is not being able to select multiple GPX files at once for geotagging images.

**Describe the solution you'd like**
I would like to be able to select multiple GPX files at once in the import window.

**Alternatives**
During the GPX import process, I have tried holding Shift and Ctrl while clicking the files to no avail.

**Additional context**
I think I have a niche use case for GPX files, so I understand if this isn't something that most others would need.

I like to take lots of screenshots while in my flight simulator, and I have a program that runs during my flights that allows me to export flights to GPX files. I've been using those files to geotag my screenshots. I usually do several flights before importing into Darktable. If possible, it'd be great to be able to import all my GPX files at once rather than one at a time after several flights.

**Comment by heitorPB** [comment]
Being able to import multiple GPX tracks would be awesome.

**Comment by paolobenve** [comment]
I'd want to work on this issue, but I'd need a mentor...

**Comment by johnny-bit** [comment]
@paolobenve - depending on how deep you'd like your changes to be :)

in `src/libs/geotagging.c` in `_choose_gpx_callback` you have to allow multiple files to be selected using `gtk_file_chooser_set_select_multiple` with second param set to `TRUE`. And then instead of `gtk_file_chooser_get_filename` use `gtk_file_chooser_get_filenames` to get all the GPX files and process them.

To see how multple files are handled you can check `styles.c` or `preferences.c` where `gtk_file_chooser_set_select_multiple` is set to true.

That should be enough IMO since applying GPX file is already a "job", so it's separate thread.

**Comment by paolobenve** [comment]
> in src/libs/geotagging.c in _choose_gpx_callback you have to allow multiple files _etc_

Thank you, done, this is the easiest part of the issue.

The most difficult is _using_ the multiple files selected, which come as a GSList.

I suppose we have to change the structure `dt_lib_geotagging_t` in `src/libs/geotagging.c` in order to manage a list of gpx files instead of one...

**Comment by johnny-bit** [comment]
Welp, so it's a bit more complex ;) you'd need @phweyland for moar guidance then ;)

**Comment by phweyland** [comment]
Everything is feasible, but to concatenate gpx files and their tracks is the job of a gpx file editor.
The same for track points cleaning, optimizing, track split or concatenation, etc ... 

> The most difficult is using the multiple files selected, which come as a GSList.

I guess that a good start is to add a dt_gpx_add() beside dt_gpx_new().

> I suppose we have to change the structure dt_lib_geotagging_t in src/libs/geotagging.c in order to manage a list of gpx files instead of one...

Not sure this necessary as the gpx files themselves are not used any more after having been read.

Remains the UI where the user should know he has selected several files and/or which files have been selected.
