### ISSUE TITLE
Liquify angle interpolation problem using line or curves tool when crossing the line horizontal to the left (west)

### ISSUE THREAD

**Issue by toschi23** [darktable-org/darktable#9675]
**Describe the bug/issue**
When using the liquify tool and especially the line and curve tools, Darktable allows the user, to set the distortion vectors at distict points and iterpolates the vectors for the segment in between. 
From what I can tell it does so by interpolating the strength of the distortion (length of the vector) and the direction of distortion (angle of the vector). 
As seen in the appended screenshot this causes problems when neighboring vectors face left and one is tilted slightly up and one slightly down. In this case the Liquify module does not interpolate along the short angle, but the longer angle the other way around. This causes heavy distortion between the two nodes. It also does not just affect the visualized yellow guiding arrows, but the underlying image augmentation as well.

As I said it appears to be related to how the vectors (complex numbers in the code) get interpolated. Unfortunately I am not proficient enough in writing and reading C code to completely pin down the error. 

**To Reproduce**
To reproduce this behavior
1. Go to liquify
2. Click on the line tool
3. add two points on the image, preferably somewhere with a vertical line segment so the effect it has on the image is more easily seen.
4. Set one vector facing to the upperleft quadrant
5. Set the other vector to face to the lowerleft quadrant. (Playing with the angles especially crossing the horizontal line makes the error obvious.)

**Expected behavior**

**Screenshots**
![Bildschirmfoto vom 2021-07-30 07-46-50](https://user-images.githubusercontent.com/12988933/127606933-86bf35f7-4a82-4ebe-98e3-98bfa82e952f.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6
* OS                : Linux
* Linux - Distro    : Ubuntu 21.4

**Additional context**

 - I asked a question about this on [reddit](https://www.reddit.com/r/DarkTable/comments/ospcrm/liquify_arrow_interpolation/?utm_source=share&utm_medium=web2x&context=3) and another user could reproduce this issue. His/her DT Version is unknown to me
 - Can you reproduce with a RAW or Jpeg or both? Affects raw and jpg
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes

 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
[Color_squares.jpg.txt](https://github.com/darktable-org/darktable/files/6905376/Color_squares.jpg.txt)

**Comment by TurboGit** [comment]
Should be fixed, see #9678
