### ISSUE TITLE
parametric mask preview not visible in Lab blend colorspace

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9676]
if the Lab blend colorspace is selected, the yellow mask preview is not available. The mask itself is applied.

**To Reproduce**
1. open image in darkroom
2. apply local contrast with parametric or drawn mask
3. activate display of mask

default blend colorspace ist lab - so no yellow preview is shown. Switching to RGB (scene or display) blend mode enables the preview 

**Platform**
* darktable version : darktable-3.7.0+631~g9cbcf9e47 
* OS                : Win10 and OSx

**Comment by Mark-64** [comment]
I can't reproduce, can you specify step by step?

**Comment by ralfbrown** [comment]
Confirmed on linux.  Also for the sharpen and legacy colorbalance modules.

- open an image
- enable local contrast, set details to 200+ to make things obvious
- turn on parametric mask, set L channel limits such that only a part of the image is affected (will be noticeable by the changed appearance)
- click on the show-mask button
- image turns grayscale, but no yellow shows

**Comment by jade-nl** [comment]
Came to github to make a bug report about this. I'll add to this one instead:

https://user-images.githubusercontent.com/56407344/127741837-919db393-7c04-4d11-8276-ef6fa7aec429.mp4

this is **darktable 3.7.0+583~g8aa6c7e5a**

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by s7habo** [comment]
#9699

**Comment by jade-nl** [comment]
@TurboGit 

```
[stasis] jade ~/.local/git/darktable $ git bisect good
131fede29c613797bc653c5ebf60cf273c9735a8 is the first bad commit
commit 131fede29c613797bc653c5ebf60cf273c9735a8
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Sun Jul 25 05:31:18 2021 -0400

    convert more float* args to dt_aligned_pixel_t

:040000 040000 9a67e4cab2128722b5c7406576493a66d6f01f80 5cd5688691051a3eaff9de2f70d1b4376608f013 M      src
```

**Comment by TurboGit** [comment]
@jade-nl: Thanks a lot this will speed up the fix.

**Comment by TurboGit** [comment]
We are probably messing with the alpha channel. @ralfbrown ?

**Comment by ralfbrown** [comment]
If **not** setting the alpha channel of the output of `dt_apply_transposed_color_matrix` fixes things, then some caller of a function which ultimately calls it is doing things in the wrong order....  (and may potentially lead to uninitialized-value problems elsewhere)
