### ISSUE TITLE
A better icon for "define shortcuts"?

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#9680]
About the new icon for "define shortcuts"

![immagine](https://user-images.githubusercontent.com/43290988/127678899-3b11a75f-32da-444c-8d32-ddeaad27f6ed.png)

On top of being too big and not balanced with the others, I don't think it is suggesting its purpose.

What about something like the following?

![immagine](https://user-images.githubusercontent.com/43290988/127679222-ccbeb05e-cdb1-4164-91d2-264a1ef7b86c.png)

Of course I can volunteer to redesign it

**Comment by johnny-bit** [comment]
Well... the "PLZ HALP" was right there from the start on the pr itself :P

However we have already an issue open https://github.com/darktable-org/darktable/issues/9483 so why not close this one and continue there?

I'm all for nicer icons & cursors :)

**Comment by Mark-64** [comment]
ok, closing here
