### ISSUE TITLE
Compilation error with lensfun 0.3.95

### ISSUE THREAD

**Issue by tankist02** [darktable-org/darktable#9684]
When I try to build latest darktable (master or 3.6.x branches) against lensfun 0.3.95 I get the following error:
[code]
In file included from /data/soft/darktable/build/lib64/darktable/plugins/introspection_lens.cc:85:
/data/soft/darktable/src/iop/lens.cc: In function ‘lfModifier* get_modifier(int*, int, int, const dt_iop_lensfun_data_t*, int, gboolean)’:
/data/soft/darktable/src/iop/lens.cc:346:92: error: no matching function for call to ‘lfModifier::lfModifier(const float&, int&, int&, lfPixelFormat, int)’
  346 |   mod = new lfModifier(d->crop, w, h, LF_PF_F32, (force_inverse) ? !d->inverse : d->inverse);
      |                                                                                            ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [lib64/darktable/plugins/CMakeFiles/lens.dir/build.make:82: lib64/darktable/plugins/CMakeFiles/lens.dir/introspection_lens.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5039: lib64/darktable/plugins/CMakeFiles/lens.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[/code]

**Comment by johnny-bit** [comment]
The 0.3.95 is an alpha release that breaks stuff, see https://github.com/darktable-org/darktable/issues/2813

maitaining compatibility with it is no-goal. instead see https://github.com/darktable-org/darktable/pull/9049 and @payano's work

**Comment by tankist02** [comment]
What are my options to have support for Nikon Z6? 

Thanks,Andrew

    On Friday, July 30, 2021, 2:14:40 PM PDT, Hubert Kowalski ***@***.***> wrote:  
 
 


The 0.3.95 is an alpha release that breaks stuff, see #2813

maitaining compatibility with it is no-goal. instead see #9049 and @payano's work

**Comment by payano** [comment]
Hi,
Could you try to build against the '2.0.0' version and my patch for darktable, 

Repos:
Darktable master branch
https://github.com/payano/darktable

Lensfun bump_ver branch
https://github.com/payano/lensfun/tree/bump_ver

I'm on vacation now and will fix this patch for the latest darktable release when I'm home again.

/Johan

**Comment by johnny-bit** [comment]
@tankist02 - you don't have to use 0.3.95 to have support for new bodies/lenses.

just use `lensfun-update-data` as describede in https://github.com/darktable-org/darktable/wiki/Camera-support#lens-correction

@payano - i hope your effort will be successfull and I do hope that lensfun lib will pick up steam :)

**Comment by tankist02** [comment]
Thank you for your advice, but it did not work out for me. Fedora 34 which I use has lensfun 0.3.2 and updating the database did not bring support for Nikon Z6.
BTW ART (fork of RawTherapee by Alberto Aggrigio) uses deprecated functions from lensfun 0.3.95 and everything works just fine, including corrections for Nikon Z6.


    On Saturday, July 31, 2021, 11:47:33 PM PDT, Hubert Kowalski ***@***.***> wrote:  
 
 


@tankist02 - you don't have to use 0.3.95 to have support for new bodies/lenses.

just use lensfun-update-data as describede in https://github.com/darktable-org/darktable/wiki/Camera-support#lens-correction

@payano - i hope your effort will be successfull and I do hope that lensfun lib will pick up steam :)

**Comment by payano** [comment]
Thanks @johnny-bit , I don't know if my version '2.0.0' will be merged but I'll try my  best :)
