### ISSUE TITLE
[dt 3.7.0] adding raster mask crashes darktable

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#9685]
**Describe the bug/issue**
Adding raster mask to module crashes darktable

**To Reproduce**

1. make some parametric mask on one module
2. open another module and add raster mask
3. darktable crashes 

See [darktable_bt_H3GA70.txt](https://github.com/darktable-org/darktable/files/6909975/darktable_bt_H3GA70.txt)

* darktable version : 3.7.0~git579.5c3444e43e-1
* Linux - Distro    : Kubuntu 20.04
* Graphics card     : GeForce GTX 1070
* Graphics driver   : 460.91.03
* OpenCL installed  : yes
* OpenCL activated  : yes
* Desktop           : KDE

**Comment by jade-nl** [comment]
Confirmed.

this is **darktable 3.7.0+583~g8aa6c7e5a**

Backtrace: [darktable_bt_5CQJ70.txt](https://github.com/darktable-org/darktable/files/6911287/darktable_bt_5CQJ70.txt)

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by ralfbrown** [comment]
Looks like `add_remove_mask_indicator` is called before the raster mask info is fully populated -- module->raster_mask.sink.source is NULL at the time of the crash.  I wasn't able to see in a quick scan where things are getting set, so it's likely some callbacks are involved; we may need to special-case things to **not** attempt to display the source module's name if the variable is NULL.

**Comment by johnny-bit** [comment]
additionally the tooltip isn't set up correctly in translatable way. it assumes that the flow of words would be the same eg: `_("this module has a")+" "+TYPE` and in case of raster mask it's `_("this module has a") + " " + TYPE +" "+ _("taken from") +" "+ MODULE`. I bet there are languages that wouldn't have the same order ;)
