### ISSUE TITLE
[FR] Use Sharp YUV for WebP export

### ISSUE THREAD

**Issue by pitbuster** [darktable-org/darktable#9686]
**Is your feature request related to a problem? Please describe.**
WebP export uses the default YUV conversion, which is not the best quality

**Describe the solution you'd like**
Use the Sharp YUV option for WebP exporting. As mentioned in the article below, it should be probably be the default and there is little reason to not use it (so it is probably not necessary to have a toggle for this).

**Additional context**
https://www.ctrl.blog/entry/webp-sharp-yuv.html

**Comment by parafin** [comment]
Is there some documentation on what “sharp YUV” actually is, on math level?

**Comment by pitbuster** [comment]
I couldn't find much documentation. From the source code, it seems that fast path uses a table to do the conversion faster but less accurrate: https://chromium.googlesource.com/webm/libwebp/+/refs/heads/main/src/enc/picture_csp_enc.c

**Comment by parafin** [comment]
Looks like it’s more complex and some filtering is used to produce sharper result, see this file too: https://chromium.googlesource.com/webm/libwebp/+/refs/heads/main/src/dsp/yuv.c
So I’m guessing it’s no longer 2x2 averaging as defined by the standard, but instead some higher order interpolation filter. One has to look out for things like halos and ringing when using this, I suspect, though usually it indeed should look better.

I have no opinion if enabling this is a good idea, I was just interested in technical details of RGB->YUV conversion.

**Comment by johnny-bit** [comment]
There's a "TODO" in code of webp export to expose more options to users so it might fall under just that - exposing more options (eg as an "advanced" expander)
