### ISSUE TITLE
Crash in dt 3.7.0 when moving mouse in tone equalizer

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#9688]
Recently I started getting consistent crashes with the latest dev versions of dt.

To reproduce:
- open an image in darkroom
- activate tone equalizer
- move mouse over the image (pointer turns into crosshair)
- move wheel to make a random adjustment (this step may not be necessary)
- move pointer towards the top edge of the image
- when pointer crosses top border dt freezes and dumps core

I get this behavior consistently with most images, both raw and jpg.
Also I tried with a fresh configdir and it still happens.

dt: 3.7.0~git586.ededff1666 provided by openSUSE
distro: openSUSE Tumbleweed
graphic: Integrated Intel
openCL: no
desktop: Plasma/KDE

[darktable_bt_PVFI70.txt](https://github.com/darktable-org/darktable/files/6911092/darktable_bt_PVFI70.txt)

**Comment by johnny-bit** [comment]
Managed to confirm it on current master. No adjustment necessary, just hit top edge of image and get crash :)

The problem according to my crash log is in :
```
#3  0x00007fd24017e1ca in get_luminance_from_buffer (buffer=0x7fd1c7637040, width=1350, height=<optimized out>, x=1078, y=0) at /home/johnny/darktable_repos/darktable/src/iop/toneequal.c:641
        y_abs = {18446744073709551615, 0, 1, 0}
        luminance = <optimized out>
#4  0x00007fd24019ad4a in mouse_moved (self=0x5557aa581000, x=<optimized out>, y=<optimized out>, pressure=<optimized out>, which=<optimized out>) at /home/johnny/darktable_repos/darktable/src/iop/toneequal.c:2003
        dev = <optimized out>
        g = <optimized out>
        fail = 0
        wd = 1350
        ht = 899
        pzx = 0.798759103
        pzy = 0.000787526369
        x_pointer = <optimized out>
        y_pointer = <optimized out>
        radius_threshold = <optimized out>
#5  0x00007fd2701d2f90 in mouse_moved (self=0x5557a920a2c0, x=995.85888671875, y=0.588287353515625, pressure=<optimized out>, which=0) at /home/johnny/darktable_repos/darktable/src/views/darkroom.c:3269
        dev = 0x5557a93a6250
        tb = <optimized out>
        capwd = <optimized out>
        capht = <optimized out>
        mouse_over_id = <optimized out>
        ctl = 0x5557a6f6e2c0
        width_i = <optimized out>
        height_i = <optimized out>
        offx = <optimized out>
        offy = <optimized out>
        handled = <optimized out>
#6  0x00007fd281685337 in mouse_moved (w=<optimized out>, event=0x5557aa762670, user_data=<optimized out>) at /home/johnny/darktable_repos/darktable/src/gui/gtk.c:1068
        pressure = 1
        device = <optimized out>
```

So - `toneequal.c` lin 641. Quick blame points to 5f17042 as offending commit (part of #9657)

@ralfbrown - can you take a look at what might've caused the issue?

[darktable_bt_9P9S70.txt](https://github.com/darktable-org/darktable/files/6911212/darktable_bt_9P9S70.txt)
