### ISSUE TITLE
Adding Y channel (luminance) to waveform/histogram 

### ISSUE THREAD

**Issue by sandyadr** [darktable-org/darktable#9694]
**Is your feature request related to a problem? Please describe.**
I've found it really helpful to have a Y channel in waveform/parade, especially when trying to set/match the luminance from one image to another (or when doing local colour/exposure correction).

**Describe the solution you'd like**
Having a recent discussion with @dtorop in #9170 about further scope variant, and the possibility of multiple scopes in a future version. It would be nice to have an additional Y channel, especially in waveform/Parade, so the channel option will be YRGB, Like in resolve or RT/ART.

**Additional context**
See #9170 about my though why it would be helpful when editing (based on my workflow in another software)

**Comment by dtorop** [comment]
I'd be happy to work on this. Probably best to wait until code settles down a bit.

The math here is to take RGB in histogram colorspace, convert it to XYZ, and draw the Y value...?

Is there a case in which we care about lightness rather than luminance? (E.g. convert to CIELuv and draw the L channel.) Not to divert this FR, but are there other "missing scopes" which would help with image work:

- luminance + chromaticity waveform/parade (YCbCr?)
- lightness + chroma (drawn vectorscope style to give a sense of a section through the image gamut)
- vectorscope "zoomed out" to see image laid into the full chromaticity diagram (spectral locus, purple line, white point, maybe Planckian locus)
- a 3D gamut drawing of the lightness/chromaticity within histogram colorspace
- an overlay of input, working, and output colorspace gamut triangles on the vectorscope

**Comment by sandyadr** [comment]
> Probably best to wait until code settles down a bit.

Yes, I think that's the best approach to avoid having to adopt the new code again later.

And now for the question, first of all, please noted that I'm not completely an expert in this topic, I only have a limited understanding from what I've read when I'm learning about colour correction and using software for editing(mostly photo, sometimes video), so I apologize beforehand if I used the wrong term here (especially Luma/Y', Luminance/Y, and Luminosity), and all my answer below is just from my understanding based on my (limited) experience, so CMIIW. Maybe someone else could fill in any missing information or corrects me.

> The math here is to take RGB in histogram colourspace, convert it to XYZ, and draw the Y value...?

I do not completely understand the math behind it for the histogram implementation, but if I understand it correctly from reading the dt documentation about luminance that it is "expressed by the Y channel of the CIE XYZ 1931 space", then maybe that is the right math here.

> Is there a case in which we care about lightness rather than luminance?

I'm not sure if I ever use software that shows lightness in their scope, but looking at the mask channel data on L or Jz channel, and imagining the scope output, I don't think it's that useful other than evaluating the scope for masking purposes.

> luminance + chromaticity waveform/parade (YCbCr?)

I've never seen an image editing software having this scope, only on video grading software, and rarely see anyone use it (other than the Y channel), but maybe the reason that it is needed on video software is for evaluating the data for legal broadcast value because the video is transmitted in YPbPr.

> lightness + chroma (drawn vectorscope style to give a sense of a section through the image gamut)

I'm not sure about the visual of this scope, do you have any reference/example?

> a 3D gamut drawing of the lightness/chromaticity within histogram colorspace

I think I've seen something similar in LUT editing/creation software, but in image/RAW editing software,  is it the most effective scope to inspect (out of) gamut data? How about the balance between usefulness and performance drawback of having 3D element (i assume we could rotate the 3D object (cube?)). 

but

> - vectorscope "zoomed out" to see image laid into the full chromaticity diagram (spectral locus, purple line, white point, maybe Planckian locus)
> - an overlay of input, working, and output colorspace gamut triangles on the vectorscope

If I correctly assume that it is similar to resolve CIE 1931 xy scope, isn't it the more effective way to inspect the gamut data? An overlay of input/working/output colourspace gamut on top of spectral locus.

All in all, personally I already think darktable have more than enough scope variant for image editing (compared to most image editing software), I'm more concerned about optimizing it to have a more fluid workflow (more scope options, the interaction/integration between colour picker and the scope, etc). The additional scope is always more than welcome if it helps to inspect and/or evaluating problems within an image.

Sorry for the long comment, and thanks!
