### ISSUE TITLE
Retouch module error in darktable 3.7.0~git586.ededff1666-6359.1

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#9695]
**Describe the bug/issue**
I updated to darktable 3.7.0~git586.ededff1666-6359.1 and got this visualization error with the retouch module.
at different resolutions (100% & 200%) darktable shows similar behavior.

**Expected behavior**
The usual expected behavior of the retouch module.

**Screenshots**
in darkroom

![Screenshot-20210731120706-2896x1860](https://user-images.githubusercontent.com/67672868/127746539-766f8126-0015-451b-8ace-6f37da173825.png)

In Lighttable
![Screenshot-20210731120800-2896x1860](https://user-images.githubusercontent.com/67672868/127746652-62f087bf-3479-4929-b5e8-96b4c2b8d5e9.png)

**Platform**
darktable 3.7.0~git586.ededff1666-6359.1
bit depth is 64 bit
normal build
SSE2 optimized codepath enabled
OpenMP support enabled
OpenCL support enabled
Lua support enabled, API version 8.0.0-dev
Colord support enabled
gPhoto2 support enabled
GraphicsMagick support enabled
ImageMagick support disabled
OpenEXR support enabled

OS: Fedora 34 (Workstation Edition) x86_64
Host: Z390 AORUS MASTER
Kernel: 5.12.17-300.fc34.x86_64
Uptime: 1 hour, 14 mins 
Packages: 3116 (rpm), 8 (flatpak), 12 (snap) 
Shell: zsh 5.8 
Resolution: 3840x2160
DE: GNOME 40.3
WM: Mutter
WM Theme: Materia-dark-compact
Theme: Mojave-dark [GTK2/3] 
Icons: Os-Catalina-icons-master [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 2219MiB / 32037MiB
Graphics driver : 460.73.01
OpenCL installed : yes
OpenCL activated : yes

**Comment by jade-nl** [comment]
Confirmed.

Only seems to happen when you are using the *wavelet decomposition* section.

* darktable 3.7.0+593~g2f8a3ac87

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by sandyadr** [comment]
Confirmed.

This happens even without using wavelet decompose.

- darktable-3.7.0+601_gf0e6c14fb (windows insider program 8/1)
- darktable-3.7.0+705_g0978979e7 (win10 build incl. cr3 support)

Last version without this problem
- darktable-3.7.0+620_g74ad7ea3f (win10 build incl. cr3 support)

Platform

- OS : Windows 10 
- Graphics driver : nvidia (465.89)
- OpenCL installed : Yes
- OpenCL activated : Yes

**Comment by johnny-bit** [comment]
Can you try and bisect the issue? https://github.com/darktable-org/darktable/pull/9553#issuecomment-895583004 looks like that might be the cause.

**Comment by johnny-bit** [comment]
Please test #9799 and report back :)

**Comment by sandyadr** [comment]
Yes this fixed for me too. sorry if it's late, just test it on the latest win10 build with cr3 support.

**Comment by difrkaguilar** [comment]
Great job guys!!! Everything works perfect now on Fedora. I'm without words to express my gratitude!!.
Thanks a Lot!.
