### ISSUE TITLE
Masking is disabled in LAB color space

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#9699]
**Describe the bug/issue**

Both parametric and drawn masks _do not work_ for modules in _LAB color space._

Here is an example with contrast equalizer. **LAB** color space:

![Masking1](https://user-images.githubusercontent.com/38165484/127763839-3411f8ab-59fd-49ac-8b66-1ed12b00eb85.jpg)

**RGB** (display and scene):

![Masking2](https://user-images.githubusercontent.com/38165484/127763865-601e8174-3cb9-4a50-9588-131b07d56944.jpg)

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Enable a module that works in LAB color space
2. Create a drawn and/or parametric mask
3. Mask is not shown/created
4. Switch to another color space - RGB (display or scene)
5. Mask is displayed and created

**Expected behavior**

Mask should be able to be displayed and created in any color space

**Platform**

- darktable version : 3.7.0~git599.6ddf273212-1
- Linux - Distro : Kubuntu 20.04
- Graphics card : GeForce GTX 1070
- Graphics driver : 460.91.03
- OpenCL installed : yes
- OpenCL activated : yes
- Desktop : KDE

**Comment by TurboGit** [comment]
@s7habo : Can you bisect to find the first bad commit that has introduced this? TIA.

**Comment by s7habo** [comment]
Thanks for your feedback!

> Can you bisect to find the first bad commit that has introduced this? TIA.

I am not sure how to do that. I don't compile the darktable but use ppa repository for master branch offered here:
https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

But I'm pretty sure this issue belongs to this issue here:
#9676
and maybe someone there can help.

**Comment by jade-nl** [comment]
@s7habo : Done :wink:
