### ISSUE TITLE
no way to define timezone for gpx file anymore

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#9702]
**Describe the bug/issue**
geotaggging using a gpx file does not work anymore, because I can't define the correct timezone.

- current timezone: Europe/Vienna (UTC+1:00) + daylight saving time -> 2 hours difference between UTC and local time
- in earlier versions of dt I could define the timezone of the gpx-file in the file-dialog-window
- the field 'camera time zone' seems to only affect the section to apply the offset, but has no effect on the 'gpx file' section

**To Reproduce**
1. open map view
2. open geotagging module
3. add gpx file
4. no matching image
5. mouseover shows no difference between localtime and UTC
(see screenshot in red)

**Screenshot**
![image](https://user-images.githubusercontent.com/5677563/127783440-cc3f336a-a445-41ac-be88-7d5427062e44.png)

**Expected behavior**
- possibility to define time zone of the gpx file

**Platform**

* darktable version : 3.6.0
* OS                : Linux
* Linux - Distro    : Manjaro
* Desktop           : gnome

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes with latest master**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by TurboGit** [comment]
@phweyland : Probably something for you, can you have a look? No urgency. TIA.

**Comment by quovadit** [comment]
I found the problem:

When entering a timezone in the field 'camera time zone', it won't get saved unless you press 'Return' after selecting the entry_completion value.

I just clicked on 'Europe/Vienna' after entering 'vienna', and then clicked on 'select a GPS track file...'.

Is there a (simple) way to save the entered value as soon as it gets selected, or should I just clarify dtdocs?

**Comment by phweyland** [comment]
> it won't get saved unless you press 'Return' after selecting the entry_completion value.

That's correct. I remember that I had not felt this perfect, but I didn't found the way to enter the clicked value in the list.
This said, this is the general behavior of completion across dt (tags, metadata, ...).

**Comment by quovadit** [comment]
I understand.
The difference with applying tags is, that I see that nothing happens until I double-click on the tag again.
When entering the timezone, I have no indication, that the chosen value is not saved yet (see screenshot).
So maybe we could add a 'not saved yet' indicator next to the field (*), which changes to a 'saved' indicator (✓) when saved.

**Comment by phweyland** [comment]
Humm, I've a bit different display as long as I haven't hit enter (the list component is still there, indicating the action is not yet complete):
![image](https://user-images.githubusercontent.com/23012047/128258924-21fbc185-12c6-47ce-9f62-138be83a067c.png)

But I agree.  Even if I don't see this as bug, that is not completely cool. Not sure we can change this, between the click on an element of the list and hit enter, the completion mechanism does everything... If you have an implementation idea, it's welcome :).
