### ISSUE TITLE
Ricoh GR III not detected by denoise (profiled) module

### ISSUE THREAD

**Issue by grattus** [darktable-org/darktable#9706]
**Bug description**
The denoise (profiled) module fails to detect images taken with the Ricoh GR III while support has been added in June (commit e7e02aefb785cfe14adf82ad9689ae0731c9269f). I assume that this comes from [noiseprofiles.json](https://github.com/darktable-org/darktable/blob/master/data/noiseprofiles.json) indicating `"model": "RICOH GR III",` instead of `"model": "GR III",`. Samples were initially provided in issue #9099

**Platform**
- OS: Fedora 34
- Darktable version : 3.6

**Comment by Nilvus** [comment]
@rawfiner: probably for you!

**Comment by johnny-bit** [comment]
I've re-assigned to me and corrected the name in noiseprofiles without changing anything else. The #9938 should fix this issue which is the last issue tagged with 3.6.1 milestone
