### ISSUE TITLE
Copy & Import: file paths non correctly managed under Windows

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#9707]
I can't make the new function Copy & Import work correctly in DT 3.6 under Windows.

In the dialog, under "base directory naming pattern", if I put a variable, for example

![immagine](https://user-images.githubusercontent.com/43290988/127886952-d97c61b9-51f9-4709-a6f7-5601b8ebc564.png)

then the pictures are copied and imported in the database correctly, but the film roll name is including the picture folder name and a slash, which is incorrect

![immagine](https://user-images.githubusercontent.com/43290988/127886883-df8c6646-a96f-45d7-9954-31fe05c34419.png)

If instead, I put the absolute path

![immagine](https://user-images.githubusercontent.com/43290988/127887445-d7ef84e0-264e-426d-922a-9fb488818332.png)

the the pictures are copied correctly, but not imported in the database

![immagine](https://user-images.githubusercontent.com/43290988/127886433-cee9a587-aac8-4b92-81b0-873dbd510241.png)

See in the error message that the backslash in E:\Immagini is removed.

I guess Windows file paths need some sanification.

**Comment by wpferguson** [comment]
#9630 is a related issue.  The whole windows drive/UNC/file chooser support on windows is a mess.

**Comment by Mark-64** [comment]
Here it seesm more an issue related to strings, estracted from the file paths, which are put in the database. 
Files are copied, but not imported or imported with incorrect attributes.
I will have a look to the code in the coming days and if I need help I'll let you know.

**Comment by wpferguson** [comment]
Tested copying and importing from a network drive and nothing was copied and nothing was imported (but that may be a different bug).  I'll set up another local drive and try that.
