### ISSUE TITLE
lighttable: collection module height cannot be adjusted when in folder view

### ISSUE THREAD

**Issue by 01McAc** [darktable-org/darktable#9708]
In my folder view in lighttable there are heaps of folders I imported to dt. I can only see a tiny bit of them as the module is too small. So there is actually more to display. Issue: _Ctrl+Scroll mouse doesn't work when in folder view_ but it does work when in film roll view. See #1 in screenshot 
![Screenshot_20210802_154934](https://user-images.githubusercontent.com/88337479/127890609-b97af715-7c7e-48c9-9bb1-158bae962ee5.jpg)

**Comment by TurboGit** [comment]
I cannot reproduce this.

**Comment by TurboGit** [comment]
@elstoc : How did you reproduced?

**Comment by TurboGit** [comment]
AFAIK we are not rewriting the collection module but the collection filtering (a new lib module).

**Comment by elstoc** [comment]
@TurboGit see [this comment](https://github.com/darktable-org/darktable/pull/10733#issuecomment-1015826610). That PR's changes have already impacted the Ctrl+scroll functionality.

**Comment by TurboGit** [comment]
Indeed, anyway since I cannot reproduce let's close this for now.
