### ISSUE TITLE
Lua bug: register_storage_initialize sends a 0 as image, get_tags sends a 0 tag

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#9715]
------------------------

**Describe the bug/issue**

dt.register_storage's initialize function (described on https://darktable-org.github.io/luadocs/lua.api.manual/darktable/darktable.register_storage/#initialize ) should handle a table of dt_lua_image_t as its images (3rd) argument, but one of the values in that table is zero.

Moreover, one of the tags returned by dt.tags.get_tags(image) is 0 as well (thus it's not a tag and doesn't have a name attribute).

**To Reproduce**

Export an image in Lua using dtMediaWiki, use the register_storage function and get an image's tags, or the custom script provided below to export an image and look for the caught "BUG" and the actual Lua error: 

[debugexport.lua.txt](https://github.com/darktable-org/darktable/files/6923752/debugexport.lua.txt)

rename to debugexport.lua, place in .config/darktable/lua/contrib/, and add 'require "contrib/debugexport"' to ~/.config/darktable/luarc

**Expected behavior**
Images should all be dt_lua_image_t, tags returned by get_tags should be tags with a name attribute. Not 0.

**Screenshots**
![scrn-2021-08-03-13-35-50](https://user-images.githubusercontent.com/6899116/128008909-fced4658-52af-442f-9c6a-c0ecf568592b.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.7.0+639~g18a0a99832
* OS                : e.g. Arch Linux
* Memory            : 176 GB
* Graphics card     : Nvidia GTX 1070 + Radeon 56
* Graphics driver   : official
* OpenCL installed  : yes
* OpenCL activated  : yes, AMD
* Xorg              : Wayland
* Desktop           : Sway
* gcc               : 11.1.0
* CMAKE_BUILD_TYPE  : std, https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=darktable-git

**Additional context**
_Please provide any additional information you think may be useful, for example:_
See the reproduction script above.

 - Can you reproduce with another darktable version(s)? not tried but dtMediaWiki worked previously
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both** Tried raw
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? Not tried because need luarc to activate scripts
 - Do you use lua scripts? Yes
   - What lua scripts start automatically? 
require "tools/script_manager"
require "contrib/dtMediaWiki/dtMediaWiki"
require "examples/gettextExample"
require "contrib/debugexport"

**Comment by wpferguson** [comment]
The darktable Lua API table generation code (most/all?) relies on a behavior that worked fine in Lua 5.2 and 5.3,  but was never guaranteed to work, and Lua 5.4 breaks the behavior.  A quick work around is to check if the index of the table matches the size of the table and break the loop if it does.  In the meantime, I'll start finding all the places that ipairs tables are generated and returned, and fixing the code.

**Comment by wpferguson** [comment]
Depending on the way the lua5.4 package is built, a user may or may not see these types of errors.  I've had a tough time recreating them, but I built my lua5.4 package early on and built it the way that Ubuntu does, i.e. take the download package from the source and build it as shipped, which in this case means with the -DLUA_COMPAT_5_3 flag in the Makefile.  If your lua is built that way, then when you dump a table of tags from the API it looks like this
```
8.648742 LUA processing image 1 with filename PICT2002.tif
lua table at index 2 at dt_lua_tag_get_attached:253 (length 11.000000)
1.000000 - userdata
2.000000 - userdata
3.000000 - userdata
4.000000 - userdata
5.000000 - userdata
6.000000 - userdata
7.000000 - userdata
8.000000 - userdata
9.000000 - userdata
10.000000 - userdata
11.000000 - userdata
8.649212 LUA key is 1 and val is darktable|format|tif
8.649289 LUA key is 2 and val is beach
8.649347 LUA key is 3 and val is sunrise
8.649409 LUA key is 4 and val is Australia
8.649471 LUA key is 5 and val is Australia|New South Wales|Tabourie Lake
8.649539 LUA key is 6 and val is New South Wales
8.649598 LUA key is 7 and val is Tabourie Lake
8.649654 LUA key is 8 and val is holiday
8.649714 LUA key is 9 and val is pano source
8.649769 LUA key is 10 and val is panorama
8.649809 LUA key is 11 and val is panorama|pano source
```
and the userdata is strings (tag names).

If you don't have the compatibility flag then this is the result
```
12.542460 LUA processing image 1 with filename PICT2002.tif
lua table at index 2 at dt_lua_tag_get_attached:253 (length 12.000000)
1.000000 - userdata
2.000000 - userdata
3.000000 - number
4.000000 - userdata
5.000000 - userdata
6.000000 - userdata
7.000000 - userdata
8.000000 - userdata
9.000000 - userdata
10.000000 - userdata
11.000000 - userdata
12.000000 - userdata
12.543068 LUA key is 1 and val is darktable|format|tif
12.543187 LUA key is 2 and val is beach
12.543792 LUA ERROR : /home/bill/.config/dttesttables/lua/test/test_tags.lua:8: attempt to index a number value (local 'val')
```
Notice how value number 3 is a number instead of a string.  This is what happens when you use luaL_ref() to build tables instead of lua_seti or lua_rawseti in lua 5.4.

The good news is that I've built lua 5.4 without the compatibility flags so now I can recreate all the crashes on my main system instead of in a VM.

**Comment by trougnouf** [comment]
That was fast! I confirm the numerical values are gone. Thank you @wpferguson for the excellent work.
