### ISSUE TITLE
Lightable not showing progress for long operation - bulk style apply

### ISSUE THREAD

**Issue by rrroonn** [darktable-org/darktable#9724]
Darktable 3.6.0 Linux (Mint) 

**Describe the bug/issue**

I imported a lot of photos and the jpegs had "Lens correction" turned on which affected some images where the camera was recognised but, because they were JPEGs, any correction would have already been applied.

I created a filter that has only the "Lens correction" module - and turned off. 
I used the collections side filters to select affected JPEGS - about 2500.  
I selected all images and applied the style in "append" mode.  
It appeared as if nothing happened though the interface became unresponsive.  The whole process too around a minute and I monitored progress via the System Monitor app.

A progress dialog or similar visual indicator should be considered.

**Comment by MStraeten** [comment]
what do you mean with ‚jpegs had „lens correction“ turned on‘? Did you apply a style with that setting?
Applying a style to a whole bunch of images in lighttable causes a recalculation of the thumbnails. Depending on the power of your machine this can take time and resources…
It’s up to the system to indicate this (on osx it’s a rotating ball)

**Comment by ralfbrown** [comment]
One issue is that when changing histories or metadata, **all** affected XMP files get written in a foreground loop, so the GUI doesn't get back control until that process finishes. See `dt_image_synch_xmps` in src/common/image.c.

Moving the sidecar writes into a background job has been on my to-do list for a few months, see #8909.

**Comment by rrroonn** [comment]
> what do you mean with ‚jpegs had „lens correction“ turned on‘? Did you apply a style with that setting?

I think it was auto-applied on import ...  I am just getting over dumping Windows and Adobe and ramping up Linux Mint and Darktable, so my recollection of exactly why this was applied is hazy.  Possible operator error?  Not really the point of the issue though :-)

> Applying a style to a whole bunch of images in lighttable causes a recalculation of the thumbnails. Depending on the power of your machine this can take time and resources…

Yes

> It’s up to the system to indicate this (on osx it’s a rotating ball)

Yes and no.  I did it twice just to be sure I didn't miss a hidden indication of background activity.  No hour glass etc.   But, blame and/or responsibility aside, user experience is what counts.  One could question whether any potentially long running task should be done in the UI thread and what impact that would have on the user experience - hour glass or no hour glass...  just my 10 cents.

**Comment by rrroonn** [comment]
> Moving the sidecar writes into a background job has been on my to-do list for a few months, see #8909.

Yes, moving to background threads would fix this issue.
