### ISSUE TITLE
Apple iPhone 12 Pro Max DNG File Support.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#9725]
I try to import two DNG files from iPhone 12 in darktable, in the import window the preview show the files but after import show this message:

![Screenshot-20210803162437-2477x414](https://user-images.githubusercontent.com/67672868/128105438-cfd02388-38ef-40d6-9e69-67a5cab78397.png)

I leave an image as reference.

[IMG_2611.ZIP](https://github.com/darktable-org/darktable/files/6927863/IMG_2611.ZIP)

This file is licensed [Creative Commons, By-Attribution, Share-Alike](https://creativecommons.org/licenses/by-sa/4.0/).

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/7578

**Comment by johnny-bit** [comment]
Please follow #7578
