### ISSUE TITLE
Better comparison option of 4 ways tab in color balance RGB

### ISSUE THREAD

**Issue by B-Souty** [darktable-org/darktable#9727]
**Is your feature request related to a problem? Please describe.**

Using `Color Balance RGB` instead of `Color Balance` to color grade makes it harder to see a before/after without also changing settings from the master tab.

**Describe the solution you'd like**

I would love an on/off switch in the `4 ways` tab to better see the change from my color grading only. Even better if this could somehow create a dedicated history step to be able to use snapshots as well.

**Comment by MStraeten** [comment]
Why not use two instances of the module?

**Comment by B-Souty** [comment]
Because it feels silly using 2 instances, one for each tab. Why not leave it as 2 separate modules in that case? What was the reasoning for moving `Color balance` into `Color balance RGB`?

**Comment by MStraeten** [comment]
That’s not silly at all, thats the key concept and strength of darktable: do different things in different modules. If there’s no dependency there’s no need to just use one module instance

**Comment by B-Souty** [comment]
>do different things in different modules

Sure, if I want to apply different settings of a same module to different part of the image, that makes perfect sense. If I want to apply a module globally using complementary tabs of said module, having to create separate instance just to be able to do an easy before/after seems a bit silly. 

With that said, I realized I could simply create a snapshot before altering the `4 ways` tabs so I guess that will be enough for now. I wish I would just understand the reasoning behind adding this tab to `color balance RGB` instead of using the old dedicated `color balance` module

**Comment by johnny-bit** [comment]
There's another "workaround":
1. adjust global settings & create preset from them
2. adjust 4-ways tab and create preset from global+4ways adjustment
3. switch between preset from 1 and 2 to compare.

> I wish I would just understand the reasoning behind adding this tab to color balance RGB instead of using the old dedicated color balance module.

color balance rgb is whole new module with new maths and so on. 

> I still believe it would be nice to have a toggle to easily see the changes of the 4 ways tab though.

It's complex change that would necessitate some kind of temporary storage of params & restore them... 
Another similar request is in #7480 for different module.

No dev has yet picked up this because it's quite complex backend wise and IMO hard UI-wise.
