### ISSUE TITLE
Retouch module isn't saving wavelet edits

### ISSUE THREAD

**Issue by fkhawajagh** [darktable-org/darktable#9730]
When I create wavelet scales in the retouch module, I can make edits and they display on the screen.  However, when I export the image, none of the wavelet scale changes are exported.

If I only make changes to scale 0, those edits are exported fine.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to retouch module
2. Click on "Wavelet Decompose" and create 1 scale
3. make some edits
4. export the file to any format

The exported file doesn't contain any edits done in the scales.

**Expected behavior**
All edits should be exported matching what's on the screen.

**Screenshots**
<img width="347" alt="Screen Shot 2021-08-04 at 9 24 16 PM" src="https://user-images.githubusercontent.com/42197057/128276520-1b9ed9fc-de12-4670-b346-c6f25332553e.png">
<img width="342" alt="Screen Shot 2021-08-04 at 9 24 26 PM" src="https://user-images.githubusercontent.com/42197057/128276532-c44f8d82-ccd6-4cc0-a71b-dc66eee8411e.png">

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.6.0+3~g4287791fe
* OS                : MacOS (Big Sur) 11.2.3
* Memory            :  16GB
* Graphics card     :  AMD Radeon Pro 5500M 4 GB Intel UHD Graphics 630 1536 MB
* Graphics driver   : 
* OpenCL installed  : No
* OpenCL activated  : No
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with a RAW or Jpeg or both? I'm using a TIFF file as original
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)?  Yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 
[CTP06457_02.tif.txt](https://github.com/darktable-org/darktable/files/6935376/CTP06457_02.tif.txt)

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes
 - Do you use lua scripts?  No
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by TurboGit** [comment]
Cannot reproduce.

**Comment by TurboGit** [comment]
You have a 4 steps reproducer but on the screenshot I see also that you are using parametric masks. Please be coherent in your report to help finding the possible cause.
