### ISSUE TITLE
Inconsistent handling of path-relative command line arguments in presence of symlinks

### ISSUE THREAD

**Issue by chrysn** [darktable-org/darktable#9734]
(For context, this describes an issue I'm having when using darktable with [git-annex](https://git-annex.branchable.com/), whose setup makes the kind of symlink farm described plausible, and which is commonly used as a more powerful alternative to git's large file support (git-lfs). For easy reproducibility I've turned my setup into a minimal example, which makes less sense on its own but should be easier to work with).

When faced with a symlink file whose target has no recognized image extension, darktable behaves differently depending on whether it is invoked with the file given in relative or absolute form.

Full example:
```sh
$ mkdir /tmp/darktable-import-test
$ cd /tmp/darktable-import-test
$ mkdir data
$ mkdir second
$ gm convert rose: data/test.tif      # create an example image
$ mv data/test.tif data/test
$ cd second
$ ln -s ../data/test test.tif
$ tree ..                # for illustration
..
├── data/
│   └── test
└── second/
    └── test2.tif -> ../data/test
$ darktable test.tif            # does not open anything
$ darktable $PWD/test.tif       # opens the file
```

This is inconsistent, and confusing to users accustomed to starting `program file`. They may come to assume from this behavior that darktable can not accept files from the command line at all, and only ever accepts images into its data base using the import process. The observed behavior is typically only visible to command line users, as "opening a file from the file manager" typically passes the full path to the to-be-opened application.

This was tested with darktable 3.6.0 as packaged in Debian experimental. The file extension part seems to be relevant because if the target has the same .tif extension, darktable would attempt to write in the data directory (a behavior which I strongly dislike, but that's a different story).

**Comment by chrysn** [comment]
(To avoid runnign into issues with things in the database, I've later tried this again with `--library :memory` in the original git-annex setup, which is probably helpful for reproducing as it avoids any effects of imports that happened on the last test).

**Comment by UweOhse** [comment]
The culprit is dt_util_normalize_path(), which behaves differently if called with test.tif and /somewhere/second/test.tif:

```
  if(g_path_is_absolute(filename) == FALSE)
  {
    char *current_dir = g_get_current_dir();
    char *tmp_filename = g_build_filename(current_dir, filename, NULL);
    g_free(filename);
    filename = g_realpath(tmp_filename);
    if(filename == NULL)
    {
      g_free(current_dir);
      g_free(tmp_filename);
      g_free(filename);
      return NULL;
    }
    g_free(current_dir);
    g_free(tmp_filename);
  }
```
In case of a relative file name realpath() is called, which returns /somewhere/data/test (without an extension, which is something other parts of darktable do not like).

It certainly wrong that only one code path calls realpath.
I suggest to drop the g_realpath call completely, and return the tmp_filename, because i darktable should put the XMP file at the place i gave to the program.
