### ISSUE TITLE
Square is not a square when exported

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#9738]
**Describe the bug/issue**
When exporting an image that has been cropped to aspect ratio 1:1 with the crop the result is not a square, the other side is one pixel off.

**To Reproduce**
1. Open an image
2. Crop image to 1:1, keeping the full height
3. Return to darkroom
4. Export image full sized image

**Expected behavior**
Both sides are equal.

**Screenshots**
![image](https://user-images.githubusercontent.com/18402158/128409111-7b32cb1f-f5b7-4522-b854-03daa4772a51.png)

![image](https://user-images.githubusercontent.com/18402158/128409441-342c24ba-a34f-4bee-af2b-11f94e4fb8c7.png)

**Platform**
* darktable version : 3.6.0.1
* OS                : Windows 10
* OpenCL       : no impact

**Additional context**
The same error occurs also in my virtual Ubuntu (21.04) and in Windows with the latest master (3.7.0+649).

There are no modules with geometric transformations applied (e.g. crop & **rotate** or lens correction).

This looks similar as error #7465

**Example file**
[2021_07_30.zip](https://github.com/darktable-org/darktable/files/6941199/2021_07_30.zip)

**Comment by juhavlintula** [comment]
I tested also the official 3.6.0 build and it also creates the one pixel error.

**Comment by amousset** [comment]
Reproduced with example file on current master.

**Comment by amousset** [comment]
The value is incorrect in image information

![d](https://user-images.githubusercontent.com/329388/140668110-1077c3f3-5a12-4169-a246-94302705df62.png)

**Comment by amousset** [comment]
This seems to happen because of the rounding in https://github.com/darktable-org/darktable/blob/ea953bfdc100df4ba37b9d6a3a7fbd14f32de285/src/iop/crop.c#L306 (so the ratio is only incorrect at some specific crop settings).

**Comment by MStraeten** [comment]
reproduced with osx - i found it can be even more than 1 pixel even if exporting without scaling (keep width and height =0)

**Comment by vrabiutz** [comment]
Same issue on version 3.8.1 (Ubuntu 20.04).

**Comment by Nilvus** [comment]
I've tested on actual master with few square images and can't reproduce. I have same size on exported one in height and width but code pointed above by @amousset is still there. So if one of people here who have seen the issue, could you precise if you can still reproduce on actual master or not?

**Comment by MStraeten** [comment]
current master: 1:1 crop 2601x2601 displayed on the image, export size: 2600x2599

![image](https://user-images.githubusercontent.com/39386816/205732831-ae355b14-c503-41ff-b356-7458aeffe400.png)

**Comment by Nilvus** [comment]
@AlicVB: if you have some time, this issue seems related to crop on some case. See @amousset comment above with a possible related line in crop.c file

**Comment by juhavlintula** [comment]
I tested this with the same image I have in the bug report and with a recent master (4.1.0+1023~g7cbd85371) on Win11. I got interesting results:
1. when I exported the image as-is the dimensions were 3911×3912
2. when I opened the crop module and moved the crop area, and moved it back to exactly the same place, the exported dimensions were 3911×3911

**Comment by TurboGit** [comment]
Closed !
