### ISSUE TITLE
Diffuse or sharpen: large number of iterations results in exaggerated sharpness in jpg

### ISSUE THREAD

**Issue by billmartz** [darktable-org/darktable#9749]
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

When a jpg is exported when the number of iterations in diffuse or sharpen is high, the degree of sharpening in the jpg is noticeably greater than what is shown in the edited image in darkroom.

![image](https://user-images.githubusercontent.com/46618108/128574071-20bdf6f7-cc55-4b8e-9a1d-1af958690173.png)

darkroom screenshot
![iBn 12 103 iterations image in darkroom ](https://user-images.githubusercontent.com/46618108/128574667-6a2f0bb4-7334-446d-8acc-d59834ee0cfa.jpg)

jpeg
![iBb_12 RW2 xmp _04 103 iterations ](https://user-images.githubusercontent.com/46618108/128574225-d744dac5-4c88-4504-af84-fa97e3300d3d.jpg)

iBb.RW2 is available at:
https://discuss.pixls.us/t/raw-sharpness-with-darktable/21315/112

My sidecar:
[iBb_12.RW2.txt](https://github.com/darktable-org/darktable/files/6948113/iBb_12.RW2.txt)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : darktable-3.7.0+649~g33bf47877-win64
* OS                : Windows 10 Pro, version 20H2
* Memory            : 32 GB
* Graphics card     : NVIDIA GeForce GTX 1070 
* Graphics driver   : Driver version: 457.51
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / Didn't try**
 - Can you reproduce with a RAW or Jpeg or both? **Saw same behavior with another RW2; although, it was not quite as obvious as with the beard.**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **Didn't try**
 - Do you use lua scripts? No
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by todd-prior** [comment]
What setting do you have for your preview...there is one performance over quality and a few others....could it be something there that contributes to the discrepency??

**Comment by billmartz** [comment]
I have prefer performance over quality unchecked, demosaicing for zoomed out darkroom mode at full, and reduce resolution of preview image at original.

**Comment by billmartz** [comment]
I get the same effect with the jpg I made of yteaot's xmp from https://discuss.pixls.us/t/color-calibration-guidance-needed/26518/22.
