### ISSUE TITLE
ILCE-7RM4A support and Darktable crashes

### ISSUE THREAD

**Issue by domosbg** [darktable-org/darktable#9751]
Hello,
I'm new to github. So please correct me, if I have done something wrong by posting my issue.

First of all I would like to ask if it would be still helpful to upload some pictures from the ILCE-7RM4A to https://raw.pixls.us/.
It was discussed here in this post: #9347, but I couldn't find pictures from the camera in the repo. If it helps, i would try to upload some pictures.

Now to the issue report:
Doing the same as described in #9347 the same error message appears ("darktable could not load...."). But after around 10 to 15 seconds after opening the picture in the dark room, Darktable crashes.

The Backtrace of the crash can be found here:
[darktable_bt_JZ4660.txt](https://github.com/darktable-org/darktable/files/6948750/darktable_bt_JZ4660.txt)

Darktable crashes on every picture done with the camera. After applying the workaround provided by kmilos in #9347 (editing the cameras.xml file) everythings works fine, no crash. 

**Platform**

* darktable version : 3.6.0.1
* OS                : Windows 10 (10.0.19042.1110)
* Memory            : 16 GB
* Graphics card     : Geforce RTX2070 + Intel UHD Graphics 630
* Graphics driver   : 430.81
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by kmilos** [comment]
Please [upload a sample to RPU and open a formal camera support request](https://github.com/darktable-org/darktable/wiki/Camera-support).

That was just a temporary workaround.

**Comment by LebedevRI** [comment]
Awaiting upload to RPU.

**Comment by domosbg** [comment]
I uploaded 3 files to RPU. But i can't find them in their repository. Can it take a while until it is shown?
Uploaded 12 bit compressed, 14 bit compressed and uncompressed. 12 bit uncompressed is only taken by the camera in BULB mode or if long exposure is activated. That's not so easy for me to do. Is a picture in 12 bit uncompressed neccessary for the full support of the camera?

**Comment by johnny-bit** [comment]
@domosbg - in order for us to support the camera we need all the types of files camera can produce.

**Comment by LebedevRI** [comment]
> I uploaded 3 files to RPU.

Thank you. I guess this will do.

**Comment by domosbg** [comment]
@johnny-bit @LebedevRI I finally was able to make a picture with 12 bit uncompressed and uploaded it to RPU. Hope it is usable and helps supporting the camera.
Thanks a lot for your work.

**Comment by LebedevRI** [comment]
Thank you!

**Comment by domosbg** [comment]
@LebedevRI Have you already had a chance to take a look at the pictures? Just want to know if they are usable for adding camera support.

Can the noise profile, white balance preset and lens corrections taken from the ILCE-7RM4? Only the monitor at the back has changed from ILCE-7RM4 to ILCE-7RM4A (higher resolution), so there should be no difference in the camera parts which are responsible for taking the picture. There could only be changes in the firmware of the camera versions which could influence the picture processing.
