### ISSUE TITLE
Wrong warning for demosaic module

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#9753]
DT 3.6, Windows 10.

In certain cases I get a wrong warning in demosaic module "disabled as not appropriate"

![immagine](https://user-images.githubusercontent.com/43290988/128603689-bb738712-cc77-474f-b263-68046448d556.png)

but the image is a raw and the module is actually activated.

To reproduce:
1) import some raw and tif files in a collection
2) click on a raw file to enter darkroom
3) expand demosaic module
4) click on a tif file in the filmstrip. See the warning "disabled as not appropriate". This is correct
5) now click back on the raw file. The warning stays on. This is wrong

**Comment by aurelienpierre** [comment]
That would be consistent with other inconsistencies I have seen in color calibration. It seems that the pipeline init (supposed to trigger the `reload_defaults()` that init the default settings and the validity self checks) fails sometimes. As you said, it's hard to reproduce, which usually means race conditions somewhere.

**Comment by jenshannoschwalm** [comment]
I believed this to be fixed via #9583, currently can't reproduce here.

**Comment by Mark-64** [comment]
Indeed it seem fixed in master.
closing
