### ISSUE TITLE
Feature request: "Expand/collapse all" in collections module tree

### ISSUE THREAD

**Issue by salmo6** [darktable-org/darktable#9754]
I usually organize my photos with nested tags in lighttable view. In the left panel, this creates a tree of tags, from which I can select the group of photos I want to work with. If I open one of the photos in darkroom, when I later return to lighttable my tree of tags is collapsed, and I have to click on every triangle to open them again. 

An "expand all" button would be handy to eliminate the annoying tedium of having to click all those little triangles every time I return to lighttable.

Another option would be not to have that tree collapse automatically, but provide a "collapse all" button to do it manually.

Dave

**Comment by difrkaguilar** [comment]
> An "expand all" button would be handy to eliminate the annoying tedium of having to click all those little triangles every time I return to lighttable.

An expand all and collapse all button or right click to do this action, this will be a nice addition, and full arrow keyboard navigation too.
Using up and down to navigate through folders, tags, date taken, date-time taken, import timestamp, change timestamp, export timestamp and every other needed in collections. And left / right arrows to expand / collapse.

![Screenshot-20210807152443-399x276](https://user-images.githubusercontent.com/67672868/128611770-b44b4dec-1eb2-4403-a5a1-722f6d2f0d5f.png)
