### ISSUE TITLE
English tooltips in global preferences shortcut section when Spanish language is set.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#9756]
**Describe the bug/issue**
When Spanish language is set in global preferences, in shortcuts section the tooltips are in English not in Spanish.
The two search ComboBox (search shortcuts list and search action list) are in English too.

**To Reproduce**

1. Go to global preferences window.
2. Set language to Spanish.
3. Close darktable.
4. Open darktable.
5. Go to global preferences window.
6. Click on shortcuts.
7. Select any shortcut or action and wait for the tooltip.
8. See error. Tooltips  and ComboBox are in English.

**Expected behavior**
If language is set to Spanish the expected behavior is that tooltips must be in Spanish too.

**Screenshots**
![Screenshot-20210807155729-1008x580](https://user-images.githubusercontent.com/67672868/128612706-2c99149d-6584-4ad9-baa0-cc3d43174317.png)

![Screenshot-20210807155759-1000x575](https://user-images.githubusercontent.com/67672868/128612709-4948abc7-2c8e-4dc7-8282-95a2ffed78df.png)

**Platform**
darktable 3.7.0~git681.1745bed4b3-6397.1
bit depth is 64 bit
normal build
SSE2 optimized codepath enabled
OpenMP support enabled
OpenCL support enabled
Lua support enabled, API version 8.0.0-dev
Colord support enabled
gPhoto2 support enabled
GraphicsMagick support enabled
ImageMagick support disabled
OpenEXR support enabled

OS: Fedora 34 (Workstation Edition) x86_64
Host: Z390 AORUS MASTER
Kernel: 5.12.17-300.fc34.x86_64
Uptime: 2 hours, 31 mins
Packages: 3121 (rpm), 8 (flatpak), 12 (snap)
Shell: zsh 5.8
Resolution: 3840x2160
DE: GNOME 40.3
WM: Mutter
WM Theme: Materia-dark-compact
Theme: Mojave-dark [GTK2/3]
Icons: Os-Catalina-icons-master [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 2219MiB / 32037MiB
Graphics driver : 460.73.01
OpenCL installed : yes
OpenCL activated : yes

**Comment by johnny-bit** [comment]
Those seem to be simply untranslated. Untranslated strings fallback to english. If you can help with Spanish translation check https://github.com/darktable-org/darktable/wiki/Translating-darktable
