### ISSUE TITLE
[Windows] File browser

### ISSUE THREAD

**Issue by 4044ever** [darktable-org/darktable#9759]
**Is your feature request related to a problem? Please describe.**
Currently there is no simple easy to use file browser. 

**Describe the solution you'd like**
A normal Windows type like file browser, similar to Rawtherapee. The type that is basically used by any other Windows program.

**Additional context**
I think older versions had a file browser.

**Comment by johnny-bit** [comment]
Read the documentation please
https://www.darktable.org/usermanual/3.6/en/lighttable/lighttable-modes/filemanager/

**Comment by 4044ever** [comment]
I mean a FILE BROWSER to browser trough folders on the HDD. Not Lighttable. Currently it's a pain in the *** to get to a file.

**Comment by johnny-bit** [comment]
https://www.darktable.org/usermanual/3.6/en/lighttable/digital-asset-management/
+
https://www.darktable.org/usermanual/3.6/en/overview/workflow/import-rate-tag/
+
https://www.darktable.org/usermanual/3.6/en/module-reference/utility-modules/lighttable/import/
