### ISSUE TITLE
dt 3.6 ignores $(MODEL) when renaming filenames during import

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#9762]
**Introduction**
This referres to "copy and import" and renaming filenames according to import options in general settings of darktable

**Describe the bug/issue**
I try to use this string `$(EXIF_YEAR)$(EXIF_MONTH)$(EXIF_DAY)_$(MODEL)$(FILE_NAME).$(FILE_EXTENSION)` for renaming images during import.
Result is
20210604__N5X1655.NEF
instead of expected
20210604_D500_N5X1655.NEF

So obviously date values work fine but not the camera model.
I get this when using exiv2

```
$ exiv2 20210604__N5X1655.NEF
Dateiname       : 20210604__N5X1655.NEF
Dateigröße      : 24938105 Bytes
MIME-Typ        : image/x-nikon-nef
Bildgröße       : 5600 x 3728
Kamerahersteller: NIKON CORPORATION
Kameramodell    : NIKON D500
Zeitstempel des Bildes: 2021:06:04 16:13:45
Bildnummer      : 
Belichtungszeit : 1/1000 s
Blende          : F5.6
Belichtungskontrolle: -1/2 EV
Blitz           : Kein Blitz
Blitzkontrolle  : 
Brennweite      : 500.0 mm (35 mm äquivalent: 750.0 mm)
Entfernung des Motivs: 
ISO Geschwindigkeit: 280
Belichtungsmodus: Manuell
Messmodus       : Mittelpunkt gewichteter Durchschnitt
Makromodus      : 
Bildqualität    : RAW    
Exif-Auflösung  : 160 x 120
Weißabgleich    : SUNNY       
Vorschau        : Keine
Copyright       : 
Exif-Kommentar  : 
```

or long version:
```
exiv2 -pt 20210604__N5X1655.NEF
(...)
Exif.Image.Make                              Ascii      18  NIKON CORPORATION
Exif.Image.Model                             Ascii      11  NIKON D500
```
**Platform**

* darktable version : darktable   3.6.0-1.1   amd64      from OBS
```
System:
  Host: Rechner Kernel: 4.19.0-17-amd64 x86_64 bits: 64 compiler: gcc 
  v: 8.3.0 Desktop: Cinnamon 3.8.8 Distro: Debian GNU/Linux 10 (buster) 
Machine:
  Type: Desktop Mobo: ASUSTeK model: P8Z77-M v: Rev 1.xx serial: <filter> 
  UEFI: American Megatrends v: 2203 date: 12/18/2015 
CPU:
  Topology: Quad Core model: Intel Core i5-3570 bits: 64 type: MCP 
  arch: Ivy Bridge rev: 9 L2 cache: 6144 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 27282 
  Speed: 3657 MHz min/max: 1600/3800 MHz Core speeds (MHz): 1: 3770 2: 3774 
  3: 3790 4: 3763 
Graphics:
  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics 
  vendor: ASUSTeK P8H77-I driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1200~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ivybridge Desktop v: 4.2 Mesa 18.3.6 
  direct render: Yes 
Info:
  Processes: 250 Uptime: 26d 15h 41m Memory: 15.48 GiB 
```

* OpenCL installed  : no
* OpenCL activated  : no

I checked on my system after another user asked me about this issue he had on the following system:
Darktable: 3.6.0
Windows 10 Pro Version: 20H2 Build: 19042.1110

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with a RAW or Jpeg or both? only tested with RAW
 - Do you use lua scripts? no

Btw: also tested with my Panasonic camera - same issue
and also applies to $(MAKER)

**Comment by phweyland** [comment]
In line with the [doc](https://darktable-org.github.io/dtdocs/preferences-settings/import/).

**Comment by bilddateien** [comment]
Thanks, I did not see this but only found the general page about [variables](https://darktable-org.github.io/dtdocs/special-topics/variables/).
There it says
> The following variables are available, though they may not all be applicable in every context

so: still in line with doc ...
