### ISSUE TITLE
Not launching on Windows 11 Beta

### ISSUE THREAD

**Issue by Surg42** [darktable-org/darktable#9766]
On Windows 11 Beta build 22000.120 after installing darktable  it does not launch and an error message is displayed the error file is attached.
[darktable_bt_YME770.txt](https://github.com/darktable-org/darktable/files/6951211/darktable_bt_YME770.txt)

**Comment by johnny-bit** [comment]
error is in `OpenCL.dll` and not in darktable. either disable opencl or update opencl drivers and it should work.
