### ISSUE TITLE
Wrong JzCzhz blending results on CPU path

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#9767]
**Did you buy darktable from an application store ?**

No.

**Describe the bug/issue**

Mask blending on CPU produces wrong results when JzCzhz blending is used. GPU path works correctly. E.g. selecting a hz range based on a colorful area of the image, that area isn't included in the mask.

I found the root cause: `blendif_rgb_jzczhz.c` uses a "hacked" profile with modified `matrix_out` here:
https://github.com/darktable-org/darktable/blob/40421d57d99c2b25f57898cd451b1bb357d10fa9/src/develop/blends/blendif_rgb_jzczhz.c#L150

However since https://github.com/darktable-org/darktable/commit/6ba7a7e47b131e5d30da4f78b226b822ffbcdec3 `matrix_out_transposed` is used instead. However that matrix is not initialized here:
https://github.com/darktable-org/darktable/blob/40421d57d99c2b25f57898cd451b1bb357d10fa9/src/develop/blend.c#L219-L228

GPU code uses `matrix_out` directly, hence it works correctly.

@ralfbrown, would you mind having a look at this? I can also post a simple fix, adding the initialization of `matrix_out_transposed` there but I feel you might come up with a cleaner fix. :)

**Comment by ralfbrown** [comment]
There isn't an obvious better way.  Besides directly setting the transposed elements inside the loop, the other reasonable alternative would be calling the transpose function after the loop.
