### ISSUE TITLE
Panasonic DC-S5: high-res/pixel-shift

### ISSUE THREAD

**Issue by jdneumeyer77** [darktable-org/darktable#9768]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

I've uploaded a sample. Although, it seems there was one before. I probably should have looked before I did that. There is a 48MP version that I'll upload a sample for that and  hope to contribute noise profilesvas well once I have time.

I've been running dev branch for a while and I'm happy to confirm the changes.

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/rawspeed/issues/246

**Comment by LebedevRI** [comment]
928115e76f6d9864762dd606696e414d27c22524
