### ISSUE TITLE
darktable-generate-cache: allow skipping rejected images

### ISSUE THREAD

**Issue by moy** [darktable-org/darktable#9772]
**Is your feature request related to a problem? Please describe.**

darktable-generate-cache generates the cache for all images in the database, including rejected ones which are unlikely to be used. This can take a very long time if the user has a low accepted/rejected ratio.

A typical workflow:

1) Import all images from the camera
2) Do a rough selection to reject bad images
3) `darktable-generate-cache -m 8` to populate full size thumbnail cache
4) Use culling/full size preview to finish image selection

When step 2 rejects many images (macro photographers understand what I'm talking about ;-) ), step 3) is needlessly long.

Another typical use-case: in the last steps of the workflow, finish image selection and processing, and then use the full-size preview as an image viewer: then one wants only to see not-rejected images.

**Describe the solution you'd like/Alternatives**

A new `darktable-generate-cache --skip-rejected` option, or probably better: skip rejected images by default, and add a new `--include-rejected` option.

**Comment by wpferguson** [comment]
darktable-generate-cache also takes start and end image numbers (min-imgid, max-imgid)s o that it doesn't have to run over the whole database.

Also, see #5171.
