### ISSUE TITLE
Preload/precompute next thumbnail in culling & full-size preview mode

### ISSUE THREAD

**Issue by moy** [darktable-org/darktable#9773]
**Is your feature request related to a problem? Please describe.**

The culling and full-size preview modes are great to compare and select images. They are perfect when the cache is already populated. However, especially when viewing the images at 100% scale, moving to the next image can be long.

**Describe the solution you'd like**

A solution would be to pre-compute (or pre-load if the image is available on disk) the next image while viewing the current one (or the current set of images in culling mode).

A typical flow currently can be

1) view an image or a set of images, take a handful of seconds to decide which one to select/rate/reject
2) mouse-wheel or arrow key to move to the next image (or reject an image to move to the next automatically)
3) wait a handful of seconds for dt to show the next image
4) goto 1.

If steps 1) and 3) take comparable amount of time, the user spends around half the time waiting for dt (=> more time to do the selection, and much less pleasant user-experience). With pre-computing, this could be:

1) view an image or a set of images, *while dt is computing the thumbnail for the next one*
2) mouse-wheel or arrow key to move to the next image (or reject an image to move to the next automatically)
3) *don't wait, the image is already there :-)*. Or possibly wait for the end of the computation, but much less than currently.
4) goto 1

**Alternatives**

Ideally, dt could even pre-compute the next `N` images with `N` being a configuration parameter, but that probably raise more implementation issues compared to the benefit.

**Comment by wpferguson** [comment]
This is another flavor of #5171.  This can be solved with a lua script but currently it will only work in master.

**Comment by moy** [comment]
Thanks. I looked for "preload", "precompute" but not "pre-render" as keywords ;-). Closing as duplicate.
