### ISSUE TITLE
regression: lazy XMP writing disables writes entirely

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#9776]
**Did you buy darktable from an application store ?**
no

**Describe the bug/issue**
In an installed version of darktable which is upgraded to a version incorporating #9681, XMP writes are turned off entirely.  Where the writes had previously been enabled, they are now set to "never", rather than "on import".

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Use a darktablerc from a version prior to #9681 which has xmp writes enabled
2. Invoke an executable built with #9681
3. Go to Preferences|Storage and note that "write sidecar file for each image" is now set to Never.

**Expected behavior**
If sidecar writing was previously enabled, it should stay enabled.

**Platform**

* darktable version : 3.7.0+694
* OS                : Linux
* Linux - Distro    : Mageia
* gcc               : 8.4.0
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Comment by jenshannoschwalm** [comment]
Saw this, will fix asap
