### ISSUE TITLE
DT crashes in lighttable view when zooming on pictures with middle-click

### ISSUE THREAD

**Issue by Mispille** [darktable-org/darktable#9788]
## Issue

When zooming on pictures using middle-click, memory usage jumps like crazy
After filling available RAM, it start using swap
Then when all RAM and Swap are used, Darktable crashes

## Steps to reproduce
* Open DT
* Select either **full preview** or any **culling view** layouts
* Use middle click on any picture to zoom in at selected location
* See RAM usage go up
* Continue until full RAM is used and DT crashes

> Changing mode, going to darkroom, or anything else **doesn't make RAM usage go back to normal**

## Platform

* darktable version : 3.6.0-1.1
* OS                : 5.11.0-7620-generic
* Linux - Distro    : Pop!_OS 21.04 based on Ubuntu 21.04 (No tweaks on the system, fresh install)
* CPU : AMD **Ryzen 5600H**
* Memory            :  8Go
* Graphics card     :  NVIDIA **GTX 3060** in max-p 130W version
* Graphics driver   : 470.57.02
* Xorg              : X11
* Desktop           : GNOME 3.38

Notes on Darktable
* Fresh install of 3.6.0 version with `.deb` package available online - Installed *today*
* Config file : Only change import path, no other settings changed
* Happens with OpenCL support **ON** and **OFF**

**Comment by johnny-bit** [comment]
I've tried on current master and it works for me (although initial render to get 100% zoom takes a bit) and it works on 3.6.0 for me...

Maybe the images you're browsing are resource intensive and middle clicking on them requests pipe run for both so it might overload your system? 8GB ram for 2 simultaneous pipe runs might be problematic. Maybe the crash isn't as much darktable crashing as OOMKiller killing darktable process?

**Comment by Mispille** [comment]
Tried getting more data this morning
In the logfile done with `darktable -d all` there is no error/fail/fatal/crash mention
But while doing this, here is what was printed in terminal:

```
darktable -d all > ~/downloads/dt_crash.log
[memory] at startup
[memory] max address space (vmpeak):      120300 kB
[memory] cur address space (vmsize):      120268 kB
[memory] max used memory   (vmhwm ):       27492 kB
[memory] cur used memory   (vmrss ):       27492 kB

^^^^^ modulegroups
vvvvv
[memory] after successful startup
[memory] max address space (vmpeak):     6658288 kB
[memory] cur address space (vmsize):     6658288 kB
[memory] max used memory   (vmhwm ):      270264 kB
[memory] cur used memory   (vmrss ):      270264 kB
wait time 0,161125s
wait time 0,184890s
try- wait time 0,100005s
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
Killed
```

Hope this can give you more insighs, if not please guide me on what steps I need to take to investigate further!

Many thanks

**Comment by johnny-bit** [comment]
It's very weird that you get _iop_validate_params for `framing` module. Can you attach the `dt_crash.log` file you've created and xmp files of the files that cause mem spike?

as I said - the "Killed" message is not from darktable but from your OS OOMKiller.

**Comment by RobbieAB** [comment]
This sounds like something is memory leaking triggering the OOM killer to get invoked. It probably is darktable if darktable keeps being the killed application, but it is probably worth confirming the method of the crash is indeed the OOM killer.

Can you check your dmesg logs, or provide a copy which we can review?

**Comment by Mispille** [comment]
Here is the log file

You'll see OpenCL bluiding binary programs because cache wasn't available as I deleted forlder to check if issue was resolved
Didn't change anything
[dt_crash.log](https://github.com/darktable-org/darktable/files/6967904/dt_crash.log)

**Comment by RobbieAB** [comment]
The is the dt crash log. I was looking for the kernel logs from the host machine, which will clearly show an OOM killer invocation if that is happening, and will also provide details on the decision making process the kernel is following if it is the kernel killing the application.

**Comment by Mispille** [comment]
@RobbieAB yes I was replying to @johnny-bit 

Here is what `sudo journalctl | grep -i darktable | grep "août 11"
[jctl_darktable.log](https://github.com/darktable-org/darktable/files/6967980/jctl_darktable.log)
` gave me in attachement

There is indeed this line :

`août 11 10:39:57 quasar kernel: Out of memory: Killed process 4228 (darktable) total-vm:14808592kB, anon-rss:3868592kB, file-rss:64632kB, shmem-rss:11608kB, UID:1000 pgtables:15168kB oom_score_adj:0`

Thanks for helping!

**Comment by johnny-bit** [comment]
yeah, the oomkiller kills darktable because starting 2 pipe runs means HUGE spike in mem usage and oomkiller kills whatever app is most recent active memory hog (which obviously will be darktable)

can you additionally post results of `sudo dmesg` ?

**Comment by Mispille** [comment]
Here is all the information needed, do you see anything suspicious?

1. `sudo dmesg` info: [dmesg.log](https://github.com/darktable-org/darktable/files/6974843/dmesg.log)
2. Memory stats with everything closed + Swap total size
```
              total        used        free      shared  buff/cache   available
Mem:          7,7Gi       1,3Gi       4,3Gi       4,0Mi       2,1Gi       6,1Gi
Swap:         4,0Gi          0B       4,0Gi
```
4. Images: 48 MP or 12 MP
5. [XMP files](https://github.com/darktable-org/darktable/files/6974855/xmp.zip)

Also here is more info about what is going on during this activity in the system: 
[syslog_tail_dt_crash.log](https://github.com/darktable-org/darktable/files/6974870/syslog_tail_dt_crash.log)

**Comment by johnny-bit** [comment]
So... You've got 8GB ram. With NOTHING on you have max 6GB avail which tbh is rather small. On top of that 4GB swap is not adequate... With current spec I'd recommend 2xRAM for swap (generally 16G swap should be enough breathing room)

There's IMO nothing suspicious in both dmesg and syslog - just oomkiller doing it's thing.

What's suspicious is that all the xmp files you've sent look like XMPs from fresh import. The messages in https://github.com/darktable-org/darktable/issues/9788#issuecomment-896629386 mentioned invalid params to `framing` module which none of the xmps you've sent seem to use...

I wonder now... with middle click... how many pipes are actually started? 2? or whole collection?

**Comment by Mispille** [comment]
Yep just started working on this hardware recently, planning to upgrade to 16

How could I check pipes ?

**Comment by johnny-bit** [comment]
> How could I check pipes ?

that's more of a dt dev question. I was under the impression that culling mode starts pipe just for the visible images and I hope that's the case.

I'd recommend starting investigation that way:
1. try have collection of just 2 images and do middle click. does it go to oomkiller or not? if not - try increasing number of images in collection and see where's the crashpoint.
2. try increasing swap to 16G. see if it still crashes

**Comment by Mispille** [comment]
@johnny-bit Understood, I'll try this weekend and keep you informed

Also even if I agree that 8 Go is limiting for photography managing and editing, I still have the intuition that such peaks in RAM usage on a single mouse click on a single picture feels abnormal

Thanks for the help! Coming back with more info when I have time available in the coming days

**Comment by dterrahe** [comment]
Please confirm if still an issue in latest master. Otherwise please close.

**Comment by Mispille** [comment]
Hi everyone

unfortunately I came back to windows for work environnement restrictions and therefor cannot give you any update on this issue

I'm sorry about that

Closing issue

Thank you for your kind support
