### ISSUE TITLE
Can't rename duplicated masks

### ISSUE THREAD

**Issue by billmartz** [darktable-org/darktable#9790]
Did you buy darktable from an application store ?

No

Describe the bug/issue

Trying to rename a duplicate of a mask produces an error;
[darktable_bt_VDC670.txt](https://github.com/darktable-org/darktable/files/6964273/darktable_bt_VDC670.txt)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

darktable version : darktable-3.7.0+699~g081b924ed-win64.exe
OS : Windows 10 Pro, version 20H2
Memory : 32 GB
Graphics card : NVIDIA GeForce GTX 1070
Graphics driver : Driver version: 457.51
OpenCL installed : Yes
OpenCL activated : Yes

**Additional context**
_Please provide any additional information you think may be useful, for example:_

Can you reproduce with another darktable version(s)? Didn't try
Can you reproduce with a RAW or Jpeg or both? Didn't try
Are the steps above reproducible with a fresh edit (i.e. after discarding history)? Didn't try
Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? Didn't try
Do you use lua scripts? No

**Comment by phweyland** [comment]
Duplicate of #9504 ?

**Comment by billmartz** [comment]
May very well be same problem. I didn't use 3.6 real long, but renaming a mask is something I often do, and I didn't see this problem until 3.7. Maybe I never renamed a mask.

**Comment by billmartz** [comment]
Duplicates another issue.
