### ISSUE TITLE
Mask manager missing features

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#9792]
**Is your feature request related to a problem? Please describe.**
When trying to use the mask manager, I have found it frustrating that:
1. There is no mask preview button. If the mask manager allows creation of new masks outside the context of a module, it needs a way to preview the mask.
2. I cannot seem to figure out how to create a mask group using the mask manager. Groups seem to only be created by using a module. Again, if I can create masks using the mask manager, it seems logical that I should be able to group/compose masks together using the mask manager too.

**Describe the solution you'd like**
I would like to have a quick way to preview a mask (or group mask) from the mask manager module. If this functionality already exists, it might be too difficult for someone like me to discover.

The ability to add masks from the mask manager is great, but without a way to group or combine masks unless activating a module seems. A useful workflow would be to create a mask from the mask manager, set up the boolean operations, and then activate a module and use that nice mask group I just created in the manager.

**Comment by ralfbrown** [comment]
Clicking on the shape's name will display its control points; once those are shown, moving the mouse near the drawn curve will also display the falloff/feathering zone.  Likewise, clicking on a group name will display all of the shapes in the group.

Select multiple shapes by control-clicking the second and subsequent, then right-click for a menu which includes a "group forms" option.  @elstoc: it appears that this latter option is not described in the documentation (https://darktable-org.github.io/dtdocs/module-reference/utility-modules/darkroom/mask-manager/).

**Comment by difrkaguilar** [comment]
I made reference to some of this features in #8453
There I explained about a redesign of the mask manager with some of the missing features to make more easily to work with.
Anyway, better ideas can be done.

**Comment by groutr** [comment]
@ralfbrown Thank you for the explanations. I'm still very much learning the mask manager module. The preview that I was meaning was the yellow shaded preview of the mask.

Selecting multiple shapes using ctrl was not obvious to me, but I'm learning that I still have a lot of experimenting left to. One thing that I tried for adding a shape to a group was dragging the shape to the group (like you would drag a file to folder in a file manager).

One thing that I can find no explanation for in the manual is why I see a "24%" appended to shape names that appear in groups.
![Screenshot_20210816_234624](https://user-images.githubusercontent.com/10678620/129665153-74beedad-1d71-4dfb-8037-90ac96bb0d70.png)

**Comment by difrkaguilar** [comment]
An unexpected behavior of the mask manager is that if users create a group with come shapes, circles, elipces or paths, expand the group and scroll over the mask to change the opacity the group automatically collapse, then users must have to expandit againg every time  to see the shapes opacity.
