### ISSUE TITLE
SONY ILCE-7RM4A

### ISSUE THREAD

**Issue by bobek321** [darktable-org/darktable#9796]
Hello,

I would be happy if Sony A7rIVa could be supported in Darktable that I use for over 3 years now. And love it. I uploaded one raw file at raw.pixls.us  - please let me know if you need any more samples.

Thanks, Aleksander

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/9751

**Comment by LebedevRI** [comment]
Duplicate of #9751
