### ISSUE TITLE
Retouch: black area artifacts in combination with diffuse/sharpen

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9797]
frequently black artifacts occurs if retouch is used in combination with diffuse/sharpen module

![image](https://user-images.githubusercontent.com/39386816/129195113-eb05d81c-409c-495a-bafe-d8879405e709.png)

mostly in preview, but sometimes also in full pixelpipe

deactivating diffuse/sharpen

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. open image in darkroom (e.g. mire1.cr2 from integration tests)
2. apply retouch: add path with wavelet decomposition and merge of scales
3. apply diffuse/sharpen (i used sharpen demosaicing AA filter)
4. See error (or play around with merging scales in diffuse module)

[mire1.cr2.xmp.txt](https://github.com/darktable-org/darktable/files/6975425/mire1.cr2.xmp.txt)

**Which commit introduced the error**
bisecting gave:
```
e4cf5ef002a218750e38e45afdd629ca7f9ec5be is the first bad commit
commit e4cf5ef002a218750e38e45afdd629ca7f9ec5be
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Fri Jul 30 02:31:11 2021 -0400

    remove extraneous memset calls

 src/common/bilateral.c       | 10 ++++------
 src/common/imagebuf.c        |  4 ++--
 src/develop/masks/brush.c    | 17 ++++++++---------
 src/develop/masks/ellipse.c  |  4 ----
 src/develop/masks/gradient.c | 30 +++++++++++++++++-------------
 src/develop/masks/group.c    |  7 ++-----
 src/develop/masks/path.c     | 36 +++++++++++++++++-------------------
 src/iop/equalizer_eaw.h      |  6 +++++-
 8 files changed, 55 insertions(+), 59 deletions(-)

```

**Platform**
darktable current master (with cr3 support in rawspeed)

* darktable version : darktable 3.7.0+778~g6b16b9bf6

* OS                :  reproduced on Win10 & OSx
with and without openCL enabled
(suppressed opencl by --disable-opencl )

any ideas which -d option can give a hint what's happening there?

**Comment by MStraeten** [comment]
the screenshot looks similar, so maybe it’s a duplicate. Difference: i need diffuse/sharpen to get this reproducible

**Comment by ralfbrown** [comment]
Probably a dup, but this one has both a reproducing sidecar and a bisect.  That made it relatively straightforward to find the cause.

**Comment by johnny-bit** [comment]
@MStraeten has the best issue reports :1st_place_medal:

**Comment by MStraeten** [comment]
fixed, thanks
