### ISSUE TITLE
diffuse: exposure independent edge awareness

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#9808]
**Is your feature request related to a problem? Please describe.**

Currently the `diffuse or sharpen` module seems to mainly target darker tones whenever a positive (non-zero) `edge sensitivity` value is set. This is caused by the regularization which uses the local variance to decrease the diffusion strength near sharp edges to avoid halos. Variance is greater in the lighter parts of the image.

**Describe the solution you'd like**

Normalize the variance like it's done in the `exposure independent guided filter` of the `tone equalizer`: `regularization = variance / center_pixel_value^2`.

What do you think @aurelienpierre ? I find the current behaviour quite problematic especially when trying to add local contrast in the highlights – there's hardly any effect in the highlights while shadows get pretty dark. I can open a PR with examples later if this seems to you like a viable way forward.

**Comment by aurelienpierre** [comment]
I tested variance normalization, and it didn't work great because it oversharpened the shadows. I think the current behaviour is more physically-plausible.

**Comment by flannelhead** [comment]
@aurelienpierre interesting. I'm thinking something along the lines of:

```diff
--- a/src/iop/diffuse.c
+++ b/src/iop/diffuse.c
@@ -783,7 +783,8 @@ static inline void heat_PDE_diffusion(const float *const restrict high_freq, con
         // Prevents large scale halos when deblurring.
         for_each_channel(c, aligned(variance))
         {
-          variance[c] = variance_threshold + sqrtf(variance[c] * regularization_factor);
+          const float center_value = MAX(LF[index + c], 1e-6);
+          variance[c] = MAX(variance_threshold + sqrtf(variance[c] * regularization_factor) / center_value, 1e-6);
         }
         // compute the update
         dt_aligned_pixel_t acc = { 0.f };
--
```
i.e. using the `LF` value of the center pixel for normalization. The variance is currently calculated as the sum of squares of `HF` pixels in the neighbourhood, as they kind-of represent the first derivative at that scale, if I'm right? (Pardon my ignorance, I'm not very familiar with wavelets yet)

Here's one example where I used the `add local contrast` preset and increased iterations to 6 to exaggerate the effect.

Without diffuse:

![without_diffuse](https://user-images.githubusercontent.com/5001906/129605373-3e09d8f4-76bb-4c35-a743-d7de07dbd369.png)

Diffuse on, without this patch applied (current state):

![without_normalization](https://user-images.githubusercontent.com/5001906/129605084-a3308535-38f7-4b33-9d25-d7025ca70b7b.png)

Notice the very hard increase of contrast in the deep shadows, almost everything pulled to black.

Diffuse on, with this patch applied:

![with_normalization](https://user-images.githubusercontent.com/5001906/129605428-5bfdb471-70d4-4350-8f1b-b31dd1410b3b.png)

Notice the gentler treatment of shadows while the highlights still get a boost.

**Comment by aurelienpierre** [comment]
HF is actually the laplacian already, so second order derivative, aka oscillations around the local average… which is a variance if you average its square along a patch. The variance is normalized already for wavelet scales to be scene-referred invariant no matter the scale (otherwise, large details like sky/ground border get oversharpened and produce halos). Actually the wavelets scheme + equivalent blur radius should already take care of normalization, but I really don't know what variance normalization means in a multiscale context. LF will become very grey as scale increases.

From an aesthetic point of view, we also don't expect as much details in lowlights. In paintings, shadows are usually blurrier than highlights.

**Comment by flannelhead** [comment]
Right, since a suitable way of normalizing (or need thereof) is unclear, I'll close this for now. This image is also probably a pretty pathological example since the scene referred values of the cloud highlights are quite far above the usual range. Overall I've been quite satisfied with what can be done with the module.
