### ISSUE TITLE
Panasonic S5: Underexposed images green/Black levels not read

### ISSUE THREAD

**Issue by jdneumeyer77** [darktable-org/darktable#9811]
**Describe the bug/issue**

Underexposed images are very green for the Panasonic S5 raw files (rw2). For instance, I was capturing the Milky Way by way of stacking. So I set up the proper exposure for iso3200 with a test shot, but switched it to iso640 before taking the exposures for the stack to further reduce noise (640 is the dual-gain point for this sensor).

While investigating why my files were so green I saw this ticket: #9285 which seems similar. Based on that I used exiftools to find the Black levels and that seems to have fixed.

**Expected behavior**
The expected behavior is shown in the screenshots without the green cast and much darker exposure overall. The exposure was pushed 5 stops on each image. 

**Dark and overly green image**
![Screenshot_2021-08-14_15-58-41](https://user-images.githubusercontent.com/9755266/129464004-325e8cd3-b847-4048-b388-c09360ced758.png)

**Correct Behavior after setting the black levels**
![Screenshot_2021-08-14_15-59-15](https://user-images.githubusercontent.com/9755266/129464017-dc65e07a-b9d5-42c4-945b-ae20d78bf7b9.png)

Looking at rawspeed has support in [cameras.xml](https://github.com/darktable-org/rawspeed/blob/develop/data/cameras.xml#L6156) for it and looks to set the default to 509. Glancing at the rawspeed [decoder](https://github.com/darktable-org/rawspeed/blob/develop/src/librawspeed/decoders/Rw2Decoder.cpp#L225), it attempts to read the values from the exif properly, but must fail for some reason.

Here's the exif snippet:
```
exiftool P1010852.RW2 | grep -i Black
Black Level Red                : 512
Black Level Green             : 512
Black Level Blue                : 512
```

I've attached a test image and I license it under under CC0 for testing purposes.
[samples.zip](https://github.com/darktable-org/darktable/files/6987394/samples.zip)

To reproduce bump the exposure to +6ev and to correct use 509 or 512 as the black levels in raw black/white levels module. Happy to help and dig further once I have more time.

**Platform**

* darktable version : 3.7.0.r699.g081b924ed5-1
* OS                :  Linux 5.10.53
* Linux - Distro    : Manjaro
* Memory            : 64gb
* Graphics card     : Nvidia Ti2060
* Graphics driver   : Nvidia
* OpenCL installed  : yes
* OpenCL activated  : not available / probably a primus issue...
* Xorg              : 1.20.13
* Desktop           : XFCE
* GTK+              : 4.2
* gcc               : 11.1
* cflags            : unknown/defaults
* CMAKE_BUILD_TYPE  : unknown/defaults

**Comment by johnny-bit** [comment]
Is the issue present on samples on raw.pixls.us?

What's weird is that on your green shot it looks like Black Levels are set to 527, the defaults are as you say 509 while exiftool says 512.

@LebedevRI - what do you think?

**Comment by jdneumeyer77** [comment]
The sample file exif says 510 for Black Levels, but when I open it in DT it says 525 (after disabling my auto apply workaround). It almost looks like something is adding 15.

I've attached a diff between the exif output from one of my files and the sample.
[samplefile.exif.txt](https://github.com/darktable-org/darktable/files/6989545/samplefile.exif.txt)
[myfile.exif.txt](https://github.com/darktable-org/darktable/files/6989547/myfile.exif.txt)
[exif.diff.txt](https://github.com/darktable-org/darktable/files/6989559/exif.diff.txt)

**Comment by jenshannoschwalm** [comment]
exiftool might do some magic before display, the relevant data should be tested to be correct via exiv2 .

**Comment by jdneumeyer77** [comment]
Using exiv2 it doesn't seem to have those entries Black Level {Red, Green, Blue}. The exiv2 doesn't seem to have raw documentation for the tags or their website is just confusing. I see the one for [Maker Notes](https://exiv2.org/tags-panasonic.html), but the tag id doesn't match the output file.

[sample.exiv2.txt](https://github.com/darktable-org/darktable/files/6996139/sample.exiv2.txt)

Exiftools has some documents on the [raw](https://exiftool.org/TagNames/PanasonicRaw.html). It matches the tag Ids being read by [rawspeed](https://github.com/darktable-org/rawspeed/blob/develop/src/librawspeed/decoders/Rw2Decoder.cpp#L214).

Based on the Exiftools docs though I think the problem is that it's reading the entry values as 32 bit unsigned ints instead of 16 bit unsigned ints.

```
    const auto getBlack = [&raw](TiffTag t) -> int {
      const auto val = raw->getEntry(t)->getU32();
      int out;
      if (__builtin_sadd_overflow(val, 15, &out))
        ThrowRDE("Integer overflow when calculating black level");
      return out;
    };
```
That seems to be where the 15 is coming from. 512 + 15 = 527. So it looks like it's overflowing either because it should be reading a 16 bit entry (not sure how `getEntry(t)->getU32() `handles reading more then it's supposed to). I'm rusty with C/C++ (I'm a Scala developer...), but also I'm not sure how `__builtin_sadd_overflow` handles being given a unsigned value when it handles signed values (gcc docs look poor).

**Comment by jenshannoschwalm** [comment]
Isn't the `getU32` here just wrong?

**Comment by jdneumeyer77** [comment]
@jenshannoschwalm I agree. I also don't understand why it's adding 15 to them which seems to causing problem with underexposed images. The affect on normally exposed images is very subtle. Similarly exposed as above, but at higher ISOs the green is subdued yet still there.

Should I just make an PR to switch to `getU16` and remove the addition/overflow check? If there is any value checks that traditionally happen could you point me to an example?

**Comment by jenshannoschwalm** [comment]
I thought about it again, i think the U16 is ok and safe, also it's just as the docs suggest. Also i don't understand what an overflow check is here for. We might want to check for plausible values (must be >=0 and < whitze point).

In any case it's a rawspeed issue and @LebedevRI is not always reading here. So rise the issue there and why not a pr? If he thinks it's bad because of any reason we can't think of now - he will let you know :-)

**Comment by LebedevRI** [comment]
Unfixed in darktable-org/rawspeed@b701374539fa224daf6533b1d80963f4845363da / xref #10008.
