### ISSUE TITLE
mouse over in preview area moves the section

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9816]
When zooming in the selection frame is floating around along to mouse movments after an initial dragging in the preview. 
It needs pressing a key thats not defined to be used with mouse movements (e.g. Esc key) to leave the preview area without changing the selection frame.

**To Reproduce**
1. Use current master
2. open image in darkroom and zoom in
2. place mouse pointer in preview area
3. move around without pressing a button
4. the selection frame follows your mouse

**Which commit introduced the error**
t.b.d

**Platform**
* darktable version : current master 3.7.0+833~g307903a2a
* OS                : Win10, also OSX

**Comment by MStraeten** [comment]
bisecting done:
```
ff2f1d566f84278580d8469a53fc1945f3e3b6a5 is the first bad commit
commit ff2f1d566f84278580d8469a53fc1945f3e3b6a5
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Sat Aug 7 13:39:28 2021 +0100

    shortcut tooltips and visual mapping for navigation and histogram

 src/libs/histogram.c  | 4 ++++
 src/libs/navigation.c | 2 ++
 2 files changed, 6 insertions(+)

```

**Comment by dterrahe** [comment]
Wow. "Interesting" side effect of setting GDK_ENTER_NOTIFY_MASK (which is needed to change the mouse cursor when entering the navigation widget in mapping mode to indicate you can assign a shortcut). For me this only happens after I press the mouse in the widget at least once. But then it doesn't stop. I'm investigating...

**Comment by dterrahe** [comment]
Used gtk_widget_set_events instead of gtk_widget_add_events. #9828 fixes.
