### ISSUE TITLE
color picker shows negative RGB values

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#9818]
DT 3.7 master, Windows 10.
Global color picker in point mode can show negative RGB values

![immagine](https://user-images.githubusercontent.com/43290988/129606489-1fafe450-13fb-4955-88fe-088d6904efd7.png)

and the consequence is that the color Hex value shown when hovering is completely wrong.

Also, it is strange that the color picked in area mode in the same region of the picture shows a min value non negative

![immagine](https://user-images.githubusercontent.com/43290988/129606178-1c372f2c-1da7-458d-82f8-b8852fc15c81.png)

In the example above I only use exposure, color calibration, filmic rgb and color balance rgb

**Comment by MStraeten** [comment]
do you have "clip negative RGB from gamut" enabled in color calibration?

**Comment by Mark-64** [comment]
Yes.
Although it doesn't have any effect on negative values in volor picker.

**Comment by Mark-64** [comment]
I found that to have correct reading for the overlay color palette, I must set "histogram color profile" to "system display profile". 
Any other profile gives incorrect values. The ones reported above were generated with sRGB.
The manual is not super clear about this

**Comment by Mark-64** [comment]
Closing
