### ISSUE TITLE
Build: LCMS2 -Wdeprecated-register fail

### ISSUE THREAD

**Issue by valpackett** [darktable-org/darktable#9821]
LittleCMS 2 uses the `register` keyword by default, resulting in this error, at least on clang 12:

```
/usr/local/include/lcms2.h:1261:44: fatal error: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
typedef cmsInt32Number (* cmsSAMPLER16)   (CMSREGISTER const cmsUInt16Number In[],
                                           ^~~~~~~~~~~~
/usr/local/include/lcms2.h:158:23: note: expanded from macro 'CMSREGISTER'
#  define CMSREGISTER register
                      ^
1 error generated.
```

It is possible to build LCMS2 with `CMS_NO_REGISTER_KEYWORD` but not every OS distribution is doing that. (It's also technically possible to define that just when including the header but that would result in technically broken ABI I guess :D)

So I suppose `CHECK_COMPILER_FLAG_AND_ENABLE_IT(-Wno-error=deprecated-register)` should be added for now?

Related: https://sourceforge.net/p/lcms/mailman/message/36520357/

**Comment by johnny-bit** [comment]
This is IMO LittleCMS2 bug and not darktable one.
