### ISSUE TITLE
Build: Thread Safety Analyzer blows up on dt_pthread_cond_wait

### ISSUE THREAD

**Issue by valpackett** [darktable-org/darktable#9822]
Darktable deliberately enables `-Wthread-safety`:

https://github.com/darktable-org/darktable/blob/4d57769d84d720f87fd8e01d16bb38f67927f2e4/cmake/compiler-warnings.cmake#L29

Which results in clang not liking the wrappers, at least the `pthread_cond_wait` one:

```
In file included from ../src/common/bilateralcl.c:23:
In file included from ../src/common/darktable.h:47:
../src/common/dtpthread.h:329:10: fatal error: calling function 'pthread_cond_wait' requires holding mutex 'mutex->mutex' exclusively [-Wthread-safety-analysis]
  return pthread_cond_wait(cond, &mutex->mutex);
         ^
1 error generated.
```

(with clang 12 on FreeBSD -CURRENT)

**Comment by johnny-bit** [comment]
Well... It looks like LLVM 11 & 1 complains about it on FreeBSD but it doesn't complain on ubuntu...
