### ISSUE TITLE
FR: customizable usage of opencl per module to improve performance

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9825]
after running several performance measurements on different images on two machines with different cpu and gpu power i found that some module benefit from gpu processing but others doesn't or are quite slower if using gpu. This is depending on the system configuration, so there's no "one size fits all"

So being able to customize the use of opencl per module can be useful to tweak performance:
- if cpu is faster in general - just enable opencl for the modules that will benefit
- if gpu is faster in general - just disable opencl for the modules where opencl results in a noticeable slow down

**Describe the solution you'd like**
1. extend module code to perform opencl processing according to a user customization
2. use darktablerc for a per module customization e.g. 
`plugins/darkroom/filmicrgb/opencl=false` 
or a separate opencl section
`opencl/filmicrgb/opencl=false `
that will evaluated on run time (default: true if opencl is enabled in general;  --disable-opencl or `opencl=FALSE` in darktablerc overrides these settings)

**Alternatives**
in case gpu is faster in general the user can delete the opencl kernel that slows down the processing ;)

**Comment by parafin** [comment]
The problem that effect of disabling opencl kernel of specific iop depends on what's in the pipe - specifically what iops come before and after, do they have opencl kernels themselves or not. It will determine if memory transfer is required. So depending on image history and also caching settings results will differ. So IMHO it's not that straightforward as simple benchmark. Though I guess if OpenCL kernel is measurably slower than doing transfer from GPU to CPU, then CPU processing, then transfer from CPU back to GPU, then indeed it will be faster that way always.

**Comment by johnny-bit** [comment]
Isn't this a duplicate of #5669?

**Comment by MStraeten** [comment]
seems to be a duplicate - haven't gone back far enough in my search ;)
The discussion there went into some automatic stuff depending on chipsets. But thats too much 'one size fits all' approach.
I even don't see it in an per module hamburger menu option, since - as parafin pointed out - it's not straightforward to identify what needs to be tweaked. I agree, it doesn't make sense to tweak per image - since tweaking will cost more time than the optimized configuration will save on processing. 
But if there's a noticeable effect in general (e.g. low variance of logged processing times) it might make sense to be able to customize this. It's not about getting the best possible processing time but even a better over all performance (which may be even worse in a few cases).

**Comment by johnny-bit** [comment]
OK, Marked as duplicate then :)

I think your idea is worth exploring in terms of #5669. I recently added a possibility to specify via darktablerc compile options for opencl programs and I consider that not something to put into ui. Similarly here - I'd not want such config item - neither in module nor in settings. Mainly because it'd be easy for people to shoot themselves in foot with it.

Would you mind sharing your ideas in #5669 and closing this one? I think it's worthwhile.

**Comment by MStraeten** [comment]
done
