### ISSUE TITLE
Potential integer overflow in src/common/imageio_pfm.c

### ISSUE THREAD

**Issue by KSB21ST** [darktable-org/darktable#9827]
**Describe the bug/issue**
It seems that there exists a potential integer overflow. Please find the following description:

1. img->width can be an arbitrary large number
https://github.com/darktable-org/darktable/blob/d2cd54ffa8a3e3fd23db3543968febedb81b2513/src/common/imageio_pfm.c#L53

2. Call to calloc with the large integer can cause a memory allocation with an overflowed size.
https://github.com/darktable-org/darktable/blob/d2cd54ffa8a3e3fd23db3543968febedb81b2513/src/common/imageio_pfm.c#L86

**Comment by johnny-bit** [comment]
Good catches. I already have couple fixes planned :)

**Comment by johnny-bit** [comment]
hey, if you can - please check #9840 and if it corrects the issue to your liking :)
