### ISSUE TITLE
Importing from folders containing letters like ä, ü and ö wont work.

### ISSUE THREAD

**Issue by Nico-1808** [darktable-org/darktable#9841]
**Introduction**
Dear Darktable development team, since the new updated vesion 3.6.0.1 I noticed a small but very annoying bug. If you name a folder / directory with words that contain letters like ä, ü or ö, files from these folders can no longer be imported into Darktable. This is annoying, especially for me as a German user, as I now have to rename many folders before I can import the files. The error happens with RAW and JPEG files I didn't test other files. Also reinstalling didn't change anything.

I wrote this message with Google translator, so sorry for any mistakes.

**Platform**
I'm using an older Toshiba Laptop with an Intelcore i3 and a AMD graphics card and Windows 8.1. I kown this is not the best for editing but it's all I have.

**Comment by Mark-64** [comment]
Fixed in master by #9498, fix will be in release 3.6.1
