### ISSUE TITLE
Module order: shouldn't lut 3d be applied after filmic?

### ISSUE THREAD

**Issue by carolfs** [darktable-org/darktable#9844]
**Did you buy darktable from an application store ?**

No.

**Describe the bug/issue**

When lut 3d is applied before filmic, highlights often appear blown out. When I switch the order, this problem disappears. Therefore, I suggest that lut 3d should appear after filmic in the pipeline by default.

**To Reproduce**

1. Apply lut 3d to well-exposed image.

**Expected behavior**

1. Highlights are not blown out.

**Screenshots**

Notice the difference in the sky (first has lut before filmic, second has lut after filmic).

![lut_before_filmic](https://user-images.githubusercontent.com/55320/130261724-461bded7-24b5-47f0-9881-6b27dae99d6e.jpg)
![lut_after_filmic](https://user-images.githubusercontent.com/55320/130261716-5111b4b7-dcaf-4f1f-9daa-0ee36c8de211.jpg)

**Platform**

darktable 3.6.0 on Fedora 34, photos edited from RAW (Fujifilm X-T20).

**Comment by Mark-64** [comment]
I agree with you, but the thing has been debated many times, there are pro and cons.
LUTs can be artistic, to apply a look, and in that case they should go after Filmic, or technical, to convert colorspace and then it is better before.

**Comment by MStraeten** [comment]
Yes and no. Yes if the lut is intended to apply a look on low dynamic range input, no if it’s intended to deal with high dynamic range input or revert an encoding done in the camera (e.g. undo log encoding)
You have to decide yourself based on the LUT you are using.
Since it can be used in the scene referred part of the pipe it’s placed there by default.

**Comment by carolfs** [comment]
I see. In any case, I don't mind changing the order by hand. Thank you for the replies.
