### ISSUE TITLE
FR: RYB vectorscope

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#9847]
**Is your feature request related to a problem? Please describe.**

The vectorscope is a powerful tool to analyze the colors present in an image.
It uses CIELUV and JzAzBz color spaces. These color spaces have been conceived to be perceptually uniform (delta E evenness).
For this reason there is no assumption nor relationship with color harmony.

Some color harmony rules has been described based on the RYB (or artist) color wheel (CIELUV and JzAzBz produce a color wheel close to the RGB one in term of polar coordinates).
 
![image](https://user-images.githubusercontent.com/23012047/130290174-a18fedcd-8f77-419b-abf8-828e48667e8e.png)

RYB primary colors and the complementary ones 
![image](https://user-images.githubusercontent.com/23012047/130291596-e5a84acf-5f77-4065-9679-33a0912270b1.png)

It should be noted that if RYB is said a substractive model, the YMC is the substractive equivalent to the additive RGB. So here we are not going to debate about additive / substractive property, but only about harmony ... which should be the same whatever the mean to obtain the final colors.

Based on the RYB color wheel we have some simple geometric rules which give (normally) pleasant color associations:
- monochromatic or closed colors (can be seen also on a RGB color wheel :))
- analogous complementary 
- complementary (teal & orange)
- split complementary
- triadic
...

It's a bit strange (for me) to see that the same geometric rules are commonly applied on the RGB color wheel. Krita, for example, has an artist color picker, implementing these rules on RGB. That doesn't produce opposite results but the differences remained noticeable.
For my standpoint (I'm not artist ...) I prefer the RYB based harmony.

**Describe the solution you'd like**

If we believe that the rules which have been applied by the greatest artists during several centuries are still valid and can be applied on our images it could be worth to add a third vectorscope, RYB, beside the CIELUV and JzAzBz ones.

That should help to analyze and tweak an image based on these rules.
This has also been suggested in #9798 and #9209.

**Alternatives**

Some alternatives have been discussed on pixls.us in [using-color-balance-rgb-for-creative-color-grading](https://discuss.pixls.us/t/using-color-balance-rgb-for-creative-color-grading/26338/27) or [create-custom-color-palette-to-show-in-the-vectorscope](https://discuss.pixls.us/t/create-custom-color-palette-to-show-in-the-vectorscope/25555).
If the overall workflow is similar, I believe that a RYB vectorscope would simplify it.

I think that the RYB topic have poped up in the discussions based on this impressive video [Secrets of color-grading in photography](https://www.youtube.com/watch?v=mC8ol2-V7Ck&t=601s) from Joanna Kustra.

**Additional context**

RYB is not a color space but there is some literature which can help to find a (kind of) RYB equivalent to the sRGB color space, where the harmony geometric rules are mode valid:
[Paint Inspired Color Mixing and Compositing for Visualization](http://vis.computer.org/vis2004/DVD/infovis/papers/gossett.pdf) (Gosset)
https://math.stackexchange.com/questions/305395/ryb-and-rgb-color-space-conversion/2776901#2776901, reversible (Jean-Olivier Irisson)
[Computational RYB Color Model and its Applications](https://danielhaim.com/research/downloads/Computational%20RYB%20Color%20Model%20and%20its%20Applications.pdf)
It is worth to cite the [paletton site](https://paletton.com/) as a generator of complementary colors.

**Comment by Mark-64** [comment]
There are few FR on the vectorscope currently, directly or indirectly inspired by that video from Joanna Kustra.
On top of this one we have #9836, #9798 and maybe others.
Plus, there is already an ongoing heavy rework of vectorscope and color picker, see #9835 #9640.
I wonder if we can help here. I could try to implement some of the simpler FR (not this one), but I dont' want to interfere.

**Comment by dtorop** [comment]
> If we believe that the rules which have been applied by the greatest artists during several centuries are still valid and can be applied on our images it could be worth to add a third vectorscope, RYB, beside the CIELUV and JzAzBz ones.

!!!

I appreciate the write-up. I'll be a bit swamped in the near term with various things (darktable and non-darktable) but if no one else claims this as a project, I'd be happy to make a try on it, probably later this year...

**Comment by phweyland** [comment]
I've started to look into it. Trying to understand how that works currently.
If I can I'll make a try. I'm on the background for the time being. Let's see if I succeed in doing something ... :)

**Comment by dtorop** [comment]
That's great! Indeed if you can get the background calculated in `_lib_histogram_vectorscope_bkgd()` you're 90% of the way there... You probably figured out that in `_lib_histogram_draw_vectorscope()` you can do something like:

```diff
modified   src/libs/histogram.c
@@ -936,10 +936,14 @@ static void _lib_histogram_draw_vectorscope(dt_lib_histogram_t *d, cairo_t *cr,
   if(!isnan(d->vectorscope_pt[0]))
     cairo_push_group(cr);
   cairo_set_source(cr, bkgd_pat);
+#if 0
   cairo_mask(cr, graph_pat);
   cairo_set_operator(cr, CAIRO_OPERATOR_HARD_LIGHT);
   cairo_set_source_rgba(cr, 1.0, 1.0, 1.0, 0.55);
   cairo_mask(cr, graph_pat);
+#else
+  cairo_paint(cr);
+#endif
 
   cairo_pattern_destroy(bkgd_pat);
   cairo_surface_destroy(bkgd_surface);
```

And then it'll draw the background to test that out. (Actually the above patch isn't working for me right now in CIELuv, not sure why...)

The code in `_lib_histogram_process_vectorscope()` could use another pass -- more optimizations and more brevity -- but that doesn't have to be your problem... It shouldn't be too difficult to add an extra vectorscope type to the UI...

Sometimes a test image as below can be nice, as it shows a full span of RGB values in the scope...
[
![hue saturation gradient scaled 2](https://user-images.githubusercontent.com/2311860/130367061-41a1404a-88a9-4e92-b82b-96e38aac5fba.png)
](url)

**Comment by phweyland** [comment]
> And then it'll draw the background to test that out. (Actually the above patch isn't working for me right now in CIELuv, not sure why...)

I've discovered that. :+1: It works, at least I can see two different wheels for CIELuv and Jzazbz.

**Comment by phweyland** [comment]
Gosset RYB background with darktable and darktable-elegent-grey theme:
![image](https://user-images.githubusercontent.com/23012047/130522034-5b733456-6e1c-49ab-be9c-fd00599cdaba.png)

![image](https://user-images.githubusercontent.com/23012047/130522209-eea2d31d-7384-4932-8f54-442bdad42927.png)

Is really convenient that the theme changes the graph colors ?

The same with gmic RYB:
![image](https://user-images.githubusercontent.com/23012047/130523789-8e8cf590-b358-4cd2-84e8-58b3bccec896.png)

![image](https://user-images.githubusercontent.com/23012047/130523760-de0b6916-85c8-4d88-9f9f-6a02a724c84b.png)

I've not yet made work rgb2ryb() with gosset but the gmic algo seems to start to work, here the Joanna's color wheel (screen shot):
![image](https://user-images.githubusercontent.com/23012047/130618074-7bd31447-569b-403c-a0f0-c4d66a93be97.png)
We can see that hues are not evenly spread. Here with gmic rg2ryb() and dt_RGB_to_HSV().

**Comment by dtorop** [comment]
It looks promising!

> Is really convenient that the theme changes the graph colors ?

It's something to think about. The scope has a subtle background right now based on the `graph_bg` CSS. This seems to make sense for consistent theming (and gives a hint as to what's in/out of graphable range). It could be possible to render the graph to a temporary buffer (as already is the case for when there is a point sample overlay) and see if a compositing mode besides `CAIRO_OPERATOR_ADD` can produce a good result.

On the other hand, the key thing seems not so much that the background color looks the same for each theme, as that the distinction between hues is legible.

**Comment by dtorop** [comment]
Interesting! The "Gosset + Interpolation type A - t * (B - A)" looks good enough. Does it make those strange net-like overlaps as in your screenshot at the bottom, though?

**Comment by phweyland** [comment]
> The "Gosset + Interpolation type A - t * (B - A)" looks good enough.

The background is built based the original Gosset RYB cube.

> Does it make those strange net-like overlaps as in your screenshot at the bottom, though?

The graph is built a reversed cube, which has been proposed on the link above.
This reversed cube doesn't work as shown by the graphs below.
Only the Junichi SUGITA, Tokiichiro TAKAHASHI model (gmic) is fully reversible and covers the full range of RGB values. While the background is not as smart as the Gosset one, it ensures the graph is coherent.

With gmic, the RGB span is well represented (chroma coherent along radius (different lightness)):

![image](https://user-images.githubusercontent.com/23012047/131218544-62a3c52d-f357-4933-8c29-cda3983c60c2.png)

With Gosset linear, see how the chroma varies with lightness:
![image](https://user-images.githubusercontent.com/23012047/131218729-0c1e3682-3083-4d99-934b-94d3c96ab4c3.png)
Accentuated with Gosset cubic (the 6 vertexes should appear, only 3 does):
![image](https://user-images.githubusercontent.com/23012047/131218782-1f6a5296-154b-4057-9998-c8cdbfb02aaf.png)

With a real image, referring to one of Johanna's video [here](https://www.youtube.com/watch?v=mC8ol2-V7Ck&t=792s): 

JzAzBz
![image](https://user-images.githubusercontent.com/23012047/131218827-2657c515-c0e6-4350-8ccf-54ad79959d49.png)

RYB gmic (not exactly the harmony presented by Johanna but close to).
![image](https://user-images.githubusercontent.com/23012047/131218853-734a7862-4e11-420c-b528-eb4e9fcae41c.png)

RYB Gosset linear (new orange, more yellow, ...)
![image](https://user-images.githubusercontent.com/23012047/131218863-a7774273-b18c-4398-b7ed-271da1110bec.png)

RYB Gosset cubic
![image](https://user-images.githubusercontent.com/23012047/131218884-658bb708-1c3d-43a1-93ff-c012cbea96f9.png)

**Comment by aurelienpierre** [comment]
I find concerning the fact that cyan is much more squeezed than other colors.

**Comment by phweyland** [comment]
> cyan is much more squeezed than other colors

True

**Comment by phweyland** [comment]
Idea: take the hues of Gosset vertex hues, and find the corresponding reversible function(hue). It would less compress the cyan, but keep chroma and lightness... spline ?

**Comment by phweyland** [comment]
Gosset hues + spline - extension red -> yellow / compression yellow to red

![image](https://user-images.githubusercontent.com/23012047/131249411-9175974b-f98c-4db3-8e51-f316e2f48011.png)


![image](https://user-images.githubusercontent.com/23012047/131249403-0ab4ec9a-5d82-467b-add8-3640c1168a74.png)

**Comment by blackwolf365** [comment]
Essentially, RGB and CMY are direct reflections of each other. The RYB model, however, is simply a flawed and duller version, developed in an era that lacked pure pigments
