### ISSUE TITLE
Simplified Rating System

### ISSUE THREAD

**Issue by AxionCDM** [darktable-org/darktable#9851]
(I am new to Darktable and GitHub, so I am truly sorry if I am doing this incorrectly)

**Is your feature request related to a problem? Please describe.**
I like to be efficient with my time and I find the granularity of the 5 star rating system for images too much.

**Describe the solution you'd like**
I would like to see the option to replace the 5-Star, Colors, and Rejected rating system replaced with a more simple Thumb Up, Thumbs Down, and (single) Star system. Thumbs down for Rejected, Thumbs Up for worth keeping and possibly spending time on, and Star for my best photos.

**Comment by christte** [comment]
Could you accomplish the same by assigning only rejected and 5-stars? Both are available through keyboard shortcuts. There is no requirement to use the entire scale.

**Comment by johnny-bit** [comment]
Do you know that the 5-star system is literally in ALL DSLRs and mirrorless cameras? and starts+labels are there to allow MORE freeedom to you not less. Culling/rating photos isn't some social media site.

**Comment by AxionCDM** [comment]
> Could you accomplish the same by assigning only rejected and 5-stars?

Yes, this is true and I will give that a try. Thanks for the suggestion! The option I suggested would clean up the interface a bit (and my brain-space) to 3 options/buttons and not 12; I am finding that the interface hits pretty hard. Also, I am a mouse user (with occasional keyboard input).

**Comment by AxionCDM** [comment]
> Do you know that the 5-star system is literally in ALL DSLRs and mirrorless cameras? and starts+labels are there to allow MORE freeedom to you not less. Culling/rating photos isn't some social media site.

Sorry, I don't mean to offend anybody with my suggestion.

**Comment by johnny-bit** [comment]
> Sorry, I don't mean to offend anybody with my suggestion.

Nobody's offended.

It's just that 5-star rating system is actually standard across whole industry. It's present in all digital cameras (probably not in smartphones, but even my ancient point&shoot from early 2000s has it) and in raw image processors.

It's in darktable (https://www.darktable.org/usermanual/3.6/en/lighttable/digital-asset-management/star-color/) where it has it's place in pre-processing workflow (https://www.darktable.org/usermanual/3.6/en/overview/workflow/import-rate-tag/). It's the same way in [Raw Therapee](https://rawpedia.rawtherapee.com/File_Browser) as well as [CaptureOne](https://support.captureone.com/hc/en-us/articles/360002743718-Rating-and-tagging), [Lightroom](https://helpx.adobe.com/lightroom-classic/help/flag-label-rate-photos.html), [Luminar](https://skylum.com/luminar/user-guides?category=chapter-10-rating-images), [AfterShot](http://product.corel.com/help/AfterShot/540111121/Main/IT/Documentation/index.html?labels_ratings_and_tags.html) and probably bunch of others... It's probably one of the most universal and ubiquitous concept in all of RAW editors where it comes to image organization... That's also why you can use ANY tutorial or article on how to develop your own way of rating images and never be hindered by lack of stars/color labels/tags.

> Also, I am a mouse user (with occasional keyboard input).

Keyboard shortcuts are great :) they speed up the workflow by short cutting :)

**Comment by Nilvus** [comment]
> > Could you accomplish the same by assigning only rejected and 5-stars?
> 
> Yes, this is true and I will give that a try. Thanks for the suggestion! The option I suggested would clean up the interface a bit (and my brain-space) to 3 options/buttons and not 12; I am finding that the interface hits pretty hard. Also, I am a mouse user (with occasional keyboard input).

Not for all users as 5 stars is a standard and it would just complexify options for many users that use actual rating system. I fear for you that your request will probably not be possible to implement. Suggestions you had here are probably the best.

**Comment by johnny-bit** [comment]
Closing since it's not possible to implement because it would break things for people who actually use the rating/labels in their cameras and their workflows.
