### ISSUE TITLE
Unexpected behaviour when importing files when using FILE_EXTENTION in the "sub directory naming pattern" of the copy & import dialog.

### ISSUE THREAD

**Issue by egelmex** [darktable-org/darktable#9863]
Unexpected behaviour when importing files when using FILE_EXTENTION in the "sub directory naming pattern" of the copy & import dialog. Folder names are not correct, and files end up being distributed amongst the created folders unexpectedly. 

**To Reproduce**
1. Go to "copy & import"
2. set the "sub directory naming pattern" option to `$(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY)_$(FILE_EXTENSION)`
3. import some files

Folders are created with name such as 
* 2021-08-11_10
* 2021-08-14_8
* 2021-08-16_6
* 2021-08-20_
* 2021-08-11_ARW
* 2021-08-14_ARW
* 2021-08-16_8
* 2021-08-20_%.2d
* 2021-08-11_Compression

with the imported files spread somewhat randomly amongst them.

```
.
├── 2021-08-21_
│   ├── 11-13-46_0002.ARW.xmp
│   ├── 11-13-46_0002.ARW
│   ├── 11-13-46_0001.JPG.xmp
│   ├── 11-13-46_0001.JPG
│   ├── 11-13-37_0004.ARW.xmp
│   ├── 11-13-37_0004.ARW
│   ├── 11-13-37_0003.JPG.xmp
│   ├── 11-13-37_0003.JPG
│   ├── 11-13-35_0006.ARW.xmp
│   ├── 11-13-35_0006.ARW
│   ├── 11-13-35_0005.JPG.xmp
│   └── 11-13-35_0005.JPG
├── 2021-08-20_Orientation
│   ├── 12-41-23_0032.ARW.xmp
│   ├── 12-41-23_0032.ARW
│   ├── 12-41-18_0034.ARW.xmp
│   └── 12-41-18_0034.ARW
├── 2021-08-20_Model
│   ├── 12-39-17_0037.JPG.xmp
│   └── 12-39-17_0037.JPG
├── 2021-08-20_JPG
│   ├── 13-00-00_0008.ARW.xmp
│   ├── 13-00-00_0008.ARW
│   ├── 12-41-22_0030.ARW.xmp
│   ├── 12-41-22_0030.ARW
│   ├── 11-25-49_0043.JPG.xmp
│   ├── 11-25-49_0043.JPG
│   ├── 11-22-07_0049.JPG.xmp
│   ├── 11-22-07_0049.JPG
│   ├── 11-16-10_0056.ARW.xmp
│   ├── 11-16-10_0056.ARW
│   ├── 11-16-10_0055.JPG.xmp
│   └── 11-16-10_0055.JPG
├── 2021-08-20_ExifVersion
│   ├── 12-59-53_0013.JPG.xmp
│   └── 12-59-53_0013.JPG
├── 2021-08-20_ARW
│   ├── 12-53-57_0020.ARW.xmp
```

**Expected behavior**
Folders names `2021-01-01_JPG` containing only JPG files, and `2021-01-01_ARW` containing only ARW files. 

**Screenshots**
![image](https://user-images.githubusercontent.com/474014/130355171-f71f625f-8c48-4722-a51e-2d8940b0039c.png)

**Platform**
* darktable version : 3.6.0
* OS                : Windows 10

This was also tested by "kofa" on IRC and had unexpected behavior on Linux.

**Comment by Mark-64** [comment]
Confirmed on DT git master. I will have a look

**Comment by Mark-64** [comment]
@egelmex can you test #9868?

**Comment by egelmex** [comment]
does the CI spit out a windows build of this? I don't have a setup that I can easily build this at the moment.
