### ISSUE TITLE
.NEF converted with Adobe DNG Converter can't find lens data

### ISSUE THREAD

**Issue by dfontenot** [darktable-org/darktable#9883]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
If I convert a .NEF using Adobe DNG Converter (13.1), I am not able to use the lens correction module on the resulting .dng file. The lens correction module says that it can't find the lens, but if I load the original .NEF file in Darktable and use the lens correction module on it, it can find the lens data.

I've confirmed that my lensfun database is up to date by running `lensfun-update-data`.

The lens data on the .dng file (according to exiftool). This matches what's in the .NEF file.
Lens ID                         : AF-P DX Nikkor 18-55mm f/3.5-5.6G
Lens Spec                       : 18-55mm f/3.5-5.6 G VR AF-P

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Convert a .NEF into a .dng with Adobe DNG Converter
2. Load the .dng file into Darktable
3. Go to the lens correction module

**Expected behavior**
The lens correction module to work on the .dng file

**Platform**

* darktable version : 3.6.0
* OS                : Linux 5.11.0-27-generic
* Linux - Distro    : e.g. Ubuntu 20.04
* Memory            : 16 GB
* Graphics card     :  GTX 960
* Graphics driver   :  Nvidia
* OpenCL installed  :  yes
* OpenCL activated  :  yes

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **NEF**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? Not able to change configdir to /tmp, run into a core dump:
 -  - Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
[1]    36091 abort (core dumped)  darktable --configdir "/tmp"
 - Do you use lua scripts? No

**Comment by dfontenot** [comment]
@johnny-bit Do you know which exif tags are in use for the lens correction module? And do you know which version of the exiv2 library is bundled with Darktable 3.6.0? I noticed something strange when loading these raw images with exvi2.

I checked out these images with the exiv2 command line tool (version 0.27.2), and I noticed that I exiv2 can't load (for example) tag Exif.Image.LensInfo on the original .NEF, but it can load it on the converted .dng. Please let me know if there are some other tags that I should check.

`exiv2 -g Exif.Image.LensInfo -Pv DSC_2062.NEF` (fails)
`exiv2 -g Exif.Image.LensInfo -Pv DSC_2062.dng`
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
180/10 550/10 35/10 56/10

I get the above error when trying to load any tag with exiv2.

Other tags I tried:
* Exif.Photo.LensSpecification (works only for the .dng)
* Exif.Photo.LensMake (does not work on either)
* Exif.Photo.LensModel (works only for the .dng)

**Comment by johnny-bit** [comment]
No idea. Plz check with exiv2 project on GitHub.

**Comment by kmilos** [comment]
In a NEF this is actually located in a different tag, like `Exif.NikonLd3.LensIDNumber`.

**Comment by kmilos** [comment]
Btw, the full lens name expected by lensfun seems to preserved by the DNG converter in the Exif IFD (`LensModel` tag):

```
$ exiv2 -Pkt -g Lens _DSC0018.dng
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
Exif.Photo.LensSpecification                  160/10 500/10 350/100 630/100
Exif.Photo.LensMake                           NIKON
Exif.Photo.LensModel                          NIKKOR Z DX 16-50mm f/3.5-6.3 VR
Exif.Photo.LensSerialNumber                   30003966
Exif.Image.LensInfo                           160/10 500/10 350/100 630/100
Xmp.aux.LensInfo                              160/10 500/10 350/100 630/100
Xmp.aux.Lens                                  NIKKOR Z DX 16-50mm f/3.5-6.3 VR
Xmp.aux.LensSerialNumber                      30003966
Xmp.exifEX.LensModel                          NIKKOR Z DX 16-50mm f/3.5-6.3 VR
```

So there still might be some things to check on the dt side re the plumbing of this...

**Comment by kmilos** [comment]
Ah, this conversion behaviour seems to be (body/lens?) model dependent... Indeed with my own D5600 and same lens as OP, the `Exif.NikonLd3.LensIDNumber` is chopped when translated to 'Exif.Photo.LensModel'...

Not sure how to get around this in dt (apart from reporting to Adobe), as the original makernote is no longer readable by exiv2 (might be something to improve anyway).

**Comment by kmilos** [comment]
Looks like Adobe uses the LCP file if available for translation into `Exif.Photo.LensModel` (for the OP lens it is `NIKON D3300 (Nikon AF-P DX NIKKOR 18-55mm F3.5-5.6G VR) - RAW.lcp`), but some other method if not (like the Z mount example).

Snippet from the said LCP file:

```
       stCamera:LensID="160"
       stCamera:Lens="18.0-55.0 mm f/3.5-5.6"
       stCamera:LensInfo="180/10 550/10 35/10 56/10"
       stCamera:LensPrettyName="Nikon AF-P DX NIKKOR 18-55mm f/3.5-5.6G VR"
```

If only the used the `LensPrettyName`... :sigh:
