### ISSUE TITLE
better display of colorpicker samples in histogram and waveform

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#9899]
**Is your feature request related to a problem? Please describe.**
When the histogram and waveform can be limited to the current point sample, the display becomes slightly absurd. In the case of histogram, we see three peaks for the red/green/blue levels:

![image](https://user-images.githubusercontent.com/2311860/131237602-0fe8dbba-9234-47f5-a33d-1ae530a1c723.png)
In the case of waveform, we see three lines:

![image](https://user-images.githubusercontent.com/2311860/131237366-545b333e-f319-45fc-812d-0a17b37f255f.png)

While this literally follows the instructions "restrict scope", the readout is strange, and doesn't provide context in the image. It is also inconsistent with how vectorscope handles point samples. Vectorscope shows (dimmed) the entire scope for context, and draws a point on the scope to represent the current sample.

![image](https://user-images.githubusercontent.com/2311860/131237400-6602cd25-64bc-45b7-b488-57e77915ef8b.png)

**Describe the solution you'd like**

As with vectorscope, histogram and waveform should dim the non-restricted scope and show an overlay representing the point sample.

For histogram, this can be similar to how rgb curves handles display of point samples:

![image](https://user-images.githubusercontent.com/2311860/131237459-4f881f8e-2c43-41cd-a101-9fd0720125b9.png)

The histogram would display three vertical lines to represent the red, green, and blue components of the current point sample.

For waveform, this would be similar to the vectorscope presentation. The waveform would show three circles, colored red/green/blue, to represent for each channel the position (1-dimensional) and brightness of each sample value.

**Alternatives**

This could also expand to rendering box samples via an overlay as well. I think this is a less good idea. It's nice to see a box sample in the scope as if we are rendering a scope of a crop of an image. And the way RGB curves renders box samples in the histogram (a shaded area from minimum to maximum lightness), while useful, doesn't give the sense of the specifics of the histogram of that area.

**Additional context**

There is work to display live samples (#9866) in vectorscope. It could be interesting to come up with a system to display live samples in other scopes as well.

Visibility of the red/green/blue overlays may be an issue, particularly for blue. The solution may be as simple as providing a contrasting neutral outline around the point/line.

I'd be happy to code this as time allows.

**Comment by Mark-64** [comment]
Live samples are displayed in color zones, tone curve and rgb curve as vertical lines / bands, but only if the module color picker is active.
Maybe we want to make the sample visualization behavior uniform across the gui ?

**Comment by MStraeten** [comment]
this might make sense if color picker is in point mode. But there’s also a valid scenario to have the current behaviour in waveform too: to do a manual white balance: bringing those three lines in line

In my opinion it doesn’t make sense if an area is picked, the content can spread over the whole range - an overlay would be meaningless because no restriction to the content of the picked area is visible..

In vectorscope it’s quite different: since it’s hard to see a dot in the scope it makes sense to put the mark on the dimmed scope

**Comment by dtorop** [comment]
> current behaviour in waveform too: to do a manual white balance: bringing those three lines in line

This would be possible if dots (or ellipses?) are displayed for a point sample in waveform. The point sample would be neutral when the samples from each channel overlap. In the case of horizontal waveform, they would all have the same x-position and neutral would mean y-position alignment. In the case of vertical waveform, they would all have the same y-position, and the x-position would need to be aligned.

**Comment by phweyland** [comment]
What about using a complementary color of the background color at the dot's position?

**Comment by todd-prior** [comment]
@dtorop  Nice progress on this Dan, one thing I notice is in the vectorscope when restricting to selection the way it is redrawn it is hard to see on many occasions. The dot is lovely and clear for point selections but the range sometimes produces only a few faint speckles on the  plot.....I wonder if there would be a way to improve the visibility here???

**Comment by Mark-64** [comment]
> the range sometimes produces only a few faint speckles on the plot

Yes, also areas of uniform color are represented by few points, no matter how large they are, eventually one point only in case for example of color palettes overlaid with watermark module.
As the cromaticity data is put into bins to draw vectorscope, an idea could be to draw each bin with a size depending on the count, or better on the %of total?
This way uniform color areas or restricted selection would have bigger "pixels" on the drawing.
Not sure if this is possible / computationally expensive with cairo, though.
