### ISSUE TITLE
SIGSEGV when cropping (preview update?)

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9900]
**Describe the bug/issue**
I was working on an image, using the crop module. My mouse is a bit flaky, so while dragging the crop rectangle's corner, sometimes it thinks I'm already done, although I did not release the mouse button. I started dragging it again, and darktable crashed. I'm not at all sure this is easy to reproduce; I've processed quite a few images today and didn't have a problem until this one.

**To Reproduce**
1. Use the crop module in the darkroom.
2. Darktable crashes.
3. See backtrace
[darktable_bt_GG5K80.txt](https://github.com/darktable-org/darktable/files/7072204/darktable_bt_GG5K80.txt)

**Expected behavior**
No crash

**Which commit introduced the error**
No idea. I last updated a few days ago; but given the erratic nature of the issue, it may have been there for quite a while.

**Platform**
* darktable version : 3.7.0+899~ga8833f00f
* OS                : Linux - kernel 5.11.0-31
* Linux - Distro    : Ubuntu 21.04
* Memory            : 64 GB
* Graphics card     : NVidia 1060/6GB
* Graphics driver   : 460.91.03-0ubuntu0.21.04.1
* OpenCL installed  : nvidia-opencl-dev:amd64 version 11.2.2-1ubuntu1 
* OpenCL activated  : yes
* Xorg              : 1:7.7+22ubuntu1
* Desktop           : KDE 5.80.0-0ubuntu1 
* GTK+              : 3.24.25-1ubuntu4.1 
* gcc               : 10.3.0
* cflags            : none
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Comment by AlicVB** [comment]
hmmm... I can't reproduce on my side, but as you said it's not so easy to trigger...
That said, considering the backtrace, the fix seems quite simple : see PR #9901

**Comment by kofa73** [comment]
Thank you.
