### ISSUE TITLE
3.6 user manual - color checker white patch as "20% reflective"?

### ISSUE THREAD

**Issue by ellelstone** [darktable-org/darktable#9902]
darktable 3.6 user manual: https://www.darktable.org/usermanual/3.6/en/special-topics/color-pipeline/

says this:

display-referred
    Pixel values are expected to lie between 0 and 100% of the display range, where **100% is understood to be the luminance of a 20% reflective white surface (the white patch of a Color Checker)** and 0% is understood to be the maximum density of the output medium (saturated black ink or minimum LED panel backlighting).

The value "20% reflective" for the Color Checker white patch seems very low - how is "reflective" defined here? 

The **reflectance** (https://en.wikipedia.org/wiki/Reflectance) of white paper can reach 90%. 

https://chromaxion.com/information/ColorChecker_Passport_Technical_Report.pdf says the reflectance of the white balance chart (which is roughly the same as neutral patch 8, so gray rather than "white") is about 60%.

So I was curious whether the "20%" value is a typo, or whether "reflective" as used in the darktable manual means something other than "reflectance".

**Comment by johnny-bit** [comment]
please address documentation issues here: https://github.com/darktable-org/dtdocs/issues/new and close this one. thanks!
