### ISSUE TITLE
Customize image export interface

### ISSUE THREAD

**Issue by zener78** [darktable-org/darktable#9911]
Hi, I’m trying to customize image export via script based on the Lua API darktable.register_storage; this API calls a widget: types.lua_widget, with which I can customize the interface, adding new panels but I can’t remove previus panels like “format options” and “global options” as in the attached picture.

The issue is:
since I can create my interface adding panels as above, I'd like to be able to remove basic panels to free space on screen.
I thank you for that possibility.

![immagine](https://user-images.githubusercontent.com/89864660/131546334-10f0f7d5-0d0b-45e1-bc93-1aa8c02fdbb5.png)

**Comment by dterrahe** [comment]
#12415 and #12338 may (or may not!) be of use to you.
