### ISSUE TITLE
Image orientation on dt_lua_image_t data type

### ISSUE THREAD

**Issue by zener78** [darktable-org/darktable#9912]
Hi. In a my Lua script I need to know the correct frame ratio of selected images but I find from image.width and image.height dimensions with no correct orientation as I can already see on the screen.

May you add, for instance, output_width, output_height and orientation to be exposed as part of the dt_lua_image_t data type, please?

Thanks.

**Comment by jhaiduce** [comment]
I have a need to set/change the image orientation from a Lua script. I imagine that attribute could be made writable once exposed through the dt_lua_image_t?

**Comment by wpferguson** [comment]
Did a quick test.  Opened a new copy of darktable.  Imported a set of images.  Opened a console and opened the library database with sqlite3.  Checked the orientation of image 1 and the value was 6.  Selected the image in lighttable and rotated it 90 degrees CCW.  Check the orientation value and it was still 6.  Stopped darktable to ensure it flushed everything to the database, then check the value and it was still 6.  Stopped and restarted sqlite3 (to make sure it wasn't using a cached copy).  Checked the orientation value of image 1 and it was still 6.  

So, this confirms what I remember which is that orientation does not reflect the current image orientation.  I'd have to dig thru the code to see how the actual image orientation is tracked and changed.

**Comment by wpferguson** [comment]
> I have a need to set/change the image orientation from a Lua script. I imagine that attribute could be made writable once exposed through the dt_lua_image_t?

Changing the orientation field wont change the image orientation.  A dt_lua_image_t flip function could be added to change the image orientation, but that should be a separate issue.

**Comment by jhaiduce** [comment]
> A dt_lua_image_t flip function could be added to change the image orientation, but that should be a separate issue.

Thanks for looking into that. I'll open a new issue.
