### ISSUE TITLE
guides lines desynchronized

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#9915]
**Describe the bug/issue**

The guides buttons is enabled but the lines are not drawn, clicking on the button will display the line but deactivate the button!

**To Reproduce**
1. Go to 'darkroom'
2. Click on he 'guide' toggle button bottom-right
3. Quite darktable
4. Restart it and go to 'darkroom'
5. See guide button is activated, no guide lines displayed
6. Click the guide button, it is now deactivated but the lines are displayed

**Expected behavior**

Button status should properly reflect the guide status.

**Platform**

* darktable version : master
* OS                : Linux - GNOME
* Linux - Distro    : Debian/sid

**Comment by TurboGit** [comment]
@dterrahe : Possibly a regression due to new InputNG ? If not maybe this is due to recent changes from @AlicVB ?

**Comment by dterrahe** [comment]
Do you still see this after #9894 ? It contains some fixes for issues like this.

**Comment by TurboGit** [comment]
@dterrahe : No, with #9694 all is working as expected. Thanks !
