### ISSUE TITLE
In the custom module presets, the drawn mask should also be saved

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#9918]
Sometimes it is also necessary to save a drawn mask in the module preset. 

For example, since there is no vignetting correction for most of my lenses in Lensfun database, I try to make a preset with the help of exposure module by creating a mask with inverted circle:

The photo without correction:

![devignette1](https://user-images.githubusercontent.com/38165484/131690109-607a2f98-5d97-4cf8-b458-a87950a408f2.jpg)

Inverted drawn mask (circle):

![devignette2](https://user-images.githubusercontent.com/38165484/131690245-353cf80d-0b0a-4486-9012-ba1cee0c8d43.jpg)

Vignetting correction: 

![devignette3](https://user-images.githubusercontent.com/38165484/131690484-55170203-bd3f-4343-86c5-b75b70dd4369.jpg)

Now I want to save this as a preset of the exposure module, so that I don't have to create the mask again. Unfortunately this is not possible, because the drawn mask is not saved with the preset.

**Comment by jenshannoschwalm** [comment]
That would be VERY tricky and would require a complete redesign of modules parameters for all modules imho.

Is vignetting module used with auto preset not good enough?

**Comment by s7habo** [comment]
Thanks for your reply @jenshannoschwalm 

> Is vignetting module used with auto preset not good enough?

No, because brightness option does not increase the exposure in that area but only makes it whiter. 

Here is another example.

Without:

![devignette4](https://user-images.githubusercontent.com/38165484/132088884-5ec9bac8-72eb-4eb0-8b3e-c3a7b3bb2130.jpg)

With:

![devignette5](https://user-images.githubusercontent.com/38165484/132088903-bdd011f5-69ef-4866-b9bf-6f5d96d61c9f.jpg)


You see how the edges become "grayer" and local contrast is lost even though the "saturation" option is set to maximum.

It gets a bit better if you use "lightness" blend mode...

![devignette7](https://user-images.githubusercontent.com/38165484/132089038-d8f38fec-4d5a-4715-bbe9-6de9348e8a17.jpg)

...but it becomes even more problematic if you increase the contrast in the pixelpipe before:

![devignette8](https://user-images.githubusercontent.com/38165484/132089080-59cf2c71-db41-4991-953b-44282a673833.jpg)

I tried it and the result is the following:

![devignette9](https://user-images.githubusercontent.com/38165484/132089347-a5aa65f2-a8a9-45da-a99a-8c050bc41599.jpg)

It looks better, but still, the above problem persists.

Exposure module is much better because besides correct exposure correction, you can also use mask refinement:

![devignette11](https://user-images.githubusercontent.com/38165484/132089861-08faf417-f7c7-4104-8e84-b6c8099ca0e5.jpg)



Final result:

![devignette12](https://user-images.githubusercontent.com/38165484/132089901-e4d4a0a8-9adc-42e0-a8c1-bb4d154b63fb.jpg)

**Comment by jenshannoschwalm** [comment]
Ok, agreed. I'll think about it... I understand your desire for a full mask setup.

Wouldn't a manually defined vignette for lens correction be a better way?

**Comment by s7habo** [comment]
> Wouldn't a manually defined vignette for lens correction be a better way?

Absolutely! This would be the most ideal solution!  For example, earlier also the automatic correction of cromatic abberation that comes with Lensfun was not always ideal. Since additional correction is also possible manually within the lens correction module, for me the problem has been solved. If I can additionally correct vignetting manually as well, that would be a dream. 

In any case, thanks for your effort.

**Comment by benp456** [comment]
Just to add another use case for drawn masks in presets. Some lenses have a type of chromatic aberration (one species of blue/purple fringing) that is field dependent (worse in the corners) but different from the TCA that can be corrected by the lens correction module. In darktable you can address this with the contrast equaliser or chromatic aberrations module, but these desaturate details across the whole frame, so it's desirable to limit the effect to the corners with a mask exactly as in the vignetting example above. The ability to apply that correction automatically via a module preset would be very nice for people living with these compromised lenses.

Examples of lenses showing this kind of problem - Nikon 18-55 AF-P, Canon PowerShot G5X Mark II.

(And like with vignetting... the full flexibility of drawn masks is not needed, so another solution would be to add a couple of parameters to the chromatic aberrations module to define a feathered circular mask.)
