### ISSUE TITLE
missing lens correction preset

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#9932]
v3.6.0

Previous versions had the lens correction among the presets.

Now opening the options - presents, lens correction isn't available, and supposedly cannot be saved as a preset

**Comment by domosbg** [comment]
In Options - Presets are only the modules shown which have already presets. If there are no presets for a module the module is not shown in Options - Preset. But you can add new presets in the darkroom, if you click on the toast (three line) menu in the module header. After adding a preset the module is shown in Options - Presets.

**Comment by Nilvus** [comment]
In 3.6, presets only appear if there's some. So as @domosbg, you can save them from darkroom one (with module settings so!). You also have an option in preferences to display or not default darktable presets. Think about closing this issue when it's ok for you.
