### ISSUE TITLE
Map view: magnetic effect when dropping an image near another

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#9934]
v3.6.0

In map view at maximum zoom level, with some image already on the map:
- drag another image from the bottom thumbnails
- drop it near the one which is already on the map -> the new image is attracted by the old one, you cannot position it some 10px apart

**Comment by phweyland** [comment]
Hi Paolo, this is only an appearance...
Images are displayed grouped to save time and power. See "group size factor" and "min image per group" in "map settings".

**Comment by paolobenve** [comment]
@phweyland thank you for your expication! :-)

I cannot find  "group size factor" nor "min image per group" nor "map settings" in darktable preferences... Where are they?
