### ISSUE TITLE
add to library dialog: no preview for dng when the eye is clicked

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#9935]
v3.6.0

In the "Add to library" dialog, add a folder with jpg images: when the jpg images are listed, clicking the eye at the right of name and modified date-time shows a preview of the image

On the contrary, with dng images, clicking the eyes only shows a darktable icon.

On my personally compiled 3.6.0+cr3 support the cr3 images shows the darktable icon too.

**Comment by johnny-bit** [comment]
Fixed in https://github.com/darktable-org/darktable/pull/9638
