### ISSUE TITLE
Question: memory leaks in conf.c ?

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#9936]
Working on #9930, I am looking into conf.c and I see many things like

```
void dt_conf_set_int(const char *name, int val)
{
  char *str = g_strdup_printf("%d", val);
  if(dt_conf_set_if_not_overridden(name, str)) g_free(str);
}
```

and inside `dt_conf_set_if_not_overridden()`

`g_hash_table_insert(darktable.conf->table, g_strdup(name), str);`

Aren't we leaking memory here? Or am I missing something?

**Comment by dterrahe** [comment]
If `g_hash_table_insert` is called a second time with the same `name`, it first frees both the old name and the old str before inserting the new one. So it shouldn't be leaking `names`...

(because of `cf->table = g_hash_table_new_full(g_str_hash, g_str_equal, g_free, g_free);`)

**Comment by Mark-64** [comment]
ok, thank you for clarifying
Closing
