### ISSUE TITLE
segfault opening gpx file

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#9940]
3.6.0

I have darktable opened with many images, I go to map view, and then open a gpx file

I get the attacched error
[error.txt](https://github.com/darktable-org/darktable/files/7112377/error.txt)

**Comment by phweyland** [comment]
Can you share the gpx file?

**Comment by paolobenve** [comment]
I cannot reproduce any more the issue... I think I had some corrupted dng images, possibly they produced the crash
