### ISSUE TITLE
Move diffuse or sharpen after color calibration

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9942]
**Describe the bug/issue**
Based on https://discuss.pixls.us/t/diffuse-or-sharpen-position-in-pixelpipe/26536, _diffuse or sharpen_ should be placed after _color calibration_.

**Comment by Nilvus** [comment]
@aurelienpierre: as you work on those modules and answer in related pixl.us discussion, I assigned it to you.

**Comment by piratenpanda** [comment]
wasn't this fixed by
https://github.com/darktable-org/darktable/commit/13dd76c5919955d65245200bd3507e483d689129
?

**Comment by Nilvus** [comment]
Indeed. Thanks for pointing that. Closing so.
