### ISSUE TITLE
Tagging: unassigned partially matched tags will be written to export

### ISSUE THREAD

**Issue by grubernd** [darktable-org/darktable#9949]
**Describe the bug/issue**

Any tag that partially matches an assigned tag from the beginning will be also written to the exported files.

In crude regex: `^.*`

**To Reproduce**

1. Have a tag in your collection, does not need to be used in the current library. e.g. `tree`
2. Assign an extended variant of that tag to an image, e.g. `tree-hugger`
3. Do NOT assign `tree` to that image
4. Export
5. Check metadata: both `tree-hugger` (as expected) and `tree` (not expected) will be there

**Further notes**

The export will respect the rules associated with _private_ tags.

Tags set as _category_ will not be exported.

With a large enough tag collection this can lead to some very unexpected tag exports. For example any short number like `1` will be exported together with anything that also starts with 1, wether it is `10` or `1world`. Same goes for short words, compound words and so on.

**Platform**

* darktable version : 3.6.0 on BunsenLabs Lithium (debian 10)

**Comment by phweyland** [comment]
I'll at this. Thanks for reporting.

**Comment by phweyland** [comment]
> The export will respect the rules associated with private tags.
> Tags set as category will not be exported.

Have you found any issue related to those ?

**Comment by grubernd** [comment]
> > private tags
> > categories
> 
> Have you found any issue related to those ?

No.

But I found that the matching goes across the full hierarchy if that wasn't clear from the initial report.
So `tree|birch` will trigger an export of `tree` even if "omit hierarchy" is set to on.

**Comment by phweyland** [comment]
Yes, omit hierarchy is a very old settings which could be removed now, but I've avoid to change the old logic. His purpose is to avoid to export the elements of the path if they are not themselves a tag. With new logic you set those elements as category to prevent to export them.
