### ISSUE TITLE
geotagging by gpx file: set coordinates through interpolation

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#9950]
It looks like darktable, when geotagging images through a gpx file, assigns latitude/longitude choosing one of the points in the gpx file.

I wish it were not choosing one of the point, but interpolating between the last of the previous (temporarily) points and the first of the following ones.

Use case 1
====== 

Last month I flyed across the Atlantic Ocean, and took some photo in the middle of the Ocean. I had begun recording the gpx with OSMAnd before leaving in order to geotag the photos. Unfortunatly, the airplane isn’t transparent to gpx satellite signals, so my gpx file only took the points before entering and after exitibg the aircraft.

As darktable works currently, through that gpx file I get the photo geotagged at the airports of departure and arrival.

Use case 2
======

The app that generates the gpx file is set to record a point every minute, but the user moves a certain space every minute and shoots various photos, so the photos would remain stuck at the points where the gpx fixed the coordinates

**Comment by kmilos** [comment]
FWIW, could leverage the `proj` library for this ([minimal C implementation needed of the full GeographicLib](https://geographiclib.sourceforge.io/html/C/index.html)), as it seems to be [widely available](https://repology.org/project/proj/information).

Python example:  https://stackoverflow.com/questions/38451828/how-to-iterate-between-two-geo-locations-with-a-certain-speed-in-python3

**Comment by HansBull** [comment]
Maybe you could apply your gpx file directly to the rawfiles with exiftool. The documentation at https://exiftool.org/geotag.html states: `The GPS track log file is loaded, and linear interpolation is used to determine the GPS position at the time of the image`

**Comment by kmilos** [comment]
[Linear interpolation doesn't work that well for "use case 1"](https://gisgeography.com/great-circle-geodesic-line-shortest-flight-path/), but is an ok approximation and this is indeed a very neat way of addressing "use case 2".

**Comment by phweyland** [comment]
On the principle I don't disagree with the suggested change but I don't find the 2 use cases motivating.
1. if GPS doesn't work one should not rely on it. In any case the position is inaccurate.
2. Set GPS points every minutes doesn't seem appropriate. Usually you can constrain the distance too to avoid the lack of accuracy, or at least set a period more compatible with the speed.

**Comment by paolobenve** [comment]
The gpx track has to be drawn by geodesic interpolation, too

**Comment by phweyland** [comment]
> The gpx track has to be drawn by geodesic interpolation, too

Why ? What is the benefit ?

**Comment by paolobenve** [comment]
> > The gpx track has to be drawn by geodesic interpolation, too
> 
> Why ? What is the benefit ?

In order to address the first use case.

**Comment by paolobenve** [comment]
Here is the difference:

1. without this PR: the three images are set at the beginning of the line, which is straight:
![non-geodesic-non-interpolation](https://user-images.githubusercontent.com/1417508/133127426-c24b719a-30a7-4caa-b440-d94be853db0a.png)


2. with this PR: the images are set at there position according to timestamp, and the line is the geodesic one
![geodesic](https://user-images.githubusercontent.com/1417508/133127131-8c720d81-2380-4e03-b0d9-f62a646374d8.png)

**Comment by phweyland** [comment]
Looks great. Why do we have a small straight segment on Madrid side ?

**Comment by paolobenve** [comment]
Because the track has 4 points
