### ISSUE TITLE
documentation: links inverted in module groups article

### ISSUE THREAD

**Issue by twigit** [darktable-org/darktable#9954]
In [this page](http://www.darktable.org/usermanual/3.6/en/darkroom/organization/module-groups/) of the 3.6 manual, the section "workflow: scene-referred & workflow: display-referred" contains a link towards articles about these worflows. These links are inverted : "scene-referred" link points towards display-referred article, and _vice versa_

**Comment by Nilvus** [comment]
documentation repository is not here. Please post related issues here: https://github.com/darktable-org/dtdocs/issues
