### ISSUE TITLE
darktable preferences/presets - modules collapse after action

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#9956]
**Is your feature request related to a problem? Please describe.**
In darktable preferences if users are making some action to presets with modules expanded, editing or deleting, after the action the module collapse it content. This is not a nice behaviour  because if users like to edit some presets then have to expand the module every time they like to edit them.

**To Reproduce**
1. Go to darktable preferences
2. Click on presets
3. Scroll down to any module and expand it content
4. Edit or delete a preset
5. See the "error" - the module collapse it content.

**Describe the solution you'd like**
Users must have the choice to edit some presets without have to expand the module every time they are editing the options.

**Additional context**

https://user-images.githubusercontent.com/67672868/132386313-6faa36f2-f0be-4443-83d1-dee61695b124.mp4

**Comment by paolobenve** [comment]
trying to fix it

**Comment by paolobenve** [comment]
actually the module is collapsed even if the OK button is pressed, while it's not collapsed when the cancel button is pressed

**Comment by paolobenve** [comment]
Actually was a known issue, the code documented two possible ways to solve it:
- saving expanded/collapsed modules state and restoring it
- modifying/deleting only the current preset, without clearing/refilling the whole preset list

I implemented the 2nd way.

**Comment by difrkaguilar** [comment]
> I implemented the 2nd way.

Great. this can be a solution at least for this issue. Thanks a lot for your support.
