### ISSUE TITLE
Crop doesn't work when color picker is active

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#9965]
**Describe the bug/issue**
When color picker is active the crop handles are not visible. When moving the around the image the cursor changes where the crop handles are, but if you try to drag it only moves the picker area. Also, if there is already a previous crop the cropped area is not shown in dark. The same thing happens for both point and area picker.

**To Reproduce**
1. Open an image in darkroom
2. Activate color picker
3. Open crop (or crop and rotate)
4. No crop handles visible
5. De-activate color picker
6. See the crop handles

**Expected behavior**
Having color picker active shouldn't impact crop/crop and rotate module or there should be information to the user why the crop is not active.

**Which commit introduced the error**
Don't know

**Platform**
* darktable version : 3.7.0+1014~g6b4283c47
* OS                : Win10

**Additional context**
Same issue with my Ubuntu VM

**Comment by Mark-64** [comment]
I think this is by design, not only for crop, but for all modules displaying an overlay: graduated density, tone equalizer, color checher in color calibration, etc.
Only one overlay can be displayed at once

**Comment by domosbg** [comment]
Maybe it would help if the mouse cursor design is changed if the color picker is active. Then it is easier to see that e.g. croping is actaully not possible because of an active color picker.
