### ISSUE TITLE
darktable won't start on macOS

### ISSUE THREAD

**Issue by mariussteffen** [darktable-org/darktable#9966]
Hi,

even after deleting darktable's .config and .cache subdirectories, I can't get it to start on macOS - running with '-d all' gives:

```
Marius MacBook Pro:MacOS marius$ ./darktable -d all
0.000788 application_directory: /Applications/darktable.app/Contents/MacOS
0.000936 darktable.datadir: /Applications/darktable.app/Contents/Resources/share/darktable
0.001029 darktable.plugindir: /Applications/darktable.app/Contents/Resources/lib/darktable
0.001109 darktable.localedir: /Applications/darktable.app/Contents/Resources/share/locale
0.001359 darktable.configdir: /Users/marius/.config/darktable
0.001570 darktable.cachedir: /Users/marius/.cache/darktable
0.001670 darktable.sharedir: /Applications/darktable.app/Contents/Resources/share
0.001768 darktable.tmpdir: /private/var/folders/z7/yvzjffb51d59g5pzjzrdkgrw0000gn/T
[memory] at startup
[memory] max address space (vmpeak):         unknown
[memory] cur address space (vmsize):      4523292 kB
[memory] max used memory   (vmhwm ):         unknown
[memory] cur used memory   (vmrss ):        11896 kB
0.001829 new_xdg_data_dirs: (null)
```

After that, the app seems to cease any CPU activity, practically being dead. No GUI whatsoever starting.

macOS version: 11.5.2
darktable version: 3.6.0.3
Running on MacBook Pro 15" 2017

**Comment by Nilvus** [comment]
Please test last darktable release (3.6.1) here: https://github.com/darktable-org/darktable/releases/tag/release-3.6.1.
As you can see here #10087, the issue should be solved by using 3.6.1.6 dmg package (bottom of the page). I so close. If needed, ask for reopening with tests done and new information.

**Comment by parafin** [comment]
It’s not related to #10087, maybe instead to #10065. But indeed please test with latest release and please see #10065 for possible workaround, we’ll reopen if it’s not the same issue.

**Comment by GiovanniBianchessi** [comment]
> Hi,
> 
> even after deleting darktable's .config and .cache subdirectories, I can't get it to start on macOS - running with '-d all' gives:
> 
> ```
> Marius MacBook Pro:MacOS marius$ ./darktable -d all
> 0.000788 application_directory: /Applications/darktable.app/Contents/MacOS
> 0.000936 darktable.datadir: /Applications/darktable.app/Contents/Resources/share/darktable
> 0.001029 darktable.plugindir: /Applications/darktable.app/Contents/Resources/lib/darktable
> 0.001109 darktable.localedir: /Applications/darktable.app/Contents/Resources/share/locale
> 0.001359 darktable.configdir: /Users/marius/.config/darktable
> 0.001570 darktable.cachedir: /Users/marius/.cache/darktable
> 0.001670 darktable.sharedir: /Applications/darktable.app/Contents/Resources/share
> 0.001768 darktable.tmpdir: /private/var/folders/z7/yvzjffb51d59g5pzjzrdkgrw0000gn/T
> [memory] at startup
> [memory] max address space (vmpeak):         unknown
> [memory] cur address space (vmsize):      4523292 kB
> [memory] max used memory   (vmhwm ):         unknown
> [memory] cur used memory   (vmrss ):        11896 kB
> 0.001829 new_xdg_data_dirs: (null)
> ```
> 
> After that, the app seems to cease any CPU activity, practically being dead. No GUI whatsoever starting.
> 
> macOS version: 11.5.2 darktable version: 3.6.0.3 Running on MacBook Pro 15" 2017

Same problem here.
No interface and no acivity, no application runnning in Finder
.config/darktable folder is empty
Darktable 4.0 just downloaded and previous version too.

iMacdiGiovanni:MacOS giovanni$ ./darktable -d all
0.000696 application_directory: /Applications/darktable.app/Contents/MacOS
0.000763 darktable.datadir: /Applications/darktable.app/Contents/Resources/share/darktable
0.000801 darktable.plugindir: /Applications/darktable.app/Contents/Resources/lib/darktable
0.000836 darktable.localedir: /Applications/darktable.app/Contents/Resources/share/locale
0.000899 darktable.configdir: /Users/giovanni/.config/darktable
0.000940 darktable.cachedir: /Users/giovanni/.cache/darktable
0.000979 darktable.sharedir: /Applications/darktable.app/Contents/Resources/share
0.001060 darktable.tmpdir: /private/var/folders/1n/r4p2hcgc8xj9dr0059blbdf80000gv/T
[memory] at startup
[memory] max address space (vmpeak):         unknown
[memory] cur address space (vmsize):     34311388 kB
[memory] max used memory   (vmhwm ):         unknown
[memory] cur used memory   (vmrss ):        12860 kB
0.001076 new_xdg_data_dirs: (null)

iMac (Retina 4K, 21.5-inch, 2019)
3 GHz Intel Core i5 6 core
16 GB 2667 MHz DDR4
Radeon Pro 560X 4 GB

MacOs 12.5 Monterey

Regards
Giovanni Bianchessi
