### ISSUE TITLE
Website link errors

### ISSUE THREAD

**Issue by bigntallmike** [darktable-org/darktable#9969]
(If there's a different place to report this please let me know)
The blog entry links on https://www.darktable.org/about/features/ are broken.  
For instance, "https://www.darktable.org/blog/2016-05-24-colour-manipulation-with-the-colour-checker-lut-module/2016-05-24-colour-manipulation-with-the-colour-checker-lut-module.md" which leads to a 404.

**Comment by elstoc** [comment]
The darktable website repository is on darktable-org/dtorg. Please raise an issue there.

**Comment by johnny-bit** [comment]
Closing since website issues should be opened on website repo.
