### ISSUE TITLE
X-Rite ColorChecker Passport support

### ISSUE THREAD

**Issue by bigntallmike** [darktable-org/darktable#9970]
**Feature request**
I was thrilled to see that proper color checker support has been added to darktable, but unfortunately I use an X-Rite ColorChecker Passport, the smaller more portable device seen here: [X-Rite ColorChecker Passport](https://www.xrite.com/categories/calibration-profiling/colorchecker-classic-family/colorchecker-passport-photo-2)
Is there any plan to add support for this device as well?

**Comment by Mark-64** [comment]
It is supported. Just choose XRite ColorChecker 24.
Align the 24 patches  with the correspondent side of your Passport

**Comment by bigntallmike** [comment]
> It is supported. Just choose XRite ColorChecker 24.
> Align the 24 patches with the correspondent side of your Passport

I was under the (obviously mistaken) impression that the values of the colour patches were different between the two.

**Comment by johnny-bit** [comment]
Closing since this is non-issue :)
