### ISSUE TITLE
More EXIF tag choices in Collections

### ISSUE THREAD

**Issue by scholzling** [darktable-org/darktable#9971]
**Is your feature request related to a problem? Please describe.**
I am missing many EXIF tags in the picture informations window and the collection function. 
I am using darktable to manage my scanned negatives. I use negadoctor to convert them to positives. I like the fact that i can adjust the settings for one picture and then copy the same settings to all other pictures of the same roll(because i can collect them based on filmroll given by the import folder). But i want to be able to do this on filmtype basis. Because the same filmtype will always have the same basic colorcast and color conversion process. 

Lets say i figure out a better way to adjust the basic conversion of a filmtype. I already imported 50 filmrolls. In the current state of darktable there is no way to filter for the filmtype which i declared in the EXIF data of each picture. I tought the collection function would be able to do that, but it is missing many of EXIF tags i added with [analogExif](http://analogexif.sourceforge.net/help/main-features.php) including film type.

Why does it not include all the tags available in the file. I saw that the issue came up in #7892. There was work on the picture informations window. But i think it was not finished. Also i guess the collections function uses metadata stored in darktables database which was created from exif on import. So this solution wont help my problem.

**Describe the solution you'd like**
I want that all exif tags of a picture are available in the collections function. This would enable a massive improvement on the way collections work. Collections based on: used developer, laboratory, filmtype, metering mode.. anything.

**Alternatives**
I guess an alternative would be a custom luascript which it self looks at the exif data of the original file an somehow filters them for me. But i dont have experience with the functionality of the lua script function.

**Comment by wpferguson** [comment]
One solution could be a lua script that runs on import and scans each image for whatever information you want and then creates tags from that and attaches it to each image.  That would make the data available in the collections module, so that you could sort and find with it.  Can you attach an image (you might have to zip it) that has the EXIF data you want to extract?

**Comment by scholzling** [comment]
Yes this could work too. But I also had in mind that this way on export all exif data could be kept intact. But this sounds like a solution to my proposed issue anyway so yea I will upload a file when I get home.

Von meinem iPhone gesendet

**Comment by scholzling** [comment]
This image is already inverted but it has all the exif information i would be interesed in:

[0016_004.zip](https://github.com/darktable-org/darktable/files/7144628/0016_004.zip)
