### ISSUE TITLE
take basic adjustments module back please!

### ISSUE THREAD

**Issue by fortenew** [darktable-org/darktable#9976]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by fortenew** [comment]
1. I've used basic adjustments module extensivly in my workflow. It was the best and quickest way to apply local changes (EV, Contrast, Highlight compression  in conjuction with mask mechanismus. Without this module i must separatly apply every effect connected to one mask. Not
2. The Highlight compression in this module was for me the best tool to retrieve details in blown out highlights, Far better then that in  shadow@highlights modul which i don't ever use for highlights.
Overall Darktable without this module has taken a large step backwards from my point of view. 
So please, please take it back!

**Comment by johnny-bit** [comment]
The module is simply "deprecated". We never remove modules. Simply enable deprecated module in module groups and ignore deprecation warning.

**Comment by Nilvus** [comment]
And new quick panel access is done to replace basic adjustments as this module had some processing issues and it's more powerful to allow people to choose which sliders from existing modules to use. A minimal set is proposed. As this will not change and you could still use this module if you want (even if we don't recommend it), I close this issue (if needed, you can still answer of course).

**Comment by fortenew** [comment]
Oh. I didn't know that the old modules are hidden there. That saved my workflow. So now i want to highlight that quick panel is not exactly a replacement to me. It has no mask on its own and the highlight compression slider is nowhere to be found.  Nevertheless thank you for the answers.
