### ISSUE TITLE
XMP files always 1 second newer, causes "check for xmp updates" to trigger on every launch

### ISSUE THREAD

**Issue by EdgarVerona** [darktable-org/darktable#9983]
(potentially related to https://github.com/darktable-org/darktable/issues/5847 ?)

**Did you buy darktable from an application store ?**

No, I downloaded it straight from darktable.

**Describe the bug/issue**

I don't know if this is necessarily helpful, but on Windows 10 I am experiencing this exact issue still. Every xmp file is ~1 second newer than the database entry, though the only change occurred during their initial import.

![image](https://user-images.githubusercontent.com/620343/132932580-24156dcb-9389-478c-bfdb-d66e8129976b.png)

At first I thought darktable was just very slow to load, as there's no UI response for several minutes until it finally brings up this dialog.  But then I noticed the timestamp difference and the fact that I haven't changed those XMP files, and when I found this bug it seems to be a very similar issue.

These timestamp differences are happening on a system where both the database and images/xmp files are hosted on a Samba share on a Linux server, but the application is being run from my local windows machine.

(I suppose since my workflow is simple enough - I only plan to do basic editing in darktable itself - I can just turn off the "check for xmp updates at startup" setting since the only thing that should be editing them is darktable, so I'm personally not blocked by this)

**To Reproduce**

(Prerequisite: Darktable installed on windows 10 machine)

1. Created a Samba share on a linux server.
2. Added images to be imported to that samba share, along with XMPs from lightroom
3. On the same samba share, added a new "_darktable" subfolder for the darktable database.
4. Added a Z drive mapping to the samba share on my local windows PC (the one running the darktable application)
4. Launched app with: ""C:\Program Files\darktable\bin\darktable.exe" --library Z:\_darktable\library.db"
5. Used the "import" -> "Add to library..." button to add the images from the samba share.
6. Enabled the "Settings" -> "Storage" -> "look for updated xmp files on startup" checkbox
7. Closed Darktable
8. Reopened darktable, and after several minutes of loading got the window popup above that showed every imported image as having an xmp file 1 second newer than the database's data
9. This condition occurs every time I open Darktable until I disabled the "look for updated xmp files on startup" checkbox.

**Expected behavior**

That the timestamps in both the database and XMP would be identical/matching well enough that the dialog box wouldn't pop up given that they're unchanged since the initial import. (this is probably a terrible suggestion, but what if the database stored timestamp was saved off to be whatever the modified timestamp of the XMP file ends up being after darktable modifies/creates it, that way the source of truth is always the xmp file's date if that turns out to be the root problem?  I don't know if this would have unintended side effects, but it was a thought that popped in my head as an avenue to explore if that'd be useful)

**Screenshots**

![image](https://user-images.githubusercontent.com/620343/132932580-24156dcb-9389-478c-bfdb-d66e8129976b.png)

**Which commit introduced the error**

Unfortunately, I don't know.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0
* OS                : For Darktable: Windows 10, ver. 21H1
* Linux - Distro    : For Samba share server, Proxmox 7.0-11
* (If it matters, the samba share is pointing to a folder on a ZFS mirror setup)

**Comment by Nilvus** [comment]
There's some network issues in Windows that had been fixed (or more precisely introduced as it was not really implemented correctly as far as I know!) and would be in darktable 3.8. So it's probably already fixed and done in actual master. You could see for example those pull requests merged in master:  #9774 and #9903 from @Mark-64. I ping him as he would probably be more precise about that than me.

**Comment by johnny-bit** [comment]
Actually - this is not a darktable bug. Not even os bug. I think the actual issue is that the dates on your client and server (meaning your PC and Linux Samba server) are off by one second (actually it's more than 1sec as seen in screenshots). That means that dates written to db differ to timestapms of files themselves.

For file sharing and networking you HAVE to make sure that both clocks are in sync, that's why we have internet time. Check how to sync windows with nearest NTP server and make sure your linux box uses same server, then make sure that sync service is enabled so clocks do not drift apart too much and you won't have problems.

So... you might want to close this issue :)

**Comment by EdgarVerona** [comment]
Yep, you're right - I had NTP set up on my windows box, but had neglected to set it up on my proxmox server.  I'll give that a shot.

Though would it even need to synchronize between the client and server if there was a single source of truth for file edit time?  Like if the database's last modified date just used the date of the file on the authoritative source - the filesystem's date modified on the given xmp file - there wouldn't be a need to make sure the servers were in lock step.  There'd be just one source of truth for modified date/time.  I don't know if that'd be infeasible for other reasons, but I think it could be worth considering.

**Comment by johnny-bit** [comment]
The dialog you see is the decider for source of truth. This is important when working on shared files across multiple PCs. Sometimes you know you were just playing around on your laptop and you have to omit updated xmps, other times you got to overwrite local changes while on the road... This is expected and this is needed feature IMHO.

**Comment by EdgarVerona** [comment]
Ah yeah, I'd not thought about that scenario.  Makes sense.  Good stuff!  I set up proxmox to use the same time server, though I imagine since they're already out of sync I'm going to have to give it one more long initial load with that dialog to synchronize the dates, but I'll do that later today.  Thanks for this info, I appreciate it!
