### ISSUE TITLE
Build error at soften.cl

### ISSUE THREAD

**Issue by Sanaki** [darktable-org/darktable#9989]
When attempting to compile latest git (build.sh or manual cmake), compilation fails at soften.cl seemingly due to a makefile error.
```
[ 88%] Test-compiling OpenCL program soften.cl
error: unknown argument: '-target'
distcc[21371] ERROR: compile (null) on localhost failed
share/darktable/kernels/CMakeFiles/opencl-program-soften.cl.dir/build.make:73: recipe for target 'share/darktable/kernels/soften.cl.touch' failed
make[2]: *** [share/darktable/kernels/soften.cl.touch] Error 1
CMakeFiles/Makefile2:7921: recipe for target 'share/darktable/kernels/CMakeFiles/opencl-program-soften.cl.dir/all' failed
make[1]: *** [share/darktable/kernels/CMakeFiles/opencl-program-soften.cl.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
```

**Platform**

* darktable version : b174c61bef3c50b3bcebf0e3ff0ef3ffa4832202
* OS                : Linux, kernel 5.4.0-81
* Linux - Distro    : Mint 19.3
* Memory            : 32GB
* Graphics card     : GeForce GTX 1060 6GB
* Graphics driver   : proprietary 470.63.01
* OpenCL installed  : 2.2.11
* Xorg              : 2:1.19.6-1ubuntu4.9
* Desktop           : Cinnamon 4.4.8
* GTK+              : 3.22.30
* gcc               : 11.1.0
* CMAKE_BUILD_TYPE  : RelWithDebInfo
* cmake version     : 3.21.20210831 Kitware/CMake@f94e4b8bb3d5a3403d8612106c3d5fdbe616ca9f

Of possible note (unlikely due to the error in question), `clinfo` provided this tidbit, but I see no way to resolve it offhand:
> NOTE:	your OpenCL library only supports OpenCL 2.1, but some installed platforms support OpenCL 3.0. Programs using 3.0 features may crash or behave unexepectedly

**Comment by parafin** [comment]
Try without distcc.

**Comment by Sanaki** [comment]
No change. Distcc is disabled at the moment anyway, but I removed it from the path entirely and retried just to be certain.
