### ISSUE TITLE
missing osm_gps_map_point_free calls?

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#9992]
I'm seeing that in views/map.c there are various `osm_gps_map_point_new_degrees` calls without the corresponding `osm_gps_map_point_free` call in the same function.

lines in [master](https://github.com/darktable-org/darktable/commit/8dafecacf18d446cd9acf9f60de9aed1d404740e): 1660, 1799, 2201, 2253, 2293, 

Is it ok or must be corrected?

**Comment by johnny-bit** [comment]
My usual recommendaton would be to add frees and test whether that breaks stuff due to double-free ;) If the points are added to list then instead of free for each point you have to use g_list_free_full and specify osm_gps_map_point_free as a free function call

**Comment by phweyland** [comment]
> Is it ok or must be corrected?

Good catch.
1660, 1799, should be freed.
2201,  2253, 2262, 2293 are used in some osm objects and should not be freed.
