### ISSUE TITLE
Tone equalizer fails to update luminance mask and histogram

### ISSUE THREAD

**Issue by paolodepetrillo** [darktable-org/darktable#9995]
If a tone equalizer parameter affecting the luminance mask is changed, and is then immediately changed back to its previous setting, then the luminance mask and histogram do not update, and become out of sync with the module parameters. This happens because the luminance mask is only updated when process() is called, and it is not called if the pixelpipe cache contains a matching entry corresponding to the previously used settings.

To reproduce:
Go to the masking tab. Reset the module.
Change the mask exposure compensation and observe that the gray bar moves.
Reset the module and observe that the gray bar does not move, even though mask exposure compensation reset to 0.

Or:
Change the luminance estimator and observe that the gray bar moves.
Change the luminance estimator back to the previous setting and observe that the gray bar does not move.

I think that this explains why if you keep clicking the auto exposure compensation button repeatedly, it cycles through a few different values instead of just toggling back and forth between 0 EV and the correct value.

The problem occurs with v3.6.0 and the latest 3.7.0+1041~gb174c61be. I am testing on Arch Linux with OpenCL enabled.

**Comment by Mark-64** [comment]
> I think that this explains why if you keep clicking the auto exposure compensation button repeatedly, it cycles through a few different values instead of just toggling back and forth between 0 EV and the correct value.

Yeah, this has been bugging me a lot

**Comment by Mark-64** [comment]
Adding a preview refresh at the end of `gui_changed()` fixes the luminance bar and histogram update issue for me.
I am not sure if this is an acceptable fix in terms of performance, though.

```
void gui_changed(dt_iop_module_t *self, GtkWidget *w, void *previous)
{
  dt_iop_toneequalizer_gui_data_t *g = (dt_iop_toneequalizer_gui_data_t *)self->gui_data;
  if(w == g->method     ||
     w == g->blending   ||
     w == g->feathering ||
     w == g->iterations ||
     w == g->quantization)
  {
    invalidate_luminance_cache(self);
  }
  else if (w == g->details)
  {
    invalidate_luminance_cache(self);
    show_guiding_controls(self);
  }
  else if (w == g->contrast_boost || w == g->exposure_boost)
  {
    invalidate_luminance_cache(self);
    dt_bauhaus_widget_set_quad_active(w, FALSE);
  }
  dt_iop_refresh_preview(self);
}
```

However, this does not solve the other issue of exposure compensation picker, cycling through different values.

**Comment by paolodepetrillo** [comment]
I think the exposure compensation picker cycling is the same issue. It looks like the intended behavior is that when it's clicked, if the exposure boost is nonzero it resets it to zero, and if it is zero it adds an offset calculated from the current histogram.

On the first click, it works correctly, starting from 0 EV and applying an offset, based on the histogram for 0 EV.
On the second click, it sets the exposure boost back to 0 EV but it doesn't update the histogram because of a cache hit for the parameters with the 0 EV setting.
On the third click, it calculates the exposure boost incorrectly based on the out of date histogram that has the offset applied, rather than the 0 EV histogram that it should use.

Putting `dt_iop_refresh_preview(self);` at the end of `invalidate_luminance_cache` seems to fix the problem in all cases, but I'm not sure if that causes any performance issues.

**Comment by Mark-64** [comment]
Yes, it seems necessary, either at the end of invalidate_luminance_cache() or immediately after each call to it (it is called 4 times).
Also, there are other oddities in the way the pickers in TE behave, when you switch on/off the module with active pickers etc.
The pickers callback must be reviewed.

**Comment by Mark-64** [comment]
Ok, I think we have a decent fix for all issues, so I can propose a PR and we continue the discussion there
