### ISSUE TITLE
Tone equalizer pickers inconclusive/unstable

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#9997]
**To Reproduce**
1. Download the raw from https://discuss.pixls.us/uploads/short-url/3x7TCchjeXvvBmtsM1eQYD1lEyo.NEF
2. Restart darktable and import
3. Enable Tone EQ
4. Try the pickers on the advanced tab several times

**Expected behavior**
Pickers pick always the same value (1st click: pick a value -- 2nd click: reset -- 3rd click: pick same value as in 1st click)

**Screencast**
![tone-eq-unstable](https://user-images.githubusercontent.com/3177739/133069732-d68030c1-f923-4e13-8fba-9ea776e85697.gif)

**Which commit introduced the error**
Unknown; behaviour is the same this with 3.6.0 on Windows, no OpenCL as well as 3.7.0+1047~gf22f9ec62 on Linux with OpenCL

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0 as well as 3.7.0+1047~gf22f9ec62 
* OS                : Linux kernel 5.11.0, Windows 10
* Linux - Distro    : Ubuntu 21.04
* Memory            : 16 GB (Windows), 64 GB (Linux)
* Graphics card     : none (Windows), NVidia 1060/6GB (Linux)
* CMAKE_BUILD_TYPE  : Release on Windows, RelWithDebugInfo on Linux

**Additional context**
Not always reproducible when darktable is not restarted before import.

**Comment by Mark-64** [comment]
This is connected to #9995, but not the same.
I am looking into both

**Comment by kofa73** [comment]
I think there's still something strange.
If I click at a 'normal rate' (click, wait for update, click again, wait for update), it goes nicely between 0 and a stable value.
However, clicking like made, it's possible to trigger 3 different values (probably a race condition?).
0 EV value:
![image](https://user-images.githubusercontent.com/3177739/133578702-ad66a2e1-2a76-4e54-bafe-bb81651f7128.png)
Normal value (with a bit of wait):
![image](https://user-images.githubusercontent.com/3177739/133578817-78e8b884-a3a0-4946-bd4e-6436c9defaa9.png)
Clicking like crazy:
![image](https://user-images.githubusercontent.com/3177739/133578872-0cb32cbf-79f9-4e43-8a22-1d57921ba44d.png)

**Comment by Mark-64** [comment]
Ok, I might have a look, before or after merge of #9998

**Comment by Mark-64** [comment]
@kofa73 can you please test again #9998 ?
